### ISSUE TITLE
Viafree.se - Lyxfällan episode 13 will stop after a few seconds

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1007]
When i try to download Lyxfällan it will stop after a few seconds but i can watch the whole episode on [Viafree.se](https://www.viafree.se/program/livsstil/lyxfallan/sasong-25/avsnitt-13)
Why can't i download it?

```
INFO: Url: https://www.viafree.se/program/livsstil/lyxfallan/sasong-25/avsnitt-13
INFO: Outfile: lyxfallan.s25e13-984704-viaplay.srt
WARNING: File (lyxfallan.s25e13-984704-viaplay.srt) already exists. Use --force to overwrite
INFO: Selected to download hls, bitrate: 2519
INFO: Outfile: lyxfallan.s25e13-984704-viaplay.ts
[015/253][======........................................................................................................] ETA: 0:02:26
Muxing lyxfallan.s25e13-984704-viaplay.ts into lyxfallan.s25e13-984704-viaplay.mp4
INFO: Muxing lyxfallan.s25e13-984704-viaplay.ts into lyxfallan.s25e13-984704-viaplay.mp4
Muxing done, removing the old file.
INFO: Muxing done, removing the old file.
```

svtplay-dl 2.1+11.g1c302d4

**Comment by myowncloudservice** [comment]
Hi,

I try download the episode 13 of Lyxfällan from viafree.se with this link and it works correctly.

https://www.viafree.se/program/livsstil/lyxfallan/sasong-25/avsnitt-13


I use the latest master version of SVTPlay-dl for Windows

**svtplay-dl 2.1-14-g72143b7**

**You can download it from this link**
https://ci.appveyor.com/api/buildjobs/hnxs008g16owwhll/artifacts/svtplay-dl.zip

**Comment by granbom** [comment]
I tried with svtplay-dl **2.1-14-g72143b7** (python3.6) on Ubuntu and I get the same error as @Sopor- 
The 15th segment return a 404 response.

`
_make_request: https://mtgxse04-vh.akamaihd.net:443 "GET /i/open/20xxxxxx/2052xxxx/205255xx/20525511/bb62a56622ac29ec011bacf83bd07ee3_20525511_008670_20181126T122356_,150,300,600,1200,2400,.mp4.csmil/segment15_4_av.ts?null=0&id=AgBT6Yo7U+lSt+EfB1zWJiflydTD2n0FaYRwueJgdVWftLjIqT6R2X3lUX5qYeZ17F1kpMsJxEl6og%3d%3d&hdntl=exp=1544057185~acl=/*~data=hdntl~hmac=7e85b2bef940ed6dcc84a63e24d21db1f3ec960031ed0d6c180eb111f388465c HTTP/1.1" 404 175
`

**Comment by myowncloudservice** [comment]
Very strange, I have download it with no errors and I have look at the movie to and It's working correctly for me!

**Comment by Sopor-** [comment]
I have tried latest master too and i get the same error.

**Comment by spaam** [comment]
i cant reproduce it now :(

**Comment by Sopor-** [comment]
I tried it for a few minutes aga and the same thing happen...
```
INFO: Outfile: lyxfallan.s25e13-984704-viaplay.srt
INFO: Selected to download hls, bitrate: 2519
INFO: Outfile: lyxfallan.s25e13-984704-viaplay.ts
[015/253][======........................................................................................................] ETA: 0:02:37
INFO: Muxing lyxfallan.s25e13-984704-viaplay.ts into lyxfallan.s25e13-984704-viaplay.mp4
INFO: Muxing done, removing the old file.
```

**Comment by spaam** [comment]
you get `404` too like @granbom  on the file?

**Comment by Sopor-** [comment]
```
[015/253][======........................................................................................................] ETA: 0:02:09DEBUG [1544572055.0665097] /usr/local/lib/python3.5/dist-packages/svtplay_dl-2.1+14.g72143b7-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://mtgxse04-vh.akamaihd.net/i/open/20xxxxxx/2052xxxx/205255xx/20525511/bb62a56622ac29ec011bacf83bd07ee3_20525511_008670_20181126T122356_,150,300,600,1200,2400,.mp4.csmil/segment15_4_av.ts?null=0&id=AgAf0HUiU+lSro1MEFxzMI5wfY0DTCE5Pf57zcyfTpOyBZBIn6GDNh8Vn9UNd2Hl4fk2lv8+F6JPJg%3d%3d&hdntl=exp=1544658445~acl=/*~data=hdntl~hmac=a5c07c8c1f022600a27aa7d5e18739d71eeab924da3de89e666c9526d00e09e6'
DEBUG [1544572055.1181104] /usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py/_make_request: https://mtgxse04-vh.akamaihd.net:443 "GET /i/open/20xxxxxx/2052xxxx/205255xx/20525511/bb62a56622ac29ec011bacf83bd07ee3_20525511_008670_20181126T122356_,150,300,600,1200,2400,.mp4.csmil/segment15_4_av.ts?null=0&id=AgAf0HUiU+lSro1MEFxzMI5wfY0DTCE5Pf57zcyfTpOyBZBIn6GDNh8Vn9UNd2Hl4fk2lv8+F6JPJg%3d%3d&hdntl=exp=1544658445~acl=/*~data=hdntl~hmac=a5c07c8c1f022600a27aa7d5e18739d71eeab924da3de89e666c9526d00e09e6 HTTP/1.1" 404 176
```

**Comment by Sopor** [comment]
Update: I still get the same error here :(
