### ISSUE TITLE
Viafree ERROR: No videos found. Video not found

### ISSUE THREAD

**Issue by Bengt-H** [spaam/svtplay-dl#1023]
python C:\svtplay-dl\svtplay-dl --verbose --q=1425 --flexible-quality=350 --subtitle --output=the-good-doctor-s02e09 https://www.viafree.se/program/drama/the-good-doctor/sasong-2/avsnitt-9
DEBUG [1544772659.752125] C:\svtplay-dl\svtplay-dl\svtplay_dl\utils\getmedia.py/get_media: version: 0+unknown
DEBUG [1544772659.752125] C:\svtplay-dl\svtplay-dl\svtplay_dl\service\__init__.py/__init__: service: viaplay
DEBUG [1544772659.752125] C:\svtplay-dl\svtplay-dl\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/drama/the-good-doctor/sasong-2/avsnitt-9'
DEBUG [1544772659.76775] C:\Python34\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se
DEBUG [1544772660.299] C:\Python34\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/drama/the-good-doctor/sasong-2/avsnitt-9 HTTP/1.1" 200 None
DEBUG [1544772660.314625] C:\svtplay-dl\svtplay-dl\svtplay_dl\utils\http.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/images'
DEBUG [1544772660.33025] C:\Python34\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): playapi.mtgx.tv
DEBUG [1544772660.45525] C:\Python34\lib\site-packages\urllib3\connectionpool.py/_make_request: http://playapi.mtgx.tv:80 "GET /v3/videos/images HTTP/1.1" 404 25
ERROR [1544772660.45525] C:\svtplay-dl\svtplay-dl\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Video not found

**Comment by drejjmit** [comment]
Same. Maybe because a free account is needed.

**Comment by jackpryan** [comment]
So is there a way to put in your viafree credentials into the commandline ?

**Comment by Bengt-H** [comment]
No, the problem is in the translation from episodenumber ti video id.
The video url "https://www.viafree.se/program/drama/the-good-doctor/sasong-2/avsnitt-9" doesn't work, but "https://www.viafree.se/program/drama/the-good-doctor/sasong-2/984586" works fine.

**Comment by jackpryan** [comment]
Thanks Bengt-H, that works! Great work-around! Hopefully the devs can implement a fix for this!

**Comment by TheBishopSweden** [comment]
Where can I find the video id that is mentioned in this thread?
my command line looks this:
svtplay-dl -S https://www.viafree.se/program/drama/navy-ncis/sasong-16/avsnitt-3

**Comment by drejjmit** [comment]
Open Developer tools (Ctrl+Shift+I in Chrome). Press **Network**. Go the the video. Type **stream-progress** in **Filter**. Video ID is shown. https://www.viafree.se/program/drama/navy-ncis/sasong-16/984333 in this case

**Comment by Bengt-H** [comment]
Yesss !
Thank you magic75

**Comment by yabbah** [comment]
Can they have changed again? I cant find that video ID for https://www.viafree.se/program/drama/advokatbyra-aber-bergen/sasong-1/avsnitt-1 in dev-tools. :(

**Comment by TV4Profilen** [comment]
The above work-around seems not to be working anymore :( 
Tried:  https://www.viafree.se/program/livsstil/lyxfallan/sasong-26/avsnitt-13
Couldn't find "stream-progress" in network section

**Comment by TV4Profilen** [comment]
Edit
Lyxfällan works with this version:
svtplay-dl 2.1-53-gd33186e

https://ci.appveyor.com/project/spaam/svtplay-dl/build/artifacts
