### ISSUE TITLE
Tv4 subtitle tv4 not working on some programs

### ISSUE THREAD

**Issue by pamm01** [spaam/svtplay-dl#1050]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by pamm01** [comment]
Trying to download subtitle, not working:

svtplay-dl -S --verbose  https://www.tv4play.se/program/the-truth-about-the-harry-quebert-affair/11775564
DEBUG [1550175924.9355392] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1550175924.937196] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1550175924.9372838] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/the-truth-about-the-harry-quebert-affair/11775564'
DEBUG [1550175924.9394913] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se
DEBUG [1550175925.1837406] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/the-truth-about-the-harry-quebert-affair/11775564 HTTP/1.1" 200 None
DEBUG [1550175925.1882067] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/11775564?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1550175925.1897564] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net
DEBUG [1550175925.41036] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/11775564?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 200 915
DEBUG [1550175925.4111326] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP).m3u8'
DEBUG [1550175925.4126213] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se
DEBUG [1550175925.5456493] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP).m3u8 HTTP/1.1" 200 3012
DEBUG [1550175925.5514095] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000.m3u8'
DEBUG [1550175925.566145] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000.m3u8 HTTP/1.1" 200 48360
DEBUG [1550175925.5861616] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1550175925.5875328] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se
DEBUG [1550175925.6488388] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 57
DEBUG [1550175925.8598568] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1550175925.8746912] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 57
DEBUG [1550175926.1003373] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-2.webvtt'
DEBUG [1550175926.1148417] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-2.webvtt HTTP/1.1" 200 58
DEBUG [1550175926.1156187] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-3.webvtt'
DEBUG [1550175926.129672] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/f2a49/e325lmfoetz(11775564_ISMUSP).ism/e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-3.webvtt HTTP/1.1" 200 119
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 176, in get_one_media
    options_subs_dl(subfixes)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 171, in options_subs_dl
    subs[0].download()
  File "/usr/lib/python3/dist-packages/svtplay_dl/subtitle/__init__.py", line 58, in download
    data = self.wrstsegment(subdata)
  File "/usr/lib/python3/dist-packages/svtplay_dl/subtitle/__init__.py", line 295, in wrstsegment
    first = str2sec(ha.group(1)) + time
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Bengt-H** [comment]
As far as i can see there seem to be a problems with the parsing and concatenating of the different segments of the split 'webvtt' files if they contain empty lines in unexpected places.

In the example above the offending segment (the 3rd, "e325lmfoetz(11775564_ISMUSP)-textstream_swe=3000-3.webvtt") looks like this:

"WEBVTT
X-TIMESTAMP-MAP=MPEGTS:1620000,LOCAL:00:00:00.000

00:00:00.040 --> 00:00:04.000

JUNI 1975
SOMMERDALE, MAINE

"

Another example is the offending 10th segment of the subtitle for the 7th episode of "Keeping Faith" from TV4 Play "https://www.tv4play.se/program/keeping-faith/11789441" where it stops with the error: "IndexError: list index out of range"

"WEBVTT
X-TIMESTAMP-MAP=MPEGTS:4140000,LOCAL:00:00:00.000

00:00:01.640 --> 00:00:04.000

ONSDAG MORGON

"

**Comment by dksx** [comment]
For what is worth, removing the segment part after 3000 and sending a GET request returns the whole subtitle file. 
e.g for the episode mentioned above

https://lbs-usp-hls-vod.cmore.se/vod/b880f/34sae52ygch(11789441_ISMUSP).ism/34sae52ygch(11789441_ISMUSP)-textstream_swe=3000.webvtt

**Comment by spaam** [comment]
this is fixed in master. will releasing 2.2 tomorrow or the day after.
