### ISSUE TITLE
Why bloat the filename with SHA256 encrypted video ID?

### ISSUE THREAD

**Issue by iwconfig** [spaam/svtplay-dl#1051]
What is the purpose of doing this? 
https://github.com/spaam/svtplay-dl/blob/dcbf6a8a0ee373a32b091492352787f360d508ab/lib/svtplay_dl/service/svtplay.py#L235

Is it necessary to hash the video ID? Can't it just be left as is? Having access to the decrypted video ID is much simpler, and I don't have to know the decrypted video ID beforehand to be able to compare them

**Comment by spaam** [comment]
the issue was because it had `-` in the name and we used same character as a dilimiter between each section of the name. like NAME-ID-SERVICE.EXT.  i thought it was a bit easier to use this for some kind of unique name like `kalle-249ae42-svtplay.mp4` instead of like `kalle-a3-24523-svtplay.mp4`

**Comment by spaam** [comment]
easier and easier.  more like not adding so much dashes in the filename. i think that looks better and we only use seven digits of the hash.

**Comment by iwconfig** [comment]
I thought so too. Fair enough. In the future, maybe allow a decrypted ID with `--no-hash` or something. :smile:  Not a pressing issue for now, i was just curious as to why. Especially since i've started doing [backups of all the metadata.](https://github.com/iwconfig/svtplay-data)

**Comment by spaam** [comment]
yeah maybe . no one really said anything about it before so :)
