### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by p0trzebi3** [spaam/svtplay-dl#1062]
### svtplay-dl versions:

svtplay-dl 2.1

### Operating system and Python version:

Windows 10, python35.dll

### What is the issue:

svtplay-dl https://www.svtplay.se/video/21375862/ishockey-vm-damer/ishockey-vm-damer-4-apr-11-20

DEBUG [1554503724.3245869] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1554503724.333101] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1554503724.3341012] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/21375862/ishockey-vm-damer/ishockey-vm-damer-4-apr-11-2011-20'
DEBUG [1554503724.3436177] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1554503726.9955108] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21375862/ishockey-vm-damer/ishockey-vm-damer-4-apr-11-2011-20 HTTP/1.1" 301 97
DEBUG [1554503727.1958547] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21375862/ishockey-vm-damer/ishockey-vm-damer-4-apr-11-20 HTTP/1.1" 200 36444
DEBUG [1554503727.2860007] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391889-001A'
DEBUG [1554503727.2930126] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1554503727.5153923] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1391889-001A HTTP/1.1" 200 734
DEBUG [1554503727.520901] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3c62e43d-bf87-4577-a3d6-097b9f528471/lowbw.mpd'
DEBUG [1554503727.5264096] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1554503727.7452662] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3c62e43d-bf87-4577-a3d6-097b9f528471/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1554503727.7522776] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1554503727.975649] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1554503727.9871676] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed3.cdn.svt.se:80
DEBUG [1554503728.155972] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed3.cdn.svt.se:80 "GET /d0/se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/lowbw.mpd HTTP/1.1" 200 2962
DEBUG [1554503728.1584764] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd'
DEBUG [1554503728.2351005] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd HTTP/1.1" 302 0
DEBUG [1554503728.315231] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd HTTP/1.1" 302 0
DEBUG [1554503728.4264362] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed3.cdn.svt.se:80 "GET /d0/se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd HTTP/1.1" 200 4263
DEBUG [1554503728.4289405] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-1k.akamaized.net/se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3c62e43d-bf87-4577-a3d6-097b9f528471%2Fmanifest.mpd'
DEBUG [1554503728.4349496] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-1k.akamaized.net:80
DEBUG [1554503728.6673405] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-1k.akamaized.net:80 "GET /se/20190404/3c62e43d-bf87-4577-a3d6-097b9f528471/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3c62e43d-bf87-4577-a3d6-097b9f528471%2Fmanifest.mpd HTTP/1.1" 200 837
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
Have you tried latest master? You can download it [here](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23351676/artifacts).

**Comment by p0trzebi3** [comment]
> 
> 
> Have you tried latest master? You can download it [here](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23351676/artifacts).

That did it, thx.
