### ISSUE TITLE
TV4Play - Subtitles are delayed

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1063]
### svtplay-dl versions:

svtplay-dl 2.1-52-gbe21f7d

### Operating system and Python version:

Windows 10

### What is the issue:

Something is wrong with the subtitles on TV4. Some of the subtitles are too late and this make them only be visible for a very short time. Others will work perfekt. I don't know the reason but i have now compared it with TV4Play.se to verify that something is wrong.
I have downloaded different programs (Biggest loser, Border patrol, Stockholmspolisen) and i see the same issue in all of them.
Here is one example:
```
42
00:03:33.000 --> 00:03:33.440
Berätta vad ni gjorde i Thailand.
```
You can see that this subtitle is too short and sometimes they are even shorter.

**Comment by spaam** [comment]
url?

**Comment by Sopor** [comment]
[Biggest loser](https://www.tv4play.se/program/biggest-loser/11886774)
[Border patrol](https://www.tv4play.se/program/border-patrol/3964261)
[Stockholmspolisen](https://www.tv4play.se/program/stockholmspolisen/11826130)

You should be able to take any episodes...

**Comment by spaam** [comment]
hmm thing would be so much simpler if we skip subs.

**Comment by Sopor** [comment]
Yes, but TV4 use external subs on all programs and subs can be very useful for people that are deaf. I'm not deaf but i still use subtitles on swedish programs. When watching TV at night i need to have a low volume. So subtitles are very useful even if they make a lot of extra work for you.

**Comment by spaam** [comment]
i have pushed a fix to master.

**Comment by Sopor** [comment]
That seems to works perfect. Nice work @spaam
