### ISSUE TITLE
Viafree.fi ERROR: No videos found

### ISSUE THREAD

**Issue by ikoutone** [spaam/svtplay-dl#1066]
### svtplay-dl versions:
2.1

### Operating system and Python version:
Windows 10
python --version
'python' is not recognized as an internal or external command,
operable program or batch file.

### What is the issue:

svtplay-dl.exe --verbose https://www.viafree.fi/ohjelmat/komedia/adult-swim-metalocalypse/kausi-1/jakso-18
DEBUG [1555667280.857279] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1555667280.8582506] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viaplay
DEBUG [1555667280.8592486] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.fi/ohjelmat/komedia/adult-swim-metalocalypse/kausi-1/jakso-18'
DEBUG [1555667280.8612432] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.fi:443
DEBUG [1555667282.429051] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.fi:443 "GET /ohjelmat/komedia/adult-swim-metalocalypse/kausi-1/jakso-18 HTTP/1.1" 200 None
ERROR [1555667282.434062] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find video file for: https://www.viafree.fi/ohjelmat/komedia/adult-swim-metalocalypse/kausi-1/jakso-18

**Comment by Goldfire86** [comment]
I have this issue as well, sorry if this is the wrong place to put this. I'm using viafree.se, but I'm seeing the same issue as the OP viafree.fi site as well.

Here's my output from youtube-dl:

```
youtube-dl.exe --verbose https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2019.04.07
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92738-g3a36b0c4b8, ffprobe N-92738-g3a36b0c4b8
[debug] Proxy map: {}
[Viafree] avsnitt-1: Downloading webpage
WARNING: [Viafree] avsnitt-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 327 (char 326)
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 529, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\tvplay.py", line 447, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpspbwh57p\build\youtube_dl\extractor\common.py", line 1004, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Here's my output from svtplay-dl:

```
svtplay-dl.exe https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1 --verbose
DEBUG [1555689078.81813] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1555689078.81813] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viaplay
DEBUG [1555689078.81813] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1'
DEBUG [1555689078.81813] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1555689079.648636] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/reality/highway-patrol/sasong-9/avsnitt-1 HTTP/1.1" 200 None
ERROR [1555689079.708556] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find video file for: https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1
```

This happens for all links. I'd be very grateful to have this working so I can download some specific episodes that I'm missing of shows that are tricky to get now.

**Comment by Sopor** [comment]
I can't check viafree.fi because of the GEO block. Have you tried latest [master](https://ci.appveyor.com/api/buildjobs/8xgn2cfb0amdhqhs/artifacts/svtplay-dl.zip)?

**Comment by Sopor** [comment]
@Goldfire86 latest master will work for you
```
svtplay-dl.exe https://www.viafree.se/program/reality/highway-patrol/sasong-9/avsnitt-1
INFO: Selected to download hls, bitrate: 2495
INFO: Outfile: highway-patrol.s09e01-984539-viaplay.ts
[010/130][======..........................................................................] ETA: 0:00:25
```

**Comment by Goldfire86** [comment]
@Sopor  Thank you very much, appreciate it.

**Comment by ikoutone** [comment]
The latest master seems to work. Thank you!
