### ISSUE TITLE
MACOS 10.9 brew install ffmpeg

### ISSUE THREAD

**Issue by noob403** [spaam/svtplay-dl#1067]
I try to install the following  
"brew install ffmpeg"

libbluray: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew Cask:
  brew cask install homebrew/cask-versions/java8
You can download from:
  https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

SOOOOOOO: it fails I try agian by installing 
  "brew cask install homebrew/cask-versions/java8"
that falis too. 

"libbluray: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew Cask:
  brew cask install homebrew/cask-versions/java8
You can download from:
  https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
MacBook-Pro:~ PD$ brew cask install homebrew/cask-versions/java8
Error: Cask 'java8' is unavailable: '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions/Casks/java8.rb' does not exist.

I still cant make it work since ffmpeg lacks java , and the java8 is missing. 

Thanks for some help 
/Noob403

### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by granbom** [comment]
Hi @noob403 
ffmpeg doesn't need java per say. But building "libbluray" does.

Normally brew have ready made binaries (called bottles) but they are macOS version dependent and since macOS 10.9 isn't supported anymore by brew, it will try to build everything locally on your computer instead of using bottles. (Apple ended support for 10.9 in September 2016, so upgrading your OS is a good idea regardless)

If your hardware is less than 10 years old, you should be able to upgrade to macOS 10.13 (at least) which is still supported and these type of issues will disappear.

If your hardware is older than 10 years you will still get the same issues, since 10.11 is the lasts macOS that is supported then, and brew (as well as Apple) doesn't support 10.11 anymore either.

**Comment by noob403** [comment]
@granbom 
Thanks for the heads up. I don't want to upgrade to 10.13. 
I  just wanna know if there are any solutions to this or not. 
It all worked till yesterday when I by mistake erase it all.

**Comment by noob403** [comment]
brew cask install java8? java link is dead any other solutions folks?

**Comment by granbom** [comment]
@noob403 any reason for not upgrading to 10.13?

Links and most things might not work with brew since you are using an OS that hasn't been supported for years.

https://www.youtube.com/watch?v=Jwpg-AwJ0Jc

**Comment by noob403** [comment]
@granbom well for the starters disk utility in High Sierra sucks. Try to partition a USB drive.  Beside that it makes a macbook pro from 2011 i7 so hot that it is more or less useless to use. Battery drain is like crazy. I use both of them but 10.9 is more reliable one. I just need the java to work somehow.

**Comment by granbom** [comment]
@noob403 ok sorry to hear. I have a MacBook Air 2011 running 10.13 without fan issues.
If disk utility is different or unusable, use something else maybe?

**Comment by granbom** [comment]
@noob403 you don't need Java to install either svtplay-dl or ffmpeg. You need java to compile one part of ffmpeg, but exclude libbluray instead when compiling ffmpeg. ffmpeg (or VLC and so on) use it to be able to read from a blu-ray player on your computer.

**Comment by Sopor** [comment]
This can't be [used](https://evermeet.cx/ffmpeg/)?

**Comment by noob403** [comment]
@Sopor it may sound dumb but since I am a noob, how do I install that ?is a sideload? or something i can install via brew?

**Comment by noob403** [comment]
@granbom it is all greek to me , but thanks you for expalning.

**Comment by noob403** [comment]
this command work like a charm , just follow the instructions if you miss anything.  just type:
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
