### ISSUE TITLE
Dplay.se - How to copy URL from the new layout?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1069]
It seems that Dplay have been changing layout so how can i now get the URL to download an [episode](https://www.dplay.se/program/sofias-anglar)? I don't want to open the `Inspect elements` everytime i want to copy a URL :(

**Comment by niclasnj** [comment]
Where do you find the URL when you open the inspect elements?

**Comment by Sopor** [comment]
I haven't, but i assumed it was the only way to get it.

**Comment by Sopor** [comment]
It seems to be quite easy to get those URLs even if you have to manually change them ...

If you want to download S10E16 from Ullared `https://www.dplay.se/program/ullared` the URL will be `https://www.dplay.se/videos/ullared/ullared-1016`

If you want to download S02E11 from Södertäljepolisen `https://www.dplay.se/program/sodertaljepolisen` the URL will be `https://www.dplay.se/videos/sodertaljepolisen/sodertaljepolisen-210`

**Comment by Sopor** [comment]
When downloading many episodes it can sometimes be quiet boring to copy and paste. So now when dplay don't add unique numbers to the path it would be great if svtplay-dl worked like this:

`svtplay https://www.dplay.se/videos/sodertaljepolisen`
enter season and episode: 201-210 310 405 501-610
This should download season 2 episodes 01 to 10, season 3 episode 10, season 4 episode 05 and season 5 episode 01 to season 6 episode 10.

This should at least work with Dplay and Viafree, but SVTPlay use these unique number 21973062 so that won't be possible. I believe `-A` is not working either so maybe this could be an alternative way to download the whole season or even the whole series ...

**Comment by orjano** [comment]
It seems that the url suggestion above was changed 7-14 days ago. https://www.dplay.se/videos/ullared/ullared-1018 worked great up to episode 18, episode 19-20 does not work with this url format. Have anyone found a way to extract the correct url from dplay.se?

**Comment by Sopor** [comment]
They have change it, E20 = https://www.dplay.se/videos/ullared/ullared-72523

**Comment by orjano** [comment]
How do you find the video ID?

**Comment by Sopor** [comment]
I have no idea what they have done here...
E19 = https://www.dplay.se/videos/ullared/ullared

**Comment by Sopor** [comment]
I cheat :)

I use https://www.playpilot.com

**Comment by Bengt-H** [comment]
To get Ullared S10e19 it worked with the url  https://www.dplay.se/videos/ullared/72519

**Comment by Sopor** [comment]
In Firefox i start the video with the Inspect element open (F12) and click on the XHR filter. The number in red is the number to add.

![image](https://user-images.githubusercontent.com/5789283/59048558-5a179180-8886-11e9-8232-df661121e950.png)

**Comment by trixxitrixxi** [comment]
@Sopor used inspector and found the same link, did not work.
But the link from Playpilot did work without a problem.

**Comment by SYSophie** [comment]
@trixxitrixxi @Sopor Playpilot is sometimes scraping the wrong URL. At this point I would suggest that people use tv.nu to get the full path. Or better if none of these work you can extract the full from the disco-api.

**Comment by Sopor** [comment]
@trixxitrixxi it is working for me. You must do something wrong...
```
svtplay-dl.exe https://www.dplay.se/videos/sodertaljepolisen/97918
INFO: Selected to download hls, bitrate: 6532
INFO: Outfile: sodertaljepolisen.s03e02.bengaler.pa.studentflak.tvingar.polisen.att.agera-97918-dplay.audio.ts
[105/251][=================================...............................................] ETA: 0:00:06
```

![image](https://user-images.githubusercontent.com/5789283/63855281-584dfd80-c99f-11e9-9339-168cfe8440a9.png)

Did you replaced `program` with `videos` in the URL?

**Comment by trixxitrixxi** [comment]
> 
> 
> @trixxitrixxi it is working for me. You must do something wrong...
> 
> ```
> svtplay-dl.exe https://www.dplay.se/videos/sodertaljepolisen/97918
> INFO: Selected to download hls, bitrate: 6532
> INFO: Outfile: sodertaljepolisen.s03e02.bengaler.pa.studentflak.tvingar.polisen.att.agera-97918-dplay.audio.ts
> [105/251][=================================...............................................] ETA: 0:00:06
> ```
> 
> ![image](https://user-images.githubusercontent.com/5789283/63855281-584dfd80-c99f-11e9-9339-168cfe8440a9.png)
> 
> Did you replaced `program` with `videos` in the URL?

fixed it, i missed the "/videos/" and used the url without. thx

**Comment by Sopor** [comment]
Another way is to use the `--get-url` like this:
`svtplay-dl.exe -A -g https://www.dplay.se/program/sodertaljepolisen`

This will show the URL:
```
INFO: Url: https://www.dplay.se/videos/sodertaljepolisen/bengaler-pa-studentflak-tvingar-polisen-att-agera
https://dplaynordics-vod-33.akamaized.net/dplaydni/87387/0/hls/8801959004/exp=1567098940~acl=%2f*~data=hdntl~hmac=cb43b2629f49533206222801cdc05df707299c4c343c8cd13b475c1ca012b924/913062852-prog_index.m3u8?hdntl=exp=1567098940~acl=/*~data=hdntl~hmac=cb43b2629f49533206222801cdc05df707299c4c343c8cd13b475c1ca012b924&version_hash=8b285f40
```

To download:
```
svtplay-dl.exe https://www.dplay.se/videos/sodertaljepolisen/bengaler-pa-studentflak-tvingar-polisen-att-agera
```

**Comment by niclasnj** [comment]
another way to do it is to search for the episode. If you dont know the name just start the episode and then copy/paste it into search. From there you can copy the url!!!

**Comment by Sopor** [comment]
@niclasnj Yes, that seems to work too 👍

**Comment by wheee2000** [comment]
Thanks!!
Does anyone know the video URL for dplay.DK ?
e.g. https://www.dplay.dk/videos/politijagt/93270 does not work, like it does with dplay.se

Thanks

**Comment by niclasnj** [comment]
@Sopor  how can you cheat with https://www.playpilot.com you cant download from it, right?

**Comment by spaam** [comment]
it works using -A to download. but you will download the whole show..

**Comment by casper** [comment]
If I try to download anything I get an error "Need the 'st' cookie to work". How do I fix that?

**Comment by spaam** [comment]
@casper https://github.com/spaam/svtplay-dl/issues/1239#issuecomment-693010838
i should document this somewhere else.. 🤔

**Comment by casper** [comment]
That would be nice 👍 I tried my luck with developer tools on Chrome. Found some cookies, but none of them named st.

![image](https://user-images.githubusercontent.com/25386/94456500-39cabf00-01bc-11eb-8c1f-7e87a955ee95.png)

**Comment by spaam** [comment]
Did you login to the site? 🤔

**Comment by casper** [comment]
Yes. But I am on the free plan. Maybe I need a subscription? Hmm..

**Comment by spaam** [comment]
Hmm strange. Can you check the page i had in the screenshot? 🤔

**Comment by casper** [comment]
Ok. I found this cookie in Firefox, but not in Chrome. Even if I log in on both. But this website seems extremely buggy. At least on Chrome I get strange errors from their login page. Maybe it fails to give me the st cookie on Chrome because of these bugs.

But now I have it. I have to give it to svtplay-dl on the command line? Or can I use a cookie.txt file somehow?
