### ISSUE TITLE
New svtplay material causes svtplay-dl to crash

### ISSUE THREAD

**Issue by EmmW** [spaam/svtplay-dl#1077]
Problem: Older svtplay material can be downloaded, more recent cannot (svtplay-dl crashes), even though everything seems to be up-to-date:

- Mac OS 10.12.6
- Homebrew 2.1.1
- svtplay-dl 2.1
- Python 2.7.16
- ffmpeg 4.1.3

1) Link that works fine (published April 26th):
svtplay-dl https://www.svtplay.se/video/18960018/amerikas-finaste-natur/amerikas-finaste-natur-everglades

2) Link that doesn't work (published May 3rd):
svtplay-dl https://www.svtplay.se/video/19026231/amerikas-finaste-natur/amerikas-finaste-natur-sasong-1-grand-canyon

Without --verbose:
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

With --verbose:
DEBUG [1556985245.429015] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1556985245.430954] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1556985245.431103] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/19026231/amerikas-finaste-natur/amerikas-finaste-natur-sasong-1-grand-canyon'
DEBUG [1556985245.438859] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1556985245.942063] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/19026231/amerikas-finaste-natur/amerikas-finaste-natur-sasong-1-grand-canyon HTTP/1.1" 200 36924
DEBUG [1556985245.969841] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1381001-002A'
DEBUG [1556985245.971219] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1556985246.218614] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1381001-002A HTTP/1.1" 200 749
DEBUG [1556985246.2194402] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4-lowbw.m3u8'
DEBUG [1556985246.220544] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1556985246.4664772] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1556985246.468056] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1556985246.738847] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1556985246.741365] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed5.cdn.svt.se:80
DEBUG [1556985246.9904482] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1362
DEBUG [1556985247.6411269] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/2798761b-15cc-41e7-b45b-8a460349b3e8/master-lowbw.m3u8'
DEBUG [1556985247.7477388] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /2798761b-15cc-41e7-b45b-8a460349b3e8/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1556985247.840687] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1556985247.9375591] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-lowbw.m3u8 HTTP/1.1" 200 1349
DEBUG [1556985247.938139] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/2798761b-15cc-41e7-b45b-8a460349b3e8/lowbw.mpd'
DEBUG [1556985248.0314848] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /2798761b-15cc-41e7-b45b-8a460349b3e8/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1556985248.118284] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1556985248.2165399] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/lowbw.mpd HTTP/1.1" 200 12394
DEBUG [1556985248.288382] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4.m3u8'
DEBUG [1556985248.387795] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1556985248.488162] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1556985248.603206] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/master-fmp4.m3u8 HTTP/1.1" 200 2278
DEBUG [1556985248.6037781] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd'
DEBUG [1556985248.705641] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd HTTP/1.1" 302 0
DEBUG [1556985248.8093069] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd HTTP/1.1" 302 0
DEBUG [1556985248.939605] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed5.cdn.svt.se:80 "GET /d0/se/20190430/2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd HTTP/1.1" 200 13814
DEBUG [1556985249.014279] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-1l.akamaized.net/d0/se/20190429/2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F2798761b-15cc-41e7-b45b-8a460349b3e8%2Fmanifest.mpd'
DEBUG [1556985249.015924] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-1l.akamaized.net:80
DEBUG [1556985249.388862] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-1l.akamaized.net:80 "GET /d0/se/20190429/2798761b-15cc-41e7-b45b-8a460349b3e8/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F2798761b-15cc-41e7-b45b-8a460349b3e8%2Fmanifest.mpd HTTP/1.1" 200 1841
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

What to do??

**Comment by Sopor** [comment]
Install latest master. You should be able to compile your own if you follow [these](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) steps.

**Comment by EmmW** [comment]
Thanks for the tip, but I had already tried those steps with the following results:

git clone https://github.com/spaam/svtplay-dl.git
= fatal: destinationssökvägen "svtplay-dl" finns redan och är inte en tom katalog.

brew install python3
= Warning: python 3.7.3 is already installed and up-to-date

pip3 install requests
= Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages

brew install rtmpdump
= Warning: rtmpdump 2.4+20151223 is already installed and up-to-date

pip3 install cryptography
= Collecting cryptography
  Could not fetch URL https://pypi.python.org/simple/cryptography/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement cryptography (from versions: )
No matching distribution found for cryptography

pip3 install pyyaml
= Collecting pyyaml
  Could not fetch URL https://pypi.python.org/simple/pyyaml/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement pyyaml (from versions: )
No matching distribution found for pyyaml

pip3 install pysocks
= Collecting pysocks
  Could not fetch URL https://pypi.python.org/simple/pysocks/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement pysocks (from versions: )
No matching distribution found for pysocks

brew install ffmpeg
= Warning: ffmpeg 4.1.3_1 is already installed and up-to-date

make
= make: *** No targets specified and no makefile found.  Stop.

sudo make install
= make: *** No rule to make target `install'.  Stop.

svtplay-dl --version
= svtplay-dl 2.1

Everything seems to be up-to-date, except for cryptography, pyyaml and pysocks, which couldn't be installed though... Are the above results any help in locating the source of the problem (svtplay-dl working fine on older svt material, but crashing on new svt material)?

**Comment by Sopor** [comment]
If you already have it downloaded (cloned) `destinationssökvägen "svtplay-dl" finns redan och är inte en tom katalog` you need to change current directory to that folder and run `git pull`. This will update svtplay-dl to latest master. Then you can try `make` and `sudo make install`
If this svtplay-dl is some other folder than from github you need to clone to another folder.
`git clone https://github.com/spaam/svtplay-dl.git <nameofthefolder>`.

**Comment by Sopor** [comment]
Google is your friend `Upgrading MacOS to High Sierra and then upgrading pip to the latest version solved it.`. 
Try to upgrade pip for python3
`curl https://bootstrap.pypa.io/get-pip.py | python3`

**Comment by EmmW** [comment]
Ok, so I changed the directory ("cd /Users/myname/svtplay-dl") and then ran "git pull" with the following result:

Uppdaterar e232001..d33186e
Fast-forward
 .gitattributes                                                     |    1 +
 .github/ISSUE_TEMPLATE.md                                          |   20 +
 .gitignore                                                         |  228 +++++++++-
 .travis.yml                                                        |   35 ++
 MANIFEST.in                                                        |    6 +-
 Makefile                                                           |   51 +--
 README.md                                                          |  153 +++++++
 README.rst                                                         |  162 -------
 appveyor.yml                                                       |   44 ++
 bin/svtplay-dl                                                     |    2 +-
 dockerfile/Dockerfile                                              |   21 +
 docs/README.docker.md                                              |   22 +
 lib/Makefile                                                       |    6 +-
 lib/svtplay_dl/__init__.py                                         |  497 ++-------------------
 lib/svtplay_dl/__main__.py                                         |    2 +-
 lib/svtplay_dl/__version__.py                                      |  520 ++++++++++++++++++++++
 lib/svtplay_dl/error.py                                            |    3 +
 lib/svtplay_dl/fetcher/__init__.py                                 |   60 ++-
 lib/svtplay_dl/fetcher/dash.py                                     |  328 ++++++++------
 lib/svtplay_dl/fetcher/hds.py                                      |   66 ++-
 lib/svtplay_dl/fetcher/hls.py                                      |  506 +++++++++++++++++-----
 lib/svtplay_dl/fetcher/http.py                                     |   21 +-
 lib/svtplay_dl/fetcher/rtmp.py                                     |   50 ---
 lib/svtplay_dl/output.py                                           |  205 ---------
 lib/svtplay_dl/postprocess/__init__.py                             |  162 ++++---
 lib/svtplay_dl/service/__init__.py                                 |  103 +++--
 lib/svtplay_dl/service/aftonbladet.py                              |   62 ++-
 lib/svtplay_dl/service/atg.py                                      |   44 ++
 lib/svtplay_dl/service/bambuser.py                                 |   40 --
 lib/svtplay_dl/service/barnkanalen.py                              |  100 +++++
 lib/svtplay_dl/service/bigbrother.py                               |   19 +-
 lib/svtplay_dl/service/cmore.py                                    |  121 ++++++
 lib/svtplay_dl/service/dbtv.py                                     |   39 --
 lib/svtplay_dl/service/disney.py                                   |   61 +--
 lib/svtplay_dl/service/dplay.py                                    |  275 ++++++------
 lib/svtplay_dl/service/dr.py                                       |   78 ++--
 lib/svtplay_dl/service/efn.py                                      |    7 +-
 lib/svtplay_dl/service/eurosport.py                                |  104 +++++
 lib/svtplay_dl/service/expressen.py                                |   33 +-
 lib/svtplay_dl/service/facebook.py                                 |   12 +-
 lib/svtplay_dl/service/filmarkivet.py                              |    6 +-
 lib/svtplay_dl/service/flowonline.py                               |   14 +-
 lib/svtplay_dl/service/hbo.py                                      |   52 ---
 lib/svtplay_dl/service/koket.py                                    |  107 +++++
 lib/svtplay_dl/service/lemonwhale.py                               |   16 +-
 lib/svtplay_dl/service/mtvnn.py                                    |  152 +++++--
 lib/svtplay_dl/service/mtvservices.py                              |   14 +-
 lib/svtplay_dl/service/nhl.py                                      |   22 +-
 lib/svtplay_dl/service/npo.py                                      |   76 ++++
 lib/svtplay_dl/service/nrk.py                                      |   20 +-
 lib/svtplay_dl/service/oppetarkiv.py                               |  117 ++---
 lib/svtplay_dl/service/picsearch.py                                |   39 +-
 lib/svtplay_dl/service/pokemon.py                                  |   25 +-
 lib/svtplay_dl/service/qbrick.py                                   |   60 ---
 lib/svtplay_dl/service/radioplay.py                                |   10 +-
 lib/svtplay_dl/service/raw.py                                      |   41 +-
 lib/svtplay_dl/service/riksdagen.py                                |   17 +-
 lib/svtplay_dl/service/ruv.py                                      |   16 +-
 lib/svtplay_dl/service/services.py                                 |   85 ++++
 lib/svtplay_dl/service/solidtango.py                               |   20 +-
 lib/svtplay_dl/service/sportlib.py                                 |   71 +++
 lib/svtplay_dl/service/sr.py                                       |   44 +-
 lib/svtplay_dl/service/svt.py                                      |   26 +-
 lib/svtplay_dl/service/svtplay.py                                  |  338 ++++++++-------
 lib/svtplay_dl/service/tests/__init__.py                           |    2 -
 lib/svtplay_dl/service/tests/oppetarkiv.py                         |    1 -
 lib/svtplay_dl/service/tests/service.py                            |   37 +-
 lib/svtplay_dl/service/tv4play.py                                  |  348 +++++----------
 lib/svtplay_dl/service/twitch.py                                   |   89 ++--
 lib/svtplay_dl/service/urplay.py                                   |   70 +--
 lib/svtplay_dl/service/vg.py                                       |   35 +-
 lib/svtplay_dl/service/viaplay.py                                  |  291 +++++++------
 lib/svtplay_dl/service/viasatsport.py                              |   11 +-
 lib/svtplay_dl/service/vimeo.py                                    |   31 +-
 lib/svtplay_dl/service/youplay.py                                  |   15 +-
 lib/svtplay_dl/subtitle/__init__.py                                |  216 +++++++---
 lib/svtplay_dl/tests/dash-manifests/cmore.mpd                      |  413 ++++++++++++++++++
 lib/svtplay_dl/tests/dash-manifests/content_type_adaptationset.mpd |   81 ++++
 lib/svtplay_dl/tests/dash-manifests/fff.mpd                        |   35 ++
 lib/svtplay_dl/tests/dash-manifests/svtplay-live.mpd               |   67 +++
 lib/svtplay_dl/tests/dash-manifests/svtvod.mpd                     |  729 +++++++++++++++++++++++++++++++
 lib/svtplay_dl/tests/dash.py                                       |   38 ++
 lib/svtplay_dl/tests/filenamify.py                                 |    5 +-
 lib/svtplay_dl/tests/formatname.py                                 |  329 ++++++++++++++
 lib/svtplay_dl/tests/hls.py                                        |   81 ++--
 lib/svtplay_dl/tests/http.py                                       |   51 +++
 lib/svtplay_dl/tests/output.py                                     |   52 +--
 lib/svtplay_dl/tests/protocol_prio.py                              |   24 +-
 lib/svtplay_dl/utils/__init__.py                                   |  253 -----------
 lib/svtplay_dl/utils/getmedia.py                                   |  225 ++++++++++
 lib/svtplay_dl/utils/http.py                                       |   85 ++++
 lib/svtplay_dl/utils/io.py                                         |   16 -
 lib/svtplay_dl/utils/nfo.py                                        |   60 +++
 lib/svtplay_dl/utils/output.py                                     |  235 ++++++++++
 lib/svtplay_dl/utils/parser.py                                     |  301 +++++++++++++
 lib/svtplay_dl/utils/proc.py                                       |   12 +
 lib/svtplay_dl/utils/stream.py                                     |  125 ++++++
 lib/svtplay_dl/utils/terminal.py                                   |   16 +-
 lib/svtplay_dl/utils/text.py                                       |   63 +++
 lib/svtplay_dl/utils/urllib.py                                     |   18 -
 requirements-dev.txt                                               |    5 +
 requirements.txt                                                   |    4 +
 scripts/cibuild.py                                                 |  126 ++++++
 setup.cfg                                                          |   12 +-
 setup.py                                                           |   62 +--
 setversion.py                                                      |   17 +
 spec/svtplay-dl.spec                                               |   18 -
 tox.ini                                                            |   12 +
 versioneer.py                                                      | 1822 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 109 files changed, 8878 insertions(+), 3317 deletions(-)
 create mode 100644 .gitattributes
 create mode 100644 .github/ISSUE_TEMPLATE.md
 create mode 100644 .travis.yml
 create mode 100644 README.md
 delete mode 100644 README.rst
 create mode 100644 appveyor.yml
 create mode 100644 dockerfile/Dockerfile
 create mode 100644 docs/README.docker.md
 create mode 100644 lib/svtplay_dl/__version__.py
 delete mode 100644 lib/svtplay_dl/fetcher/rtmp.py
 delete mode 100644 lib/svtplay_dl/output.py
 create mode 100644 lib/svtplay_dl/service/atg.py
 delete mode 100644 lib/svtplay_dl/service/bambuser.py
 create mode 100644 lib/svtplay_dl/service/barnkanalen.py
 create mode 100644 lib/svtplay_dl/service/cmore.py
 delete mode 100644 lib/svtplay_dl/service/dbtv.py
 create mode 100644 lib/svtplay_dl/service/eurosport.py
 delete mode 100644 lib/svtplay_dl/service/hbo.py
 create mode 100644 lib/svtplay_dl/service/koket.py
 create mode 100644 lib/svtplay_dl/service/npo.py
 delete mode 100644 lib/svtplay_dl/service/qbrick.py
 create mode 100644 lib/svtplay_dl/service/services.py
 create mode 100644 lib/svtplay_dl/service/sportlib.py
 create mode 100644 lib/svtplay_dl/tests/dash-manifests/cmore.mpd
 create mode 100644 lib/svtplay_dl/tests/dash-manifests/content_type_adaptationset.mpd
 create mode 100644 lib/svtplay_dl/tests/dash-manifests/fff.mpd
 create mode 100644 lib/svtplay_dl/tests/dash-manifests/svtplay-live.mpd
 create mode 100644 lib/svtplay_dl/tests/dash-manifests/svtvod.mpd
 create mode 100644 lib/svtplay_dl/tests/dash.py
 create mode 100644 lib/svtplay_dl/tests/formatname.py
 create mode 100644 lib/svtplay_dl/tests/http.py
 create mode 100644 lib/svtplay_dl/utils/getmedia.py
 create mode 100644 lib/svtplay_dl/utils/http.py
 delete mode 100644 lib/svtplay_dl/utils/io.py
 create mode 100644 lib/svtplay_dl/utils/nfo.py
 create mode 100644 lib/svtplay_dl/utils/output.py
 create mode 100644 lib/svtplay_dl/utils/parser.py
 create mode 100644 lib/svtplay_dl/utils/proc.py
 create mode 100644 lib/svtplay_dl/utils/stream.py
 create mode 100644 lib/svtplay_dl/utils/text.py
 delete mode 100644 lib/svtplay_dl/utils/urllib.py
 create mode 100644 requirements-dev.txt
 create mode 100644 requirements.txt
 create mode 100755 scripts/cibuild.py
 create mode 100644 setversion.py
 delete mode 100644 spec/svtplay-dl.spec
 create mode 100644 tox.ini
 create mode 100644 versioneer.py

I then ran "make" with the following result:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C lib
for py in svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py; do \
		install -d ".build/${py%/*}"; \
		install $py .build/$py; \
	done
# Add git version info to __version__, seen in --version
sed -i -e 's/^__version__ = \(.*\)$/__version__ = "2.1-53-gd33186e"/' \
		.build/svtplay_dl/__init__.py
find .build/ -exec touch -m -t 198001010000 {} \;
(cd .build && zip -X --quiet svtplay-dl svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py)
(cd .build && zip -X --quiet --junk-paths svtplay-dl svtplay_dl/__main__.py)
echo '#!/usr/bin/env python3' > svtplay-dl
cat .build/svtplay-dl.zip >> svtplay-dl
rm -rf .build
chmod a+x svtplay-dl
mv -f lib/svtplay-dl .

After that I ran "sudo make install" with the following result:

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C lib
for py in svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py; do \
		install -d ".build/${py%/*}"; \
		install $py .build/$py; \
	done
# Add git version info to __version__, seen in --version
sed -i -e 's/^__version__ = \(.*\)$/__version__ = "2.1-53-gd33186e"/' \
		.build/svtplay_dl/__init__.py
find .build/ -exec touch -m -t 198001010000 {} \;
(cd .build && zip -X --quiet svtplay-dl svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py)
(cd .build && zip -X --quiet --junk-paths svtplay-dl svtplay_dl/__main__.py)
echo '#!/usr/bin/env python3' > svtplay-dl
cat .build/svtplay-dl.zip >> svtplay-dl
rm -rf .build
chmod a+x svtplay-dl
mv -f lib/svtplay-dl .
install -d /usr/local/bin
install -m 755 svtplay-dl /usr/local/bin

Finally, I ran "curl https://bootstrap.pypa.io/get-pip.py | python3" with the following result:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1669k  100 1669k    0     0  1421k      0  0:00:01  0:00:01 --:--:-- 1422k
Collecting pip
  Using cached https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.1
    Uninstalling pip-19.1:
      Successfully uninstalled pip-19.1
Successfully installed pip-19.1

Having done all of this, I again ran "svtplay-dl https://www.svtplay.se/video/19026231/amerikas-finaste-natur/amerikas-finaste-natur-sasong-1-grand-canyon", this time with the following result (different from before, but unfortunately still not working...):

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ImportError: No module named 'yaml'

Can you make any sense of this? I'm afraid updating from Sierra to High Sierra is not an option in this case (I have some applications that I still use that don't work with High Sierra)...

**Comment by EmmW** [comment]
Wait a minute! I just tried to run the following three commands too (that I couldn't get to work before):

pip3 install cryptography
pip3 install pyyaml
pip3 install pysocks

...and now it (i.e. "svtplay-dl https://www.svtplay.se/video/19026231/amerikas-finaste-natur/amerikas-finaste-natur-sasong-1-grand-canyon") works -- thanks for all your help! :-)

**Comment by sarkeshik** [comment]
I've been following this ticket and from the top to the bottom twice but still have issues. 

`svtplay-dl https://www.svtplay.se/video/22060494/mord-i-paradiset/mord-i-paradiset-sasong-7-avsnitt-4
ERROR: svtplay-dl crashed
....`

I should have the latest of everything mentioned here. Is there anything else I can do?

**Comment by sarkeshik** [comment]
> I've been following this ticket from the top to the bottom twice but still having issues.
> 
> `svtplay-dl https://www.svtplay.se/video/22060494/mord-i-paradiset/mord-i-paradiset-sasong-7-avsnitt-4 ERROR: svtplay-dl crashed ....`
> 
> I should have the latest of everything mentioned here. Is there anything else I can do?
> 
> Mac OS 10.14.4
> Homebrew 2.1.1
> svtplay-dl 2.1
> Python 2.7.10
> pip 19.1
> ffmpeg version 4.1.3

Oh! I know what I didn't do correctly: I missed the `sudo make install` in the steps. Sorry. Now it works, thanks a lot!

**Comment by EmmW** [comment]
Yeah, it seems there's a whole bunch of different Terminal commands that all have to be carried out properly (and in order) for svtplay-dl to work again -- miss one and you're still getting crashes... :-)

Now closing this ticket (thanks Sopor!).
