### ISSUE TITLE
Svtplay crash - IndexError: list index out of range

### ISSUE THREAD

**Issue by maangs** [spaam/svtplay-dl#1079]
### svtplay-dl versions:
2.1
### Operating system and Python version:
Windows 10 64 bit
Python 3.7.3

### What is the issue:
https://www.svtplay.se/video/22073850/bast-i-test/bast-i-test-de-basta-testen-

svtplay-dl https://www.svtplay.se/video/22073850/bast-i-test/bast-i-test-de-basta-testen-sasong-1-basta-testen-del-2 --verbose
DEBUG [1557086349.0567076] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1557086349.0567076] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1557086349.0567076] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/22073850/bast-i-test/bast-i-test-de-basta-testen-sasong-1-basta-testen-del-2'
DEBUG [1557086349.0567076] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1557086349.6348226] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22073850/bast-i-test/bast-i-test-de-basta-testen-sasong-1-basta-testen-del-2 HTTP/1.1" 200 40250
DEBUG [1557086349.712942] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392749-002A'
DEBUG [1557086349.712942] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1557086349.8379614] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392749-002A HTTP/1.1" 200 792
DEBUG [1557086349.8535624] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8'
DEBUG [1557086349.8535624] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1557086349.9942093] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8 HTTP/1.1" 302 0
DEBUG [1557086349.9942093] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1557086350.1211824] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8 HTTP/1.1" 302 0
DEBUG [1557086350.136778] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed6.cdn.svt.se:80
DEBUG [1557086350.23053] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed6.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8 HTTP/1.1" 200 2513
DEBUG [1557086350.23053] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-1a.akamaized.net/d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F13f327af-94c1-49ce-aa45-770d04c381ba%2Fmaster.m3u8'
DEBUG [1557086350.23053] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-1a.akamaized.net:80
DEBUG [1557086350.3711731] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-1a.akamaized.net:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F13f327af-94c1-49ce-aa45-770d04c381ba%2Fmaster.m3u8 HTTP/1.1" 200 591
DEBUG [1557086350.4180188] C:\Python35\lib\site-packages\chardet\eucjpprober.py/feed: EUC-JP Japanese prober hit error at byte 240
DEBUG [1557086350.4336402] C:\Python35\lib\site-packages\chardet\mbcharsetprober.py/feed: EUC-KR Korean prober hit error at byte 240
DEBUG [1557086350.4492645] C:\Python35\lib\site-packages\chardet\mbcharsetprober.py/feed: EUC-TW Taiwan prober hit error at byte 239
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Russian confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: KOI8-R Russian confidence = 0.01
DEBUG [1557086350.4648895] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Russian confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: MacCyrillic Russian confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM866 Russian confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM855 Russian confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Bulgairan confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Bulgarian confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: TIS-620 Thai confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-9 Turkish confidence = 0.16848297696268852
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1557086350.4805105] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1557086350.4961355] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://ed6.cdn.svt.se/d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8'
DEBUG [1557086350.5586674] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed6.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master.m3u8 HTTP/1.1" 200 2513
DEBUG [1557086350.6055117] C:\Python35\lib\site-packages\chardet\eucjpprober.py/feed: EUC-JP Japanese prober hit error at byte 240
DEBUG [1557086350.6367612] C:\Python35\lib\site-packages\chardet\mbcharsetprober.py/feed: EUC-KR Korean prober hit error at byte 240
DEBUG [1557086350.6680105] C:\Python35\lib\site-packages\chardet\mbcharsetprober.py/feed: EUC-TW Taiwan prober hit error at byte 239
DEBUG [1557086350.6992588] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1557086350.6992588] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1557086350.6992588] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1557086350.6992588] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Russian confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: KOI8-R Russian confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Russian confidence = 0.01
DEBUG [1557086350.7148826] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: MacCyrillic Russian confidence = 0.01
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM866 Russian confidence = 0.01
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: IBM855 Russian confidence = 0.01
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.0
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.0
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-5 Bulgairan confidence = 0.01
DEBUG [1557086350.7305079] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1251 Bulgarian confidence = 0.01
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: TIS-620 Thai confidence = 0.0
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: ISO-8859-9 Turkish confidence = 0.16848297696268852
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: utf-8  confidence = 0.7525
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-JP not active
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: GB2312 Chinese confidence = 0.01
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-KR not active
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: CP949 Korean confidence = 0.01
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: Big5 Chinese confidence = 0.01
DEBUG [1557086350.7461326] C:\Python35\lib\site-packages\chardet\charsetgroupprober.py/get_confidence: EUC-TW not active
DEBUG [1557086350.7617562] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/13f327af-94c1-49ce-aa45-770d04c381ba/master-lowbw.m3u8'
DEBUG [1557086350.824253] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /13f327af-94c1-49ce-aa45-770d04c381ba/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557086350.886751] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1557086350.886751] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed0.cdn.svt.se:80
DEBUG [1557086350.9805286] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed0.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master-lowbw.m3u8 HTTP/1.1" 200 1551
DEBUG [1557086350.9805286] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/13f327af-94c1-49ce-aa45-770d04c381ba/master-fmp4.m3u8'
DEBUG [1557086351.0274026] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /13f327af-94c1-49ce-aa45-770d04c381ba/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1557086351.0742743] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1557086351.0898654] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed4.cdn.svt.se:80
DEBUG [1557086351.1680164] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/master-fmp4.m3u8 HTTP/1.1" 200 2532
DEBUG [1557086351.1680164] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/13f327af-94c1-49ce-aa45-770d04c381ba/lowbw.mpd'
DEBUG [1557086351.2148957] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /13f327af-94c1-49ce-aa45-770d04c381ba/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1557086351.2773926] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1557086351.2929897] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed2.cdn.svt.se:80
DEBUG [1557086351.418012] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/lowbw.mpd HTTP/1.1" 200 14825
DEBUG [1557086351.4492326] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd'
DEBUG [1557086351.4961345] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557086351.527383] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd HTTP/1.1" 302 0
DEBUG [1557086351.574258] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd HTTP/1.1" 200 16245
DEBUG [1557086351.574258] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-1a.akamaized.net/d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F13f327af-94c1-49ce-aa45-770d04c381ba%2Fmanifest.mpd'
DEBUG [1557086351.6680024] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-1a.akamaized.net:80 "GET /d0/se/20190502/13f327af-94c1-49ce-aa45-770d04c381ba/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F13f327af-94c1-49ce-aa45-770d04c381ba%2Fmanifest.mpd HTTP/1.1" 200 2119
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
You need to start to use the search... This error has been reported several times already.
Use latest [master ](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

**Comment by maangs** [comment]
Maybe it's time to update the files on svtplay-dl.se then
