### ISSUE TITLE
Questions about patches

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#1081]
1. Do you welcome patches for support of new sites?

2. What type of sites are within your scope? (Mostly Scandinavian sites?)

3. How many days do you usually take to apply a patch from a contributor?

**Comment by spaam** [comment]
i thought i answered this .. but some stuff came in the way sorry about that :( 

1) yes, i have added some sites in the past people wanted
2) most of the sites is from scandinavia but i have added sites from the rest of the world too. 
3) Usually it can be from one day to a few days depending on how good they are.  but lately it have been a loong time because of some personal stuff.  if a contributor have done a bunch of PRs i ask them if they want to have commit access to the repo.

**Comment by forthrin** [comment]
Well, this is a nice surprise. `youtube-dl` has turned out to be such a disaster lately:

- It's slow, performance-wise (hundreds of extractors, all kinds of formats are checked)
- Thousands of unresolved pull requests and issues. Many issues get no response even years after. The project seems grossly understaffed or just not well organised at all.
- The code seems clunky and feature creep-ridden in an attempt to support everything.
- Also, nothing brightens your day like a page-full of hostile warnings and checkboxes in issue form

Actually, I started writing my own, ridiculously small and simple. Only problem so far is some decryption issues. But you learn much more this way, and you can get things exactly how you want them :)

In the meantime, I'd rather use you guys for everything I don't support, since your *rather* small, and actually respond to issues, at least when "some stuff" doesn't come in the way :P

Maybe I'll participate with a patch sometime too, if there's something wrong, and I know how to fix at. At least now I know there's a nice person with a functioning brain in the other end.

**Comment by spaam** [comment]
Interesting never heard that about youtube-dl. 🤔 

the decryption can be a bit hard sometimes. How to do it in HLS and AES is pretty easy. but when they add some other DRM like widewine its a bit way to hard. 
haha i made this project to learn python, always good to start a project to learn things.

sounds like a plan and glhf :)

**Comment by forthrin** [comment]
THX! A good learning project. I assume you have some philosophy to be "not youtube-dl", eg. staying lightweight by not piling on a ton of features and supporting every last obscure site on earth.

The most important thing is to get the highest available resolution of a single video from the highest quality entertainment sites. (With subtitles!) Isn't that what they call "Do one thing well"?

I also delegate complicated work to other tools (like FFmpeg) whenever I can :)
