### ISSUE TITLE
Crash STV.se

### ISSUE THREAD

**Issue by MatsK** [spaam/svtplay-dl#1094]
### svtplay-dl versions:
svtplay-dl 2.1

### Operating system and Python version:
Windows 10
Python 3.7.3

### What is the issue:

svtplay-dl>svtplay-dl.exe https://www.svtplay.se/video/14760152/oasis-supersonic --verbose

DEBUG [1558942658.3329961] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1558942658.3351123] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1558942658.3351123] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/14760152/oasis-supersonic'
DEBUG [1558942658.3391087] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1558942659.4615374] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/14760152/oasis-supersonic HTTP/1.1" 200 37112
DEBUG [1558942659.4685535] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1378847-001A'
DEBUG [1558942659.4705524] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1558942659.4995353] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1378847-001A HTTP/1.1" 200 747
DEBUG [1558942659.501517] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3e800850-a9e0-4e75-9397-310203aaa571/master-fmp4.m3u8'
DEBUG [1558942659.5035133] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1558942659.6784546] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3e800850-a9e0-4e75-9397-310203aaa571/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1558942659.6814532] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1558942659.7294266] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1558942659.736425] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): ed4.cdn.svt.se:80
DEBUG [1558942659.8886583] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master-fmp4.m3u8 HTTP/1.1" 200 2390
DEBUG [1558942659.8906584] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8'
DEBUG [1558942659.9056487] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558942659.91964] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8 HTTP/1.1" 302 0
DEBUG [1558942659.9356315] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8 HTTP/1.1" 200 2368
DEBUG [1558942659.9366305] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-9j.akamaized.net/d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3e800850-a9e0-4e75-9397-310203aaa571%2Fmaster.m3u8'
DEBUG [1558942659.94063] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-9j.akamaized.net:80
DEBUG [1558942659.9586215] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-9j.akamaized.net:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3e800850-a9e0-4e75-9397-310203aaa571%2Fmaster.m3u8 HTTP/1.1" 200 553
DEBUG [1558942659.964614] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://ed4.cdn.svt.se/d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8'
DEBUG [1558942660.091542] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master.m3u8 HTTP/1.1" 200 2368
DEBUG [1558942660.1085346] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3e800850-a9e0-4e75-9397-310203aaa571/master-lowbw.m3u8'
DEBUG [1558942660.1195254] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3e800850-a9e0-4e75-9397-310203aaa571/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558942660.1485095] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1558942660.275436] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/master-lowbw.m3u8 HTTP/1.1" 200 1411
DEBUG [1558942660.2794337] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd'
DEBUG [1558942660.2914279] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558942660.3144145] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd HTTP/1.1" 302 0
DEBUG [1558942660.3354023] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd HTTP/1.1" 200 20095
DEBUG [1558942660.3453994] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-9j.akamaized.net/d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3e800850-a9e0-4e75-9397-310203aaa571%2Fmanifest.mpd'
DEBUG [1558942660.4773202] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-9j.akamaized.net:80 "GET /d0/se/20190516/3e800850-a9e0-4e75-9397-310203aaa571/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F3e800850-a9e0-4e75-9397-310203aaa571%2Fmanifest.mpd HTTP/1.1" 200 2266
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment]
Dupe of #1065 

Use latest [master ](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

**Comment by MatsK** [comment]
And then I have to compile from source, and I couldn't get that to work, installed all req. but the compile still failed.

C:\Users\_Username_\Downloads\git\svtplay-dl>python C:\\Users\\_Username_\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\cxfreeze --include-modules=cffi,queue,idna.idnadata --target-dir=build bin\svtplay-dl
Traceback (most recent call last):
  File "C:\\Users\\_Username_\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\cxfreeze", line 5, in <module>
    main()
  File "C:\Users\_Username_\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\main.py", line 177, in main
    freezer.Freeze()
  File "C:\Users\_Username_\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\freezer.py", line 643, in Freeze
    self.finder = self._GetModuleFinder()
  File "C:\Users\_Username_\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\freezer.py", line 364, in _GetModuleFinder
    finder.IncludeModule(name)
  File "C:\Users\_Username_\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 619, in IncludeModule
    namespace = namespace)
  File "C:\Users\_Username_\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\finder.py", line 335, in _ImportModule
    raise ImportError("No module named %r" % name)
ImportError: No module named 'cffi'

**Comment by MatsK** [comment]
Is there a more recent pre compiled windows version than 2.1?

**Comment by Sopor** [comment]
Why didn't you download the [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts)?

**Comment by MatsK** [comment]
I downloaded master and followed the "Windows compiling instruction"! Thx for the appveyor pointer, will check it out now.

**Comment by MatsK** [comment]
Downloaded new Windows executable from here [https://ci.appveyor.com/project/spaam/svtplay-dl/build/artifacts]

**Comment by krokofant** [comment]
Is it only @spaam that can release a new version? Because the fixes would be nice to have released. Autoupdate via scoop would work if a release was made. 👍
