### ISSUE TITLE
Problems updating/installing via apt on ubuntu

### ISSUE THREAD

**Issue by dazpp** [spaam/svtplay-dl#1098]
Following the install/upgrade information on https://svtplay-dl.se/install/linux/ I get errors using the apt update one.

Ign:5 https://apt.svtplay-dl.se svtplay-dl InRelease
Get:6 https://apt.svtplay-dl.se svtplay-dl/release amd64 Packages [2,902 B]
Get:7 https://apt.svtplay-dl.se svtplay-dl/release i386 Packages [2,897 B]

W: GPG error: https://apt.svtplay-dl.se svtplay-dl InRelease: The following signatures were invalid: KEYEXPIRED 1554230347  KEYEXPIRED 1554230347  KEYEXPIRED 1554230347  KEYEXPIRED 1554230347
W: The repository 'https://apt.svtplay-dl.se svtplay-dl InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

I did remove the old apt-keys and downloaded/installed the new one but I still get the same error.

**Comment by Sopor** [comment]
svtplay-dl 2.1 is the version you get when you install from repo. You need to use from [source](https://svtplay-dl.se/install/source/) instead because 2.1 is broken on several sites.

You should use `svtplay-dl 2.1-53-gd33186e`

**Comment by dazpp** [comment]
I have tried that to but still get errors:

daz@yoda:~/4$ svtplay-dl -A https://www.svtplay.se/video/22541074/for-nationens-basta/for-nationens-basta-sasong-1-vad-som-sker-i-skuggorna
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ImportError: No module named 'yaml'



My system is running Ubuntu 16.04.6 LTS

**Comment by Sopor** [comment]
Run `svtplay-dl --version` so you know it is the `2.1-53-gd33186e` version you are running.

**Comment by dazpp** [comment]
I still get the above error doing that.

**Comment by Sopor** [comment]
It must show some kind of message when you run `pip3 install pyyaml`... You could also try to search for `No module named 'yaml'` in this issue tracker. Other users have got the same message before.

**Comment by dazpp** [comment]
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (3.13)

**Comment by Sopor** [comment]
That is for python 2, you need for python 3.

**Comment by spaam** [comment]
i have fixed this. you need to update the key i posted. thanks for the report <3
