### ISSUE TITLE
DRM or GEO?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1106]
I was downloading `https://www.tv4play.se/program/wallander` and episode 1-8 no problems to download, but 9-12 was DRM protected. I then tried youtube-dl and here it was GEO restricted. I wondering what is correct and why 4 out of 8 are not possible to download?

**Comment by gotroni** [comment]
According to the information in the json information in the web page, episode 9 - 12 is drm protected (' is_drm_protected': True ) . And therefore not possible to download!
