### ISSUE TITLE
failed download from SVT

### ISSUE THREAD

**Issue by simson96** [spaam/svtplay-dl#1107]
### svtplay-dl versions: 
svtplay-dl 2.1

### Operating system and Python version:
Mac OS X 10.14.5
Python 2.7.16

### What is the issue:
svtplay-dl --verbose https://www.svtplay.se/video/22667026/babylon-berlin/babylon-berlin-sasong-1-avsnitt-1?start=auto
DEBUG [1562082747.967987] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1562082747.9694421] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1562082747.969522] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/22667026/babylon-berlin/babylon-berlin-sasong-1-avsnitt-1?start=auto'
DEBUG [1562082747.9943419] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1562082748.486488] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22667026/babylon-berlin/babylon-berlin-sasong-1-avsnitt-1?start=auto HTTP/1.1" 200 42362
DEBUG [1562082748.5012522] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1393580-001A'
DEBUG [1562082748.50326] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1562082748.618142] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1393580-001A HTTP/1.1" 200 763
DEBUG [1562082748.6190531] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/9ace8f15-5fd5-49b1-9657-1c4918df4212/lowbw.mpd'
DEBUG [1562082748.625261] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1562082748.659103] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /9ace8f15-5fd5-49b1-9657-1c4918df4212/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1562082748.662258] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1562082748.692551] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1562082748.703267] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-ed2.secure.footprint.net:80
DEBUG [1562082748.73387] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed2.secure.footprint.net:80 "GET /d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/lowbw.mpd HTTP/1.1" 200 15019
DEBUG [1562082748.735401] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd'
DEBUG [1562082748.754818] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562082748.772794] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562082748.794139] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-ed2.secure.footprint.net:80 "GET /d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd HTTP/1.1" 200 16439
DEBUG [1562082748.7947772] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-1h.akamaized.net/d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F9ace8f15-5fd5-49b1-9657-1c4918df4212%2Fmanifest.mpd'
DEBUG [1562082748.80719] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-1h.akamaized.net:80
DEBUG [1562082748.8260229] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-1h.akamaized.net:80 "GET /d0/se/20190617/9ace8f15-5fd5-49b1-9657-1c4918df4212/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F9ace8f15-5fd5-49b1-9657-1c4918df4212%2Fmanifest.mpd HTTP/1.1" 200 1955
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by Sopor** [comment]
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by simson96** [comment]
Works! Thanks.
