### ISSUE TITLE
Only 9 seconds of sound on all svtplay downloads

### ISSUE THREAD

**Issue by crapal** [spaam/svtplay-dl#1115]
### svtplay-dl versions:

svtplay-dl 2.1-53-gd33186e

### Operating system and Python version:

Windows and linux

### What is the issue:

Any video downloaded the last few days plays sound for 9 seconds and then becomes quiet.
This happens on both windows10 and Linux.
When the download is interrupted before muxing, the audio.ts file seems correct in size, but only plays the first 9 seconds of audio.
   e.g svtplay-dl https://www.svtplay.se/video/22780610/jordgubbslandet

**Comment by spaam** [comment]
i cant reproduce this. what version of ffmpeg do you have?

**Comment by Sopor** [comment]
I think it is because he is downloading DASH instead of HLS #1086

**Comment by crapal** [comment]
Thanks for your help!
It turned out that 1) my ffmpeg on linux was too old and 2) I didn't bother to install ffmpeg on windows since I only wanted to check the audio file.
When I install ffmpeg on windows it works as it should, however I'm still confused since I can't playback the separate audio.ts file. The size is correct and it will mux with the video, but vlc won't play the separate audio-file for more that 9 seconds which is the same time that the old ffmpeg version stops muxing.
Nothing critical since it does work, but I'm just curious if something has changed lately.

**Comment by bitbytare** [comment]
I can confirm 9 sec sound.
Linux Mint 19.1
ffmpeg version 3.4.6-0ubuntu0.18.04.1
svtplay-dl 2.1-53-gd33186e
downloading HLS

**Comment by Sopor** [comment]
You need to use ffmpeg 4 or higher

**Comment by bitbytare** [comment]
Thanks! It works perfectly now :)

**Comment by spaam** [comment]
thanks for the bug report <3
