### ISSUE TITLE
svtplay-dl CRASH when dl https://www.svtplay.se/video/21439398/eagles/eagles-sasong-1-sleepover

### ISSUE THREAD

**Issue by primaw** [spaam/svtplay-dl#1123]
### svtplay-dl versions: 2.1

Run `svtplay-dl --version`

### Operating system and Python version:

Mac OS 10.14.6
Python 2.7.10

### What is the issue:

ERROR: svtplay-dl crashed when DL https://www.svtplay.se/video/21439398/eagles/eagles-sasong-1-sleepover

Detailed info
XXX-MacBook-Pro:~ magnusnilsson$ svtplay-dl --verbose https://www.svtplay.se/video/21439398/eagles/eagles-sasong-1-sleepover
DEBUG [1565685218.5310059] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1565685218.53189] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1565685218.5319371] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/21439398/eagles/eagles-sasong-1-sleepover'

**Comment by Sopor** [comment]
That can't be the complete debug info?

I assume it is the same as #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102 #1107 #1109 #1112 #1113 #1116

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by spaam** [comment]
this should be fixed in 2.2.  it will soon be available in brew. i have made a PR for it. it will be merge in a day or so :)
