### ISSUE TITLE
nfo file for tv show episode mixes title and showtitle

### ISSUE THREAD

**Issue by scharinger** [spaam/svtplay-dl#1125]
svtplay-dl 2.1-53-gd33186e

windows 10

The genereted nfo file for tv show episode mixes <title> and <showtitle> value.

Example
svtplay-dl --remux -A -o "L:\Video\Barn\Nasse" https://www.svt.se/barnkanalen/barnplay/nasse --nfo

**Comment by spaam** [comment]
`and value`  what do you mean by that?  `title` and `showtitle` is mixed?

**Comment by spaam** [comment]
nvm i fixed it. thanks for the bug report <3

**Comment by scharinger** [comment]
Good, something got wrong in the writing there, meant <showtitle> and <title>. But you figured it out. Thank you!
