### ISSUE TITLE
SVT Kvarteret Skatan.

### ISSUE THREAD

**Issue by f98jsc** [spaam/svtplay-dl#1130]
### svtplay-dl versions:
Dont know but downloaded 2019-08-28 and patched with fix.
Run `svtplay-dl --version`

### Operating system and Python version:
Win10

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Trying to download all episodes of these. Season 1 gets errors but season 2 downloads correctly. 

Same if I use all-ep.exe or umans_webtv_downloader.exe

https://www.oppetarkiv.se/video/1338693/kvarteret-skatan-sasong-1-avsnitt-1-av-6

**Comment by Sopor** [comment]
Add the label `incomplete`...

**Comment by Sopor** [comment]
It is working for me ...
```
svtplay-dl.exe -A https://www.oppetarkiv.se/video/1338693/kvarteret-skatan-sasong-1-avsnitt-1-av-6
INFO: Episode 1 of 18
INFO: Url: http://www.oppetarkiv.se/video/1338693/kvarteret-skatan-sasong-1-avsnitt-1-av-6
INFO: Selected to download hls, bitrate: 3082
INFO: Outfile: kvarteret.skatan-sasong.1.s01e01-c7455a4-oppetarkiv.audio.ts
[029/169][=============...................................................................] ETA: 0:00:39
```

**Comment by f98jsc** [comment]
Aha, sorry. Got the two mixed together. See that svtplay-dl is working correctly so will try there.

**Comment by SYSophie** [comment]
@f98jsc issues with uwtd should be reported at [uwtd.me](uwtd.me)
The all-ep is currently not maintained due to abuse :(
