### ISSUE TITLE
svtplay ERROR: No videos found. Can't find any video on that page  on 2.2

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1134]
Hi,

Today (2019-09-02) there is an issue at trying to download from links at svtplay.se

A link that worked yesterday does today cause svtplaydl to respond with the error message:
"ERROR: No videos found. Can't find any video on that page."
An example is the material at web page "https://www.svtplay.se/video/23482334/vagra-sociala-medier".
Note that the web page successfullly plays the video when trying to watch it via the web browser, in my case using Firefox.

Is it perhaps just a temporary issue where an update by SVT will make it go away ?
Anyone else experiencing the same effect ?

NOTE
What still works is using svtplaydl to download from
- URplay.se:  svtplaydl successfully download material,
   an example is "https://urplay.se/program/208230-filmer-fran-ett-svunnet-kina-forandringar-vantar"
- Live from SVTplay channel, stplaydl successfully stores a .ts file
  The example I used when testing live download was from "https://www.svtplay.se/kanaler/svt2?start=auto"

I'm using a python installation of svtplaydl copied from "master" 2019-05-03
It's been running flawlessly until now on a platform Windows 8.1 Pro using a Python 3.5.3 install

Regards,
L-B

**Comment by pythonuser3856** [comment]
I noticed that there is a new version 2.2 of svtplaydl.
However, using that version returns the same result as described above.

**Comment by pythonuser3856** [comment]
I mistakenly closed the issue, here it is again; sorry

**Comment by Sopor** [comment]
### svtplay-dl versions:

svtplay-dl 2.2

### Operating system and Python version:

Windows 10

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

```
svtplay-dl.exe https://www.svtplay.se/video/23423310/hamnd-och-karlek/hamnd-och-karlek-sasong-1-avsnitt-1 --verbose
DEBUG [1567451554.0012405] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.2
DEBUG [1567451554.0012405] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567451554.0012405] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23423310/hamnd-och-karlek/hamnd-och-karlek-sasong-1-avsnitt-1'
DEBUG [1567451554.0168335] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567451554.6561291] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23423310/hamnd-och-karlek/hamnd-och-karlek-sasong-1-avsnitt-1 HTTP/1.1" 200 30283
ERROR [1567451554.671834] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find any video on that page.
```

**Comment by Sopor** [comment]
I hope you manage to fix this @spaam :)

**Comment by spaam** [comment]
some cases we dont get any season and episode number. for example `uppdrag granskning`. i guess need to stop with that. 
i have -A option left to do. will do that tomorrow and release `2.3` tomorrow with the fix.

**Comment by exoji2e** [comment]
Have the same problem with `falsk identitet`. In the meantime `youtube-dl` seems to work (however with very bad naming of the downloaded files).

**Comment by wahboh** [comment]
Ever so grateful for your fantastic work!!

Sorry to have yo add another exaple link that gives the same error:

https://www.svtplay.se/video/23339018/grans

ie  "ERROR: No videos found. Can't find any video on that page." but playable in web browser.
Running version 2.2 Windows

Kind regards
Wabo

**Comment by Sopor** [comment]
Yes, we need to wait for a new commit or a new release from @spaam

**Comment by jjabba** [comment]
+1
I have the same issue as of a few days ago. I have automated downloads of 'Aktuellt' to play the news via Plex, and lately anything appering in the rss stream served here:
`https://www.svtplay.se/aktuellt/rss.xml`
will not download but instead produce the `ERROR: No videos found. Can't find any video on that page.` error.

**Comment by frepe360** [comment]
I see this too, with this URL: https://www.svtplay.se/video/1680195/froken-frimans-krig/del-1-1459

(I also noticed that Kodi (18.4 Git:20190831-3ade758) plays this without any problems.

**Comment by fyrkrans** [comment]
> It seems that SVT is totally changed... I hope you manage to fix this @spaam :)

+1

It really seems to affect everything on SVTplay, so posting further examples is IMO a waste of time.  Unfortunately I can't code, so all I can do is hope that those who do manage to find a solution.  Best of luck!

**Comment by gustaf71** [comment]
I'm not a programmer but here is how I understand it.

In the url from svtplay there is <svtId> tag that give the <data-video-id>
If we search for for <data-video-id> in video class and find it we also find src link to .m3u8
Now we could use ffmpeg to download the video link.

I use this filter from ffmpeg 'aac_adtstoasc'
Convert MPEG-2/4 AAC ADTS to an MPEG-4 Audio Specific Configuration bitstream.

ffmpeg -i "video_url.m3u8" -c copy -bsf:a aac_adtstoasc "output.mp4"

**Comment by Sopor** [comment]
Maybe @spaam could commit his fix so we at least can download single episodes from svtplay?

**Comment by Sopor** [comment]
Thanks @spaam 

`svtplay-dl 2.3+1.gbb0689d`

**Comment by spaam** [comment]
2.3 dont work anymore?

**Comment by Sopor** [comment]
What do you mean? Have you released 2.3?

**Comment by EmmW** [comment]
Hi Johan (@spaam)

How do you upgrade from svtplay-dl 2.2 to 2.3+1.gbb0689d? When I tried "brew upgrade svtplay-dl" in Terminal on Mac, I got back "Error: svtplay-dl 2.2 already installed"...

Mark

**Comment by spaam** [comment]
@Sopor yes. as you see in the filename :)  it  has 2.3 and one more commit.

@EmmW im making a brew MR in a few min.. it taks a day or so until they merge it.

**Comment by Sopor** [comment]
@spaam I can only see Currently v2.2 (2019-08-24) on https://svtplay-dl.se

**Comment by cadwal** [comment]
@spaam I think there is still something wonky with the final fallback in seasoninfo.

DEBUG [1567794548.1650858] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.3
DEBUG [1567794548.1660824] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567794548.1660824] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23417814/hundra-procent-bonde/hundra-procent-bonde-sasong-21-avsnitt-3?start=auto'
DEBUG [1567794548.1690738] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567794548.7290826] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23417814/hundra-procent-bonde/hundra-procent-bonde-sasong-21-avsnitt-3?start=auto HTTP/1.1" 200 29534
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 106, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 81, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 254, in outputfilename
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 286, in seasoninfo
ValueError: Unknown format code 'd' for object of type 'str'

**Comment by Sopor** [comment]
@EmmW Instead of waiting, compile your own svtplay-dl
If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by bartdedecker** [comment]
Version 2.4: One of the string patterns expects a final "z" in the date, which does not match "Z". Perhaps the pattern should be changed into "...[zZ]"?
One can circumvent the error by using -A --all-last 1 options.

H:\downloads>svtplay-dl --verbose https://www.svtplay.se/video/23553138/luuk-och-hallberg/luuk-och-hallberg-sasong-1-avsnitt-1
DEBUG [1567937142.6911132] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1567937142.698109] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1567937142.6991086] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23553138/luuk-och-hallberg/luuk-och-hallberg-sasong-1-avsnitt-1'
DEBUG [1567937142.7031076] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1567937143.498649] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23553138/luuk-och-hallberg/luuk-och-hallberg-sasong-1-avsnitt-1 HTTP/1.1" 200 30671
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2019-09-07T15:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by pe22ad** [comment]
I'm trying to upgrade to 2.4 via brew install svtplay-dl but i'm getting the old not functioning 2.2? 

What do I do wrong?

//Per

**Comment by JohnnyJorgensen** [comment]
I get the same error @bartdedecker mentions above. But his -A --all-last 1 workaround doesn't work for me. I get episode 3 instead of episode 4 using that:

C:\Users\jojo\Documents\Software\SVTPlay-DL\_new - special ffmpeg>svtplay-dl --verbose https://www.svtplay.se/video/23582314/ss-gb/ss-gb-sasong-1-avsnitt-4
DEBUG [1568188197.758038] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-2-g5466853
DEBUG [1568188197.758038] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1568188197.758038] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/23582314/ss-gb/ss-gb-sasong-1-avsnitt-4'
DEBUG [1568188197.758038] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1568188198.0478258] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23582314/ss-gb/ss-gb-sasong-1-avsnitt-4 HTTP/1.1" 200 31583
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 23, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 78, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 315, in extrametadata
  File "C:\Python35\lib\_strptime.py", line 510, in _strptime_datetime
  File "C:\Python35\lib\_strptime.py", line 343, in _strptime
ValueError: time data '2019-09-11T00:00:00Z' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by JohnnyJorgensen** [comment]
Strange. Today I can download the episode above. Yesterday I couldn't... Same software...

svtplay-dl https://www.svtplay.se/video/23582314/ss-gb/ss-gb-sasong-1-avsnitt-4
