### ISSUE TITLE
dplay.dk url

### ISSUE THREAD

**Issue by wheee2000** [spaam/svtplay-dl#1135]
Does anyone know the video URL for dplay.DK ?
using the same as for dplay.se does not work (https://github.com/spaam/svtplay-dl/issues/1069). 
e.g. https://www.dplay.dk/videos/politijagt/93270 does not work, like it would with dplay.se

Thanks

**Comment by SYSophie** [comment]
Please note @wheee2000 that dplay.dk uses videoer instead of videos like dplay.se
i.e:
`https://www.dplay.dk/videoer/politijagt/93270`

Could close this issue now hopefully! :)

**Comment by wheee2000** [comment]
indeed, and thank you.
