### ISSUE TITLE
SVT Play - no videos found

### ISSUE THREAD

**Issue by Gorian90** [spaam/svtplay-dl#1146]
### svtplay-dl versions: 
2.2

### Operating system and Python version: 
MacOS 10.14.4, Python 2.7.10

### What is the issue:
I'm getting an error message saying that there is no video to be found on the URL. I'll admit that I'm connecting through a VPN (Mullvad), but it works fine in the browser. 

**Command:** 
svtplay-dl --verbose https://www.svtplay.se/video/23549922/det-kinesiska-experimentet

**Output:** 
DEBUG [1568020252.4062889] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.2
DEBUG [1568020252.407864] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1568020252.4079528] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/23549922/det-kinesiska-experimentet'
DEBUG [1568020252.4135501] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1568020256.357646] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23549922/det-kinesiska-experimentet HTTP/1.1" 200 27846
ERROR [1568020256.762323] /usr/local/Cellar/svtplay-dl/2.2/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find any video on that page.

**Comment by Sopor** [comment]
You are using an old version. Latest version is 2.4. If you don't want to wait you can compile your own svtplay-dl.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by spaam** [comment]
its on its way. when this https://github.com/Homebrew/homebrew-core/pull/44002 is merged. it will be available in brew.  thanks for bug report <3
