### ISSUE TITLE
svtplay-dl crashes when attempting to download Octonauterna

### ISSUE THREAD

**Issue by tomasgrahn** [spaam/svtplay-dl#1152]
Hi!

First of all I'd like to thank everyone involved in this project for this wonderful tool. I use it all the time to download cartoons for my kids to watch on their tablets when we go for a long drive. Anyway, I encountered this problem when attempting to download Octonauterna today:

DEBUG [1568462345.1857612] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.4+6.gce9bfd3
DEBUG [1568462345.1861186] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
DEBUG [1568462345.1864238] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/octonauterna'
DEBUG [1568462345.1875947] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se
DEBUG [1568462345.2636313] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/octonauterna HTTP/1.1" 200 None
DEBUG [1568462345.2897596] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
INFO [1568462345.2898333] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 20
INFO [1568462345.289894] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: http://www.svt.se/barnkanalen/barnplay/octonauterna/13305964
DEBUG [1568462345.289949] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'http://www.svt.se/barnkanalen/barnplay/octonauterna/13305964'
DEBUG [1568462345.2906637] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svt.se
DEBUG [1568462345.302117] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://www.svt.se:80 "GET /barnkanalen/barnplay/octonauterna/13305964 HTTP/1.1" 301 0
DEBUG [1568462345.3032207] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se
DEBUG [1568462345.3539164] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/octonauterna/13305964 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py", line 91, in get_all_episodes
    get_one_media(substream)
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/service/barnkanalen.py", line 61, in get
    self.outputfilename(janson["video"])
  File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.4+6.gce9bfd3-py3.6.egg/svtplay_dl/service/svtplay.py", line 252, in outputfilename
    pid = data[self.visibleid]["parent"]["id"]
AttributeError: 'Barnkanalen' object has no attribute 'visibleid'

Here's how I executed svtplay-dl:
svtplay-dl --verbose --all-episodes "https://www.svt.se/barnkanalen/barnplay/octonauterna"

I'm running the latest version (as of writing this) on Ubuntu 19.04:
svtplay-dl 2.4+6.gce9bfd3

Thanks in advance!

**Comment by spaam** [comment]
thanks for the bug report <3. i commitied a fix for this in master. it will be in the next version :)

**Comment by tomasgrahn** [comment]
Thanks! That solves this issue, but now I have a problem muxing but I'll open a separate issue for that.
