### ISSUE TITLE
New subdomain makes downloads not possible for pokemon.com

### ISSUE THREAD

**Issue by pokefanatic** [spaam/svtplay-dl#1165]
### svtplay-dl versions:

svtplay-dl 2.4

### Operating system and Python version:

macOS High Sierra 10.13.6 (17G8030)
Python 2.7.16

### What is the issue:

**Error message:** ERROR: That site is not supported. Make a ticket or send a message

On web site:
https://watch.pokemon.com/en-us/season.html?id=pokemon-the-series-sun-moon-ultra-legends-vol-3

I try to download:
svtplay-dl --verbose https://watch.pokemon.com/en-us/player.html?id=e037b8ea17a54d19b4c87a183809901c

Result:
DEBUG [1569742479.7013571] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.4
DEBUG [1569742479.7030249] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: generic
DEBUG [1569742479.703082] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://watch.pokemon.com/en-us/player.html?id=e037b8ea17a54d19b4c87a183809901c'
DEBUG [1569742479.7491992] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): watch.pokemon.com:443
DEBUG [1569742479.7851148] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://watch.pokemon.com:443 "GET /en-us/player.html?id=e037b8ea17a54d19b4c87a183809901c HTTP/1.1" 200 5081
ERROR [1569742479.788786] /usr/local/Cellar/svtplay-dl/2.4_1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: That site is not supported. Make a ticket or send a message

**Comment by bonbonmcdaniel** [comment]
Having the same problem.

**Comment by spaam** [comment]
this works with 4.3.. bit late but yeah :)
