### ISSUE TITLE
audio silent after 4 seconds

### ISSUE THREAD

**Issue by drhexgit** [spaam/svtplay-dl#1172]
Linux Mint 19.1    python 3.6.7
svtplay-dl 2.4    also tested 2.4-26-g5dcc899  from source

Files download fine, and the video is ok, but the audio turns silent after about 4 seconds.
Downloading using dash or hls  makes no difference.
Happens on any episode of "vem vet mest" and "svenska nyheter" from svtplay.
Streaming the programs in a web browser works. 

Examining the *.audio.ts file downloaded, it has the proper length to contain all the audio. A hex editor tells me that the data varies throughout the entire file, it is not filled with zeros. The clipping point of 4 seconds is about 64kB into the file, if that's a hint.
I tried playing the file using multiple programs on multiple devices with the same result, so it's not a playback issue.
My best guess is that a few bytes in the header of the audio file are written incorrectly so that the file seems shorter than it is.

**Comment by spaam** [comment]
what version of ffmpeg do you have?

**Comment by drhexgit** [comment]
ffmpeg 3.4.4-0ubuntu0.18.04.1

**Comment by drhexgit** [comment]
...but ffmpeg is used to merge the audio and video file, right?   I tried loading the *.audio.ts file into audacity - it only shows 4 seconds, so the audio file is corrupt even before being merged with the video data.

**Comment by Sopor** [comment]
You need version 4 or higher of ffmpeg ...

**Comment by drhexgit** [comment]
After upgrading to ubuntu 19.10 which includes ffmpeg 4.1.4-1build2, the audio is now complete.
