### ISSUE TITLE
svtplay: No videos found. //2019-10-31

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#1183]
### svtplay-dl versions:
svtplay-dl 2.4-29-gc59a305

### Operating system and Python version:

Windows 10 Pro x64
Python 3.7.dll

### What is the issue:

No videos found.

svtplay-dl.exe --verbose https://www.svtplay.se/video/24141030/var-tid-ar-nu/var-tid-ar-nu-sasong-3-nattklubben?start=auto

DEBUG [1572558151.3664382] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-29-gc59a305
DEBUG [1572558151.3764327] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1572558151.3774335] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/24141030/var-tid-ar-nu/var-tid-ar-nu-sasong-3-nattklubben?start=auto'
DEBUG [1572558151.3844368] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1572558152.3893359] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/24141030/var-tid-ar-nu/var-tid-ar-nu-sasong-3-nattklubben?start=auto HTTP/1.1" 200 41920
DEBUG [1572558152.4174285] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/e72LRdM'
DEBUG [1572558152.4214368] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1572558152.791781] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/e72LRdM HTTP/1.1" 200 830
DEBUG [1572558152.7957356] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd'
DEBUG [1572558152.7997568] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): switcher.cdn.svt.se:443
DEBUG [1572558153.2477877] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 302 0
DEBUG [1572558153.2527845] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): balancer.cdn.svt.se:443
DEBUG [1572558153.3599718] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://balancer.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 302 0
DEBUG [1572558153.3669486] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): ed0.cdn.svt.se:443
DEBUG [1572558153.4754374] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed0.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 200 3865
DEBUG [1572558153.4784367] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1m.akamaized.net/d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F669b2636-eed6-4449-b150-8823826e251d%2Fmanifest.mpd'
DEBUG [1572558153.4864385] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1m.akamaized.net:443
DEBUG [1572558153.6103754] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1m.akamaized.net:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F669b2636-eed6-4449-b150-8823826e251d%2Fmanifest.mpd HTTP/1.1" 200 873
DEBUG [1572558153.8053434] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://ed0.cdn.svt.se/d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd'
DEBUG [1572558153.831372] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed0.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 200 3865
DEBUG [1572558154.0273497] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd'
DEBUG [1572558154.053536] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 302 0
DEBUG [1572558154.0746772] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://balancer.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 302 0
DEBUG [1572558154.120366] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed0.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/manifest.mpd HTTP/1.1" 200 3865
DEBUG [1572558154.1233535] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/master-fmp4-lowbw.m3u8'
DEBUG [1572558154.1463535] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.167353] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://balancer.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.1753597] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): ed4.cdn.svt.se:443
DEBUG [1572558154.2938612] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed4.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1060
DEBUG [1572558154.2968605] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/master-lowbw.m3u8'
DEBUG [1572558154.3158853] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.4423766] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1m.akamaized.net:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master-lowbw.m3u8 HTTP/1.1" 200 454
DEBUG [1572558154.446384] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/master-fmp4.m3u8'
DEBUG [1572558154.4692302] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.487215] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://balancer.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.5092888] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed4.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master-fmp4.m3u8 HTTP/1.1" 200 2082
DEBUG [1572558154.5142925] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/lowbw.mpd'
DEBUG [1572558154.5407574] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1572558154.650287] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1m.akamaized.net:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/lowbw.mpd HTTP/1.1" 200 734
DEBUG [1572558154.6572452] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://switcher.cdn.svt.se/669b2636-eed6-4449-b150-8823826e251d/master.m3u8'
DEBUG [1572558154.6803863] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /669b2636-eed6-4449-b150-8823826e251d/master.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.6989264] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://balancer.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8 HTTP/1.1" 302 0
DEBUG [1572558154.7260504] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed0.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8 HTTP/1.1" 200 2060
DEBUG [1572558154.7300184] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1m.akamaized.net/d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F669b2636-eed6-4449-b150-8823826e251d%2Fmaster.m3u8'
DEBUG [1572558154.7530978] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1m.akamaized.net:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2F669b2636-eed6-4449-b150-8823826e251d%2Fmaster.m3u8 HTTP/1.1" 200 604
DEBUG [1572558154.7590883] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://ed0.cdn.svt.se/d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8'
DEBUG [1572558154.808495] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://ed0.cdn.svt.se:443 "GET /d0/se/20191025/669b2636-eed6-4449-b150-8823826e251d/master.m3u8 HTTP/1.1" 200 2060
ERROR [1572558154.8174534] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by spaam** [comment]
i cant reproduce this. its working here 🤔

**Comment by myowncloudservice** [comment]
I use the Lastest version of svtplay-dl.exe downloaded from 

https://ci.appveyor.com/project/spaam/svtplay-dl

https://ci.appveyor.com/api/buildjobs/6aqyvpbr07asnxjl/artifacts/svtplay-dl.zip

**Comment by myowncloudservice** [comment]
Hi, @spaam 

I have fix it myself it was something with my own script who create this issue on svtplay.se

Thanks for a great job with svtplay-dl!
