### ISSUE TITLE
tv4play has started to give this : can't download DRM protected content from this site

### ISSUE THREAD

**Issue by duck7207** [spaam/svtplay-dl#1185]
### svtplay-dl versions:
svtplay-dl 2.4-29-gc59a305
svtplay-dl 2.4

### Operating system and Python version:
windows 10
python 3.5 & 3.7

### What is the issue:
url: 
https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/11979041
https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/11979048
https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/11979050

verbose:
c:\sys\svtplay>.\svtplay-dl.exe https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/11979050 -v
DEBUG [1573375075.7183895] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-29-gc59a305
DEBUG [1573375075.7212234] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1573375075.722221] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/11979050'
DEBUG [1573375075.7232184] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1573375076.2060947] C:\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/s%C3%A5-mycket-b%C3%A4ttre/11979050 HTTP/1.1" 200 None
ERROR [1573375076.2451596] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. We can't download DRM protected content from this site.

the 1st episode works but not the rest.

**Comment by spaam** [comment]
i guess they changed how things works in newer episodes.  i cant decrypt it :(
