### ISSUE TITLE
dateutil.parser.parse(some_time_stamp).strftime('%s') is not always supported

### ISSUE THREAD

**Issue by fredrikbondesson** [spaam/svtplay-dl#1196]
### svtplay-dl versions:

svtplay-dl 2.4

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
Windows 10 
Python 3.8.1

### What is the issue:
dateutil.parser.parse(some_time_stamp).strftime('%s') is not always supported

There is some code that uses the .strftime('%s') (see svtplay_dl\service\svtplay.py), however this might not always be supported. 

For more information see:
https://stackoverflow.com/questions/46902029/how-to-convert-date-string-by-using-lib-dateutil?noredirect=1&lq=1

svtplay-dl.py -S https://www.svtplay.se/video/24778694/this-beautiful-fantastic --verbose

DEBUG [1577630335.2102752] svtplay-dl\lib\site-packages\svtplay_dl\utils\getmedia.py/get_media: version: 2.4
DEBUG [1577630335.2112744] svtplay-dl\lib\site-packages\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1577630335.2112744] svtplay-dl\lib\site-packages\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/24778694/this-beautiful-fantastic'
DEBUG [1577630335.21927] svtplay-dl\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1577630335.294218] svtplay-dl\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/24778694/this-beautiful-fantastic HTTP/1.1" 200 29964
Traceback (most recent call last):
  File "Scripts\svtplay-dl.py", line 7, in <module>
    svtplay_dl.main()
  File "svtplay-dl\lib\site-packages\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "svtplay-dl\lib\site-packages\svtplay_dl\utils\getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "svtplay-dl\lib\site-packages\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
    for i in streams:
  File "svtplay-dl\lib\site-packages\svtplay_dl\service\svtplay.py", line 77, in get
    self.extrametadata(janson, self.visibleid)
  File "svtplay-dl\lib\site-packages\svtplay_dl\service\svtplay.py", line 306, in extrametadata
    self.output["publishing_datetime"] = int(dateutil.parser.parse(episode["validFrom"]).strftime("%s"))
ValueError: Invalid format string

(Note in output above some paths are slightly modified)

Note: I fixed the error above by changing to use timestamp() 
self.output["publishing_datetime"] = int(dateutil.parser.parse(episode["validFrom"]).timestamp())

**Comment by Sopor** [comment]
Try latest [master](https://svtplay-dl.se/download/snapshots/) and see if that fix the problem...

**Comment by fredrikbondesson** [comment]
Seems to be fixed in master. I also had a quick look in the master code and no sign of "strftime("%s")" anymore!

Thanks

**Comment by Sire** [comment]
Verified as fixed, can be closed.
