### ISSUE TITLE
Pokemon.com "ERROR: That site is not supported. Make a ticket or send a message"

### ISSUE THREAD

**Issue by Randomdude192** [spaam/svtplay-dl#1199]
### svtplay-dl version: 
2.4-29-gc59a305/2019/10/19
### Operating system and Python version: 
Windows 10 Python 3.5 for 2.4 and 3.7 for 2.4-29-gc59a305
### What is the issue:
When downloading an episode from [watch.pokemon.com](https://watch.pokemon.com/sv-se/) I get the "ERROR: That site is not supported. Make a ticket or send a message" and I think it is due  to them making you watch episodes on [watch.pokemon.com](https://watch.pokemon.com/sv-se/) instead of [pokemon.com](https://www.pokemon.com/us/pokemon-episodes/) as this happens with all episodes
### Command:
`svtplay-dl https://watch.pokemon.com/sv-se/player.html?id=91b2f1b28ad34e1e975fd2f7ce048c9c`

**Comment by spaam** [comment]
this works with 4.3.. bit late but yeah :)
