### ISSUE TITLE
Encryption bypassing as separate tool

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#1200]
I had a thought I want to pass by you guys:

Anyone with basic knowledge of programming and HTML/JSON parsing/regex can write a video downloader, particularly since you can delegate a lot of heavy lifting to tools like FFmpeg.

However bypassing encryption/obfuscation schemes is not funny. That takes serious knowledge only had by dedicated crypto freaks.

So I was thinking: A separate project for a separate tool that does *only* that, so that video extractors can call that tool for the heavy lifting when needed.

This way every video extractor tool wouldn't have to update their bypassing code every time a site changes their scheme. It would only have to be done once.

What are your thoughts on this?

**Comment by VideoPlayerCode** [comment]
I think every site uses Widevine. Relevant info:

https://news.ycombinator.com/item?id=21308388

**Comment by forthrin** [comment]
What I'm mostly referring to is obfuscation schemes were you can't just get to the `.m3u8` URL because it has been encrypted, or there is impossible-to-read JavaScript code involved.

For example, with some YouTube videos, `streamingData->formats->url` will return a HTTP 403 for no apparent reason. Or there will be a `s` parameter with some sort of encryption key.

In `svtplay-dl/lib/svtplay_dl/service/dr.py` there is a `_decrypt` function that does stuff with AES, etc. that no regular programmer will understand unless he's deep into crypto.

So the idea would be to put all such heavy lifting that requires crypto knowledge into a separate tool to the benefit for non-crypto programmers that want to do things with online video content.

**Comment by forthrin** [comment]
Evidently the joy of doing the extra work yourself far surpasses the idea of code reuse. Closing.
