### ISSUE TITLE
TV4Play - Tillsammans mot cancer - sound out of sync

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1201]
### svtplay-dl versions:

svtplay-dl 2.4-29-gc59a305

### FFmpeg version:

ffmpeg 4.2.1

### Operating system and Python version:

Windows 10

### What is the issue:
When downloading `Tillsammans mot cancer` the sound will get out of sync. It seems that `youtube-dl` also generates the same issue, but not if you watch it from the site or with `Kodi/Retrospect`.

`svtplay-dl.exe https://www.tv4play.se/program/tillsammans-mot-cancer/12490848`

**Comment by SYSophie** [comment]
@Sopor TV4 has a habit of sometimes especially with live streams produce bad streams when it comes to the HLS and these streams has malformed PTS - timestamps for the audio track. Then when the audio then is merged with the video thru FFmpeg, errors just adds on and it completely derails to a point of not saveable. 

I would highly suggest that you download the stream thru DASH instead which has a tendency to produce correct better streams. This isn't supported today by svtplay-dl but it's by youtube-dl.

**Comment by Sopor** [comment]
But when i downloaded with youtube-dl it never used ffmpeg. What i can see it only downloaded one single file with both video and audio from TV4
[download] Destination: Tillsammans mot cancer-12490848.mp4

**Comment by SYSophie** [comment]
@Sopor this is a question concerning youtube-dl instead of svtplay-dl. Hint there is a verbose command which will tell you more detailed what's going on.

As I said before the bad PTS-timestamps are already there in the HLS stream and use of ffmpeg usually just makes it worse.

I highly recommend you to try and use the DASH protocol instead of the HLS.

With this said I leave this issue here since we're moving away from svtplay-dl and the core issue.

**Comment by Sopor** [comment]
In that case we need an option to not use ffmpeg. And yes, DASH works 👍

**Comment by SYSophie** [comment]
@Sopor well ffmpeg just adds on to the issue with HLS but even when not using ffmpeg the bad PTS timestamps are still there from source.  If you have shit which you put into a box, shit will still come out from the box.

The audio tracks needs to be fixed somehow when it contains bad PTS timestamps. I just think it's easier to use DASH for simplicity and you actually get a good end result and not an end result that has been patched together.
