### ISSUE TITLE
possibility to get mp4 container when downloading

### ISSUE THREAD

**Issue by freuz** [spaam/svtplay-dl#121]
it would be nice if one could get .mp4 container when downloading instead of .flv
mp4 is more convinient to use in zoomplayer, xbmc and others and it would be nice to not need to manually remux :)

**Comment by atrus05** [comment]
The archaic ts format is not something that behaves well in many players, so I agree with freuz that being able to directly get a mp4 version of the file would be a win.

**Comment by spaam** [comment]
I'm almost done with #254, after that i will fix this muxing to .mp4
