### ISSUE TITLE
SVT Play crash

### ISSUE THREAD

**Issue by atrus05** [spaam/svtplay-dl#1216]
### svtplay-dl versions:
2020-01-24

### Operating system and Python version:
Ubuntu Server 18.04
Python 2.7.17

### What is the issue:

Crash (seen below) when trying to download this specific video.

atrus@norco:/tank1/Media/TV/Vetenskapens Värld/Season 2020$ svtplay-dl --verbose https://www.svtplay.se/video/25404251/vetenskapens-varld/vetenskapens-varld-sasong-32-megabranderna-det-globala-hotet?start=auto
DEBUG [1581700413.863213] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1581700413.8642688] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1581700413.8643308] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/25404251/vetenskapens-varld/vetenskapens-varld-sasong-32-megabranderna-det-globala-hotet?start=auto'
DEBUG [1581700413.8662014] /home/atrus/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1581700414.6098652] /home/atrus/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/25404251/vetenskapens-varld/vetenskapens-varld-sasong-32-megabranderna-det-globala-hotet?start=auto HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 57, in get
KeyError: 'video'

**Comment by Sopor** [comment]
That can't be the right version of svtplay-dl? I'm running svtplay-dl 2.4+31.g25d3105 and i can download it
```
$ svtplay-dl https://www.svtplay.se/video/25404251/vetenskapens-varld/vetenskapens-varld-sasong-32-megabranderna-det-globala-hotet
INFO: Outfile: vetenskapens-varld.megabranderna-det-globala-hotet-798ac91-svtplay.srt
INFO: Selected to download hls, bitrate: 2696
INFO: Outfile: vetenskapens-varld.megabranderna-det-globala-hotet-798ac91-svtplay.audio.ts
[012/908][=.............................................................................................................] ETA: 0:03:07
```

**Comment by atrus05** [comment]
Dont know what to say, but it sure was that version.
I have now updated to latest (2020.03.01), and the download start but stops at exactly 76%. Simply freezes. @Sopor I can see that you are downloading in .ts, and when I download it downloads in .mp4. I wonder if that is why it works for you.... hmm. I will try to figure out how to change to .ts to see if that works.

**Comment by atrus05** [comment]
Holy shit, I am so sorry. I see now that I entered the wrong github repository. I am using youtube-dl, and now svtplay-dl (as svtplay-dl stopped working for me a couple of months ago). Sorry!

**Comment by Sopor** [comment]
@atrus05 So when you run `svtplay-dl --version` you get 2020-01-24 ?
