### ISSUE TITLE
Subtitle *.vtt is not supported

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1229]
Only *.srt is supported.
You can try: https://www.oppetarkiv.se/video/3326085/skeppsholmen-sasong-1-avsnitt-1-av-26?ac=skepps

Only the *.mp4 will be downloaded with no subtitle file.

**Comment by UWTD** [comment]
uwtd have an fix for this problem.
https://www.uwtd.me/postid/4734/

**Comment by torbjornljung** [comment]
Sorry ! Hi ! Tried the fixed svtplay-dl. There was no file extension so I added .exe. Then when trying to run it Windows complained that it's not compatible with my 64-bit installation.

Could you fix that ?

Cheers, Torbjorn Ljung

**Comment by torbjornljung** [comment]
Hi again ! Maybe you can make an .exe out of it. Unfortunately I can't do it.
Cheers, Torbjorn

**Comment by UWTD** [comment]
You can use svtplay-dl with python.
`python svtplay-dl "url"`

**Comment by torbjornljung** [comment]
Sorry ! But it didn't work. 
I can see historically this problem was mentioned 2016, and the I saw was "it will be included in the next release". Do you know who is managing new releases ? 
Cheers, Torbjorn

**Comment by torbjornljung** [comment]
But youtube-dlg can download *.vtt subtitles.

**Comment by UWTD** [comment]
It works. I promise

**Comment by torbjornljung** [comment]
Hi UWTD, Could you please write detailed instructions how to install Python in Windows 10 ? As I said I 
tried it and then tried to execute it as you said but I think I got an error saying that yaml something was missing, then I downloaded yaml and installed it but..... no success.
