### ISSUE TITLE
SVT Barn

### ISSUE THREAD

**Issue by cass00** [spaam/svtplay-dl#1231]
### svtplay-dl versions:
svtplay-dl 2.4+35.g81cb18f
### Operating system and Python version:
Fedora 30 Python 3.6.8
### What is the issue:
Can't download from SVT Barn

svtplay-dl -v https://www.svt.se/barnkanalen/barnplay/zogg/eWvXQ32

DEBUG [1587413542.6297672] /usr/local/lib/python3.6/site-packages/svtplay_dl-2.4+35.g81cb18f-py3.6.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.4+35.g81cb18f
DEBUG [1587413542.6301436] /usr/local/lib/python3.6/site-packages/svtplay_dl-2.4+35.g81cb18f-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
DEBUG [1587413542.6301887] /usr/local/lib/python3.6/site-packages/svtplay_dl-2.4+35.g81cb18f-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/zogg/eWvXQ32'
DEBUG [1587413542.6316214] /usr/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se
DEBUG [1587413542.6981635] /usr/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/zogg/eWvXQ32 HTTP/1.1" 200 91426
ERROR [1587413542.741745] /usr/local/lib/python3.6/site-packages/svtplay_dl-2.4+35.g81cb18f-py3.6.egg/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find video info.

**Comment by Sopor** [comment]
Have you tried from [here](https://www.svtplay.se/video/21937342/zogg) ?
