### ISSUE TITLE
No sound in downloaded video

### ISSUE THREAD

**Issue by fabfer** [spaam/svtplay-dl#1235]
svtplay-dl versions:

svtplay-dl 2.4

### Operating system and Python version:

Ubuntu 18.04.4 LTS,  Python 2.7.17

### What is the issue:

After downloading any video, only the first 3 seconds of audio are present in the final converted media file.
An example of video with no audio (apart the first few seconds) is the following:

    svtplay-dl https://www.svtplay.se/video/26595950/we-got-this/we-got-this-sasong-1-katten-rio

**Comment by Sopor** [comment]
You are running an old svtplay-dl, but the reason for no sound is probably a too old ffmpeg. You need 4 or higher of ffmpeg.

**Comment by fabfer** [comment]
It worked! Thank you very much for your help!
