### ISSUE TITLE
SVT Play have now 5.1 sound in some shows. How can I get it?

### ISSUE THREAD

**Issue by Thoxxx** [spaam/svtplay-dl#1237]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

**Comment by Sopor** [comment]
Was it too hard to include some URLs?

**Comment by Thoxxx** [comment]
https://www.svtplay.se/video/24829882/tamara-drewe?start=auto
https://www.svtplay.se/video/26573930/falsk-identitet/falsk-identitet-sasong-5-avsnitt-1?start=auto

**Comment by Thoxxx** [comment]
Many new series and movies are in 5.1

**Comment by Sopor** [comment]
What do you use to play it in to get 5.1 audio?

**Comment by Thoxxx** [comment]
Apple TV 4K

**Comment by UWTD** [comment]
Uwtd will release an svtplay-dl fix later today. It is already in use by some users but will be public today

**Comment by Thoxxx** [comment]
Nice! Thank you

**Comment by spaam** [comment]
@UWTD feel free to do a pull request and we can have the changes upstream : )

**Comment by spaam** [comment]
seems like videos is also in h265(hevc)..

it will be a interesting how to present the data. should we prefer h264(avc) over h265?  🤔

**Comment by Sopor** [comment]
h265 is not supported by all single-board computer, so i suggest you to stay with h264.

**Comment by spaam** [comment]
that sounds like a option.. maybe have something similar to the `-P` option where we can specify what files to download so you can get the hevc if you want it.

**Comment by UWTD** [comment]
h265 have big issus in some devices. And svt's h265 have crappy quality..

**Comment by Sopor** [comment]
It seems that SVT has started to use 1080p too. I just downloaded a 1080p in 5.1 audio with youtube-dl :)

**Comment by UWTD** [comment]
1080p is not new on svt

**Comment by Sopor** [comment]
I have never downloaded any 1080p with svtplay-dl from SVTPlay.

**Comment by UWTD** [comment]
Ok

**Comment by Thoxxx** [comment]
I think more or less all new material (maybe not news etc) is 1080p

**Comment by Thoxxx** [comment]
@Sopor: How do you download from svt play with youtube-dl?
I tried https://www.svtplay.se/video/25374987/good-kill but only got 2.0 audio
Plays 5.1 on Apple TV

**Comment by UWTD** [comment]
@Thoxxx 
Try:
`youtube-dl -f hls-cmaf-avc-51-surround-Svenska https://www.svtplay.se/video/25374987/good-kill`

**Comment by Sopor** [comment]
@Thoxxx I used:
```
youtube-dl -f bestvideo+hls-ts-avc-51-surround-Svenska --write-sub --all-subs --embed-subs --convert-subs srt --restrict-filenames https://www.svtplay.se/video/25374987/good-kill
```

**Comment by Sopor** [comment]
@UWTD That line you suggested only downloads the audio

**Comment by UWTD** [comment]
@Sopor yes. I guess he do not need the video to if it already downloaded once? Merge the new audio to the old video and it is done

**Comment by Sopor** [comment]
I believe most non expert user don't do that. It is one step over there heads :)

**Comment by Sopor** [comment]
The add-on Retrospect for Kodi now also has support for 5.1 audio :)

**Comment by Thoxxx** [comment]
Hi, The best for me is if I can download both audio and video and mux them in one pass. I'm not into programming at all, but it seems this works on svt play until there is an updated svtplay-dl:

youtube-dl -f bestvideo+hls-ts-avc-51-surround-Svenska https://www.svtplay.se/video/25374987/good-kill

Thanks

**Comment by UWTD** [comment]
Yes maybe it's to hard for some users but some will make it. I guess @spaam will look at my pull request tomorrow. And if users can't wait the modified svtplay-dl is posted on my site

**Comment by Thoxxx** [comment]
Strange though that the video don't open in QuickTime Player. Works in VLC and Apple TV
<img width="415" alt="Skärmavbild 2020-06-03 kl  00 05 40" src="https://user-images.githubusercontent.com/66281871/83575438-bf50a200-a52f-11ea-9ef5-c5e3d88e8cb5.png">

**Comment by UWTD** [comment]
Yes it is some issues with youtube-dl and the merge

**Comment by Sopor** [comment]
@Thoxxx I downloaded the same file as you did and it was no problem to play it in VLC, Kodi, MPC, WMP 12 or MPC Homecinema. I don't have QT in Windows.

```
General
Complete name                            : Tamara_Drewe-K16pgXw.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 2.63 GiB
Duration                                 : 1 h 46 min
Overall bit rate                         : 3 548 kb/s
Writing application                      : Lavf58.29.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 h 46 min
Bit rate                                 : 3 100 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.060
Stream size                              : 2.29 GiB (87%)
Writing library                          : x264 core 155 r2917 0a84d98
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=hex / subme=9 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-4 / threads=34 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=6 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=192 / keyint_min=96 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=3100 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=4700 / vbv_bufsize=6200 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : ac-3
Duration                                 : 1 h 46 min
Bit rate mode                            : Constant
Bit rate                                 : 448 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 340 MiB (13%)
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
```

**Comment by SYSophie** [comment]
> seems like videos is also in h265(hevc)..
> 
> it will be a interesting how to present the data. should we prefer h264(avc) over h265? 🤔

H264(AVC) has overall better performance for now, H265(HEVC) removes details, messes up a lot sometimes and has a general green tint to it.

According to this thread they're still tweaking the HEVC - [Link](https://swedroid.se/forum/threads/test-av-5-1-ljud-pa-svt-play-via-chromecast.181489/)

I posted a few samples in that thread comparing the two of them. Attaching them here too.
Sample #1 - [Link](https://imgur.com/a/yyWtBiI)
Sample #2 - [Link](https://imgur.com/a/2R3kX81)

I think HEVC has a great future ahead of it but for now I think it's better to stick with H264 when looking at the quality difference and the compatibility.

@Sopor 1080p has been available at least since October 2019.
Tipped media about it - [Link](https://feber.se/film/svt-play-kommer-fa-hogre-upplosning/403394/)
Since then it has been available on everything newly published. With a few exceptions.

**Comment by Thoxxx** [comment]
@Sopor I can play other 5.1 videos in QT Player but no files from youtube-dl. But it works on other players.
@SYSophie Agree that avc looks better

**Comment by SYSophie** [comment]
> @Sopor I can play other 5.1 videos in QT Player but no files from youtube-dl. But it works on other players.
> @SYSophie Agree that avc looks better

the yt-dl issue is something I suggest you report in their repo. But it would be interesting to know which versions of the softwares (yt-dl & FFmpeg) that you are running I assume that you are up to date?

When I'm downloading manually the streams thru FFmpeg it plays fine thru any player.

Yeah some people might argue that H265 looks better on larger screen which I in some cases can agree on but then we have the general green tint, big mess ups from time to time and removed details. 

Based on the scrubbing I have done thru 10-20 of these videos and comparing them I must say that I would say that AVC has a better performance overall. But I guess that might change soon as they are tweaking it.

**Comment by Thoxxx** [comment]
yt-dl version 2020.05.29
ffmpeg 4.1.4

I wrote ... --version in Terminal. Was that right?

**Comment by Sopor** [comment]
I run ffmpeg version 4.2.1 and youtube-dl 2020.05.29. Try update if you can...

**Comment by Thoxxx** [comment]
What's the best way to update FFmpeg ?

**Comment by UWTD** [comment]
@Thoxxx what OS do you use?

**Comment by Sopor** [comment]
I think he is running macos ...

**Comment by Thoxxx** [comment]
Mojave. I reinstalled ffmpeg with Homebrew and got 4.2.3 But still the same problem with QT Player. Works on VLC and Apple TV. Is there an updated svtplay-dl coming up?

**Comment by SYSophie** [comment]
@Thoxxx UWTD has released a version of it's custom svtplay-dl that supports it and made a PR for this repo.

**Comment by Thoxxx** [comment]
I'm sorry, I'm not sure how to get/use it

**Comment by Thoxxx** [comment]
I managed to get UWTD's version to run; git clone https://github.com/UWTD/svtplay-dl.git
Now the --version says svtplay-dl 2.4-42-g916e199
But still only 2 channels AAC

**Comment by UWTD** [comment]
@Thoxxx url yo the video?

**Comment by SYSophie** [comment]
@Thoxxx not all videos is using 5.1 it's still in testing. This is why @UWTD is asking which URL you're using as for the most part of the videos AAC 2-channel is still the highest rated audio available.

**Comment by Thoxxx** [comment]
Here are some URL:s that's in ac3 5.1 but svtplay-dl still only gives 2 channel AAC
https://www.svtplay.se/video/26844873/euphoria?start=auto
https://www.svtplay.se/video/26560142/normala-manniskor/normala-manniskor-sasong-1-avsnitt-1?start=auto
https://www.svtplay.se/video/27065201/the-frankenstein-chronicles/the-frankenstein-chronicles-sasong-2-prodigal-son
Even old series they stream again can sometimes be ac3: https://www.svtplay.se/video/18584390/akta-manniskor/akta-manniskor-sasong-1-avsnitt-1

Many new series and quite a few feature films are now 5.1

**Comment by Thoxxx** [comment]
You can see directly when svtplay-dl starts that it downloads a stereo m4a file first

**Comment by UWTD** [comment]
@Thoxxx https://delafil.se/4bf3f93822990487/svtplay-dl.rar

**Comment by Thoxxx** [comment]
I don't know how to use this...

**Comment by UWTD** [comment]
@Thoxxx Install python:
https://www.python.org/downloads/
Install PyYAML with command:
`pip install PyYAML`
Install cryptography with command:
`pip install cryptography`
then run svtplay-dl like this:
`python .\svtplay-dl https://www.svtplay.se/video/26844873/euphoria`


https://delafil.se/9d5277eb9750c71b/Ny_mapp[2].mp4

**Comment by Thoxxx** [comment]
I'm using macOS 10.14.6 (Mojave)
Are these commands for Mac?
Have installed python from their website
Have installed PowerShell (with brew). Don't know what it is
Should I do anything with this link you sent: https://delafil.se/4bf3f93822990487/svtplay-dl.rar
<img width="566" alt="Skärmavbild 2020-06-17 kl  00 05 34" src="https://user-images.githubusercontent.com/66281871/84833015-a3b8c180-b02e-11ea-8b2e-91afc6ebee64.png">

**Comment by UWTD** [comment]
Unpack the rar and make the command in the folder the svtplay-dl  is in. You can use terminal instead of powershell

**Comment by Thoxxx** [comment]
I placed the svtplay-dl file in my user folder
These are the results:
<img width="568" alt="Skärmavbild 2020-06-17 kl  01 04 55" src="https://user-images.githubusercontent.com/66281871/84836824-d8307b80-b036-11ea-8d5a-6eb100f31efd.png">
<img width="565" alt="Skärmavbild 2020-06-17 kl  01 06 17" src="https://user-images.githubusercontent.com/66281871/84836829-db2b6c00-b036-11ea-8a21-9ae72679e7bc.png">


I tried also to write python3 to use the latest version. Is that right?

**Comment by SYSophie** [comment]
@Thoxxx  please note that svtplay-dl requires that certain modules are pre-installed to work 
https://github.com/spaam/svtplay-dl/blob/master/README.md#from-source

In this text you will also see which python version is the lowest requirement.

**Comment by Thoxxx** [comment]
It's working now! Thank you
I have to write: python3 svtplay-dl URL
Only 'python' points to the built in Python 2.7

But the file is not playable in QuickTime, same problem as with youtube.dl
Any ideas?
Has to do with the merging, the mp4 plays if I 'grab' it before the merge

**Comment by UWTD** [comment]
From youtube-dl more then QuickTime have problems in some cases. But i can't se why QuickTime have problem with this merge. Is it the audio? Can you play the audio only file before merge in QuickTime?

**Comment by Thoxxx** [comment]
No, I can't play the m4a in QT player, but in VLC
The mp4 is OK before the merge

**Comment by UWTD** [comment]
Can you play other ac3 coded files in QT?

**Comment by Thoxxx** [comment]
That's probably it!
It plays 5.1 AAC but not ac3
I think it's a QuickTime Player thing

**Comment by spaam** [comment]
`2.5` have support it. it will download the file by default. use `--format-preferred` to choose what you want..
