### ISSUE TITLE
Is there really no one who has a solution to why dplay.se doesn't work anymore?

### ISSUE THREAD

**Issue by Pirrevirr** [spaam/svtplay-dl#1239]
Whatever I do, I always get in return:

ERROR: No videos found. You dont have permission to watch this.

Someone suggested that one must log out of the web browser in order for it to work, but that returns the same results for me. I've tried:

Staying logged on in browser and svtplay-dl [url]
Staying logged on in browser and svtplay-dl -u login -p password [url]
Logging out from browser and svtplay-dl [url]
Logging out from browser and svtplay-dl -u login -p password [url]

Every option gives me: "ERROR: No videos found. You dont have permission to watch this".

Thank you in advance.

**Comment by Sopor** [comment]
There is a template to follow for a reason ...

What version of svtplay-dl are you using?

Operating system?

Python version?

FFmpeg version?

**Comment by Pirrevirr** [comment]
> There is a template to follow for a reason ...
> 
> What version of svtplay-dl are you using?
> 
> Operating system?
> 
> Python version?
> 
> FFmpeg version?
> 
> URL you tried to download?
> 
> Did you add the --verbose switch?

Svtplay-dl version: svtplay-dl 2.4-2-g5466853
Os: Win 8.1
Python: Is it the python35.dll file?
FFmpeg: Not sure how to find that. I know it is installed, but I can't find where.
URL: https://www.dplay.se/videos/den-stora-halsoresan/sjukdom-staller-till-det-for-martin
When I add --verbose:

DEBUG [1591907149.7379558] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.
py/get_media: version: 2.4-2-g5466853
DEBUG [1591907149.7379558] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init_
_.py/__init__: service: dplay
DEBUG [1591907149.7379558] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/r
equest: HTTP getting 'https://www.dplay.se/videos/den-stora-halsoresan/sjukdom-s
taller-till-det-for-martin'
DEBUG [1591907149.7409577] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_new_conn: Starting new HTTPS connection (1): www.dplay.se:443
DEBUG [1591907150.3415303] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://www.dplay.se:443 "GET /videos/den-stora-halsoresan/sju
kdom-staller-till-det-for-martin HTTP/1.1" 200 None
DEBUG [1591907150.3435323] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/r
equest: HTTP getting 'https://disco-api.dplay.se/token?realm=dplayse&deviceId=a6
c9e9014e41b5cd5e0b7903471850e79c17284f29bef1284c4412b423e8f69b&shortlived=true'
DEBUG [1591907150.345534] C:\Python35\lib\site-packages\urllib3\connectionpool.p
y/_new_conn: Starting new HTTPS connection (1): disco-api.dplay.se:443
DEBUG [1591907150.5467262] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://disco-api.dplay.se:443 "GET /token?realm=dplayse&devic
eId=a6c9e9014e41b5cd5e0b7903471850e79c17284f29bef1284c4412b423e8f69b&shortlived=
true HTTP/1.1" 200 None
DEBUG [1591907150.5477276] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/r
equest: HTTP getting 'https://disco-api.dplay.se/content/videos/den-stora-halsor
esan/sjukdom-staller-till-det-for-martin'
DEBUG [1591907150.6007774] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://disco-api.dplay.se:443 "GET /content/videos/den-stora-
halsoresan/sjukdom-staller-till-det-for-martin HTTP/1.1" 200 None
DEBUG [1591907150.6017783] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/r
equest: HTTP getting 'https://disco-api.dplay.se/playback/videoPlaybackInfo/1328
90'
DEBUG [1591907150.6518264] C:\Python35\lib\site-packages\urllib3\connectionpool.
py/_make_request: https://disco-api.dplay.se:443 "GET /playback/videoPlaybackInf
o/132890 HTTP/1.1" 403 214
ERROR [1591907150.6528277] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.
py/get_one_media: No videos found. You dont have permission to watch this

The second message, you wrote I don't understand at all. What is a user-agent? How do I use self.headers.update({"User-Agent": FIREFOX_UA})?

Thank you.

**Comment by Sopor** [comment]
Is is a quite old version you are using. Even if i don't think it will solve your problem you should considering to [update](https://svtplay-dl.se/download/snapshots/).

When i login from Firefox i don't get any captcha so i don't know why i get it with svtplay-dl. Maybe it need a cookie?

**Comment by Pirrevirr** [comment]
An old version of what? The 2.4 version svtplay-dl is the one listed as the current?

Old Python?

 It obvious your knowledge is way higher than mine. What is a captcha? How do I give it a cookie? And I use Chrome but Firefox at work, but I have the same problem there.

**Comment by SYSophie** [comment]
@Pirrevirr there are already many issues covering this matter. I don't see why another one is needed?

Cookies are needed as they now use recaptcha and to bypass this you can use cookies and right now svtplay-dl don't have a function to utilise cookies, however youtube-dl does ([Link](https://github.com/spaam/svtplay-dl/issues/1192#issuecomment-609077867)). There has also been a solution presented to it also for svtplay-dl [Link](https://github.com/spaam/svtplay-dl/issues/1209#issuecomment-580756654)

**Comment by Sopor** [comment]
I have made some test with youtube-dl and i haven't manage it to work. I get the exact same error message every time whatever i try:
`ERROR: This video is only available for registered users. Use --username and --password or --netrc to provide account credentials.`

**Comment by Pirrevirr** [comment]
@SYSophie do you know how to solve it? What you wrote made no sense to me at all, nor did the links you refered to. :(

**Comment by SYSophie** [comment]
@Sopor you're supposed to use --cookies for youtube-dl followed by the path to the cookies file.
I also don't think the PR that was made is too old.

@Pirrevirr I would suggest then that you use UWTD and then that you use the cookies.txt file as instructed in the forum or that you simply read up on how-to use yt-dl.

**Comment by Sopor** [comment]
@SYSophie Yes, i have exported cookies.txt from Firefox and used the switch --cookies but it will not work whatever i do. I have tried using an empty cookie.txt too so youtube-dl can write its own cookie but i only get the above message.

**Comment by Pirrevirr** [comment]
@Sopor I got it now and I'm going to write you what no one seems to be able to explain in simple words.

Create the cookies.txt from the start page of Dplay, beeing loged in.
Place the cookies.txt-file in a folder that you can refer to. So I use Windows and I've just let is stay in my Download folder.

Then the command is:

youtube-dl --cookies /Users/[IN THIS CASE MY USERNAME]/Downloads/cookies.txt [URL]

Note. As I was behind on a serie, I downloaded 14 episodes. In some cases, I got an error, so I tried again, up to five times, and it worked.

Good luck!

**Comment by spaam** [comment]
woho. super late update .) the fix will only work with `-A` because you cant really copy the actual video url anymore from the browser..  anyway the snapshot `20200915_214418` you guys can download videos again with -A with some additional work. you need to get the `st` cookie to be able to download videos again. 

**how to get it**: first login to the site.  then you can use the `developer tools` in chrome and click on `network` tab, in firefox you need to open `web developer` then `network`. after you have done that reload the page. how to get the cookie in chrome  https://svtplay-dl.se/stuff/dplay-chrome.png  , it will be something similar in firefox. i guess other modern browsers work too.  . copy that `st` cookie until the `;`. then add it to the `--cookies st=value`  replace `value` with the long line you copy from your web browser :)

maybe i should write this somewhere else too 🤔 

i will release a new version tomorrow (16/9) evening .)
