### ISSUE TITLE
How to specify auth for --proxy?

### ISSUE THREAD

**Issue by ahmedtds** [spaam/svtplay-dl#1240]
Hi

How can I pass username and password for my proxy with --proxy option?

Thanks.

**Comment by spaam** [comment]
it should be something like `--proxy socks5://user:pass@host:port`. can you test if it works? :)

**Comment by ahmedtds** [comment]
tried things like that but couldn't manage to make it work

some notes:
my proxy is not socks5, it's https
my username contains @ character

I can manage to this work on youtube-dl:
`--proxy "blabla%40blala.com:password@proxy.proxyserver.com:80"`

but I couldn't manage anything to work on svtplay-dl.

tried above command, tried it with both %40 for @ character and with actual @ etc..

just can't get it work with sctplay-dl when everything is fine with youtube-dl

**Comment by spaam** [comment]
ahhhh okey.  for a quick look at the code for youtube-dl . at one place they add `http://` infront of the value you have in the proxy argument.  
did you try that?  🤔

**Comment by ahmedtds** [comment]
yeah tried with both http:// and https:// it just doesn't work. I think you have a problem with parsing the username and password

**Comment by spaam** [comment]
i just take the string and put it to proxy for http and https connections. then send it the `requests` who handles the http requests.

**Comment by ahmedtds** [comment]
ok maybe your dr.dk plugin is also broken. I will try with another site now.

**Comment by spaam** [comment]
dr.dk might be broken. i have not updated in a while.

**Comment by ahmedtds** [comment]
ok ok, made it work with svtplay.se, dr.dk is definitely broken.

still it may be a good idea mention how to specify auth in docs or somewhere. also %40 needs to be used for @ character, just a note for someone who stumbles upon this in the future.

**Comment by spaam** [comment]
thanks for testing and the suggestion <3
