### ISSUE TITLE
Capturing SVT live-stream has stopped working

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1246]
### svtplay-dl versions:
Run `svtplay-dl --version`
svtplay-dl 2.4-42-g916e199

The above is the python snapshot 20200602 which is the latest I've found
At my testing I've also used snapshot 20200328.

### Operating system and Python version:
Name and version of the operating system and python version (run `python --version`)
Windows 8.1 Pro x64
py --version
Python 3.7.4

### What is the issue:
Downloading live stream from SVTplay has suddenly stopped working.
This is a new behavior. I had no issue downloading a live stream starting 2020-08-23 00:45 (the movie "Room") from the same channel = svt1.

An example run to show the issue:

E:\tst>py c:\svtplaydll\svtplay-dl_sshot_20200602_154130\__main__.py -l -c 5 -v
-S https://www.svtplay.se/kanaler/svt1
DEBUG [1598367393.6820743] c:\svtplaydll\svtplay-dl_sshot_20200602_154130\svtplay_dl\utils\getmedia.py/get_media: version: 2.4-42-g916e199
DEBUG [1598367393.6820743] c:\svtplaydll\svtplay-dl_sshot_20200602_154130\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1598367393.6820743] c:\svtplaydll\svtplay-dl_sshot_20200602_154130\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/kanaler/svt1'
DEBUG [1598367393.6820743] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1598367393.744577] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /kanaler/svt1 HTT
P/1.1" 200 80311
ERROR [1598367393.7602003] c:\svtplaydll\svtplay-dl_sshot_20200602_154130\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find video info.

---------------------------------------------------------
The issue seems to be with live streams only.
My installation of svtplay-dl works fine with non-live SVTplay, for example
https://www.svtplay.se/video/1581756/glimt-av-norge/del-3-409

----------------------------------------------------------
A printout to show the successful case:
E:\tst>py c:\svtplaydll\svtplay-dl_sshot_20200602_154130\__main__.py https://www
.svtplay.se/video/1581756/glimt-av-norge/del-3-409
INFO: Selected to download dash, bitrate: 5281
INFO: Outfile: glimt-av-norge.i-egners-fotspar-a452368-svtplay.m4a
[025/226][====....................................] ETA: 0:00:37

**Comment by pythonuser3856** [comment]
I just tested a really old version 1.9.11 of svtplay-dl and that version *is* able to save a live stream !

**Comment by pythonuser3856** [comment]
Will this issue be addressed ?  The error remains present in the new veriosn 2.8.
I find it as a clear drawback to have to use version 1.9.11 to capture live-streams from SVT channels.
- for one this older release lack support for later added features such as 5.1 sound.
- another is the obvious hassle in adm that eventually comes from sofware forking.

**Comment by pythonuser3856** [comment]
Since this issue was posted some time ago I guess it will not be addressed.
What I do miss, and what this issue is about, is an option to try to capture 5.1 sound from live streams.
If that is anyway not an option I'm fine with continuing to use svtplay-dl version 1.9.11 to capture SVT channel live streams.

**Comment by SYSophie** [comment]
@pythonuser3856 there is no 5.1 sound for the channels live streams which can be observed in the manifests.

**Comment by pythonuser3856** [comment]
Ok, then the remaining issue is that latest official version of svtplay-dl is unable to capture.
But as I've mentioned, I'm fine with using the old version 1.9.11 for this.

**Comment by olof** [comment]
There's no reason to close this issue then, right? Even though nobody found time/motivation to work on it, it seems useful to have it documented. Especially the fact that it used to work (and still does with a previous version), that's really helpful for anybody taking on the task. (Feel free to close again if I misunderstood something.)

**Comment by pythonuser3856** [comment]
It's good to have got some comments to what I've reported. I'll leave as is.

**Comment by pythonuser3856** [comment]
A reply to the comment from SYSophie:
SVT announces that the film "Adult Players" scheduled to start at 2020-12-13 00:25 will be sent in 5.1 while it at the same time is *not* made available at SVTplay.
Could it perhaps be so that the available streams vary over time and an option of 5.1 is only available / detectable when it's in use by a TV channel ?  Why should SVT otherwise announce a use of 5.1 sound ?

**Comment by spaam** [comment]
latest snapshot will have a fix for this. 2.9 will be released tomorrow sunday.

**Comment by SYSophie** [comment]
> A reply to the comment from SYSophie:
> SVT announces that the film "Adult Players" scheduled to start at 2020-12-13 00:25 will be sent in 5.1 while it at the same time is _not_ made available at SVTplay.
> Could it perhaps be so that the available streams vary over time and an option of 5.1 is only available / detectable when it's in use by a TV channel ? Why should SVT otherwise announce a use of 5.1 sound ?
First of all SVT isn't requiring shows to be delivered to them with 5.1 sound.

2nd  SVT is also airing TV also terrestrial and them thru the channel SVT HD you can enjoy 5.1 if the show has been delivered with 5.1 audio.

Third, shows are distributed differently and not everything goes on SVTplay due to how they have negotiated the rights.

So SVT dö announcement of the use of 5.1 when it comes to SVT HD and when it's available and also on SVTplay on films when it's available.
