### ISSUE TITLE
TV4Play: No videos found

### ISSUE THREAD

**Issue by myhrmans** [spaam/svtplay-dl#1247]
### svtplay-dl versions:

2.4.2

### Operating system and Python version:

Ubuntu 20.04
Python 3.7.5

### What is the issue:
Trying to download any episode or all from example Idol will return "No Videos Found. Can't find json data"

Example test: 

> svtplay-dl --verbose https://www.tv4play.se/program/idol/12533692
DEBUG [1598596824.9292698] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.4-2
DEBUG [1598596824.9368095] /usr/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1598596824.9371562] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/idol/12533692'
DEBUG [1598596824.9471376] /home/myhrmans/.local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1598596825.3178446] /home/myhrmans/.local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/idol/12533692 HTTP/1.1" 200 None
ERROR [1598596825.3276823] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find json data

**Comment by roothen** [comment]
Not sure if it helps in any way and sorry for mentioning a "competitor" but youtube-dl seem to be able to get the video-stream so someone with a good development understanding may want to take a peak into how they do it. Although, they do not seem to be able to get the subtitle.

**Comment by myhrmans** [comment]
> Not sure if it helps in any way and sorry for mentioning a "competitor" but youtube-dl seem to be able to get the video-stream so someone with a good development understanding may want to take a peak into how they do it. Although, they do not seem to be able to get the subtitle.

Same results here.

**Comment by Bofinken** [comment]
Got the same problem, then tried with UWTD and no problem there

**Comment by suncore** [comment]
The patch from magic75 worked but I had to copy the change in line 45 to line 92 before it would work (I used the -A flag).

**Comment by roothen** [comment]
> The patch from magic75 worked but I had to copy the change in line 45 to line 92 before it would work (I used the -A flag).

The modified patched worked for me as well. (However, I did not test it without changing line 92.)

Thanks @magic75 and @suncore

**Comment by magic75** [comment]
Sorry, I always forget about the -A option since I don't use it...
The pull request should be updated now, thanks to @svallebro & @suncore

**Comment by KGBGit** [comment]
I made the changes in tv4play.py but there is no difference.

"svtplay-dl -S https://www.tv4play.se/program/morden-i-sandhamn/12579021
ERROR: No videos found. Can't find json data"

**Comment by suncore** [comment]
> I made the changes in tv4play.py but there is no difference.
> 
> "svtplay-dl -S https://www.tv4play.se/program/morden-i-sandhamn/12579021
> ERROR: No videos found. Can't find json data"

That works for me. Check you are using the right tv4play.py. I'm using a special svtplay-dl script to ensure I'm using the right libs:  

My svtplay-dl:

#!/usr/bin/env python3
# ex:ts=4:sw=4:sts=4:et
# -*- tab-width: 4; c-basic-offset: 4; indent-tabs-mode: nil -*-
import sys
sys.path.append('/a/linux/svtplay-dl/svtplay-dl/lib')
import svtplay_dl

if __name__ == "__main__":
    svtplay_dl.main()

**Comment by KGBGit** [comment]
Thank you for fast answer, unfortunally i'm a rookie in this.
Where and how do I use your script??

**Comment by anders55j** [comment]
@KGBGit which OS? This one worked on Windows for me: https://ci.appveyor.com/project/spaam/svtplay-dl/builds/35036953/artifacts

**Comment by KGBGit** [comment]
I'm om Mac Os mojave.
Anyway I will look for that zip, hopefully it will work.

Thanks for your answer.

**Comment by KGBGit** [comment]
Nej, suck, det var exe-varianten, gillas inte på Mac...

Finns det nån som kan förbarma sig...

**Comment by KGBGit** [comment]
No, that was for PC, will not run on Mac...

Are there anybody that can bring help in this matter??

**Comment by suncore** [comment]
Jag kan försöka hjälpa till men det kan vara lite trickigt. Behöver veta lite mer först. Jag kör Linux så jag vet inte vad som är samma.
Har du laddat ner git-repot?
Kör du ett CLI-fönster på macen där du kör scriptet?
Hur har du installerat svtplay-dl? Via make-fil eller laddat ner nåt?

På linux kan man köra ett kommando:
$ which svtplay-dl
för att ta reda på var scriptet ligger. Sen kan man ändra i scriptet. Då lägger man till raden med 
sys.path.append('/a/linux/svtplay-dl/svtplay-dl/lib')
Fast sökvägen ska vara det som passar på din mac där git-repot ligger.

**Comment by Sopor** [comment]
I made this [guide](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) for some time ago. You can try to follow that if you like.

**Comment by KGBGit** [comment]
Hej, tack.

Jag kör mac os.

Jag testade att köra which svtplay-dl, svaret var /usr/local/bin/svtplay-dl.

Vad är ett Git-repo?
Vad är CLI-fönster
Homebrew skötte nedladdning/uppdatering/installation, jag kör svtplay-dl i terminalen.

**Comment by suncore** [comment]
Ett git-repo är en databas med källkod, sånt som finns här på github :-)
Ett CLI-fönster är samma som en terminal.
Var ligger din tv4play.py fil någonstans, den du ändrade i?

**Comment by KGBGit** [comment]
Den ligger under min användare, så det var inte rätt.
Men under /usr/local/bin/ finns ingen tv4play.py.

Det finns däremot under /usr/local/cellar/...... och långt långt ner.
Så jag ändrade i den, men det hjälpte inte.

Fråga: Måste man göra något mer med den filen än att ändra? 
Python är väl intepreterande så en ändring behöver väl inte kompileras??

**Comment by suncore** [comment]
Det borde räcka att ändra den filen. Python behöver inte kompileras, bara ändra och köra. Jag vet inte vad det kan vara för problem. Kan inte mac, bara Linux...

**Comment by myhrmans** [comment]
> Den ligger under min användare, så det var inte rätt.
> Men under /usr/local/bin/ finns ingen tv4play.py.
> 
> Det finns däremot under /usr/local/cellar/...... och långt långt ner.
> Så jag ändrade i den, men det hjälpte inte.
> 
> Fråga: Måste man göra något mer med den filen än att ändra?
> Python är väl intepreterande så en ändring behöver väl inte kompileras??

Kolla om det finns någon fil under /usr/local/svtplay-dl/lib/svtplay_dl/service/tv4play.py

**Comment by KGBGit** [comment]
Under /usr/local/ finns ingen svtplay-dl alls.

**Comment by anders55j** [comment]
Måste bara kolla att du gör rätt ändring, det pratas ju om en fix på fixen ovan, men om du inte behöver -A så är det detta som behöver ändras: https://github.com/spaam/svtplay-dl/pull/1248/commits/fd7d923b2fd8ba0744b64d16a0e3e73c383ece84

**Comment by KGBGit** [comment]
Jodå, det är de två ändringarna plus den för -A.

**Comment by KGBGit** [comment]
Finally with the help of two times "brew uninstall svtplay-dl" followed by brew install... and some removals
ordered by brew plus the patches from above, my problem is solved.

Everything is working as expected, even the -A option.

Thank you very much for your help in bringing my problem to an end.

Thanks.

**Comment by spaam** [comment]
`2.5` have support for this :)
