### ISSUE TITLE
Specify codec for ffmpeg

### ISSUE THREAD

**Issue by krokerik** [spaam/svtplay-dl#1249]
Recently a lot of the movies on svtplay have started being encoded with 5.1 audio, which requires transcoding in Plex media player. Before this they were all in aac which could be played directly, I wouldn't mind the extra time taken for conversion at the time of download if it meant a smooth use when streaming. If it was in the configuration file you could also ensure the same codecs used even if you downloaded from all of the different sites supported. When downloading for private archiving uniformity is very convenient.

**Comment by spaam** [comment]
if you are using latest master or one of the newer snapshots. you can specify: `--format-preferred h264`. by default it will try to download the one with higher bitrate of stereo or 5.1. 
```
  --format-preferred h264,h264-51
                        Choose the format you prefer, --list-quality to show which one to choose from
```

i will release a new version beginning of next week.

**Comment by krokerik** [comment]
Is this also available in the configuration file, or will it be?

**Comment by spaam** [comment]
it is`2.5` have support for it.  the config value is `format_preferred`

**Comment by Sopor** [comment]
@spaam Can i specify different `format-preferred` for different services?

**Comment by spaam** [comment]
@Sopor yes just like other config values.

**Comment by Sopor** [comment]
@spaam And you shouldn't use something else than `format-preferred` so it is more obvious it is the sound (`soundformat-preferred`)?

**Comment by spaam** [comment]
@Sopor no. if you check for example svtplay, you can see with `--list-quality` it will list h265/hevc codecs too.  i choose to prefer using h264 over h265 because more stuff support that video codec.. if you want h265 just add it to the list in `--format-preferred`
