### ISSUE TITLE
Request for support for SolidSport (Same as SolidTango?)

### ISSUE THREAD

**Issue by mrcarlberg** [spaam/svtplay-dl#1253]
Request for support for SolidSport. I believe it is the same platform as SolidTango.

$ svtplay-dl --verbose https://solidsport.com/divari/watch/maalikooste-koovee-karhut-19-9-2020
DEBUG [1600598274.005526] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.5
DEBUG [1600598274.006911] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/service/__init__.py/__init__: service: generic
DEBUG [1600598274.006954] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://solidsport.com/divari/watch/maalikooste-koovee-karhut-19-9-2020'
DEBUG [1600598274.030688] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): solidsport.com:443
DEBUG [1600598275.411733] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://solidsport.com:443 "GET /divari/watch/maalikooste-koovee-karhut-19-9-2020 HTTP/1.1" 200 None
n <class 'svtplay_dl.service.solidtango.Solidtango'>
DEBUG [1600598275.417229] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/service/__init__.py/__init__: service: solidtango
DEBUG [1600598275.41731] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://edg02-prd-se-ixn.solidtango.com/cache/thumbnail/crop614x344/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg?cb=27a83ff9d6f28bb43c917bf551500f12'
DEBUG [1600598275.419308] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): edg02-prd-se-ixn.solidtango.com:443
DEBUG [1600598275.619601] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /cache/thumbnail/crop614x344/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg?cb=27a83ff9d6f28bb43c917bf551500f12 HTTP/1.1" 200 38658
DEBUG [1600598275.6224651] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sjisprober.py/feed: SHIFT_JIS Japanese prober hit error at byte 0
DEBUG [1600598275.622568] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/eucjpprober.py/feed: EUC-JP Japanese prober hit error at byte 0
DEBUG [1600598275.6226282] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/mbcharsetprober.py/feed: GB2312 Chinese prober hit error at byte 0
DEBUG [1600598275.62268] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/mbcharsetprober.py/feed: EUC-KR Korean prober hit error at byte 0
DEBUG [1600598275.622729] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/mbcharsetprober.py/feed: CP949 Korean prober hit error at byte 0
DEBUG [1600598275.6227798] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/mbcharsetprober.py/feed: Big5 Chinese prober hit error at byte 0
DEBUG [1600598275.622825] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/mbcharsetprober.py/feed: EUC-TW Taiwan prober hit error at byte 0
DEBUG [1600598275.647594] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: windows-1251 confidence = 0.040635358212770714, below negative shortcut threshhold 0.05
DEBUG [1600598275.668581] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: KOI8-R confidence = 0.042849223193165226, below negative shortcut threshhold 0.05
DEBUG [1600598275.687166] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: ISO-8859-5 confidence = 0.04337667458707876, below negative shortcut threshhold 0.05
DEBUG [1600598275.7043898] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: MacCyrillic confidence = 0.04210475041042962, below negative shortcut threshhold 0.05
DEBUG [1600598275.7217941] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: IBM866 confidence = 0.04297941822523311, below negative shortcut threshhold 0.05
DEBUG [1600598275.7402098] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: IBM855 confidence = 0.043805871094019795, below negative shortcut threshhold 0.05
DEBUG [1600598275.790115] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: ISO-8859-5 confidence = 0.04255076259761207, below negative shortcut threshhold 0.05
DEBUG [1600598275.8075268] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: windows-1251 confidence = 0.04001192082924237, below negative shortcut threshhold 0.05
DEBUG [1600598275.825506] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: TIS-620 confidence = 0.047763696506169934, below negative shortcut threshhold 0.05
DEBUG [1600598275.839679] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: ISO-8859-9 confidence = 0.04647370896685837, below negative shortcut threshhold 0.05
DEBUG [1600598275.866771] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: windows-1255 confidence = 0.041513051806045656, below negative shortcut threshhold 0.05
DEBUG [1600598275.8835871] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/sbcharsetprober.py/feed: windows-1255 confidence = 0.03959706479961277, below negative shortcut threshhold 0.05
DEBUG [1600598275.901778] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 not active
DEBUG [1600598275.90184] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: KOI8-R not active
DEBUG [1600598275.901867] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 not active
DEBUG [1600598275.90189] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: MacCyrillic not active
DEBUG [1600598275.901912] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM866 not active
DEBUG [1600598275.9019341] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: IBM855 not active
DEBUG [1600598275.901958] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-7 Greek confidence = 0.06620721614708128
DEBUG [1600598275.901982] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1253 Greek confidence = 0.06722369268394407
DEBUG [1600598275.902004] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-5 not active
DEBUG [1600598275.902025] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1251 not active
DEBUG [1600598275.902046] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: TIS-620 not active
DEBUG [1600598275.902066] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: ISO-8859-9 not active
DEBUG [1600598275.902092] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 Hebrew confidence = 0.0
DEBUG [1600598275.902195] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 not active
DEBUG [1600598275.902237] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/charsetgroupprober.py/get_confidence: windows-1255 not active
DEBUG [1600598275.902276] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: no probers hit minimum threshold
DEBUG [1600598275.902304] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: utf-8  confidence = 0.010000000000000009
DEBUG [1600598275.902335] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: SHIFT_JIS Japanese confidence = 0.01
DEBUG [1600598275.90236] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: EUC-JP Japanese confidence = 0.01
DEBUG [1600598275.902383] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: GB2312 Chinese confidence = 0.01
DEBUG [1600598275.902405] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: EUC-KR Korean confidence = 0.01
DEBUG [1600598275.902427] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: CP949 Korean confidence = 0.01
DEBUG [1600598275.9024482] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: Big5 Chinese confidence = 0.01
DEBUG [1600598275.9024699] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: EUC-TW Taiwan confidence = 0.01
DEBUG [1600598275.9024918] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1251 Russian confidence = 0.040635358212770714
DEBUG [1600598275.902515] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: KOI8-R Russian confidence = 0.042849223193165226
DEBUG [1600598275.9025369] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: ISO-8859-5 Russian confidence = 0.04337667458707876
DEBUG [1600598275.9025621] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: MacCyrillic Russian confidence = 0.04210475041042962
DEBUG [1600598275.902584] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: IBM866 Russian confidence = 0.04297941822523311
DEBUG [1600598275.9026072] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: IBM855 Russian confidence = 0.043805871094019795
DEBUG [1600598275.9026291] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: ISO-8859-7 Greek confidence = 0.06620721614708128
DEBUG [1600598275.90265] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1253 Greek confidence = 0.06722369268394407
DEBUG [1600598275.9026718] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: ISO-8859-5 Bulgairan confidence = 0.04255076259761207
DEBUG [1600598275.90276] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1251 Bulgarian confidence = 0.04001192082924237
DEBUG [1600598275.9027982] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: TIS-620 Thai confidence = 0.047763696506169934
DEBUG [1600598275.902826] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: ISO-8859-9 Turkish confidence = 0.04647370896685837
DEBUG [1600598275.902853] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1255 Hebrew confidence = 0.0
DEBUG [1600598275.902878] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1255 Hebrew confidence = 0.041513051806045656
DEBUG [1600598275.902903] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1255 Hebrew confidence = 0.03959706479961277
DEBUG [1600598275.9029682] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/chardet/universaldetector.py/close: windows-1255 Hebrew confidence = 0.03959706479961277
DEBUG [1600598275.904628] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://edg02-prd-se-ixn.solidtango.com/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'
DEBUG [1600598285.94707] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
DEBUG [1600598285.947374] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1600598285.9475882] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retry: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml
DEBUG [1600598295.9816499] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
DEBUG [1600598295.98206] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1600598296.5839229] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retry: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml
DEBUG [1600598306.613146] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
DEBUG [1600598306.6135402] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1600598307.8146229] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retry: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml
DEBUG [1600598317.833185] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
DEBUG [1600598317.8335328] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1600598320.237877] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retry: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml
DEBUG [1600598330.2543292] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
DEBUG [1600598330.254724] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1600598335.0581288] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/urlopen: Retry: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml
DEBUG [1600598345.133062] /usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://edg02-prd-se-ixn.solidtango.com:443 "GET /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml HTTP/1.1" 504 578
Traceback (most recent call last):
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 817, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 807, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/Cellar/svtplay-dl/2.5/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='edg02-prd-se-ixn.solidtango.com', port=443): Max retries exceeded with url: /api/v1/play/2b1324b3-6a68-4ca2-8ae9-a1a5457b5bdb.jpg.xml (Caused by ResponseError('too many 504 error responses'))

**Comment by spaam** [comment]
i have added support for username and password.   it will be included in 2.6 release.
