### ISSUE TITLE
Linux - Can't compile anymore :(

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1254]
When i try to compile svtplay-dl i now get this error:
```
$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 33, in <module>
    readme = f.read()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2390: ordinal not in range(128)
```

**Comment by spaam** [comment]
i cant reproduce this . there is no info about what python version or OS.

**Comment by Sopor** [comment]
I'm running Python 3.5.3 and Linux version is OSMC.

**Comment by spaam** [comment]
what does `locale` say?

**Comment by Sopor** [comment]
```
$ locale
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

**Comment by Sopor** [comment]
I have been compiling on this system for years now and it has always worked until today when i was going to compile a new version :(

**Comment by spaam** [comment]
i fucking hate python sometimes.

**Comment by spaam** [comment]
you should fix your locale to something better than `C`

**Comment by Sopor** [comment]
It seems that i can choose one of these
```
$ locale -a
C
C.UTF-8
POSIX
```

**Comment by spaam** [comment]
ööh okey, you dont have like `en_US.UTF-8`? i dont know how `C.UTF-8` is. never seen it before.  feels like a bad distribution without propper utf8 support in 2020.
anyway i commited something to master. it might work with C.

**Comment by Sopor** [comment]
You are the best, thanks!
```
Finished processing dependencies for svtplay-dl==2.5+4.ge92ebbb
```
