### ISSUE TITLE
Cannot find 'st' cookies

### ISSUE THREAD

**Issue by posktomten** [spaam/svtplay-dl#1265]
svtplay-dl version 2.7-3-ga550bd1 and 2.6
Python 2.7.18
Ubuntu 20.04
Error message: `ERROR: No videos found. Need the 'st' cookie to work`
Trying with these instructions from spaam
https://svtplay-dl.se/stuff/dplay-chrome.png
The problem is that I do not have a "users" tab.
http://bin.ceicer.com/streamcapture2/st.png
Chromium Version 86.0.4240.75 (Official Build) snap (64-bit)
Anyone see what I'm doing wrong?
Ingemar Ceicer

**Comment by spaam** [comment]
I made that picture when i logged in to the site.

but you should be able to see the cookie if you click on `Application` tab in `developer tools`  then on the left side click on `cookies` under the `storage` section on the left.  then on the middle screen you should see a bunch of cookies and one of them should be the `st` one

**Comment by posktomten** [comment]
Yes thank you!
`svtplay-dl -u myusername -p mypassword -S --cookies st="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZHBsYXlzZTo4Mzg3ZjZiZi1kMzdmLTQ4MmEtYmQ4MC0zZTU3MzZkYzk4MjMiLCJqdGkiOiJ0b2tlbi04ZTE1MDI1Mi03YTJhLTQzNWUtOWVlMS1hZTY2Y2VhMDhiMDMiLCJhbm9ueW1vdXMiOmZhbHNlLCJpYXQiOjE2MDI5MjQyNTF9.S0N5ynCIEVRFety6TErBFMaEKJscprffhxQNAAeIvOo" https://www.dplay.se/program/estonia-fyndet-som-andrar-allt`


Works properly. But only episode 3, of 5. I have tried
`--get-only-episode-url`
and
`--all-episodes`
but it does not work.
Thanks for the answer and your work with svtplay-dl!
Ingemar

**Comment by spaam** [comment]
You dont need the user and passwd with the cookie. And you want to remove the st cookie value in your post. Its something that is unique to you :)

**Comment by posktomten** [comment]
Hm, it works without username and password. Username and password are confirmed and a valid 'st' cookie is created. You should not publish your 'st' cookie ...

**Comment by posktomten** [comment]
Tack!
