### ISSUE TITLE
svtplay-dl download all episodes not working

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1266]
### svtplay-dl versions:

Hi I downloaded svtplay-dl in february this year.

Since then every option worked great, but now and since some weeks ago I cannot download all episodes from a tv-serie, my last test was Livstid.

Here's the command I used:
svtplay-dl -S -A " https://www.svtplay.se/video/28107792/livstid/livstid-sasong-1-livet-forstas-baklanges?start=auto"

The screen-dump of the error msg is attached

Cheers,
Torbjorn
![Skärmbild (16)](https://user-images.githubusercontent.com/33009810/96457861-90a64000-1220-11eb-8dad-20aa80b9f5c5.png)

**Comment by spaam** [comment]
it seems like you have a misstake in the url. you have an extra ` ` ( space )  efter `"`.  that might be the issue, can you try removing that to see if it works better? :)

**Comment by torbjornljung** [comment]
Just installed the latest windows version think it is 2.7. Now it works as before, same command. But thanks for your response.
