### ISSUE TITLE
UR Play videos are 'hard-coded' with subtitles

### ISSUE THREAD

**Issue by bohelax** [spaam/svtplay-dl#1267]
### svtplay-dl versions:

See text below

### Operating system and Python version:

Microsoft Windows [Version 10.0.18363.1110]
I haven't Python installed, simply using the .dll:s etc from the Windows .zip files.
ffmpeg version 4.2.2
VLC Media player 3.0.11 (jenkins@ee165b7cae4d Jun 4 2020 15:48:20)

### What is the issue:
spaam requested clarification of the title issue in a new ticket:

Downloading from UR Play first failed (for me) on 7/10-20. This was resolved pretty quickly.
A log of tested snapshots and releases follows:
svtplay-dl-amd64_20200930_191109.zip	-Fails ERROR: No videos found. Can't find json info
svtplay-dl-amd64_20201010_105959.zip	-Fails ERROR: No videos found. Can't find json info
svtplay-dl-amd64_20201010_113044.zip	-Works, i.e. finds something to download
svtplay-dl-amd64_20201010_131826.zip	-Works
svtplay-dl-amd64_20201012_130320.zip	-Works
svtplay-dl-amd64_20201012_172713.zip	-Works
svtplay-dl-amd64_20201012_173206.zip	-Works
svtplay-dl 2.7 :
svtplay-dl-win32_Latest windows 32bit .exe (currently 2.7).zip   (.exe dated 2020-10-12 00:24)		-Works
svtplay-dl-amd64_Latest windows 64bit .exe (currently 2.7).zip (.exe dated 2020-10-12 00:23)	-Works

Some terminology (invented by me):
By 'hard-coded' subtitles I mean that the text is actually burnt into the video stream and there i no way to avoid it.
(This is what SVT Play does for all foreign languages.)
By 'embedded' subtitles I mean what ffmpeg does in response to the -M option of svtplay-dl.
Apparently the text of the subtitles are stored in the .mp4, but it is up to the player (VLC in my case) to actually display
the subtitles on top of the video. This allows you to dynamically during playback choose to turn subtitles on of off.
This I consider a nice feature.
A quick summary of the relevant svtplay-dl options:
1) svtplay-dl           {URL}  Will download .ts -> .mp4,             only .mp4 remains with NO embedded subtitles
2) svtplay-dl    -M  {URL}  Will download .ts -> .mp4 and .srt, only .mp4 remains with       embedded subtitles
3) svtplay-dl -S       {URL}  Will download .ts -> .mp4 and .srt, both .mp4 and .srt remains with NO embedded subtitles
4) svtplay-dl -S -M {URL}  Will download .ts -> .mp4 and .srt, both .mp4 and .srt remains with        embedded subtitles
In cases 1 and 3 the remaining .mp4:s are identical (by a binary compare).
In cases 2 and 4 the remaining .mp4:s are identical (by a binary compare).
In cases 3 and 4 the remaining .srt:s are identical (by a binary compare).

Now to the actual issue:
It used to be the case that the videos from UR Play did NOT contain hard-coded subtitles, even for foreign languages.
In order to get subtitles you had to use -S and/or -M.
This made sense considering that UR Play may be used for foreign language training.
After the change (whatever UR Play did) all videos have hard-coded subtitles, even for Swedish-only programs!
This makes no sense for foreign language training programs, such a the short films in "Kortfilmsklubben" (UR Play).

All the tested versions of svtplay-dl (that works) give identical results.

A sample of a Swedish-only video I used during testing is "Svenska förklarad Del 16 Språkmelodier" found at:
https://urplay.se/program/218316-svenska-forklarad-sprakmelodier
I choose it also because it is short (75MB, 5 min) and is available until 2024.

Is there a way to get back the old behavior, i.e. videos *without* hard-coded subtitles?

//BoH

**Comment by bohelax** [comment]
Anything happening with this issue?

(I just tested the 20201102_220856 snapshot to no avail.)

I *really* hate hard-coded subtitles in Swedish-only programs!

I also greatly miss dynamic subtitles in English programs.

//BoH

**Comment by amigatomte** [comment]
> Anything happening with this issue?
> (I just tested the 20201102_220856 snapshot to no avail.)
> I _really_ hate hard-coded subtitles in Swedish-only programs!
> I also greatly miss dynamic subtitles in English programs.

I submitted a pull request to fix this two weeks ago, but it has not been accepted yet. 
You can try it yourself in the meantime: https://github.com/spaam/svtplay-dl/blob/e726dd8f6fed5832437bb4d30ea3752e057c0b03/lib/svtplay_dl/service/urplay.py

**Comment by spaam** [comment]
this will get in tonight :)

**Comment by bohelax** [comment]
Nothing in snapshot 20201113_103042

I have  a backlog of UR Play programs, some of which have now expired (not everything stay for a long time).

//BoH

**Comment by amigatomte** [comment]
> 
> 
> Nothing in snapshot 20201113_103042
> 
> I have a backlog of UR Play programs, some of which have now expired (not everything stay for a long time).
> 
> //BoH
Hi,
My pull request has still not been approved. However you could copy the new version of urplay.py from https://github.com/spaam/svtplay-dl/blob/e726dd8f6fed5832437bb4d30ea3752e057c0b03/lib/svtplay_dl/service/urplay.py and upgrade your local copy in the meantime.

Also, the latest version of youtube-dlc should work on urplay.se as well. https://github.com/blackjack4494/yt-dlc
Good luck!

**Comment by bohelax** [comment]
Hi there, amigatomte!

1) Interesting, but will it work with urplay.py? All I have is urplay.pyc in /service (and I don't have Python itself (yet, awaiting new hardware)).

2) I tried youtube-dlc.exe 2020.11.11-3 and found that it fails on some titles, but works on others. I don't want to get involved  in debugging another project too.

//BoH

**Comment by amigatomte** [comment]
Hi BoH! 

1. Oh, ok. That's strange, How do you install svtplay-dl and what operating system are you using? I used Python and the source code.
2. Really? I did the latest URPlay update on youtube-dlc. Could you please post the URL:s that didn't work, so I can fix it?

**Comment by amigatomte** [comment]
@spaam Any chance of merging this pull request soon?

**Comment by bohelax** [comment]
Hi amiga(forever)tomte!

1) Like it says in the first post of this thread I use Windows 10 and the stuff from the svtplay-dl-amd64.zip file.

2) Two URLs are:
https://urplay.se/program/208303-ugglornas-hemliga-liv
https://urplay.se/program/214637-norges-oonskade-tyskungar

//BoH

**Comment by spaam** [comment]
this should be fixed in 2.8. if not open a new ticket :)
