### ISSUE TITLE
Sound is partly missing on some clips???

### ISSUE THREAD

**Issue by MrMEEE** [spaam/svtplay-dl#1279]
### svtplay-dl versions:

Run `svtplay-dl --version`
svtplay-dl 2.7-4-gef557cb

### Operating system and Python version:

CentOS 7
Python 3.6.8

### What is the issue:

Some videos from viafree.dk looses audio after about 7 minutes???

These works:
https://www.viafree.dk/programmer/reality/forside-fruer/saeson-3/episode-1
https://www.viafree.dk/programmer/reality/forside-fruer/saeson-3/episode-2
https://www.viafree.dk/programmer/reality/forside-fruer/saeson-3/episode-3

These doesn't:
https://www.viafree.dk/programmer/reality/forside-fruer/saeson-3/episode-4
https://www.viafree.dk/programmer/reality/forside-fruer/saeson-8/episode-1

The ones that doesn't seem to have higher quality available, but even if I download a lower quality, they still doesn't have audio after 7 minutes

**Comment by spaam** [comment]
what version of ffmpeg do you have?

**Comment by MrMEEE** [comment]
3.4.8

**Comment by spaam** [comment]
this might be a ffmpeg issue and it works in ffmpeg 4.x

**Comment by MrMEEE** [comment]
Ok.. I will try and report back.. any feedback on: #1278 ?

**Comment by MrMEEE** [comment]
Yes, it works with ffmpeg 4 :).. thanks..
