### ISSUE TITLE
svtplay-dl -S -A don't work anymore

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1282]
**This command that used to work, i.e. all episodes including subtitles.**
**Tried to execute it after having downloaded the latest release, a few minutes ago.
Here's the command I used:**
svtplay-dl -S -A "https://www.svtplay.se/video/20495012/dips/dips-svensk-kinesiskt-pang-pang?start=auto"
![Skärmbild (68)](https://user-images.githubusercontent.com/33009810/99194594-a99f0400-2780-11eb-8d90-d0295346ce44.png)
**Here's a screen-dump of the svtplay-dl folder:**
![Skärmbild (69)](https://user-images.githubusercontent.com/33009810/99194625-df43ed00-2780-11eb-94bb-ba19c87c6cf2.png)
Cheers, Torbjorn

**Comment by SweDennis** [comment]
Hi,
This, I would think, is a Windows only error.
I just tried it on my Linux, using:

dennis@Lenovo:~/temp$ svtplay-dl --version
svtplay-dl 2.7+5.gbf1f9c5
dennis@Lenovo:~/temp$ 

dennis@Lenovo:~/temp$ python --version
Python 3.8.5
dennis@Lenovo:~/temp$ 

... and it all works fine. Just for everyone's reference.

Regards,
/Dennis

**Comment by SYSophie** [comment]
@torbjornljung please take a close look at the error message produced and the path that has been presented to you. Do these paths correspond with the folder of the folder that you claim is the new version?

Seems like your script is calling for a version located on a different disk and probably is old.

**Comment by torbjornljung** [comment]
Just reinstalled and copied FFMPEG to the folder, and tried again, same error. Command used: "svtplay-dl -S -A "some URL".
Wouldn't that be a clean install, without any references ?
It seems that oppetarkiv.pyc is causing the problems, it's in the \lib\svtplav-dl\service.
Removed it, but then I was told it was missing.
If you could give me some hints I could try to reinstall again

**Comment by SYSophie** [comment]
@torbjornljung installation guide is found here: [https://github.com/spaam/svtplay-dl#windows](https://github.com/spaam/svtplay-dl#windows)

**Comment by torbjornljung** [comment]
I think I've done what it says:
_**Install on Windows 
Download
You can download the latest release here. Unzip and run svtplay-dl.exe from a command prompt.**_
It doesn't say anything about Python and FFMPEG ? Just download and unzip. I don't understand what to do.
It describes a more complicated install from binaries, but it seems very complicated.

**Comment by hacker112** [comment]
Same problem on Mac OS X El Capitan 10.11.6, svtplay-dl 2.7.

```shell
$ svtplay-dl -S -A "https://www.svtplay.se/video/20495012/dips/dips-svensk-kinesiskt-pang-pang?start=auto"
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 66, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
    for n in janson[i]['items({"filter":{"includeFullOppetArkiv":false}})']:
KeyError: 'items({"filter":{"includeFullOppetArkiv":false}})'
```

**Comment by torbjornljung** [comment]
It works perfectly if I skip the -A option, i.e. svtplay-dl -S

**Comment by SYSophie** [comment]
> Same problem on Mac OS X El Capitan 10.11.6, svtplay-dl 2.7.
> 
> ```shell
> $ svtplay-dl -S -A "https://www.svtplay.se/video/20495012/dips/dips-svensk-kinesiskt-pang-pang?start=auto"
> Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 66, in main
>     get_media(urls[0], config, __version__)
>   File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
>     get_all_episodes(stream, url, options)
>   File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
>     episodes = stream.find_all_episodes(stream.config)
>   File "/usr/local/Cellar/svtplay-dl/2.7/libexec/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 220, in find_all_episodes
>     for n in janson[i]['items({"filter":{"includeFullOppetArkiv":false}})']:
> KeyError: 'items({"filter":{"includeFullOppetArkiv":false}})'
> ```

try the link without ?start=auto
So:

https://www.svtplay.se/video/20495012/dips/dips-svensk-kinesiskt-pang-pang

**Comment by torbjornljung** [comment]
Sorry, didn't work, same error😞

Den ons 18 nov. 2020 kl 10:40 skrev SYSophie <notifications@github.com>:

**Comment by vikekh** [comment]
I do experience the same problem on Ubuntu.

**Comment by SweDennis** [comment]
Hello Vikekh, which version of Ubuntu, svtplay-dl, and the rest are you running?
Like I commented above, I'm running Mint, based on Ubuntu, and I Don't experience the issue, perhaps it can help you.

Here's what I run, and it works for me:

dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-29-generic #31~20.04.1-Ubuntu SMP Fri Nov 6 16:10:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ 

dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 2.7+5.gbf1f9c5
dennis@Lenovo:~$ 

dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 

dennis@Lenovo:~$ ffmpeg --version
ffmpeg version N-54441-gaa5e49e46d-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers

Regards,
/Dennis

**Comment by spaam** [comment]
2.8 have a fixed. it was released yesterday evening. it should be available in the most places :)

**Comment by torbjornljung** [comment]
Thanks a lot ! Now it works 😋

fre 20 nov. 2020 kl. 15:43 skrev Johan Andersson <notifications@github.com>:
