### ISSUE TITLE
Request for future release

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#1283]
Hi svtplay-dl crew

Thanks for an extremely useful program. I really appreciate all the work you have put into it.

Here's my request:

I'm 95% done with the first version of a graphic interface to svtplay-dl. As you can imagine, the interface launches svtplay-dl and redirects the standard console output stream (and the standard error stream) to the program using output redirection. Unfortunately, what happens when that is done is that the streams are buffered in buffers with a default length of 4kb.

That means that I don't get the output texts from svtplay-dl in a consistant stream, but in chunks of 4kb, which makes progress reporting look extremely strange.

Apparently, from what I can tell on Google, there's nothing I can do to change that, but it seems like it could be fixed if you could tweak the way svtplay-dl buffers work, either by disabling buffering, changing the buffer size or flushing the buffers whenever something is written to the output stream.

Do you think it would be possible to do that?

Here's a few links to questions and responses about the problem, because apparently, it's a quite common problem:

https://stackoverflow.com/questions/3844267/how-to-disable-output-buffering-in-process-standardoutput
https://stackoverflow.com/questions/31152759/c-sharp-process-standard-output-delay
https://gist.github.com/antopor/5515bed636c3d99395ea
https://stackoverflow.com/questions/29128485/c-sharp-stream-pipe-stream-spy
http://www.cplusplus.com/reference/cstdio/setvbuf/

Screendump of the GUI application I'm doing in case anybody is curious... 
![bild](https://user-images.githubusercontent.com/3128989/99640717-94a8c600-2a49-11eb-834b-80e10cdcbdf9.png)

**Comment by spaam** [comment]
2.8 is out with ze fixes :)

**Comment by spaam** [comment]
ops this was something else..How do you hook the script into the app?  im using `sys.stderr` to write the progressbar thing.  have you looked at https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED ?

**Comment by spaam** [comment]
i guess you are using windows.  it is using py3.8 in the latest versions.

**Comment by JohnnyJorgensen** [comment]
Yes, I'm hooking the stderr output from Windows, DotNet... ;-)

**Comment by spaam** [comment]
try set the variable i linked to and see if it works better 🤔

**Comment by JohnnyJorgensen** [comment]
I'm sure this is a stupid question, but I'm a DotNet programmer and have never worked with Python. How would I go about changing a Python variable? Don't you have to do that in the Python code?

**Comment by spaam** [comment]
you dont have to touch python at all.  your function in your C# code that execute the binary should have some kind of method or something where you can set an environment variable.  we can do that in python. i bet C# have something similar.

**Comment by JohnnyJorgensen** [comment]
I found it - Learned something new today. Thanks!

It's better. Not 100% perfect, but acceptable. I believe we can close the issue.

Thanks again. I'll be back when I'm completely done with the first version... ;-)
