### ISSUE TITLE
Download only video? 

### ISSUE THREAD

**Issue by Nekleton1** [spaam/svtplay-dl#1286]
Is there a way to download only the video, skipping the audio? Every time I download a video, it downloads the audio first and then the video, and it takes much longer than it would take just downloading the video.

**Comment by spaam** [comment]
Right now there is no option for it because everyone want audio with their video. never had a use case when someone needed only video.

**Comment by SweDennis** [comment]
I have never had that need, personally, but I have definitely had reasons to want to only download the audio.
Perhaps, if one can be implemented, perhaps the other one will be available at a small cost.

Regards,
/Dennis

**Comment by spaam** [comment]
just looking at the code it will be like  3 places. two in dash and one hls where we check if the stream have audio. the adding the option to the argument parser and config stuff.

**Comment by SweDennis** [comment]
Sounds like a good Christmas present to me ...

**Comment by spaam** [comment]
Do we want `only audio` or do we only care about `only video`?  🤔

**Comment by SweDennis** [comment]
The case started as "Only Video", I just chimed in with my own need, i.e., "Only Audio", thinking that implementing one would give us two for the price of one, in implementation, or at least that was my hope. :-D

+1 for Audio Only, as well as the original need of the case starter, but I'm only one vote. :-D

Regards,
/Dennis

**Comment by SweDennis** [comment]
To me, it's rather priceless with Audio Only, interview programs, for instance, "Min Sanning", "Hellenius Hörna", "Skavlan" and whatnot. Previously I've had to split them up myself, put them on my phone, and listen to them as podcasts, problem being that streaming with video leaves video on, and for no reason draining the battery. It's really an app/Android issue more than svtplay-dl issue. If the phone allowed me to close screen, and keep the audio running, I wouldn't have the need, but this is why I chimed in, not having to split the video stream myself, extracting the audio. I could still keep on doing it, doesn't take lots of effort or thought, but still practical if svtplay-dl, could do it from the start. :-D

Regards,
/Dennis

**Comment by spaam** [comment]
i have implemented `--only-audio` and `--only-video`. this will only work with files when the files is separated, which most videos have now days.  you cant use both at the same time. this will be part of 2.9 release that will be released tomorrow evening. it will be available via snapshot today.

**Comment by SweDennis** [comment]
Absolutely great, it works for the things it works for, and when it doesn't, I'll just split them up afterwards, as I always have.
Many thanks for a great Christmas Present.

Regards,
/Dennis

**Comment by SweDennis** [comment]
Just updated to
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 2.8+3.g18a8758
dennis@Lenovo:~$ 

The option --only-audio works like a charm, I think you can safely release ... :-D

Regards,
/Dennis
