### ISSUE TITLE
Dplay changed name to discovery+

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#1304]
Need to add support for it

**Comment by spaam** [comment]
it seems to be just a rename of the domain. everything else seems to work like before.

**Comment by spaam** [comment]
it will be fixed in 2.9 later today

**Comment by Faster22** [comment]
I can´t get this to work am i missing some command?

**Comment by Usernamnet** [comment]
Works fine after putting in command line.
`svtplay-dl --cookies st="min kaka" [https://www.discoveryplus.se/videoid]`
but how do i put the `--cookies st="`" to the config-file instead? so that i dont have to type it for every line in svtplay-dl

**Comment by spaam** [comment]
@Usernamnet https://svtplay-dl.se/config/ 
```
service:
  dplay:
    cookies: st="KalleAnka"
```
but i found a bug related to it  #1316 

this issue is fixed. but config cookie is unrelated to this.

**Comment by Usernamnet** [comment]
> 
> 
> @Usernamnet https://svtplay-dl.se/config/
> 
> ```
> service:
>   dplay:
>     cookies: st="KalleAnka"
> ```
> 
> but i found a bug related to it #1316
> 
> this issue is fixed. but config cookie is unrelated to this.

Yeah 
service:
   dplay:
      cookies: st="mycookie"

Does not work.
