### ISSUE TITLE
Download failure from URplay.se

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1308]
**svtplay-dl versions:**
svtplay-dl v2.8 python code
snap-shot 201231_141922 python code

**Operating system and Python version:**
python 3.7.4
windows 8.1 64-bit

**What is the issue:**

svtplay-dl is unable to download from URplay.se
Some example links with failure:
https://urplay.se/program/214782-skrapet-pa-mount-everest
https://urplay.se/program/215795-91-ar-och-vinterbadare
https://urplay.se/program/216564-harlems-soldater-i-forsta-varldskriget
(basically all links that I test now fails)

The failure is also at hand with items/links which previously could be downloaded from URplay.se
An example link of this is:
https://urplay.se/program/216564-harlems-soldater-i-forsta-varldskriget

**Execution trace of svtplay-dl:**
py e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\__main__.py --verbose https:
//urplay.se/program/214782-skrapet-pa-mount-everest
DEBUG [1610613253.783133] e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\utils\getmedia.py/get_media: version: 2.8-9-gc3ff052
DEBUG [1610613253.783133] e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\service\__init__.py/__init__: service: urplay
DEBUG [1610613253.783133] e:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtplay_dl\utils\http.py/request: HTTP getting 'https://urplay.se/program/214782-skrapet-pa-mount-everest'
DEBUG [1610613253.783133] C:\Program Files\Python37\lib\site-packages\urllib3\co
nnectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1610613253.8681438] C:\Program Files\Python37\lib\site-packages\urllib3\c
onnectionpool.py/_make_request: https://urplay.se:443 "GET /program/214782-skrap
et-pa-mount-everest HTTP/1.1" 200 40210
ERROR [1610613253.8881602] c:\svtplaydll\svtplay-dl_sshot_20201231_141922py\svtp
lay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find json info

**Comment by bohelax** [comment]
Yeah, I guess UR Play started a new season by screwing with us again!

Also as usual it's a show stopper.
//BoH

**Comment by pythonuser3856** [comment]
Thanks for the fast fix on the snapshot branch
/L-B
