### ISSUE TITLE
Urplay ERROR: No videos found. Can't find json info

### ISSUE THREAD

**Issue by leipet** [spaam/svtplay-dl#1309]
### svtplay-dl versions:

svtplay-dl 2.8

### What is the issue:

https://urplay.se/program/214607-filmer-fran-ett-svunnet-singapore-det-brittiska-imperiet
ERROR: No videos found. Can't find json info

**Comment by pythonuser3856** [comment]
See issue #1308

**Comment by spaam** [comment]
this should be fixed in 2.9
