### ISSUE TITLE
add support for svt.se/recept 

### ISSUE THREAD

**Issue by raveslave** [spaam/svtplay-dl#1310]
would be great if videos listed under https://www.svt.se/recept/ would work 🥇

**Comment by spaam** [comment]
i have clicked around on that site and i cant find any videos.

**Comment by raveslave** [comment]
https://www.svt.se/recept/cupcakes-med-bar-och-farskostfrosting

**Comment by spaam** [comment]
great. now it will be easier to fix :)

**Comment by raveslave** [comment]
awesome!
