### ISSUE TITLE
Jag har lyckats med att installera två olika versioner av svtplay-dl.

### ISSUE THREAD

**Issue by Ferbd-Git** [spaam/svtplay-dl#1314]
### svtplay-dl versions:

Run `svtplay-dl --version`
svtplay-dl 2.8-14-g4aa528b

### Operating system and Python version:
linux ubuntu 20.04

Name and version of the operating system and python version (run `python --version`)
Python 3.8.5

### What is the issue:

Problemet är att jag installerade först den "Debian and Ubuntu" installationen och sedan "For any linux".
Nu, när jag vill veta vilken version jag har, får jag:
svtplay-dl --version
svtplay-dl 2.8-14-g4aa528b

Men, om jag vill installera, får jag följande:

sudo apt-get install svtplay-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
svtplay-dl is already the newest version (2.9-1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

Så att jag får konflikt mellan två olika versioner.
Jag vet inte hur jag kan avinstallera för att rensa min dator från svtplay-dl och sedan kunna installera om den för att få den att fungera.

    svtplay-dl --verbose https://www.example.com

**Comment by spaam** [comment]
vad säger `which svtplay-dl`? 
om den säger något som inte är `/usr/bin/svtplay-dl`.  ta bort det `which` kommandot skrev ut.  tex  om `which` kommandot skriver ut tex `/usr/local/bin/svtplay-dl`  skriv `sudo rm /usr/local/bin/svtplay-dl`  efter du har gjort det. skriv sedan `hash -r`
efter det så borde  `svtplay-dl --version` skriva ut `2.9`

**Comment by EmmW** [comment]
Hej spaam,

Jag har samma problem (fast jag kör Mac OSX 10.14.6) -- en svtplay-dl-version som jag har installerat via homebrew och en som jag har lyckats installera på något annat sätt... :-)

När jag kör "brew upgrade svtplay-dl" så får jag 2.9 installerad, men när jag sedan kör "svtplay-dl --version" så får jag fortfarande "svtplay-dl 2.8-14-g4aa528b". Du tipsade mig tidigare om att köra "cd /Users/[min mapp]/svtplay-dl" (den mapp där jag verkar ha den aktiva versionen?) följt av "git pull" följt av "sudo python3 setup.py install", och när jag gör det och därefter kollar "svtplay-dl --version" så får jag äntligen "svtplay-dl 2.9"!

Men då det känns lite rörigt med två olika versioner på detta vis vore det toppen om det går att radera den felaktiga installationen en gång för alla. Jag kör därför "which svtplay-dl" och får då följande svar: "/Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl". Skall jag därmed köra "sudo rm /Library/Frameworks/Python.framework/Versions/3.5/bin/svtplay-dl" följt av "hash -r", och sedan flytta mappen "Users/[min mapp]/svtplay-dl" (om det nu är den aktiva versionen) till en annan mapp? Du skriver ovan att den skall ligga i "/usr/bin", men någon sådan mapp har jag väl inte på Mac?

Tack på förhand för tips/instruktion!

Mvh Mark

**Comment by Ferbd-Git** [comment]
Hej, jag har kört: 
sudo rm /usr/local/bin/svtplay-dl
Också  hash -r
Efter det, resultat på --version blir så här:
svtplay-dl --version
Command 'svtplay-dl' not found, but can be installed with:
sudo apt install svtplay-dl

Fastän jag försökte att installera om:

sudo apt-get install svtplay-dl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
svtplay-dl is already the newest version (2.9-1).
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.

Dvs. det verkar så att svtplay-dl finns någonstans i min dator?

Tackar så mycket för hjälpen.

**Comment by spaam** [comment]
@Ferbd-Git , det är för att du har tagit bort den körbara filen och pakethanteraren (apt) tror att du har det fortfarande installerat. testa med att återinstallera det igen `apt reinstall svtplay-dl` så borde de funka :) 


@EmmW iom du använde `setup.py` grejen, vad säger `pip3 list`? ser du `svtplay-dl` där?  om så, kör `pip3 uninstall svtplay-dl` .   för att installera det via brew igen så måste du nog köra `brew reinstall svtplay-dl`

**Comment by Ferbd-Git** [comment]
Hej spaam, tackar för hjälpen, det fungerade med "apt reinstall svtplay-dl"
Nu sitter den på plats igen och jag har testat att den fungerar.
Min fru blir jätte glad, hon väntade på Husdrömmar.

**Comment by EmmW** [comment]
@spaam  Skumt! När jag kör "pip3 list" får jag följande svar: "svtplay-dl 2.4" -- trots att jag tidigare bara fått fram "svtplay-dl 2.8-14-g4aa528b" samt, efter git pull-grejen, "svtplay-dl 2.9"... Det verkar som om jag lyckats få in hela *tre* olika svtplay-dl-versioner i systemet :-).

Hur som helst, jag körde "sudo pip3 uninstall svtplay-dl" för att ta bort den där gamla 2.4, och när jag efter detta körde "pip3 list" igen så stod det nu plötsligt "svtplay-dl 2.9" i stället, så nu verkar det ju faktiskt funka! Jag körde även "which svtplay-dl" och fick då följande svar: "/usr/local/bin/svtplay-dl" -- tror du allt står rätt till i systemet nu så att jag bara kan köra "brew upgrade svtplay-dl" som vanligt när det kommer en ny version (utan att behöva köra git pull-grejen)?

Mvh Mark

**Comment by spaam** [comment]
@EmmW  beror på hur du har installerat det :) men  om `svtplay-dl --version` kommer upp som `2.9` är de nog rätt. om du installerar det via brew så kommer den säkert klaga att `/usr/local/bin/svtplay-dl` finns redan :)

**Comment by spaam** [comment]
i guess this is fixed :)
