### ISSUE TITLE
Problem with swedish subtitle from Viafree

### ISSUE THREAD

**Issue by Usernamnet** [spaam/svtplay-dl#1315]
### svtplay-dl versions:

svtplay-dl --version
svtplay-dl 2.9

### Operating system and Python version:

Windows 10

### What is the issue:

Jag har problem med att få ner svensk text från Viafree

    svtplay-dl -S https://www.viafree.se/program/humor/ridiculousness/sasong-17/avsnitt-1
ger mig dansk text. 
Jag har även testat viafree.no och .dk. får inte ner svensk text.
har även testat
svtplay-dl --all-subtitles https://www.viafree.se/program/humor/ridiculousness/sasong-17/avsnitt-1
då får jag fortfarande bara ner en dansk text

**Comment by spaam** [comment]
fy fan :(  låter hemskt :(
