### ISSUE TITLE
SVT ERROR: No Videos Found. Can't Find Video Info

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1317]
This command used to work perfectly up until yesterday, now I get this error.
Here's the command I issue:
**svtplay-dl -S "https://www.svtplay.se/video/29962654/en-mordare-bland-oss/en-mordare-bland-oss-sasong-1-avsnitt-1?**start=auto"
I'm running Windows 10.
Please try it, and see if it works for you ?

**Comment by spaam** [comment]
what version of svtplay-dl are you using? i released 2.9 yesterday with a fix.

**Comment by torbjornljung** [comment]
Hi ! I'm using version 2.8, Could you please tell me how to download and install 2.9(Windows) the easiest way ?

**Comment by spaam** [comment]
https://svtplay-dl.se/archive/ is a good place for it :)

**Comment by torbjornljung** [comment]
Thanks a lot for your excellent and super-fast support !
