### ISSUE TITLE
Wrong quality downloaded from svt-play

### ISSUE THREAD

**Issue by xfors** [spaam/svtplay-dl#1318]
### svtplay-dl versions:

svtplay-dl 2.9

### Operating system and Python version:

Ubuntu 18.04.1 LTS, 4.15.0-112-generic
Python 3.6.9

### What is the issue:

The downloaded files bitrate doesn't match the desired and stated bitrate

In the example below svtplay-dl claims it's downloading bitrate 2803, but according to ffprobe it's only 1760

/usr/bin/svtplay-dl -q 2700 -Q 900 -P dash https://www.svtplay.se/video/29997566/atlantic-crossing/atlantic-crossing-sasong-1-over-atlanten
INFO: Outfile: atlantic-crossing.s01e03.3-over-atlanten-7eac4f8.srt
INFO: Selected to download dash, bitrate: 2803 format: h264-51
INFO: Outfile: atlantic-crossing.s01e03.3-over-atlanten-7eac4f8.m4a
[858/858][=============================================================================================================================================================================================] ETA: 0:00:00
INFO: Outfile: atlantic-crossing.s01e03.3-over-atlanten-7eac4f8.mp4
[858/858][=============================================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into atlantic-crossing.s01e03.3-over-atlanten-7eac4f8.mp4
INFO: Merging done, removing old files.

ffprobe version 4.3.1-0york0~18.04 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'atlantic-crossing.s01e03.3-over-atlanten-7eac4f8.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:54:50.62, start: 0.000000, bitrate: 1760 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 960x540 [SAR 1:1 DAR 16:9], 1307 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(swe): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Side data:
      audio service type: main

**Comment by spaam** [comment]
yeah its a somewhat known issue. 

to quote https://github.com/axiomatic-systems/Bento4/issues/158#issuecomment-311733153 :
> The reason you are seeing a different value for the bandwidth in the MPD and from ffmpeg/mediainfo is because the MPD value is computed in a different way, in order to comply with the specification. The bandwidth reported by ffmpeg or mediainfo is the average bandwidth for the stream (number of bytes divided by duration), whereas for the MPD the calculation is done by segment, and also based on the buffer model, that takes the minBufferTime into account. To be more specific, the value is an indication to the player that if it starts playing after having buffered 'minBufferTime', and if the network bandwidth is exactly the value in the MPD, then the buffer will never completely empty. So if your encoder creates segments for which the average bitrate for the segment is higher, or if within a segment you have a higher bitrate at some point of the the segment than other points, you will see the MPD bandwidth value be somewhat different from the stream's average bandwidth.

the bitrate i use is the extracted `bandwith` entry in the playlist for the streams and then add audio bitrate / bandwith  and video bitrate / bandwith together.   (audio 448908  + video 2354178) / 1000  = 2 803
here we can see the audio is close to what ffmpeg say. the video is a bit off.
there is no easy way to get the correct bitrate of the files without downloading all of them. a lot of data will be wasted.

**Comment by xfors** [comment]
OK, thanks!
I just had a feeling that bitrates were more aligned before the latest update of the svtplay web interface. Guess that's just a coincidence then.
