### ISSUE TITLE
svtplay

### ISSUE THREAD

**Issue by jula420** [spaam/svtplay-dl#1319]
### svtplay-dl versions:

svtplay-dl 2.9

### Operating system and Python version:

Ubuntu 20.04 Python 3.8.5 

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl -t https://www.svtplay.se/video/29764366/rapport/rapport-10-feb-12-00-1

will crash and not download thumbnail.

This helps but maybe there is more to it.
```
--- a/lib/svtplay_dl/service/svtplay.py
+++ b/lib/svtplay_dl/service/svtplay.py
@@ -344,7 +344,10 @@ class Svtplay(Service, MetadataThumbMixin):
         self.output["title_nice"] = episode["parent"]["name"]
 
         try:
-            t = episode["parent"]["image"]["id"]
+            pid = episode["parent"]["image"]["id"]
+            changed = episode["parent"]["image"]["changed"]
+            url = "https://www.svtstatic.se/image/original/default/{pid}/{changed}?format=auto&quality=100".format(pid,changed)
+            self.output["showthumbnailurl"] = url
         except KeyError:
             t = ""
         if isinstance(t, dict):
```

**Comment by spaam** [comment]
thank you for the bug report, it will be fixed in the next release `3.0` later this week.  if you feel brave you can use a snapshot until then.
