### ISSUE TITLE
Felaktiga/ofullständiga undertexter från UR-play

### ISSUE THREAD

**Issue by bjoro80** [spaam/svtplay-dl#1324]
### svtplay-dl versions:
svtplay-dl 3.0

### Operating system and Python version:
Mac OS Big Sur 11.2

Name and version of the operating system and python version (run `python --version`)
Python 2.7.16

### What is the issue:

Jag har laddat ner ett antal dokumentärer från UR-play där den nedladdade textningen inte stämmer överens med den jag får se om jag kör programmet direkt på UR-play. Jag förstår inte mönstret, men rätt vad det är så saknas en textrad. Öppnas textfilen är det lätt att hitta exempel där rad 2 saknas.

Jag gissar att det är ett problem rakt över, men här är en dokumentär där det är problem:

svtplay-dl -S -M --verbose https://urplay.se/program/215798-koreakriget-det-glomda-kriget

Hoppas jag fått med all önskvärd information. Har inte felrapporterat tidigare och är allmän novis på detta område.

**Comment by spaam** [comment]
informationen är bra  och ja ser problemet.  får klura ut hur man ska fixa problemet ikväll :)

**Comment by bjoro80** [comment]
Så bra, både att jag sköter mig och att problemet syns. :) Tackar och bockar och hoppas det går hitta en lösning!

**Comment by SYSophie** [comment]
> informationen är bra och ja ser problemet. får klura ut hur man ska fixa problemet ikväll :)

I would suggest using vtt instead of tt. They use a replace function from tt to vtt themselves(Source:[application-39609ea3b95074435cb7.js](https://urplay.se/assets/packs/js/application-39609ea3b95074435cb7.js).)
Snippet:

`file: (t = e.tt.location, t.replace(".tt", ".vtt")),`
So:
`https://undertexter.ur.se/215000-215999/215798-13.tt`
becomes:
`https://undertexter.ur.se/215000-215999/215798-13.vtt`

**Comment by spaam** [comment]
@SYSophie good catch, with that it will be even easier fix instead of having to play around with xml :)

**Comment by bjoro80** [comment]
Att ärendet är stängt nu innebär att det är fixat? Antar att jag behöver uppdatera eller ladda ner någon fix i så fall för att att få det att fungera korrekt? Jag är en glad användare snarare än tekniskt bevandrad så ber om ursäkt om jag ställer korkade frågor.

**Comment by spaam** [comment]
ja det är fixat men det finns bara i en snapshot release än, finns på hemsidan om du vill testa.  kommer släppa nästa version imorgon kväll med fixen.
