### ISSUE TITLE
Error at download of livestreaming from SVTBarn

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1325]
**svtplay-dl version:**
svtplay-dl snap-shot 20210216 225742 (python code)

**Operating system and Python version:**
python 3.7.4
windows 8.1 64-bit

**The error trace that I get:**
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\getmedia.py/get_media: version: 3.0-1-g0bcf162
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/kanaler/svtbarn'
DEBUG [1613541998.7442403] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1613541998.822385] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /kanaler/svtbarn HTTP/1.1" 200 56646
DEBUG [1613541998.8379982] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/ch-svtbarn'

DEBUG [1613541998.8379982] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1613541998.9630234] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/ch-svtbarn HTTP/1.1" 404 38
ERROR [1613541998.9630234] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by pythonuser3856** [comment]
Related to similar error resolved in #1246 ?

**Comment by pythonuser3856** [comment]
Perhaps I'm too quick to comment (?) but it still fails using snapshot 20210220_131303 while I at the same time can use FireFox to view the channel.

**The execution trace that I get:**
svtplay-dl --live --verbose https://www.svtplay.se/kanaler/svtbarn
DEBUG [1613827856.3733141] e:\svtplaydll\svtplay-dl_sshot_20210220_131303py\svtplay_dl\utils\getmedia.py/get_media: version: 3.0-3-g32ba346
DEBUG [1613827856.374315] e:\svtplaydll\svtplay-dl_sshot_20210220_131303py\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1613827856.3753154] e:\svtplaydll\svtplay-dl_sshot_20210220_131303py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/kanaler/svtbarn'
DEBUG [1613827856.3793206] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1613827856.9999146] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /kanaler/svtbarn HTTP/1.1" 200 None
DEBUG [1613827857.0399535] e:\svtplaydll\svtplay-dl_sshot_20210220_131303py\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/ch-svtbarn'
DEBUG [1613827857.0419555] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1613827857.1550643] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/ch-svtbarn HTTP/1.1" 404 38
ERROR [1613827857.156065] e:\svtplaydll\svtplay-dl_sshot_20210220_131303py\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by spaam** [comment]
you are right. svtplay with they naming schema.. their path to barnkanalen is svtbarn ..  :(

**Comment by spaam** [comment]
should be fixed now

**Comment by pythonuser3856** [comment]
Confirmed to work with snapshot 20210220_151316.
Many Thanks !
