### ISSUE TITLE
TV4Play - -A switch doesn't always download all episodes

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#1327]
### svtplay-dl versions: 

3.0

### Operating system and Python version:

Windows 10, Python unknown (command line command just says that Python isn't installed).

### What is the issue:

When a season contains more than 12 episodes, svtplay-dl just fetches the first 12. That is probably because TV4Play just lists the first 12 with a "Show more" button you have to click to see the remaining.

Example:
svtplay-dl.exe -A https://www.tv4play.se/program/brottet
INFO: Episode 1 of 32
INFO: Url: https://www.tv4play.se/program/brottet/13309665

It only fetches the first 12 episodes of season 1's 20 episodes, and all 10 episodes from season 2 and all 10 episodes from season 3, which it surprisingly enough finds even though they are hidden in a tab system.

Cheers,
Johnny J.

**Comment by spaam** [comment]
thanks for the bug report <3

i finally found a good way for this. i have commited a fix for this and i will release a new version tomorrow evening with the fix. 

```
INFO: Episode 1 of 40
```
