### ISSUE TITLE
svtplay.find_all_episodes errors if no episodes available

### ISSUE THREAD

**Issue by jagot** [spaam/svtplay-dl#1331]
### svtplay-dl versions:

svtplay-dl 2.9+7.g664a9e2

### Operating system and Python version:

$ python --version
Python 3.9.1

$ uname -ra
Linux R2D2 5.10.16-arch1-1 #1 SMP PREEMPT Sat, 13 Feb 2021 20:50:18 +0000 x86_64 GNU/Linux

### What is the issue:

I call methods of the Python library directly to find episodes available for a series and found that since some time back, if no episodes are available, `svtplay.find_all_episodes` errors instead of just returning an empty list.

For a series with no episode available:
```bash
$ svtplay-dl -A "https://www.svtplay.se/friday-night-dinner"
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 59, in get_media
    get_all_episodes(stream, url, options)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 77, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 213, in find_all_episodes
    if "listablesBy" in key and data[0]["associatedContent"][0]["id"] != "related":
IndexError: list index out of range
```

For a series with one upcoming episode, but none available currently:
```bash
$ svtplay-dl -A "https://www.svtplay.se/stan-lees-lucky-man"
ERROR: Can't find other episodes.
```

**Comment by spaam** [comment]
thanks for the bug report <3 
it have been fixed already in #1322 and it will be out in the next version late today. if you cant wait you can test a snapshot. :)
