### ISSUE TITLE
svtplay.se downloads now fail after the site got a new look (AttributeError: 'Svtplay' object has no attribute 'visibleid')

### ISSUE THREAD

**Issue by towil1** [spaam/svtplay-dl#1335]
### svtplay-dl versions:

svtplay-dl 3.1-5-gcb3612b

### Operating system and Python version:

Ubuntu 18.04 LTS
Python 3.6.9

### What is the issue:

svtplay-dl --verbose https://www.svtplay.se/video/1955994/mia-och-klara/del-1-1841
DEBUG [1615374578.4392328] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 3.1-4-g998f51f
DEBUG [1615374578.446188] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1615374578.4471166] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/1955994/mia-och-klara/del-1-1841'
DEBUG [1615374578.4481726] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: TOWIL proxy None
DEBUG [1615374578.4524174] /home/towil/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1615374578.5907476] /home/towil/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/1955994/mia-och-klara/del-1-1841 HTTP/1.1" 200 33071
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 83, in get
AttributeError: 'Svtplay' object has no attribute 'visibleid'

**Comment by spaam** [comment]
interesting. i dont get this error at all 🤔

**Comment by towil1** [comment]
The old look is back now, thats why it is working again. Ttoo bad I didn't take a screen shot, it was quite neat.

**Comment by Ferbd-Git** [comment]
Idag fungerar igen.
Jag kan ladda ner idag en film som det inte gick att ladda ner igår.

**Comment by pythonuser3856** [comment]
I have what seems to be the same issue with the link
https://www.svtplay.se/video/30167492/blind-spot
The link was just made available at svtplay.se

Windows 8.1 64-bit
python version 3.1 of svtplay-dl
python 3.7.4

crash trace:
-
py e:\svtplaydll\svtplay-dl_v3.1\__main__.py --subtitle --verbose https://www.svtplay.se/video/30167492/blind-spot
-
-------------------
2021-03-11 14:47:59
-------------------
DEBUG [1615470479.6067364] e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\utils\getmed
ia.py/get_media: version: 3.0-7-ge423c1c
DEBUG [1615470479.608739] e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\service\__ini
t__.py/__init__: service: svtplay
DEBUG [1615470479.608739] e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\utils\http.py
/request: HTTP getting 'https://www.svtplay.se/video/30167492/blind-spot'
DEBUG [1615470479.6117408] C:\Program Files\Python37\lib\site-packages\urllib3\c
onnectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:44
3
DEBUG [1615470479.6808095] C:\Program Files\Python37\lib\site-packages\urllib3\c
onnectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30167492/
blind-spot HTTP/1.1" 200 27212
Traceback (most recent call last):
  File "e:\svtplaydll\svtplay-dl_v3.1\__main__.py", line 15, in <module> 
    svtplay_dl.main()
  File "e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\utils\getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
    for i in streams:
  File "e:\svtplaydll\svtplay-dl_v3.1\svtplay_dl\service\svtplay.py", line 83, in get
    if not vid and not self.visibleid:
AttributeError: 'Svtplay' object has no attribute 'visibleid'

**Comment by spaam** [comment]
ahh the videos is not available 🤔  i guess that is why its crashing

**Comment by towil1** [comment]
Yes, but that is also the "new look" I was referring to yesterday.

**Comment by towil1** [comment]
Indeed, the Mia & Klara link has the new look again and  is failing again like in my first post.

**Comment by pythonuser3856** [comment]
"Blind Spot" is on broadcast tonight local time 22.30
I'm at this point in time not able to see the film using Firefox
Let's see what the web page looks like after time for braodcast

**Comment by spaam** [comment]
"mia & klara" is crashing the same way as the one with the broadcast tonight  🤔

**Comment by pythonuser3856** [comment]
Ok, then I'll drop it

**Comment by pythonuser3856** [comment]
It seems as if new layout is used overall = **all tried items fail**

**Comment by spaam** [comment]
That is Great. I have something that work-ish. The metadata is left to fix. like season and episode stuff that people like to have.

**Comment by spaam** [comment]
i have released 3.2 with the fix.  it should be available in all places. brew later today (friday).

if any bugs is found, open a new issue :)

**Comment by Ferbd-Git** [comment]
Spaam, tack så mycket för jobbet, jag ser att du höll på torsdag kväll, ända till början av fredagen den 12 mars, dvs. småtimmarna på fredag.
Allt för att vi, användare av svtplay-dl ska kunna uppleva nöjet att ladda ner en film och se den kanske på en plats vi inte har bra wi-fi.
Hälsar med stor respekt,
Ferbd-Git
