### ISSUE TITLE
AttributeError: 'Svtplay' object has no attribute 'visibleid'

### ISSUE THREAD

**Issue by Ferbd-Git** [spaam/svtplay-dl#1336]
### svtplay-dl versions:
svtplay-dl 3.1

### Operating system and Python version:
Ubuntu 20.04.2 LTS

Python 3.8.5

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

   $ svtplay-dl --verbose https://www.svtplay.se/video/30081276
DEBUG [1615377592.7924144] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.1
DEBUG [1615377592.7934875] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1615377592.7935424] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30081276'
DEBUG [1615377592.7948782] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1615377593.5539033] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30081276 HTTP/1.1" 200 27824
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 83, in get
    if not vid and not self.visibleid:
AttributeError: 'Svtplay' object has no attribute 'visibleid'

**Comment by spaam** [comment]
thanks for the ticket <3 
but i will closing this, we already have #1335 for the same issue. please follow that ticket for updates :)
