### ISSUE TITLE
svtplay.se downloads now fail after the site got a new look #2

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1337]
The issue in #1335 remains when using the svtplay-dl v3.2 that is obtainable via the svtplay-dl distribution link https://svtplay-dl.se/archive/

But is it version 3.2 ?
When running svtplay-dl --version I get the same version ID as with svtplay-dl version 3.1

svtplay-dl --version yields
svtplay-dl 3.0-7-ge423c1c
for both version 3.1 and 3.2

**Comment by spaam** [comment]
thanks for the report. for some reason the script that moves files around crashed and for some reason the `svtplay-dl` binary thing got the wrong version. need to check that. anyway. i have fixed those now on the page. it should work :)

**Comment by pythonuser3856** [comment]
Great work !
Really
