### ISSUE TITLE
'Svtplay' object has no attribute 'visibleid'

### ISSUE THREAD

**Issue by hallonstedt** [spaam/svtplay-dl#1338]
Yesterday, svtplay-dl stopped working. The following error appears when I try to download a file (I am running svtplay-dl 3.1 on python 3.5):

```
# /usr/local/bin/svtplay-dl --force --verbose https://www.svtplay.se/video/30477580/lokala-nyheter-skane/svt-nyheter-skane-12-mars-09-05-1
DEBUG [1615537880.2299185] /usr/local/lib/python3.5/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.1
DEBUG [1615537880.232758] /usr/local/lib/python3.5/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1615537880.232843] /usr/local/lib/python3.5/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30477580/lokala-nyheter-skane/svt-nyheter-skane-12-mars-09-05-1'
DEBUG [1615537880.236298] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1615537880.7582476] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30477580/lokala-nyheter-skane/svt-nyheter-skane-12-mars-09-05-1 HTTP/1.1" 200 31602
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.5/dist-packages/svtplay_dl/service/svtplay.py", line 83, in get
    if not vid and not self.visibleid:
AttributeError: 'Svtplay' object has no attribute 'visibleid'
```

Normally, when I encounter errors, I just get the latest git master and compile and we're back in business but version 3.2 fails to run on my machine:

```
# svtplay-dl --version
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 56
    logging.debug(f"service: {self.__class__.__name__.lower()}")
                                                              ^
SyntaxError: invalid syntax
```

**Comment by spaam** [comment]
3.2 have a fix for svtplay.se but i also dropped support for python 3.5, i wrote on the website. 

maybe upgrade your OS to something newer? the only linux dist i know running py3.5 is debian stretch released 4 years ago and ubuntu 16.04 released 5 years ago. i know debian stable have python 3.7, ubuntu 18.04 have python 3.6, ubuntu 20.04 have python 3.8.

if you dont want to upgrade and have docker installed. you use the [spaam/svtplay-dl:3.2](https://hub.docker.com/r/spaam/svtplay-dl)
or install a newer version of python3.

**Comment by hallonstedt** [comment]
Understood, thanks for the quick reply. An upgrade will probably break my PVR but the Docker idea is not bad! 

May I suggest that you update the documentation accordingly?

Your [Install from source](https://svtplay-dl.se/install/source/) documentation says Python 3.5 is required and [README.md](https://github.com/spaam/svtplay-dl/blob/master/README.md) here on GitHub says 3.4 is required.

**Comment by spaam** [comment]
> May I suggest that you update the documentation accordingly?
> 

That sounds like an awesome idea. thanks for pointing that out. it should be updated on both places in a few min :)

**Comment by erikatl** [comment]
Version 3.2-1 appeared in the AUR, doesn't build:
```
Aur (1) svtplay-dl-3.2-1

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Skapar paket: svtplay-dl 3.2-1 (fre 12 mar 2021 11:54:59)
==> Hämtar källor...
  -> Hittade 3.2.tar.gz
==> Validerar source filer med sha256sums...
    3.2.tar.gz ... MISSLYCKADES
==> FEL:  En eller flera filer klarade inte valideringstestet.
:: Packages failed to build: svtplay-dl-3.2-1
```

**Comment by spaam** [comment]
@erikatl i have never touched PKGBUILD before. is it archlinux?

**Comment by erikatl** [comment]
I am using Manjaro, which is based on Arch and has access to the AUR.

**Comment by spaam** [comment]
i guess they use some AUR as arch linux.  there is a similar comment that you did but at AUR place for arch linux https://aur.archlinux.org/packages/svtplay-dl/#comment-796058

**Comment by JonLohnn** [comment]
Seems to be the same problem för me, on latest Manjaro:

[jol@Datorn The Tunnel S03]$ svtplay-dl -S https://www.svtplay.se/video/30340122/the-tunnel-hamnden/the-tunnel-hamnden-sasong-3-avsnitt-2?modalId=jdPYkPY --verbose
DEBUG [1615547380.6334972] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 3.0-7-ge423c1c
DEBUG [1615547380.6345375] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1615547380.6345873] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30340122/the-tunnel-hamnden/the-tunnel-hamnden-sasong-3-avsnitt-2?modalId=jdPYkPY'
DEBUG [1615547380.6361504] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1615547380.7385495] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30340122/the-tunnel-hamnden/the-tunnel-hamnden-sasong-3-avsnitt-2?modalId=jdPYkPY HTTP/1.1" 200 29910
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 15, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 69, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 61, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 83, in get
AttributeError: 'Svtplay' object has no attribute 'visibleid'

**Comment by erikatl** [comment]
Yes, that is definitely a comment regarding the same problem. And yes, The AUR is only one, shared by Arch, Manjaro and a few other Arch based distros.

**Comment by JonLohnn** [comment]
I am a newbie, sorry if my questions doesn't contribute to a soultion, but I ask anyway:
It seems every update in AUR has a delay before it is "accepted", and this time svtplay-dl stopped working after update.
Can I hope for this to be fixed in future releases, or is there something I should do myself in Manjaro?

**Comment by erikatl** [comment]
@JonLohnn (I am not a newbie but still a noob.) I believe this a bit off topic, svtplay-dl guys are probably not directly involved in packaging their app for AUR. It might be a good idea to reach out to the AUR packaging group referred to by spaam above instead.

**Comment by erikatl** [comment]
OK, the AUR problem is now solved. (Including a bittersweet comment from swearchnick at the AUR packaging team...)

**Comment by spaam** [comment]
@JonLohnn nothing wrong to ask .  i released 3.2 like 13h ago,  the AUR was updated 6h ago.  from when i released it to get it to AUR with only 7h delay, its pretty great. sure the person made a mistake this time with the sha checksum being wrong, but it was just fixed with a few hours later.  for macOS people who use brew, sometimes it takes longer than 7h to get the latest version accepted. 

how to get your svtplay-dl 3.0 to the latest one, i dont know, i guess there is some arguments to your package manager to do it  :)

@erikatl is correct. if its something wrong with AUR  package, just make a comment for the package there and i bet the maintainer there will fix it when they have time.

**Comment by SYSophie** [comment]
@spaam I experience the same error with python 3.9 on macOS installed either via source or brew:

`svtplay-dl "https://www.svtplay.se/video/30081204/the-lost-city-of-z?modalId=jx1X5VR" --verbose
DEBUG [1615803618.049351] /usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.1
DEBUG [1615803618.05003] /usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1615803618.0500648] /usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30081204/the-lost-city-of-z?modalId=jx1X5VR'
DEBUG [1615803619.042249] /usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1615803620.012809] /usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30081204/the-lost-city-of-z?modalId=jx1X5VR HTTP/1.1" 200 28606
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/3.1/libexec/lib/python3.9/site-packages/svtplay_dl/service/svtplay.py", line 83, in get
    if not vid and not self.visibleid:
AttributeError: 'Svtplay' object has no attribute 'visibleid'
`

**Comment by spaam** [comment]
@SYSophie yeah, aftonbladet updated their stuff and the test in brew that use it broke and i didn't check it.  hopefully tonight when #1343 is fixed, we can get a working version in brew.

**Comment by spaam** [comment]
this is fixed yesterday. 3.3 have a fix and its available on brew
