### ISSUE TITLE
dash: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by iwconfig** [spaam/svtplay-dl#1340]
### svtplay-dl versions:

svtplay-dl 3.2+4.gc1bfd0f

### Operating system and Python version:

OSX El Capitan 10.11.6
python 3.7

### What is the issue:

Updated svtplay-dl to the latest dev version since the svtplay.se site changed.

Now I get the following error:

    $ svtplay-dl -M -o "/Volumes/Media/" "https://www.svtplay.se/video/28156536/vetenskapens-varld/vetenskapens-varld-sasong-33-fett-van-eller-fiende" --verbose
    DEBUG [1615669196.843719] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.2+4.gc1bfd0f
    DEBUG [1615669196.848612] /usr/local/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
    DEBUG [1615669196.848744] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/28156536/vetenskapens-varld/vetenskapens-varld-sasong-33-fett-van-eller-fiende'
    DEBUG [1615669196.8613608] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
    DEBUG [1615669196.958229] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/28156536/vetenskapens-varld/vetenskapens-varld-sasong-33-fett-van-eller-fiende HTTP/1.1" 200 42244
    DEBUG [1615669196.980284] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://api.svt.se/video/jmL1YBb'
    DEBUG [1615669196.9850082] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
    DEBUG [1615669197.092762] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/jmL1YBb HTTP/1.1" 200 1089
    DEBUG [1615669197.095744] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://switcher.cdn.svt.se/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8'
    DEBUG [1615669197.0992682] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): switcher.cdn.svt.se:443
    DEBUG [1615669197.1533818] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8 HTTP/1.1" 302 0
    DEBUG [1615669197.158567] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): ed3.cdn.svt.se:443
    DEBUG [1615669197.227533] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://ed3.cdn.svt.se:443 "GET /d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8 HTTP/1.1" 200 1223
    DEBUG [1615669197.228478] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-6k.akamaized.net/d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2Fb8ba16d6-321c-40d4-8ae1-83d232cb4d62%2Fhls-ts-lb-avc.m3u8'
    DEBUG [1615669197.245523] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-6k.akamaized.net:443
    DEBUG [1615669197.307182] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-6k.akamaized.net:443 "GET /d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2Fb8ba16d6-321c-40d4-8ae1-83d232cb4d62%2Fhls-ts-lb-avc.m3u8 HTTP/1.1" 200 493
    DEBUG [1615669197.3166149] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://ed3.cdn.svt.se/d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8'
    DEBUG [1615669197.331336] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://ed3.cdn.svt.se:443 "GET /d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/hls-ts-lb-avc.m3u8 HTTP/1.1" 200 1223
    DEBUG [1615669197.334843] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://switcher.cdn.svt.se/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/dash-avc.mpd'
    DEBUG [1615669197.346336] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://switcher.cdn.svt.se:443 "GET /b8ba16d6-321c-40d4-8ae1-83d232cb4d62/dash-avc.mpd HTTP/1.1" 302 0
    DEBUG [1615669197.3695538] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://ed3.cdn.svt.se:443 "GET /d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/dash-avc.mpd HTTP/1.1" 200 4014
    DEBUG [1615669197.370549] /usr/local/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-6k.akamaized.net/d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/dash-avc.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2Fb8ba16d6-321c-40d4-8ae1-83d232cb4d62%2Fdash-avc.mpd'
    DEBUG [1615669197.4035552] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-6k.akamaized.net:443 "GET /d0/se/20200912/b8ba16d6-321c-40d4-8ae1-83d232cb4d62/dash-avc.mpd?alt=https%3A%2F%2Fswitcher.cdn.svt.se%2Fb8ba16d6-321c-40d4-8ae1-83d232cb4d62%2Fdash-avc.mpd HTTP/1.1" 200 890
    Traceback (most recent call last):
      File "/usr/local/bin/svtplay-dl", line 7, in <module>
        svtplay_dl.main()
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 69, in main
        get_media(urls[0], config, __version__)
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
        get_one_media(stream)
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
        for i in streams:
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 94, in get
        yield from videos
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 119, in _get_video
        streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 188, in dashparse
        return _dashparse(config, res.text, url, res.cookies, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 223, in _dashparse
        subtitles = adaptionset(attributes, temp, url, baseurl)
      File "/usr/local/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 147, in adaptionset
        if codecs[:3] == "avc":
    TypeError: 'NoneType' object is not subscriptable

Seeing the recent changes in dash.py with support for multiple adaptionsets and subtitles (9b4ed1b), I figured it might have something to do with that. I reproduced this running on another computer and the same error occurred.

I tried with the release version and it worked just fine, so this is specifically related to dev version 3.2+4.gc1bfd0f.

**Comment by spaam** [comment]
interesting 🤔   i guess the tests i made before is a bit bad i guess that didn't catch this :D
