### ISSUE TITLE
svtplay-dl crashed

### ISSUE THREAD

**Issue by skaker1** [spaam/svtplay-dl#1341]
### svtplay-dl versions:

Run `svtplay-dl --version`
svtplay-dl 3.2
### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
Windows 10 20H2. Python?
### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

https://www.svtplay.se/maxat-fredag

All episodes except the first is downloaded.

This is the episoed that doesn'twork:

"https://www.svtplay.se/video/27872439/maxat-fredag/maxat-fredag-sasong-4-os-mania?modalId=jE41G2B"

[verbose log.txt](https://github.com/spaam/svtplay-dl/files/6137003/verbose.log.txt)

**Comment by spaam** [comment]
i see the error. for some reason they say a HLS thing is DASH. so the script crashes :)

**Comment by spaam** [comment]
this will be in 3.3  later today

**Comment by skaker1** [comment]
Hi!

Thank you. I tried it and now it's working again.

Med vänlig hälsning/Best regards

Kenneth Eriksson


Den sön 14 mars 2021 kl 19:05 skrev Johan Andersson <
***@***.***>:
