### ISSUE TITLE
Can't download from svtplay.se

### ISSUE THREAD

**Issue by mikewinq** [spaam/svtplay-dl#1344]
### Operating system and Python version: Win 10 Pro and Python 3.7.1

Name and version of the operating system and python version (run `python --version`)

### What is the issue: Can't download from SVTPlay, all-ep.exe says "ERROR: Can't find video id. removed?" and umans_webtv_downloader.exe "ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue"

### URL: https://www.svtplay.se/video/29439040/gristaget-farden-mot-revansch-och-undergang?modalId=KQ7Vo93

DEBUG [1615793275.2992618] svtplay-dl\svtplay_dl\utils\getmedia.py/get_media: version: -unknown
DEBUG [1615793275.301262] svtplay-dl\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1615793275.3022559] svtplay-dl\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/29439040/gristaget-farden-mot-revansch-och-undergang?modalId=KQ7Vo93'
DEBUG [1615793275.305248] C:\Video\uwtd_20201028\uwtd\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1615793276.0494761] C:\Video\uwtd_20201028\uwtd\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/29439040/gristaget-farden-mot-revansch-och-undergang?modalId=KQ7Vo93 HTTP/1.1" 200 26910
Traceback (most recent call last):
  File "C:\Video\uwtd_20201028\uwtd\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Video\uwtd_20201028\uwtd\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "svtplay-dl\__main__.py", line 20, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 69, in main
  File "svtplay-dl\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "svtplay-dl\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "svtplay-dl\svtplay_dl\service\svtplay.py", line 76, in get
AttributeError: 'Svtplay' object has no attribute 'visibleid'

**Comment by spaam** [comment]
this is fixed in 3.2. update to that :)
