### ISSUE TITLE
There is some thing wrong with the latest tv4play service

### ISSUE THREAD

**Issue by svallebro** [spaam/svtplay-dl#1346]
### svtplay-dl versions:

Run `svtplay-dl --version`
svtplay-dl 3.2+11.g7500477
7500477f8d059eaae8229fb34d5db403af09238a

### Operating system and Python version:
Windows 10
Python 3.8.5
### What is the issue:
I'm getting episodes from other series and way too many 

P:\svtplay-dl\build\svtplay-dl.exe  -A https://www.tv4play.se/program/bytt-är-bytt  --get-only-episode-url
INFO: Episode 1 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/125572 -> Det okända del 3, säsong 3
INFO: Episode 2 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/125642
INFO: Episode 3 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/125675
INFO: Episode 4 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/128907
INFO: Episode 5 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/136671
INFO: Episode 6 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/136672
INFO: Episode 7 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/139709
INFO: Episode 8 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/139712
INFO: Episode 9 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/249404
INFO: Episode 10 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/342094
INFO: Episode 11 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/362494
INFO: Episode 12 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/388634
INFO: Episode 13 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/684245
INFO: Episode 14 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/686933
INFO: Episode 15 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/973025
INFO: Episode 16 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1189212
INFO: Episode 17 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1193555
INFO: Episode 18 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1201015
INFO: Episode 19 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1214778
INFO: Episode 20 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1222643
INFO: Episode 21 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1277823
INFO: Episode 22 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/1378747
INFO: Episode 23 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2132061
INFO: Episode 24 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2162942
INFO: Episode 25 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2176767
INFO: Episode 26 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2225741
INFO: Episode 27 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2227802
INFO: Episode 28 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2232676
INFO: Episode 29 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2235595
INFO: Episode 30 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2239732
INFO: Episode 31 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2241570
INFO: Episode 32 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/2243997
INFO: Episode 33 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3187401
INFO: Episode 34 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3204928
INFO: Episode 35 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3214125
INFO: Episode 36 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3234480
INFO: Episode 37 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3234481
INFO: Episode 38 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3404290
INFO: Episode 39 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3414676
INFO: Episode 40 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3426034
INFO: Episode 41 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3435053
INFO: Episode 42 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3442912
INFO: Episode 43 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3445013
INFO: Episode 44 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3466881
INFO: Episode 45 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3489153
INFO: Episode 46 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3498793
INFO: Episode 47 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3498812
INFO: Episode 48 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3510032
INFO: Episode 49 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3519834
INFO: Episode 50 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3538832
INFO: Episode 51 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3558234
INFO: Episode 52 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3568332
INFO: Episode 53 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3577032
INFO: Episode 54 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3578633
INFO: Episode 55 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3592372
INFO: Episode 56 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3603933
INFO: Episode 57 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3615193
INFO: Episode 58 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3636113
INFO: Episode 59 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3646496
INFO: Episode 60 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3895167
INFO: Episode 61 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3906175
INFO: Episode 62 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3906178
INFO: Episode 63 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3910132
INFO: Episode 64 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3910567
INFO: Episode 65 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3910568
INFO: Episode 66 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3910569
INFO: Episode 67 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3914296
INFO: Episode 68 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3923644
INFO: Episode 69 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3923654
INFO: Episode 70 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3923972
INFO: Episode 71 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3924005
INFO: Episode 72 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3924008
INFO: Episode 73 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3924147
INFO: Episode 74 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3928219
INFO: Episode 75 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3928786
INFO: Episode 76 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3931458
INFO: Episode 77 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3932241
INFO: Episode 78 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3932493
INFO: Episode 79 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3934753
INFO: Episode 80 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3935891
INFO: Episode 81 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3937021
INFO: Episode 82 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3938422
INFO: Episode 83 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3938948
INFO: Episode 84 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3938949
INFO: Episode 85 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3939628
INFO: Episode 86 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3940549
INFO: Episode 87 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3941001
INFO: Episode 88 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3941937
INFO: Episode 89 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3943827
INFO: Episode 90 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3945122
INFO: Episode 91 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3945684
INFO: Episode 92 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3945888
INFO: Episode 93 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3951747
INFO: Episode 94 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3953553
INFO: Episode 95 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3956096
INFO: Episode 96 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3958916
INFO: Episode 97 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3959667
INFO: Episode 98 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3960703
INFO: Episode 99 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3960780
INFO: Episode 100 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3961648
INFO: Episode 101 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3965773
INFO: Episode 102 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3966071
INFO: Episode 103 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3968323
INFO: Episode 104 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3969747
INFO: Episode 105 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971465
INFO: Episode 106 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971785
INFO: Episode 107 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971837
INFO: Episode 108 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971864
INFO: Episode 109 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971897
INFO: Episode 110 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971922
INFO: Episode 111 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971949
INFO: Episode 112 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3971980
INFO: Episode 113 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/3972014
INFO: Episode 114 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/10001945
INFO: Episode 115 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979037
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979038
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979042
INFO: Episode 118 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979044
INFO: Episode 119 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979045
INFO: Episode 120 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979047
INFO: Episode 121 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979052
INFO: Episode 122 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979053
INFO: Episode 123 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979054
INFO: Episode 124 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/11979055
INFO: Episode 125 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580231
INFO: Episode 126 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580247
INFO: Episode 127 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580262
INFO: Episode 128 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580264
INFO: Episode 129 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580272
INFO: Episode 130 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12580283
INFO: Episode 131 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12613125
INFO: Episode 132 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12613127
INFO: Episode 133 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12613129
INFO: Episode 134 of 134
INFO: Url: https://www.tv4play.se/program/bytt-är-bytt/12613131

**Comment by spaam** [comment]
bah. i dislike this website

**Comment by spaam** [comment]
this will be in 3.3. its released now
