### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by JamesWilde** [spaam/svtplay-dl#1347]
### svtplay-dl versions:

svtplay-dl --version gives the same msg
It was a new upgrade with brew

### Operating system and Python version:

MacOS 10.14.6
Python 2.7.16

### What is the issue:

svtplay-dl -S  https://www.svtplay.se/video/30490492/tradgardstider/tradgardstider-sasong-10-kalhygge-och-drommar?modalId=86gk7w3

But apparently it never gets that far.  I get the same error when I run svtplay-dl --version so it is presumably an error in my version of svtplay-dl.

I'll see if I can download the next last version and see whether that works

**Comment by spaam** [comment]
feels like you have two installs of the script.  one installed via brew and a second via something else.
what does `which svtplay-dl` say?  does it say something that is not `/usr/local/bin/svtplay-dl`?  if so remove it.

**Comment by JamesWilde** [comment]
Nope, that was the first thing I checked.  The file is in /usr/local/bin.
I dl-d new copies, changed the mod to 755 and moved it to /usr/local/bin.  I have now dl'd earlier versions, right back to 2020-04-08 and they all give the same result with svtplay-dl --version.

I'll reload the original version from backup and see what happens.

**Comment by JamesWilde** [comment]
Oh dear, the backup doesn't include /usr/local/bin.

**Comment by spaam** [comment]
i installed it via brew now and it works here.
`I dl-d new copies, changed the mod to 755 and moved it to /usr/local/bin.` ?  so you installed it via something else.
i recommend checking out `Prerequisites` section on https://svtplay-dl.se/install/source/

**Comment by JamesWilde** [comment]
I also did a python upgrade after installing svtplay-dl.  Btw, thanks for being here.

**Comment by spaam** [comment]
its okey, svtplay-dl package via `brew install svtplay-dl`  include all the dependencies.  but installing it via curl / wget / browser download does not include all dependencies. its more up to the user to fix those on their own.

**Comment by JamesWilde** [comment]
Just got a msg that the file is not linked, which I now have done, and svtplay-dl --version returns 3.3 so I'll give it a live try.

Seconds later: Woohoo!  It works again.  Thanks for everything, especially for svtplay-dl.

**Comment by spaam** [comment]
thanks :)
