### ISSUE TITLE
Error downloading certain files from SVTPlay

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#1354]
### svtplay-dl version:

3.3

### Operating system and Python version:

Operating system: Windows 10, version 10.0.19042.0

Python version: Unknown

### What is the issue:

These download failed:

https://www.svtplay.se/video/30764778/mcleods-dottrar/mcleods-dottrar-sasong-6-old-wrongs
https://www.svtplay.se/video/30812678/varldens-historia-pyramidens-hemligheter/varldens-historia-pyramidens-hemligheter-avsnitt-1
https://www.svtplay.se/video/30812698/varldens-historia-pyramidens-hemligheter/varldens-historia-pyramidens-hemligheter-avsnitt-2

CommandLine used:  -S -f --verbose -o C:\Users\jojo\AppData\Roaming\SVTPlayGUI\f62a2675-9698-4afb-8165-168ea1a9f0d5 https://www.svtplay.se/video/30764778/mcleods-dottrar/mcleods-dottrar-sasong-6-old-wrongs

Verbose output:
svtplay-dl.exe  -S -f --verbose -o C:\Users\jojo\AppData\Roaming\SVTPlayGUI\f62a2675-9698-4afb-8165-168ea1a9f0d5 https://www.svtplay.se/video/30764778/mcleods-dottrar/mcleods-dottrar-sasong-6-old-wrongs
DEBUG [1618302188.2349062] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.3
DEBUG [1618302188.236914] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1618302188.236914] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/30764778/mcleods-dottrar/mcleods-dottrar-sasong-6-old-wrongs'
DEBUG [1618302188.2408717] C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1618302188.3929353] C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30764778/mcleods-dottrar/mcleods-dottrar-sasong-6-old-wrongs HTTP/1.1" 200 60326
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\hostedtoolcache\windows\Python\3.8.8\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 73, in get
KeyError: 'data'

**Comment by JohnnyJorgensen** [comment]
Sorry, didn't see that somebody else reported the same error while I was writing the error report... :-(

**Comment by spaam** [comment]
it takes time to fill in the issue with the correct data like you did, but thanks for the bug report :)  i will close this and you can follow #1352 for updates about the issue :)
