### ISSUE TITLE
Kan inte ladda ner Trädgårdstider från svtplay.

### ISSUE THREAD

**Issue by Ferbd-Git** [spaam/svtplay-dl#1355]
### svtplay-dl versions:
svtplay-dl 3.3

### Operating system and Python version:
Python 3.8.5

### What is the issue:
$ svtplay-dl --verbose https://www.svtplay.se/video/30817042
DEBUG [1618335269.142401] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.3
DEBUG [1618335269.1434925] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1618335269.1435483] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/30817042'
DEBUG [1618335269.1449158] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1618335269.6435456] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30817042 HTTP/1.1" 200 31898
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 73, in get
    entry = json.loads(data_entry["data"])
KeyError: 'data'

**Comment by Ferbd-Git** [comment]
Glömde att skriva vilket operativ: Ubuntu 20.04.2 LTS

**Comment by spaam** [comment]
detta är fixat i master. ska släppa en ny version om någon timme med fixen :)  vi har en issue redan om detta #1352. stänger denna  :)
