### ISSUE TITLE
Correction for svt.py does not work with -A option

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1356]
The solution does not work with the **-A --get-only-episode-url** options on svtplay.se site

**find_all_episodes** still refers to non-existing key "data"

### svtplay-dl versions:

Run `svtplay-dl --version`

% svtplay-dl --version
svtplay-dl 3.3-4-g391af6f

### Operating system and Python version:

Windows 10
Python 3.8.0

### What is the issue:

% svtplay-dl --verbose -A --get-only-episode-url https://www.svtplay.se/video/30858198/veckans-brott/veckans-brott-sociala-poliser

DEBUG [1618349832.2951634] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.3-4-g391af6f
DEBUG [1618349832.298162] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1618349832.2991621] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/30858198/veckans-brott/veckans-brott-sociala-poliser'
DEBUG [1618349832.3051596] C:\hostedtoolcache\windows\Python\3.8.8\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1618349833.0149844] C:\hostedtoolcache\windows\Python\3.8.8\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/30858198/veckans-brott/veckans-brott-sociala-poliser HTTP/1.1" 200 43757
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.8\x86\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 74, in run
  File "C:\hostedtoolcache\windows\Python\3.8.8\x86\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 77, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 171, in find_all_episodes
KeyError: 'data'

**Comment by anttin2020** [comment]
Same error just with only -A as well, using config:
default:
    path: "x:/path"
    subtitle: true
    merge_subtitle: true
    all_episodes: true
    exclude: syntolkat
    remux: true
    filename: "{title}/{title}.s{season}e{episode}.{episodename}.{ext}"

Also if not already fixed, please fix the existing file detection to start with video, the previous version always loaded the audio and only then noticed that the video already existed.

**Comment by spaam** [comment]
3.5 was just released with the fix. upgrade to that :)

**Comment by anttin2020** [comment]
thanks :) https://svtplay-dl.se/archive/ still shows 3.4, is there some delay on updates to show up?

**Comment by spaam** [comment]
it will be updated in a few min.. forgot to push the changes.  you can replace the `3.4` in the download url to `3.5` to get the file :)
