### ISSUE TITLE
File name of standalone UR Play programs

### ISSUE THREAD

**Issue by bohelax** [spaam/svtplay-dl#1357]
Now the file names of programs that are part of a series are nicely done, thank you.
(E.g. https://urplay.se/program/218193-afghanistan-ett-sargat-land-kungadomet-afghanistan becomes
afghanistan-ett.sargat.land.s01e01.kungadomet.afghanistan-218193-urplay.mp4).

However, standalone programs, not part of a series, seems to be treated the same way, as seen below:
________________________________________________________________________________________________________
bin>ver

Microsoft Windows [Version 10.0.18363.1474]

bin>py
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

bin>urs https://urplay.se/program/214593-universums-kartritare

bin>svtplay-dl.py -o temp -s -S --force-subtitle --all-subtitles https://urplay.
se/program/214593-universums-kartritare
2.1 seconds
One srt - Normal

bin>svtplay-dl.py -S -M https://urplay.se/program/214593-universums-kartritare

INFO: Outfile: {title}.s01.universums.kartritare-214593-urplay.srt
INFO: Selected to download hls, bitrate: 3273 format: h264
INFO: Outfile: {title}.s01.universums.kartritare-214593-urplay.ts
[788/788][========================================] ETA: 0:00:00
INFO: Muxing {title}.s01.universums.kartritare-214593-urplay.ts and merging its
subtitle into {title}.s01.universums.kartritare-214593-urplay.mp4
INFO: Determining the language of the subtitle.
INFO: Language code: swe
INFO: Muxing done, removing the old file.
53.4 seconds
55.8 seconds

bin>
________________________________________________________________________________________________________

It's not a big deal, but if avoidable is less ugly
//BoH

**Comment by spaam** [comment]
i see the issue 🤔

**Comment by spaam** [comment]
i committed something to fix this. it will be in a release later this week
