### ISSUE TITLE
Can't find any playable files from Discovery+

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#1361]
### svtplay-dl versions:

3.5-1-g8805627

### Operating system and Python version:

Windows 10, Windows stand-alone .EXE version

### What is the issue:

Some newer videos from Discovery Plus doesn't work to download via svtplay-dl, and results in "Can't find any playable files", even though the majority of videos work. For example:
https://www.discoveryplus.se/program/alla-utom-vi
https://www.discoveryplus.se/program/udda-veckor

Example command:
svtplay-dl -S --raw-subtitles --remux -A --verbose --cookies st=XXXXX https://www.discoveryplus.se/program/alla-utom-vi

Output:
DEBUG [1618710821.8776715] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.5-1-g8805627
DEBUG [1618710821.8786716] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dplay
DEBUG [1618710821.8806715] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-
api.discoveryplus.se/users/me'
DEBUG [1618710821.8856719] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1618710822.2086904] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1618710822.2116904] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=9708fd0c3a64591c024c02167f3b7cad1dcda62d1d41b6d0a27b96989b63864f&shortlived=true'
DEBUG [1618710822.322697] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=9708fd0c3a64591c024c02167f3b7cad1dcda62d1d41b6d0a27b96989b63864f&shortlived=true HTTP/1.1" 200 None
DEBUG [1618710822.325697] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1618710822.4037015] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1618710822.4057016] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://disco-api.discoveryplus.se/cms/routes/program/alla-utom-vi?decorators=viewingHistory&include=default'
DEBUG [1618710822.4097018] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1618710822.5567105] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/alla-utom-vi?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1618710822.6317146] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/alla-utom-vi?decorators=viewingHistory&include=default HTTP/1.1" 200 None
ERROR [1618710822.6357148] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dplay.py/find_all_episodes: Cant find any playable files

Same issue with episode specific URLs (such as https://www.discoveryplus.se/videos/alla-utom-vi/alla-utom-vi-193411 instead of https://www.discoveryplus.se/program/alla-utom-vi ).

**Comment by spaam** [comment]
i have commited a fix for this. it will be in the next version later today. :)
