### ISSUE TITLE
-A doesn't work for certain programs on Discovery+

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#1362]
### svtplay-dl versions:

3.5-1-g8805627

### Operating system and Python version:

Windows 10, stand-alone .EXE version

### What is the issue:

With a few programs, -A doesn't work for all episodes, but instead returns "KeyError: 'value'". Individual episodes can be downloaded just fine.

Not sure what's the issue is, as most programs work just fine with -A.

Example:
svtplay-dl -A -S --verbose --cookies st=XXXXX https://www.discoveryplus.se/program/90-day-fiance-happily-ever-after

Output:
DEBUG [1618711680.4807808] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.5-1-g8805627
DEBUG [1618711680.4817808] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dplay
DEBUG [1618711680.4837809] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1618711680.4867811] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1618711680.7877982] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1618711680.7887986] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=666c36b33fea21cedd139cd489729de9e1bdde1d20f4cf07b9ca22cd64b39f79&shortlived=true'
DEBUG [1618711680.8848038] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=666c36b33fea21cedd139cd489729de9e1bd
de1d20f4cf07b9ca22cd64b39f79&shortlived=true HTTP/1.1" 200 None
DEBUG [1618711680.8868039] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1618711680.9538078] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1618711680.9548078] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://disco-api.discoveryplus.se/cms/routes/program/90-day-fiance-happily-ever-after?decorators=viewingHistory&include=default'
DEBUG [1618711680.957808] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1618711681.0668142] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/90-day-fiance-happily-ever-after?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1618711681.2298236] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/90-day-fiance-happily-ever-after?decorators=viewingHistory&include=default HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run

  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 77, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dplay.py", line 158, in find_all_episodes
KeyError: 'value'

**Comment by spaam** [comment]
thanks for the bug ticket. this will be in the next version later today  😊
