### ISSUE TITLE
KeyError Filters when downloading certain shows from Discovery+

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#1366]
### svtplay-dl versions:

3.6

### Operating system and Python version:

Windows 10, stand-alone .EXE version

### What is the issue:

A few shows can't be downloaded from Discovery+, and results in an error message.

Example:
svtplay-dl -S --raw-subtitles --remux -A --verbose --cookies st=XXXXX https://www.discoveryplus.se/program/alskar-alskar-inte

Returns:
DEBUG [1619018519.4739673] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.6
DEBUG [1619018519.4749672] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dplay
DEBUG [1619018519.4769673] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1619018519.4799676] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3connectionpool.py/_new_
conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1619018519.7389824] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3connectionpool.py/_make
_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1619018519.7409825] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-
api.discoveryplus.se/token?realm=dplayse&deviceId=1270be94b76ac32534581f51fecec7ce90ed9e0f3693f310058fba0c6ca8aaa7&short
lived=true'
DEBUG [1619018519.8329878] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3connectionpool.py/_make
_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=1270be94b76ac32534581f51fecec7ce90ed
9e0f3693f310058fba0c6ca8aaa7&shortlived=true HTTP/1.1" 200 None
DEBUG [1619018519.8349879] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-
api.discoveryplus.se/users/me'
DEBUG [1619018519.946994] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3connectionpool.py/_make_
request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1619018519.9479945] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://disco-a
pi.discoveryplus.se/cms/routes/program/alskar-alskar-inte?decorators=viewingHistory&include=default'
DEBUG [1619018519.9509947] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1619018520.0550005] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/alskar-alskar-inte?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1619018520.2090094] C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/alskar-alskar-inte?decorators=viewingHistory&include=default HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in
 run
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run

  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 59, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 77, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dplay.py", line 159, in find_all_episodes
KeyError: 'filters'

**Comment by spaam** [comment]
bah. my fix for your previous bug report #1361  broke this. i guess i need to do a better fix 🤔

**Comment by spaam** [comment]
i commited a fix for this. it will be in the next episode later this week
