### ISSUE TITLE
rename dplay to discoveryplus, viaplay  to viafree. 

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#1369]
the sites have changed name recently and long time ago.

1) we need to fix that
2) we should also handle backwards compatible with old configs 
3) remove it after X months.  one year should be enough?
4) display a warning message if people have the old name?

**Comment by kjetilpp** [comment]
But viaplay still exists? https://viaplay.no/serier/sons-of-anarchy

**Comment by spaam** [comment]
yes it does .but the script dont support that site.  many years ago  they had videos there like they have om viafree.  nowdays on viaplay its paid content and its using DRM.
