### ISSUE TITLE
ERROR: No videos found. Can't find video info.

### ISSUE THREAD

**Issue by Zz-Wang** [spaam/svtplay-dl#1373]
### svtplay-dl versions:

svtplay-dl 2.8

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

MacOS Big Sur 11.1
Python 2.7.16

### What is the issue:
 svtplay-dl --verbose https://www.svtplay.se/video/16239874/moderna-tider/moderna-tider-sasong-1-matrecensenten?position=226&id=8pBXr9j

No videos found. Can't find video info.

**Comment by spaam** [comment]
your version 2.8 and its a bit old. the newest version is 3.7. its available on the most places.  i see you are using macOS, if you are using brew to install it.  try `brew update && brew upgrade` :)

**Comment by Zz-Wang** [comment]
Tack för snabbt svar! 

Mvh
