### ISSUE TITLE
LJUDpålägg Ovanpå Originalljudet vid hämtning!

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1376]
Man undrar vad Svtplay.se har hittat på nu...

https://www.svtplay.se/video/31066234/morden-vid-kustvagen/

Man får ljudet med en svensk Babblerska (Narrator) OVANPÅ det engelska originalljudet, som bara hörs otroligt svagt i bakgrunden.

Jag hämtade del 1 (av 3) i lördags, och den hade Ok (alltså engelskt) ljud.

Nu har de lagt upp både del 2 och del 3, men båda har alltså svensk Babblerska ovanpå.

svtplay-dl -S https://www.svtplay.se/video/31066234/morden-vid-kustvagen/morden-vid-kustvagen-sasong-1-avsnitt-2?id=jBMz1ZV

svtplay-dl -S https://www.svtplay.se/video/31095854/morden-vid-kustvagen/morden-vid-kustvagen-sasong-1-avsnitt-3?id=jzJzzoM

MEN det är Originalljud när man spelar upp dem i Edge...!

Fel hos Svtplay.se eller med Hämtningen via Svtplay-Dl, ljudet ÄR ju alltså Ok i webbläsaren ?!

**Comment by Sopor** [comment]
I get the same issue here. The sound you get is `Uppläst undertext` and i don't know how you select the proper audio track when they all have the same name when i use `--list-quality`?

```
INFO: Quality   Method  Codec   Resolution
INFO: 5719      DASH    H264-51 1920x1080
INFO: 5719      DASH    H264-51 1920x1080
INFO: 5719      DASH    H264-51 1920x1080
INFO: 5719      DASH    H264-51 1920x1080
```

**Comment by Sopor** [comment]
If i use another downloader i can easy see what audio track i should choose:
```
format code                            extension  resolution note
hls-cmaf-full-stereo-Svenska           mp4        audio only [sv]
hls-cmaf-full-stereo-Tydligare_tal     mp4        audio only [sv-x-tydligaretal]
hls-cmaf-full-surround-Svenska         mp4        audio only [sv]
hls-cmaf-full-surround-Tydligare_tal   mp4        audio only [sv-x-tydligaretal]
hls-cmaf-lb-full-stereo-Svenska        mp4        audio only [sv]
hls-cmaf-lb-full-stereo-Tydligare_tal  mp4        audio only [sv-x-tydligaretal]
hls-stereo-Svenska                     mp4        audio only [sv]
hls-ts-avc-stereo-Svenska              mp4        audio only [sv]
hls-ts-full-stereo-Svenska             mp4        audio only [sv]
hls-ts-full-stereo-Tydligare_tal       mp4        audio only [sv-x-tydligaretal]
hls-ts-full-surround-Svenska           mp4        audio only [sv]
hls-ts-full-surround-Tydligare_tal     mp4        audio only [sv-x-tydligaretal]
hls-ts-lb-full-stereo-Svenska          mp4        audio only [sv]
hls-ts-lb-full-stereo-Tydligare_tal    mp4        audio only [sv-x-tydligaretal]
```

**Comment by pythonuser3856** [comment]
I managed to to get "normal" copies of ep2 & ep3 **by enforcing use of HLS**, i.e. I added the parameter "--stream-priority hls" to svtplay-dl
At the same time I also enforced selection of 5.1-sound using "--format-preferred h264-51" I don't know if that had any impact on selection of type of audio-stream beside selecting 5.1-sound

Before that I tried using the parameter "--exclude" with the parameter value "upplast,tydligare,syntolkat,teckentolkat,teckensprakstolkat" but still got the overlayed speaker voice.

**Comment by Sopor** [comment]
@pythonuser3856 That seems to work! 👍

**Comment by aqgasa** [comment]
Hi! I know I should probably open a new thread but could you test if you can download anything from www.tv4play.se ? It stopped working for me today.
Thank you!

**Comment by Sopor** [comment]
@aqgasa Seems to work perfect

```
svtplay-dl.exe https://www.tv4play.se/program/masked-singer-sverige/del-7-s%C3%A4song-1/13306024
INFO: Outfile: masked-singer-sverige.s01e07.masked.singer.sverige.del.7-13306024-tv4play.srt
INFO: Selected to download hls, bitrate: 6460 format: h264
INFO: Outfile: masked-singer-sverige.s01e07.masked.singer.sverige.del.7-13306024-tv4play.audio.ts
[230/995][==================..............................................................] ETA: 0:00:18
```

**Comment by aqgasa** [comment]
Ok, thank you.

**Comment by Minherre** [comment]
Ja, det här felet med Talad Text som Ljud måste ju åtgärdas, för det sprider sig uppenbarligen...!

svtplay-dl -S https://www.svtplay.se/video/30971198/john-lennon-mordet-pa-en-ikon?id=8Dmp7g7

Det där ger Talad Text som Ljud.

Men pythonuser3856 förslag funkade som tur är!

svtplay-dl -S --stream-priority hls https://www.svtplay.se/video/30971198/john-lennon-mordet-pa-en-ikon?id=8Dmp7g7

Det där normalt ljud.

Men då blir det ju att man ofta får hålla på och hämta två versioner, och man måste ju då alltid provspola videon för att höra vad man fått för ljud också, ganska tidsödande då nedladdningen numera går mycket slöare sen de började med den där KODsnutten sist, förut fick jag ned en en-timmes video på under en minut, nu kan det ta åtskilliga minuter...

**Comment by Sopor** [comment]
@Minherre Det går lika bra utan kod-snutten (id=)om du vill ta bort den men den påverkar inget. Det är inte så att du börjar ladda ner klockan 02:00 när många videos släpps för då går det långsamt?

Jag tog ner `John Lennon: Mordet på en ikon` med 5.1-ljudet på 35 sekunder och videon på 1:40 och jag låg på 100-180 mbit i nerladdningshastighet. Det är väl inte långsamt?

**Comment by pythonuser3856** [comment]
When one uses svtplay-dl with the switch "--list-quality" to get available streams we see that, just as @Sopor mentioned in the first reply above, that there are multiple streams which svtplay-dl show as being identical.
Why are there multiple occurrences ?
Is it perhaps so that they are not identical but represent variants of audio streams ?
There are for sure different audio streams since we get different outcomes from using DASH versus HLS.

In that case, what seems to be needed is a way for the user of svtplay-dl to distinhguish between each and every stream available and determine which to get.
In that case this issue is rather about "Insufficient granularity at selecting (audio) stream".

How a solution should be tailored is perhaps not that straight forward, though.
1) Perhaps add a qualifier to each stream listed and leave to the user to conclude and select ?
2) Or identify commonly used identifers which let svtplay-dl determine the wanted variant be itself ?
3) or another ideas

Automation would be nice, i.e. avoid a solution which require to first list available streams and use that to decide which stream to retrieve.

Let's say that the output from "--list-quality" is expanded to include additional information to set the streams apart.
In that case it would help the user of svtplay-dl to have access to a switch similar to "--exclude" to enable filtering of wanted / unwanted stream properties, i.e. a switch that would enable the user to create a profile for generic downloading suitable for that user.

**Comment by spaam** [comment]
> Why are there multiple occurrences

easy, becuse we parse all the different playlists with video. a bunch of them have same bitrate. a bunch of them is from what sopor wrote here https://github.com/spaam/svtplay-dl/issues/1376#issuecomment-834672982 we didnt really.


> 1. Perhaps add a qualifier to each stream listed and leave to the user to conclude and select ? 
> 2. Or identify commonly used identifers which let svtplay-dl determine the wanted variant be itself ?

the script **_was_** made to be generic and not have any special config values for service X or Y,  all services only had one audio and several video with different bitrate and resolution. but that have changed in the last year or so :)

anyway,
sure that could be added.  but there are some issues. which one. should be default? should de stereo be it? the one with tydligare tal or the one with surround sound? i have written about this in #1295 at https://github.com/spaam/svtplay-dl/issues/1295#issuecomment-820797245 to be more exact. if you have any input or so, please write that in that ticket.

**Comment by pythonuser3856** [comment]
I missed that we have #1295. I've put a comment there.
#1376, this one, seems to be a dup of #1295

**Comment by Ferbd-Git** [comment]
Ja, pythonusers workaround fungerar, men, det skulle vara bättre att filmen blir nerladdad direkt som det är, dvs. med originalljud.
Om någon vill ha Berättarens tal, då skulle vara ett val med någon parameter.
Än så länge, tack Pythonuser för din tillfälliga lösning.

**Comment by spaam** [comment]
yoyo, bakgrund till problemt är att skriptet använder bitrate för att avgöra vad som är bra. skriptet sparar bitraten för ljudet för att sedan lägger till det med bildbitraten för at få totala bitraten för videon. problemet som har uppståt nu är att `original` ,`tydligaretal` och `uppläst undertext` är att dom kan ha samma ljudbitrate. i och med det så kan det "riktiga"/original ljudet bli överskrivet med något annat beroende på vart det är i spellistan något som jag inte räknande med när ja skrev parsern. 

får skriva om lite interna grejer för att få de funka, när det kommer bli klart? förhoppningsvis till veckan :)

**Comment by Ferbd-Git** [comment]
Spaam, tackar för ditt engagemang, som sagt, det fungerar med den workaround som finns, men, det kommer att bli mycket bättre med din riktiga lösning.
Det är ändå inte akut, tack vare Pythonuser.
Vi, användare, kan vänta för resultatet av ditt arbete.
Tack så mycket.

**Comment by olivertwistor** [comment]
@spaam Tack för ditt arbete med detta verktyg. Det uppskattas verkligen och du löser det här senaste strulet när du har tid och ork. Som @Ferbd-Git säger kan vi användare vänta.

En parameter för att välja mellan originalljud, tydligt tal och uppläst tal vore bra att ha, för de som ändå vill/måste ha nåt annat än originalljud på grund av hörselnedsättningar.

**Comment by pythonuser3856** [comment]
Om du har möjlighet, testa den senaste tillfälliga versionen av svtplay-dl som är nåbar via länken "Snapshots" på hemsidan. Denna testversion av svtplay-dl har ett par nya parametrar för att välja ljudspår.

**Comment by Sopor** [comment]
Och vad använder man i `svtplay-dl.yaml` för att välja ljud så man slipper ange det varje gång?

**Comment by olivertwistor** [comment]
> 
> 
> Och vad använder man i `svtplay-dl.yaml` för att välja ljud så man slipper ange det varje gång?

Enligt https://svtplay-dl.se/config/ är nyckeln `format_preferred`, t.ex.

```yaml
{
   "format_preferred": "h264-51"
}
```

**Comment by Sopor** [comment]
Är det inte bara till videon för den har jag redan. Jag pratar om `--audio-language` och `--audio-role`.

**Comment by olivertwistor** [comment]
@Sopor Du har rätt. Parametrarna audio-language och --audio-role har jag aldrig använt, så jag törs inte svara på det.

**Comment by Sopor** [comment]
@spaam How do i use `--audio-language` and `--audio-role` in the config file? I can't find them here either https://svtplay-dl.se/config

**Comment by spaam** [comment]
@Sopor as you can see here https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/utils/parser.py#L195 and https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/utils/parser.py#L203 its called `audio_language` and `audio_role` :)

**Comment by Sopor** [comment]
@spaam That was way too easy! You need to make it harder to find next time 😃

**Comment by spaam** [comment]
3.9.1 har fix för detta  :) testa o skapa en ny bugg rapport om det är fortfarande problem

**Comment by Ferbd-Git** [comment]
Hej spaam, tack så mycket för fixet, jag har testat, laddat ner en film (Gilbert Grape) utan den workaround som pythonuser3856 hade kommit på.
Resultatet av testet var positivt, filmen blev bra, utan den extra berättarröst över filmens originalljudet.
Så, bra jobbat, vi kan fortsätta att använda svtplay-dl som gör svtplay tjänsten så mycket mera flexibel och användbar.

**Comment by Ferbd-Git** [comment]
Ja, jag glömde att skriva att innan jag laddade ner filmen, installerade jag 3.9.1 versionen, så klart.
