### ISSUE TITLE
Välja ett specifikt avsnitt på discoveryplus

### ISSUE THREAD

**Issue by OliviaEljest** [spaam/svtplay-dl#1377]
Om man ska till exempel ladda ner en fotbollsmatch från discoveryplus, där individuella matcher inte har sin egen url, så laddar programmet ner den tidigaste matchen. Hade varit väldigt bra om man kunde få en lista på individuella "avsnitt" (matcher) och kunna välja därifrån vilken man vill ha.

**Comment by spaam** [comment]
just nu så finns det inget sätt för det för den sidan. om man ska tanka hem något där så får man köra -A för att ta hem alla avsitt.  men visst. de går väl kanske använda --exclude för att exkludera videos.

**Comment by OliviaEljest** [comment]
Aha, okej... Men varför skulle det inte gå att kunna få en lista i cmd-fönstret, eftersom att all information om alla avsnitt finns ifall man kör med -A?

**Comment by spaam** [comment]
varför? rätt simpelt, för att ingen har frågat om någon sådan funktionalitet tidigare.
vi har all info i skriptet redan med adresser till dom olika videos. det enda som behövs är att någon skriver koden för att lista det och komma på ett Kraftigt Bra namn till argumentet för det.

**Comment by spaam** [comment]
haha jag är dum, det finns redan visst. hade totalt glömt det.  det du vill ha är `-A --get-only-episode-url` :)
