### ISSUE TITLE
Missing episodes.

### ISSUE THREAD

**Issue by kjetilpp** [spaam/svtplay-dl#1379]
### svtplay-dl versions:

.\svtplay-dl.exe --version
svtplay-dl 3.7

### Operating system and Python version:

Windows 10

### What is the issue:

It only finds 43 episodes. Should be 149

.\svtplay-dl.exe  --cookies st="XXXxxXXX" --all-episodes --get-url https://www.discoveryplus.se/program/vagens-hjaltar

**Comment by spaam** [comment]
I get the correct number of episodes. i guess you dont have a paid subscription?  you need that to access all the conent.
