### ISSUE TITLE
Crash at using switch "--live" with SVTplay

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1380]
### svtplay-dl versions:
svtplay-dl version 3.7

### Operating system and Python version:
Windows 8.1
Python version 3.8.10

### What is the issue:

Run-time error with link
https://www.svtplay.se/video/31066038/mot-ljusare-tider/mot-ljusare-tider-sasong-1-10-maj-08-00

**Trace using --verbose:**
py c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\__main__.py --live --verbose https://www.svtplay.se/video/31066038/mot-ljusare-tider/mot-ljusare-tider-sasong-1-10-maj-08-00
DEBUG [1620682327.7435045] c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\getmedia.py/get_media: version: 3.7
DEBUG [1620682327.7435045] c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1620682327.7435045] c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/31066038/mot-ljusare-tider/mot-ljusare-tider-sasong-1-10-maj-08-00'
DEBUG [1620682327.7435045] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1620682327.8060248] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443
"GET /video/31066038/mot-ljusare-tider/mot-ljusare-tider-sasong-1-10-maj-08-00 HTTP/1.1" 200 33529
DEBUG [1620682327.8216357] c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/eWXkVPY'
DEBUG [1620682327.8216357] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1620682327.86853] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/eWXkVPY HTTP/1.1" 200 697
DEBUG [1620682327.86853] c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-event-16-c.akamaized.net/world/1402982-002W/manifest.mpd?defaultSubLang=1'
DEBUG [1620682327.86853] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-event-16-c.akamaized.net:443
DEBUG [1620682327.9466612] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://svt-event-16-c.akamaized.net:443 "GET /world/1402982-002W/manifest.mpd?defaultSubLang=1 HTTP/1.1" 200 935
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\__main__.py", line 15, in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\utils\getmedia.py", line 111, in get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\service\svtplay.py", line 95, in get
    yield from videos
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\service\svtplay.py", line 120, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\fetcher\dash.py",line 210, in dashparse
    return _dashparse(config, res.text, url, res.cookies, **kwargs)
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\fetcher\dash.py",line 225, in _dashparse
    attributes.set("availabilityStartTime", parse_dates(xml.attrib["availabilityStartTime"]))
  File "c:\svtplaydll\svtplay-dl_v3.7_2021-05-10py\svtplay_dl\fetcher\dash.py",line 305, in parse_dates
    raise ValueError(f"Can't parse date format: {date_str}")ValueError: Can't parse date format: 2021-05-10T06:00:11.451554796Z

**Comment by spaam** [comment]
so many decimals 🤔

**Comment by pythonuser3856** [comment]
Has SVT made a change ?
Using switch "--live" with a channel (e.g. https://www.svtplay.se/kanaler/svt1) also no longer works.

**Comment by spaam** [comment]
yees. they added nanoseconds. they had milliseconds before

**Comment by spaam** [comment]
i fixed the crash..  HLS works on kanaler.
dash does not support live streams.
