### ISSUE TITLE
"Can't find any playable files" when downloading a file from discoveryplus.se

### ISSUE THREAD

**Issue by hereinmyhead** [spaam/svtplay-dl#1383]
### svtplay-dl versions:

svtplay-dl 3.8

### Operating system and Python version:

Windows 10 Pro
Python 3.9

### What is the issue:

Can't download the following file from discoveryplus.se: 

svtplay-dl -S -A --verbose --cookies "st=COOKIE" https://www.discoveryplus.se/program/irene-huss-guldkalven
DEBUG [1620979133.8340032] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8
DEBUG [1620979133.8340032] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dplay
DEBUG [1620979133.8340032] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1620979133.8340032] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): disco-api.discoveryplus.se:443
DEBUG [1620979134.0215087] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1620979134.0215087] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/token?realm=dplayse&deviceId=XXXXX=true'
DEBUG [1620979134.083988] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /token?realm=dplayse&deviceId=XXXXXX=true HTTP/1.1" 200 None
DEBUG [1620979134.083988] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/users/me'
DEBUG [1620979134.131323] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /users/me HTTP/1.1" 200 None
DEBUG [1620979134.131323] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://disco-api.discoveryplus.se/cms/routes/program/irene-huss-guldkalven?decorators=viewingHistory&include=default'
DEBUG [1620979134.131323] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): disco-api.discoveryplus.se:80
DEBUG [1620979134.208998] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: http://disco-api.discoveryplus.se:80 "GET /cms/routes/program/irene-huss-guldkalven?decorators=viewingHistory&include=default HTTP/1.1" 301 134
DEBUG [1620979134.2558725] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/routes/program/irene-huss-guldkalven?decorators=viewingHistory&include=default HTTP/1.1" 200 None
DEBUG [1620979134.2558725] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://disco-api.discoveryplus.se/cms/collections/251888494693706608405313992779162623038?decorators=viewingHistory&include=default&page[items.number]=1&pf[seasonNumber]=1&pf[show.id]=17996'
DEBUG [1620979134.365245] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://disco-api.discoveryplus.se:443 "GET /cms/collections/251888494693706608405313992779162623038?decorators=viewingHistory&include=default&page%5Bitems.number%5D=1&pf%5BseasonNumber%5D=1&pf%5Bshow.id%5D=17996 HTTP/1.1" 200 None
ERROR [1620979134.365245] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dplay.py/find_all_episodes: Cant find any playable files

**Comment by spaam** [comment]
ohh fancy. something that is not a tv series 🤔

**Comment by spaam** [comment]
i committed a fix for this, it will be in a snapshot until next release beginning of next week.

**Comment by hereinmyhead** [comment]
thank you spaam! you are doing a really great job!
