### ISSUE TITLE
File name of standalone SVT Play programs

### ISSUE THREAD

**Issue by bohelax** [spaam/svtplay-dl#1385]
Sorry to bother you @spaam so soon after, I'm sure, exhausting work on the audio problem on SVT Play.

But, now standalone programs, not part of a series, gets their name twice in the file name (a problem similar to issue #1357, that has been fixed, thank you ).

For test purposes I use the program Tärnsommar that is not too large.
I also went back and downloaded a bunch of snapshots to determine when the effect first presented itself.
This is what I found:
bin>svtX https://www.svtplay.se/video/31107894/varldens-natur-tarnsommar 20210418_141114

bin>svtplay-dl_20210418_141114.py -S -M https://www.svtplay.se/video/31107894/varldens-natur-tarnsommar
INFO: Outfile: varldens.natur.tarnsommar-5a47a21-svtplay.srt
INFO: Selected to download dash, bitrate: 5946 format: h264
INFO: Outfile: varldens.natur.tarnsommar-5a47a21-svtplay.m4a
[043/760][=======......................................................................................
Terminate batch job (Y/N)? y

bin>svtX https://www.svtplay.se/video/31107894/varldens-natur-tarnsommar 20210419_203440

bin>svtplay-dl_20210419_203440.py -S -M https://www.svtplay.se/video/31107894/varldens-natur-tarnsommar
INFO: Outfile: varldens.natur.tarnsommar.varldens.natur.tarnsommar-5a47a21-svtplay.srt
INFO: Selected to download dash, bitrate: 5946 format: h264
INFO: Outfile: varldens.natur.tarnsommar.varldens.natur.tarnsommar-5a47a21-svtplay.m4a
[042/760][=======......................................................................................
Terminate batch job (Y/N)? y

So between snapshots 20210418_141114 and 20210419_203440 something happens with the file naming.
Hopefully this info may be of use to you.

_Note_ that this is at most a blemish and **not** a fault in svtplay-dl (the most excellent downloader!).

Forever grateful to you @spaam !!
//BoH

**Comment by spaam** [comment]
i see the issue.  added this because of a klipp thing last month. i have an idea how to fix it

**Comment by pythonuser3856** [comment]
At using version 3.9.1 the reported issue seems to have vanished
With an example link
https://www.svtplay.se/video/19690859/glenn-gould-spelar-bach
I got the auto-named file name
glenn.gould.spelar.bach-28bb054-svtplay.mp4

**Comment by spaam** [comment]
yep. closing this
