### ISSUE TITLE
DRM Protected from tv4play.se

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1389]
Using svtplay-dl version 3.8 Windows 10
When trying to download from tv4play.se: https://www.tv4play.se/program/miss-marple/del-2-hemligheten-p%C3%A5-chimneys-s%C3%A4song-5/2412287
I receive "No Videos Found. We can't download DRM protected content from this site"
It worked perfect a week(or maybe two weeks) ago.
This is my command line: svtplay-dl -S "%_inputname%"  <-------inputname = the url above.---------->

**Comment by Sopor** [comment]
When playing it in a web browser i get this message

![image](https://user-images.githubusercontent.com/5789283/119956439-64feeb80-bfa1-11eb-97e0-2f94360ac660.png)

So i assume TV4 has added DRM to it ...

**Comment by torbjornljung** [comment]
Hi ! Does it mean that it’s unfixable?

fre 28 maj 2021 kl. 10:43 skrev Sopor ***@***.***>:

**Comment by spaam** [comment]
its unfixable from svtplay-dl, cant do anything with it. i could just download it and you have unusable files. but i thought that would be waste of time and bandwidth, that is why i added that message :)
