### ISSUE TITLE
The audio track is the subtitle read instead of the original audio track

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1392]
I'm using the latest svtplay-dl version 3.8, Windows 10.
Here's the url: https://www.svtplay.se/video/31341026/de-var-fem/de-var-fem-avsnitt-1?id=8zJ1gvk
In Chrome you can see that it's optional: Uppläst undertext
Do you know if there's a solution to this ?

**Comment by Minherre** [comment]
Läs
https://github.com/spaam/svtplay-dl/issues/1376
Där finns lösningen att använda 
--stream-priority hls 
för att få 'rätt' ljudspår.

Även tråden
https://github.com/spaam/svtplay-dl/issues/1295
diskuterar detta.

**Comment by einarblaberg** [comment]
With the latest version from git you can use audio-role (and/or -language) 

```
$ svtplay-dl --list-quality https://www.svtplay.se/video/31341026/de-var-fem/de-var-fem-avsnitt-1?id=8zJ1gvk
INFO: Quality:   METHOD:  Codec:   Resolution:  Language:            Role:
INFO: 6157       DASH     hevc-51  1920x1080    sv                   main
INFO: 6157       DASH     hevc-51  1920x1080    sv-x-tydligaretal    alternate
INFO: 6157       DASH     hevc-51  1920x1080    sv-x-tal             dub

```

From the manpage
```
  --audio-language AUDIO_LANGUAGE
                        Choose the language of the audio (it can override the
                        default one), --list-quality to show which one to
                        choose from
  --audio-role AUDIO_ROLE
                        Choose the role of the audio (it can override the
                        default one), --list-quality to show which one to
                        choose from

```

**Comment by torbjornljung** [comment]
Hej !
Kolla bifogade skärmdump. När jag kör därifrån så funkar det !!! Undertexterna läses inte längre upp. Perfekt nerladdning.
Här är kommandot jag använde, vilket är det jag använt under en längre tid utan ändring:

svtplay-dl -S -A -u torbjornljung@gmail.com -p Aspu2den --exclude=syntolkat,teckensprakstolkat https://www.svtplay.se/video/31341026/de-var-fem/de-var-fem-avsnitt-1?id=8zJ1gvk
![Skärmbild (221)](https://user-images.githubusercontent.com/33009810/120291430-96d6c180-c2c3-11eb-8c10-82068991c8f7.png)
Bifogar också en skärmbild från mappen som inte funkar(undertexterna läses)
![Skärmbild (222)](https://user-images.githubusercontent.com/33009810/120291791-fc2ab280-c2c3-11eb-9459-0177d714da12.png)
-----------------Klurigt-------------------------

**Comment by Minherre** [comment]
Av vilken anledning lägger du in din email och password när du ska hämta från Svt?

"torbjornljung@gmail.com -p Aspu2den "

**Comment by spaam** [comment]
Du behöver inget användarnamn och lösenord till svtplay. Det är andra siter so. Behöver det.

**Comment by torbjornljung** [comment]
Oj, sorry, det var inte meningen, den brukar jag använda till viafree.
Kan du ta bort det ? Onödigt att det visas.


Den tis 1 juni 2021 kl 20:09 skrev Minherre ***@***.***>:

**Comment by torbjornljung** [comment]
Oj, sorry, det var inte meningen, den brukar jag använda till viafree.
Kan du ta bort det ? Onödigt att det visas.

Den tis 1 juni 2021 kl 20:15 skrev Johan Andersson ***@***.***

**Comment by torbjornljung** [comment]
Har nu tagit bort user/pwd

**Comment by spaam** [comment]
Kommer släppa en ny version imorgon med lite fixar om detta.

**Comment by torbjornljung** [comment]
Körde igen från den mapp som funkade, men utan user/pwd.
Fungerade.
Här kommer en skärmdump som visar vilken ljudfil som automatiskt valdes.
![Skärmbild (223)](https://user-images.githubusercontent.com/33009810/120373511-b946fa00-c318-11eb-858d-c87f54af590b.png)

**Comment by torbjornljung** [comment]
Hej Minherre, kan du ta bort mitt user/pwd ?

Den tis 1 juni 2021 kl 20:09 skrev Minherre ***@***.***>:

**Comment by spaam** [comment]
3.9.1  är en bra grej. använd det :)

**Comment by torbjornljung** [comment]
Hej,
Funkade bra 😊

Den mån 7 juni 2021 kl 20:56 skrev Johan Andersson ***@***.***
