### ISSUE TITLE
Cmore: Wrong username or password

### ISSUE THREAD

**Issue by hereinmyhead** [spaam/svtplay-dl#1393]
### svtplay-dl versions:
svtplay-dl 3.8-25-g88432ed

### Operating system and Python version:
Windows 10 Pro x64
Python 3.9

### What is the issue:

I can't download from Cmore. I get this error message: "Wrong username or password"

**Username & password**
When I use username and password command I get this:

> svtplay-dl -S -A --verbose -u XXXXXX -p XXXXXX https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
DEBUG [1622720701.0691483] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
DEBUG [1622720701.0701487] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
DEBUG [1622720701.07115] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
DEBUG [1622720701.0741494] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
DEBUG [1622720701.2671638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
ERROR [1622720701.2681653] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password

**st cookie**
When I use "st cookie" command I get this:

> svtplay-dl -S -A --verbose --cookies "st=XXXXXXXXXXXXXXXXXXXXX" https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
DEBUG [1622720271.1219566] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
DEBUG [1622720271.1259577] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
DEBUG [1622720271.2409518] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
ERROR [1622720271.241952] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password

I can't find the "st cookie" value with the guide at [https://svtplay-dl.se/stuff/dplay-chrome.png](url). I'am using Chrome. When I open `Developer Mode` and choose tab `Application` and navigate to `Cookies` in the menu to the left I get bounch of cmore.se-cookies. There is no value with "user" or "st" in it. The closest thing I can find is `sessionToken` that I tried got the error message above.

Am I doning something wrong?

**Comment by spaam** [comment]
it seems like you wrote the wrong  user and/or password. i tested it now and it works for me without any issues.

the `st` cookie thing is only for the site `Discovery+`

**Comment by hereinmyhead** [comment]
Oh, I see that now! Sorry for bothering you with my stupid mistake! Have a nice day!

**Comment by spaam** [comment]
its okey glad you found the issue ,  but i found that the -A option is broken now on cmore so that does not work and i need to fix that :)

**Comment by hereinmyhead** [comment]
👍 I saw that too now and thank you!

**Comment by aye8ge82** [comment]
> 
> 
> 
> 
> ### svtplay-dl versions:
> svtplay-dl 3.8-25-g88432ed
> 
> ### Operating system and Python version:
> Windows 10 Pro x64
> Python 3.9
> 
> ### What is the issue:
> 
> I can't download from Cmore. I get this error message: "Wrong username or password"
> 
> **Username & password**
> When I use username and password command I get this:
> 
> > svtplay-dl -S -A --verbose -u XXXXXX -p XXXXXX https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720701.0691483] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720701.0701487] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720701.07115] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720701.0741494] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720701.2671638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720701.2681653] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> **st cookie**
> When I use "st cookie" command I get this:
> 
> > svtplay-dl -S -A --verbose --cookies "st=XXXXXXXXXXXXXXXXXXXXX" https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720271.1219566] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720271.1259577] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720271.2409518] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720271.241952] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> I can't find the "st cookie" value with the guide at [https://svtplay-dl.se/stuff/dplay-chrome.png](url). I'am using Chrome. When I open `Developer Mode` and choose tab `Application` and navigate to `Cookies` in the menu to the left I get bounch of cmore.se-cookies. There is no value with "user" or "st" in it. The closest thing I can find is `sessionToken` that I tried got the error message above.
> 
> Am I doning something wrong?
> 
> 
>

**Comment by aye8ge82** [comment]
> 
> 
> 
> 
> ### svtplay-dl versions:
> svtplay-dl 3.8-25-g88432ed
> 
> ### Operating system and Python version:
> Windows 10 Pro x64
> Python 3.9
> 
> ### What is the issue:
> 
> I can't download from Cmore. I get this error message: "Wrong username or password"
> 
> **Username & password**
> When I use username and password command I get this:
> 
> > svtplay-dl -S -A --verbose -u XXXXXX -p XXXXXX https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720701.0691483] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720701.0701487] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720701.07115] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720701.0741494] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720701.2671638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720701.2681653] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> **st cookie**
> When I use "st cookie" command I get this:
> 
> > svtplay-dl -S -A --verbose --cookies "st=XXXXXXXXXXXXXXXXXXXXX" https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720271.1219566] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720271.1259577] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720271.2409518] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720271.241952] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> I can't find the "st cookie" value with the guide at [https://svtplay-dl.se/stuff/dplay-chrome.png](url). I'am using Chrome. When I open `Developer Mode` and choose tab `Application` and navigate to `Cookies` in the menu to the left I get bounch of cmore.se-cookies. There is no value with "user" or "st" in it. The closest thing I can find is `sessionToken` that I tried got the error message above.
> 
> Am I doning something wrong?
> 
> 
>

**Comment by aye8ge82** [comment]
> 
> 
> 
> 
> ### svtplay-dl versions:
> svtplay-dl 3.8-25-g88432ed
> 
> ### Operating system and Python version:
> Windows 10 Pro x64
> Python 3.9
> 
> ### What is the issue:
> 
> I can't download from Cmore. I get this error message: "Wrong username or password"
> 
> **Username & password**
> When I use username and password command I get this:
> 
> > svtplay-dl -S -A --verbose -u XXXXXX -p XXXXXX https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720701.0691483] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720701.0701487] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720701.07115] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720701.0741494] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720701.2671638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720701.2681653] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> **st cookie**
> When I use "st cookie" command I get this:
> 
> > svtplay-dl -S -A --verbose --cookies "st=XXXXXXXXXXXXXXXXXXXXX" https://www.cmore.se/serie/212873-fem-killar-i-veckan/sasong-1/episod-1/13309897-fem-killar-i-veckan
> DEBUG [1622720271.1219566] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8-25-g88432ed
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: cmore
> DEBUG [1622720271.1229558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://account-delta.b17g.services/api?client=cmore-web'
> DEBUG [1622720271.1259577] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): account-delta.b17g.services:443
> DEBUG [1622720271.2409518] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://account-delta.b17g.services:443 "POST /api?client=cmore-web HTTP/1.1" 403 919
> ERROR [1622720271.241952] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\cmore.py/find_all_episodes: Wrong username or password
> 
> I can't find the "st cookie" value with the guide at [https://svtplay-dl.se/stuff/dplay-chrome.png](url). I'am using Chrome. When I open `Developer Mode` and choose tab `Application` and navigate to `Cookies` in the menu to the left I get bounch of cmore.se-cookies. There is no val

 with "user" or "st" in it. The closest thing I can find is `sessionToken` that I tried got the error message above.
> 
> Am I doning something wrong?
> 
> 
>
