### ISSUE TITLE
Issue using -A on dr.dk

### ISSUE THREAD

**Issue by Elfie84** [spaam/svtplay-dl#1394]
### svtplay-dl versions:

svtplay-dl --version 3.8

### Operating system and Python version:

Windows 10

### What is the issue:

I don't have much experience coding so i havn't been able to solve this on my own. Trying to get single episodes work just fine however when i try to use the -A function on dr.dk it doesn't seem to work. I have gotten it to work on svtplay.se so i think im doing it right. Anyone got any tips on how to get all episodes from a series on dr.dk?

C:\Users\johan\Downloads\svtplay-dl-amd64\svtplay-dl>svtplay-dl -A --verbose https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
DEBUG [1622974787.649632] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 3.8
DEBUG [1622974787.649632] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: dr
DEBUG [1622974787.6521175] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008'
DEBUG [1622974787.6557598] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.dr.dk:443
DEBUG [1622974787.8126104] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.dr.dk:443 "GET /drtv/saeson/frank-and-kastaniegaarden_9008 HTTP/1.1" 200 70625
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 81, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 36, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 60, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 78, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\dr.py", line 68, in find_all_episodes
KeyError: 'item'

**Comment by SweDennis** [comment]
Confirmed using:

```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.8+31.ga3642b8
dennis@Lenovo:~$ uname -a
Linux Lenovo 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@Lenovo:~$ python --version
Python 3.8.5
```

**Comment by SweDennis** [comment]
Sounds suspiciously similar to previous problems with dplus, albetit different errors. Single episodes work, but -A doesn't.

/Dennis

**Comment by spaam** [comment]
i found some videos that had some issues  :)

**Comment by SweDennis** [comment]
Good for you, enjoy the watching. Teamviewer available as before if need be. :-D

**Comment by spaam** [comment]
one of the issues is that i expected that one of the values to be first in a list of items. but some videos , its not true :)

**Comment by SweDennis** [comment]
I don't speak greek. I'm fluent in Swedish and English ...

**Comment by Elfie84** [comment]
So... Does that mean there might be a solution to this or do i have to get the 255 episodes of Bonderöven one by one?

**Comment by spaam** [comment]
2.9.1 have a fix for it.  :)

**Comment by Elfie84** [comment]
Nice. Thx!
