### ISSUE TITLE
How to download from discoveryplus.se with svtplay-dl?

### ISSUE THREAD

**Issue by myowncloudX** [spaam/svtplay-dl#1396]
Hi, I'm wondering how I should proceed to be able to download from discoveryplus.se

I'm a subscriber to Live

**Comment by spaam** [comment]
you need to use the `st` cookie that you get from the webpage, if you are using chrome, you can click on the lock 🔒  next to the adress field. then choose cookies , then the disco-api url, then you should see the `st` cookie there.  copy the content from it. it should be a looong text string.  then you will have to add it to the cookies argument to the script. like `svtplay-dl --cookies "st=VERYLONGSTRING" https://www.discoveryplus.se/URL`  replace the `VERYLONGSTRING` with the cookie content you copied before :) 

the content of the cookie is pretty private to your account so you should _NOT_ share it :)
