### ISSUE TITLE
tv4play thumbnail is ASCII file

### ISSUE THREAD

**Issue by jula420** [spaam/svtplay-dl#1399]
### svtplay-dl versions:

svtplay-dl 4.0-4-gc5ae975

### Operating system and Python version:

Ubuntu 20.04.2 LTS
Python 3.8.10

### What is the issue:

thumbnail for tv4play is not an image file, for instance
svtplay-dl -t https://www.tv4play.se/program/mord-i-paradiset/13319955

**Comment by spaam** [comment]
this is fixed in 4.1  that i just released :)
