### ISSUE TITLE
Windows defender gives warnings about Trojan:Win32/Wacatac.B!ml in latest distribution

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1402]
Index of /download/snapshots/20210709_183031/svtplay-dl-win32.zip

I scanned the unzipped files with Windows Defender and got this warning about the distribution:

Trojan:Win32/Wacatac.B!ml    Severe

**Comment by bartdedecker** [comment]
file: Downloads\svtplay-dl\svtplay-dl\svtplay-dl.exe

Alert level: Severe
Details: This program is dangerous and executes commands from an attacker.

**Comment by spaam** [comment]
its a false positive.  it happens every now and then. if you dont trust the .exe is virus free,  feel free to install python and install the script via pip  instead :)

**Comment by spaam** [comment]
maybe you should try the 64bit version instead? it seems a bit better according to 
https://www.virustotal.com/gui/file/155f35be4e2a87328e04984634863ef733d77d18664de10da9de3739cbeaeeee/detection
vs
32bit https://www.virustotal.com/gui/file/967dcca25e3d8f504536af554288a17d4f5efd4de299d493697672bf32d7a4bb/detection
