### ISSUE TITLE
Viafree requires -v (verbose) to work

### ISSUE THREAD

**Issue by frepe360** [spaam/svtplay-dl#1403]
### What is the issue:

Downloading from viafree.se works if I use the verbose flag (-v), but if I do not use -v, the svtplay-dl shows:

ERROR: No videos found. You need to login

This URL: https://www.viafree.se/program/reality/svenska-truckers/sasong-3/avsnitt-1

I am using my personal username and password.

**Comment by frepe360** [comment]
This could be wrong, sorry... it works sometimes, sometimes not, even with the -v flag.

**Comment by spaam** [comment]
it seems to be some issue on their ends.  i get random issues too with and without `-v`.  when i try to login to their website i get issues too..

**Comment by frepe360** [comment]
Ok, thanks. I'll just keep trying. It usually works within 5-10 attempts.

**Comment by SweDennis** [comment]
```
dennis@lenovo:~$ uname -a
Linux lenovo 5.11.0-22-generic #23~20.04.1-Ubuntu SMP Thu Jun 17 12:51:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
dennis@lenovo:~$ svtplay-dl --version
svtplay-dl 4.1
dennis@lenovo:~$ python --version
Python 3.8.10
dennis@lenovo:~$ 
```
Most definitely an issue with viafree, I tried this:

1. Tried the above link without -v, got the login error, twice
2. Tried the above link with -v, got the login error, twice
3. Tried the above link without -v, it all worked fine.

All three tests within one minute of each other.
New to me, can't say I've ever seen it before, but now I do.

/Dennis

**Comment by frepe360** [comment]
I agree. There is something funny about the viafree site, which causes this. It seems to have absolutely nothing to do with the -v flag, this issue can be set to resolved.

**Comment by spaam** [comment]
closing this :)
