### ISSUE TITLE
Cannot download from Viafree

### ISSUE THREAD

**Issue by torbjornljung** [spaam/svtplay-dl#1406]
It used to work properly. My command-line is correct with login info.
But now svtplay-dl crashes when downloading from viafree.se.
Installed the latest version 4.2. Downloading from Svtplay works as before.
Please try to download https://www.viafree.se/program/drama/doc-martin/sasong-9/avsnitt-1 from viafree.se.
![Skärmbild (246)](https://user-images.githubusercontent.com/33009810/127917267-25bf8d77-41ff-4fe1-a002-3224e62d87d9.png)

**Comment by spaam** [comment]
it works great here.  what does it say when you add `-v` flag when you download the video?

**Comment by torbjornljung** [comment]
Hi !
Sorry but it's like Greek to me. Hoefully you might understand what it
said, look at the attachments.

Den mån 2 aug. 2021 kl 22:09 skrev Johan Andersson ***@***.***

**Comment by spaam** [comment]
i dont see any attachments :)

**Comment by torbjornljung** [comment]
![Skärmbild (248)](https://user-images.githubusercontent.com/33009810/127925279-d50f4f50-2f1e-48f2-bef3-124bd64e4c9e.png)
![Skärmbild (247)](https://user-images.githubusercontent.com/33009810/127925283-c0d20daa-ed5b-4a09-bc9a-093344d3c798.png)

**Comment by torbjornljung** [comment]
I attached 2 screen-dumps previously by mail. Now I've updated it in
Github. Hope you can see them now

Den mån 2 aug. 2021 kl 23:16 skrev Johan Andersson ***@***.***

**Comment by spaam** [comment]
for some reason you got a space between `"` and  `https`    like this `" https://"` .  sometimes you got `http:// http://www.viafree`

**Comment by torbjornljung** [comment]
OK Now I've corrected that, and here comes the error/log
![Skärmbild (249)](https://user-images.githubusercontent.com/33009810/127926098-d9fd64cc-6245-4581-95e3-502c55fa6f1a.png)

**Comment by torbjornljung** [comment]
Ohhh Sorry but now I see I'm not logged in. I will change that immediately

**Comment by spaam** [comment]
congratz.  now you just need to send it the correct credentials for the site using ´-u UserName -p SuperPassword` or use a config like its described here https://svtplay-dl.se/config/ look at the dplay sample config but replace dplay with viafree  :)

**Comment by torbjornljung** [comment]
![Skärmbild (250)](https://user-images.githubusercontent.com/33009810/127926638-7e4fac40-4c76-4f4e-85c8-a7948f20dcc6.png)

**Comment by torbjornljung** [comment]
OK,here comes the latest try

Den mån 2 aug. 2021 kl 23:24 skrev Johan Andersson ***@***.***

**Comment by torbjornljung** [comment]
The screen-dump can be viewed in Github


Den mån 2 aug. 2021 kl 23:24 skrev Johan Andersson ***@***.***

**Comment by spaam** [comment]
are you trying to access some swedish content outside of sweden? the latest screenshot shows a http 403 error message when trying to access the video data.  maybe its because of geoblocking.

**Comment by torbjornljung** [comment]
Hi again! But I've downloaded from Viafree before by using only the
command-line ?

Den mån 2 aug. 2021 kl 23:30 skrev Johan Andersson ***@***.***

**Comment by torbjornljung** [comment]
No my IP is from Sweden

Den mån 2 aug. 2021 kl 23:48 skrev Johan Andersson ***@***.***

**Comment by spaam** [comment]
what kind of arguments are you using in your script?  i cant reproduce this at all.

**Comment by torbjornljung** [comment]
Hi !
Maybe you can try the command I used:
svtplay-dl -S -v -u ***@***.*** -p Password "
https://www.viafree.se/program/drama/doc-martin/sasong-9/avsnitt-1"

Den mån 2 aug. 2021 kl 23:54 skrev Johan Andersson ***@***.***

**Comment by torbjornljung** [comment]
The -u should not be there, sorry

**Comment by torbjornljung** [comment]
Ohh sorry, of course the -u should be there, meaning User.
Now I run it again with the --verbose option
![Skärmbild (251)](https://user-images.githubusercontent.com/33009810/127929886-a9241dd2-a6bd-4870-9e20-9153aa459754.png)

**Comment by Gurkan911** [comment]
I seem to have the same issue with Viafree. It worked fine a couple of weeks ago but now when I try to download NCIS or S.W.A.T svtplay-dl will crash.

svtplay-dl  --verbose --username **** --password **** https://www.viafree.se/program/crime/swat/sasong-4/avsnitt-14

DEBUG [1628840300.02678] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.1-5-gc05a736
DEBUG [1628840300.0317726] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viafree
DEBUG [1628840300.0317726] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/crime/swat/sasong-4/avsnitt-14cls'
DEBUG [1628840300.0427544] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1628840300.1698313] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/crime/swat/sasong-4/avsnitt-14cls HTTP/1.1" 200 None
DEBUG [1628840300.1748247] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://viafree.mtg-api.com/identity/viafree/auth/pwd/sessions'
DEBUG [1628840300.181814] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): viafree.mtg-api.com:443
DEBUG [1628840300.4624836] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://viafree.mtg-api.com:443 "POST /identity/viafree/auth/pwd/sessions HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\viaplay.py", line 53, in get
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\__init__.py", line 357, in loads
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\decoder.py", line 337, in decode
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 14193 (char 14192)

Any thoughts?

**Comment by bartdedecker** [comment]
I have also the same problem with the json decoder.

>svtplay-dl --version
svtplay-dl 4.2-2-g52d98a8

>svtplay-dl --verbose -u **** -p **** -A --get-only-episode-url https://www.viafree.se/program/dokumentar/svenska-fall
DEBUG [1628885316.3722863] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.2-2-g52d98a8
DEBUG [1628885316.379282] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viafree
DEBUG [1628885316.380281] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/dokumentar/svenska-fall'
DEBUG [1628885316.812035] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1628885317.502637] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/dokumentar/svenska-fall HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 104, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\viaplay.py", line 130, in find_all_episodes
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\__init__.py", line 357, in loads
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\decoder.py", line 337, in decode
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 51297 (char 51296)

**Comment by spaam** [comment]
the json thing is fixed earlier today.  i will be releasing a new version on sunday, if you cant wait there is a snapshot with the fix on the web page :)

**Comment by bartdedecker** [comment]
You should apply the fix on line 52 (replace undefined by null)  also to line 130.

**Comment by torbjornljung** [comment]
Cannot find the new version, the latest is still from 2021-07-23.

Den fre 13 aug. 2021 kl 22:22 skrev Johan Andersson <
***@***.***>:

**Comment by torbjornljung** [comment]
spaam: When are you going to release the fixed version ?

**Comment by Umeaboy** [comment]
I've just successfully downloaded that clip in Linux using a newly compiled version of svtplay-dl and all I wrote was:

svtplay-dl https://www.viafree.se/program/crime/swat/sasong-4/avsnitt-14 --user=EMAILHIDDENFORPRIVACYREASONS --password=PASSWORDHIDDENFORPRIVACYREASONS

INFO: Outfile: s.w.a.t..s04e14.avsnitt.14-1056078-viafree.ts
INFO: Selected to download hls, bitrate: 4377 format: h264-51
[297/297][=====================================================================================================================================================================================================] ETA: 0:00:00
[297/297][=====================================================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into s.w.a.t..s04e14.avsnitt.14-1056078-viafree.mp4
INFO: Merging done, removing old files.

**Comment by kristofferjalen** [comment]
@torbjornljung Fixed version is here: https://svtplay-dl.se/download/snapshots/

**Comment by bartdedecker** [comment]
The patch is incomplete: line 130 of viaplay.py should be
janson = json.loads("{}{}".format("{", match.group(1).replace("undefined", "null")))
(cfr. line 52)
Otherwise -A will fail.

**Comment by torbjornljung** [comment]
Thanks Kristoffer ! Now it works beautifully :)

Den ons 1 sep. 2021 kl 16:28 skrev Kristoffer Jälén <
***@***.***>:

**Comment by Erbe28** [comment]
Why not just release a new version with the viafreefix ( and all other fixes)? I can't get it to work with my mac's.
