### ISSUE TITLE
Viafree and tv4play won't work

### ISSUE THREAD

**Issue by fladerfilip** [spaam/svtplay-dl#1410]
svtplay-dl 4.2

Python 2.7.18

DEBUG [1629647913.2220726] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.2
DEBUG [1629647913.2227783] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: viafree
DEBUG [1629647913.2228143] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/film/vice/film/1052733'
DEBUG [1629647913.223676] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1629647913.2776105] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/film/vice/film/1052733 HTTP/1.1" 200 None
DEBUG [1629647913.2808366] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://viafree.mtg-api.com/identity/viafree/auth/pwd/sessions'
DEBUG [1629647913.281594] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): viafree.mtg-api.com:443
DEBUG [1629647913.561013] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://viafree.mtg-api.com:443 "POST /identity/viafree/auth/pwd/sessions HTTP/1.1" 200 2302
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/viaplay.py", line 53, in get
    janson = json.loads("{}{}".format("{", match.group(1)))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 15901 (char 15900)

**Comment by spaam** [comment]
i only see viafree here and it was fixed in master. if tv4play is an issue , create a different issue
