### ISSUE TITLE
Downloading the Hjerson series from Swedish TV4 fails

### ISSUE THREAD

**Issue by erikatl** [spaam/svtplay-dl#1416]
### svtplay-dl versions:
svtplay-dl 4.3

### Operating system and Python version:
OS: Manjaro Linux x86_64
Desktop Environment: Plasma 5.22.5 
Kernel: 5.14.0-0-MANJARO
Python 3.9.6

### What is the issue:

    /media/ilios/uppladdat  svtdl --verbose https://www.tv4play.se/program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794
DEBUG [1631467305.3215158] /usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.3
DEBUG [1631467305.324299] /usr/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1631467305.3243566] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794'
DEBUG [1631467305.3275154] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1631467305.86478] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794 HTTP/1.1" 200 None
DEBUG [1631467305.8746793] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1631467305.881833] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1631467306.1257277] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
DEBUG [1631467306.1262376] /usr/lib/python3.9/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1631467306.126521] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1631467306.283328] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
DEBUG [1631467306.2838044] /usr/lib/python3.9/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1631467306.8848171] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1631467307.0048444] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
DEBUG [1631467307.005387] /usr/lib/python3.9/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1631467308.2069159] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1631467308.336353] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
DEBUG [1631467308.336746] /usr/lib/python3.9/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1631467310.7394664] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1631467310.877409] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
DEBUG [1631467310.8779104] /usr/lib/python3.9/site-packages/urllib3/util/retry.py/increment: Incremented Retry for (url='/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1631467315.682054] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/urlopen: Retry: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome
DEBUG [1631467315.7846758] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 500 113
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 846, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3.9/site-packages/svtplay_dl/service/tv4play.py", line 70, in get
    res = self.http.request("get", url, cookies=self.cookies)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py", line 42, in request
    res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='playback-api.b17g.net', port=443): Max retries exceeded with url: /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome (Caused by ResponseError('too many 500 error responses'))

**Comment by spaam** [comment]
Do you use a proxy or vpn or something similar?

**Comment by erikatl** [comment]
Yes I have my Surfshark VPN active. Does it interfere with your fantastic download service?

**Comment by erikatl** [comment]
The error messages look to me quite the same after closing my VPN (I am not an expert in any way...):
    /media/ilios/uppladdat  svtdl --verbose https://www.tv4play.se/program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794
DEBUG [1631481221.1029541] /usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.3
DEBUG [1631481221.1057522] /usr/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1631481221.1058097] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794'
DEBUG [1631481221.1089613] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1631481221.4906442] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/agatha-christies-hjerson/del-1-s%C3%A4song-1/13326794 HTTP/1.1" 200 None
DEBUG [1631481221.4962304] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1631481221.5006042] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1631481221.6263876] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13326794?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 200 953
DEBUG [1631481221.6274414] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP).m3u8?hls_no_audio_only=true'
DEBUG [1631481221.6348124] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se:443
DEBUG [1631481221.6657298] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP).m3u8?hls_no_audio_only=true HTTP/1.1" 200 653
DEBUG [1631481221.676574] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000.m3u8'
DEBUG [1631481221.6836474] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000.m3u8 HTTP/1.1" 200 2145
DEBUG [1631481221.6966] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP).mpd?hls_no_audio_only=true'
DEBUG [1631481221.704326] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP).mpd?hls_no_audio_only=true HTTP/1.1" 200 22757
INFO [1631481221.8964639] /usr/lib/python3.9/site-packages/svtplay_dl/utils/output.py/find_dupes: Outfile: agatha-christies-hjerson.s01e01.agatha.christies.hjerson.del.1.srt
DEBUG [1631481221.8966] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1631481221.8993835] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se:443
DEBUG [1631481221.9210212] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 302 0
DEBUG [1631481221.924844] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): hy-cdne12.streaming.cmore.se:443
DEBUG [1631481221.9482138] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 57
DEBUG [1631481221.9487922] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt'
DEBUG [1631481221.9535234] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 302 0
DEBUG [1631481221.958907] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-1.webvtt HTTP/1.1" 200 57
DEBUG [1631481221.959638] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-2.webvtt'
DEBUG [1631481221.9640775] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-2.webvtt HTTP/1.1" 302 0
DEBUG [1631481221.9693127] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-2.webvtt HTTP/1.1" 200 58
DEBUG [1631481221.9698029] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-3.webvtt'
DEBUG [1631481221.9744709] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-3.webvtt HTTP/1.1" 302 0
DEBUG [1631481221.9797022] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-3.webvtt HTTP/1.1" 200 58
DEBUG [1631481221.9801648] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-4.webvtt'
DEBUG [1631481221.9846663] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-4.webvtt HTTP/1.1" 302 0
DEBUG [1631481221.9899251] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-4.webvtt HTTP/1.1" 200 58
DEBUG [1631481221.9903965] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-5.webvtt'
DEBUG [1631481221.9950054] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-5.webvtt HTTP/1.1" 302 0
DEBUG [1631481222.000271] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-5.webvtt HTTP/1.1" 200 58
DEBUG [1631481222.0010357] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-6.webvtt'
DEBUG [1631481222.005557] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-6.webvtt HTTP/1.1" 302 0
DEBUG [1631481222.0109744] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-6.webvtt HTTP/1.1" 200 58
DEBUG [1631481222.0114665] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-7.webvtt'
DEBUG [1631481222.0158696] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-7.webvtt HTTP/1.1" 302 0
DEBUG [1631481222.0210345] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-7.webvtt HTTP/1.1" 200 58
DEBUG [1631481222.021511] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-8.webvtt'
DEBUG [1631481222.0258226] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-8.webvtt HTTP/1.1" 302 0
DEBUG [1631481222.0311573] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-8.webvtt HTTP/1.1" 200 246
DEBUG [1631481222.0320623] /usr/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-9.webvtt'
DEBUG [1631481222.036489] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-9.webvtt HTTP/1.1" 302 0
DEBUG [1631481222.041632] /usr/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://hy-cdne12.streaming.cmore.se:443 "GET /vod/6b75a/y3dh5dne0uc(13326794_ISMUSP).ism/y3dh5dne0uc(13326794_ISMUSP)-textstream_swe=3000-9.webvtt HTTP/1.1" 200 258
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 159, in get_one_media
    subtitle_decider(stream, subtitles)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/utils/stream.py", line 115, in subtitle_decider
    subtitles[0].download()
  File "/usr/lib/python3.9/site-packages/svtplay_dl/subtitle/__init__.py", line 67, in download
    data = self.wrstsegment(subdata)
  File "/usr/lib/python3.9/site-packages/svtplay_dl/subtitle/__init__.py", line 318, in wrstsegment
    subs[-1][0] = f"{ha.group(1).replace('.', ',')} --> {sec2str(second).replace('.', ',')}"
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by spaam** [comment]
Yes tv4play is blocking is the thing sadly, they do it in a wrong way..
the `AttributeError: 'NoneType' object has no attribute 'group'` issue you got without VPN is fixed in master and will be in the next release.

**Comment by erikatl** [comment]
Thank you for your support. And for keeping this service alive. Much appreciated.
