### ISSUE TITLE
Several Virustotal warnings 32-bit version

### ISSUE THREAD

**Issue by sed03** [spaam/svtplay-dl#1417]
This doesn't look good for the latest 32-bit version:
https://www.virustotal.com/gui/file/b16092f29a7ce64b8837f39d288198087e6ba1be608809e22420d7c8a06f8f8b

Several _Gen:Variant.Fugrafa.153511_ warnings.

Probably false positives.

**Comment by spaam** [comment]
yes its a false positive.   the 64bit version is less prone to get false positive
