### ISSUE TITLE
tv4play.se "No videos found" after site update.

### ISSUE THREAD

**Issue by towil1** [spaam/svtplay-dl#1418]
### svtplay-dl versions:

4.4-dirty

### Operating system and Python version:

Ubuntu 18.04.5
Python3 3.6.9

### What is the issue:

tv4play.se got a new look around 13:30 today, and after that the videos cannot be found:

svtplay-dl --verbose https://www.tv4play.se/program/zerozerozero/del-2-t
ampico-skies-s%C3%A4song-1/13347475
DEBUG [1631543059.0350678] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.4-dirty
DEBUG [1631543059.0411396] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1631543059.0413032] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/zerozerozero/del-2-tampico-skies-s%C3%A4song-1/13347475'
DEBUG [1631543059.0418785] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: TOWIL proxy {'http': 'http://localhost:28888', 'https': 'http://localhost:28888'}
DEBUG [1631543059.0458307] /home/towil/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1631543059.6253376] /home/towil/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/zerozerozero/del-2-tampico-skies-s%C3%A4song-1/13347475 HTTP/1.1" 200 None
ERROR [1631543059.6820135] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Cant find video id for the video

**Comment by spaam** [comment]
this is fixed in master and will be in the next release on wednesday.
