### ISSUE TITLE
TV4Play change subtitling - WebVTT 

### ISSUE THREAD

**Issue by Lunarwalker60** [spaam/svtplay-dl#1419]
Last week downloading "Agatha Christies Hjerson S01E06" worked fine. This week S01E07 doesn't work.
Is this known and will there be a remedy?

svtplay-dl -v -f -o "Agatha Christies Hjerson - S01E07" -S --all-subtitles --force-subtitle "https://www.tv4play.se/program/agatha-christies-hjerson/del-7-s%C3%A4song-1/13329169"

DEBUG [1631692200.8093746] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.4
DEBUG [1631692200.8113747] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1631692200.8113747] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/agatha-christies-hjerson/del-7-s%C3%A4song-1/13329169'
DEBUG [1631692200.8153749] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1631692201.290402] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/agatha-christies-hjerson/del-7-s%C3%A4song-1/13329169 HTTP/1.1" 200 None

**Comment by spaam** [comment]
this is fixed in master. i will release 4.5  tonight :)

**Comment by Lunarwalker60** [comment]
Toppen - tackar på förhand! --Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2021-09-15, 10:14 Johan Andersson ***@***.***> wrote:

   
  this is fixed in master. i will release 4.5 tonight :)

**Comment by Lunarwalker60** [comment]
Works like charm! (Y)
Tacksomfan!
