### ISSUE TITLE
TV4Play stopped working (again) v4.5

### ISSUE THREAD

**Issue by Geestarraw** [spaam/svtplay-dl#1420]
### svtplay-dl versions:
4.5

### Operating system and Python version:
Windows 10
Python 3.8.10

### What is the issue:

Downloading from TV4Play doesn't work. It worked previous week.

svtplay-dl.exe --verbose --stream-priority dash https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/del-2-s%C3%A4song-10/11979041

DEBUG [1632044645.8272622] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.5
DEBUG [1632044645.8292563] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1632044645.8292563] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/del-2-s%C3%A4song-10/11979041'
DEBUG [1632044645.835261] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1632044646.690261] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/s%C3%A5-mycket-b%C3%A4ttre/del-2-s%C3%A4song-10/11979041 HTTP/1.1" 200 None
ERROR [1632044646.7152672] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. We can't download DRM protected content from this site.

**Comment by spaam** [comment]
the error message is pretty clear. they got DRM on the video and we cant do anything with it sadly.

**Comment by Geestarraw** [comment]
@spaam Could that really be correct? I was more thinking the "no videos found" part of the error was the problem. The first episode of the season works without any problem:
https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/del-1-s%C3%A4song-10/11979046

**Comment by Geestarraw** [comment]
As do the latest season https://www.tv4play.se/program/s%C3%A5-mycket-b%C3%A4ttre/del-1-s%C3%A4song-11/12580265

**Comment by spaam** [comment]
@Geestarraw before they only had the drm info later in the playlist file where the script get the audio/video files. it seems to be that they have added it to an earlier stage . that means i could make it so it say `no videos found` earlier :) 

i guess they have random drm on some videos, i cant do anything with it.

**Comment by Geestarraw** [comment]
OK, I understand! Thanks for looking into it! 🙂
