### ISSUE TITLE
Again: Issue installing from the AUR

### ISSUE THREAD

**Issue by erikatl** [spaam/svtplay-dl#1422]
### svtplay-dl versions:
svtplay-dl 4.5-2
Run `svtplay-dl --version`
svtplay-dl 4.5
### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
OS: Manjaro Linux x86_64
Kernel: 5.14.7-2-MANJARO
Python 3.9.7
### What is the issue:
The new svtplay-dl 4.5-2 does not compile from the AUR:
```
:: Laddar ner PKGBUILD-filer...
 PKGBUILD-filer är aktuella
 inget nytt att granska
hämtar devel information...
==> Skapar paket: svtplay-dl 4.5-2 (fre  8 okt 2021 19:41:27)
==> Hämtar källor...
  -> Hittade svtplay-dl-4.5.tar.gz
==> Validerar source filer med sha256sums...
    svtplay-dl-4.5.tar.gz ... MISSLYCKADES
==> FEL:  En eller flera filer klarade inte valideringstestet.
fel: misslyckades med att hämta källor för 'svtplay-dl-4.5-2': 
fel: bygge misslyckat för paket: svtplay-dl-4.5-2
```

**Comment by GalaxyCurse** [comment]
Det beror på om det är en uppdatering från t.ex 4.5-1 till 4.5-2 så heter den filen som dras ner fortfarande 4.5.tar.gz och pamac (I mitt fall) kollar om det redan finns en fil innan den laddar ner, ser att 4.5.tar.z finns där och känner sig nöjd. Sen så försöker den validera, med sha256sum, det som den tror är 4.5-2 men faktist är 4.5-1 och misslyckas. Det enda jag har kommit på är att manuellt radera "/var/tmp/pamac-build-mitt_användarnamn/svtplay-dl/svtplay-dl-4.5.tar.gz" Då plockar pamac snällt ner den nya filen och valideringen går igenom.
Det är inte ett fel på svtplay-dl, utan på AUR scriptet som borde namnge 4.5-2 för 4.5-2.tar.gz istället för 4.5.tar.gz
