### ISSUE TITLE
tv4play no thumb

### ISSUE THREAD

**Issue by jula420** [spaam/svtplay-dl#1423]
### svtplay-dl versions:
4.5-1-gadcaa73

### Operating system and Python version:
5.11.0-37-generic #41~20.04.2-Ubuntu
Python 3.8.10

### What is the issue:

No thumb downloaded for tv4play, any url

Thanks,

Jan

**Comment by spaam** [comment]
Do you have an example of an URL that doesn't work? i tried it and it worked for me 🤔

**Comment by jula420** [comment]
https://www.tv4play.se/program/min-historiske-pojkv%C3%A4n/13331565
I have a few others that does/didn't work as well

**Comment by spaam** [comment]
this should be fixed in 4.6 :)
