### ISSUE TITLE
TV4 Error (ERROR: No videos found. Can't find json data)

### ISSUE THREAD

**Issue by superautomatic** [spaam/svtplay-dl#1425]
### svtplay-dl versions:

svtplay-dl 4.5

### Operating system and Python version:

MacOs 10.15.7
Python 2.7.16

### What is the issue:

TV4 unable to find videos (ERROR: No videos found. Can't find json data)

    svtplay-dl --verbose https://www.tv4play.se/program/lego-masters-sverige/del-8-final-s%C3%A4song-2/13326012

svtplay-dl --verbose https://www.tv4play.se/program/lego-masters-sverige/del-8-final-s%C3%A4song-2/13326012
DEBUG [1634566489.106406] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.5
DEBUG [1634566489.109051] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1634566489.1091058] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/lego-masters-sverige/del-8-final-s%C3%A4song-2/13326012'
DEBUG [1634566489.11802] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1634566489.375911] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/lego-masters-sverige/del-8-final-s%C3%A4song-2/13326012 HTTP/1.1" 200 None
ERROR [1634566489.410482] /usr/local/Cellar/svtplay-dl/4.5/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find json data

Username and password stored in svtplay-dl.yaml

**Comment by spaam** [comment]
i have pushed a fix for this and will be in the next release 4.6 that i will release later this evening :)
