### ISSUE TITLE
UrPlay tyx ha hittat på nåt nytt...

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1432]
UrPlay tyx ha hittat på nåt nytt...

Svtplay-dl.exe v.4.8, senaste Win10, alla (nåja, har inte testat ALLT...) andra URLer funkar ju.

svtplay-dl -S https://urplay.se/program/214756
ERROR: No videos found. Can't find json info

Men videon spelar på webbsidan.

**Comment by pythonuser3856** [comment]
I have the same issue.
The behavior by svtplay-dl seems to match what lead to the update in version 4.8 for SVTplay

ffmpeg 4.4
windows 8.1
python 3.8.10
svtplay-dl 4.8
link: https://urplay.se/program/219837-varlden-fran-forr-naken-aret-runt

py c:\svtplaydll\svtplay-dl_v48_2021-10-27py\__main__.py --verbose --subtitle https://urplay.se/program/219837-varlden-fran-forr-naken-aret-runt
Time at use
2021-10-30  9:43:50
DEBUG [1635579831.1907442] c:\svtplaydll\svtplay-dl_v48_2021-10-27py\svtplay_dl\utils\getmedia.py/get_media: version: 4.8
DEBUG [1635579831.192746] c:\svtplaydll\svtplay-dl_v48_2021-10-27py\svtplay_dl\service\__init__.py/__init__: service: urplay
DEBUG [1635579831.192746] c:\svtplaydll\svtplay-dl_v48_2021-10-27py\svtplay_dl\utils\http.py/request: HTTP getting 'https://urplay.se/program/219837-varlden-fran-forr-naken-aret-runt'
DEBUG [1635579831.19675] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1635579831.2938428] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://urplay.se:443 "GET/program/219837-varlden-fran-forr-naken-aret-runt HTTP/1.1" 200 33490
ERROR [1635579831.310861] c:\svtplaydll\svtplay-dl_v48_2021-10-27py\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find json info

**Comment by Minherre** [comment]
https://urplay.se/program/219837-varlden-fran-forr-naken-aret-runt

den där funkade för mig igår fredag morse, med svtplay-dl.exe v.4.8.

Så har de ändrat nåt på UrPlay är det sen igår förmiddag.

**Comment by Minherre** [comment]
https://urplay.se/program/219837-varlden-fran-forr-naken-aret-runt

den där funkade för mig igår fredag morse, med svtplay-dl.exe v.4.8.

Så har de ändrat nåt på UrPlay är det sen igår förmiddag.

**Comment by spaam** [comment]
har pushat en fix för detta. kommer med i en ny version senare idag. runt kvällen typ

**Comment by Minherre** [comment]
> har pushat en fix för detta. kommer med i en ny version senare idag. runt kvällen typ

TACK, nu fungerande det med "Snapshot 31-Oct-2021 00:44", men tråkigt nog valde den ju fortfarande lägsta upplösningen, så man var tvungen köra med:

svtplay-dl --list-quality https://urplay.se/program/214756
INFO: Quality:   METHOD:  Codec:   Resolution:  Language:            Role:
INFO: 3335       HLS      h264     640x360                           main
INFO: 3021       HLS      h264     1280x720                          main

Och sen:

svtplay-dl -S -P hls -q 3021 https://urplay.se/program/214756

för att få 720p versionen, men men...
