### ISSUE TITLE
--after-date doesn't seem to work

### ISSUE THREAD

**Issue by dasil9** [spaam/svtplay-dl#1434]
### svtplay-dl versions:
4.8 and 4.9

### Operating system and Python version: 
Windows 10

### What is the issue: 
--after-date doesn't seem to work. It downloads all episodes. The date of the two files in this case are 2021-08-26 but both get downloaded even though I set "--after-date 2021-10-07".
This is one example of the downloads I run:
svtplay-dl.exe --after-date 2021-10-07 -A -s --exclude syntolkat,teckensprakstolkat --output-format mkv https://www.svtplay.se/alfons-aberg
I've tried upgrading från 4.8 to 4.9 but the issue remains.

**Comment by spaam** [comment]
i have pushed a fix for it.  there will be a snapshot for it. in a few min on the website.  dont know when the next version going to be released. this is the only fix committed after 4.9. it might take a week or so :)
