### ISSUE TITLE
tv4play issue with VPN.

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1436]
Hi all, this is Not an error, nor anything to do with svtplay-dl, but thought to post it here for everyones reference.

For quite some time I've had issues with tv4play.se.

In order:

1. It works.
2. All of a sudden it stops working, giving me "Your location is hidden, using a VPN or an anonymizing service, stop doing that if you want to use our service.
This particularly happens after a reboot, using an old tab in the browser, but can just as well happen at any point in time.

The solution is simply to disconnect the VPN and reconnect, and the weird thing is that even if I get an IP in the same span it works after this. I have no idea what times out or what gives, or why I get this error.
In the browser I get "Hidden" and svtplay-dl crashes, with that old and known 500-something error instead of the 403 that should occur.

Like I said, just for info to keep should anyone else get the same.

/Dennis

**Comment by Minherre** [comment]
IF it shall be possible to use as a 'reference', then change the Subject to something useful!

**Comment by SweDennis** [comment]
Point well taken, and agreed. Title is changed, thanks for comment.
