### ISSUE TITLE
Unable to download from SVT Play or TV4 Play: ERROR: svtplay-dl crashed

### ISSUE THREAD

**Issue by PyttePeter** [spaam/svtplay-dl#1439]
### svtplay-dl versions:
svtplay-dl 4.9
svtplay-dl 4.9-3-g4f2fa55

Run `svtplay-dl --version`

### Operating system and Python version:
Win10 21H1 19043.1348 (2 different PC's, same OS version)
Windows Server 2012 6.3 build 9600
Python included with svtplay-dl, no Python installed separately

Name and version of the operating system and python version (run `python --version`)

### What is the issue:
Unable to download from SVT Play or TV4 Play: ERROR: svtplay-dl crashed
Can't seem to download anything

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.example.com

C:\Filesharing>svtplay-dl.exe --verbose https://www.svtplay.se/video/32893243/hackad/hackad-sasong-1-jag-har-inget-att-dolja?id=e6EyP4m
DEBUG [1636805388.7654898] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.9-3-g4f2fa55
DEBUG [1636805388.7654898] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1636805388.7654898] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/32893243/hackad/hackad-sasong-1-jag-har-inget-att-dolja?id=e6EyP4m'
DEBUG [1636805388.781095] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1636805388.9344] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/32893243/hackad/hackad-sasong-1-jag-har-inget-att-dolja?id=e6EyP4m HTTP/1.1" 200 34533
DEBUG [1636805388.981252] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/e6EyP4m'
DEBUG [1636805388.981252] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1636805389.1350434] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/e6EyP4m HTTP/1.1" 200 953
DEBUG [1636805389.1350434] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-9n.akamaized.net/d0/world/20211018/21d60e97-6007-442f-9404-bd54be28e2bd/hls-ts-avc.m3u8'
DEBUG [1636805389.1350434] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-9n.akamaized.net:443
DEBUG [1636805389.351255] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-9n.akamaized.net:443 "GET /d0/world/20211018/21d60e97-6007-442f-9404-bd54be28e2bd/hls-ts-avc.m3u8 HTTP/1.1" 200 768
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 98, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 113, in _get_video
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\hls.py", line 46, in hlsparse
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 865, in text
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\models.py", line 735, in apparent_encoding
AttributeError: module 'chardet' has no attribute 'detect'

**Comment by PyttePeter** [comment]
I tried a few combinations of parameters before trying without any at all.

**Comment by spaam** [comment]
i tried this on my windows 11 machine and had no issues at all.  it works both in cmd and powershell. 
i dont have access to a windows 10 machine.

**Comment by spaam** [comment]
i released 4.10. it might work better for you.
