### ISSUE TITLE
Option --subfolder in effect without being invoked

### ISSUE THREAD

**Issue by andersroh** [spaam/svtplay-dl#1440]
svtplay-dl 4.9
MacOS 10.15.7
Python 2.7.16

### What is the issue:

Since last update of svtplay-dl, all downloads end up in subfolders 'movies' or '_show name_', as if the option --subfolder had been invoked, even if it has not.

svtplay-dl -A -q 800 -Q 100 --output '/Volumes/Media/TV/Greta Gris/' 'https://www.svtplay.se/greta-gris'

Media files end up in '/Volumes/Media/TV/Greta Gris/greta.gris/' and '/Volumes/Media/TV/Greta Gris/movies/' 
(both folders are used because some episodes are named e.g. 's03e01' and some are named with an episode title)

**Comment by spaam** [comment]
i think you have a config that you forgot about that you have 🤔 
for me this is happening when i try the same thing: 
```
➜  lib git:(master) ✗ cd kalle
cd: no such file or directory: kalle
➜  lib git:(master) ✗ mkdir kalle
➜  lib git:(master) ✗ python3 -m svtplay_dl https://www.svtplay.se/greta-gris  -A -q 800 -Q 100 -o kalle/
INFO: Episode 1 of 36
INFO: Url: http://www.svtplay.se/video/25381467/greta-gris/greta-gris-sasong-7-morfars-leksaksflygplan
INFO: Outfile: greta.gris.morfars.leksaksflygplan-06ac4e4-svtplay.mp4
INFO: Selected to download dash, bitrate: 884 format: h264
[82/82][============================================================================================================================================================] ETA: 0:00:00
[82/82][============================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into greta.gris.morfars.leksaksflygplan-06ac4e4-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 2 of 36
INFO: Url: http://www.svtplay.se/video/25346343/greta-gris/greta-gris-sasong-7-grottorna
^C
➜  lib git:(master) ✗ cd kalle/
➜  kalle git:(master) ✗ ls
greta.gris.morfars.leksaksflygplan-06ac4e4-svtplay.mp4
```

**Comment by andersroh** [comment]
*embarrased*
I was going to write that I am 100% certain that I have not created a config file, but let's just say I will never think in terms of 100% sure again...

**Comment by spaam** [comment]
woho we found the issue. good job :)
