### ISSUE TITLE
TV4 Play is not supported anymore

### ISSUE THREAD

**Issue by Umeaboy** [spaam/svtplay-dl#1446]
### What is the issue: When trying to download the movie called Lyrro - ut & invandrarna I'm met with the message "ERROR: That site is not supported. Make a ticket or send a message".

[kristoffer@ip249-2-1 ~]$ svtplay-dl --verbose user=hiddenforprivacyreasons password=hiddenforprivacyreasons https://www.tv4play.se/program/lyrro-ut-invandrarna/avsnitt/12622657
DEBUG [1638655273.1532393] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: Unknown
DEBUG [1638655273.1574054] /usr/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: generic
DEBUG [1638655273.1575253] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://user=youremailhere@domain.com'
DEBUG [1638655273.1625736] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): tutanota.com:80
DEBUG [1638655273.228623] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: http://tutanota.com:80 "GET / HTTP/1.1" 302 0
DEBUG [1638655273.2383149] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): tutanota.com:443
DEBUG [1638655273.4662044] /usr/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://tutanota.com:443 "GET / HTTP/1.1" 200 85785
ERROR [1638655273.5343585] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: That site is not supported. Make a ticket or send a message

I built SVT Play DL by using the latest code available.

**Comment by spaam** [comment]
it works fine here.  it seems like you typing some arguments wrong.  to use username and password. you need to type `--username`  or `-u`   and  `--password` or `-p` .  you seems to forgot adding those two dashes and shorted the `username` to `user` .
