### ISSUE TITLE
SVTPlay -A fetches too much

### ISSUE THREAD

**Issue by JohnnyJorgensen** [spaam/svtplay-dl#1449]
SVTPlay version 4.9

svtplay-dl.exe  -S -A -f https://www.svtplay.se/maste-gitt-serien

fetches not only the 8 episodes in the series, but everything under the "Upptäck mer" section. 23 files in total for me.

svtplay-dl.exe  -S -A -f -o C:\Users\jojo\AppData\Roaming\SVTPlayGUI\ef22c377-3e6d-4a74-9fe6-89639298b61f https://www.svtplay.se/maste-gitt-serien
INFO: Episode 1 of 23
INFO: Url: http://www.svtplay.se/video/27974835/maste-gitt-serien/maste-gitt-serien-sasong-1-karma
INFO: Outfile: maste.gitt.serien.s01e01.1..karma-b03a3e7-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e01.1..karma-b03a3e7-svtplay.mp4
INFO: Selected to download dash, bitrate: 5448 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e01.1..karma-b03a3e7-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 2 of 23
INFO: Url: http://www.svtplay.se/video/27974783/maste-gitt-serien/maste-gitt-serien-sasong-1-goteborg
INFO: Outfile: maste.gitt.serien.s01e02.2..goteborg-ac51dac-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e02.2..goteborg-ac51dac-svtplay.mp4
INFO: Selected to download dash, bitrate: 5943 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e02.2..goteborg-ac51dac-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 3 of 23
INFO: Url: http://www.svtplay.se/video/27974819/maste-gitt-serien/maste-gitt-serien-sasong-1-arvet
INFO: Outfile: maste.gitt.serien.s01e03.3..arvet-c948440-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e03.3..arvet-c948440-svtplay.mp4
INFO: Selected to download dash, bitrate: 5573 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e03.3..arvet-c948440-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 4 of 23
INFO: Url: http://www.svtplay.se/video/27974779/maste-gitt-serien/maste-gitt-serien-sasong-1-clowner-utan-granser
INFO: Outfile: maste.gitt.serien.s01e04.4..clowner.utan.granser-0e1a3f5-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e04.4..clowner.utan.granser-0e1a3f5-svtplay.mp4
INFO: Selected to download dash, bitrate: 5749 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e04.4..clowner.utan.granser-0e1a3f5-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 5 of 23
INFO: Url: http://www.svtplay.se/video/27974815/maste-gitt-serien/maste-gitt-serien-sasong-1-ambulanzen
INFO: Outfile: maste.gitt.serien.s01e05.5..ambulanzen-585cfad-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e05.5..ambulanzen-585cfad-svtplay.mp4
INFO: Selected to download dash, bitrate: 5713 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e05.5..ambulanzen-585cfad-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 6 of 23
INFO: Url: http://www.svtplay.se/video/27974831/maste-gitt-serien/maste-gitt-serien-sasong-1-fatmas-dejt
INFO: Outfile: maste.gitt.serien.s01e06.6..fatmas.dejt-e1d2ef4-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e06.6..fatmas.dejt-e1d2ef4-svtplay.mp4
INFO: Selected to download dash, bitrate: 5618 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e06.6..fatmas.dejt-e1d2ef4-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 7 of 23
INFO: Url: http://www.svtplay.se/video/27974823/maste-gitt-serien/maste-gitt-serien-sasong-1-ekotomater
INFO: Outfile: maste.gitt.serien.s01e07.7..ekotomater-5c0cd4f-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e07.7..ekotomater-5c0cd4f-svtplay.mp4
INFO: Selected to download dash, bitrate: 5856 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e07.7..ekotomater-5c0cd4f-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 8 of 23
INFO: Url: http://www.svtplay.se/video/27974791/maste-gitt-serien/maste-gitt-serien-sasong-1-sverigevanner
INFO: Outfile: maste.gitt.serien.s01e08.8..sverigevanner-e869a32-svtplay.srt
INFO: Outfile: maste.gitt.serien.s01e08.8..sverigevanner-e869a32-svtplay.mp4
INFO: Selected to download dash, bitrate: 5450 format: h264-51
INFO: Merge audio and video into maste.gitt.serien.s01e08.8..sverigevanner-e869a32-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 9 of 23
INFO: Url: http://www.svtplay.se/video/23522386/becker-kungen-av-tingsryd
INFO: Outfile: becker-kungen.av.tingsryd-acac87f-svtplay.srt
INFO: Outfile: becker-kungen.av.tingsryd-acac87f-svtplay.mp4
INFO: Selected to download dash, bitrate: 5918 format: h264-51
INFO: Merge audio and video into becker-kungen.av.tingsryd-acac87f-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 10 of 23
INFO: Url: http://www.svtplay.se/kniven-i-hjartat
ERROR: No videos found. This mode is not supported anymore. Need the url with the video.
INFO: Episode 11 of 23
INFO: Url: http://www.svtplay.se/video/30804302/snalla-kriminella
INFO: Outfile: snalla.kriminella-f772d6e-svtplay.srt
INFO: Outfile: snalla.kriminella-f772d6e-svtplay.mp4
INFO: Selected to download dash, bitrate: 5816 format: h264-51
INFO: Merge audio and video into snalla.kriminella-f772d6e-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 12 of 23
INFO: Url: http://www.svtplay.se/video/16393154/en-man-som-heter-ove
INFO: Outfile: en.man.som.heter.ove-a645ee8-svtplay.srt
INFO: Outfile: en.man.som.heter.ove-a645ee8-svtplay.mp4
INFO: Selected to download dash, bitrate: 5634 format: h264-51
INFO: Merge audio and video into en.man.som.heter.ove-a645ee8-svtplay.mp4
INFO: Merging done, removing old files.
INFO: Episode 13 of 23
INFO: Url: http://www.svtplay.se/video/32951622/vader-vi-minns
INFO: Outfile: vader.vi.minns-160807b-svtplay.srt
INFO: Outfile: vader.vi.minns-160807b-svtplay.mp4
INFO: Selected to download dash, bitrate: 5462 format: h264

.... And so on. It's still downloading...!!!

**Comment by spaam** [comment]
this is fixed in 4.10  :)
