### ISSUE TITLE
svtplay.se on MacOS - No videos found. Can't find video id

### ISSUE THREAD

**Issue by the-mountain-man** [spaam/svtplay-dl#1451]
I have had this problem before but it was possible to solve by adding " or ' around the url, however it is not helping anymore. Haven't used svtplay-dl since upgrading OS. No fancy stuff, just a basic svtplay-dl https://www.svtplay.se/video/27942147/flygkaparen-som-forsvann

### What is the issue: ERROR: No videos found. Can't find video id

Trying to download https://www.svtplay.se/video/27942147/flygkaparen-som-forsvann

@-MacBook-Pro ~ % svtplay-dl --verbose https://www.svtplay.se/video/27942147/flygkaparen-som-forsvann
DEBUG [1642181151.597711] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.1
DEBUG [1642181151.598638] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1642181151.59868] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/27942147/flygkaparen-som-forsvann'
DEBUG [1642181151.6175659] /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1642181151.8284109] /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/27942147/flygkaparen-som-forsvann HTTP/1.1" 200 30510
ERROR [1642181151.835757] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find video id

**Comment by spaam** [comment]
@the-mountain-man it seems like you are using an old version 4.1 of the script.  4.8 got som fixes for this and 4.10 is the newest version. try updating to the newest version and see if it works better :)

**Comment by the-mountain-man** [comment]
Hey, thanks, I was not really paying enough attention to the versions (trying very hard to solve a problem that didn't exist)... Having 4.1 and 4.10 being the newest - my bad. When running 4.10 everything works just fine. Always good to have an extra pair of eyes at the numbers. Once again; thanks.

**Comment by spaam** [comment]
glad that the new version solved the problem for you. have a nice weekend :)
