### ISSUE TITLE
Pop up Error message after installing v4.10

### ISSUE THREAD

**Issue by GreveTess** [spaam/svtplay-dl#1456]
svtplay-dl version v4.10 does not seem to want to start on my computer at all v4.9 works well (besides the known bugs).

I get error message that api-ms-win-core-path-l1-1-0.dll is missing after upgrading.
Reinstalling does not help.

I am still using Win7. 
Grateful for any assistance, I would love to upgrade and have the latest bug fixes

![image](https://user-images.githubusercontent.com/86667574/152949880-349a2d8b-21f3-49c2-942f-f8fb59a84803.png)

**Comment by spaam** [comment]
i have some bad news for you. i switched to use python 3.9 to build the .exe for windows. they dropped windows 7 support with that release. 

one option for you to deal with this in the future will have to be some work for you. you need to install python 3.8 on your computer. then you have to install the dependencies via pip  ` cryptography pyyaml pysocks requests` .  then you can download the binary  for example this for 4.10 https://svtplay-dl.se/download/4.10/svtplay-dl  .  then you should be able to use svtplay-dl again via `python.exe svtplay-dl  URL`  🤔

**Comment by GreveTess** [comment]
You are killing me here, :-) Weird that I'm the only one still stuck on Windows 7. I would have assumed more people would have this issue. 
I'll try to figure it out but I have no idea how, at least 4.9 works (besides -A for tv4play which is why I wanted it)
Updating Windows is on the agenda but it's so annoying and time consuming so we'll see when that happens.

**Comment by ing181** [comment]
Hey! maybe this one works. Latest svtplay-dl source code compiled with python 3.8. On a Windows 10 computer.
https://bin.ceicer.com/tmp/svtplaydl-4.10-1-gf7b3d1b.zip

**Comment by GreveTess** [comment]
You are a savior it seems to work. Finally I can grab full seasons in TV4.

**Comment by candrapersada** [comment]
https://bin.ceicer.com/tmp/svtplaydl-4.10-1-gf7b3d1b.zip
Not Found
The requested URL was not found on this server.

Apache/2.4.52 (FreeBSD) mpm-itk/2.4.7-04 PHP/7.4.27 Server at bin.ceicer.com Port 80
