### ISSUE TITLE
Latest snapshot directory does not contain .zip-files

### ISSUE THREAD

**Issue by Gurkan911** [spaam/svtplay-dl#1461]
Latest snapshot directory does not contain .zip-files, only a single "svtplay-dl" file.

No zipfiles: 
https://svtplay-dl.se/download/snapshots/20220221_125723/

Zip-files: 
https://svtplay-dl.se/download/snapshots/20211219_124247/

If possible I would appreciate the zip-files.

Thanks in advance.

**Comment by spaam** [comment]
yeah because the thing creating the .exe files changed their stuff how to handle version numbers so it crashed the build script. i looked into it and later gave up on it. getting slightly annoying  this whole .exe stuff.

**Comment by spaam** [comment]
I just need to hardcode what version to use of the tool that create the exe files. Its like 2 min job. 😊

**Comment by spaam** [comment]
this was fixed yesterday :)

**Comment by Gurkan911** [comment]
Thank you!
