### ISSUE TITLE
Ny typ av Undertext på SVTPlay

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1462]
Hej!

Vad är detta för slags Subtitle som medföljer:

https://www.svtplay.se/video/34597232/den-dodsdomda-polarexpeditionen

Innehåller typ:

=========

STYLE
::cue {
color: #DFDFDF;
}
::cue(.huvudpratare) {
color: #00FFFF;
}
::cue(.ljud) {
color: #FF00FF;
}
::cue(.ljudskylt) {
color: #FF00FF;
}
::cue(.relivemark) {
color: #FF0000;
}
::cue(.sang) {
color: #00FF00;
}

ac7ff7a0ad304689abbc836bf0248323
1
00:00:06,360 --> 00:00:10,080
1845 gav sig
en brittisk expedition ut–

901ad1de734b4b048110baa4068b2bf1
2
00:00:10,240 --> 00:00:15,040
–för att söka ett av forsknings-
resornas mest eftertraktade mål:

1b8b567723844b84910d7c6a149c9718
3
00:00:15,200 --> 00:00:18,120
Den gäckande Nordvästpassagen.

efa2d811e1814b4db20ca7d07c4792b0

=========

Sparas ju som .SRT av Svtplay-Dl men är då inte användbar, dvs visas inte alls i min Hårdvaru Mediaspelare, men syns i t ex VLC.

**Comment by spaam** [comment]
spännande.  låter som något jag borde fixa :)

**Comment by Minherre** [comment]
> spännande. låter som något jag borde fixa :)

Så du vet alltså inte heller vad det där är för typ av Sub ?!

Men den Sub-typen måste väl åtminstone vara känd av de som gör VLC, för där fungerar ju sub'en.

Och Svt har väl knappast hittat på nåt alldeles eget.

**Comment by spaam** [comment]
jag har aldrig sett det tidigare. varför jag har inte sett det är väl på grund av att jag tar aldrig hem subs :)

VLC har många fler utvecklare och användare så de vore lite konstigt om dom inte visste :)

**Comment by Minherre** [comment]
Fick en kommentar
( https://github.com/SubtitleEdit/subtitleedit/issues/5855 )
om att det är en VTT:

"I have no idea what those hash things ("ac7ff7a0ad304689abbc836bf0248323") are, but overall it's a WebVTT file, so if you change the extension to vtt (i.e. filename.vtt instead of filename.txt), SE will be able to open it.!

Men Svt tycks ju ha lagt till nåt ?!

**Comment by Minherre** [comment]
> precis det är som en webvtt som vi gör om till en .srt fil. jag får fixa lite kod för att göra det :) men det får bli ikväll iom jag jobbar just nu :)

Hmm, nu har det gått x antal dagar, hur har det gått, för nu dyker nya Subs upp som är oanvändbara...

T ex så funkar inte

https://www.svtplay.se/video/34677071/vetenskapens-varld/vetenskapens-varld-sasong-35-naturens-katastrofer

som ju ser likadan ut som den Sub som den här tråden startade med!

**Comment by Minherre** [comment]
Tack för 4.11, hämtade de felande Subsen från inlägget ovan, och det ser ut att funka!

**Comment by spaam** [comment]
woho :D tack för att du testade att de funkade och för bugg rapporten <3
