### ISSUE TITLE
All-Episodes does not work on TV4Play anymore!

### ISSUE THREAD

**Issue by ecsjjgg** [spaam/svtplay-dl#1468]
With the latest svtplay-dl.exe

I can't list all episodes of a show from tv4play.se, and ofcourse I can't download the whole show either...

I can now only download the episodes one by one...

This started to happen this Wednesday-Thursday, they (TV4) must have made some changes then...

**Comment by pythonuser3856** [comment]
I can confirm.

With a setup of:
svtplay-dl v4.11, python code
MS WIndows 8.1
Python 3.8.10
ffmpeg 4.4-78

and using the command:
svtplay-dl --get-only-episode-url -A --include-clips https://www.tv4play.se/program/macgyver/del-4-säsong-3/13729383

I get:
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_v411_2022-03-29py\__main__.py", line 15, in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_v411_2022-03-29py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_v411_2022-03-29py\svtplay_dl\utils\getmedia.py", line 61, in get_media
    get_all_episodes(stream, url, options)
  File "c:\svtplaydll\svtplay-dl_v411_2022-03-29py\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
    episodes = stream.find_all_episodes(stream.config)
  File "c:\svtplaydll\svtplay-dl_v411_2022-03-29py\svtplay_dl\service\tv4play.py", line 108, in find_all_episodes
    for panel in program["panels"]:
KeyError: 'panels'

The same command worked a couple of days ago.

**Comment by spaam** [comment]
i think i have found a way to fix it but need to find some tv series with more then 2 seasons to verify if its correct or not.

**Comment by Bub0** [comment]
> i think i have found a way to fix it but need to find some tv series with more then 2 seasons to verify if its correct or not.

Checked around and this has three. 🙂
https://www.tv4play.se/program/wonderland

**Comment by ecsjjgg** [comment]
> > i think i have found a way to fix it but need to find some tv series with more then 2 seasons to verify if its correct or not.
> 
> @spaam Checked around and this has three. 🙂 https://www.tv4play.se/program/wonderland

No, it doesn't on tv4play.se, only 2 seasons, but half of S01 + half of S02 is in reality S02, and the second half of S02 is S03...

But @spaam, you can check out this series instead, https://www.tv4play.se/program/playmakers as it has 5 seasons, and they are all available...

**Comment by Bub0** [comment]
> > > i think i have found a way to fix it but need to find some tv series with more then 2 seasons to verify if its correct or not.
> > 
> > @spaam Checked around and this has three. 🙂 https://www.tv4play.se/program/wonderland
> 
> No, it doesn't on tv4play.se, only 2 seasons, but half of S01 + half of S02 is in reality S02, and the second half of S02 is S03...
> 
> But @spaam, you can check out this series instead, https://www.tv4play.se/program/playmakers as it has 5 seasons, and they are all available (5*10 episodes), and they are fairly short ~25 minutes each...

Ha! Strange. Website said three at the time I looked at it!🧐
Thanks...
But this should be a better one. https://www.tv4play.se/program/anna-pihl
If they isn't messing with me again! 😝

**Comment by spiteproject** [comment]
There are 7 seasons of the series Solsidan: https://www.tv4play.se/program/solsidan  (season 6 is DRM protected)

**Comment by JohnnyJorgensen** [comment]
I tested with this one - 3 seasons - doesn't work:
https://www.tv4play.se/program/bedr%C3%A4geriet

**Comment by KmanSwe** [comment]
House has 8 proper seasons on TV4 plus..

**Comment by spaam** [comment]
4.12 got a fix for this :) thanks for the links and the report <3
