### ISSUE TITLE
Upgrading fails: "unknown compression for member  'control.tar.zst"

### ISSUE THREAD

**Issue by leifho2** [spaam/svtplay-dl#1471]
### svtplay-dl versions:

$ svtplay-dl --version
svtplay-dl 4.10+7.g36a087a

### Operating system and Python version:

$ cat /etc/debian_version 
11.3
$ python3 --version
Python 3.9.2
$ cat /etc/apt/sources.list.d/svtplay-dl.list
deb https://apt.svtplay-dl.se/ svtplay-dl release

Same problem also on a Raspberry Pi running Debian Buster (debian_version 10.12).

### What is the issue:

$ sudo apt update
$ LANG=C sudo apt upgrade
The following packages will be upgraded:
  svtplay-dl
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
dpkg-deb: error: archive '/var/cache/apt/archives/svtplay-dl_4.12_all.deb' uses unknown compression for member
 'control.tar.zst', giving up
dpkg: error processing archive /var/cache/apt/archives/svtplay-dl_4.12_all.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2

Installing the packages zstd or python3-zstd didn't help.
Possibly a Debian issue, but the svtplay-dl package is not from Debian.

---
svtplay-dl is great! I've been using it for years.
/Leif

**Comment by spaam** [comment]
bah :D  i upgraded my ubuntu server where i built my package to 22.04. i guess it broke it  :D

**Comment by spaam** [comment]
will rebuild the package and release an update shortly :)

**Comment by leifho2** [comment]
Great! I can probably be here and try again then. /Leif

⁣Skickat från BlueMail ​

Den 14 maj 2022 13:04, kI 13:04, Johan Andersson ***@***.***> skrev:

**Comment by spaam** [comment]
try update now and it should work better 🤔

**Comment by leifho2** [comment]
Perfect! Now I have svtplay-dl version 4.12. Thanks a lot! :-)
