### ISSUE TITLE
add link download svtplay-dl for Windows 7

### ISSUE THREAD

**Issue by candrapersada** [spaam/svtplay-dl#1476]
### svtplay-dl versions:

svtplay-dl v4.12

### Operating system and Python version:

Windows 7

### What is the issue:

add link download svtplay-dl for Windows 7 without get error message that api-ms-win-core-path-l1-1-0.dll

**Comment by spaam** [comment]
windows 7 is not supported by python 3.9 that i use to build the .exe.  windows 7 is not even supported by microsoft...  should consider updating to a support version of the OS...

i switched to 3.8 to build the .exe. it will work for some time.
