### ISSUE TITLE
Download produces huge files

### ISSUE THREAD

**Issue by santajrr** [spaam/svtplay-dl#1477]
### svtplay-dl versions:

svtplay-dl 4.12

### Operating system and Python version:

Ubuntu 18.04.6 LTS
Python 3.6.9

### What is the issue:

I have been trying to download a couple of episodes of _Frank og Kastaniegården_ using commands like these two:

svtplay-dl -S --no-merge https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-roerhoest-og-filtsaaler_302958
or
svtplay-dl -S --no-merge https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-menage-a-trois_304070

No matter what or when I try I get some huge files. The audio stream for the first url ends up being a little over 6.5 GB and the video file keeps getting bigger and bigger. I have usually stopped when it reachead around 50 GB. Each episode of _Frank og Kastaniegården_ is usually around 28-30 minutes long so files with those sizes are very unsual.

I have tried downloading the first url with --verbose. The result can be found in svtplay-dl-debug.txt. I stopped the download when it reached passed 22 GB for the video stream.

The last time i downloaded an episode (I don't remember the version of svtplay-dl I used) the combined file (video, audio and subtitles) ended up being a little over 1 GB in size.

I have also tried the same downloads using svtplay-dl 4.11 and 4.10, but the results are the same.

[svtplay-dl-debug.txt](https://github.com/spaam/svtplay-dl/files/8840334/svtplay-dl-debug.txt)

**Comment by spaam** [comment]
interesting files.  its a different way how we normally download HLS files. "normally" the files in the m3u8 playlist contain many files that are few seconds each.. but this seems to be one huge file split into different byte ranges. we dont have support for that right now 🤔

**Comment by santajrr** [comment]
OK, I hope you will get support later.

**Comment by spaam** [comment]
i have something that is working. need to test some things and hopefully it will be included in the next version that i going to release tonight :)

**Comment by spaam** [comment]
this is fixed in 4.13 :)

**Comment by santajrr** [comment]
Thank you very much for the quick fix.
