### ISSUE TITLE
Warning downloading subtitles from dr.dk

### ISSUE THREAD

**Issue by santajrr** [spaam/svtplay-dl#1478]
### svtplay-dl versions:

svtplay-dl 4.13

### Operating system and Python version:

Ubuntu 18.04.6 LTS
Python 3.6.9

### What is the issue:

When I download an episode of _Frank og Kastanjegården_ using this command:
svtplay-dl -S --no-merge https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-roerhoest-og-filtsaaler_302958
I get this message:
WARNING: Can't download subtitle file

I have attached a file with debug.

[debug_subtitles.txt](https://github.com/spaam/svtplay-dl/files/8842387/debug_subtitles.txt)

**Comment by spaam** [comment]
its fixed in master. the issue i used the wrong playlist  to get the correct file .)
