### ISSUE TITLE
Subtitles out of sync with audio

### ISSUE THREAD

**Issue by santajrr** [spaam/svtplay-dl#1479]
### svtplay-dl versions:

svtplay-dl 4.13-2-g7cdb7f2

### Operating system and Python version:

Ubuntu 18.04.6 LTS
Python 3.6.9

### What is the issue:

When I download an episode of _Frank og Kastanjegården_ using this command:
`svtplay-dl -S --no-merge https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-roerhoest-og-filtsaaler_302958
`and then merge the files to mkv using ffmpeg:
`ffmpeg -i frank.kastaniegaarden.sson.2022.rrhst.og.filtsaler.drtv-dr.ts -i frank.kastaniegaarden.sson.2022.rrhst.og.filtsaler.drtv-dr.srt -i frank.kastaniegaarden.sson.2022.rrhst.og.filtsaler.drtv-dr.audio.ts -metadata:s:a:0 language=da -metadata:s:a:0 language=da -metadata:s:s:0 language=da -c copy Bonderøven.S25E03.mkv`
the subtitles are out of sync with the audio.

Is that an issue with svtplay-dl or the data downloaded from dr.dk?

I have tried downloading both [https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-roerhoest-og-filtsaaler_302958](url) and [https://www.dr.dk/drtv/se/frank-and-kastaniegaarden_-menage-a-trois_304070](url) and if I play my merged mkv files and delay the subtitles by 9.5 seconds, the subtitles match the audio.

[debug_subtitles.txt](https://github.com/spaam/svtplay-dl/files/8843893/debug_subtitles.txt)

**Comment by spaam** [comment]
🤔  are they out of sync if you have the .srt file external and only audio and video in the same file and use like vlc to see if its correct?

**Comment by spaam** [comment]
i got something that works. will do some more tests tomorrow and hopefully release something new later this weekend with ze fix :)

**Comment by santajrr** [comment]
Sounds good :-)

**Comment by santajrr** [comment]
How is the fix for the subtitle sync issue coming along?

**Comment by santajrr** [comment]
Is there a solution in sight for the subtitle sync issue?

**Comment by santajrr** [comment]
I'm still having problems with the subtitles being out of sync when downloading from dr.dk. It seems to always be 9.5 seconds that a have to delay the subtitles with in order to have subtitles match what' being said.

Originally I discovered the problem with episodes of [Frank og Kastanjegården](https://www.dr.dk/drtv/serie/frank-and-kastaniegaarden_6954) but recently I have also had the problem with several episodes of [Historien om Danmark](https://www.dr.dk/drtv/serie/historien-om-danmark_145311).

Any solution in sight?

**Comment by santajrr** [comment]
This is one of the episodes I was having issues with:
https://www.dr.dk/drtv/se/historien-om-danmark_-reformation-og-renaessance_145570

My ffmpeg version is:
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers

I have just tried with svtplay-dl v. 4.18 and with 4.18 there doesn't seem to be a problem.

I will create a new ticket if the problem reappears.
