### ISSUE TITLE
kalle.json stored with downloads from TV4play

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1482]
It started to appear when I switched to use the latest snapshot version
svtplay-dl 4.13-6-g8f9552e
I haven't noticed the effect with downloads from SVTplay

**Comment by pythonuser3856** [comment]
I guess it will be handled with the next full release

**Comment by spaam** [comment]
thanks for the issue :D  i fixed it and pushed it :D
