### ISSUE TITLE
Progress report does not show when stdout is a file or a pipe.

### ISSUE THREAD

**Issue by mhogomchungu** [spaam/svtplay-dl#1484]
### svtplay-dl versions:

4.13

### Operating system and Python version:

Operating System: Linux
Python version: 3.6.5

### What is the issue:

svtplay-dl  https://www.svtplay.se/klipp/35661937/inflation-fa-experternas-tips?id=8WYp76n 1>out 2>&1

Run the above command and then start opening the "out" file and observe that no progress line is added to the file and when the download completes, all progress lines show up at once.

Repeat the above command with "--verbose" option and observe the "out" file is getting updates with progress report together with DEBUG messages.

**Comment by spaam** [comment]
This is an issue with python. You need to use  "PYTHONUNBUFFERED=true svtplay-dl url" to make it work.

**Comment by mhogomchungu** [comment]
Why not add the variable automatically? 

GUI Front ends see the problem they work around the issue by showing non-deterministic progress bar.

**Comment by spaam** [comment]
Because this is not an issue to svtplay-dl. Its an issue to the language svtplay-dl using.

**Comment by mhogomchungu** [comment]
Fair enough, thanks.
