### ISSUE TITLE
Pluto TV - All episodes get the same name when using -A

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1489]
### svtplay-dl versions:

svtplay-dl 4.13-6-g8f9552e

### Operating system and Python version:

Windows 10

### What is the issue:

I haven't tested Pluto TV before but when i try to use -A it won't work because every episodes get the same name as you can see here
```
svtplay-dl.exe -A https://pluto.tv/en/on-demand/series/andromeda-sv/details/season/1
INFO: Episode 1 of 110
INFO: Url: https://pluto.tv/en/on-demand/series/andromeda-sv/1/episode/under-natten-2000-1-1
INFO: Outfile: andromeda-plutotv.ts
WARNING: File (andromeda-plutotv.ts) already exists. Use --force to overwrite
INFO: Episode 2 of 110
INFO: Url: https://pluto.tv/en/on-demand/series/andromeda-sv/1/episode/en-bekraftande-flamma-2000-1-2
INFO: Outfile: andromeda-plutotv.ts
WARNING: File (andromeda-plutotv.ts) already exists. Use --force to overwrite
INFO: Episode 3 of 110
INFO: Url: https://pluto.tv/en/on-demand/series/andromeda-sv/1/episode/att-forlora-den-avgorande-blixten-2000-1-3
INFO: Outfile: andromeda-plutotv.ts
WARNING: File (andromeda-plutotv.ts) already exists. Use --force to overwrite
INFO: Episode 4 of 110
INFO: Url: https://pluto.tv/en/on-demand/series/andromeda-sv/1/episode/d-minus-noll-2000-1-4
INFO: Outfile: andromeda-plutotv.ts
WARNING: File (andromeda-plutotv.ts) already exists. Use --force to overwrite
```

**Comment by spaam** [comment]
bah. seems like they have several different ways to store the season and episode info

**Comment by Sopor** [comment]
No, it didn't worked 😥

**Comment by Sopor** [comment]
With `svtplay-dl` one episode take less than a minute to download. With other `*-dl.exe`  it will take several minute to download the same episode. I don't know why, though ...

**Comment by spaam** [comment]
interesting 🤔 ( in the future it will be even faster).. anyway does this other tool have ads in the output file?  svtplay-dl filter out those files before downloading all the files.

**Comment by Sopor** [comment]
No ads in the output file.

**Comment by spaam** [comment]
did you test latest snapshot?

**Comment by pythonuser3856** [comment]
I have tested the snap-shot '20220703_112542' / 'svtplay-dl 4.13-10-g48f376a' and for me it works fine with switch '-A'.
I used the URL 'https://pluto.tv/en/on-demand/series/mtv-unplugged-da-ptv1/season/1/episode/elton-john-parte-1-1989-1-5-ptv3' and the files stored were named '...s01eXX...'

**Comment by spaam** [comment]
do you want to share an example of a video with this issue? i dislike their web site and i dont want to use it more  :)

**Comment by pythonuser3856** [comment]
My mistake, they do become named with four digits, sorry

**Comment by spaam** [comment]
ahh it make sense. because i used some modulus stuff before to get the season and episode. it worked on some shows like lyxfällen :)
```
self.output["season"] = int(three_or_more_digit_string) // 100
self.output["episode"] = int(three_or_more_digit_string) % 100
```

**Comment by Sopor** [comment]
Wasn't the issue already closed?
