### ISSUE TITLE
Random success with a link at Pluto.tv

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1492]
Versions used:

snap-shot 20220703_112542  / '--version' print-out: svtplay-dl 4.13-10-g48f376a
Python 3.8.10
Windows 8.1
FFmpeg 5.0.1

When I attempt to get media with the link
https://pluto.tv/en/on-demand/series/south-park-sv/season/8/episode/skogsdjurens-jul-2003-8-814
I get random results which are either
1) ERROR: No videos found.      , or
2) a successful download
At the dl-attempts I'm using a single parameter the http-link and no config-file

If I run the dl-command a number of times I get the following sequential set of fairly random outcomes (20 attempts):
1 success
2 error
3 error
4 error
5 error
6 success
7 success
8 success
9 error
10 success
11 error
12 success
13 error
14 error
15 error
16 error
17 success
18 error
19 success
20 error

The attempts were made with an approx 5 seconds interval
The dl-command was hanging a bit longer in the success cases
I do not notice any network issues using the same command with links towards svtplay.se or tv4play.se a couple of minutes after the test, i.e. I have not identified any network issue on my side

**Comment by pythonuser3856** [comment]
Hmm, does that explain the randomness ?

To catch unexpected outcomes more reliably:
I'm using a script-wrapper to batch-run svtplay-dl. With this use an output 'errorlevel' from svtplay-dl would help me to catch any event of mishaps regardless reason (such as an ERROR, 'file exists', etc).
Is adding an an output result from svtplay-dl doable ?
For me it would help a lot !

**Comment by pythonuser3856** [comment]
1) At viewing the list of episodes of a season using my browser there are sometimes episodes listed twice, I have however not checked if only one of them is functional

2) There is for sure a visual feedback to the user of svtplay-dl and it's possible to let a script capture the output and parse it for a string indicating a not wanted/expected outcome.
That would, however, with a use of MS Windows and no 'tee' or 'tail' available for use, get me a silent screen and keep me unaware of what's happening until the svtplay-dl execution is concluded.
Based on that,
what I'm asking for is that the program returns an integer value back to the operating system at stop of execution; a value zero is a normal exit while other (positive integer) values may be assigned for example based on severity of the error.

**Comment by spaam** [comment]
i can fix the issue with 404 thing but then we have another issue related to #1489 `south.park.s08e814-plutotv.ts` .   ` "number": 814, "season": 8,`  .  im getting bit fed up with this shitty bad site. im not going to fix that.  more thinking about removing it instead of having to add hacks to fix their shitty stuff .

**Comment by pythonuser3856** [comment]
What would be good to strive for, regardless any site controversy, is a consistent behavior at a use of svtplay-dl.
If that is cumbersome to achieve with pluto.tv, then I see your point.

Should I move my question about a use of an exit code a là Unix to a separate issue ?
For reference, in a bash script the exit code is used as the environment variable $? while it's referred to as errorlevel in a Windows .BAT-file
