### ISSUE TITLE
[ Request ]  Add use of sys.exit() to cover more run-time issues

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1493]
svtplay-dl v4.13

svtplay-dl already supports a number error cases where svtplay-dl returns an exit code (errorlevel in MS Windows)
- in case a parameter errors as well as for an incorrect use of logic, svtplay-dl stop with an exit code 2
- at networking issues from which svtplay-dl is unable to continue after some retrying, svtplay-dl stop with an exit code 1
However, at an attempt to over-write a media while not using the switch '-f' or '--force' svtplay-dl today returns an error message but an exit code 0 indicating success despite a failed operation.

What the user intends to achieve may vary:
- even though there already is a file with a matching file name, the intent could be to get it updated/replaced.
- to always apply the switch '-f' is not a good idea since it would cause download of everything even though files are already there.
Proposal:
Let svtplay-dl return an exit code different from 0 in this case, for example 1 as for other run-time errors.
Doing so enables a script to capture the event and it may then be tailored to suit the needs of the specific user,
for example a) notify the user about the event, and b) download a duplicate to a different directory.

**Comment by spaam** [comment]
why overwrite is not returning 1 or something else, is called ` -A, --all-episodes`.  it was designed as if it can find an episode people already have, it will not overwrite it and skip to the next file in the list of episodes and download that. changing that so it will return 1 is a bit meh and i dont really want to change that without a really good reason. i guess it will break peoples scripts that they have been using for a long time.

back in the day when video sites used flash and rtmp , we could easily resume a download  ( `-r` argument).  i have some ideas for this updated thing. it somewhat related to the threading idea i have.  download each chuck separate and store them at a temporarily place. then when everything is done put it together. downside we will use more disk space but plus side we could resume an download and it could be faster too. but i just need to get tummen ur röven and do it and stop pushing it forward all the time.

**Comment by pythonuser3856** [comment]
Thinking about it I found a workaround.
I'll let a script compare time stamp of files with the approximate time of use of svtplay-dl.
With no use of '-f' a script will be able to separate old/existing files from freshly downloaded ones.
Thank's for your attention.
