### ISSUE TITLE
Version numbering, perhaps just cosmetics

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1507]
### svtplay-dl versions:

```
dennis@gentoo ~ $ svtplay-dl --version
svtplay-dl 0+unknown
dennis@gentoo ~ $ 
```

### Operating system and Python version:

```
Linux gentoo 5.19.17-gentoo #1 SMP Mon Oct 24 15:01:39 CEST 2022 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ python --version
Python 3.10.8
dennis@gentoo ~ $ 
```

### What is the issue:

Since the last two updates, I get the above version number.
Seems like cosmetics, though, everything is functionally working just fine.

**Comment by spaam** [comment]
how did you install it on your gentoo system? what file are you using?

**Comment by SweDennis** [comment]
1. git clone https://github.com/spaam/svtplay-dl/
2. cd svtplay-dl
3. sudo python3 setup.py install

**Comment by SweDennis** [comment]
Or rather, a git pull for updates followed by number 3.
Same behaviour however.

**Comment by SweDennis** [comment]
Oh well, I only have to care about the output of svtplay-dl --version for the times that I have reasons to post an issue here, since you ask for it in your template, and besides ... the Actual version number is very visible during manual install either way so it can still be provided in future issues, should future issues arise ... so all in all, not an issue, or at worst ... cosmetics ... :-D

**Comment by spaam** [comment]
the output is pretty useful to help and see what snapshot a user are using when they report a bug.  exe and make variants we set it manually. i guess need to figure out  a way to do it  with setup.py in a good way without having to add more dependencies that could brake stuff in the future. 🤔

**Comment by SweDennis** [comment]
You seem to be fully on top of things, but when I reported the tv4play issue, case #1505, the svtplay --version was functional.
The versioning broke with the tv4play issue being solved, and after that there was another update that I don't know what it was, so when I said "Since the last two updates", what I really meant was ... "The last two times that I did a git pull".
I do that daily however, and every time before I post an issue so I know I always have the latest, so I don't expect you have to backtrack too long to see what versions of whatever caused it all. :-D

Perhaps downgrade whatever versions you use and keep them there? :-D

/Dennis

**Comment by spaam** [comment]
https://github.com/spaam/svtplay-dl/commit/9fd65788d42c9c09997373732b824fe0af772d9c this thing broke it and fixed some other issues  https://github.com/spaam/svtplay-dl/actions/runs/3084455340/jobs/4986626345 . it fixed cx_freeze making exe issue. that was failing before. it broke setup.py.   i dont have the olds logs from the previous to see what versions of all this shit was using. it was working on the old cx_freeze but then i guess some of their dependencies updated and broke other things.  python in a nutshell.  the good  shit and bad shit about this poo.   :)

**Comment by SweDennis** [comment]
I'm all cool, sorry to bring your attention to a non issue. :-D Make of it what you will, and fix it as you see fit. As I said before, when I do a manual install I still see what the actual version is, and I'll bring that along for future issues, no matter what svtplay-dl --version brings. All the best, and have a great weekend, enjoy the pizza, as a way to say thank you for your swift attention ...

**Comment by SweDennis** [comment]
What's up with https://www.paypal.me/spaam ? It gives me a 403 ... Followed the donate link from https://svtplay-dl.se/donate/

**Comment by spaam** [comment]
i found the issue on sunday when i made the release hacked around it to fix the release. :) but its a good thing we have an issue for it  now .)   the link is working for me. if that doesnt work i guess you might can use my email j@i19.se  instead 🤔

**Comment by SweDennis** [comment]
I get this https://imgur.com/JsmJDER.png, but I'll sort it out ... weird that links give different results, but that's internet for you, or perhaps because I'm on VPN or whwatever, but I'll sort it out.

**Comment by SweDennis** [comment]
What the Crap, Paypal has issues, I get same 403 just going to https://www.paypal.com/ ...

**Comment by SweDennis** [comment]
Works with VPN turned off, Pizza money sent, now off to talk to my VPN provider ... :-D

**Comment by spaam** [comment]
this is fixed in master now.  :)
