### ISSUE TITLE
Corrupt media at SVTplay ?

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1510]
**Versions used:**
svtplay-dl 4.14-3-g8950be8
Python 3.8.10
Windows 8.1
ffmpeg version 5.1.2-full_build-www.gyan.dev

At downloading from SVTplay "Morden i Londongrad", svtplay-dl creates an .mp4 file with **a size of 266 bytes**
The command used:
svtplay-dl --format-preferred h264-51 https://www.svtplay.se/video/36910607/morden-i-londongrad/morden-i-londongrad-avsnitt-1

The erroneous result is not a generic.
If I apply the same command with the link to SVTplay "L.A. Konfidentiellt", I do get a working video file with 5.1-sound.
The command used in this case:
svtplay-dl --format-preferred h264-51 https://www.svtplay.se/video/jkd53P9/l-a-konfidentiellt

Is it the SVTplay-media with "Morden i Londongrad" that are of questionable quality w.r.t. 5.1-sound or what am I missing ?

**Comment by Sopor** [comment]
I could download it without any problem. I do not get any 5.1 audio, though.

And yes, i have `format-preferred: h264-51`, but i have it in the `svtplay-dl.yaml` file.

svtplay-dl 4.14-3-g8950be8

```
svtplay-dl.exe https://www.svtplay.se/video/36910607/morden-i-londongrad/morden-i-londongrad-avsnitt-1
INFO: Outfile: morden.i.londongrad.s01e01.1.ett.fall.fran.fjarde.vaningen-a3ff3e1-svtplay.mp4
INFO: Selected to download dash, bitrate: 4545 format: h264
[787/787][================================================================================] ETA: 0:00:00
[787/787][================================================================================] ETA: 0:00:00
INFO: Merge audio and video into morden.i.londongrad.s01e01.1.ett.fall.fran.fjarde.vaningen-a3ff3e1-svtplay.mp4
INFO: Merging done, removing old files
```

**Comment by spaam** [comment]
yeah it seems corrupt. getting the same issue :)

**Comment by Sopor** [comment]
Why can i download a working one?

**Comment by spaam** [comment]
sadly the 5.1 audio is broken 🤔 adding that specific m3u8 file to a deny list,  it seems do only have 2.0 audio tracks

**Comment by Sopor** [comment]
None of the episodes of `Morden i Londongrad` have 5.1 audio.

**Comment by pythonuser3856** [comment]
Your finding is what I'd expected.
Thanks for clarifying !
