### ISSUE TITLE
Slippa Syn- och Teckenspråkstolkade avsnitt

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1511]
svtplay-dl -S -A https://www.svtplay.se/video/37362685/genjagarna-lar-dig-mer/genjagarna-lar-dig-mer-sasong-1-avsnitt-1

svtplay-dl -S -A https://www.svtplay.se/video/37245053/genjagarna/genjagarna-sasong-1-avsnitt-1

"INFO: Episode 1 of 12" 

De där två URLerna är Fyra avsnitt vardera, men hur gör man -- förutom att hämta dem en o en -- för att slippa få med de 4 Syntolkat och de 4 Teckenspråkstolkat av vardera URLen?

När man hämtar med -A så börjar den som tur är med att hämta de vanliga, men sen (om man inte avbryter med Ctrl-C) så påbörjas då alla de andra 8 avsnitten att hämtas, vilket är klart onödigt.

Vad är Fixen?

**Comment by spaam** [comment]
Finns flera sätt o lösa detta på. tex `svtplay-dl -e "teckensprakstolkat,syntolkat" URL`  `-e` är för att den ska exkludera ord som är komma separerade.   tex `-e a` kommer den att excludera alla med `a` i namnet. `-e "a,b"`  kommer den göra de med `a` och `b`. 
för att slippa skriva in `-e` för varje gång du ska tanka hem något så kan jag Kraftigt Rekommendera läsa https://svtplay-dl.se/config/  finns ett par exempel på hur man gör :)
