### ISSUE TITLE
chardet a requirement?

### ISSUE THREAD

**Issue by metayan** [spaam/svtplay-dl#1512]
After upgrading all `pip` packages to latest, I got
```
/usr/local/lib/python3.9/dist-packages/requests/__init__.py:109:
 RequestsDependencyWarning:
 urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.0.1) doesn't match a supported version!
```
when starting `svtplay-dl`.

After installing `chardet` manually, the warning disappeared.
Maybe `chardet` should be added to `requirements.txt`.

Using
`svtplay-dl 4.14-3-g8950be8`
on Linux and macOS.

**Comment by spaam** [comment]
yes and no.  it depends how you see it.  svtplay-dl is depending on requests. requests is depending on charset.  the warning you are getting is coming from requests.  sure i could pin all the dependencies to a specific version  but right now its not really an issue.

**Comment by metayan** [comment]
Ah, alright. I'm not so proficient in python package intricacies, so thanks for the explanation. Closing.
