### ISSUE TITLE
svtplay-dl does no longer find the subtitles on svtplay.se

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1514]
### svtplay-dl versions:

% svtplay-dl --version
svtplay-dl 4.14-3-g8950be8

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
Windows 10 Pro
python 3.8.0

### What is the issue:

svtplay-dl does no longer find the Swedish subtitles of a program; however, when watching online, subtitles are available 

  % svtplay-dl --subtitle --verbose http://www.svtplay.se/video/KxkqbnE/vem-bor-har/vem-har-egen-brygga
DEBUG [1669666908.1009865] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.14-3-g8950be8
DEBUG [1669666908.1045158] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1669666908.1045158] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://www.svtplay.se/video/KxkqbnE/vem-bor-har/vem-har-egen-brygga'
DEBUG [1669666908.1065135] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svtplay.se:80
DEBUG [1669666908.3390303] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: http://www.svtplay.se:80 "GET /video/KxkqbnE/vem-bor-har/vem-har-egen-brygga HTTP/1.1" 307 0
DEBUG [1669666908.3418038] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1669666908.4783945] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/KxkqbnE/vem-bor-har/vem-har-egen-brygga HTTP/1.1" 200 73261
DEBUG [1669666908.5627985] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/e7o6Xmv'
DEBUG [1669666908.5643876] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1669666908.734051] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/e7o6Xmv HTTP/1.1" 200 1312
DEBUG [1669666908.7373648] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-9s.akamaized.net/d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/hls-cmaf-lb-full.m3u8'
DEBUG [1669666908.7470381] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-9s.akamaized.net:443
DEBUG [1669666908.9792628] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-9s.akamaized.net:443 "GET /d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/hls-cmaf-lb-full.m3u8 HTTP/1.1" 200 875
DEBUG [1669666909.032434] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\charset_normalizer\api.py/from_bytes: Encoding detection: utf_8 is most likely the one.
DEBUG [1669666909.0394442] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-9s.akamaized.net/d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/text/text-closed.m3u8'
DEBUG [1669666909.0414295] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-9s.akamaized.net:443
DEBUG [1669666909.2720556] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-9s.akamaized.net:443 "GET /d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1669666909.28063] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\charset_normalizer\api.py/from_bytes: Encoding detection: ascii is most likely the one.
DEBUG [1669666909.289147] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-9s.akamaized.net/d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/dash-lb-full.mpd'
DEBUG [1669666909.3769848] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-9s.akamaized.net:443 "GET /d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/dash-lb-full.mpd HTTP/1.1" 200 1072
DEBUG [1669666909.4401426] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\charset_normalizer\api.py/from_bytes: Encoding detection: utf_8 is most likely the one.
DEBUG [1669666909.4415915] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\charset_normalizer\api.py/from_bytes: Encoding detection: utf_8 is most likely the one.
DEBUG [1669666909.5718954] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-9s.akamaized.net/d0/world/20221125/d4fd321e-5db2-4093-a67d-66d64067bdb3/dash-hbbtv-hevc.mpd'

**Comment by Usernamnet** [comment]
Same problem in version 4.15

**Comment by Minherre** [comment]
PRECIS vad jag tänkte skriva, fast på svenska då...  ;-)

De här är Två Delar vardera, och båda programmen inleds med svensk Berättare (senare i programmen är det ju hårdkodad svensk textning), och det Berättaren säger är textat när man ser dem på nätet, men det kommer inte med några .SRT filer när man hämtar dem, varför då?

svtplay-dl -S -A https://www.svtplay.se/video/jEWx4zm/verklighetens-peaky-blinders/1-gangkrig

svtplay-dl -S -A https://www.svtplay.se/video/e96wbaR/varldens-historia-operation-barbarossa/1-lebensraum-till-varje-pris

Använder 4.15.

**Comment by pythonuser3856** [comment]
I had the same problem

Now, however, it seems to work again.
At least for the two links that I've tried:
https://www.svtplay.se/video/jmoMQqM/30-minuter/energi--och-naringsminister-ebba-busch
https://www.svtplay.se/video/jgVzANr/hart-vader/5-monsun-pa-liv-och-dod

**Comment by Minherre** [comment]
Såg att v4.16 anlänt, men jag får fortfarande inga Subs till vare sig

svtplay-dl -S https://www.svtplay.se/video/8Wv6bVy/verklighetens-peaky-blinders/1-gangkrig

eller

svtplay-dl -S https://www.svtplay.se/video/e96wbaR/varldens-historia-operation-barbarossa/1-lebensraum-till-varje-pris

Suck...

**Comment by spaam** [comment]
det är visst för att dom verkade ha kvar det gamla sättet på vissa videos och nya sättet på andra.  tråkigt

**Comment by spaam** [comment]
4.17 har support för gamla o nya. om ni har 4.15 så funkar de att tanka hem subs. dom som hade nya länkat här har de gamla nu.

**Comment by Minherre** [comment]
> det är visst för att dom verkade ha kvar det gamla sättet på vissa videos och nya sättet på andra. tråkigt

Ok, Tack, det där Snapshotet "01-Dec-2022 06:23" funkade för att hämta bara Subs för alla dem jag skrev om ovan!
