### ISSUE TITLE
Download of subtitles from TV4 Play no longer works for some programs

### ISSUE THREAD

**Issue by andersm1019** [spaam/svtplay-dl#1516]
### svtplay-dl versions: 
4.17

### Operating system and Python version:
Raspbian GNU/Linux version 10 (buster)
Pyton 3.7.3

### What is the issue:
Subtitles not downloaded from some programs on TV4 Play.
Example:
svtplay-dl -S --force-subtitle --verbose "https://www.tv4play.se/program/kometernas-jul/del-9-s%C3%A4song-1/13778803?offset=0"

DEBUG [1670578286.4101102] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.17
DEBUG [1670578286.4143448] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1670578286.4148445] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/kometernas-jul/del-9-s%C3%A4song-1/13778803?offset=0'
DEBUG [1670578286.4186983] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1670578286.6238613] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/kometernas-jul/del-9-s%C3%A4song-1/13778803?offset=0 HTTP/1.1" 200 None
DEBUG [1670578286.6318913] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback2.a2d.tv/play/13778803?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets'
DEBUG [1670578286.6346412] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1670578286.9498594] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/13778803?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets HTTP/1.1" 200 4375
DEBUG [1670578286.951401] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/.m3u8'
DEBUG [1670578286.9540985] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1670578287.030177] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/.m3u8 HTTP/1.1" 200 627
DEBUG [1670578287.0404735] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554-textstream_swe=1000.m3u8'
DEBUG [1670578287.055673] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554-textstream_swe=1000.m3u8 HTTP/1.1" 200 1600
DEBUG [1670578287.0690854] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/.mpd'
DEBUG [1670578287.0876703] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/.mpd HTTP/1.1" 200 1336
DEBUG [1670578287.3215468] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554-textstream_swe=1000.m3u8'
DEBUG [1670578287.3242974] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1670578287.3905864] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /26305947-e4b4-46a4-a507-fc884c57664e/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554.ism/06ab9a50-774d-11ed-9361-3552c5044eb6_20324554-textstream_swe=1000.m3u8 HTTP/1.1" 200 1600

**Comment by spaam** [comment]
i got something in the works.  rewrote some parts of the subtitle code.  im testing it now. hopefully i can commit it tomorrow :D

**Comment by Sopor** [comment]
I downloaded kommissarie-van-der-valk and episode 1 and 2 no subtitles but on episode 3 i got subtitles.

**Comment by spaam** [comment]
what streaming site have that episodes? 🤔

**Comment by Sopor** [comment]
It seems that i only got 866 entries, but the whole subtitle should have 1585 entries.

**Comment by Sopor** [comment]
> what streaming site have that episodes? 🤔

`https://www.tv4play.se/program/kommissarie-van-der-valk/del-3-s%C3%A4song-2/13773146`

**Comment by spaam** [comment]
i pushed the commit to master. it seems to work. for urplay, svtplay, tv4play.  :)  will test more sites tomorrow before releasing a new version

**Comment by Sopor** [comment]
Some lines have these extra numbers from 8 to 10 digits
```
3
00:02:57,840 --> 00:02:59,360
-Hej!
-Hej!
875180381
```

**Comment by Sopor** [comment]
It still don't show any progress indicator when downloading subtitles.

Is that something you can fix? If you are new to svtplay-dl you will think that the program has hung.

I remember there was another way to get the whole subtitle in one file instead of downloading small parts.

I don't know if that is still available ...

**Comment by JohnnyJorgensen** [comment]
HI all. Curious. What is the status on this issue? I don't really understand from the comments if it is fixed or if it still doesn't work?

**Comment by martinlindhe** [comment]
Would it be possible to allow for unprocessed vtt subtitles to be written to disk, rather than the vtt -> srt scrub that happens now?

**Comment by testbughub** [comment]
+1 here.
I'm having issues with [The Rookie](https://www.tv4play.se/program/the-rookie).
I know it has worked before, since I've used it for the first two seasons a few months ago.

**Comment by cobolbear** [comment]
> Some lines have these extra numbers from 8 to 10 digits
> 
> ```
> 3
> 00:02:57,840 --> 00:02:59,360
> -Hej!
> -Hej!
> 875180381
> ```
> 
> ```
> 15
> 00:03:39,040 --> 00:03:41,400
> -Vilken besvikelse.
> -Natten är ung.
> 1406969359
> ```

I'm still facing similar issues that Sopor refers to.

**Comment by spaam** [comment]
i have a fix for it. will release a new version tomorrow 😃

**Comment by testbughub** [comment]
Latest fix did it for me. Thanks! :smile:

**Comment by spaam** [comment]
this is fixed in latest release. :)
