### ISSUE TITLE
Subtitles download not properly on tv4play.se

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1520]
The subtitles are not always downloaded properly. Especially on tv4play.se, parts are missing, and some subtitles are only shown a fraction of a second.
Compare what you get when you watch online https://www.tv4play.se/program/farmen/del-1-s%C3%A4song-16/13786490 with what you get when you use svtplay-dl.

**Comment by Sopor** [comment]
![image](https://user-images.githubusercontent.com/5789283/213946643-ee435455-9208-4da9-9945-80cbecebb52b.png)

Operating System?
svtplay-dl version?
ffmpeg version?
No --verbose log

**Comment by bartdedecker** [comment]
The issue has been solved. You may close this.
