### ISSUE TITLE
--only-subtitle option?

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1522]
Would it be possible to add a new option --only-subtitle?

For some (older) programs, subtitles have only recently been made available. It would be nice if one could download them as follows:  svtplay-dl -A --only-subtitle URL

Hence, once the subtitle file is downloaded, it does not proceed with downloading the audio and video files.

**Comment by Sopor** [comment]
Have you tried `--force-subtitle      download only subtitle if its used with -S`?

**Comment by bartdedecker** [comment]
That works indeed. Thanks!

**Comment by Sopor** [comment]
@bartdedecker Don't forget to close the issue when you are finished ...

Only click on the button at the bottom that looks like this:
![image](https://user-images.githubusercontent.com/5789283/215613841-313c131d-7b29-4d1c-be43-f14a0528fbbf.png)

**Comment by bartdedecker** [comment]
--force-subtitle -S     works indeed
