### ISSUE TITLE
Cannot get media from SVT.se

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#1528]
Using:
svtplay-dl 4.18
python 3.8.10
windows 64

svtplay-dl crashes at an attempt to download from SVT.se
The example is using an http-link which worked yesterday -> site change ?

svtplay-dl --verbose https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok
DEBUG [1678720014.0700655] c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\utils\getmedia.py/get_media: version: 4.18
DEBUG [1678720014.0700655] c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\service\__init__.py/__init__: service: svt
DEBUG [1678720014.0700655] c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok'
DEBUG [1678720014.075066] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443
DEBUG [1678720014.2201009] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://www.svt.se:443 "GET /nyheter/inrikes/professor-i-it-sakerhet-tiktok HTTP/1.1" 200 23744
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_v418_2023-01-10py\__main__.py", line 15, in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\utils\getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_v418_2023-01-10py\svtplay_dl\service\svt.py", line 30, in get
    vid = janson["areaData"]["articles"][list(janson["areaData"]["articles"].keys())[0]]["media"][0]["image"]["svtId"]
KeyError: 'articles'

**Comment by R3C01L-SWE** [comment]
Doesn't crash here. But instead I do get this.

greyfox@mbp ~ % svtplay-dl --verbose "https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok"

DEBUG [1678720914.154339] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.18

DEBUG [1678720914.155842] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/svtplay_dl/service/__init__.py/__init__: service: svt

DEBUG [1678720914.156022] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok'

DEBUG [1678720914.251664] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443

DEBUG [1678720914.672651] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /nyheter/inrikes/professor-i-it-sakerhet-tiktok HTTP/1.1" 200 23002

ERROR [1678720914.684704] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/svtplay_dl/service/svtplay.py/_all_episodes: Can't find video info.

ERROR [1678720914.684803] /opt/homebrew/Cellar/svtplay-dl/4.18/libexec/lib/python3.11/site-packages/svtplay_dl/service/svtplay.py/find_all_episodes: Can't find any videos.

**Comment by Sopor** [comment]
Or download this `https://www.svtplay.se/video/KZArMgJ/agenda/igar-21-15` and jump to 21:32 😁

**Comment by spaam** [comment]
it seems to work here after a fix
```
➜  lib git:(master) ✗ python3 -m svtplay_dl https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok
INFO: Outfile: professor.i.it-sakerhet.tiktokforbud.overdrivet.trubbigt.svt.nyheter-svt.mp4
INFO: Selected to download dash, bitrate: 3408 format: h264
[30/30][==========================================================================================================================================================================] ETA: 0:00:00
[30/30][==========================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into professor.i.it-sakerhet.tiktokforbud.overdrivet.trubbigt.svt.nyheter-svt.mp4
INFO: Merging done, removing old files.
➜
````

**Comment by SweDennis** [comment]
Still crashes here, I'm afraid ...

```
dennis@gentoo ~ $ svtplay-dl --version
svtplay-dl 4.18+2.g85ef17d
dennis@gentoo ~ $ python --version
Python 3.10.10
dennis@gentoo ~ $ svtplay-dl https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok --verbose
DEBUG [1678729521.2173645] /usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.18+2.g85ef17d
DEBUG [1678729521.2189157] /usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/service/__init__.py/__init__: service: svt
DEBUG [1678729521.2189999] /usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/nyheter/inrikes/professor-i-it-sakerhet-tiktok'
DEBUG [1678729521.2204955] /usr/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443
DEBUG [1678729521.8968832] /usr/lib/python3.10/site-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /nyheter/inrikes/professor-i-it-sakerhet-tiktok HTTP/1.1" 200 23560
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==4.18+2.g85ef17d', 'svtplay-dl')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 708, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3.10/site-packages/svtplay_dl-4.18+2.g85ef17d-py3.10.egg/svtplay_dl/service/svt.py", line 30, in get
    vid = janson["areaData"]["articles"][list(janson["areaData"]["articles"].keys())[0]]["media"][0]["image"]["svtId"]
KeyError: 'articles'
dennis@gentoo ~ $ 
```

**Comment by SweDennis** [comment]
Aaaah, that's what you get for being presumtious in finding an update ... :-D
I'll cool off and let you work in peace ... :-D

**Comment by spaam** [comment]
4.19 fixes this 😄
