### ISSUE TITLE
Not naming file according to config file when downloading from svt play.

### ISSUE THREAD

**Issue by olskar** [spaam/svtplay-dl#1531]
### svtplay-dl versions:

svtplay-dl 4.19

### What is the issue:

Not naming file according to config file when downloading from svt play.
I use this in my config, and everything works except s and e
"{title}.s{season}e{episode}.{episodename}.{ext}"

I have tried this with
https://www.svtplay.se/video/K5Wk4re/octonauterna

**Comment by spaam** [comment]
i need the whole config file and not parts of it

**Comment by olskar** [comment]
> i need the whole config file and not parts of it

Sorry.

  default:
    all_episodes: true
    filename: '{title}.s{season}e{episode}.{episodename}-{service}.{ext}'

**Comment by spaam** [comment]
the issue seems to be that we cant find an episode number for it for some reason 🤔

**Comment by spaam** [comment]
should be fixed in the version 4.20 :)
