### ISSUE TITLE
SvtPlay-video spelar upp undertext-ljudspår

### ISSUE THREAD

**Issue by 38github** [spaam/svtplay-dl#1533]
### svtplay-dl versions:

Senaste yt-dlp + mpv

### Operating system and Python version:

Linux, Windows

### What is the issue:

SvtPlay-video spelar upp undertext-ljudspår när jag förväntar mig originalljudspåret.
https://www.svtplay.se/video/jGLPRba/shetland/avsnitt-2?id=jxLWvp7

**Comment by spaam** [comment]
tyvärr så är detta fel ställe för yt-dlp. du får gå till deras sida för support tyvärr. detta är för svtplay-dl och inte yt-dlp.
