### ISSUE TITLE
Failing DL Attempt

### ISSUE THREAD

**Issue by StreetCracker** [spaam/svtplay-dl#1534]
Same Error with regular ver 4.18 & -.19
**Only** with this single one (and like a while (around / up to several weeks) further back maybe one or a few others); otherwise several different others (series & singles) have been DLd properly even with ver 4.18.

### svtplay-dl versions:

svtplay-dl 4.19-1-gcbfd09f

### Operating system and Python version:

Operativsystemets namn	Microsoft Windows 10 Home
Version	10.0.19045 version 19045
Python hittades inte. K÷r utan argument f÷r att installera frÕn Microsoft Store eller inaktivera den hõr genvõgen frÕn Instõllningar > Hantera alias f÷r k÷rning av program.

### What is the issue:

C:\svtplay-dl\svtplay-dl--—TEST\svtplay-dl>svtplay-dl.exe --verbose -u ***** -p ***** --no-postprocess -o "D:\Video\svtplay-dl\DLs  -  TV4 Play" -t -S -A --include-clips https://www.tv4play.se/program/13-snart-30
DEBUG [1681929577.9656835] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.19-1-gcbfd09f
DEBUG [1681929577.9676461] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1681929577.9686966] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/13-snart-30'
DEBUG [1681929577.9717097] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1681929578.2986467] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/13-snart-30 HTTP/1.1" 200 None
DEBUG [1681929578.3266425] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://graphql.tv4play.se/graphql'
DEBUG [1681929578.3286443] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): graphql.tv4play.se:443
DEBUG [1681929578.517642] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://graphql.tv4play.se:443 "POST /graphql HTTP/1.1" 200 823
DEBUG [1681929578.5186448] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://graphql.tv4play.se/graphql'
DEBUG [1681929578.605643] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://graphql.tv4play.se:443 "POST /graphql HTTP/1.1" 200 823
DEBUG [1681929578.6066444] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
INFO [1681929578.6066444] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Episode 1 of 1
INFO [1681929578.6076434] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_all_episodes: Url: https://www.tv4play.se/program/13-snart-30/13802488
DEBUG [1681929578.6086469] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/13-snart-30/13802488'
DEBUG [1681929578.6106436] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1681929578.7806423] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/13-snart-30/13802488 HTTP/1.1" 301 None
DEBUG [1681929579.0423021] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/13-snart-30/avsnitt/13802488 HTTP/1.1" 200 None
DEBUG [1681929579.067057] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback2.a2d.tv/play/13802488?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets'
DEBUG [1681929579.0700426] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1681929579.3926487] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/13802488?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets HTTP/1.1" 200 5218
DEBUG [1681929579.3936636] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'
DEBUG [1681929579.3966596] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1681929579.4797742] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'): Retry(total=4, connect=5, read=4, redirect=None, status=None)
WARNING [1681929579.4817057] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=4, connect=5, read=4, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', HTTPException('got more than 100 headers'))': /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8
DEBUG [1681929579.485734] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (2): vod.streaming.a2d.tv:443
DEBUG [1681929579.5267162] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'): Retry(total=3, connect=5, read=3, redirect=None, status=None)
WARNING [1681929580.133413] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=3, connect=5, read=3, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', HTTPException('got more than 100 headers'))': /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8
DEBUG [1681929580.1360598] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (3): vod.streaming.a2d.tv:443
DEBUG [1681929580.1790395] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'): Retry(total=2, connect=5, read=2, redirect=None, status=None)
WARNING [1681929581.3890436] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=2, connect=5, read=2, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', HTTPException('got more than 100 headers'))': /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8
DEBUG [1681929581.3921595] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (4): vod.streaming.a2d.tv:443
DEBUG [1681929581.429227] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'): Retry(total=1, connect=5, read=1, redirect=None, status=None)
WARNING [1681929583.83114] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=1, connect=5, read=1, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', HTTPException('got more than 100 headers'))': /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8
DEBUG [1681929583.8340497] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (5): vod.streaming.a2d.tv:443
DEBUG [1681929583.8743098] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8'): Retry(total=0, connect=5, read=0, redirect=None, status=None)
WARNING [1681929588.6772058] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retrying (Retry(total=0, connect=5, read=0, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', HTTPException('got more than 100 headers'))': /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8
DEBUG [1681929588.680671] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (6): vod.streaming.a2d.tv:443
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\http\client.py", line 1344, in getresponse
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\http\client.py", line 331, in begin
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\http\client.py", line 221, in parse_headers
http.client.HTTPException: got more than 100 headers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 489, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vod.streaming.a2d.tv', port=443): Max retries exceeded with url: /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8 (Caused by ProtocolError('Connection aborted.', HTTPException('got more than 100 headers')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 139, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 18, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 93, in get_all_episodes
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 86, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 42, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 587, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 701, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vod.streaming.a2d.tv', port=443): Max retries exceeded with url: /3177fa98-9c8b-4cb9-bef0-8fcb7edc69a9/476f2bd0-d0a6-11ed-8b88-4336f6648e84_20345221.ism/.m3u8 (Caused by ProtocolError('Connection aborted.', HTTPException('got more than 100 headers')))

**Comment by spaam** [comment]
this is fixed in the version 4.20 :)
