### ISSUE TITLE
Slow download from svtplay.se?

### ISSUE THREAD

**Issue by bohelax** [spaam/svtplay-dl#1538]
svtplay-dl 4.20
Microsoft Windows [Version 10.0.19045.2728]

Has anyone else experienced that the downloading from svtplay has become very slow?

A 30 minute program can take about 15 minutes to download:

	bin>svtplay-dl.pyc -S -M https://www.svtplay.se/video/8D9bA4w/utrikesbyran/vinnarna
	INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.srt
	INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
	INFO: Selected to download dash, bitrate: 5583 format: h264
	[457/457][========================================] ETA: 0:00:00
	[457/457][========================================] ETA: 0:00:00
	INFO: Merge audio, video and subtitle into utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
	INFO: Determining the language of the subtitle(s).
	INFO: Language code: sv
	INFO: Merging done, removing old files.
	15 minutes, 38 seconds

At first I thought that the servers were overloaded, e.g by some live sports or something,
but urplay.se does not seem to download slower than it used to.

I used to get about 20 MiB/s for the video part of a dash download. Now it quickly falls to under 1 MiB/s.
(Bredbandskollen gives me: Latency: 12,138 ms Download: 224,990 Mbit/s Upload: 50,576 Mbit/s)

Maybe it's just me, but I wonder if svtplay.se has started using some kind of rate limiter, to discourage us downloaders.

If so maybe it could be tricked by inserting a delay before downloading the next 'chunk'(?), say some 250 ms or so.
If that is possible to do AND IF IT ACTUALLY WORKS the downloads would be slower than before but still much faster than (what I get) now.

Experimentation would be needed and since only particular services would have need of this 'feature' my suggestion would be to add it as an option, like '--chunkdelay ms' with a default of 0.
In this way it could be put into the svtplay-dl.yaml config file under a specific 'service:' header.

If svtplay.se have implemented rate limiting by blacklisting IP addresses we are out of luck.

To get feedback on whether anyone else have seen this problem would be useful, as I'm certain that svtplay-dl itself is completely innocent.

	------------------
A completely unrelated suggestion for a new feature in svtplay-dl is to replace the 'ETA: 0:00:00' by something like
'Done: 0:02:34' when (that part of) the download is completed.

//BoH

**Comment by SweDennis** [comment]
Hello, can't say that I have, and can't confirm on my setup I'm afraid, but just tested your link.

Using:
```
dennis@gentoo ~ $ svtplay-dl --version
svtplay-dl 4.20
dennis@gentoo ~ $ uname -a
Linux gentoo 6.2.14-gentoo #1 SMP PREEMPT_DYNAMIC Tue May  2 06:30:31 CEST 2023 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ python --version
Python 3.11.2
dennis@gentoo ~ $ 
```
I got this:
```
dennis@gentoo ~ $ time svtplay-dl -S -M https://www.svtplay.se/video/8D9bA4w/utrikesbyran/vinnarna
INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.srt
INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
INFO: Selected to download dash, bitrate: 5583 format: h264
[457/457][================================================================================================================================================================] ETA: 0:00:00
[457/457][================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio, video and subtitle into utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
INFO: Determining the language of the subtitle(s).
INFO: Language code: sv
INFO: Merging done, removing old files.

real	1m27.977s
user	0m18.337s
sys	0m7.483s
dennis@gentoo ~ $ 
```
Doesn't at least seem to be a persistent issue, or valid across the board for all.

/Dennis

**Comment by bohelax** [comment]
Thanks @SweDennis for the feedback!

So, I guess they are using some form of IP blocking.
I tried downloading using VPN and it is naturally much slower than usual, but it's at least faster than 'real time'.
//BoH

**Comment by SweDennis** [comment]
I will try the same under a windows VM, just to make sure and compare.
What bothers me somewhat is your statement that your VPN slows you down to any great extent given the comparatively slow speeds in question. 
In my test above I was using a VPN, and I saturate my 150 Mb/s line with or without a VPN, my ISP is the bottleneck, not the VPN.

More to follow.

/Dennis

**Comment by spaam** [comment]
i tried it on my windows 11 machine. 
```
PS C:\Users\johan\Downloads\svtplay-dl-amd64\svtplay-dl> Measure-Command { .\svtplay-dl.exe  -S -M https://www.svtplay.se/video/8D9bA4w/utrikesbyran/vinnarna | Out-Default }
INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.srt
INFO: Outfile: utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
INFO: Selected to download dash, bitrate: 5583 format: h264
[457/457][=================================================================================================================================================================] ETA: 0:00:00
[457/457][=================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio, video and subtitle into utrikesbyran.s2023e14.vinnarna-25c87dd-svtplay.mp4
INFO: Determining the language of the subtitle(s).
INFO: Language code: sv
INFO: Merging done, removing old files.

Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 6
Milliseconds      : 485
Ticks             : 1264853143
TotalDays         : 0,00146395039699074
TotalHours        : 0,0351348095277778
TotalMinutes      : 2,10808857166667
TotalSeconds      : 126,4853143
TotalMilliseconds : 126485,3143


PS C:\Users\johan\Downloads\svtplay-dl-amd64\svtplay-dl>
``` 
as we can see it took just over 2min.    i cant really find any think so change the chunk delay thing in the module i use. :)

**Comment by Sopor** [comment]
@spaam When using -M shouldn't all files be deleted after merging?
`INFO: Merging done, removing old files.`
The srt file is not deleted.

**Comment by spaam** [comment]
@Sopor you are correct.  i fixed that one time and people disliked it and now its there. :)

**Comment by bohelax** [comment]
Thank you all for the replies!

@SweDennis Unfortunately I'm using pretty old harware and I believe the slowness of my trial VPN may somewhat be due to its 'extra' encryption pass. Maybe I choose a bad/slow VPN to test it out.

What I may need is a VPN that not a VPN, i.e. some sort of 'relay service' that I could link through to give me a temporary IP, since in this case security is not an issue.

Right you are @spaam - if nobody else sees this new problem there is no need to do any work on it. Maybe just keep my suggested 'solution' in mind should this type of blocking pop up elsewhere.

Major thanks just for the existence of svtplay-dl !

//BoH

**Comment by SweDennis** [comment]
@bohelax If you are on old-ish hardware, a trial VPN, and possibly using openVPN as opposed to wireguard for a protocol, than that would for sure account for you lack in speed, so no mystery there.

**Comment by bohelax** [comment]
Thanks all, I'll try to close this issue now

//BoH
