### ISSUE TITLE
The -A switch isn't ignored on urplay.se if there is only one episode

### ISSUE THREAD

**Issue by olivertwistor** [spaam/svtplay-dl#1544]
### svtplay-dl versions:

4.22

### Operating system and Python version:

**OS**: EndeavourOS, kernel version 6.1.32-1-lts 64-bit
**Python**: 3.11.3

### What is the issue:

When I run `svtplay-dl --verbose https://urplay.se/program/221253-karlek-och-sex-i-ryssland` everything works as expected, but if I run `svtplay-dl --verbose -A https://urplay.se/program/221253-karlek-och-sex-i-ryssland` I get the following output before being returned to the prompt:

> DEBUG [1686943936.2124388] /usr/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.22
> DEBUG [1686943936.2128963] /usr/lib/python3.11/site-packages/svtplay_dl/service/__init__.py/__init__: service: urplay
> DEBUG [1686943936.213034] /usr/lib/python3.11/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/221253-karlek-och-sex-i-ryssland'
> DEBUG [1686943936.214265] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
> DEBUG [1686943936.3274796] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/221253-karlek-och-sex-i-ryssland HTTP/1.1" 200 34367

This is the same output I get for any other single video from urplay.se, not specifically the video mentioned above. Video series work as expected with the -A switch.

The reason I try to download single videos with the -A switch is that I'm lazy :stuck_out_tongue_winking_eye: and I have a .svtplay.yaml file looking like this:

```yaml
default:
    all_episodes: true
    subtitle: true
    thumbnail: true

service:
    tv4play:
        username: xxx
        password: xxx
```

Both svtplay.se and tv4play.se ignores the -A switch if downloading single episodes, so I assumed urplay.se would too. I would rather not have to remember adding -A to series on specifically urplay.se because as I said, I'm lazy.

**Comment by spaam** [comment]
yeah its a bit special should be fixed now.
