### ISSUE TITLE
Can´t download subtitles

### ISSUE THREAD

**Issue by kilmouski** [spaam/svtplay-dl#1549]
### svtplay-dl versions:

Run `svtplay-dl --version`
svtplay-dl 4.24

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)
Windows 10 22H2  Python 3.10.7
### What is the issue:

Just goes back to command promt without doing anything, I just to download the subtitles and not the movie.

Always include the URL you want to download and all switches you are using.
C:\svtplay-dl>svtplay-dl -S --force-subtitle --all-subtitles https://director.streaming.telia.com/tvm-packager-prod/vod/7a5c8458-07f2-4f86-ab9f-25e7b334ea9e/3102_b5cbef20-5bcf-4be7-b160-cad6923a75ee.smil/manifest.mpd                                   
[verbose.txt](https://github.com/spaam/svtplay-dl/files/11892422/verbose.txt)

**Comment by spaam** [comment]
latest snapshot will have a fix for this. hopefully a new version end of the week.
