### ISSUE TITLE
Språket på textningen blir unknown

### ISSUE THREAD

**Issue by ml-1** [spaam/svtplay-dl#1551]
Så här ser det ut när man muxar (-M) ett avsnitt från t.ex. tv4play.

INFO: Merge audio, video and subtitle into xxx.mp4
INFO: Determining the language of the subtitle(s).
INFO: Language code: sv
INFO: Merging done, removing old files.

Problemet är att textningen får inget språk i den muxade filen fast svtplay-dl hittade
att texten var svensk. Det är för att ffmpeg vill ha en landskod med tre bokstäver.

https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/subtitle_options#Set_Subtitle_Language

Jag har provat att hårdkoda resultatet till swe och då blir det rätt.

**Comment by spaam** [comment]
hade den inställt att den använder ISO 639-1 när de ska vara ISO 639-3.  borde va fixat nu :)
