### ISSUE TITLE
TV4 Play: -A does not work

### ISSUE THREAD

**Issue by hereinmyhead** [spaam/svtplay-dl#1553]
### svtplay-dl versions:

svtplay-dl 4.25

### Operating system and Python version:

Windows 11 Pro 22H 22621.2134
Python 3.10.0

### What is the issue:

Is there any chance to get -A to work with TV4 Play again?

C:\Users\name\Downloads\svtplay-dl>svtplay-dl https://www.tv4play.se/video/9c14d8fb037209c3b09b/tisdag-29-augusti -u USERNAME -p PASSWORD-A --verbose
DEBUG [1693336375.7340093] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.25
DEBUG [1693336375.737045] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1693336375.738085] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/authorize'
DEBUG [1693336375.7411315] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1693336376.0101066] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/authorize HTTP/1.1" 200 1098
DEBUG [1693336376.0106084] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/video/9c14d8fb037209c3b09b/tisdag-29-augusti'
DEBUG [1693336376.0126379] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1693336376.1085413] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/9c14d8fb037209c3b09b/tisdag-29-augusti HTTP/1.1" 200 None
ERROR [1693336376.1255956] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py/find_all_episodes: Can't play this because the video is geoblocked.

**Comment by spaam** [comment]
one workaround is to use the program page instead of the video :)

**Comment by hereinmyhead** [comment]
Thank you @spaam , that solution was to easy to find for me. :)
