### ISSUE TITLE
play.tv3.lv and play.tv3.ee

### ISSUE THREAD

**Issue by shelldor** [spaam/svtplay-dl#1559]
### What is the issue:

tv3.lv har bytt till play.tv3.lv vilket leder till att site is not supported
    svtplay-dl  https://play.tv3.lv/Zinas/tv3-zinas,serial-2530780

**Comment by spaam** [comment]
i looked at a bunch of videos and it seems like all of them have DRM on them. because of that i can't add support for the site .
