### ISSUE TITLE
svtplay: har två undertexter vanliga och close-caption "allt-tal"

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1560]
Hur får man med ÄVEN det den svenska Babblaren säger, i en Sub?

Ser man denna på nätet är det som Bo Eriksson säger textat från första sekunden, men hämtar man den så är bara det på engelska från 34 sek som är textat.

Har testat med:

svtplay-dl -S https://www.svtplay.se/video/8MVxGoR/varldens-historia-vilda-vastern?id=8MVxGoR

och med:

svtplay-dl --all-subtitles https://www.svtplay.se/video/8MVxGoR/varldens-historia-vilda-vastern?id=8MVxGoR

Men får ändå bara en 38kb .SRT med översättningen, inte de svenska kommentarerna, TROTS att de finns textade när man ser den på nätet ?!

I webbspelaren kan man välja 

Undertexter:
Av
Svenska
Svenska (allt tal)

Den sista var påslagen auto när jag spelade upp den i Webbläsaren.

(Sänds 20.00 ikväll på Svt2)

**Comment by spaam** [comment]
det går inte just nu?!!??! för att det finns inget stöd för det då båda är svenska och finns inget bra sätt att see skillnaden på dom.

**Comment by Bub0** [comment]
> det går inte just nu?!!??! för att det finns inget stöd för det då båda är svenska och finns inget bra sätt att see skillnaden på dom.
Hoppar bara in och visar skillnaden på dessa jag såg nu när jag kollade. 

Texten han inte vill ha:https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-open.vtt - **text-open.vtt** 

Texten  jag antar han vill ha: https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-closed.vtt  - **text-closed.vtt**

@Minherre du kan ladda ner den manuellt också om du vill. Använd tex inspektera i webbläsaren, tryck på nätverk, välj video och text, filtrera på vtt och kopiera länken till text-closed.vtt. Borde se ut så här: https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-closed.vtt
🙂

**Comment by Bub0** [comment]
> det går inte just nu?!!??! för att det finns inget stöd för det då båda är svenska och finns inget bra sätt att see skillnaden på dom.

Hoppar bara in och visar skillnaden på dessa jag såg nu när jag kollade.

Texten han inte vill ha:https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-open.vtt - text-open.vtt

Texten jag antar han vill ha: https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-closed.vtt - text-closed.vtt

@Minherre du kan ladda ner den manuellt också om du vill. Använd tex inspektera i webbläsaren, tryck på nätverk, välj video och text, filtrera på vtt och kopiera länken till text-closed.vtt. Borde se ut så här: https://ed15.cdn.svt.se/d0/se/20231002/4768dabe-1e65-47ba-9e5d-030f0607a7e9/text/text-closed.vtt
🙂

**Comment by Minherre** [comment]
> ja om du har filnamnen sådär så kan du ju se skillnad på dom . men jag vill inte hårdkoda in svtplay specifika grejer i delar som delas med andra sajter. :)

Man kanske kunde få upp en fråga - eller instruktioner för hur man hämtar - OM det finns två olika Subs som i detta fall?!

**Comment by bohelax** [comment]
Det man ju kan undra är varför inte --all-subtitles kan hitta dessa varianter.
Med den röra av alternativa undertexter som uppstått brukar jag räkna vad som finns med (ungefär)
        svtplay-dl.pyc -o srtTemp -s -S --force-subtitle --all-subtitles  <URL>
och manuellt välja om det finns mer än en (1) fil.
För ovanstående problem får man ju bara en fil - inte ens tillägg av --raw-subtitles hjälper.
/BoH

**Comment by spaam** [comment]
4.26 have a fix for this
