### ISSUE TITLE
Subtitles on svtplay.se do not download properly

### ISSUE THREAD

**Issue by bartdedecker** [spaam/svtplay-dl#1561]
The format of the subtitles has changed on svtplay.se. Hence, they are no longer properly processed and only a small part is kept in the *.srt file.
E.g. try to download the subtitles of the last two episodes of draknästet
svtplay-dl --force-subtitle https://www.svtplay.se/video/epdgy6b/draknastet/gastdrake-christian-von-koenigsegg
svtplay-dl --force-subtitle https://www.svtplay.se/video/KvZPn6k/draknastet/gastdrake-ash-pournouri

**Comment by Minherre** [comment]
TACK för att du såg det där, jag hämtade just de där två igår, men hade inte hunnit se dem än, och därmed upptäckt det där!

Ja, det där är ju för jävligt!
Subben till den första börjar ju inte förrän ca 17min in, den andra inte förrän 28min in...

Är ju ung. samma sak som det jag skrev om redan i tisdags:

https://github.com/spaam/svtplay-dl/issues/1560

Måste ju till nån slags fix.

**Comment by Minherre** [comment]
Här har vi ytterligare ett prg där det finns både Fulla Subs och så gott som Tomma Subs.

https://www.svtplay.se/blottad-i-sapmi

Hämtar man alla 10 (Det är bara 5 delar, men 5 med svensk Babblare, och 5 med samisk Babblare) så ser man att det ibland är Subs som bara är 1kb.

svtplay-dl -S -A https://www.svtplay.se/video/eakPDz3/blottad-i-sapmi/avsnitt-1

**Comment by bohelax** [comment]
Jag laddade ner filmen "Play" (https://www.svtplay.se/video/jk574Y2/play) med -S och hade naturligtvis samma problem.

Jag vet inte hur det fantastiska programmet svtplay-dl fungerar eller vad det använder sig av, men provade för första gången att använda
`bin>svtplay-dl -g https://www.svtplay.se/video/jk574Y2/play` som gav svaret
`https://svt-vod-3q.akamaized.net/d0/se/20231004/60c788e7-ff14-4310-adb1-901a4d51ebf/dash-full.mpd`
Nu kunde jag inte (med Firefox) ladda mer denna fil, men genom att kolla vad som hände när jag spelade i FF hittade jag
`https://switcher.cdn.svt.se/resolve/60c788e7-ff14-4310-adb1-901a4d501ebf/dash-full.mpd` och via detta också
`https://ed10.cdn.svt.se/d0/se/20231004/60c788e7-ff14-4310-adb1-901a4d501ebf/dash-full.mpd` som jag laddade ner.
I slutet på denna (stora fil) hittade jag
`    <AdaptationSet id="6" contentType="text" mimeType="text/vtt" lang="sv">`
`      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="caption"/>`
`     <Label>Svenska (allt tal)</Label>`
`      <Representation id="14" bandwidth="0">`
`       <BaseURL>text/text-closed.vtt</BaseURL>`
`      </Representation>`
`    </AdaptationSet>`
`    <AdaptationSet id="7" contentType="text" mimeType="text/vtt" lang="sv">`
`      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>`
`      <Label>Svenska</Label>`
`      <Representation id="15" bandwidth="0">`
`        <BaseURL>text/text-open.vtt</BaseURL>`
`      </Representation>`
`    </AdaptationSet>`
Där fanns i alla fall de magiska text-closed.vtt och text-open.vtt
Kanske det kan hjälpa någon som begriper vad som händer?
/BoH

**Comment by spaam** [comment]
behöver bara en issue för samma problem #1560 . stänger denna.
