### ISSUE TITLE
Urplay MPD send bad xml data

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1562]
Fungerar vare sig med 4.25 eller 4.26, blir bara:

svtplay-dl -S --verbose https://urplay.se/program/221259-karlek-och-relationer-i-varlden

svtplay-dl -S --verbose https://urplay.se/program/221259-karlek-och-relationer-i-varlden
DEBUG [1696829706.7517996] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.26
DEBUG [1696829706.7527976] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: urplay
DEBUG [1696829706.7527976] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://urplay.se/program/221259-karlek-och-relationer-i-varlden'
DEBUG [1696829706.7547965] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1696829706.8916094] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://urplay.se:443 "GET /program/221259-karlek-och-relationer-i-varlden HTTP/1.1" 200 37688
DEBUG [1696829706.8994434] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://media-api.urplay.se/config-streaming/v1/urplay/sources/221259'
DEBUG [1696829706.9004443] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): media-api.urplay.se:443
DEBUG [1696829706.930563] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://media-api.urplay.se:443 "GET /config-streaming/v1/urplay/sources/221259 HTTP/1.1" 200 None
DEBUG [1696829706.9325624] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://streaming20.ur.se/content/v2/221000-221999/221259-2r1652295025274/dash-avc.mpd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiIyMjA2MDAxIiwic3ViIjoiMjIxMjU5LTIiLCJleHAiOjE2OTcwMDI1MDR9.aOSi4liqVIQm8B_7kv7n4HR77-cM2_3HKBrGV11lmLc&u=10ca64c6-f009-461d-b25c-4d197e590c5d'
DEBUG [1696829706.9345608] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming20.ur.se:443
DEBUG [1696829706.954915] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://streaming20.ur.se:443 "GET /content/v2/221000-221999/221259-2r1652295025274/dash-avc.mpd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJraWQiOiIyMjA2MDAxIiwic3ViIjoiMjIxMjU5LTIiLCJleHAiOjE2OTcwMDI1MDR9.aOSi4liqVIQm8B_7kv7n4HR77-cM2_3HKBrGV11lmLc&u=10ca64c6-f009-461d-b25c-4d197e590c5d HTTP/1.1" 200 None
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\urplay.py", line 37, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 217, in dashparse
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 226, in _dashparse
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\xml\etree\ElementTree.py", line 1320, in XML
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 7, column 257

Gick däremot bra att nu med 4.26 hämta Bara Subs till de som inte funkade förut, t ex:

svtplay-dl -S --all-subtitles --force-subtitle https://www.svtplay.se/video/KvZPn6k/draknastet/gastdrake-ash-pournouri

Så tack för det!

**Comment by spaam** [comment]
detta är inte riktigt svtplay-dl problem.  dom skickar dålig xml  som är fel på därför den crashar. 🤔

**Comment by Minherre** [comment]
> detta är inte riktigt svtplay-dl problem. dom skickar dålig xml som är fel på därför den crashar. 🤔

Ser vad du skriver, men förstår inte ?!

Den är ju Spelbar på webben, så varför kan den då inte också hämtas?

**Comment by spaam** [comment]
tänk dig du har ett dokument och det finns vissa regler på hur det ska se ut. till exempel ett dokument får bara ha bokstäver i sig typ `a till ö`. för att göra detta dokument fel så har dom av misstag skrivit in `5` istället för `fem` i och med det så blir dokumentet fel.  i fallet med urplay så har dom skrivit `&` när dom egentligen skulle ha skrivit `&amp;` istället.

**Comment by Minherre** [comment]
> tänk dig du har ett dokument och det finns vissa regler på hur det ska se ut. till exempel ett dokument får bara ha bokstäver i sig typ `a till ö`. för att göra detta dokument fel så har dom av misstag skrivit in `5` istället för `fem` i och med det så blir dokumentet fel. i fallet med urplay så har dom skrivit `&` när dom egentligen skulle ha skrivit `&amp;` istället.

Jaha, och nu vet dom för all framtid hur de ska sabba för oss...  ;-( 
SUCK!

**Comment by SweDennis** [comment]
Antar att det är lite i samma anda som att webläsare i alla tider har behövt anpassa sig till websidor som inte följer standarden för html. Jag minns när jag använde Opera upp till 3.61, då var den helt strikt med att följa standarder, medan IE och andra gjorde vad de kunde för att anpassa sig, och folk sade ... "Använd IE för den Funkar ju i alla fall". Sedan så blev de webläsarna bara större och större, med fler och fler specialfall att underhålla för framtiden som till slut orsakade nya fel som inte borde funnits där från början ... En svår balansgång det där, med att få något att "bara funka" även om det inte borde när andra har slarvat ...

**Comment by spaam** [comment]
4.27 har en fix för detta : )
