### ISSUE TITLE
tv4play changed login so not working at all

### ISSUE THREAD

**Issue by jula420** [spaam/svtplay-dl#1563]
svtplay-dl versions: 4.26

Operating system and Python version: Ubuntu 22.04, python 3.10.12

svtplay-dl --verbose -u "uuu" -p "ppp" https://www.tv4play.se/video/67e70163b3e6addd60aa/avsnitt-1
DEBUG [1696865737.039736] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.26
DEBUG [1696865737.0417569] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1696865737.0418816] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/67e70163b3e6addd60aa/avsnitt-1'
DEBUG [1696865737.0438483] /home/jan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1696865737.2105966] /home/jan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/67e70163b3e6addd60aa/avsnitt-1 HTTP/1.1" 200 None
DEBUG [1696865737.2265906] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/authorize'
DEBUG [1696865737.227858] /home/jan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1696865737.390122] /home/jan/.local/lib/python3.10/site-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/authorize HTTP/1.1" 403 297
ERROR [1696865737.391637] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. You need username / password.

**Comment by rfq-mtorg** [comment]
also experiencing this issue

**Comment by spaam** [comment]
seems like i fixed the issue locally.  maybe a new version later tonight :) 

```bash
imagine svtplay-dl-dev/lib ‹master*› » python3 -m svtplay_dl https://www.tv4play.se/video/1ff5914d6feb69691bca/avsnitt-1
INFO: Outfile: robinson.s13e01.robinson.del.1-1ff5914d6feb69691bca-tv4play.ts
INFO: Selected to download hls, bitrate: 7027 format: h264
[0052/1038][====............................................................................] ETA: 0:00:07^C
imagine svtplay-dl-dev/lib ‹master*› »
```

**Comment by spaam** [comment]
4.27 have a fix for this :)

**Comment by martinlindhe** [comment]
@spaam Seems this tv4play login fix is not working

I have username & password setup and it used to work

```
$ svtplay-dl -S -v https://www.tv4play.se/video/f8b4d02c46c49f7410f0/avsnitt-9
DEBUG [1697442336.7372236] /usr/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.27+1.g5db50df6
DEBUG [1697442336.7379422] /usr/lib/python3.11/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1697442336.7379627] /usr/lib/python3.11/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/f8b4d02c46c49f7410f0/avsnitt-9'
DEBUG [1697442336.738508] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1697442336.8814971] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/f8b4d02c46c49f7410f0/avsnitt-9 HTTP/1.1" 200 None
DEBUG [1697442336.899844] /usr/lib/python3.11/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://auth.a2d.tv/_bm/get_params?type=web-jsto'
DEBUG [1697442336.9018426] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): auth.a2d.tv:443
DEBUG [1697442337.0256257] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://auth.a2d.tv:443 "GET /_bm/get_params?type=web-jsto HTTP/1.1" 200 207
DEBUG [1697442337.0272586] /usr/lib/python3.11/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/authorize'
DEBUG [1697442337.0296946] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1697442337.361209] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/authorize HTTP/1.1" 403 296
ERROR [1697442337.3625515] /usr/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. You need username / password.

$ svtplay-dl --version
svtplay-dl 4.27+1.g5db50df6
```

**Comment by spaam** [comment]
@martinlindhe  you are using an old version. update to the new version 4.28.1, read the error message  or visit https://svtplay-dl.se/tv4play/ :)

**Comment by martinlindhe** [comment]
> @martinlindhe you are using an old version. update to the new version 4.28.1, read the error message and/or visit https://svtplay-dl.se/tv4play/ :)

Just noticed & got it working with the token solution, thanks & sorry for the noise!
