### ISSUE TITLE
TV4play, no videos found, need token

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1569]
Hi,
tv4play is asking for tokens, have they started using cookie files when using svtplay-dl?
New issue on this site for me, but not uncommon otherwise, was common on discovery+ before they went DRM.

Using:

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.28.1', 'svtplay-dl')
svtplay-dl 4.28.1
dennis@gentoo ~ $ python --version
Python 3.11.5
dennis@gentoo ~ $ uname -a
Linux gentoo 6.4.16-gentoo #1 SMP PREEMPT_DYNAMIC Wed Sep 27 20:43:43 CEST 2023 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 

```
Command:

```
svtplay-dl https://www.tv4play.se/video/67e70163b3e6addd60aa/avsnitt-1 -v

```

Output:

```
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.28.1', 'svtplay-dl')
DEBUG [1697127474.3190696] /usr/lib/python3.11/site-packages/svtplay_dl-4.28.1-py3.11.egg/svtplay_dl/utils/getmedia.py/get_media: version: 4.28.1
DEBUG [1697127474.3214478] /usr/lib/python3.11/site-packages/svtplay_dl-4.28.1-py3.11.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1697127474.3215656] /usr/lib/python3.11/site-packages/svtplay_dl-4.28.1-py3.11.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/67e70163b3e6addd60aa/avsnitt-1'
DEBUG [1697127474.3237865] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1697127474.4734497] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/67e70163b3e6addd60aa/avsnitt-1 HTTP/1.1" 200 None
ERROR [1697127474.496726] /usr/lib/python3.11/site-packages/svtplay_dl-4.28.1-py3.11.egg/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. You need a token to access the website. see https://svtplay-dl.se/tv4play/

```

Regards,
/Dennis

**Comment by spaam** [comment]
token thing is something i added yesterday to workaround the login issue we had before.  the login got a bunch of browser checks in javascript. some of those data i dont know how to get.  instead of using the user / passwd, we can use the token to get around it.  that message was something i added so people can read how to do it.

**Comment by SweDennis** [comment]
Spaam ...

sorry to re-open, but help file says:

```
--token TOKEN         token

```

What's a valid token? 

Just looked in --help and https://svtplay-dl.se/usage/ and also tried this and that as TOKEN ...

Please advice. :-D

/Dennis

**Comment by spaam** [comment]
comrade dennis, you will get 12 points if you go to the page in the error message and read it.  if you still having issues after it. feel free to tell me what the issue is with this token thing so i can update that page to make it easier to understand :)

**Comment by SweDennis** [comment]
Oh for F**Ks sake, please ignore me from now on, I completely misread that URL message ... 

Sigh.

Case closed

/Dennis

**Comment by spaam** [comment]
congratulations you won 12 points 🎉

**Comment by SweDennis** [comment]
And you won a pizza come next pay day.

/Dennis

**Comment by SweDennis** [comment]
The current https://svtplay-dl.se/tv4play/ needs some work ...at least from what I can see at my setup and brave browser ...

The token is nowhere to be found under Console for me, possibly my fault, and I didn't expect as much, but it's all over the place under the Network tab. for me here and now ...

Bottom line is that all works, my original link works without username and password but with the session token instead, once you find it ... :-D

/Dennis

**Comment by spaam** [comment]
Did you login to the page? If so, did you copy the code on the svtplay-dl site and pasted that to the console tab and press enter? 🤔

**Comment by jula420** [comment]
Working 100% for me

**Comment by Sopor** [comment]
@spaam What `code` are you talking about? I can't see any code ...

**Comment by spaam** [comment]
@Sopor , on the svtplay-dl.se web site 
![image](https://github.com/spaam/svtplay-dl/assets/202428/65516cd1-04fa-41e5-96f1-9555d5ab31b3)  the code in the dark area 🤔

**Comment by Sopor** [comment]
> @Sopor , on the svtplay-dl.se web site the code in the dark area 🤔

Hm and i need to press enter at the end too or else it is hard to copy.

**Comment by spaam** [comment]
sure i guess i should have included that on the page . but feels like most people did that anyway? 🤔

**Comment by SweDennis** [comment]
@spaam I didn't copy that text and press enter. Need to take a 101-course in inspecting and using the various things since it was a me-thing that I didn't find it at first. :-D

All is well here.

/Dennis
