### ISSUE TITLE
It's not possible to download from TV4Play (token is used)

### ISSUE THREAD

**Issue by hereinmyhead** [spaam/svtplay-dl#1576]
svtplay-dl 4.28.1
Python 3.11.1
Windows 11 Pro 21H2

### What is the issue:

I cannot download anything from TV4 Play anymore. It worked for about a week with the token thing but now it does not. I have verified that the token is up-to-date. 

### --verbose:

C:\Users\******\OneDrive\Apps\svtplay-dl>svtplay-dl` https://www.tv4play.se/video/a14ae04f733572d78f7e/s%C3%B6ndag-19-november --verbose

DEBUG [1700414086.801558] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.28.1
DEBUG [1700414086.8036354] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1700414086.8036354] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/video/a14ae04f733572d78f7e/s%C3%B6ndag-19-november'
DEBUG [1700414086.8047624] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1700414086.904731] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/a14ae04f733572d78f7e/s%C3%B6ndag-19-november HTTP/1.1" 200 None
DEBUG [1700414086.921048] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1700414086.9220867] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1700414087.1382349] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 200 624
DEBUG [1700414087.1402733] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback2.a2d.tv/play/a14ae04f733572d78f7e?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3'
DEBUG [1700414087.1412346] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1700414087.5560334] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/a14ae04f733572d78f7e?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3 HTTP/1.1" 200 5389
DEBUG [1700414087.5560334] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.m3u8?start_index=3'
DEBUG [1700414087.5570297] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): vod.streaming.a2d.tv:443
DEBUG [1700414088.6234488] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.m3u8?start_index=3 HTTP/1.1" 200 2565
DEBUG [1700414088.6265848] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://vod.streaming.a2d.tv/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'
DEBUG [1700414096.2157297] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
DEBUG [1700414096.2157297] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1700414096.216746] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3
DEBUG [1700414104.6372159] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
DEBUG [1700414104.6372159] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1700414105.2469792] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3
DEBUG [1700414110.3981912] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
DEBUG [1700414110.3985455] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1700414111.6121893] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3
DEBUG [1700414111.726059] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
DEBUG [1700414111.726059] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1700414114.1438038] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3
DEBUG [1700414124.1977859] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
DEBUG [1700414124.1977859] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1700414129.001343] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3
DEBUG [1700414129.4165108] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://vod.streaming.a2d.tv:443 "GET /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 HTTP/1.1" 504 176
urllib3.exceptions.ResponseError: too many 504 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 486, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 941, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 931, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vod.streaming.a2d.tv', port=443): Max retries exceeded with url: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 84, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 45, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 703, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 510, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='vod.streaming.a2d.tv', port=443): Max retries exceeded with url: /00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3 (Caused by ResponseError('too many 504 error `responses'))

**Comment by spaam** [comment]
its working fine here. do you use a VPN or proxy or something to access the video?

**Comment by SweDennis** [comment]
Not very helpful but can confirm as working using: 

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.28.1', 'svtplay-dl')
svtplay-dl 4.28.1
dennis@gentoo ~ $ python --version
Python 3.11.5
dennis@gentoo ~ $ uname -a
Linux gentoo 6.6.1-gentoo #1 SMP PREEMPT_DYNAMIC Sat Nov 18 17:03:35 CET 2023 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 
```

**Comment by hereinmyhead** [comment]
Thank you @spaam and @SweDennis! No VPN or proxy. It's very helpful to know that the app is working! I will try another computer at my home.

**Comment by spaam** [comment]
what happens if you open 'https://vod.streaming.a2d.tv/00315d6c-b5b0-4f7e-9ea3-415dbab72df7/ca736a80-86dd-11ee-b154-93e0e545e37e_20450929.ism/.mpd?start_index=3´ in your browser? does it show a message or something else? it might download  a file that you can open in notepad  🤔

**Comment by Sopor** [comment]
If i run svtplay-dl` https://www.tv4play.se/video/a14ae04f733572d78f7e/s%C3%B6ndag-19-november --verbose i get:

svtplay-dl` is not recognized as an internal or external command, operable program or batch file.

I can see there is a " ` " sign after svtplay-dl.

**Comment by hereinmyhead** [comment]
Thank you for your answers! I works now on another Windows computer!
