### ISSUE TITLE
svtplay-dl  crashed for pluto.tv

### ISSUE THREAD

**Issue by Gulfo1** [spaam/svtplay-dl#1578]
### svtplay-dl versions:

.\svtplay-dl.exe --version
svtplay-dl 4.28.1

(Latest windows 64bit .exe)

### Operating system and Python version:

Windows 10

### What is the issue:

.\svtplay-dl.exe https://pluto.tv/en/on-demand/series/64ca3468177f70001315bfcb/season/19/episode/64f99c6d6b9e3e001363f66d
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues

.\svtplay-dl.exe --verbose https://pluto.tv/en/on-demand/series/64ca3468177f70001315bfcb/season/19/episode/64f99c6d6b9e3e001363f66d
DEBUG [1701006404.2752326] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.28.1
DEBUG [1701006404.2752326] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: plutotv
DEBUG [1701006404.2752326] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://pluto.tv/en/on-demand/series/64ca3468177f70001315bfcb/season/19/episode/64f99c6d6b9e3e001363f66d'
DEBUG [1701006404.2752326] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): pluto.tv:443
DEBUG [1701006405.1350489] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://pluto.tv:443 "GET /en/on-demand/series/64ca3468177f70001315bfcb/season/19/episode/64f99c6d6b9e3e001363f66d HTTP/1.1" 200 None
DEBUG [1701006405.166142] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://boot.pluto.tv/v4/start'
DEBUG [1701006405.166142] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): boot.pluto.tv:443
DEBUG [1701006405.4787228] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://boot.pluto.tv:443 "GET /v4/start?appName=web&appVersion=7.8.1-7ed0d2934d67fff986332da63a4eb45c87683638&deviceVersion=100.0.0&deviceModel=web&deviceMake=firefox&deviceType=web&clientID=3ce92a6b-8c62-11ee-b9dc-fc45965178ff&clientModelNumber=1.0.0&episodeSlugs=64ca3468177f70001315bfcb&serverSideAds=false&constraints=&drmCapabilities=widevine%253AL3&clientTime=2023-11-26T13%3A46%3A45Z HTTP/1.1" 200 None
DEBUG [1701006405.4787228] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://service-vod.clusters.pluto.tv/v4/vod/slugs/64ca3468177f70001315bfcb'
DEBUG [1701006405.4941514] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): service-vod.clusters.pluto.tv:443
DEBUG [1701006405.682202] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://service-vod.clusters.pluto.tv:443 "GET /v4/vod/slugs/64ca3468177f70001315bfcb?appName=web&appVersion=7.8.1-7ed0d2934d67fff986332da63a4eb45c87683638&deviceVersion=100.0.0&deviceModel=web&deviceMake=firefox&deviceType=web&clientID=3ce92a6b-8c62-11ee-b9dc-fc45965178ff&clientModelNumber=1.0.0&episodeSlugs=64ca3468177f70001315bfcb&serverSideAds=false&constraints=&drmCapabilities=widevine%253AL3&clientTime=2023-11-26T13%3A46%3A45Z HTTP/1.1" 404 65
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\plutotv.py", line 34, in get
KeyError: 'type'

**Comment by spaam** [comment]
seems bit broken. i cant watch any videos on the website.   just a frozen picture.

**Comment by spaam** [comment]
this should work better now in 4.69
