### ISSUE TITLE
Svtplay-dl not merging audio and video

### ISSUE THREAD

**Issue by fezaland** [spaam/svtplay-dl#1579]
When downloading from SVT Play, I get one MP4 file and one m4a file, and they will not merge. Latest version of  svtplay-dl and Mac OS.

This is the result I get from whatever link I try to download:

INFO: Merge audio and video into rapport.ikvall.1930-6209347-svtplay.mp4
ERROR: Something went wrong: dyld[13487]: Library not loaded: /usr/local/opt/mbedtls/lib/libmbedcrypto.14.dylib
  Referenced from: <DE3BA1B2-9ADA-3C66-A961-A3B284D526F5> /usr/local/Cellar/librist/0.2.7_3/lib/librist.4.dylib
  Reason: tried: '/usr/local/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/Cellar/mbedtls/3.5.1/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache)

How to fix this?
/Fredrik

**Comment by adrinia** [comment]
I had the same problem and followed the instructions here:
https://stackoverflow.com/questions/77110765/error-while-run-command-ffmpeg-library-not-loaded-opt-homebrew-opt-mbedtls-l

brew uninstall librist --ignore-dependencies
brew uninstall mbedtls --ignore-dependencies
brew reinstall ffmpeg

**Comment by spaam** [comment]
yeah this is something brew fucked up.  @adrinia thing should work :D
