### ISSUE TITLE
Can't download 4k quality of off svtplay.se - "Can't find that quality"

### ISSUE THREAD

**Issue by SkurtCobain** [spaam/svtplay-dl#1582]
### svtplay-dl versions:

svtplay-dl 4.28.1

### Operating system and Python version:

Windows 11 (OS-version 22621.2715) - Python 3.11.7

### What is the issue:

While trying to download the 4k version of 'Historien om Sverige', get the error: "Can't find that quality. Try a different one listed in --list-quality or try --flexible-quality"

### Ascertaining the available qualities:

svtplay-dl --list-quality https://www.svtplay.se/video/jQ76kE5/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan?info=visa
INFO: Quality:   METHOD:  Codec:   Resolution:  Language:            Role:
INFO: 19603      DASH     hevc-51  3840x2160    sv                   main
INFO: 19603      DASH     hevc-51  3840x2160    sv-x-tydligaretal    alternate
INFO: 19603      DASH     hevc-51  3840x2160    sv                   main
INFO: 19603      DASH     hevc-51  3840x2160    sv-x-tydligaretal    alternate
INFO: 19349      DASH     hevc     3840x2160    sv                   main
INFO: 19349      DASH     hevc     3840x2160    sv-x-tydligaretal    alternate

### Trying to download:

svtplay-dl --quality 19603 --verbose https://www.svtplay.se/video/jQ76kE5/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan?info=visa
DEBUG [1702575778.5243094] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.28.1
DEBUG [1702575778.525309] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1702575778.525309] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/jQ76kE5/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan?info=visa'
DEBUG [1702575778.52631] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1702575778.6574454] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/jQ76kE5/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan?info=visa HTTP/1.1" 200 36343
DEBUG [1702575778.6684492] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/ewAbYBZ'
DEBUG [1702575778.6694493] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1702575778.7422042] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/ewAbYBZ HTTP/1.1" 200 1892
DEBUG [1702575778.7432065] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt'
DEBUG [1702575778.7442062] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575778.8607585] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt HTTP/1.1" 200 25835
DEBUG [1702575778.8627589] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd'
DEBUG [1702575778.8637598] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575778.906325] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd HTTP/1.1" 200 1021
DEBUG [1702575778.9808462] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd'
DEBUG [1702575778.9828472] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.0278027] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd HTTP/1.1" 200 1021
DEBUG [1702575779.038806] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt'
DEBUG [1702575779.0512993] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt HTTP/1.1" 200 25835
DEBUG [1702575779.0593011] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-avc.m3u8'
DEBUG [1702575779.0680902] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-avc.m3u8 HTTP/1.1" 200 836
DEBUG [1702575779.072092] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8'
DEBUG [1702575779.0730925] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.1247642] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1702575779.126766] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-hbbtv-hevc.mpd'
DEBUG [1702575779.1406646] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-hbbtv-hevc.mpd HTTP/1.1" 200 1063
DEBUG [1702575779.2171872] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-full.mpd'
DEBUG [1702575779.2250745] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-full.mpd HTTP/1.1" 200 1570
DEBUG [1702575779.4171252] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-full.mpd'
DEBUG [1702575779.4181256] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.460021] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-full.mpd HTTP/1.1" 200 1570
DEBUG [1702575779.4870272] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt'
DEBUG [1702575779.5049355] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt HTTP/1.1" 200 25835
DEBUG [1702575779.5069363] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-lb-full.m3u8'
DEBUG [1702575779.51465] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-lb-full.m3u8 HTTP/1.1" 200 706
DEBUG [1702575779.5166516] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8'
DEBUG [1702575779.5176525] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.5597553] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1702575779.5607572] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-full.m3u8'
DEBUG [1702575779.57247] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-full.m3u8 HTTP/1.1" 200 1055
DEBUG [1702575779.5784717] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8'
DEBUG [1702575779.5794718] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.624072] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1702575779.6260726] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-avc.m3u8'
DEBUG [1702575779.6329267] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-ts-avc.m3u8 HTTP/1.1" 200 836
DEBUG [1702575779.6359272] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8'
DEBUG [1702575779.6369276] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.6785564] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1702575779.680557] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-cmaf-lb-full.m3u8'
DEBUG [1702575779.687559] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/hls-cmaf-lb-full.m3u8 HTTP/1.1" 200 824
DEBUG [1702575779.6915605] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8'
DEBUG [1702575779.6925604] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.7359242] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.m3u8 HTTP/1.1" 200 114
DEBUG [1702575779.7379246] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd'
DEBUG [1702575779.744934] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd HTTP/1.1" 200 1021
DEBUG [1702575779.8197908] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd'
DEBUG [1702575779.8207912] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575779.862702] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-avc.mpd HTTP/1.1" 200 1021
DEBUG [1702575779.8737054] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt'
DEBUG [1702575779.8913994] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt HTTP/1.1" 200 25835
DEBUG [1702575779.8933992] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-lb-full.mpd'
DEBUG [1702575779.9020386] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-lb-full.mpd HTTP/1.1" 200 1071
DEBUG [1702575779.9665895] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-lb-full.mpd'
DEBUG [1702575779.9675903] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-1n.akamaized.net:443
DEBUG [1702575780.0092702] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-lb-full.mpd HTTP/1.1" 200 1071
DEBUG [1702575780.0207765] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt'
DEBUG [1702575780.0393076] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/text/text-closed.vtt HTTP/1.1" 200 25835
DEBUG [1702575780.0413082] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-1n.akamaized.net/d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-hbbtv-avc.mpd'
DEBUG [1702575780.0485387] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-1n.akamaized.net:443 "GET /d0/world/20231116/77188bad-aa7a-453c-b5a3-20b8bc5cd225/dash-hbbtv-avc.mpd HTTP/1.1" 200 970
DEBUG [1702575780.1033795] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\stream.py/format_prio: Format priority: ['h264', 'h264-51']
DEBUG [1702575780.1043792] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\stream.py/protocol_prio: Protocol priority scores (higher is better): {'dash': 3, 'hls': 2, 'http': 1}
ERROR [1702575780.1043792] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: Can't find that quality. Try a different one listed in --list-quality or try --flexible-quality

**Comment by spaam** [comment]
your issue is related to this line `DEBUG [1702575780.1033795] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\stream.py/format_prio: Format priority: ['h264', 'h264-51']
DEBUG [1702575780.10437`
and you can see in the `--list-quality` line 
```
INFO: 19603 DASH hevc-51 3840x2160 sv main
```
last time i checked `hevc-51` is not  `h264-51` .  i recommend you reading https://svtplay-dl.se/4.69/  
you are using an old version of svtplay-dl. 4.69 was release few days ago.  :)

**Comment by SkurtCobain** [comment]
Ok! Thank you. I got it to work through specifying the --format

Patchnote:

*You can specify --format dvhevc-51,dvhevc,hevc-51,hevc to only get videos with dolby vision with and without 5.1 sound and hevc with and without 5.1 sound. by default svtplay-dl only download h264-51 and h264.

**Comment by Sopor** [comment]
@spaam Why will it not download if i only specify the quality?

```
svtplay-dl.exe https://www.svtplay.se/video/ewAbYBZ/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan -q 19603
INFO: Outfile: historien.om.sverige.s01e01.1.stenaldern.ca.14.500-3700.ar.sedan-8bedd30-svtplay.srt
ERROR: Can't find that quality. Try a different one listed in --list-quality or try --flexible-quality
```

If i `--list-quality` i can see that the highest quality is 19603.

And `--flexible-quality` will only show the help whatever i type after ☹

**Comment by spaam** [comment]
Let me guess. You are using same default values as SkurtCobain? See my previous answer :)

**Comment by Sopor** [comment]
I haven't specify anything more than quality 19603 as you can see in my previous post..

I even tried to add `resolution: ">=1080"`, but now it will only download 1080. If i add >= it should download higher as 1080 and if that not exists it should download 1080 or have i misunderstood something?.
```
svtplay-dl.exe https://www.svtplay.se/video/ewAbYBZ/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan
INFO: Outfile: historien.om.sverige.s01e01.1.stenaldern.ca.14.500-3700.ar.sedan-8bedd30-svtplay.srt
INFO: Outfile: historien.om.sverige.s01e01.1.stenaldern.ca.14.500-3700.ar.sedan-8bedd30-svtplay.mp4
INFO: Selected to download dash, bitrate: 7569 format: h264-51
```

If i add `>=2160` i only get `ERROR: Can't find any streams with that video resolution >=2160`

**Comment by Sopor** [comment]
@spaam BTW, in the 4.69 [info](https://svtplay-dl.se/4.69/) i think you have forgot to add a `"` at the end of `--resolution ">=1080`

**Comment by spaam** [comment]
what does this say? 
```
imagine svtplay-dl-dev/lib ‹master*› » python3 -m svtplay_dl --help | grep format-preferr
                  [--format-preferred h264,h264-51]
  --format-preferred h264,h264-51
``` 
using my glasses and i can read it say `h264,h264-51` ✔️ 


reading 
```
imagine svtplay-dl-dev/lib ‹master*› » python3 -m svtplay_dl --list-quality https://www.svtplay.se/video/ewAbYBZ/historien-om-sverige/1-stenaldern-ca-14-500-3700-ar-sedan
INFO: Quality:   METHOD:  Codec:   Resolution:  Language:            Role:
INFO: 19603      DASH     hevc-51  3840x2160    sv                   main
INFO: 19603      DASH     hevc-51  3840x2160    sv-x-tydligaretal    alternate
INFO: 19603      DASH     hevc-51  3840x2160    sv                   main
INFO: 19603      DASH     hevc-51  3840x2160    sv-x-tydligaretal    alternate
INFO: 19349      DASH     hevc     3840x2160    sv                   main
INFO: 19349      DASH     hevc     3840x2160    sv-x-tydligaretal    alternate
INFO: 10653      DASH     hevc-51  2560x1440    sv                   main
```
Do i see any `h264` or `h264-51` in the top under codec for `4k` videos? no.
using my glasses, do i still see any `h264` in the top there?  not at all.  
then im starting to think. maybe i cant fint those videos because they have a different format then the one im requesting?  it most be it 🤔   last time i checked `h264` is not the same as `hevc` 😄

**Comment by spaam** [comment]
öhhh something wrong in the logic

**Comment by Sopor** [comment]
If i specify `format-preferred: hevc-51` in the svtplay-dl.yaml it will still download `h264-51`.

Oh, `hevc-51` will not work in the config file.

**Comment by spaam** [comment]
these default codecs thing was added back in 2020-07-28.  im not sure how many devices do support hevc videos today   🤔

**Comment by Sopor** [comment]
Now i think i have got it to work... Thanks @spaam 🎂

**Comment by cobolbear** [comment]
I'm also phasing this issue. I tried with several solution but it still refuses me to download hevc, is it due to that I'm missing codec for Hevc?

**Comment by spaam** [comment]
@cobolbear by default svtplay only download `h264` and `h264-51`  format of the videos.    if you do what i wrote in my previous post https://github.com/spaam/svtplay-dl/issues/1582#issuecomment-1856613781 it will work

**Comment by cobolbear** [comment]
> @cobolbear by default svtplay only download `h264` and `h264-51` format of the videos. if you do what i wrote in my previous post [#1582 (comment)](https://github.com/spaam/svtplay-dl/issues/1582#issuecomment-1856613781) it will work

thanks, I will try to override that

**Comment by cobolbear** [comment]
> @cobolbear by default svtplay only download `h264` and `h264-51` format of the videos. if you do what i wrote in my previous post [#1582 (comment)](https://github.com/spaam/svtplay-dl/issues/1582#issuecomment-1856613781) it will work

Super! I was struggeling with this a lot :)
