### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [spaam/svtplay-dl#1585]
Wondering how I can have the `-options`  setup every time. With youtube-dl, in mac, you'd create ".config/youtube-dl/config" with the commands inside. I've tried looking around, but I haven't found anything for svtplay-dl except for some reference to a .yaml file which I'm not sure how it'd be formatted.

**Comment by spaam** [comment]
i have no idea what this `-options` thing is you talking about.  youtube-dl and svtplay-dl is completly different tools.

you can always check https://svtplay-dl.se/config/ it got some examples.

**Comment by 2V3EvG4LMJFdRe** [comment]
That's what I meant, thanks.

**Comment by Sopor** [comment]
@2V3EvG4LMJFdRe youtube-dl is a dead project.

You should use [yt-dlp](https://github.com/yt-dlp/yt-dlp) instead.
