### ISSUE TITLE
Inga Subs till Jojo Rabbit

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1586]
Får inga Subs alls till Jojo Rabbit, men fick Subs till nåt annat på Svtplay imorse.

https://www.svtplay.se/video/KMVx91Z/jojo-rabbit

Det finns Subs när man spelar upp den i Webbläsaren.

Använde:

svtplay-dl -S --all-subtitles https://www.svtplay.se/video/e4zXrDa/jojo-rabbit

**Comment by spaam** [comment]
du berättar inte vilken version du använder. jag får subs i 4.69.

**Comment by Minherre** [comment]
> du berättar inte vilken version du använder. jag får subs i 4.69.

Varför skulle det ha ändrat sig från förra 4.28.1?

Jag giller inte att man måste ha en config-fil till nya, och dessutom inte ens i samma mapp!

Och du ska väl inte stänga Subject innan folk haft en chans att svara, eller hur ?!

**Comment by spaam** [comment]
om du har läst release notes för 4.69 så kan du se att svtplay-dl har en par undertext fixar.
du behöver inte ha en config fil till de nya?   vanliga program kollar inte efter en config fil i samma mapp. 

om de funkar för mig i 4.69 och du inte inte berättar va du använder för version så antar ja du använder en gammal version.  dvs 4.69 har en fix för det.  ingen ide ha issuen öppen.

**Comment by Minherre** [comment]
Ok, ok, Tack tack , nu ska jag 'kanske' se Jojo Rabbit till Lunch...  ;-)
