### ISSUE TITLE
Still only partial subtitles from SVT

### ISSUE THREAD

**Issue by TardisK9** [spaam/svtplay-dl#1588]
I've downloaded the latest version of svtplay-dl (4.69), but it hasn't solved the subtitle problem that I've had with SVT since the end of september. When both Swedish and other languages are spoken in the same program there are no subtitles for the Swedish.

This happens with for example "Överklasspionerna" ( svtplay-dl --verbose https://www.svtplay.se/video/8opYDEG/overklasspionerna).

I'm using Windows 10. I seem to have Python version 3.9 (although don't remember installing it).

**Comment by spaam** [comment]
sounds like you want the one with captions.  `allt tal` subs.  try add `--all-subtitles` and you will get both the normal one and the one you want :)

**Comment by TardisK9** [comment]
With that command the subtitles are downloaded as two separate files, but the one with subtitles for the Swedish won't merge. I've tried merging the files manually with MKVToolNix too, but the Swedish subtitles still won't merge and therefore don't show when playing the program.

**Comment by spaam** [comment]
it works fine there without any issues. i was using `svtplay -M --all-subtitles URL`
![image](https://github.com/spaam/svtplay-dl/assets/202428/d87d200f-41a7-45d5-be43-bb53871dc6e1)

what version of ffmpeg do you use?  🤔

**Comment by TardisK9** [comment]
My mistake, I didn't know you have to right-click and choose Track 2 in VLC. The subtitles are there as long as you do that every time. Thanks! :-)

(I'm using FFmpeg version 6.1.)

**Comment by spaam** [comment]
you can press `v` to cycle between them in VLC. but using the right click method is a bit easier way to show there is two subtitles in the file :)
