### ISSUE TITLE
Issues with live streams svt1, svt2

### ISSUE THREAD

**Issue by borqq** [spaam/svtplay-dl#1591]
### svtplay-dl versions:
svtplay-dl 4.28.1

### Operating system and Python version:
Linux 6.6.8-arch1-1
Python 3.11.6

### What is the issue:
`svtplay-dl --verbose -l --stream-priority hls https://www.svtplay.se/kanaler/svt2`
```
...
[22/22][======================================] DU: 0:01:07DEBUG [1704024492.743261] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt2-d.akamaized.net/se/svt2/18c72148c00/dash-v4/v4-407338.mp4'
DEBUG [1704024492.7601562] /usr/lib/python3.11/site-packages/urllib3/connectionpool.py/_make_request: https://svt2-d.akamaized.net:443 "GET /se/svt2/18c72148c00/dash-v4/v4-407338.mp4 HTTP/1.1" 200 2063934
...
```

Expected behavior: Stream should start playing
Actual behavior: Stream downloads to file (without sound being captured)

Or maybe I'm doing something wrong? My intention is not to download the stream but rather watch in in real-time

Best regards

**Comment by spaam** [comment]
this is a known issue.    maybe someday it will be fixed and there is already issues with this. closing this
