### ISSUE TITLE
TV4Play

### ISSUE THREAD

**Issue by BacchusFLT** [spaam/svtplay-dl#1592]
### svtplay-dl versions: 
4.69 (Scoop updated to the most recent)

### Operating system and Python version:
Windows 11
Python 3.12.1 (Scoop updated to the most recent)

### What is the issue:

Command issued:
svtplay-dl -S -A https://www.tv4play.se/program/1fbe9591d752f48943c5/whitechapel

Claims DRM protection

I have populated the "svtplay-dl.yaml" as per this:
service:
  tv4play:
    token: "eyJhbGciOiJ ... [Here the actual token is placed, extracted as per https://svtplay-dl.se/tv4play/]

Output:

svtplay-dl -S -A https://www.tv4play.se/program/1fbe9591d752f48943c5/whitechapel
INFO: Episode 1 of 18
INFO: Url: https://www.tv4play.se/video/0b618787f8a91a51f6a4
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 2 of 18
INFO: Url: https://www.tv4play.se/video/2fd17474e7bdb88f8d09
ERROR: No videos found. We can't download DRM protected content from this site.

I tried the option to have the token in the command (using --token) and the token in the yaml file - same result.

The token extracted had ' string enclosings but the YAML seemed to want the ". I tried fiddling with this but it didn't make any difference. (Supporting a string with ' is suggested as this is what I get from the browser)
There are two instances of "ey in my token string". It is still the full one? A reference to how long it is expected to be would be a good thing.
Any idea what is wrong here, if the idea is that it should work....

**Comment by spaam** [comment]
the token thing seems to be working fine. but the error message is pretty clear and stright forward. this is not an svtplay-dl issue.  we cant download and decrypt DRM protected content.  its sucks but thats how it is.
