### ISSUE TITLE
Am I blocked on discord?

### ISSUE THREAD

**Issue by ecsjjgg** [spaam/svtplay-dl#1596]
I can't join Your discord

I know that I was blocked from Your discord earlier because I spammed (Not I, a bot spammed...)

I have since changed my password, and also enabled the 2FA, so it shouldn't happen again!

My discord sername is:  ecsjjgg#5254

Can You please unblock me?

**Comment by spaam** [comment]
Good you fixed that. I banned you because you send some spam message. You should be unbanned now

**Comment by ecsjjgg** [comment]
Thanks @spaam
