### ISSUE TITLE
pluto.tv No videos found

### ISSUE THREAD

**Issue by hamkg** [spaam/svtplay-dl#1597]
### svtplay-dl versions:

4.69
### Operating system and Python version:

Linux slackware -current, python-3.9,
### What is the issue:

Tried several movies on pluto.tv but only get "No videos found". Example:
svtplay-dl --verbose https://pluto.tv/sv/on-demand/movies/63a1cc8a8ba71d0013e6ddec
DEBUG [1706699646.7629027] /usr/lib64/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.69
DEBUG [1706699646.7652898] /usr/lib64/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: plutotv
DEBUG [1706699646.765369] /usr/lib64/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://pluto.tv/sv/on-demand/movies/63a1cc8a8ba71d0013e6ddec'
DEBUG [1706699646.7675385] /usr/lib64/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): pluto.tv:443
DEBUG [1706699652.2107797] /usr/lib64/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://pluto.tv:443 "GET /sv/on-demand/movies/63a1cc8a8ba71d0013e6ddec HTTP/1.1" 200 None
DEBUG [1706699652.2146573] /usr/lib64/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://boot.pluto.tv/v4/start'
DEBUG [1706699652.2172358] /usr/lib64/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): boot.pluto.tv:443
DEBUG [1706699652.844771] /usr/lib64/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://boot.pluto.tv:443 "GET /v4/start?appName=web&appVersion=7.10.0-51fd8807cbe3b7d9e9fddfbdc2993a295a605418&deviceVersion=119.0.0&deviceModel=web&deviceMake=firefox&deviceType=web&clientID=dc9717b8-c029-11ee-a82c-d8fc93b52dfe&clientModelNumber=1.0.0&seriesIDs=63a1cc8a8ba71d0013e6ddec&serverSideAds=false&constraints=&drmCapabilities=widevine%253AL3&clientTime=2024-01-31T11%3A14%3A12Z HTTP/1.1" 200 None
ERROR [1706699652.8458111] /usr/lib64/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find video info

**Comment by Sopor** [comment]
I believe all videos have been DRM protected, so you can probably remove `PlutoTV` from `svtplay-dl` @spaam 

Maybe someone can verify it first ...

**Comment by spaam** [comment]
for some reason i can't watch any videos on pluto. its just a picture and nothing happen so 🤷. same thing in firefox and chrome.

**Comment by Sopor** [comment]
> for some reason i can't watch any videos on pluto. its just a picture and nothing happen so 🤷. same thing in firefox and chrome.

Yeah, same here and i can see the DRM symbol when i select any show to watch
![image](https://github.com/spaam/svtplay-dl/assets/5789283/b0a390a5-d2ca-478c-ac0d-d3ce7db7fa12)

**Comment by hamkg** [comment]
Obviously _some_ videos are DRM protected, bur here's one that runs fine in my browser, although I still can't get it with svtplay-dl:
https://pluto.tv/sv/on-demand/movies/64a50df70a21a30013b88f03

**Comment by 3052** [comment]
same problem here

**Comment by hamkg** [comment]
With the 4.83 release, downloading from pluto.tv works again. Thanks a lot! Marked as closed.
