### ISSUE TITLE
Ny film på SVT Play genererar "ERROR: No videos found."

### ISSUE THREAD

**Issue by Schmagz** [spaam/svtplay-dl#1599]
### svtplay-dl versions: svtplay-dl 4.69

Run `svtplay-dl --version`

### Operating system and Python version: Windows 11 Pro, Python 3.9.2

Name and version of the operating system and python version (run `python --version`)

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    svtplay-dl --verbose https://www.svtplay.se/video/eXYgD9P/three-billboards-outside-ebbing-missouri

DEBUG [1708890153.8750193] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.69
DEBUG [1708890153.8755443] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1708890153.8755443] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/eXYgD9P/three-billboards-outside-ebbing-missouri'
DEBUG [1708890153.8776484] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1708890154.0587764] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/eXYgD9P/three-billboards-outside-ebbing-missouri HTTP/1.1" 200 30252
DEBUG [1708890154.0892181] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/jkLyE6W'
DEBUG [1708890154.0902221] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1708890154.2981522] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/jkLyE6W HTTP/1.1" 200 926
DEBUG [1708890154.2991557] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-secure-3b.akamaized.net/d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-cmaf-full.m3u8'
DEBUG [1708890154.3011565] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-3b.akamaized.net:443
DEBUG [1708890154.4115043] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-secure-3b.akamaized.net:443 "GET /d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-cmaf-full.m3u8 HTTP/1.1" 403 177
DEBUG [1708890154.4115043] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-secure-3b.akamaized.net/d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-avc.m3u8'
DEBUG [1708890154.443272] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-secure-3b.akamaized.net:443 "GET /d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-avc.m3u8 HTTP/1.1" 403 177
DEBUG [1708890154.4442716] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-secure-3b.akamaized.net/d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-lb-full.m3u8'
DEBUG [1708890154.4840398] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-secure-3b.akamaized.net:443 "GET /d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-lb-full.m3u8 HTTP/1.1" 403 177
DEBUG [1708890154.485011] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-secure-3b.akamaized.net/d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-avc.m3u8'
DEBUG [1708890154.531234] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-secure-3b.akamaized.net:443 "GET /d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-ts-avc.m3u8 HTTP/1.1" 403 177
DEBUG [1708890154.5330634] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://svt-vod-secure-3b.akamaized.net/d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-cmaf-lb-full.m3u8'
DEBUG [1708890154.5652778] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://svt-vod-secure-3b.akamaized.net:443 "GET /d0/secure/20240223/72fc0b90-e690-4e9e-8d4f-37e76cef5c02/hls-cmaf-lb-full.m3u8 HTTP/1.1" 403 177
ERROR [1708890154.5662448] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by spaam** [comment]
works here.  trying to access the video outside of sweden? 🤔 
```
imagine /tmp » ./svtplay-dl https://www.svtplay.se/video/eXYgD9P/three-billboards-outside-ebbing-missouri --version

svtplay-dl 4.69
imagine /tmp » ./svtplay-dl https://www.svtplay.se/video/eXYgD9P/three-billboards-outside-ebbing-missouri

INFO: Outfile: three.billboards.outside.ebbing.missouri-a3b949e-svtplay.ts
INFO: Selected to download hls, bitrate: 3547 format: hevc-51
[0102/1730]
```

**Comment by Schmagz** [comment]
You are right I used a VPN (but connected to Swedish IP though).

**Comment by spaam** [comment]
some sites block vpn endpoints. It's like a cat and mouse thing sadly.

**Comment by Schmagz** [comment]
Yes true and thank you for reminding me.
