### ISSUE TITLE
tv4play funkar ej på serier

### ISSUE THREAD

**Issue by sebbe34-svt** [spaam/svtplay-dl#1604]
### svtplay-dl versions:
svtplay-dl 4.69

### Operating system and Python version:
Linux mint, 20.3
Python 3.8.10

### What is the issue:
Programmen går att titta på browsern (firefox) när man är inloggad (gratis konto).
Men: Det går ej hämta ner avsnitten med svtplay-dl!
Med token satt i yam-filen korrekt, anger commandot (med eller utan --verbose):
 svtplay-dl https://www.tv4play.se/program/7462ebca139abb0e9291/oxen

Förutom den aktuella episoden, som går ladda ner, Får antingen geoblocked, eller DRM issue:

INFO: Episode 1 of 6
INFO: Url: https://www.tv4play.se/video/15f47c1b4570b68f9d99
ERROR: No videos found. Can't play this because the video is geoblocked.
INFO: Episode 2 of 6
INFO: Url: https://www.tv4play.se/video/a3c2bd847bcde28cb0d9
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 3 of 6
INFO: Url: https://www.tv4play.se/video/b41203c71bb312f9c79b
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 4 of 6
INFO: Url: https://www.tv4play.se/video/d50378e0ed2e1564a74c
ERROR: No videos found. We can't download DRM protected content from this site.

Och med verbose-switchen:

DEBUG [1711741229.423056] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.69
DEBUG [1711741229.4254062] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1711741229.4257214] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1711741229.4269786] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1711741229.520336] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 200 623
DEBUG [1711741229.5219588] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/7462ebca139abb0e9291/oxen'
DEBUG [1711741229.5240734] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1711741229.5579588] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/7462ebca139abb0e9291/oxen HTTP/1.1" 200 None
DEBUG [1711741229.56283] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://client-gateway.tv4.a2d.tv/graphql'
DEBUG [1711741229.5645304] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): client-gateway.tv4.a2d.tv:443
DEBUG [1711741229.7418406] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://client-gateway.tv4.a2d.tv:443 "POST /graphql HTTP/1.1" 200 2448
DEBUG [1711741229.743685] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://client-gateway.tv4.a2d.tv/graphql'
DEBUG [1711741229.8454344] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://client-gateway.tv4.a2d.tv:443 "POST /graphql HTTP/1.1" 200 2205
DEBUG [1711741229.8480096] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
INFO [1711741229.8481526] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 1 of 6
INFO [1711741229.8482654] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: https://www.tv4play.se/video/15f47c1b4570b68f9d99
DEBUG [1711741229.8483763] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/15f47c1b4570b68f9d99'
DEBUG [1711741229.8503106] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1711741229.8742635] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/15f47c1b4570b68f9d99 HTTP/1.1" 200 None
DEBUG [1711741229.8779063] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1711741229.879343] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1711741229.9573853] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 200 623
DEBUG [1711741229.9607415] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback2.a2d.tv/play/15f47c1b4570b68f9d99?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3'
DEBUG [1711741229.9628193] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1711741230.1045258] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/15f47c1b4570b68f9d99?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3 HTTP/1.1" 404 111
ERROR [1711741230.105337] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't play this because the video is geoblocked.
DEBUG [1711741230.1063273] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
INFO [1711741230.1104305] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 2 of 6
INFO [1711741230.1105392] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Url: https://www.tv4play.se/video/a3c2bd847bcde28cb0d9
DEBUG [1711741230.110652] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/a3c2bd847bcde28cb0d9'
DEBUG [1711741230.1128223] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1711741230.1358645] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/a3c2bd847bcde28cb0d9 HTTP/1.1" 200 None
DEBUG [1711741230.1385283] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1711741230.1398501] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1711741230.217573] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 200 623
DEBUG [1711741230.2212787] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback2.a2d.tv/play/a3c2bd847bcde28cb0d9?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3'
DEBUG [1711741230.2237134] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1711741230.432808] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/a3c2bd847bcde28cb0d9?service=tv4play&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome&capabilities=live-drm-adstitch-2%2Cyospace3 HTTP/1.1" 200 5557
ERROR [1711741230.4336257] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. We can't download DRM protected content from this site.
DEBUG [1711741230.4343581] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
INFO [1711741230.437412] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_all_episodes: Episode 3 of 6

**Comment by spaam** [comment]
visst 15f47c1b4570b68f9d99 videon borde kanske ha ett bättre felmeddelande kanske iom den videon inte finns tillgänglig  förän om 11 dagar.  men dom andra filerna  har rätt felmeddelande.  dom har DRM och vi kan inte göra något åt det.

**Comment by sebbe34-svt** [comment]
Aah. Tråkigt att höra. Men tydligen går det att se även DRM-avsnitten i browsern, varför går det inte att ladda ner dem då?

(Jag noterar även följande: på websidan ser man totalt 6 avsnitt, varav de 2 sista ej har sänts ännu (är det dessa som anges som "geoblocked" då, fast i fel ordning?).  Avsnitt 4 - vän eller fiende - gick fortfarande att ladda ner (se loggen nedan). Och de övriga 3 har alltså fått på sig DRM nu? Går ej att komma runt?

Här är hela loggen, alla avsnitt (episod 4 är redan nedladdad, härav felmeddelandet):
INFO: Episode 1 of 6
INFO: Url: https://www.tv4play.se/video/15f47c1b4570b68f9d99
ERROR: No videos found. Can't play this because the video is geoblocked.
INFO: Episode 2 of 6
INFO: Url: https://www.tv4play.se/video/a3c2bd847bcde28cb0d9
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 3 of 6
INFO: Url: https://www.tv4play.se/video/b41203c71bb312f9c79b
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 4 of 6
INFO: Url: https://www.tv4play.se/video/d50378e0ed2e1564a74c
ERROR: No videos found. We can't download DRM protected content from this site.
INFO: Episode 5 of 6
INFO: Url: https://www.tv4play.se/video/d649bee81cedfe1df05c
INFO: Outfile: oxen.s01e04.van.eller.fiende-d649bee81cedfe1df05c-tv4play.srt
WARNING: File (oxen.s01e04.van.eller.fiende-d649bee81cedfe1df05c-tv4play.srt) already exists. Use --force-subtitle to overwrite
INFO: Outfile: oxen.s01e04.van.eller.fiende-d649bee81cedfe1df05c-tv4play.ts
WARNING: File (oxen.s01e04.van.eller.fiende-d649bee81cedfe1df05c-tv4play.ts) already exists. Use --force to overwrite
INFO: Episode 6 of 6
INFO: Url: https://www.tv4play.se/video/e2755ed45237cb25e931
ERROR: No videos found. Can't play this because the video is geoblocked.

-

**Comment by spaam** [comment]
test 4.73. 4.71  got some fixes for this. closing this
