### ISSUE TITLE
URL funkar i 4.69 men EJ i nya 4,71

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1606]
URL funkar i 4.69 men EJ i 4.71.

Jag chansade på att det kanske hade nåt med Subs att göra, och tog bort "-S --all-subtitles" (för den där har ändå Hårdkodade Subs), men icke, blir samma fel iaf!

=====================

svtplay-dl --verbose -S --all-subtitles https://www.svtplay.se/video/8E3QJyV/vigil/avsnitt-5
DEBUG [1712894665.3567076] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.71
DEBUG [1712894665.3577046] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1712894665.358704] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/8E3QJyV/vigil/avsnitt-5'
DEBUG [1712894665.3597047] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1712894665.54197] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/8E3QJyV/vigil/avsnitt-5 HTTP/1.1" 200 31550
DEBUG [1712894665.555148] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/jLaErZZ'
DEBUG [1712894665.558145] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1712894665.6160204] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/jLaErZZ HTTP/1.1" 200 1089
DEBUG [1712894665.616506] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'
DEBUG [1712894673.6371439] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712894673.6381602] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1712894673.640168] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712894681.6573133] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712894681.6583216] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1712894682.260902] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712894690.2777078] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712894690.2787125] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1712894691.48533] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712894699.5019593] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712894699.5029638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1712894701.914528] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712894709.9308722] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712894709.9318805] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1712894714.7388337] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712894722.7568157] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 486, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py", line 938, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.svt.se', port=443): Max retries exceeded with url: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 100, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 141, in _get_video
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 48, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\sessions.py", line 703, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\requests\adapters.py", line 510, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.svt.se', port=443): Max retries exceeded with url: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& (Caused by ResponseError('too many 500 error responses'))

=====================

Som sagt, ovan funkar i 4.69.

Hämtade flera andra, både Svtplay o URPlay, o de funkade med 4.71.

Nåt är knas med 4.71.

(Men det var iaf skönt att bli av med alla de där "api-ms-win-core-BLABLA.DLL" som låg i själva svtplay-dl mappen efter uppackning förut!)

**Comment by SweDennis** [comment]
Hello, just to chime in in some way ...
The above is confirmed using:

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.71', 'svtplay-dl')
svtplay-dl 4.71
dennis@gentoo ~ $ python --version
Python 3.11.8
dennis@gentoo ~ $ uname -a
Linux gentoo 6.8.5-gentoo #1 SMP PREEMPT_DYNAMIC Thu Apr 11 17:06:04 CEST 2024 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 
```

**Comment by spaam** [comment]
Japp de är något problem 🤔 kan reproducera problemet själv så de är trevligt.

**Comment by spaam** [comment]
Finns de andra videos med samma problem? Jag kan inte hitta någon 🤔

**Comment by spaam** [comment]
`4.72` got ze fix :)

**Comment by SweDennis** [comment]
Indeed it did, confirmed as working ... Good job and many thanks.
