### ISSUE TITLE
4.71 crashes downloading from svtplay

### ISSUE THREAD

**Issue by peter-sthlm** [spaam/svtplay-dl#1607]
I upgraded from 4.69 to 4.71. It worked fine to download a number of svtplay episodes, but for one episode, I got the error below.

For this episode, I tried with 4.69, and it worked fine, so there seems to be something differing between 4.69 and 4.71.
As a side note, I also noticed that the version 4.71 (win32) did not include a number of api-ms-win-X dlls, so I copied them from the previous version.

### svtplay-dl versions:

svtplay-dl 4.71

### Operating system and Python version:

Windows 11
Python 3.7.3

### What is the issue:

svtplay-dl.exe --verbose -M -f -t -o . "https://www.svtplay.se/video/8E3QJyV/vigil/avsnitt-5"

DEBUG [1712990430.14492] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.71
DEBUG [1712990430.14492] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1712990430.14492] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/video/8E3QJyV/vigil/avsnitt-5'
DEBUG [1712990430.14492] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1712990430.2079618] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/8E3QJyV/vigil/avsnitt-5 HTTP/1.1" 200 31685
DEBUG [1712990430.2236211] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/jLaErZZ'
DEBUG [1712990430.2236211] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1712990430.2706826] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/jLaErZZ HTTP/1.1" 200 1089
DEBUG [1712990430.2706826] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'
DEBUG [1712990438.320227] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712990438.320227] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=4, connect=5, read=5, redirect=None, status=None)
DEBUG [1712990438.3263378] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712990446.3607395] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712990446.3607395] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=3, connect=5, read=5, redirect=None, status=None)
DEBUG [1712990446.9749436] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712990455.0126586] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712990455.0126586] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=2, connect=5, read=5, redirect=None, status=None)
DEBUG [1712990456.2242932] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712990464.2347145] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712990464.2347145] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=1, connect=5, read=5, redirect=None, status=None)
DEBUG [1712990466.6393204] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712990474.6485837] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
DEBUG [1712990474.6485837] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py/increment: Incremented Retry for (url='/ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG [1712990479.4597876] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/urlopen: Retry: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd&
DEBUG [1712990487.4724574] C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& HTTP/1.1" 500 64
urllib3.exceptions.ResponseError: too many 500 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\adapters.py", line 486, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 948, in urlopen
  [Previous line repeated 2 more times]
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\connectionpool.py", line 938, in urlopen
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.svt.se', port=443): Max retries exceeded with url: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 124, in run
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\Lib\site-packages\cx_Freeze\initscripts\console.py", line 17, in run
  File "bin\svtplay-dl", line 7, in <module>
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\__init__.py", line 69, in main
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 63, in get_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 100, in get
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 141, in _get_video
  File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py", line 48, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\sessions.py", line 703, in send
  File "C:\hostedtoolcache\windows\Python\3.8.10\x86\lib\site-packages\requests\adapters.py", line 510, in send
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.svt.se', port=443): Max retries exceeded with url: /ditto/api/v1/web?manifestUrl=https%3A%2F%2Fsvt-vod-secure-1a.akamaized.net%2Fd0%2Fsecure%2F20240409%2F98c6ecc7-2fb3-4e76-8c51-029f35265650%2Fdash-avc.mpd& (Caused by ResponseError('too many 500 error responses'))

**Comment by spaam** [comment]
if you upgrade to 4.72 it will work again :)
