### ISSUE TITLE
Inga Subs med 4.73...

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1614]
svtplay-dl -S --all-subtitles https://urplay.se/program/211371-hvarfor-skola-kvinnorna-vanta

Får inga Subs med 4.73, men med 4.69.

Man undrar varför det plötsligt blev så mycket strul när versionen kom upp i 4.7x, klart skumt ?!

**Comment by spaam** [comment]
öh de är ju spännande 🤔

**Comment by Minherre** [comment]
Inte heller funkar den här nyutlagda, att hämta med Subs, med 4.73, men med 4.69:

svtplay-dl -S --all-subtitles https://urplay.se/program/237160-nmt-dagarna-2024-var-dinosaurierna-verkligen-svarta

/Suck...

**Comment by Minherre** [comment]
Och idag funkar det inte att få Subs med 4.73 till:

svtplay-dl -S --all-subtitles https://urplay.se/program/233710-arkeologi-och-ny-teknik-kroppar-som-pratar

men med 4.69.

**Comment by Minherre** [comment]
Heller inga Subs med 4.73 till:

svtplay-dl -S --all-subtitles https://urplay.se/program/235622-1900-talets-ikoner-femton-minuter-av-berommelse

Men med 4.69 funkar det...

NÄR ska detta fixas ?!

**Comment by posktomten** [comment]
Hej, jag vill tacka för allt arbete som spaam och andra lägger ner. På sin fritid. Det brukara allt fixas när någon ändring behövs!

**Comment by spaam** [comment]
`4.79` borde detta funka igen :)
