### ISSUE TITLE
tv4play kan ej ladda enstaka avsnitt eller klipp

### ISSUE THREAD

**Issue by sebbe34-svt** [spaam/svtplay-dl#1615]
### svtplay-dl versions:
4.73 

### What is the issue:
Varför kan man inte ladda ner enstaka avsnitt på tv4play? Så har det varit en längre tid nu, och spelar inte så stor roll om man ändå vill se en hel  serie.  (man får: Use program page instead of the clip / video page. )

Men t.ex. på andra sidor (tv4 klipp) blir det större problem om man bara vill ladda ner ett enstaka klipp?

ex:
##
 svtplay-dl --verbose  https://www.tv4play.se/klipp/37de44cfc5255af8147e/video-eurovision-inleds-i-malmo-i-dag?playlist=7tvSBut3prRv6H1IOQAYLT -v
DEBUG [1714907510.5115926] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.73
DEBUG [1714907510.5138824] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
WARNING [1714907510.514213] /media/sebrin/e5129a1f-ef33-4806-b880-53771b257b85/bin/svtplay-dl/svtplay_dl/service/tv4play.py/find_all_episodes: Use program page instead of the clip / video page.

**Comment by spaam** [comment]
det funkar bra här med 4.73.  så sitter du på vpn eller?`

**Comment by spaam** [comment]
verkar som du inte berättar hela sanningen om ditt argument.  du verkar använda -A på klipp som vi slutat supportat  i 4.25.

**Comment by Umeaboy** [comment]
Behöver man inte använda en token längre?
