### ISSUE TITLE
Laddar bara ner avsnitt med teckenspråkstolk

### ISSUE THREAD

**Issue by damgdj** [spaam/svtplay-dl#1618]
Kör man 

svtplay-dl https://www.svtplay.se/video/KLapEMy/30-dagar-i-fangelse/2-den-gra-vardagen

på 4.71 så laddas inte vanliga avsnittet ner utan versionen med teckenspråkstolk laddas ner istället.

**Comment by Minherre** [comment]
Har du provat med 4.79, som är senaste ?!

https://svtplay-dl.se/

**Comment by damgdj** [comment]
> Har du provat med 4.79, som är senaste ?!
> 
> https://svtplay-dl.se/

Mitt fel! Installerade igår med Homebrew och antog att 4.71 var senaste, men var tvungen att uppdatera efter installationen ändå.

**Comment by spaam** [comment]
Ja Brew va fast på 4.71 ett tag för en miss som blev upptäckt igår av en person. Fixade de igår och brew har senaste versionen nu. Om du uppdaterar brew så kan du få in den senaste versionen 🙂
