### ISSUE TITLE
Svtplay crash KeyError: 'analyticsIdentifiers'

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#1619]
File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 338, in seasoninfo
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 350, in _find_season
KeyError: 'analyticsIdentifiers'

**Comment by nlindblo** [comment]
Same error here

**Comment by spaam** [comment]
verkar som dom flyttat om lite info om vart säsong och avsnittsnummer är.   detta kommer bli fixat ikväll :)

**Comment by sebbe34-svt** [comment]
najs! mycke avsnitt som försvinner ikväll..

**Comment by spaam** [comment]
du kan planera runt 21-22 att uppdateringen kommer  :)

**Comment by spaam** [comment]
4.83 är släppt med fix för detta 🎉

**Comment by rio32425436** [comment]
Skulle det vara möjligt att uppdatera versionen som ligger på Brew :))

Jag har försökt att installera zip-filen manuellt men får det inte att funka på min dator.

**Comment by spaam** [comment]
@rio32425436 ,  Dom har skapat en så kallad Pull Reqeust att få in uppdateringen till brew nyss.  för 4.79 tog det runt en timme från när Pull Requesten va skapad tills den fanns i brew.  :)
