### ISSUE TITLE
Hur hämta t ex BARA S01 eller BARA S02 när det finns flera Säsonger efter...

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1625]
Hur hämtar man t ex BARA S01 när det finns flera säsonger att välja på?

https://www.svtplay.se/the-bay

Man kan ju inte köra med typ

svtplay-dl -A --all-last=6

då, för då lär man få de senaste från S04 & S05...

Blir man tvungen plocka dem en o en vartefter ?!

**Comment by spaam** [comment]
Du klickar på den säsongen du vill tanka hem sedan använder den urlen du får i adressfältet  till svtplay-dl med dina argument du har nu.  tex  för `the bay`  får första säsongen denna url `https://www.svtplay.se/the-bay?tabs=season-1-e2dDB6Y`
