### ISSUE TITLE
Fungerade EJ: Du klickar på den säsongen du vill tanka hem 

### ISSUE THREAD

**Issue by Minherre** [spaam/svtplay-dl#1626]
Du skrev att:

              Du klickar på den säsongen du vill tanka hem sedan använder den urlen du får i adressfältet  till svtplay-dl med dina argument du har nu.  tex  för `the bay`  får första säsongen denna url `https://www.svtplay.se/the-bay?tabs=season-1-e2dDB6Y`

_Originally posted by @spaam in https://github.com/spaam/svtplay-dl/issues/1625#issuecomment-2197268606_
            
Men då blev det bara så här:

"svtplay-dl -S --all-subtitles https://www.svtplay.se/the-bay?tabs=season-1-e2dDB6Y
ERROR: No videos found. This mode is not supported anymore. Need the url with the video."

med 4.89.

**Comment by spaam** [comment]
"med dina argument du har nu."  vad jag ser så har du inte gjort det. i ditt exempel här https://github.com/spaam/svtplay-dl/issues/1625#issue-2380760349 så har du ` -A --all-last=6`  framför allt `-A` grejen.  iom du vill ta hem alla avsnitt av någon serie så måste man ha med  `-A`.  men här har du inte med `-A`  så blir lite problimatiskt att tanka hem alla avsnitt utan det :(

**Comment by Minherre** [comment]
Aj aj aj då, var det så det var  ....   ;-)
TACK!

Är sketstressad för Microsoft har hittat på att man måste byta ut sitt gamla hederliga Win Live Mail plötsligt, o installera deras nya Free Outlook istället, annars får man ingen mail längre efter sommaren...
Sicket skit!
