### ISSUE TITLE
Undertexter saknas för vissa länkar

### ISSUE THREAD

**Issue by rio32425436** [spaam/svtplay-dl#1629]
svtplay-dl 4.89
MacOS Sonoma

svtplay-dl 'https://www.svtplay.se/video/jABavr3/gisele-freund-portratt-av-en-banbrytande-fotograf'

Jag får inga undertexter här. Men det funkar för andra filmer/länkar.

**Comment by Minherre** [comment]
Du måste ju tala om ATT du alls VILL ha Subs...

svtplay-dl -S --all-subtitles https://www.svtplay.se/video/jABavr3/gisele-freund-portratt-av-en-banbrytande-fotograf

Den där funkar!

**Comment by rio32425436** [comment]
Tack så mycket! För de flesta länkarna kommer subs automatiskt - trodde det var samma för alla.
