### ISSUE TITLE
Får "ERROR: No videos found." på Ubuntu

### ISSUE THREAD

**Issue by ChrisIse** [spaam/svtplay-dl#1631]
### svtplay-dl versions:

4.89

### Operating system and Python version:

Ubuntu studio 22.04. Python 2.7.18

### What is the issue:

Detta funkar inte i Ubuntu. Får "ERROR: No videos found". I Windows på samma laptop går det fint.

svtplay-dl https://www.svtplay.se/video/KQrdyRX/ett-fall-for-vera/2-tender?info=visa --verbose
DEBUG [1721278930.4833372] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.89
DEBUG [1721278930.4842386] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1721278930.4843028] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/KQrdyRX/ett-fall-for-vera/2-tender?info=visa'
DEBUG [1721278930.4854183] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1721278930.8868866] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/KQrdyRX/ett-fall-for-vera/2-tender?info=visa HTTP/1.1" 200 24670
DEBUG [1721278930.9414601] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://api.svt.se/video/ePB9ZJN'
DEBUG [1721278930.9438233] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1721278931.3287628] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/ePB9ZJN HTTP/1.1" 200 1108
DEBUG [1721278931.329591] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1b.akamaized.net/d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-avc.m3u8'
DEBUG [1721278931.3308852] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): svt-vod-secure-1b.akamaized.net:443
DEBUG [1721278931.6913497] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1b.akamaized.net:443 "GET /d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-avc.m3u8 HTTP/1.1" 403 282
DEBUG [1721278931.6920705] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1b.akamaized.net/d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-lb-full.m3u8'
DEBUG [1721278931.7377212] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1b.akamaized.net:443 "GET /d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-lb-full.m3u8 HTTP/1.1" 403 282
DEBUG [1721278931.738858] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1b.akamaized.net/d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-avc.m3u8'
DEBUG [1721278931.7917876] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1b.akamaized.net:443 "GET /d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-ts-avc.m3u8 HTTP/1.1" 403 282
DEBUG [1721278931.792881] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1b.akamaized.net/d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-cmaf-full.m3u8'
DEBUG [1721278931.839974] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1b.akamaized.net:443 "GET /d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-cmaf-full.m3u8 HTTP/1.1" 403 282
DEBUG [1721278931.84107] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://svt-vod-secure-1b.akamaized.net/d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-cmaf-lb-full.m3u8'
DEBUG [1721278931.8952773] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://svt-vod-secure-1b.akamaized.net:443 "GET /d0/secure/20240619/2c6331a5-c317-4365-b6fa-baa968776e99/hls-cmaf-lb-full.m3u8 HTTP/1.1" 403 282
ERROR [1721278931.89663] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found.

**Comment by posktomten** [comment]
Hej!
Funkar för mig.
Ubuntu 22.04
Python 3.10
svtplay-dl 4.89
Det är pythonversionen som är olika.
Ingemar

**Comment by spaam** [comment]
@ChrisIse , använder du vpn eller något liknande på din *nix dator för de verkar som du försöker ta hem video?

**Comment by ChrisIse** [comment]
Nu har jag sett till att senaste python är default. Alla prerequisites är uppnådda. Jag har normalt ingen vpn, men även via en svensk vpn får jag samma resultat. 
Jag kan faktiskt inte se dem i browser heller. Testar vidare.

**Comment by spaam** [comment]
du svarade inte på frågan. använder du vpn eller inte?

många sidor blockar vpn. spelar ingen roll om det är svenskt vpn eller inte.

**Comment by ChrisIse** [comment]
Nej jag anväder inte vpn.
Men denna funkar.
svtplay-dl https://www.svtplay.se/klipp/Kn49GbX/sommar-det-har-ska-du-tanka-pa-innan-du-bokar-semesterresan?video=visa

Misstänker att det ändå är nån vpn som ligger i bakgrunden, för jag har problem med vissa andra sidor. Min connectionManager visar ingen vpn, men jag måste undersöka detta närmare. Tips?

**Comment by spaam** [comment]
den videon kan du se i hela världen. den du hade tidigare kan du bara se i sverige. 
 låter som du har något vpn i bakgrunden iaf.  hur kolla de är rätt olika beroende på vad det är för vpn leverantör.  många använder appar för att bestämma. vet att nordvpn och mullvad har det.

**Comment by ChrisIse** [comment]
Tack Johan. Jag avinstallerade openvpn, och då hoppade nedladdningen  igång. Installerade openvpn igen, och då funkade det inte, så jag får köra utan openvpn tills vidare.
Då är jag nöjd för tillfället, och sen återstår att se hur jag ska kunna ha openvpn installerat, men det är ett senare problem.
