### ISSUE TITLE
tv4play - ERROR: No videos found. You need a token to access the website. see https://svtplay-dl.se/tv4play/

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [spaam/svtplay-dl#1636]
### What is the issue:

I have gone and retrieved the token as stated on the error message, but it doesn't work. The guide doesn't specify the format, and when I go on and paste the code I get two different "ey" trings separated by a `.`, one is significantly longer than the other:

`eyJhbGciOiJFUzI1NiIsIm`

Since the website doesn't state the format, I have tried every possible combination (one, then the other, then combined, then removing things that seem off ie. the ending .IckK0_66ySb). Everything retrieves the same error message.

```
redacted@redacted-iMac ~ % svtplay-dl --verbose --token "eyJhbGciOiJFUzI1NiIsImtpZCI6IjUwMTA5NDYzLTA4OGI" https://www.tv4play.se/video/c270d22c344ad177c558/avsnitt-1
DEBUG [1723031962.032619] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 4.97.1
DEBUG [1723031962.03354] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1723031962.033602] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/c270d22c344ad177c558/avsnitt-1'
DEBUG [1723031962.039099] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1723031963.3410869] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/c270d22c344ad177c558/avsnitt-1 HTTP/1.1" 200 None
DEBUG [1723031963.809823] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://avod-auth-alb.a2d.tv/oauth/refresh'
DEBUG [1723031963.811361] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): avod-auth-alb.a2d.tv:443
DEBUG [1723031964.655469] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/urllib3/connectionpool.py/_make_request: https://avod-auth-alb.a2d.tv:443 "POST /oauth/refresh HTTP/1.1" 401 50
ERROR [1723031964.6564622] /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. You need a token to access the website. see https://svtplay-dl.se/tv4play/
redacted@redacted-iMac ~ % 
```

**Comment by spaam** [comment]
you shouldnt share your token like that.. its sensitive data.  i recomment logout from your devices and login again.

if you follow the website, you should get a looong text that starts with ey..  use that whole line in the token and it should work.  the line should be like over 400+ characters long.   they have dots (.) and underscores (_) and whole bunch of characters.

**Comment by Sopor** [comment]
I have made a video that will show you how to get the token in Chrome.

You can use it on your site if you want @spaam 

https://github.com/user-attachments/assets/37b7c714-10fb-49c8-a7f2-38c3e1bbe44d

**Comment by 2V3EvG4LMJFdRe** [comment]
Thanks to both of you. The video helped a lot, maybe it could be added to the main guide since a lot of people seem to stumble on this step. It works now!
