### ISSUE TITLE
Hämta token för tv4play.se

### ISSUE THREAD

**Issue by Johan739** [spaam/svtplay-dl#1642]
Jag kan inte hämta en token för att få tv4play att funka. Står bara undefined efter att jag kör enligt instruktionen. Vad gör jag för fel? Hur gör jag?

**Comment by spaam** [comment]
vad är de för fel du får? 🤔

**Comment by Johan739** [comment]
Jag tycker jag följer instruktionen på https://svtplay-dl.se/tv4play/.  Men får inte fram nån token text "ey..." utan det står bara undefined. 
![image](https://github.com/user-attachments/assets/ca348379-07d5-4c50-b6e7-44e874d5836f)

**Comment by spaam** [comment]
har du loggat in på tv4play? 🤔

**Comment by Johan739** [comment]
Nä, det hade jag inte och nu funkar det! Danke..

**Comment by spaam** [comment]
woho bra jobbat :D ibland är de enkelt o missa vissa grejer :D
