### ISSUE TITLE
tv4play problem med "token"

### ISSUE THREAD

**Issue by hamkg** [spaam/svtplay-dl#1643]
svtplay-dl-4.97.1, linux, python-3.11

Drabbades idag av token-problemet på tv4play. Hämtade enligt instruktionerna en token:

```
> document.cookie
  .split("; ")
  .find((row) => row.startsWith("tv4-refresh-token="))
  ?.split("=")[1]; 
< 'eyJhbGciOiJFUzI1NiIsImtpZCI6IjQ4Yzg0ZDVhLTk1YWEtNDhmYi1hZDM1LWU1NmZjNWMwYTczZCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0djQiLCJleHAiOjE3NTA3NzAzMzcsImlhdCI6MTcxOTIzNDMzNywiaX.
```

Den skiljer sig en aning från min gamla token som jag hade i ~/.svtplay-dl.yaml så jag ersatte den:

```
service:
  tv4play:
    token: "eyJhbGciOiJFUzI1NiIsImtpZCI6IjQ4Yzg0ZDVhLTk1YWEtNDhmYi1hZDM1LWU1NmZjNWMwYTczZCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0djQiLCJleHAiOjE3NTA3NzAzMzcsImlhdCI6MTcxOTIzNDMzNywiaX"
```
men fortfarande får jag felmeddelandet
`ERROR: No videos found. You need a token to access the website. see https://svtplay-dl.se/tv4play/

Lite förvirrande är att det tycks finnas två token-textsträngar: dels den som jag ser i konsolen som jag kan markera och kopiera med ctrl+C och dels en mycket längre som jag kan kopiera om jag markerar den genom att klicka tre gånger och sedan ctrl+C - den ser ut så här:

eyJhbGciOiJFUzI1NiIsImtpZCI6IjQ4Yzg0ZDVhLTk1YWEtNDhmYi1hZDM1LWU1NmZjNWMwYTczZCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0djQiLCJleHAiOjE3NTA3NzAzMzcsImlhdCI6MTcxOTIzNDMzNywiaXNzIjoiaHR0cHM6Ly9hdm9kLWF1dGgtYWxiLmEyZC50diIsImp0aSI6IjJ2ZHY1MWFkZm9tYmU0cnI3bzAyYnE0MiIsIm5iZiI6MTcxOTIzNDMzNywic2Vzc2lvbl9pZCI6ImF2b2RfNzliYzIwNDMtNmIxZS00NjViLThiY2QtZTViZjhiZDMzYTA0IiwidHlwZSI6InJlZnJlc2giLCJ1aWQiOiIzNjcxNDgxNyJ9.5…

Har prövat både den långa och den korta, ingen skillnad.

Fundersam över att del långa strängen slutar med tre punkter (NDgxNyJ9.5…), som om inte allt kommer med när jag kopierar?

**Comment by Sopor** [comment]
För det första, dela inte ut din token då andra kan använda den.

Börja med att logga ut och in igen på TV4Play så du får en ny token.

Du kan följa videon jag gjorde [här](https://github.com/spaam/svtplay-dl/issues/1636#issuecomment-2273692026)

**Comment by hamkg** [comment]
Hej och tack,

jag gjorde ett nytt försök att hämta en token, nu i firefox (tidigare i chromium). Nu fick jag en fullständig sträng, utan de tre avslutande punkterna. Så tydligen har chromium problem med att få med hela strängen.

Klistrade in nya token i config-filen och nu funkar det fint, så jag stänger tråden.

**Comment by spaam** [comment]
Konstigt funkade i chrome nu. aja gött de blev fixat iaf : )
