### ISSUE TITLE
Välja bara "caption" text på svtplay?

### ISSUE THREAD

**Issue by nappen5** [spaam/svtplay-dl#1663]
### svtplay-dl versions:

Run `svtplay-dl --version`

### Operating system and Python version:

Name and version of the operating system and python version (run `python --version`)

### What is the issue: Jag vill bara ha "caption" texten, hur gör jag?

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)https://www.svtplay.se/video/ePvV5k3/granslost-fiske/avsnitt-1?video=visa

    svtplay-dl --verbose https://www.example.com

**Comment by spaam** [comment]
det går inte att välja ena eller den andra. dock kan du använda `--all-subtitles` . om du redan har tagit hem videon så kan du använda `--force-subtitle --all-subtitles` för att ta hem bara subs.  du vill ha den med `sv-caption` i namnet.

**Comment by nappen5** [comment]
Det var alltså enklare att åka till månen för 55 år sedan än att välja en undertext 2024?

**Comment by spaam** [comment]
Om du tycker de är så enkelt så får du gärna komma med en fix till det.

**Comment by nappen5** [comment]
Jag säger inte att det är enkelt, men att det troligtvis går att lösa... Själv är jag en glad amatör på detta, och tacksam för alla som delar sin kunskap. tummen upp till er alla.
