### ISSUE TITLE
How to prevent downloading "syntolkat" and "teckenspråkstolkat" when using -A?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#190]
When i use -A on SVTPlay i will get all episodes, even the "syntolkat" and "teckenspråkstolkat". Is it possible to prevent this to happen? Some kind of filter? The word "syntolkat" is included in the file name so it must be possible to detect it:

```
julkalendern-piratskattens-hemlighet-och-alla-dagar-fram-till-jul-avsnitt-13-2537988-svtplay.ts
julkalendern-piratskattens-hemlighet-och-alla-dagar-fram-till-jul-avsnitt-13-syntolkat-2540950-svtplay.ts
julkalendern-piratskattens-hemlighet-och-alla-dagar-fram-till-jul-avsnitt-13-teckensprakstolkat-2538938-svtplay.ts
```

**Comment by Sopor-** [comment]
I still get "ERROR: Can't find any streams for that url" on excluded episodes. Did you forget to change that message?

**Comment by spaam** [comment]
No. i will do that later. not today

**Comment by spaam** [comment]
made a new ticket about it  #198
