### ISSUE TITLE
Make it possible to not show "File already exists" errors...

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#197]
When i run my script i get a lot of file already exists info/error. I then tried -s for silent but that did the opposite, it only show me the errors :(
ERROR: File already exists. Use --force to overwrite
ERROR: File already exists. Use --force to overwrite
ERROR: File already exists. Use --force to overwrite
ERROR: File already exists. Use --force to overwrite

Is it possible to add a switch that will make all the ERROR about file already exists not visible and only show info when it download an episode?
INFO: Episode 1 of 4
INFO: Outfile: extrema.ogonblick.s01e01.avsnitt.1-2523327-svtplay.srt
ERROR: File already exists. Use --force to overwrite
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: extrema.ogonblick.s01e01.avsnitt.1-2523327-svtplay.ts
ERROR: File already exists. Use --force to overwrite
INFO: Episode 2 of 4
INFO: Outfile: extrema.ogonblick.s01e02.avsnitt.2-2526389-svtplay.srt
ERROR: File already exists. Use --force to overwrite
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: extrema.ogonblick.s01e02.avsnitt.2-2526389-svtplay.ts
ERROR: File already exists. Use --force to overwrite
INFO: Episode 3 of 4
INFO: Outfile: extrema.ogonblick.s01e03.avsnitt.3-2558785-svtplay.srt
ERROR: File already exists. Use --force to overwrite
INFO: Selected to download hls, bitrate: 2794
INFO: Outfile: extrema.ogonblick.s01e03.avsnitt.3-2558785-svtplay.ts
ERROR: File already exists. Use --force to overwrite
INFO: Episode 4 of 4
INFO: Outfile: extrema.ogonblick.s01e04.avsnitt.4-2569760-svtplay.srt
ERROR: File already exists. Use --force to overwrite
INFO: Selected to download hls, bitrate: 2794
INFO: Outfile: extrema.ogonblick.s01e04.avsnitt.4-2569760-svtplay.ts
ERROR: File already exists. Use --force to overwrite

It should of course be an option so users that want to see all the errors still can see them.

**Comment by spaam** [comment]
oh forgot.  you should have -s added to the arguments. svtplay-dl -s supersite.se/video/3232233223 2> /dev/null

**Comment by Sopor-** [comment]
I believe you misunderstood me... I still want to see the progress bar when i download. I only wanted to hide the 'file already exists' message.
