### ISSUE TITLE
if the subtitle exists i get 'file already exists' when trying to download the video

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#199]
If i have download the subtitle before i download the video file i get this message:
svtplay-dl http://www.svtplay.se/jesper-ronndahl-hej-framtiden
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: jesper.ronndahl.hej.framtiden.jesper.ronndahl.hej.framtiden-2573986-svtplay.ts
ERROR: File already exists. Use --force to overwrite

and this is the file i have in the folder
jesper.ronndahl.hej.framtiden.jesper.ronndahl.hej.framtiden-2573986-svtplay.srt

**Comment by Sopor-** [comment]
I'll update this.
I can't use -S anymore because when the subtitle is downloaded it will be 'file already exists' on the video file.

**Comment by spaam** [comment]
master got a fix for this :)

**Comment by agent666** [comment]
I still get this error on the last version of master...

**Comment by spaam** [comment]
@agent666 for what site?

**Comment by agent666** [comment]
2 av 2 som jag testat har felat...

Både från svt och tv3

**Comment by Sopor-** [comment]
It is working for me:
python svtplay-dl -S http://www.svtplay.se/video/2600148/embryo
INFO: Outfile: kortfilm.i.svt.embryo-2600148-svtplay.srt
ERROR: File already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 2796
INFO: Outfile: kortfilm.i.svt.embryo-2600148-svtplay.ts
[20/83][==========...................................] ETA: 0:00:19
