### ISSUE TITLE
Viasatsport

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#200]
Is it possible to add support for viasatsport?

**Comment by spaam** [comment]
maybe but i think they are using silverlight and their DRM. but i can look at it later.

**Comment by MR-2** [comment]
To my current knowledge there shouldn't be any issues with silverlight or DRM for this service. HLS exists and have seven different layers (bitrates available).

**Comment by spaam** [comment]
looking at some VODs. it looks pretty easy to fix.
