### ISSUE TITLE
Barnkanalen - Can only download one video on the page

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#201]
If i want to download from this page i only get one of the videos
svtplay-dl http://www.svt.se/barnkanalen/bacillakuten/
INFO: Selected to download hls, bitrate: 2887
INFO: Outfile: bacillakuten.pa.sondag.smaller.det!-2586982-svtplay.ts

How do i download the other ones on the page?

Could it be possible to add support for "debug text" that i can get on every video?
```
statisticsUrl : http://ld.svt.se/svt/svt/s?svt-play.barn.bacillakuten.klipp.l%C3%A4r-k%C3%A4nna-petter
```
or
```
VideoUtil.parseFullURL() http://svtklipp4a-vh.akamaihd.net/z/fritt/open/20141208/K-20141208-151540-1698/BK-2014-1208-BA-dd0026dd89b3d814_,892,144,252,360,468,1584,2700,.mp4.csmil/manifest.f4m,162,162::
```
or
```
AkamaiGenericVideo::load() ,http://svtklipp4a-vh.akamaihd.net/z/fritt/open/20141208/K-20141208-151540-1698/BK-2014-1208-BA-dd0026dd89b3d814_,892,144,252,360,468,1584,2700,.mp4.csmil/manifest.f4m,82,0,0
```
:question:

**Comment by spaam** [comment]
this is a known limitation with the script, we only get the first video we see on the page.
one workaround is try find the page for each video and then feed the url to the script.

**Comment by Sopor-** [comment]
But is it hard to add support for the "debug text"? All videos have that on SVT so if i get one of those i use that to download. I understand that it has limitations but at least i can download it :)

**Comment by spaam** [comment]
we have some "debug text" -v.  the thing you asking for, i need to rewrite some parts of the code to handle more then one video per page to get that "debug text".

**Comment by Sopor-** [comment]
Not that text. If you use the right mouse button on the black bottom bar you can copy "debug text" from the video and it should be easy to use svtplay-dl to download with

**Comment by Sopor-** [comment]
Before there was any program to download with i used that info to download videos from SVT. Now they use encrypted and dynamic streams so now i let the professionals do the job :)
But it must be easy to add support for the URL's you get when you copy the "debuginformation"? Then you know exactly the movie i want to download. Even if i have to paste the text in a text editor, find the URL, copy that URL and use it to download the video with svtplay-dl.

**Comment by spaam** [comment]
ahh now I'm on the same page :D 
yeah. i have thought about that. shouldn't be that hard to fix.
for example: svtplay-dl "http://svtklipp4a-vh.akamaihd.net/z/fritt/open/20150108/K-20150108-111033-2469/BK-2015-0108-BA-2d1993e9be4af996_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m,17,0,0" it will download the HDS stream.
i think i have something similar for html5 video in a branch.

**Comment by Sopor-** [comment]
I did try this but that did not work
```
svtplay-dl http://svtklipp4a-vh.akamaihd.net/z/fritt/open/20141208/K-20141208-151540-1698/BK-2014-1208-BA-dd0026dd89b3d814_,892,144,252,360,468,1584,2700,.mp4.csmil/manifest.f4m,82,0,0
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.10.2015.01.05', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.01.05-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.01.05-py2.7.egg/svtplay_dl/__init__.py", line 268, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.10.2015.01.05-py2.7.egg/svtplay_dl/__init__.py", line 73, in get_media
    url, stream = Generic().get(url)
TypeError: 'NoneType' object is not iterable
```

**Comment by spaam** [comment]
Nice traceback..
anyway. one issue if we get files like that is the filename. it will be some "random filename". like BK-2014-1208-BA-dd0026dd89b3d814_,892,144,252,360,468,1584,2700,.mp4

**Comment by Sopor-** [comment]
I can at least download it, better than nothing :)

**Comment by Sopor-** [comment]
I was trying to download using this new feature, but i seems to do something wrong:
```
python svtplay-dl http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-1324082247/BK2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 270, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 73, in get_media
TypeError: 'NoneType' object is not iterable
```
What url should i use from the "debuginformation"?

**Comment by spaam** [comment]
you should give the whole url with manifest.f4m in it.  not some parts of it. :D

**Comment by spaam** [comment]
for example http://svtplay13o-f.akamaihd.net/z/world/open/20150114/1361537-008A/EPISOD-1361537-008A-7b15c09d3a4b0db3_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m   or http://svtplay13o-f.akamaihd.net/z/world/open/20150114/1361537-008A/EPISOD-1361537-008A-7b15c09d3a4b0db3_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m,3450,0,0  or http://svtplay13o-f.akamaihd.net/i/world/open/20150114/1361537-008A/EPISOD-1361537-008A-7b15c09d3a4b0db3_,892,144,252,360,540,1584,2700,.mp4.csmil/master.m3u8?cc1=name=Svenska~default=yes~forced=no~uri=http://media.svt.se/download/mcc/wp3/undertexter-wsrt/1361537/1361537-008A/C(sv)/index.m3u8~lang=sv    

we need that manifest.f4m or master.m3u8 in the url

**Comment by Sopor-** [comment]
I tried http://svtplay13o-f.akamaihd.net/z/world/open/20150114/1361537-008A/EPISOD-1361537-008A-7b15c09d3a4b0db3_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m but it will still not work :(

**Comment by spaam** [comment]
are you using master or stable version?

**Comment by Sopor-** [comment]
master

**Comment by Sopor-** [comment]
It seems to work in Linux, but not Windows.

**Comment by spaam** [comment]
what does svtplay-dl -v url   say ? :D

**Comment by Sopor-** [comment]
This is Windows:
```
python svtplay-dl -v http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-132408-2247/BK-2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m
DEBUG [1421681533.93] svtplay-dl\svtplay_dl\utils\__init__.py/get_http_data: HTTP getting 'http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-132408-2247/BK-2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m?&hdcore=3.3.0'
DEBUG [1421681534.2] svtplay-dl\svtplay_dl\utils\__init__.py/get_http_data: HTTP got 5615 bytes from 'http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-132408-2247/BK-2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m?&hdcore=3.3.0' in 0.26s (= 169509bps)
DEBUG [1421681534.2] svtplay-dl\svtplay_dl\utils\__init__.py/get_http_data: HTTP getting 'http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-132408-2247/BK-2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m?&hdcore=3.3.0'
DEBUG [1421681534.21] svtplay-dl\svtplay_dl\utils\__init__.py/get_http_data: HTTP got 5615 bytes from 'http://svtklipp-f.akamaihd.net/z/fritt/open/20150107/K-20150107-132408-2247/BK-2015-0107-BA-0a75658650be26b5_,892,144,252,360,540,1584,2700,.mp4.csmil/manifest.f4m?&hdcore=3.3.0' in 0.02s (= 2807494bps)
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 270, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 111, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 136, in get_one_media
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by spaam** [comment]
i get the problem too. i will push a fix for it tomorrow
