### ISSUE TITLE
Implement download from hbonordic.com/

### ISSUE THREAD

**Issue by more10** [spaam/svtplay-dl#203]
My connections is so slow I cannot watch this site in real time. I guess it is really difficult to do but....

**Comment by spaam** [comment]
They use something called widewine as DRM and i have no idea how to remove it.

**Comment by Sopor-** [comment]
Google have bought up Widevine and more and more sites have started to use this. Probably will all Youtube videos use this in the future to prevent downloading. For now i haven't seen any way to override widevine.
