### ISSUE TITLE
TV3 Play returns 404

### ISSUE THREAD

**Issue by Kottalizer** [spaam/svtplay-dl#204]
It appears certain URLs that are perfectly valid in a web browser return 404 when used through svtplay-dl. I have successfully used wget and manually download the same URL, using the same User Agent.

martin@futurum:~/Videos$ svtplay-dl "http://www.tv3play.se/program/morden-i-midsomer--2"
ERROR: Something wrong with that url
ERROR: Error code: 404

This is the User Agent I used when succeeding with wget:
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.9.0.3) Gecko/2008092417 Firefox/3.0.3

Using svtplay-get version 0.9.2014.04.27.

**Comment by Kottalizer** [comment]
It looks like I indirectly resolved my own issue. Very silly of me – TV3 Play works just fine with the latest released version, 0.10.2015.01.05. Closing issue.

**Comment by spaam** [comment]
user fixing their own problems \o/
