### ISSUE TITLE
SVTPlay - download will freeze and ctrl+c won't work to break

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#205]
This is a friend of mine (the user i mention in issue #196). He have a lot of problem when downloading from SVT and when it stops it seems to freeze and it will not continue again. He can't even break it with CTRL+C. I can use CTRL+C but that is when it download as it should. I have seen this problems a few times by my self but for me it will start again even if it goes very slow to download.
I don't know how to reproduce it, maybe it will work if i pull out the network cable?
He is running Windows 7.

So why doesn't ctrl+c work?

**Comment by spaam** [comment]
sounds strange.  what os? what python --version ?

**Comment by Sopor-** [comment]
Windows 7 64-bit and Python 2.7.8.

**Comment by Sopor-** [comment]
I can confirm this. I did some test and if i have a download running and lost connection and i press CTRL+C nothing happens. It will not break until i get the connection back. I was running Windows 8.1 with Python 2.7.9 in Vmware.

**Comment by Sopor-** [comment]
Update: If i download and disconnect, press CTRL+C and re-connect internet after 1 minute it takes about 20 seconds for svtplay-dl to exit. So if you lost connection CTRL+C won't work.

**Comment by spaam** [comment]
master with requests should fix this
