### ISSUE TITLE
SVTPlay - can't download "Kompisar på nätet"

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#206]
When trying to download http://www.svtplay.se/kompisar-pa-natet i get a message from svtplay-dl that this is DRM protected. They seems to be F4M streams. Are all those DRM protected?

**Comment by spaam** [comment]
f4m is a playlist-ish.  it contain some info about where to find some other video streams. 
but in this case the video is encrypted with something called FlashAccess. i have no idea how to decrypt it.

**Comment by Sopor-** [comment]
More and more streams seems to be encrypted :(
