### ISSUE TITLE
ERROR: Can't play this because the video is either not found or geoblocked.

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#207]
I don't know if you also should add that the video is only for payed user?
http://www.tv3play.se/program/mordet/542679

Why does it say 'Can't play...' when i'm trying to download it? 'Can't download...' sounds more correct :)

**Comment by spaam** [comment]
you need to login to Facebook to see it..

**Comment by Sopor-** [comment]
So it's not for payed user, you only need to be logged in on Facebook to see it...
