### ISSUE TITLE
How to install latest version?

### ISSUE THREAD

**Issue by fezaland** [spaam/svtplay-dl#208]
Hello. Trying to install latest version of svtplay-dl with no success. I know almost nothing about commands in the terminal, but usually I manage with a little guidance... When I try to install with brew install I get the old version (0.9.2014.08.28).
The reason for trying the newer version is that tv3play.se doesn't work at all. With every program url I get the same error:
ERROR: Something wrong with that url
ERROR: Error code: 404
So, two questions: Will the new version sove this, and, how do I install it?

**Comment by spaam** [comment]
it seems that they didn't upgrade their version to the latest one.
you can do this to get the latest version. get the svtplay-dl file in the repo. then put the file in /usr/local/bin 
for example from the terminal:
cp ~/Downloads/svtplay-dl /usr/local/bin/   
chmod +x /usr/local/bin/svtplay-dl

**Comment by fezaland** [comment]
I have the file in my Downloads folder, but
cp ~/Downloads/svtplay-dl /usr/local/bin/
will not copy it to /usr/local/bin.
What does "chmod +x /usr/local/bin/svtplay-dl" do?

By the way, my old version is placed in /usr/local/Cellar/svtplay-dl/0.9.2014.08.28/bin

I am a mess :(

**Comment by fezaland** [comment]
Forget above for a moment, just saw that svtplay-dl version is now changed to "0.10.2015.01.05"
Will try it and come back

**Comment by spaam** [comment]
great :) chmod +x makes the file executable. so you can run it without using python infront of the script name.

**Comment by fezaland** [comment]
Seems to work..:)
Thanks a lot!

**Comment by spaam** [comment]
np :)

**Comment by spaam** [comment]
it is nice to run: brew update   after that brew upgrade  to get newer versions :)
