### ISSUE TITLE
Feature: x-forwarded-for (was: AttributeError: 'NoneType' object has no attribute 'keys')

### ISSUE THREAD

**Issue by quite** [spaam/svtplay-dl#209]
Getting this on a server that I don't administer. Could it be some dependency missing? python2.7 is 2.7.3. Same error with 2.6.6

python2.7 ./svtplay-dl  http://www.svtplay.se/...
ERROR: Cant get manifest file
ERROR: Cant get hls playlist
Traceback (most recent call last):
  File "/package/host/localhost/python-2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/package/host/localhost/python-2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/quite/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/home/quite/bin/svtplay-dl/svtplay_dl/__init__.py", line 332, in main
  File "/home/quite/bin/svtplay-dl/svtplay_dl/__init__.py", line 173, in get_media
  File "/home/quite/bin/svtplay-dl/svtplay_dl/__init__.py", line 204, in get_one_media
  File "/home/quite/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 82, in get
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by spaam** [comment]
on what video did you get that?

**Comment by quite** [comment]
http://www.svtplay.se/video/2641661/natt-over-berlin/natt-over-berlin-avsnitt-1

**Comment by Sopor-** [comment]
It's working for me
python svtplay-dl http://www.svtplay.se/video/2641661/natt-over-berlin/natt-over-berlin-avsnitt-1
INFO: Selected to download hls, bitrate: 2793
INFO: Outfile: langfilm.i.svt.natt.over.berlin-2641661-svtplay.ts
[024/678][=............................................] ETA: 0:03:33

**Comment by spaam** [comment]
This only happen when you are outside of Sweden. Master have fix for this

**Comment by Sopor-** [comment]
I couldn't read that he was outside of Sweden so i didn't know that, but now i do :)

**Comment by spaam** [comment]
I was at fosdem in brussels at the time and i got the same problem:)

**Comment by quite** [comment]
Oh ah, forgot to mention that it was working on a another machine.. Right, thanks for the fix

**Comment by gentlebear76** [comment]
Hi. Sorry to reopen this but I was wandering what the fix is. I'm trying to run it from Denmark towards SVTPlay and getting the same "Can't get manifest file..." Tried it both through a VPN-connection and without. I can get video from Danish TV so it is working, just not as I would like it to :-)

**Comment by gentlebear76** [comment]
Nevermind, I figured it out :-) Hacked an x-forwarded-for value into the header in lib/svtplay_dl/utils/__init__.py. Simply added another parameter to the standard_header variable in line 64 as follows: ,     standard_header = {'Referer': referer, 'User-Agent': useragent, 'X-FORWARDED-FOR': x_forward} with the x_forward variable set to a relevant IP :-)

**Comment by olof** [comment]
@gentlebear76 In what circumstances is that necessary? Only when you are outside of Sweden and want to access geo restricted content? What kind of ip address do you use for the X-Forwarded-for? A swedish IP address? I'm interested in case there is anything we can do within svtplay-dl to simplify for that use case. :-)

**Comment by gentlebear76** [comment]
I'm in Denmark at present and tried accessing a restricted program. Tried it through my VPN first but that didn't work. Adding the "x-forwarded-for" fixed it. Took a while to figure out what code to fiddle with ;-) Any swedish IP will work. Great program you've made :-)

**Comment by Sopor-** [comment]
It would be great if you could add "x-forwarded-for" to svtplay-dl. You can check out XOT, Bas have now added support for it https://bitbucket.org/basrieter/xbmc-online-tv-nightly
For the IP address you can use SVTPlay if you like 194.15.212.134 :)

**Comment by demioz** [comment]
I have modified "lib/svtplay_dl/utils/__init__.py" with this code that I hope it is correct:

    x_forward='160.68.205.231'
    standard_header = {'Referer': referer, 'User-Agent': useragent, 'X-FORWARDED-FOR': x_forward}

what do I do then?

I tried "setup build" & "setup install" but I still get same error when downloading geoblocked content from NRK. Im a python-noob running on Windows.

I know the ip works watching videos from NRK with chrome+modify headers plugin.

**Comment by spaam** [comment]
if you  are on *nix. you can just run make.  but on windows. that is a good question.  python setup.py install  might work.  

but I'm working on something right now to be able to set this kind of things from the command line pretty easy. i hope i can get it done this week.

**Comment by demioz** [comment]
That would be great.

**Comment by spaam** [comment]
next version going to have support for this feature

the argument going to be: --http-header "header1=value;header2=value"

ex: --http-header "X-FORWARDED-FOR=127.0.0.1"
