### ISSUE TITLE
Download suddenly stops

### ISSUE THREAD

**Issue by sound214** [spaam/svtplay-dl#212]
99 % of all downloads from SVT Play stops randomly at any percentage. I can press ctrl+c and try again, and eventually succeed. It all seems very random. I'm running OS X 10.10.3.

**Comment by Sopor-** [comment]
@sound214 Comhem?

**Comment by sound214** [comment]
Why, yes! How did you know?

**Comment by Sopor-** [comment]
I guessed because i know others with similar issues and they all use Com hem. The downloads will freeze when they download from SVTPlay.

**Comment by Sopor-** [comment]
@sound214 For about 2 weeks ago 'Com hem' released a new firmware for the CH7284E modem and they have updated it to firmware 5.510.5.4a and now it seems to work much better. Maybe you could check your firmware?

**Comment by sound214** [comment]
I have the CG3700EMR model, which they haven't released a new firmware for, as far as I can tell.

**Comment by spaam** [comment]
strange. how do you download the video? just svtplay-dl url  and later you watch the video?

**Comment by sound214** [comment]
Exactly. 

svtplay-dl robin$ svtplay-dl http://www.svtplay.se/video/2329669/babel/avsnitt-16
INFO: Selected to download hls, bitrate: 2794
INFO: Outfile: babel.s01e16.avsnitt.16-2329669-svtplay.ts
[035/350][==========...........................................................................................] ETA: 0:03:23

Seems to work fine for a bit, then both the "counter" and the ETA just stops

**Comment by Sopor-** [comment]
@sound214 I don't know if you are using Kodi but the same users having problems with svtplay-dl also have problems with XOT (add-on for Kodi). If it works with XOT then you can at least view the programs :)

**Comment by dentarg** [comment]
Same as #244?

**Comment by spaam** [comment]
next version should fix this.
