### ISSUE TITLE
svtplay-dl returns burnt-in subtitles for UR.se

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#213]
When downloading any video from UR Play (Utbildningsradion) that have optional subtitles, the video returned will have burnt-in (hardcoded) subtitles, even though the subtitles are optional and can be turned off on the actual site.

You will get a separate .SRT file with the subtitles as well, but the actual video will also have the same subtitles hardcoded.

Two examples of videos that this issue is present on (but it seems to be the same problem on any video on UR.se which offers any form of subtitles):
http://www.ur.se/Produkter/186877-Roda-torgets-limousiner (Swedish subtitles)
http://www.ur.se/Produkter/172011-Holly-s-Heroes-A-whole-new-ball-game (English subtitles)

What is the reason for this, and can something be done about it?

**Comment by Sopor-** [comment]
When i download Holly's Heroes i get those two files:
holly's-heroes-a-whole-new-ball-game-ur.se
holly's-heroes-a-whole-new-ball-game-ur.srt
So somethings is wrong, it should not end with .se and it would be great if you could remove the ' sign too.
I also notice it was hardcoded subtitles but on ur.se i can turn them off

**Comment by dhofverberg** [comment]
Indeed, the file extensions when downloading from UR.se is way off as well, and seems to always resort to .se. Based on the actual file format, I believe it should be .TS instead.
