### ISSUE TITLE
Kanal 5 - Videon inte tillgänglig i appen?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#215]
I got this message "ERROR: Videon inte tillgänglig i appen" when i was downloading "Nya Arga Snickarn". http://www.kanal5play.se/program/3060212363/video/3267262042
Is this from svtplay-dl or Kanal 5? It was also downloading with rtmpdump and it was a flv file :(

**Comment by spaam** [comment]
its from the site when we try to access hls data..
