### ISSUE TITLE
SVTPlay - will svtplay-dl work with the new layout?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#216]
Will the new layout change anything for svtplay-dl? They seems to have removed the broad cast date.

**Comment by spaam** [comment]
Nope. it still works like it should.

**Comment by Sopor-** [comment]
I get ERROR: Couldn't retrieve episode list on several programs:
http://www.svtplay.se/grantchester
http://www.svtplay.se/i-ondskans-spar
http://www.svtplay.se/veckans-brott

**Comment by spaam** [comment]
always nice to have urls to something that is broken.

**Comment by spaam** [comment]
but there is no video on those urls so it work like it should.

**Comment by Sopor-** [comment]
It seems to work if i do like this instead but that will use the old layout
svtplay-dl -A http://www.svtplay.se/video/2705485/i-ondskans-spar/i-ondskans-spar-avsnitt-4
this will not work anymore
svtplay-dl -A http://www.svtplay.se/i-ondskans-spar

**Comment by Sopor-** [comment]
So now i need to take the first episode from every program and use that together with -A? But if that episode disappear i need to find another episode again :(

**Comment by Sopor-** [comment]
And why do you say those URL are broken? I can download with:
svtplay-dl http://www.svtplay.se/arne-dahl
but i can't use -A as before

**Comment by spaam** [comment]
using -A we are looking for rss info where we can find the info. but i guess we need to fix it in some other way

**Comment by Sopor-** [comment]
I don't understand why SVT have change it like that? It's much harder to navigate because i need to scroll down to see the episodes... and why then change it back to the old layout when i run an episode? It makes no sense...

**Comment by Sopor-** [comment]
Hmm, now i get FLV files instead of TS:
Outfile: langfilm.i.svt.mannen.som.alskade.yngve-2114167-svtplay.flv
Is this correct?

**Comment by spaam** [comment]
its a file so i guess? no? maybe it got higher bitrate then the .ts file ? what does --list-quality say?

**Comment by spaam** [comment]
it will choose the one with higher highest bitrate if you don't specify what you want.  if HDS have higher. it will get that one. if HLS is higher it will get that one. if you want highest HLS maybe you should use -P hls instead of not using it.

**Comment by Sopor-** [comment]
INFO: Quality   Method
INFO: 2793      HLS
INFO: 2793      HDS
INFO: 1677      HLS
INFO: 1677      HDS
INFO: 985       HLS
INFO: 985       HDS
INFO: 633       HLS
INFO: 633       HDS
INFO: 453       HLS
INFO: 453       HDS
INFO: 345       HLS
INFO: 345       HDS
INFO: 237       HLS
INFO: 237       HDS

**Comment by Sopor-** [comment]
Hmm, it's only "Långfilm i SVT" that will download the FLV file. If i add '-P hls' it will download the TS file. So why will it only download the FLV for  "Långfilm i SVT"  and not the other programs?

**Comment by Sopor-** [comment]
The FLV file is smaller in file size, slower to startup and i can't see any bitrate when i open properties. The TS file is fast to startup and i can see the bitrate 2,89 Mbps.

**Comment by Sopor-** [comment]
Sorry, my bad...
