### ISSUE TITLE
Support for Sydsvenskan seems to be broken

### ISSUE THREAD

**Issue by olof** [spaam/svtplay-dl#217]
$ svtplay-dl -v http://www.sydsvenskan.se/lund/sa-har-kissar-vi-i-bloja-i-rymden/
    DEBUG .../svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.sydsvenskan.se/lund/sa-har-kissar-vi-i-bloja-i-rymden/'
    DEBUG .../svtplay_dl/utils/__init__.py/get_http_data: HTTP got 280355 bytes from 'http://www.sydsvenskan.se/lund/sa-har-kissar-vi-i-bloja-i-rymden/' in 4.88s (= 459166bps)
    ERROR .../svtplay_dl/service/qbrick.py/get: Can't find video file

Same thing is true for at least some other videos as well.

**Comment by Sopor-** [comment]
Is it possible to download even if the video have playback restriction?

**Comment by spaam** [comment]
the issue here is that sydsvenskan started to use youtube for their stuff.
