### ISSUE TITLE
Aftonbladet TV - I don't know if have been working before?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#220]
When i try to download from Aftonbladet TV i only get this error:
```
svtplay-dl http://tv.aftonbladet.se/abtv/articles/68818
ERROR: Can't find video info
ERROR: Can't find any streams for that url
```
As i wrote in the title i'm not sure it have worked before. It seems to be a beta site, but i'm not sure...

**Comment by spaam** [comment]
master have support for it

**Comment by spaam** [comment]
going to release a new version later today
