### ISSUE TITLE
Upgrade svtplay-dl

### ISSUE THREAD

**Issue by ilbaritone** [spaam/svtplay-dl#222]
How do I upgrade to the latest version of svtplay-dl on OS X?
I have installed it with homebrew.

**Comment by spaam** [comment]
it should be brew update and then brew upgrade. but that will only update to released versions.

**Comment by spaam** [comment]
latest brew for today have the newest version. so brew update then brew upgrade  and you will get the update.

**Comment by ilbaritone** [comment]
Thank you!
