### ISSUE TITLE
error: Your local changes to the following files would be overwritten by merge

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#223]
Now when i do 'pull' i get this message:
error: Your local changes to the following files would be overwritten by merge:
        svtplay-dl
Please, commit your changes or stash them before you can merge.
Aborting
It's easy to fix with  'git reset --hard' but why do i get it? I haven't made anything with the files.

**Comment by spaam** [comment]
the reason is that you updated the svtplay-dl binary using make. you need to checkout the original version of it with:
git checkout svtplay-dl
after that you can pull. this is one of the reasons i need to fix #89
