### ISSUE TITLE
TV4Play - Subtitles only shows "&nbsp;"

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#225]
When i was downloading with http://www.tv4play.se/program/familjen-annorlunda?video_id=3079470 with subtitles it will look like this:
1
00:00:00,00 --> 00:00:02,76
Teamwork!
2
00:00:05,76 --> 00:00:05,92
&nbsp;
3
00:00:11,76 --> 00:00:11,92
&nbsp;
4
00:00:13,72 --> 00:00:13,88
&nbsp;
5
00:00:17,24 --> 00:00:17,40
&nbsp; 

I have watch it on TV4Play and there i have working subtitle. It only seems to be this episode for now but something seems to be wrong.

**Comment by spaam** [comment]
its a feature! :)
