### ISSUE TITLE
SVTPlay - '--exclude' did not exclude any files

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#228]
I was using --exclude because i don't want to download syntolkat but today it downloaded those files  anyway. This is what i did:
```
svtplay-dl -S -A http://www.svtplay.se/jordskott --exclude=syntolkat
```
and it downloaded all these files:
jordskott.s01e06.sasong.1.avsnitt.6.1-2771862-svtplay.ts
jordskott.s01e05.sasong.1.avsnitt.5-2750645-svtplay.ts
jordskott.s01e04.sasong.1.avsnitt.4-2720008-svtplay.ts
jordskott.s01e03.sasong.1.avsnitt.3.1-2705243-svtplay.ts

they also seems to have a different way to name the files than the old ones:
jordskott.s01e06.avsnitt.6-2771768-svtplay.ts
jordskott.s01e05.avsnitt.5-2750806-svtplay.ts
jordskott.s01e04.avsnitt.4-2727846-svtplay.ts
jordskott.s01e03.avsnitt.3-2705215-svtplay.ts

**Comment by spaam** [comment]
interesting

**Comment by spaam** [comment]
the issue is that we grab the title info from the wrong part in the json thing.

**Comment by spaam** [comment]
749d00ac82629ee3c8c8a6 fixed the issue. thanks as always for the bug report :)
