### ISSUE TITLE
Kanal 5 Play doesn't work

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#231]
Nothing from Kanal 5 Play can be downloaded via svtplay-dl, and it has been like this for at least several months. Everything from Kanal 5 Play results in a "Access denied" message from svtplay-dl.

Can something be done about this so that Kanal 5 Play works again? After all, the information on the starting page still says that Kanal 5 is supported, even though this no longer is the case.

**Comment by dhofverberg** [comment]
Correction: It seems like a few videos does work, but the majority won't. Here are some example URL:s from Kanal 5 Play, which all result in a "Åtkomst nekad" error from svtplay-dl:

http://www.kanal5play.se/program/3060212363/video/3267262042#!/play/program/459440433/video/3823132162|/program/459440433
http://www.kanal5play.se/program/3060212363/video/3267262042#!/play/program/372036/video/3803062782|/program/372036
http://www.kanal5play.se/program/3060212363/video/3267262042#!/play/program/3517812304/video/3496152288|/program/372036
http://www.kanal5play.se/program/3060212363/video/3267262042#!/play/program/227058/video/3455602458|/program/372036
http://www.kanal5play.se/program/3060212363/video/3267262042#!/play/program/2825182346/video/3560142137|/program/2825182346

(The URLs do look a bit weird, but these are the actual URLs used on the site)

**Comment by Sopor-** [comment]
I believe those are DRM protected. You will get an error message like this: We cant download drm files for this site.

**Comment by Sopor-** [comment]
The third and fourth URL you are saying is broken will work for me:
ullared-jakten-pa-storsaljaren-s1-avsnitt-3-3496152288-kanal5.ts
sofias-anglar-s4-avsnitt-3-3455602458-kanal5.ts
Are you using latest version?

**Comment by dhofverberg** [comment]
Strange. I have tested with both the latest release and the current master, with the same results.

Sorry for not realizing some of the links I posted use Widevine - I actually didn't know any other site besides TV4 Play used Widevine. I don't get the error message you posted though, but rather "Åtkomst nekad" for all five URLs I posted.

**Comment by Sopor-** [comment]
I have been downloading from Kanal5 for month. I don't know why your URLs are so long? When i copy them they looks like this:
http://www.kanal5play.se/program/3517812304/video/3496152288
This is the same episode as your third one.

**Comment by spaam** [comment]
@Sopor-  if you click around on the site. it can end up with an long url.

@dhofverberg hmm.. did that happen on new released videos or was it old ones with the access denied message?

**Comment by Sopor-** [comment]
I always use the links from "Hela avsnitt" http://www.kanal5play.se/program/3517812304/sasong/1

**Comment by spaam** [comment]
they use dplay.se now. closing this
