### ISSUE TITLE
Download from efn.se

### ISSUE THREAD

**Issue by Gurkan911** [spaam/svtplay-dl#242]
Hello! Would it be possible to download videos from efn.se? Example: http://www.efn.se/2015/06/18/din-ekonomi-sa-far-du-den-perfekta-semestern/.

Best regards, Gunnar

**Comment by spaam** [comment]
looks easy. going to do some coding this weekend. so expect release after the weekend :)

**Comment by Gurkan911** [comment]
Great, thanks in advance!

**Comment by Gurkan911** [comment]
Tack så mycket, funkar bra nu att ladda ner från efn.se (åtminstone under
Lubuntu, lyckas ännu ej under Windows.)

Mvh Gunnar

2015-07-05 21:52 GMT+02:00 Johan Andersson <notifications@github.com>:

> Closed #242 <https://github.com/spaam/svtplay-dl/issues/242> via f3f748d
> <https://github.com/spaam/svtplay-dl/commit/f3f748dde270bf8523b757fe099bd9261e75cb05>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spaam/svtplay-dl/issues/242#event-348105303>.
>



-- 
Med vänlig hälsning

Gunnar Morén
