### ISSUE TITLE
svtplay - download simply gets stuck .. (svtplay, akamai, Keep-Alive)

### ISSUE THREAD

**Issue by Blobbel** [spaam/svtplay-dl#244]
I can interrupt it with ctrl-C. But on multiple tries it gets stuck, in different places but it now seems absolutely no downloads ever complete no matter how many times I try (or how long I wait).

This is on a raspberry-pi machine. The same problem was there earlier this year, but then I attributed it to a flaky ADSL line (it really was shit, noisy, dropped the line etc). But now there is a fiber connection so it should be a lot more solid than ADSL.

I connected the router (runs dd-wrt) directly to the fiber interface and not via Telia's shitty router (even though they supposedly bridged the port it was connected to), still the same thing. Updated both svtplay-dl and python3 to (what I think are) the latest versions... same thing.

What else could I try?? Could it be something svt is doing at the server?

**Comment by Sopor-** [comment]
#196 #205

**Comment by spaam** [comment]
if you can try using adding -v and show us the output.  i guess i should but timeout somewhere in the code.

**Comment by ecsfang** [comment]
I have the same problem - downloading start but seems to get stuck but goes veeery slow, what usually took 5 minutes, can take 2-3 hours to complete,
Using option -v doesn't show anything suspisious apart from that getting HTTP-data sometimes take several minutes per package. Same issue with both SVT- and TV4-play.

See log below - packet #6 took 210 seconds, compared to the previous packages which took less than 1 second.

I'm using ADSL and have no other problems with the network, e.g. using SVT Play to watch works fine.

$ svtplay-dl  -q 1678 -f -Q 10 http://www.svtplay.se/video/2215763/freddie-mercury-the-great-pretender
...
[002/504][.............................................] ETA: 0:03:24DEBUG [1436520990.48] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment2_5_av.ts?null='
DEBUG [1436520991.62] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 2373688 bytes from 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment2_5_av.ts?null=' in 1.14s (= 16692469bps)
[003/504][.............................................] ETA: 0:05:27DEBUG [1436520991.63] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment3_5_av.ts?null='
DEBUG [1436520992.53] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 1868344 bytes from 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment3_5_av.ts?null=' in 0.90s (= 16549140bps)
[004/504][.............................................] ETA: 0:05:59DEBUG [1436520992.54] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment4_5_av.ts?null='
DEBUG [1436520993.47] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 2250360 bytes from 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment4_5_av.ts?null=' in 0.93s (= 19366160bps)
[005/504][.............................................] ETA: 0:06:20DEBUG [1436520993.48] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment5_5_av.ts?null='
DEBUG [1436521204.4] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 2151096 bytes from 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment5_5_av.ts?null=' in 210.92s (= 81587bps)
[006/504][.............................................] ETA: 4:57:03DEBUG [1436521204.41] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment6_5_av.ts?null='
DEBUG [1436521205.38] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 2226296 bytes from 'http://svtplay5i-f.akamaihd.net/i/se/open/20150701/1366773-001A/EPISOD-1366773-001A-52dfb383be5b31fc_,892,144,252,360,540,1584,2700,.mp4.csmil/segment6_5_av.ts?null=' in 0.97s (= 18302658bps)

**Comment by agent666** [comment]
Let me guess that all of you  have telia as isp?

**Comment by Sopor-** [comment]
When i reported the same behavior for my friend it was Com hem. Now it works again for him. So i believe this is ISP related. I also sometimes have this issue but it is very rare. But it would be great if CTRL+C worked. That must be something they could fix... It is very easy to simulate, start a download and disconnect the network cable. Now try to break it with CTRL+C.

**Comment by Blobbel** [comment]
If it was either Com Hem or Telia I suppose you could explain it as ISP-related. But it seems a little bit implausible that both ISPs are internally configured somehow incorrectly over a half year period.

BTW I had the problem with Telia ADSL at the same time as Sopor- reported it and it was considered a possible Com Hem (cable internet) problem. Now I have the same problem with Scanova optical fiber internet (still Telia as the service provider). 

So the problem appears whether you connect via ADSL, Cable or optical fiber. And Com Hem and Telia of course are also service providers to a very large fraction of Swedish internet users..

**Comment by spaam** [comment]
it should be easy fix with the ctrl+c and resume it. need to rewrite some the HLS downloader to do it.
looking at the debug message above. it looks like we got the data from svtplay.se and started to write the data to disk and then everything stopped.

**Comment by Blobbel** [comment]
svtplay-dl -v http://www.svtplay.se/video/2275895/sydamerikas-okanda-kungadomen/avsnitt-1
DEBUG [1436797148.45] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.svtplay.se/video/2275895/sydamerikas-okanda-kungadomen/avsnitt-1'
DEBUG [1436797148.59] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 130704 bytes from 'http://www.svtplay.se/video/2275895/sydamerikas-okanda-kungadomen/avsnitt-1' in 0.14s (= 7704954bps)
DEBUG [1436797148.66] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.svtplay.se/video/2275895/sydamerikas-okanda-kungadomen/avsnitt-1?&output=json&format=json'
DEBUG [1436797148.73] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 1474 bytes from 'http://www.svtplay.se/video/2275895/sydamerikas-okanda-kungadomen/avsnitt-1?&output=json&format=json' in 0.06s (= 182932bps)
DEBUG [1436797148.76] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting u'http://svtplay17j-f.akamaihd.net/z/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m?&hdcore=3.3.0'
DEBUG [1436797148.91] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 5604 bytes from u'http://svtplay17j-f.akamaihd.net/z/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m?&hdcore=3.3.0' in 0.15s (= 304418bps)
DEBUG [1436797148.96] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting u'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8'
DEBUG [1436797149.01] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 1834 bytes from u'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8' in 0.06s (= 264842bps)
INFO [1436797149.03] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Selected to download hls, bitrate: 2793
DEBUG [1436797149.03] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null='
DEBUG [1436797149.09] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 64283 bytes from 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=' in 0.05s (= 9708034bps)
INFO [1436797149.14] /usr/local/bin/svtplay-dl/svtplay_dl/output.py/output: Outfile: sydamerikas.okanda.kungadomen.s01e01.avsnitt-1-2275895-svtplay.ts
[001/355][.................................................................................................] ETA: 0:00:00DEBUG [1436797149.27] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/segment1_6_av.ts?null='
DEBUG [1436797149.93] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 3745336 bytes from 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/segment1_6_av.ts?null=' in 0.66s (= 45675317bps)
[002/355][.................................................................................................] ETA: 0:02:11DEBUG [1436797150.01] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/segment2_6_av.ts?null='
DEBUG [1436797150.73] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 3757368 bytes from 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/segment2_6_av.ts?null=' in 0.71s (= 42273241bps)
[003/355][.................................................................................................] ETA: 0:03:01DEBUG [1436797150.81] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://svtplay17a-f.akamaihd.net/i/se/open/20150702/1362523-001A/PG-1362523-001A-LOSTKINGDOMOF-02_,988,240,348,456,636,1680,2796,.mp4.csmil/segment3_6_av.ts?null='

**Comment by Blobbel** [comment]
Also tried with -P hds, but same thing happens. Ctrl-C works however!

**Comment by spaam** [comment]
@Blobbel the one with HLS. it just stopped and nothing happen?

**Comment by agent666** [comment]
The most interesting thing is why can't many telia users download hls?

**Comment by ecsfang** [comment]
I have Telia, but this has work smooth and fine up until last week or so (sometime between 14/6 and 7/7). After that it stucks every time as described earlier. It still works without any errors, it just takes 2-3 hours instead of 2-3 minutes to download one episode.

**Comment by Blobbel** [comment]
HLS, HDS, both just stop. Not sure how long i should wait though..

**Comment by agent666** [comment]
It's just that problem I talk about... It's only hls if you test hds it's running fine and at normal speed and telia..

**Comment by agent666** [comment]
My answer was for ecsfang

**Comment by spaam** [comment]
interesting.  i have an idea which might fix the issue.

**Comment by agent666** [comment]
Spaam@ Blobbel's or my?

**Comment by ecsfang** [comment]
@agent666, I'll check if this applies to both HLS and HDS or not when I get home.

**Comment by ecsfang** [comment]
@agent666, nope, same result with both HLS and HDS:

$ svtplay-dl -q 1678 -f -P hds http://www.svtplay.se/video/xxx/xxxxx
INFO: Selected to download hds, bitrate: 1678
INFO: Outfile: xxxxxxxxxxxxxxx.flv
[026/839][=............................................] ETA: 2:21:19

About 10 packages goes quickly, but then it stucks again, and it takes 2-3 hours to complete.

**Comment by fwangel** [comment]
Any progress on this?

I believe the problem is that the download is done in separate HTTP sessions, one for each part. If it is performed with a proper "Connection: Keep-Alive" header in a single TCP/IP connection it should work fine. The remote Akamai server severely throttles the bandwidth after a few connections.

It is simple to verify by first downloading the m3u8 index file and then using e.g. wget (which supports and uses Keep-Alive connections) to download each part.

    svtplay-dl -g http://www.svtplay.se/video/3110870/rapport/rapport-16-7-12-00
    wget http://svtplay1o-f.akamaihd.net/i/world/open/20150716/1368685-089A/EPISOD-1368685-089A-ef6a7c71ae2bf2ab_,892,144,252,360,540,1584,2700,.mp4.csmil/index_6_av.m3u8?null=
    grep 'http' index_6_av.m3u8\?null= | sort -V | xargs wget
    ls segment* | sort -V | xargs cat >> rapport.167-12.00-3110870-svtplay-wget.ts

Speedy download (seconds) compared to hours when using the current download code of svtplay-dl

**Comment by spaam** [comment]
not since 3 days ago.  still same thing. maybe i will do something this evening.

**Comment by ecsfang** [comment]
Tried the tip from fwangel, and that worked like a charm ... ;)
Every part (of about ~5MB each) was downloaded within 1-2 seconds, almost no stuttering at all so that supports the suggestion about the connection problem towards the Akamai server using separate HTTP sessions.

**Comment by spaam** [comment]
one way to fix this is to start using the module requests. but if we go down that line. it will be one more dependency to install except pycrypto.

**Comment by agent666** [comment]
With requests.session()?

**Comment by spaam** [comment]
yes for example.  its easy to install on linux based systems and on osx.  need to check how to do it for the windows guys.

**Comment by agent666** [comment]
For those that have pip just enter pip install requests in cmc

**Comment by agent666** [comment]
@cmd

**Comment by fwangel** [comment]
I used the simple httplib2 module (that I think is part of a standard distribution) and built a replacement for the the get_http_data function in utils/__init__.py but since I don't usually program python I am unsure about the cookiejar part of the old function, but other than that it seems to work fine.

So far I have only tested using python3 and against svtplay.se and kanal5play.se without any premium, so I don't want to provide a patch just yet.

**Comment by Blobbel** [comment]
Some feedback for @fwangel , the code at the link worked about a billion times better for me wrt svtplay. It still (occasionally) gets stuck, but this is much better than working exactly zero percent of the time.

**Comment by dentarg** [comment]
@spaam +1 on using [Requests](http://docs.python-requests.org/en/latest/), I don't think it's sustainable for svtplay-dl to do all the HTTP stuff itself in the long-run

I can't see anything about Requests not working in Windows

...just some thoughts from your collaborator that hasn't yet contributed any code :-)

**Comment by spaam** [comment]
Master have support for requests now. it should fix this issue
