### ISSUE TITLE
Being Bingo tv6play can't find file

### ISSUE THREAD

**Issue by calovizzini** [spaam/svtplay-dl#246]
I tried to download "Being Bingo" from tv6play but it didn't work. Other shows from tv6play works fine but no episodes in Being Bingo works. Link for ep. 1: http://www.tv6play.se/program/beeing-bingo/3585?autostart=true

"INFO: Outfile: beeing-bingo-avsnitt-1-tv6-play.flv
ERROR: Could not execute rtmpdump: Can't find the file"

**Comment by Sopor-** [comment]
@calovizzini it works here... Have you installed rtmpdump?

**Comment by calovizzini** [comment]
Silly mistake, thanks mate!
