### ISSUE TITLE
How to install on Windows 8?

### ISSUE THREAD

**Issue by gigsisa** [spaam/svtplay-dl#248]
Please tell me how does it work? I got it but I can't install :(

**Comment by olof** [comment]
Hi,

You can either run it directly (`python svtplay-dl URL` or `./svtplay-dl URL`) or copy the file `svtplay-dl` to e.g. `/usr/local/bin/`. You didn't specify what OS you are on, so there may be some variations (what I said is valid for unix like operating systems).

**Comment by gigsisa** [comment]
I am on windows 8, when I press setup.py nothing happens .

**Comment by olof** [comment]
I don't use Windows unfortunately, maybe @spaam knows? But you should not have to touch/use/care about setup.py. The file `svtplay-dl` is all you need. You can copy it independently from the rest of the files in the repository.

**Comment by gigsisa** [comment]
I can't figure out what to do, where should I type this commands svtplay-dl URL, on cmd ? For example I have http://www.svtplay.se/video/129261/blabla/blabla-2   this url how can I download it ?

**Comment by Sopor-** [comment]
You need to install [python](https://www.python.org) and then you open a command prompt in the same folder where svtplay-dl is and then you run it like this:
```
python svtplay-dl http://www.svtplay.se/video/129261/blabla/blabla-2
```
You also need to install [rtmpdump](http://rtmpdump.mplayerhq.hu) and [PyCrypto](https://www.dlitz.net/software/pycrypto) if you don't want to run into any issues later. Some streams need those.

**Comment by gigsisa** [comment]
It says : Traceback (most recent call last):
  File "svtplay-dl", line 4, in <module>
    import svtplay_dl
ImportError: No module named svtplay_dl


what is problem?  :/

**Comment by olof** [comment]
@gigsisa Could you include what you did to get that error message as well?

**Comment by olof** [comment]
Closing, as there hasn't been any activity since july.
