### ISSUE TITLE
UNC path name will be included in the file name

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#251]
When i try to save with -o to an UNC path the path will be included in the file name:
```
python svtplay-dl http://www.tv4play.se/program/det-tredje-%C3%B6gat?video_id=3192335 -o "\\xbmcbuntu\TV Shows\_test"
INFO: Selected to download hls, bitrate: 4496
INFO: Outfile: \\xbmcbuntu\TV Shows\_test/xbmcbuntutv-showstestdet-tredje-ogat-del-8-tv4-play-3192335-tv4play.ts
```

Is this something you can fix so it will not add the path to the file name?
I know i can map a network drive but i use several UNC paths so it would not work very well for me :(

**Comment by dentarg** [comment]
Just some general info (I hade to google "UNC path" – I'm not a Windows user myself) that may help someone looking at this

> Microsoft Windows uses the following types of paths: local file system (LFS), such as C:\File. uniform naming convention (UNC), such as \\Server\Volume\File or / `<internet resource name>`[\Directory name] (at least in Windows 7 and later)

See also https://en.wikipedia.org/wiki/Path_(computing)#Uniform_Naming_Convention

**Comment by spaam** [comment]
I guess you only want "Outfile: xbmcbuntutv-showstestdet-tredje-ogat-del-8-tv4-play-3192335-tv4play.ts" ?

**Comment by Sopor-** [comment]
I want it to be
Outfile: \\xbmcbuntu\TV Shows\_test/det-tredje-ogat-del-8-tv4-play-3192335-tv4play.ts
but for some reason it will add the UNC path to the file name.
I can see i use backslash \ and the last is a forward slash /.

**Comment by spaam** [comment]
yeah that is because i use / to concat the directory and the filename.
