### ISSUE TITLE
The great move to requests

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#254]
pros? This will fix #181, #205,  #212, #244, ?? , profit!

cons? bad thing will be one more external deps

http://www.python-requests.org/en/latest/

**Comment by Sopor-** [comment]
I have now installed [Requests](http://www.python-requests.org), so when will svtplay-dl have support for it :)

**Comment by spaam** [comment]
Most of the work is done. some small fixes is left :)

**Comment by Sopor-** [comment]
So now svtplay-dl requires Requests or will it run without Requests?

**Comment by spaam** [comment]
the binary svtplay-dl in master is the old stuff. you need to generate a new one (with make) if you want to use one with requests

**Comment by dentarg** [comment]
:+1:

**Comment by Sopor-** [comment]
Yes, but will that force me to use Requests when i use this new version? It will not work at all without Requests?

**Comment by spaam** [comment]
In the next version you need to have requests installed if you want to use the script.

**Comment by Sopor-** [comment]
Now i only get this
ERROR: Couldn't retrieve episode list

**Comment by spaam** [comment]
cool. from where?

**Comment by Sopor-** [comment]
but i can download if i don't use -A
http://www.svtplay.se/video/3313821/akuten/akuten-sasong-5-avsnitt-5

**Comment by Sopor-** [comment]
Do you check if Requests is installed or not?

How can i see if Requests is installed on Ubuntu server?

**Comment by Sopor-** [comment]
I can't use -A
I tried it on http://www.svtplay.se/akuten

**Comment by spaam** [comment]
fixed the -A error.

no i dont check if requests is installed yet. but i will show an error message. i haven't fixed that yet.
depending how you installed it:
via apt-get: dpkg -l | grep requests
or
via pip: pip list | grep requests

**Comment by Sopor-** [comment]
hmm, i haven't installed Requests on one of my Ubuntu but it is still working.

**Comment by Sopor-** [comment]
It was already installed on that Ubuntu. Thanks for your help
python-requests                      2.2.1-1ubuntu0.3

**Comment by Sopor-** [comment]
In Windows i used pip and the other Ubuntu i used git clone

**Comment by Sopor-** [comment]
I can't install it now after latest -A fix:
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import svtplay_dl
  File "/home/nisse/svtplay-dl/lib/svtplay_dl/__init__.py", line 13, in <module>
    from svtplay_dl.utils.urllib import URLError
ImportError: cannot import name URLError

**Comment by spaam** [comment]
should work now .)

**Comment by Sopor-** [comment]
I also get this when downloading from kanal5 with -S
```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main    "__main__", fname, loader, kg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 326, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 176, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 201, in get_one_media
  File "svtplay-dl\svtplay_dl\subtitle\__init__.py", line 26, in download
  File "svtplay-dl\svtplay_dl\subtitle\__init__.py", line 70, in json
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```

**Comment by spaam** [comment]
should be fixed now

**Comment by Sopor-** [comment]
Don't forget to update the year :)
Copyright (C) 2011--2014, Johan Andersson et al

**Comment by olof** [comment]
@spaam great work! just for the record: the added dependency is easily motivated in my opinion :)

**Comment by spaam** [comment]
@olof ty ty :)

latest version 0.20.2015.09.13 have this thing. use it :)
