### ISSUE TITLE
Is it possible to convert &amp; ?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#255]
I notice that the subtitles have "&amp;amp;" instead of &, so is this possible to convert? I know i seen this for other chars too...

**Comment by spaam** [comment]
yes ofc. where did you see it?

**Comment by Sopor-** [comment]
This time it was
http://www.svtplay.se/video/3293061/sextemplet/sextemplet-avsnitt-1

**Comment by spaam** [comment]
shouldn't be that hard to fix.

**Comment by spaam** [comment]
we are doing something similar for filenames already
