### ISSUE TITLE
Sveriges Radio seems broken

### ISSUE THREAD

**Issue by jonatanlindstrom** [spaam/svtplay-dl#258]
Having downloaded episodes of Sommar i P1 throughout the summer I noticed today that it doesn't work anymore.

Example:
```
$ svtplay-dl http://sverigesradio.se/sida/avsnitt/592483?programid=2071
ERROR: Can't find audio info
ERROR: Can't find any streams for that url
```

I've tried a couple of other shows from different SR channels with the same result.

**Comment by spaam** [comment]
this will be included in the next version

**Comment by jonatanlindstrom** [comment]
Sjukt snabb respons! Heja!
