### ISSUE TITLE
TV4Play - after latest update some of the Swedish chars are wrong

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#259]
When i was downloading from TV4Play i could see that some of the Swedish chars was wrong.:
I have subtitles downloaded before the update #254 and those have correct chars.
svtplay-dl -S http://www.tv4play.se/program/brynolf-ljung-street-magic?video_id=3196098
```
Nu fĺr ni gĺ härifrĺn, allihop!
```

**Comment by spaam** [comment]
its a feature. i will take a look at it later today

**Comment by spaam** [comment]
do you use latest in master?  what python version? what os?  i tried on linux, OS X and windows 10. no issue at all.

```
3
00:00:06,56 --> 00:00:08,96
Nu får ni gå härifrån, allihop!
```

**Comment by spaam** [comment]
the file should be in utf8 format.

**Comment by Sopor-** [comment]
It seems to work in Windows but not Ubuntu. The file is UNIX UTF-8.
Python 2.7.6
Ubuntu 14.04 LTS

**Comment by Sopor-** [comment]
It seems to only be 'å' that is not working:
```
00:02:22,40 --> 00:02:29,20
Mycket stĺr pĺ spel. Bĺda killarna
vill gĺ härifrĺn som segrare.
```

**Comment by spaam** [comment]
i tried this with debian stable 8.1 with python 2.7.9. no issue.

**Comment by Sopor-** [comment]
I tested it on another computer running Ubuntu 14.04 LTS and the same python version. Same result as before :(

**Comment by Sopor-** [comment]
Now it looks the same in Ubuntu as in Windows:
```
00:01:29,72 --> 00:01:34,60
00:01:54,28 --> 00:01:59,56
Det дr omцjligt att vara otrogen nu
nдr man дr цvervakad.
```
If i play it in my web browser it looks like it should. No weird chars.

**Comment by Sopor-** [comment]
Here is a picture of Windows (left) and Ubuntu (right) and you can see there are 488 differences between the two files...
![picpick-2015 09 11-16 34 51](https://cloud.githubusercontent.com/assets/5789283/9817478/715e9bac-58a3-11e5-9081-ed865c5e4518.jpg)

**Comment by spaam** [comment]
do you use the same python version on both ?

**Comment by spaam** [comment]
i starting to think there is a bug in python 2.7.6 that was fixed in later versions.

**Comment by Sopor-** [comment]
But why do we see it now and not before?

I have now tested it on Windows 7 with Python 2.7.6 and it is working perfect.

From Windows 7 with Python 2.7.6:
00:01:24,96 --> 00:01:28,68
Vi måste hitta spelare
som orkar i två halvlekar.

From Ubuntu 14.04 with Python 2.7.6
00:01:24,96 --> 00:01:28,68
Vi mĺste hitta spelare
som orkar i tvĺ halvlekar.

**Comment by spaam** [comment]
does this happen only on tv4play or some other ones too? When you run "locale" what does it say on you linux box?

**Comment by Sopor-** [comment]
It is only TV4 what i know so far...
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8

**Comment by spaam** [comment]
this is something with requests 2.2.1  in that ubuntu version

**Comment by Sopor-** [comment]
This issue is back...
```
1
00:00:00,16 --> 00:00:05,24
Vill du ha smцrgеs? Mickan...mеste
du jobba nu nдr vi har smеbarn?

2
00:00:05,40 --> 00:00:10,16
–Var дr dina modersinstinkter?
–Utvecklingen gеr framеt.

3
00:00:10,32 --> 00:00:16,52
Du gеr frеn stenеlder till jдrnеlder
och hoppar цver bronsеldern.
```

**Comment by spaam** [comment]
you still see this on tv4 ?

**Comment by Sopor-** [comment]
It worked when you fixed this but now it seems to have other chars as you can see above
