### ISSUE TITLE
Kanal 5 -A tries to download 128 episodes

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#262]
When use -A on Kanal 5 it tries to download 128 episodes even if i specify the season i want to download. Is it possible to limit the download if i add the path to a specific season?
```
$ svtplay-dl -S -A http://www.kanal5play.se/program/227058/sasong/5
INFO: Episode 1 of 128
```

**Comment by Sopor-** [comment]
It would be really great if it could separate the seasons because it will be very hard to know what season an episode belong to when it tries to download all episodes

**Comment by spaam** [comment]
this is a bit different behaviour from other sites. nice to have the same thing for all the sites.

**Comment by Sopor-** [comment]
I understand, but if i use http://www.kanal5play.se/program/227058 it could download all episides but not if i specify season like this http://www.kanal5play.se/program/227058/sasong/5

**Comment by spaam** [comment]
master have some fixes for this
