### ISSUE TITLE
Problem downloading  content from urplay

### ISSUE THREAD

**Issue by swedpool** [spaam/svtplay-dl#265]
When trying to download from urplay, I get the following error message.
![skarmbild fran 2015-09-03 06 25 02](https://cloud.githubusercontent.com/assets/14103811/9650537/c3756542-5204-11e5-8d3a-02ea1a0f4960.png)

Am I doing something wrong here?

Thanks in advance for help with this.

**Comment by spaam** [comment]
you are using an old version of svtplay-dl script :) if you download the newest. it should work with urplay :)
