### ISSUE TITLE
How do I update to the latest version?

### ISSUE THREAD

**Issue by ilbaritone** [spaam/svtplay-dl#267]

**Comment by spaam** [comment]
it depends what you mean.
if you want to run the non-released version if you run linux, bsd or osx: run make in the root dir. svtplay-dl will be updated after that.
if you want to use the latest released version. just download the svtplay-dl file in the root folder.
if you run osx and use brew, you can: brew install svtplay-dl   and after i release a new version you can just update brew and upgrade the packages

i will release a new version on tuesday evening. :)
