### ISSUE TITLE
Can we have support for SolidTango?

### ISSUE THREAD

**Issue by mkjorling** [spaam/svtplay-dl#268]
See for example http://skkplay.se/

SKK appears to be using solidtango.com so adding support might enable other services as well.

Right now all I get is:

$ svtplay-dl --verbose https://skkplay.solidtango.com/video/badning
    DEBUG [1441919485.72] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'https://skkplay.solidtango.com/video/badning'
    DEBUG [1441919486.17] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 38735 bytes from 'https://skkplay.solidtango.com/video/badning' in 0.46s (= 676759bps)
    ERROR [1441919486.18] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: That site is not supported. Make a ticket or send a message
$

**Comment by spaam** [comment]
master have support for this site. i will make a new release of the script this weekend.
