### ISSUE TITLE
Output folder

### ISSUE THREAD

**Issue by bpmildh** [spaam/svtplay-dl#271]
Is it posible to output streams to a specific folder without providing a filename thru -o ?
(eg stick to the filename fetched by svtplay-dl)
Now it outputs to ~/ and it gets a bit messy with many downloads.
(OSX 10.10.5, Homebrew 0.9.5, svtplay-dl: 0.10.2015.08.24)

**Comment by spaam** [comment]
it should work. svtplay-dl -o /path/to/super/cool/folder/ http://super.site.domain.tld/video/360/   
with that it will output to the folder and get the name automagic like we do when we dont specify -o

**Comment by bpmildh** [comment]
Thanks, it did work but with a tilda in path ;-)
svtplay-dl -o ~/path/to/super/cool/folder/ http://super.site.domain.tld/video/360/

**Comment by spaam** [comment]
awesome :D
