### ISSUE TITLE
Kanal5

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#274]
Kanal5play change to http://www.dplay.se.. And some security ads is added. 
Is it something that can be fixed?

**Comment by spaam** [comment]
looks pretty easy to fix.

**Comment by agent666** [comment]
Hope so..

I have try with ffmpeg on m3u8 stream and hdsdump on f4m stream and was unable to get videos...

**Comment by spaam** [comment]
the issue why ffmpeg and hdsdump can't handle it is because the site really cares about the cookies when accessing the playlist and files.
