### ISSUE TITLE
TV4-premium episodes all named as tv4-play-tv-nar-du-vill-<id>-tv4play

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#276]
Just noticed that all the TV4 premium files downloaded get the defualt name of tv4-play-tv-nar-du-vill-<id>-tv4play.ts where the <id> is the video_id of the video. Guess it is because the name is taken from the title field which in the free videos have the name of the series up there, while all premium videos has the "TV4 play tv när du vill". It is not a deal breaker. 

When downloading the files one by one I just use the -o paramater. But now when -A is working for premium files this is more of a problem. Guess I will have to rename all the files by hand later on.  So my quesion is 
1. Is it posible to check the premium names from some other tag on the site? 
2. If 1 is not easily done is it posible to add a paramter tag that allows me to specify a file name that will then be increamented for example if i name the file "Serienamn - del  \<i\>.ts then i gets incremented for each file downloaded? 

Should not be an prioritized issue, but a fix would be nice and time saving.

**Comment by spaam** [comment]
from what url do you get "tv4-play-tv-nar-du-vill--tv4play.ts"? 
i get the right name from http://www.tv4play.se/program/brottsplats-usa?video_id=3103537 for example. 

1) http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=brottsplats-usa for example but.  that is more or less the same thing we have right now.

2) sure that is another feature request.

**Comment by qnorsten** [comment]
From all the kidsprograms e.g. http://www.tv4play.se/barn/postis-per?video_id=820959

**Comment by spaam** [comment]
awesome. always good to have an url with the issue. i guess i could generate the filename from the api previous comment
