### ISSUE TITLE
TV4 - Swedish chars still weird in subtitles

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#282]
When downloading from TV4 the Swedish chars will look like this. It seems to have changed if you look in issue #259
4
00:00:16,68 --> 00:00:23,52
–Bronsеldern kдnns цverspelad.
–Utan den hade vi vunnit jдrn i VM.

5
00:00:23,68 --> 00:00:26,04
Jag mеste till jobbet.

6
00:00:26,20 --> 00:00:31,00
Jag med. Vi fеr hjдlpas еt i hemmet.
Det kallas jдmstдlldhet.

---------------------------
Python 2.7.6
Requests 2.7.0
Ubuntu 14.04 LTS
svtplay-dl -S http://www.tv4play.se/program/solsidan?video_id=3200112

**Comment by spaam** [comment]
I'm thinking about remove this feature.

**Comment by Sopor-** [comment]
What feature do you want to remove?

**Comment by spaam** [comment]
subtitles. so annoying when the play site change stuff

**Comment by Sopor-** [comment]
Ohh, please don't do that :( That is one of the reasons i use svtplay-dl, i get subtitles on the episodes :)

**Comment by Sopor-** [comment]
Now it is working, thanks!
