### ISSUE TITLE
TV4 - UNC path name will be included in the file name (Windows)

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#283]
I have already reported this #251 and then it was for all sites but now it is only TV4 that will add the UNC path to the file name:
xbmcbuntutv-showsannat.solsidan-del-1-tv4-play-3200112-tv4play.ts

**Comment by spaam** [comment]
what is the command you used for it?

**Comment by Sopor-** [comment]
It seems to be fixed when issue #280 was fixed
