### ISSUE TITLE
Command line parsing on windows weirdness

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#288]
When i try to use -o i must have that after the url even if the usage tell me different. I would prefer to have the url last and to use -o before the url. That will make my script and shortcuts much easier to create and use.
svtplay-dl -h
Usage: svtplay-dl [options] url

So i need to do it like this
python svtplay-dl http://svtplay.se/agenda -o "c:\my videos\agenda\"

but i prefer to do it like this as the usage text also tell me to do it
python svtplay-dl -o "c:\my videos\agenda\" http://svtplay.se/agenda

**Comment by olof** [comment]
This works for me. What happens when you do this? The options is ignored?

One note, maybe it's nothing, but shouldn't it be

    python svtplay-dl -o "c:\\my videos\\agenda\\" http://svtplay.se/agenda

? Or is escaping handled differently on windows? Not sure why having it as a final argument would matter if that's the issue, though.

**Comment by Sopor-** [comment]
I found it. When i use " " around the path i get this behavior. I need to use " " because of the spaces.
If i do like you described i get this crash. In Windows you use " " but maybe there are other ways to do it? I do believe " " should work as it works if i place it last in the command line.
```
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 343, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 175, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 230, in get_one_media
  File "svtplay-dl\svtplay_dl\fetcher\hls.py", line 88, in download
  File "svtplay-dl\svtplay_dl\output.py", line 171, in output
```

**Comment by olof** [comment]
To include a " character in a " quoted string, you usually do \". That signals to the command line parser to treat the " character literally, i.e include it in the string.

Also, could you include the full error message including what exception was raised?

**Comment by Sopor-** [comment]
It has always worked like this since the old DOS... You can't compare Linux with Windows. Linux adds \ Windows use ".

**Comment by olof** [comment]
[Here](https://msdn.microsoft.com/en-us/library/windows/desktop/17w5ykft(v=vs.85).aspx)'s what Microsoft has to say about this, but feel free to contact them about them being wrong:

> A double quotation mark preceded by a backslash (\") is interpreted as a literal double quotation mark character (").
>
> Backslashes are interpreted literally, unless they immediately precede a double quotation mark.
>
> If an even number of backslashes is followed by a double quotation mark, one backslash is placed in the argv array for every pair of backslashes, and the double quotation mark is interpreted as a string delimiter.

I light of this, 29612f4f11bd1e6cc88b59778e65b20cb40a3533 seems to be a workaround for erroneous usage, which will instead make it impossible for people to include these characters in the filename. In the future, I advise that you cease telling people which comparisons they can and cannot make, especially people trying to help you.

**Comment by Sopor-** [comment]
I have never in my life needed to use \ when i used " " in paths with spaces. Even MS tell users to use " " around the path. Maybe when you are coding you need to use it but not for the end user.

**Comment by Sopor-** [comment]
I manage to get it to work like you describe for me, so thanks for your help :+1:

**Comment by Sopor-** [comment]
It will also be impossible to create scripts that take the path because the path will not include double backslashes. Same goes for adding it into shouts cuts buttons in common file managers.
