### ISSUE TITLE
SSL warnings seen when fetching from Sveriges Radio over HTTPS

### ISSUE THREAD

**Issue by quite** [spaam/svtplay-dl#294]
Not sure if the warning is the actual error

```
/usr/lib/python2.7/site-packages/urllib3/connection.py:264: SubjectAltNameWarning: Certificate for sverigesradio.se has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
```

**Comment by olof** [comment]
The ssl issue is only a warning; i can reproduce if i give svtplay-dl a https url to sverigesradio. But this is something only SR can solve :). We could maybe disable the warning though.

**Comment by quite** [comment]
Aha yes, but the real problem was "can't find audio info". Any nothing get's downloaded, as it used a month or two ago...

**Comment by olof** [comment]
That's another issue, unrelated to the SSL warning. Can you open a new issue about this? Make sure to include --verbose output.

**Comment by dentarg** [comment]
This can be closed at it's not a problem with svtplay-dl, it's a deprecation warning from an dependency (urllib) of a dependency (requests), https://github.com/shazow/urllib3/issues/497 has more info

Also, sverigesradio.se has fixed their certificate, from `testssl.sh sverigesradio.se`

```
 Common Name (CN)             sverigesradio.se
 subjectAltName (SAN)         sverigesradio.se www.sverigesradio.se www.sr.se sr.se
```
