### ISSUE TITLE
InsecurePlatformWarning & SSL errors with dplay.se

### ISSUE THREAD

**Issue by mcrevo96** [spaam/svtplay-dl#303]
I'm having problems downloading from dplay.se, all other sites seem to work (SVT Play, TV4 Play, TV3 Play etc). I live in FInland, but using a rented Ubuntu 14.04.3 LTS server located in Sweden.

svtplay-dl version: 0.20.2015.10.25

Here's an example:

`./svtplay-dl --verbose -f -o hh.ts http://www.dplay.se/100-hojdare/season-6-storslagen-final-hagrar-i-100-hojdare`

The response I get is:

`DEBUG [1446721643.84] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/100-hojdare/season-6-storslagen-final-hagrar-i-100-hojdare/'
DEBUG [1446721644.05] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1446721644.08] ./svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/60886?stream_type=hds'
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 345, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 202, in get_one_media
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed`

Any ideas how to solve this? The script worked fine when it still was kanal5play.se, but this started as soon as they merged to dplay.se.

Visiting the linked https://urllib3.readthedocs.org page also didn't give any answers I would understand.

**Comment by olof** [comment]
Hi, I believe this is caused by lack of some modules. Take a look at #298. @ullgren suggested the following will make it work (I added python-openssl to the list to install as well):

    $ sudo -i
    # apt-get install python-pyasn1 python-openssl python-pip
    # pip install ndg-httpsclient

**Comment by mcrevo96** [comment]
This did it for me, thank you so much! Now downloading again from dplay. :+1:
