### ISSUE TITLE
--exclude seems to stop the download

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#304]
When i use the option --exclude=syntolkat it seems to stop and not continue to download the rest of the files. I'm running latest master.
```
c:\Svtplay-dl>python svtplay-dl -S -A --exclude=syntolkat http://www.svtplay.se/angelby
INFO: Episode 1 of 14
INFO: Outfile: angelby.s01e01.avsnitt.1-3847017-svtplay.srt
INFO: Selected to download hls, bitrate: 2794
INFO: Outfile: angelby.s01e01.avsnitt.1-3847017-svtplay.ts
[265/265][===========================================================================] ETA: 0:00:00
INFO: Episode 2 of 14
ERROR: Excluding video

c:\Svtplay-dl>
```

**Comment by spaam** [comment]
what version is this?

**Comment by Sopor-** [comment]
Wow, you have added the git version number. That wasn't there before :)
0.20.2015.10.25-12-g10fdd9f

**Comment by spaam** [comment]
this happen because of 0ead96f03e81abd7 and #301 
need to find a better way to handle this with using -A
