### ISSUE TITLE
ERROR: Can't find any streams for that url  (SVTPLAY)

### ISSUE THREAD

**Issue by fshsweden** [spaam/svtplay-dl#305]
Hello, I am getting a problem with this URL:
http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1

I installed via brew on OSX El Capitan. Here is some debug info:

iMac-Office peterandersson ~/dev  >svtplay-dl --version
0.10.2015.08.24

iMac-Office peterandersson ~/dev  >which svtplay-dl
/usr/local/bin/svtplay-dl

iMac-Office peterandersson ~/dev  >svtplay-dl http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1
ERROR: Cant get manifest file
ERROR: Cant get hls playlist
ERROR: Can't find any streams for that url

iMac-Office peterandersson ~/dev  >svtplay-dl http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1 --verbose
DEBUG [1447166510.03] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1'
DEBUG [1447166510.62] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 119469 bytes from 'http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1' in 0.59s (= 1621479bps)
DEBUG [1447166510.63] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting 'http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1?output=json'
DEBUG [1447166510.67] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP got 1429 bytes from 'http://www.svtplay.se/video/4495635/vart-rymdaventyr/vart-rymdaventyr-avsnitt-1?output=json' in 0.04s (= 296295bps)
DEBUG [1447166510.67] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting u'http://svtplay10g-f.akamaihd.net/z/se/open/20151031/1369183-001A/PG-1369183-001A-SPACEVOYAGES-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m?&hdcore=3.3.0'
ERROR [1447166510.71] /usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hds.py/hdsparse: Cant get manifest file
DEBUG [1447166510.71] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/get_http_data: HTTP getting u'http://svtplay10a-f.akamaihd.net/i/se/open/20151031/1369183-001A/PG-1369183-001A-SPACEVOYAGES-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8'
ERROR [1447166510.74] /usr/local/bin/svtplay-dl/svtplay_dl/fetcher/hls.py/hlsparse: Cant get hls playlist
ERROR [1447166510.74] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Can't find any streams for that url

**Comment by olof** [comment]
Hi, could you try upgrading to the latest release (0.20.2015.10.25)? Works for me with that version.

**Comment by fshsweden** [comment]
worked like a charm! I cloned the repo and built it myself, and removed the brew'd version. THX!

**Comment by olof** [comment]
Excellent!
