### ISSUE TITLE
I can't download subtitles from dplay

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#307]
Is it only for me or is it no support for subtitles from dplay?

**Comment by spaam** [comment]
it should be available in master and not the released version. i will make a new release tomorrow

**Comment by agent666** [comment]
so if i "makefile" it would work for me?

**Comment by spaam** [comment]
If you are running an *nix system. You can type make in the root directory for the repo. After that. You will have an updated version of the svtplay-dl binary.

-- 
Johan Andersson

**Comment by agent666** [comment]
I run cygwin on W7... And have done it many times before.. Is it more fixes in the master then the subtitle?

**Comment by spaam** [comment]
yes. it have several fixes for that site. subtitles, better names for the output file, download all episodes for one show and support for premium content if you have an user / passwd for it.

**Comment by agent666** [comment]
Yay... End it is all included in master already? If i "make" today it wold be same as the release tomorrow or will you release more fixes in your release?

**Comment by spaam** [comment]
this is fixed in latest release.
