### ISSUE TITLE
no git version number on Ubuntu

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#309]
When i run 'svtplay-dl --version' on Windows i get the git version number included but on Ubuntu i only see the latest version. I'm running the same master on both.

Windows: 0.20.2015.10.25-23-g4d97206

Ubuntu: 0.20.2015.10.25

That's why i got so surprised when i got that number when spaam asked for it in #304

Is this something wrong and if not, how do i get the complete version number on Ubuntu?

**Comment by olof** [comment]
You only get commit info if you're not on an official release. If you use the release build of svtplay-dl, you won't get any additional info. Likewise, on Debian, you'll instead see something like: 0.20.2015.10.25-debian2.

**Comment by olof** [comment]
Can you confirm that this is the case before I close the issue?

**Comment by Sopor-** [comment]
I'm not really sure i understand what you mean. I run the same version on both computers.
I run 'git pull', then 'make' and to install it i run 'sudo python setup.py install'. If i then run 'svtplay-dl --version' it will only show 0.20.2015.10.25 on Ubuntu.
On Windows i use the files i have on my Ubuntu (i copy all files from ubuntu to windows) and if i run 'python svtplay-dl --version' on Windows i get 0.20.2015.10.25-23-g4d97206.
Latest commit have: 4d972063d265b3582cbac6f7ed1df08ba85855bd so that must be the latest one.

**Comment by olof** [comment]
Ah, I see. To get version info you have to have git on the machine you're building on. I think it should be 0.20.2015.10.25-unknown instead, will fix.

**Comment by olof** [comment]
Hum, should already have a -unknown suffix. Do you have git on that host? If so, what does `git describe --dirty` output?

**Comment by olof** [comment]
I just pushed a fix for a problem you maybe are running into. Could you try the latest master, and see if you get the -unknown suffix?

**Comment by Sopor-** [comment]
I still only get 0.20.2015.11.29 when running 'svtplay-dl --version' and
git describe --dirty will output 0.20.2015.11.29-3-g7dea8c8-dirty

**Comment by dentarg** [comment]
@Sopor- is this still an issue?

**Comment by Sopor-** [comment]
This is what i get when i run --version...
Windows:
python svtplay-dl --version
1.0-13-gf15df72

Ubuntu:
$ svtplay-dl --version
1.0

Ubuntu:
svtplay-dl$ git describe --dirty
1.0-13-gf15df72-dirty

**Comment by dentarg** [comment]
@Sopor- what does `which svtplay-dl` say on Ubuntu?

**Comment by Sopor-** [comment]
$ which svtplay-dl
/usr/local/bin/svtplay-dl

**Comment by spaam** [comment]
i guess he is using "setup.py install" and that one is using the version number from svtplay_dl/__init__.py

**Comment by Sopor-** [comment]
Yes, i do run `python setup.py install`

**Comment by olof** [comment]
So sorry for not responding to this sooner but if you use `make install` instead of `python setup.py install`, you should get the expected results.

**Comment by Sopor-** [comment]
Yes, i now use `make install` ...
