### ISSUE TITLE
Adding -S for subtitles messes up the video

### ISSUE THREAD

**Issue by moschler** [spaam/svtplay-dl#310]
When adding the -S option to a download, the video is unplayable.

This works:
./svtplay-dl -q 900 -Q 100 "http://www.svtplay.se/video/4364823/arets-sockerbagare-2015/arets-sockerbagare-2015-sasong-2-avsnitt-5" -o socker05.mp4

This won't work:
./svtplay-dl **-S** -q 900 -Q 100 "http://www.svtplay.se/video/4364823/arets-sockerbagare-2015/arets-sockerbagare-2015-sasong-2-avsnitt-5" -o socker05.mp4

I get the same result if I just save the TS-stream to file.

I do not know when this arose but I have seen it for a couple of months, it was just now that I found the connection.

**Comment by moschler** [comment]
No! This was not a bug in svtplay-dl, sorry.
Seems to be a bug in VLC...

Sorry, you can close this bug.... O:)

**Comment by dentarg** [comment]
@moschler I have noticed the same thing... is https://trac.videolan.org/vlc/ticket/3075 the bug in VLC you are thinking off?

**Comment by dentarg** [comment]
> is https://trac.videolan.org/vlc/ticket/3075 the bug in VLC you are thinking of?

It's gotta be, from the description of that bug:

> VLC cannot handle the situation where there is something.m2ts file and something.srt (or .txt) text file in same folder. When something.m2ts is opened VLC cannot proceed, it only prints some stuff to message log. If the text file is removed from the folder, the playback starts normally.

**Comment by dentarg** [comment]
Workaround (thanks to @spaam)

    ffmpeg -i arets.sockerbagare.s02e05.avsnitt.5-4364823-svtplay.ts -c copy -bsf aac_adtstoasc arets.sockerbagare.s02e05.avsnitt.5-4364823-svtplay.mp4

the mp4 works with the subtitle
