### ISSUE TITLE
Same name twice and a new ID number on SVT

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#319]
Now when downloading from SVT the file names look like this:
akuten.s01e06.avsnitt.6-77ef4ff-svtplay.ts
and the old one like this:
akuten.s01e06.avsnitt.6-1574558-svtplay.ts

I have notice this on Dokumentärfilm. The file name repeat it self:
mandelblom,.kattfot.och.bla.viol.mandelblom,.kattfot.och.bla.viol-6ab1a68-svtplay.ts
vi.som.diggar.elvis.vi.som.diggar.elvis-0437509-svtplay.ts
jag.ar.min.egen.dolly.parton.jag.ar.min.egen.dolly.parton-8bfb65d-svtplay.ts

I don't know if it is you or SVT that have changed something?

**Comment by spaam** [comment]
yes its a feature since they changed stuff with the id. their new id looks like "324412-32bc"..or something like that. so no more numbers.   can't do anything with it 

the other thing i can fix.
