### ISSUE TITLE
TV4Play - when only premium episodes left it seems to download 'nyheterna'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#320]
If a program only have premium episodes and i use -A, i get episodes from 'nyheterna'
```
svtplay-dl -A http://www.tv4play.se/program/tyst-vittne
```
This is what i have downloaded the 4 latest days:
ekonominyheterna.19.00-3239552-tv4play.ts
nyheterna.19.00-3239548-tv4play.ts
nyheterna.19.00-3241952-tv4play.ts
nyheterna.19.00-3242500-tv4play.ts
nyheterna.22.00-3242197-tv4play.ts
nyheterna.22.00-3242515-tv4play.ts

**Comment by spaam** [comment]
you blame the news for it #313
