### ISSUE TITLE
Request: Possible to add support for http://www.svtplay.se/sista-chansen

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#325]
Hi, not a big deal, but would be nice if it is possible to add support for the sista chansen page at svtplay. http://www.svtplay.se/sista-chansen and further sides such as http://www.svtplay.se/sista-chansen?sida=3 

Nothing urgent, just a request if it can be done.

**Comment by spaam** [comment]
what you are saying it should download everything on that page?

**Comment by qnorsten** [comment]
Yes not a needed feature for most people, but I think it would be nice to have, so you can just download everything on that page.

**Comment by spaam** [comment]
This will only work with -A. like this: svtplay-dl -A http://www.svtplay.se/sista-chansen
