### ISSUE TITLE
"This file is no longer updated" when trying to launch svtplay-dl

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#327]
When I download the latest release from 2016-01-10, I only get the following error message when I execute svtplay-dl via python:
_"This file is no longer updated.
if you still want to use it. go to https://svtplay-dl.se/archive and download the latest one"_

What does that mean? Am I doing something wrong, or what does that message mean?

The release from 2015-08-24 works fine, but I can't get any release after that to run.

I am using Windows 7, and have Python 2.7.6.

**Comment by spaam** [comment]
what it means is that i have remove the binary i had in the repo. if you still want to use the binary you need to go to the page and download the latest one.

sometimes people get confused on what version they are using. if its the one development version or the release version when they say that they are using the one in the repo. that is one of the reasons i removed it.

**Comment by dhofverberg** [comment]
Sorry, I still don't understand. I have downloaded the latest one from the page in question, but still get "This file is no longer updated".

What am I doing wrong, and how should I do this?

**Comment by spaam** [comment]
did you really download the file from https://svtplay-dl.se/archive? 
```
spaam:tmp johan$ wget https://svtplay-dl.se/download/latest/svtplay-dl
--2016-01-12 20:25:08--  https://svtplay-dl.se/download/latest/svtplay-dl
Resolving svtplay-dl.se... 104.31.82.183, 104.31.83.183, 2400:cb00:2048:1::681f:53b7, ...
Connecting to svtplay-dl.se|104.31.82.183|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55984 (55K) [application/octet-stream]
Saving to: 'svtplay-dl'

svtplay-dl                                                     100%[===================================================================================================================================================>]  54.67K  --.-KB/s    in 0.08s

2016-01-12 20:25:09 (649 KB/s) - 'svtplay-dl' saved [55984/55984]
spaam:tmp johan$ ./svtplay-dl  --version
0.30.2016.01.10

**Comment by dhofverberg** [comment]
Yes I did, and it didn't work then. However, I just tried it again and this time it worked. Not sure whether the download was corrupted the last time, or exactly what happened...

**Comment by spaam** [comment]
strange :) good thing it works now :)
