### ISSUE TITLE
DPlay.se - -A will download 52 episodes

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#329]
This new DPlay.se have a totaly new layout and i haven't used it so much but today i noticed this:
```
$ svtplay-dl -S -A http://www.dplay.se/ullared
INFO: Episode 1 of 52
INFO: Outfile: ullared.s7e1.slanger.allt.for.att.sedan.shoppa.nytt-143937-dplay.srt
INFO: Selected to download hls, bitrate: 6350
INFO: Outfile: ullared.s7e1.slanger.allt.for.att.sedan.shoppa.nytt-143937-dplay.ts
[010/253][====...............................................................................................................] ETA: 0:02:47
```
It will download 52 episodes.

You already have an exclude switch, how about adding an include switch so i can include "s7" and only download season 7?

**Comment by spaam** [comment]
you mean a whitelist kind of a thing?

**Comment by Sopor-** [comment]
Kind of...

I even tried to use the switch --all-last=NN but that will not work. It will still download all episodes.

**Comment by spaam** [comment]
hmm okey

**Comment by spaam** [comment]
found the issue with --all-last.. its only defined in some services.

**Comment by Sopor-** [comment]
Great! Maybe it will work then on dplay.se so i don't have to download them all :)
