### ISSUE TITLE
Downloading geo-blocked material from svtplay

### ISSUE THREAD

**Issue by mapinas** [spaam/svtplay-dl#332]
It would be nice if it was possible to download geo-blocked material from svtplay by providing a proxy server address. 

At the moment, however, I don't even think svtplay-dl supports downloading geo-blocked material from within Sweden (?)

**Comment by Sopor-** [comment]
If i'm not wrong, svtplay-dl already support "x-forwarded-for" ?

**Comment by spaam** [comment]
try adding this this in the latest version of the script: 
--http-header "X-FORWARDED-FOR=127.0.0.1"
replace 127.0.0.1 with a ip in .se
