### ISSUE TITLE
Outdated version on Ubuntu 14.04?

### ISSUE THREAD

**Issue by 316097** [spaam/svtplay-dl#334]
Hi, i don't know if I'm directing this to the right forum, correct me if I'm wrong, anyway I'm on Ubuntu 14.04 and svtplay-dl version 0.9.2014.04.27 also it's been a while since I used svtplay-dl, but now when I try to download "Kampen om tungvattnet". I only get a small .mpd file with some info in it.

svtplay-dl http://www.svtplay.se/video/5882636/kampen-om-tungvattnet/kampen-om-tungvattnet-avsnitt-1
INFO: Outfile: kampen-om-tungvattnet-avsnitt-1-svt-play.mpd
[4733/4733][==================================================] INFO: no thumb requested

Am I doing something wrong? Has SVT changed something? Version in Ubuntu repository outdated (most likely)?

**Comment by Sopor-** [comment]
Latest version is 0.30.2016.01.10 and yes, svt have changed a lot since 2014.04.27

**Comment by spaam** [comment]
yes.. stable version of the script in dists can be a but outdated.

**Comment by spaam** [comment]
This should fix the issue https://apt.svtplay-dl.se
