### ISSUE TITLE
Issues with dplay

### ISSUE THREAD

**Issue by zippert** [spaam/svtplay-dl#335]
I cannot seem to download anything from dplay.se, even though it is listed as supported.

Running (as an example):

*svtplay-dl http://www.dplay.se/en-skam-for-sverige-magnus-betner-och-soran-ismail/en-skam-for-sverige-magnus-betner-och-soran-ismail-3/*

yields the output:

*ERROR: That site is not supported. Make a ticket or send a message*

This is the only (type of) link I can find (there are others that are simply redirects to the same type as above) to a specific video.

Leaving out the protocol:

*svtplay-dl www.dplay.se/en-skam-for-sverige-magnus-betner-och-soran-ismail/en-skam-for-sverige-magnus-betner-och-soran-ismail-3/*

yields a different output, a longer stack trace:

*Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 324, in main
  File "/usr/bin/svtplay-dl/svtplay_dl/__init__.py", line 133, in get_media
  File "/usr/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 100, in get
  File "/usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 74, in get_http_data
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: www.dplay.se/100-hojdare/season-6-storslagen-final-hagrar-i-100-hojdare/*

What am I doing wrong?

**Comment by zippert** [comment]
And yes, downloading from svtplay.se (for example) works fine.

**Comment by spaam** [comment]
what version of svtplay-dl do you use ? :)

the first url is right :)

**Comment by zippert** [comment]
0.10.2015.05.24

**Comment by spaam** [comment]
its a bit old. i added support for it in 0.20.2015.10.08 . you need to use that version or a newer one :)

**Comment by zippert** [comment]
Why isn't a newer version available via (standard) repositories? How do I go about updating it if not via apt-get?

**Comment by spaam** [comment]
i have no clue about that sorry. i guess they are lagging a bit behind.
what dist and version do you use ?

**Comment by spaam** [comment]
you can install it via pip as root.
sudo pip install svtplay-dl

**Comment by zippert** [comment]
kubuntu 15.10

**Comment by zippert** [comment]
I cannot seem to download "pip" at all?

**Comment by zippert** [comment]
Do you have your own (updated) repo?

**Comment by spaam** [comment]
not yet. looking into that right now. it will be up in a few days.

**Comment by zippert** [comment]
OK, is there another (manual?) way to update?

**Comment by spaam** [comment]
run sudo apt-get install python-pip
then write: sudo pip install svtplay-dl

it should download the latest version

**Comment by zippert** [comment]
Yep, that did it. Thanks!
