### ISSUE TITLE
Dplay.no and TV2  Sumo

### ISSUE THREAD

**Issue by kooolkat357** [spaam/svtplay-dl#339]
Hi, is it possible to add Dplay.no and  sumo.tv2.no?

**Comment by spaam** [comment]
dplay.no yes. but sumo.tv2.no looks like they use silverlight and they might use drm too. that can be a problem

**Comment by kooolkat357** [comment]
Look  here  http://blogg.tv2.no/sumo/html5-video-sumo-sant/  they´re moving towards html5
