### ISSUE TITLE
dplay.se "That site is not supported"

### ISSUE THREAD

**Issue by johannewman** [spaam/svtplay-dl#340]
Hi, trying to download the latest episode of Ninja Warriors from dplay.se but it says the site is not supported?

root@vps:/homel# svtplay-dl http://www.dplay.se/ninjawarrior/season-2-stockholm-ar-forst-ut
ERROR: That site is not supported. Make a ticket or send a message
root@vps:/homel# svtplay-dl -A http://www.dplay.se/ninjawarrior/season-2-stockholm-ar-forst-ut
ERROR: That site is not supported. Make a ticket or send a message
root@vps:/homel# svtplay-dl -A http://www.dplay.se/ninjawarrior
ERROR: That site is not supported. Make a ticket or send a message

What could the issue be, did dplay.se make any changes to the site?

**Comment by spaam** [comment]
what version is this? old?

**Comment by johannewman** [comment]
When I check I see it's version 0.9.2014.04.27 is not the latest one, sorry
for not checking this first. I installed it from Ubuntu repo a few days ago
and just assumed it was the latest version. Will try to compile the latest
version from git instead. Or is there any easier way to upgrade it?

mån 8 feb 2016 03:44 Johan Andersson <notifications@github.com> skrev:

**Comment by spaam** [comment]
This should fix the issue https://apt.svtplay-dl.se :)
