### ISSUE TITLE
Support for any *.solidtango.com domain

### ISSUE THREAD

**Issue by persand** [spaam/svtplay-dl#343]
Related to this: 

https://github.com/spaam/svtplay-dl/issues/268

https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/solidtango.py#L12

I'd love to see support for any *.solidtango.com domain as there are more Solidtango sites out there.

**Comment by spaam** [comment]
yeah. picsearch have the same issue. i need to figure out a better way to detect things.

**Comment by spaam** [comment]
http://www.dalademokraten.se/allmant/skoter-tv-vi-hittade-sno-och-smygstartar-sasongen-i-skidbacken-2  moar solidtango sites

**Comment by spaam** [comment]
this will be included in the next release if you dont use master.
