### ISSUE TITLE
"Can't find video id"

### ISSUE THREAD

**Issue by gusseleet** [spaam/svtplay-dl#347]
$ python svtplay-dl -v http://www.dplay.se/trevligt-folk-deluxe/season-1-introducing-billy-tang/
DEBUG [1456780953.93] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.dplay.se/trevligt-folk-deluxe/season-1-introducing-billy-tang/
ERROR [1456780954.43] svtplay-dl\svtplay_dl\__init__.py/get_one_media: Can't find video id

I had no trouble with this link yesterday. Something has changed. My guess is that dbplay changed something. I thought you should now.

//Gel

**Comment by gusseleet** [comment]
Update:

Tried a random URL, got this message. 
$ python svtplay-dl --verbose http://www.dplay.se/arga-snickaren-vip/season-3-anders-bagge/
DEBUG [1456781871.33] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.dplay.se/arga-snickaren-vip/season-3-anders-bagge/'                                                                           
DEBUG [1456781871.49] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=159735'                                                                                                                                                                          
DEBUG [1456781931.59] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1456781931.76] svtplay-dl\svtplay_dl\utils\__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/159735?stream_type=hds'
Traceback (most recent call last):
  File "D:\Py\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Py\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dl\__main__.py", line 13, in <module>
  File "svtplay-dl\svtplay_dl\__init__.py", line 352, in main
  File "svtplay-dl\svtplay_dl\__init__.py", line 177, in get_media
  File "svtplay-dl\svtplay_dl\__init__.py", line 190, in get_one_media
  File "svtplay-dl\svtplay_dl\service\dplay.py", line 87, in get
  File "D:\Py\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Py\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Py\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by Sopor-** [comment]
I seems to get the same...

**Comment by spaam** [comment]
thanks for the bug report, this will be included in the next version later this week

**Comment by johannewman** [comment]
Hi,
Tried downloading
http://www.dplay.se/ninjawarrior/season-2-regionsfinalen/
and get, 
ERROR: Can't find video id
I have the latest version, did dplay change something again?

**Comment by klarvu** [comment]
I get:
"ValueError: No JSON object could be decoded"
    on any svtplay.se issue.
It works fine on my ubuntu, but not on my mac. Details for the mac:
$ svtplay-dl --version
0.9.2014.08.28

OSX 10.11.5
Python 2.7.10

Hope you can fix it.

BR  /T

**Comment by spaam** [comment]
klarvu: what version do you use on Ubuntu? Same? Try upgrading to latest version


-- 
Johan Andersson

**Comment by klarvu** [comment]
You got it wrong, it works on my ubuntu (14.04.4) but it does not work on my mac.
Or do you mean that I should upgrade svtplay-dl to the latest version? I think I have done that.

BR/T
