### ISSUE TITLE
dplay problem

### ISSUE THREAD

**Issue by bpmildh** [spaam/svtplay-dl#353]
I try this
svtplay-dl -S -o ~/svtrip/ http://www.dplay.se/gasmamman/season-1-avsnitt-4/
and get
ERROR: Can't find video id

Other streams works.

svtplay-dl version 0.30.2016.02.08

**Comment by spaam** [comment]
this works in master right now. going to release a new version later this week.

**Comment by bpmildh** [comment]
Thanks!
