### ISSUE TITLE
Issue with dplay.no

### ISSUE THREAD

**Issue by eiaro** [spaam/svtplay-dl#359]
First time user, so might be my command.

`$ svtplay-dl http://www.dplay.no/4-stjerners-middag/season-8-episode-40/`
`ERROR: Can't find video id`

Using version on pip: 0.30.2016.02.08

**Comment by spaam** [comment]
this is fixed in the commit eb5e2fe5d44c in master and not in a release. 
I'm going to release a new version later this week with some good fixes :)

if you want to use master you can install the script from source using the setup.py method

thanks for the bug report! :)
