### ISSUE TITLE
"No subtitles available" when there seems to be subtitles available

### ISSUE THREAD

**Issue by dentarg** [spaam/svtplay-dl#363]
```
$ svtplay-dl --require-subtitle http://www.svtplay.se/video/7241917/fallet-o-j-simpson-american-crime-story/fallet-o-j-simpson-american-crime-story-sasong-1-the-dream-team
INFO: No subtitles available
```

But the video do have subtitles:

![screen shot 2016-04-03 at 09 56 29](https://cloud.githubusercontent.com/assets/42626/14231413/714df240-f982-11e5-9ac4-9095114f1835.png)

**Comment by spaam** [comment]
the subtitles is burned into the video and we can't download them separate. i can't see somewhere if its burned into the video or not.

**Comment by Sopor-** [comment]
It is very easy to see on the web page if the subtitle is burned in or not. There is no subtitle button to turn it off/on :)

**Comment by dentarg** [comment]
okay thanks guys :)
