### ISSUE TITLE
SVTPlay - i now get an m4u file

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#365]
Why do i need to use -P to get my file? It must be much better to prefer hls/hds than mp4 and m4u?

```
python svtplay-dl -S http://www.svtplay.se/video/7096711/agenda/agenda-13-mar-21-15
INFO: Outfile: agenda.13.mar.21.15-34a87d1-svtplay.srt
INFO: Selected to download dash, bitrate: 3146
INFO: Outfile: agenda.13.mar.21.15-34a87d1-svtplay.m4a
[32231989/32231989][======================================================================] ETA: complete
INFO: Outfile: agenda.13.mar.21.15-34a87d1-svtplay.mp4
[897337249/897337249][======================================================================] ETA: complete
WARNING: Cant find ffmpeg/avconv. audio and video is in seperate files. if you dont want this use -P hls or hds
```

**Comment by spaam** [comment]
it depends how you see it. the m4a and mp4 is higher bitrate compared to hls and hds. sure  i could remove dash if the user dont have ffmpeg/avconv

**Comment by Sopor-** [comment]
I don't know how many that use this kind of format? I don't even know why SVT have them? I don't get any sound in the mp4 when i play it in Kodi. I do believe most of us want that :)
But until you have added a setting file it would be great if HLS was the highest video it selected by default.

**Comment by spaam** [comment]
i dont see this as an issue.  the warning is telling what is wrong so..
