### ISSUE TITLE
Error message: "Can't access premium content" even though valid account and credentials are used

### ISSUE THREAD

**Issue by SigvardMcKvack** [spaam/svtplay-dl#368]
Hi,

Thank you for your great software.

I have been trying to save a clip from TV4play.se ( http://www.tv4play.se/program/grannar-och-swingers?video_id=3242733 ) without luck. No matter what I try, I keep on getting the error message "Can't access premium content". I have tried with both the --username=user@domain.com --password=password and the -u user@domain.com -p password, but nothing seems to be working.

The verbose log didn't give me anything interesting either. It reaches the "parsing of .xml-file"-part and then throws the error. No matter what I try.

This has of course worked before, with other clips.

Sincerely,

**Comment by SigvardMcKvack** [comment]
I'm using the svtplay-dl version 0.30.2016.02.08 , installed via brew on an OS X machine running version 10.11.4.

**Comment by spaam** [comment]
oh forgot to update that one. i will release a new version later today and i will fix an update for brew with that.

**Comment by SigvardMcKvack** [comment]
Tusen tack för det, Johan! :)

Sound terrific. I will keep a lookout for that version then. In the meantime, is there a newer version that I can compile myself?

Sincerely,

**Comment by spaam** [comment]
you can git clone the repo. type make after that you will get an svtplay-dl binary that you can use :)

**Comment by agent666** [comment]
I have tried to _git clone git://github.com/spaam/svtplay-dl_ and then make but i still get **Can't access premium content**

**Comment by spaam** [comment]
master hav a fix for this and the next version.
