### ISSUE TITLE
Subtitles downloaded on windows system have broken line endings - don't play correctly on Linux

### ISSUE THREAD

**Issue by eekboom** [spaam/svtplay-dl#371]
On my windows machine if I do for example

svtplay-dl -S http://www.svtplay.se/video/7899735/svt-nyheter-pa-latt-svenska/svt-nyheter-pa-latt-svenska-18-apr-17-15

then the resulting srt file has bogus new line characters.
In an editor it shows like

```
1
0:00:06,480 --> 0:00:11,560
Välkommen till

Nyheter på lätt svenska.


2
0:00:11,720 --> 0:00:18,000
Politikern Mehmet Kaplan slutar

som minister i Sveriges regering.
```

When I look at the file with a hex editor, I see that the first text line of each subtitle ends with \0D\0D\0A - which is one new line too many.

When I copy that to my phone then MX Player only ever displays the first line of each subtitle.
(VLC on Windows plays it correctly.)

When I execute the same svtplay-dl command on a Linux machine, then there's only \0D\0A (though the real blank lines that end the subtext are \0D\0A\0A - so there is something fishy with line endings in srt files in svtplay-dl I think).

I used the latest Windows download from https://svtplay-dl.se/archive

**Comment by spaam** [comment]
i should fix that :)

**Comment by spaam** [comment]
master have a fix for this:)
