### ISSUE TITLE
Enter a span of quality bitrate between two values - Feature request

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#372]
# Enter a span of quality bitrate between two values

# Example

svtplay-dl [options] [bitrate value **FROM**], [ bitrate value **TO**] [URL]

svtplay-dl -q 1000, 1600 http://www.tv4play.se/program/lyckliga-gatan?video_id=3292784

**Comment by spaam** [comment]
if there is several options in the span. it will take the highest one?

**Comment by stdlogin** [comment]
OK

**Comment by spaam** [comment]
this will be included in the next relase.
