### ISSUE TITLE
dplay SSL issues?

### ISSUE THREAD

**Issue by larsamannen** [spaam/svtplay-dl#375]
Issues at dplay?

svtplay-dl -S http://www.dplay.se/berg-meltzer-pa-hawaii/season-3-tjejerna-aker-pa-en-farlig-hajk/ --verbose
DEBUG [1461528281.72] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.dplay.se/berg-meltzer-pa-hawaii/season-3-tjejerna-aker-pa-en-farlig-hajk/'
DEBUG [1461528282.08] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.dplay.se/api/v2/ajax/videos?video_id=165292'
DEBUG [1461528282.49] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://geo.dplay.se/geo.js'
DEBUG [1461528282.55] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/165292?stream_type=hds'
DEBUG [1461528283.7] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://sbsvod12-vh.akamaihd.net/z/delivery/0f/bf/0fbf698e-2de5-4cc9-98ac-fa733dbd1a36/SE1048307835527_1_1604141751_,25,6,40,2,60,15,10,00k.mp4.csmil/manifest.f4m?hdnea=st=1461528253~exp=1461528373~acl=/z/delivery/0f/bf/0fbf698e-2de5-4cc9-98ac-fa733dbd1a36/SE1048307835527_1_1604141751_,25,6,40,2,60,15,10,00k.mp4.csmil/*~hmac=0bf8e2b4c203ec3b222b837f3e1e3e1cc9fc467c27a1b628883dd57ed4e22a6c'
DEBUG [1461528283.99] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://secure.dplay.se/secure/api/v2/user/authorization/stream/165292?stream_type=hls'
DEBUG [1461528284.29] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://sbsvod12-vh.akamaihd.net/i/delivery/0f/bf/0fbf698e-2de5-4cc9-98ac-fa733dbd1a36/SE1048307835527_1_1604141751_,25,6,40,2,60,15,10,00k.mp4.csmil/master.m3u8?hdnea=st=1461528254~exp=1461528374~acl=/i/delivery/0f/bf/0fbf698e-2de5-4cc9-98ac-fa733dbd1a36/SE1048307835527_1_1604141751_,25,6,40,2,60,15,10,00k.mp4.csmil/*~hmac=d845ee5b34b1ab13d9e458d5978cd0ed432845da01dba231b481820ec4ef6f32'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 367, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 157, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 196, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/dplay.py", line 98, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py", line 56, in request
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError

**Comment by spaam** [comment]
did you copy the whole output? last line missing some info.

i guess you are running  a version of python that is older then 2.7.9? if so  you need to install these python packages: pyOpenSSL, ndg-httpsclient and pyasn1

**Comment by larsamannen** [comment]
No, that was all. Running on a raspb 1, Python 2.7.9. 
I have all these dependencies.

**Comment by spaam** [comment]
what version of requests?

**Comment by larsamannen** [comment]
2.4.3

**Comment by larsamannen** [comment]
stone age version of pip included in raspbian. After update of pip it works. Closing issue.

**Comment by spaam** [comment]
user fixing their own issue \o/ 
thanks for writing the solution 👍  :)
