### ISSUE TITLE
Possible to autosave all available subtiles from site e.g. urskola.se ? 

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#378]
Hello, 
Would be nice if a feature would be added so all available subtitles from a web page. 
Some shows on Urskola.se for example http://urskola.se/Produkter/170811-The-Game-Numbers has both english and swedish subtitles available. But only the Swedish one got downloaded 
I managed to get it to download the english subtitle by modifying the following line in 
**/lib/svtplay_dl/service/urplay.py b/lib/svtplay_dl/service/urplay.py**
_yield subtitle(copy.copy(self.options), "tt", jsondata["subtitles"][0]["file"].split(",")[0])_
to _yield subtitle(copy.copy(self.options), "tt", jsondata["subtitles"][1]["file"].split(",")[0])_

But I was unable to get it to save both of the subtitles at the same time, but I am not familiar with the code base for svtplay-dl (even though I have tried to look around in it) and just started to learn python so it can possibly be done quite easily. 

I know that there is some problem with naming when downloading all episodes (using the -A parameter) on UR-play that is described in issue https://github.com/spaam/svtplay-dl/issues/373 . Hopefully it might be able to resolve both at the same time.

**Comment by spaam** [comment]
to make this happen we need to rewrite how we download things a bit. right now we only download the first one see https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/__init__.py#L223  we need to just loop the subs list.  but there are some issues. 1, have a option to decide if we want to download every subtitles or only the first one. 2, add a prefix or something to the filename for the subs, if we dont do that. they will be overwritten if we download every subtile.

**Comment by qnorsten** [comment]
Thank you for your quick answer. With the help of that information I actually managed to rewrite the code a bit so it works perfect for urskola at least (have not found any other site with more than one subtitle available for now)
I do not know if it is the prettiest or best solution but nothing else seem to be broken, and I tried to write it as pretty as I could, but I am a extreme beginner at python. 
Only thing left to do is to add an option to download everything (for now it is automaticly downloading everything it can for urskola. 

Could make a pull request or something if you would like to look at it, and see if it can be useful or if it is rubbish. 
Just made it for fun and personal use.

**Comment by Sopor-** [comment]
Are you talking about #147 that i already have asked for since 2014?

**Comment by spaam** [comment]
@Sopor- yes that one..

**Comment by qnorsten** [comment]
Added a pull request for my implementation now https://github.com/spaam/svtplay-dl/pull/379
Probably not the best solution but it work. Feel free to use it Sopor if you want the feature it should fix both this issue and https://github.com/spaam/svtplay-dl/issues/147 .

**Comment by spaam** [comment]
this is in master right now. @qnorsten thanks for the contribution :)
