### ISSUE TITLE
Remuxing not working on windows (need to change ext == ts to ext == .ts

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#380]
Hi just say that a ---remux command had been added to svtplay-dl. But at least on windows it was not working for me. Was just getting an error that something went wrong. 

Managed to pinpoint the error 
the following changes has to be made to_ lib/svtplay_dl/postprocess/__init__.py_
```
-        if ext == "ts":
+        if ext == ".ts":
```

Now everything works perfect but I am not sure if it breaks something on OSX or linux.

**Comment by spaam** [comment]
you are right. thanks ! :)
