### ISSUE TITLE
The switch -P have no option for DASH

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#383]
If i want to prefer one type of stream the DASH is not mentioned in the help text and i do believe a parenthesis is missing at the end.

```
  -P preferred, --preferred=preferred
                        preferred download method (hls, hds, http or rtmp
```
INFO: Quality   Method
INFO: 3278      DASH
INFO: 2793      HLS
INFO: 2793      HDS
INFO: 1940      DASH
INFO: 1677      HLS
INFO: 1677      HDS
INFO: 1142      DASH
INFO: 985       HLS
INFO: 985       HDS
INFO: 729       DASH
INFO: 633       HLS
INFO: 633       HDS
INFO: 524       DASH
INFO: 453       HLS
INFO: 453       HDS
INFO: 400       DASH
INFO: 346       HLS
INFO: 346       HDS
INFO: 275       DASH
INFO: 238       HLS
INFO: 238       HDS

**Comment by spaam** [comment]
you are right :)
