### ISSUE TITLE
Ability to save raw(unconverted) subtitle file as well as the converted (srt) subtitle

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#387]
Hi, I do not know if this is useful for that many people, but me and a friend discussed this program a few days back, and he said that he would like to have this feature, as he would like to do his own conversions of svtplays subtitles to preserve the colors and stuff like that. Similar to what someone requested here : https://github.com/spaam/svtplay-dl/issues/256
I have written some code in my master branch of my fork https://github.com/qnorsten/svtplay-dl that works, and download both the converted srt-file and the raw subtitle file if the parameter --raw-subtitles are used. 

Tried to make the code as good as I could (was very minor changes to the original code), but might have done some mistakes. Add it to the master branch if you think it will be usefull. If not me and my friend will make our custom version of svtplay-dl and use it for this purpose.

**Comment by Sopor-** [comment]
But the raw subtitles don't work in Kodi. You need to convert those color codes if you want them to work in Kodi/VLC.

**Comment by qnorsten** [comment]
My friend prefered to do these kind of convertions him self as he is making DVDs and therefore can not support the font-tags. 
But I have added a --convert-subtitle-colors command now that converts them to <font color=""> tags. Which should be what you requested sopor. 
You can view the code in my masterbranch. 
https://github.com/qnorsten/svtplay-dl

**Comment by spaam** [comment]
this is commited (24a1789) to master :)
