### ISSUE TITLE
Drop support for python2

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#390]
Python 2 is old and only cause issues with unicode things. easier to only support python3.
Ubuntu 16.04 have /usr/bin/python as python3.

**Comment by Sopor-** [comment]
Could i use this [guide](http://ubuntuhandbook.org/index.php/2014/05/install-python-3-3-5-or-3-4-via-ppa-in-ubuntu-14-04-12-04) to install Python 3 on my Ubuntu 14.04?

**Comment by spaam** [comment]
yes. but ubuntu 14.04 already comes with python 3.4 :)

**Comment by Sopor-** [comment]
I only get Python 2.7.6 if i run `python --version`

**Comment by Sopor-** [comment]
I need to run python3 --version, Python 3.4.3. How do i know what version svtplay-dl will use?

**Comment by spaam** [comment]
if you type python3 you will get the version 3. i will change the shebang from "#!/usr/bin/env python" to "#!/usr/bin/env python3" so it will only work on python3 :)

**Comment by qnorsten** [comment]
Go for it. Or is there any platform that is unable to use Python 3 and can only use Python 2?

**Comment by spaam** [comment]
I have no idea. :)

**Comment by qnorsten** [comment]
At least most modern systems should be able to use Python3, If it simplifies the coding, so just drop support. If someone actually needed python2 support, I am sure that they will complain, else it is just less job for you, having to handle all the unicode stuff.

**Comment by iwconfig** [comment]
I see that you are working on threaded downloading. frickin' awesome :) With the upcoming transition to py3, is there any thoughts on async? If i understand this correctly, since an asynchronous call doesn't necessarily create a new thread its wise to use async with multithreading instead of either or. Also, from a module standpoint it would be a headache relief to be able to use `svtplay_dl` asynchronously in other scripts.

**Comment by spaam** [comment]
i didnt see that much of improvements on threaded dash downloads.  im thinking about to test using multiprocess queue and see if that going to gain some speed.  i haven't looked into async stuff that much. i need to find some good way to use it with requests.  its not really decided yet if we going to use threaded or/and async. 

i dont know how people use svtplay_dl in other scripts. the whole get_media with Options is a mess.
i want to rewrite that into some smaller things.

**Comment by spaam** [comment]
master is now py3 only
