### ISSUE TITLE
QuickTime losing a few seconds of audio a few times per minute, causing audio to drift out of sync fast

### ISSUE THREAD

**Issue by drathier** [spaam/svtplay-dl#393]
Is this a problem with QuickTime or the output file? Same file plays without problem on vlc on same mac computer.

**Comment by spaam** [comment]
from where did you download the video? :)

**Comment by drathier** [comment]
http://urskola.se/Produkter/179810-Yrkesmastarna-Resan-till-VM

**Comment by spaam** [comment]
i watched 6 mintues i cant see any out of sync errors. im using quicktime 10.4 (855) and ffmpeg version git-2016-05-04-e3df56f..

**Comment by dentarg** [comment]
I think we should close this one, as we couldn't reproduce. If there's still a problem @drathier, we can re-open. Please provide any useful information you can think of (e.g. what QuickTime version you are using).

**Comment by drathier** [comment]
I reverted to using vlc, which works flawlessly. If it happens again, I'll let you know with a proper bug report. Thanks for an awesome piece of software!
