### ISSUE TITLE
Dplay.se - -A tries to download 89 episodes

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#395]
This seems to be back #262 . If i use -A it will try to download 89 episodes. I have tried
http://www.dplay.se/outsiders/season-11-lik-en-seriefigur and http://www.dplay.se/outsiders but i get the same resault.

```
python svtplay-dl -A http://www.dplay.se/outsiders
INFO: Episode 1 of 89
```

**Comment by spaam** [comment]
this is not really the same thing beacuse its a different site :)
you want all episodes but not really?

**Comment by Sopor-** [comment]
Sorry my bad :)

I want to download all episodes from season 11. Now there is only one but there will be more and how do i then download only that season? All the others have there own page but the latest season will go under `Alla`
