### ISSUE TITLE
nrk.no no longer works

### ISSUE THREAD

**Issue by klagerus** [spaam/svtplay-dl#397]
nrk.no seem to have changed the web page, so that the url is no longer detected

**Comment by sveinhansen** [comment]
I have the same experience. The following patch did it for me:
[nrk-change.patch.txt](https://github.com/spaam/svtplay-dl/files/282852/nrk-change.patch.txt)

**Comment by klagerus** [comment]
Thank you, that seems to do the trick.

**Comment by waltherbans** [comment]
Thanks for the patch. But, since I'm a newbie in this: How do I apply the patch? Is this done before or after compiling? Thanks in advance

**Comment by sveinhansen** [comment]
I have created a pull request on this change for the maintainers of this project. Hopefully it will be part of the next release.

**Comment by spaam** [comment]
i commited the @sveinhansen  pull request. its in master right now and it will be in the next release hopfully tomorrow.
