### ISSUE TITLE
tv4play srt sub file format error?

### ISSUE THREAD

**Issue by 6b6561** [spaam/svtplay-dl#398]
There is an issue with a syntax error in the srt subs saved from tv4play, as an example  http://www.tv4play.se/program/maria-wern?video_id=3294813

The time string in the srt file is missing one trailing digit in the timestamps, end result is that the srt is not accepted by BubbleUPNP on Android streaming to a chromecast. I started investigating this a little and the linux subconverter "subs" is also unable to identify the srt as a proper srt file.

Adding a zero to the timestamps fixed the issue.

Example from downloaded sub:
1
00:00:04,04 --> 00:00:09,48
En man i 60...

Fixed entry:
1
00:00:04,04**0** --> 00:00:09,48**0**
En man i 60...

I have no idea if this issue is in the srt source or if it's something done by svtplay-dl.

As such easy to fix with a one-line sed, but still annoying to have to remember to do it.

`sed 's/[0-9][0-9]:[0-9][0-9]:[0-9][0-9],[0-9][0-9]/&0/g' broken.srt > fixed.srt`

**Comment by spaam** [comment]
thank you for the bug report :D  you can find a fix for this in master and in the next relase tomorrow :)
