### ISSUE TITLE
--force-subtitle pays no respect to -S

### ISSUE THREAD

**Issue by iwconfig** [spaam/svtplay-dl#405]
According to the option description **--force-subtitle** downloads only the subtitle if used with **-S**. This is not true, I get the same result without **-S** using only **--force-subtitle**.

**Comment by iwconfig** [comment]
Maybe that is the point? In that case the description is faulty.

**Comment by spaam** [comment]
it should be like you said. so its a bug somewhere

**Comment by spaam** [comment]
i tried with svtplay and it worked like it should.  what site did you try? using 1.2 ?

**Comment by iwconfig** [comment]
Downloaded latest and did a fresh install three times, two of the tests in virtualenv and i only get the subtitle using **--force-subtitle** alone _**or**_ together with **-S**.

**Comment by dentarg** [comment]
@iwconfig so you solved this in #414?

**Comment by iwconfig** [comment]
i believe so. this issue can be closed.
