### ISSUE TITLE
SVTPlay error messages - solved

### ISSUE THREAD

**Issue by hamkg** [spaam/svtplay-dl#408]
Today I haven't been able to download from svtplay.se. I get the following messages:
ERROR: Can't parse json data from the site
ERROR: Can't find any streams for that url

Have SVTPlay changed something?

**Comment by spaam** [comment]
What version do you use? Latest one?

-- 
Johan Andersson

**Comment by hamkg** [comment]
Nope, my version is at least a year old. Worked perfectly on svtplay a week ago, though, and still works with tv3play/tv8play.

**Comment by fezaland** [comment]
I have the same problem that hamkg had, and I also run an old version. Could someone help me with a step-by-step guide on how to update? I am really worthless when it comes to the Terminal and I can't remember how I got it to work for some year ago... Tried with brew install but it only says I already have the software. I did find the download file for version 1.2 but do not know what to do next... Help?

**Comment by spaam** [comment]
fezaland, what OS do you use?  do you remember how you installed the script?

**Comment by fezaland** [comment]
I use OSX 10.11. I don't remember how I installed it the first time...

**Comment by spaam** [comment]
fezaland, do you see svtplay-dl when you run: brew list | grep svtplay  ?  if it show svtplay-dl. you should run brew update && brew upgrade svtplay-dl .
if it complain about it can't find brew. pip install -U svtplay-dl

**Comment by fezaland** [comment]
Yes it shows, is this what I should run: <brew update && brew upgrade svtplay-dl>
all in one step?

**Comment by fezaland** [comment]
"brew update && brew upgrade svtplay-dl"

**Comment by spaam** [comment]
yes  or you can run those separate :)

**Comment by fezaland** [comment]
Success! Thank You so much!
