### ISSUE TITLE
Request: dplay.dk

### ISSUE THREAD

**Issue by Reconos87** [spaam/svtplay-dl#410]
Hi there.

Is it possible to add a danish support for dplay.dk? Seems to work, but it only downloads 1 subtitle in a language , which ain't Danish.

Thanks in advance

**Comment by spaam** [comment]
what language is it ?  swedish?

**Comment by Reconos87** [comment]
Im not sure if it's norweigan or swedish xD

Example: Jag vill ha en svensk mössa.
-Jag vill ha en 80-talsbil.

-Inte en "Knight Rider".

**Comment by spaam** [comment]
its swedish :D looking at the code i only extract the swedish one. i will fix that. 
thanks for the ticket btw :)

**Comment by Reconos87** [comment]
Looking forward to it! And thanks for the fast replies. Care to throw a comment in this ticket when it's added? Then i'll get an instant notice ;)
