### ISSUE TITLE
brew upgrade svtplay-dl still v.1.1

### ISSUE THREAD

**Issue by noSumo** [spaam/svtplay-dl#415]
When running `brew upgrade svtplay-dl` it says "Error: svtplay-dl 1.1 already installed". Is this correct? What should I do to get 1.2?
Regards,
//S

**Comment by iwconfig** [comment]
It appears the [brew repository only has the 1.1 version](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+svtplay+is%3Aclosed).
Until this is fixed, you can use `git clone https://github.com/spaam/svtplay-dl.git` or [download the zip](https://github.com/spaam/svtplay-dl/archive/master.zip) file and extract it, terminal into the folder and run `sudo python setup.py install`

**Comment by noSumo** [comment]
Thank you for the info @iwconfig.
I'm missing python-request so it didn't work. I'm guessing I would be needing to install all items listed in README. 
I think I'll just wait until BREW is up to date again, seems easier.

**Comment by dentarg** [comment]
@noSumo you can install python from homebrew and then install svtplay-dl with [pip](https://pip.pypa.io/en/stable/), this is what I do since @spaam always publish new releases to [PyPI](https://pypi.python.org/pypi)

```
brew install python
pip install svtplay-dl
```

Also, it isn't that hard to submit a pull request to Homebrew with an updated formula for svtplay-dl 1.2, see https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md#submit-a-123-version-upgrade-for-the-foo-formula

**Comment by noSumo** [comment]
Thank you @dentarg
So anyone can submit a newer version to Homebrew, I didn't know that.

**Comment by noSumo** [comment]
Now i've messed everything up.. :( 
running $svtplay-dl in terminal window now gives me following info:

`Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.2', 'svtplay-dl')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1491, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'svtplay-dl'`

I used "pip install svtplay-dl" and didn't get it to work, the svtplay-dl cmd still used old brew installation.

So I tried running installation from zip-file linked above, now I get the error above and i'm lost...
Do I need to create a script? What should that say?
@dentarg any helpful ideas?

Regards,

**Comment by dentarg** [comment]
I would try to remove everything related to python and svtplay-dl and start over, installing python from homebrew and then svtplay-dl from PyPi (`pip`)

Like 

```
brew uninstall svtplay-dl
pip uninstall svtplay-dl
brew uninstall pyton
```

`brew cleanup` might help too: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-uninstall-old-versions-of-a-formula

Not sure what you did with the zip file and where that put files, but if there a collisions with something in homebrew and/or pip, they usually yell about that (also do `brew doctor` and make sure everything is fine)

**Comment by dentarg** [comment]
But I think we can close this issue, as it isn't strictly the responsibility of this project to sort out. Homebrew works the way homebrew works, by friendly volunteers contributing updates to formulas :-)
