### ISSUE TITLE
https://svtplay-dl.se work but not https://www.svtplay-dl.se

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#418]
If i try to download svtplay-dl and i add www in the URL it won't work. I only see a page from CloudFlare with this error message: Invalid SSL certificate.

**Comment by spaam** [comment]
why do you add www?  :)

**Comment by spaam** [comment]
anyway i have fixed it know. it will be redirecting from www.svtplay-dl.se to svtplay-dl.se

**Comment by Sopor-** [comment]
Many web browser have key combinations to add www. at the front and .se at the end. I was not having any issue with it but maybe some other user will and both should work. WWW is still the correct way to tell it is a home page :)

**Comment by spaam** [comment]
correct and correct  i dont know about that. i just prefer using without WWW. it feels more clean :)
