### ISSUE TITLE
Request: Parameter for destination folder

### ISSUE THREAD

**Issue by fuumind** [spaam/svtplay-dl#419]
I think an option to select a destination folder would make svtplay-dl more usefull. A scenario that comes to mind:
 
svtplay-dl -q 985 -Q 10 -A _-d ~/Video_ [URL]

**Comment by spaam** [comment]
You should be able to do the same thing with -o  ~/Video
try it and see if it works. if not i have to fix it :)

**Comment by Sopor-** [comment]
I use `-o` and it is working for me :)

**Comment by fuumind** [comment]
Awsome! :) Totally missed that. Perhaps a fix in the help page then:

  -o OUTPUT, --output=OUTPUT
                        outputs to the given filename **or folder**

**Comment by spaam** [comment]
@fuumind yes, thanks for pointing that out. i will fix that this weekend :)

**Comment by fuumind** [comment]
Heck, that's the least I can do! That's what open source is about, improving the lives for all of us. Thank you for building and maintaining this software!
