### ISSUE TITLE
viafree.se

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#424]
Tv3-6-8-10 är sammanslaget till viafree.se nått som kommer/går att fixa?

**Comment by spaam** [comment]
@agent666 javisst

**Comment by spaam** [comment]
master har en fix för att tanka hem enskild video..  -A kommer snart förhoppningsvis :)

**Comment by spaam** [comment]
finns med i master nu med -A och kommer med i en ny version imorgon :) tack så mycket :)

**Comment by spaam** [comment]
med -A verkar videon få samma namn. fixar det senare idag

**Comment by agent666** [comment]
Jag får alltid hem det senaste avsnittet än om jag väjer ett annat.. :S

**Comment by agent666** [comment]
Hämtar jag manuellt via ffmpeg med m3u8 filen får jag rätt klipp...

**Comment by spaam** [comment]
spännande :)

**Comment by agent666** [comment]
Haha... Nä inte så...
