### ISSUE TITLE
ERROR: Can't find authenticity_token needed for user / password

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#425]
I have a problem with svtplay-dl where I try to dl from tv4play which worked great before. But now I just got this:

`p0ff-iMac:~ p0ff$ svtplay-dl -o ernst -u my-mail-adress -p my-passwd http://www.tv4play.se/program/sommar-med-ernst?video_id=3464672
ERROR: Can't find authenticity_token needed for user / password`

Any idea how to solve?

**Comment by spaam** [comment]
what version do you use?  i made some improvements in 1.1 for this.

**Comment by yabbah** [comment]
`p0ff-iMac:~ p0ff$ svtplay-dl --version
1.2`

How can I completely remove svtplay-dl and re-install it from brew? Even as I dont think it wont work, as I had 1.1 and got that error message. So I installed 1.2 manually. But maybe good to start over anyway :)

**Comment by yabbah** [comment]
Installed it on another machine (centos), same error appear. :/

**Comment by perphilip** [comment]
I get the same error on a windows X machine.

**Comment by spaam** [comment]
master have a fix for this and it will be available in the next bundle
