### ISSUE TITLE
Feature request - flowonline.tv

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#429]
Flowonline is a VOD service that some of the semi-large newspapers in Sweden use. Seems like they're only using HLS for their video content. For movies they host subtitles separately from flow-app-production.s3.amazonaws.com. 

This might be a interesting service to implement?

**Comment by spaam** [comment]
sure i can take a look at it :)

**Comment by MR-2** [comment]
@spaam thanks, i would be really grateful if you did. Also from my experience from these services i have noticed that googles is caching these kinds of sites pretty often. So sometimes it can be possible to retrieve a clip or movie from a cached version provided by i.e google even if the movie/clip has been "removed" from the news site. I don't know if this is possible with any other services that svtplay-dl is supporting but for me that would be another interesting feature to implement in svtplay-dl.

**Comment by spaam** [comment]
do you have an example of one of those caching videos?

**Comment by MR-2** [comment]
Here is an [example](http://webcache.googleusercontent.com/search?q=cache:LxeaWxpGZcEJ:unt.flowonline.tv/embed/video/montalbano-1/+&cd=1&hl=sv&ct=clnk&gl=se) with video and subtitle, all available even it has expired.

**Comment by spaam** [comment]
did you get that from flowonline.tv or google?

**Comment by MR-2** [comment]
Got that from a google search and then i choose to look at the cached version since i got a 403 error from the live site.

**Comment by MR-2** [comment]
Nice work! @spaam
