### ISSUE TITLE
Viafree - Impossible to only download one season

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#439]
When using -A it started to download 190 episodes. I then tried to use this path (i included the season) but it was the same result, 190 episodes :(

```
$ svtplay-dl -A http://www.viafree.se/program/livsstil/lyxfallan/sasong-21
INFO: Episode 1 of 190
INFO: Selected to download hls, bitrate: 1080
INFO: Outfile: lyxfallan.s1e3-3566-tv3play.ts
[026/266][======................................................................] ETA: 0:00:43
```

If i have used http://www.viafree.se/program/livsstil/lyxfallan i do understand it will download all episodes (and that is great if that is possible) but if i include the `sasong-21` it should only download season 21.

On Dplay.se i can take episode 1 and it will then download the whole season if i use -A.
Will download season 7:
`svtplay-dl -A http://www.dplay.se/sofias-anglar/season-7-bygga-upp-sina-liv-igen/`
Will download season 6:
`svtplay-dl -A http://www.dplay.se/sofias-anglar/season-6-hon-vill-inte-salja-sin-och-anders-drom/`

I believe i can take any episode in a season and it will download that season with -A, but i haven't tested it though.

**Comment by spaam** [comment]
but -A means All episodes. the dplay one sounds like a bug. maybe we sound if we can add season based one..

**Comment by jockeliten** [comment]
Hey,
When using viafree.se it's working like clockwork. But whenever using viafree.dk nothing works to get. Not even when using a VPN or not using a VPN.

"http://www.viafree.dk/programmer/mad/masterchef-dessert/saeson-1/episode-1 -s
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
"
I have the latest. Btw, viafree.no works fine.

**Comment by Malmis** [comment]
I had a similar "problem", but from tv4play. I already got a few shows earlier. So i didn't want to download them again, then i used:

`svtplay-dl -A --exclude=3015056,3013282,3013085,3010522 http://www.tv4play.se/program/blablashow`

just to get all the others. I excluded them with the ID for each episode.

**Comment by Sopor-** [comment]
A few yes, but i get almost 200 episodes with -A. I do use --exclude when i want to exclude "teckenspråk" from svt play :)

**Comment by qnorsten** [comment]
@spaam  I wrote some code for this for my own personal use the other day. Do you think it should be merged into master, or is it better to work on add some other command to download specific seasons, as -A stand for everything?

**Comment by spaam** [comment]
@qnorsten i guess it can be a good thing :)

**Comment by qnorsten** [comment]
This should be solved in https://github.com/spaam/svtplay-dl/commit/1dbe3155865e879bd7b96b3894f69bac329bdf96 
It can easily be changed to use a specific season command if spaam decides to implement it.
