### ISSUE TITLE
Viafree.dk unable - but works on .se and .no

### ISSUE THREAD

**Issue by jockeliten** [spaam/svtplay-dl#440]
Hey,
When using viafree.se it's working like clockwork. But whenever using viafree.dk nothing works to get. Not even when using a VPN or not using a VPN.

"http://www.viafree.dk/programmer/mad/masterchef-dessert/saeson-1/episode-1 -s
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
"
I have the latest. Btw, viafree.no works fine.
As a side note, it works watching the episode in the browser. Such as any content on the danish website.

VERBOSE

ERROR: version: -unknown
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "svtplay-dll/__main__.py", line 13, in <module>
  File "svtplay-dll/svtplay_dl/__init__.py", line 436, in main
  File "svtplay-dll/svtplay_dl/__init__.py", line 169, in get_media
  File "svtplay-dll/svtplay_dl/__init__.py", line 216, in get_one_media
  File "svtplay-dll/svtplay_dl/service/viaplay.py", line 84, in get
  File "/svtplay-dll/svtplay_dl/service/viaplay.py", line 70, in _get_video_id
KeyError: 0

**Comment by spaam** [comment]
thank you for the bugreport. :)

**Comment by jockeliten** [comment]
Hm, this did not work for me. I tried to change the file. I did not make it work on the Mac. Is there any way to do this in command? (Newbie).

**Comment by qnorsten** [comment]
Just download the latest master. Spaams fix should be better then what I proposed. Or is there some problem with the latest master?

**Comment by jockeliten** [comment]
Hi! I will try this, having a bit of issues with the svtplay-dl to work at the moment.
Whenever using play-dl-master-2/bin/svtplay-dl http://www.viafree.dk/programmer/reality/robinson-ekspeditionen/saeson-18/episode-1 it displays ERROR: That site is not supported. Make a ticket or send a message. Sth’s up with my mac can’t download the latest master. (Sorry, I am a newbie at this).

**Comment by spaam** [comment]
this will be fixed in few hours. im building a new release right now and will update brew and other packet managers.

**Comment by jockeliten** [comment]
Thank you! Great job btw! Have a good week!

**Comment by jockeliten** [comment]
Is there anything I have to do, update some software or will this be “automatic"?

**Comment by jockeliten** [comment]
Ignore my previous comment. It works wonders! Thanks for the help! (Followed instruction from terminal sudo pip install.
