### ISSUE TITLE
Move away from .pod

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#442]
perl--

**Comment by olof** [comment]
perl++ :)

But as long as we remember why we use pod: to generate manual pages...

**Comment by spaam** [comment]
yes.. but i have no idea how to fix the issue with https://github.com/spaam/svtplay-dl/blob/master/svtplay-dl.pod#--merge-subtitle-merge-subtitle-with-videoaudio-file-with--m

right now it looks bad..

**Comment by spaam** [comment]
i guess the diff_man_help.sh is the issue here.

**Comment by olof** [comment]
Is this what you mean? https://github.com/spaam/svtplay-dl/commit/b9d341d52facbd2bc4deaa2f976ddb56402caf47

What is the problem?

**Comment by spaam** [comment]
run make release with that pull request and you going to see the issue :)

**Comment by spaam** [comment]
erh. i mean make doctest :)

**Comment by spaam** [comment]
#464 fixed the issue.. closing this :D
