### ISSUE TITLE
Problems with Viafree

### ISSUE THREAD

**Issue by AnonNoob1919** [spaam/svtplay-dl#447]
Hi!

I am having issues downloading a single episode from Viafree. 

If I run `svtplay-dl.exe "http://www.viafree.se/program/reality/paradise-hotel--1/sasong-6/avsnitt-3"` the script seems to download a random season each time.

Is there any way for me to specify what season or video ID in particular I am interested in without having to edit the script?

**Comment by AnonNoob1919** [comment]
Resolved.

As long as you know how to find the video ID of a particular episode yourself with Chrome Dev Tools, all you need to do is replace "sasong-6/avsnitt-3" with that ID.

**Comment by Sopor-** [comment]
But you should be able to use:
```
svtplay-dl http://www.viafree.se/program/reality/paradise-hotel--1/sasong-6/avsnitt-3
```
to download an episode or what do you say about it @spaam?
I did some test and it seems to download from different seasons but still episode 3.

**Comment by spaam** [comment]
master have a fix for this. i will release a new version later this week
