### ISSUE TITLE
SVTplay - sista chansen - Couldn't retrieve episode list

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#451]
"Couldn't retrieve episode list"
Suspect that they have changed: GridPageStore/GridPage again?

**Comment by spaam** [comment]
nope. they changed from using " to '. the script is looking for ". because of the changed. it could not find the info :) but i will fix this after work today :)

**Comment by MR-2** [comment]
Does the sista chansen work with this fix? because i'm getting this error message now KeyError: 'GridPageStore'

**Comment by spaam** [comment]
that is another issue :)

**Comment by spaam** [comment]
master have a fix for that now :)

**Comment by MR-2** [comment]
Me so happy:)
