### ISSUE TITLE
increase size of text when merging

### ISSUE THREAD

**Issue by Christley** [spaam/svtplay-dl#459]
this is the command i use:
`svtplay-dl -S -M --remux --force http://www.svtplay.se/video/2333222/de-kloka-faglarna`

this is how large the text will be when merging:
http://i.imgur.com/QZwsTLn.png

this is how large the text will be if i merge it manually using a tool like mkvtoolnix or letting vlc or plex display the file itself:
http://i.imgur.com/3y6gIrX.png

the text is out of sync on the 2nd picture which is why it shows different pictures, but its the same episode.

using svtplay-dl 1.5 and latest ffmpeg as of 2016-09-25 00:56. using windows 10 aswell.
can the merge feature merge with a larger preset size?

**Comment by spaam** [comment]
this feels like an VLC bug with the subtitles size.
with mpv it shows like https://svtplay-dl.se/stuff/mp4-mpv-sub.png
and with QuickTime: https://svtplay-dl.se/stuff/mp4-qt-sub.png
