### ISSUE TITLE
missing site urskola.se

### ISSUE THREAD

**Issue by Skankhunter42** [spaam/svtplay-dl#460]
Hello.

Is it possible to include the site urskola.se as a a supported site?

**Comment by MR-2** [comment]
It's supported.

**Comment by Skankhunter42** [comment]
Are you shure? 

urplay.se is supported but not urskola.se when I tried yesterday with the latest build 1.5.

**Comment by MR-2** [comment]
Check out [here](https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/urplay.py).
urskola.se is listed under supported domains

**Comment by MR-2** [comment]
Which url did you try with?

**Comment by Skankhunter42** [comment]
This

http://urskola.se/Produkter/165903-Har-har-du-din-mat-Om-skrapmat

Can you get it to work?

**Comment by MR-2** [comment]
That works for me:). What error messages do you get when you add --verbose?

**Comment by Skankhunter42** [comment]
I did it at home on os x and I got "unsupported site".

I haven't tried it on windows.

**Comment by Skankhunter42** [comment]
And I can't run the program from work and try it on windows.

Maybe a os x problem?

**Comment by MR-2** [comment]
Shouldn't be an issue on any OS. But try to reproduce the error with --verbose and post the output here.

**Comment by Skankhunter42** [comment]
Here's what I get when I use it on osx

$ svtplay-dl http://urskola.se/Produkter/165903-Har-har-du-din-mat-Om-skrapmat --verbose
DEBUG [1474899249.08] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://urskola.se/Produkter/165903-Har-har-du-din-mat-Om-skrapmat'
ERROR [1474899249.12] /usr/local/Cellar/svtplay-dl/0.20.2015.11.29/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_media: That site is not supported. Make a ticket or send a message

**Comment by MR-2** [comment]
You're not running latest version you're running 0.2. Latest is 1.5

**Comment by spaam** [comment]
@Skankhunter42 run brew update  and brew upgrade, it will fix the issue :)
