### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by scansweden** [spaam/svtplay-dl#462]
V:\>c:svtplay-dl.exe --version
1.5

V:\Bibliotekstjuven>c:svtplay-dl.exe --verbose http://www.svtplay.se/video/9282157/bibliotekstjuven/bibliotekstjuven-avsnitt-1
DEBUG [1475500477.2890482] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\uti
ls\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/9282157/biblio
tekstjuven/bibliotekstjuven-avsnitt-1'
DEBUG [1475500477.6590483] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\uti
ls\__init__.py/request: HTTP getting 'http://www.svt.se/videoplayer-api/video/11
36298-001A'
DEBUG [1475500477.806548] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\util
s\__init__.py/request: HTTP getting 'http://svtplay4p-f.akamaihd.net/z/se/open/2
0160622/1136298-001A/PG-1136298-001A-BIBLIOTEKSTJUVEN-01_,988,240,348,456,636,16
80,2796,.mp4.csmil/manifest.f4m'
DEBUG [1475500478.1255946] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\uti
ls\__init__.py/request: HTTP getting 'http://svtplay4f-f.akamaihd.net/d/se/open/
delivery/20160622/1136298-001A/dash-ondemand/PG-1136298-001A-BIBLIOTEKSTJUVEN-01
-1a894f3d-36c0-336d-e488-632004cd699a-ondemand.mpd?alt=http%3A%2F%2Fswitcher.cdn
.svt.se%2F1136298-001A.mpd'
DEBUG [1475500478.2546203] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\uti
ls\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1136298-001A.mp
d'
DEBUG [1475500478.3806455] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\uti
ls\__init__.py/request: HTTP getting 'http://svtplay4d-f.akamaihd.net/d/se/open/
delivery/20160622/1136298-001A/dash-live/PG-1136298-001A-BIBLIOTEKSTJUVEN-01-1a8
94f3d-36c0-336d-cc4c-b2d8c0006d6a-live.mpd'
ERROR [1475500478.3991492] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__i
nit__.py/get_one_media: version: 1.5
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 444
, in main
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 178
, in get_media
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 225
, in get_one_media
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\service\svtplay.py", l
ine 119, in get
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\fetcher\dash.py", line
 42, in dashparse
AttributeError: 'NoneType' object has no attribute 'text'
svtplay-dl returned -1

V:\Bibliotekstjuven>

**Comment by spaam** [comment]
master have a fix for this. going to release a new version later tonight

**Comment by spaam** [comment]
1.6 have fixes for this
