### ISSUE TITLE
sverigesradio.se stopped working

### ISSUE THREAD

**Issue by falknes** [spaam/svtplay-dl#467]
Currently it seems that sverigesradio.se has stopped working. 

This is what i get when i try downloading using svtplay-dl==1.5

- svtplay-dl https://sverigesradio.se/sida/avsnitt/786606?programid=1650 --verbose
- ..env/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://sverigesradio.se/sida/avsnitt/786606?programid=1650'
- ..env/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_one_media: Can't find audio info

**Comment by WangElectronics** [comment]
I have this error on MacOS with svtplay-dl ver. 2.1

ERROR: No videos found. Can't find audio info

**Comment by kalaskitte** [comment]
Same error for me... version 2.1 running ubuntu

**Comment by spaam** [comment]
@WangElectronics @kalaskitte please open a new ticket instad next time. this is closed and from 2016 :)  i have open a ticket #1033  now for this new issue.
