### ISSUE TITLE
-A not working, crash

### ISSUE THREAD

**Issue by noSumo** [spaam/svtplay-dl#468]
Tried latest fix: #466 since I hade same problem.
Now svtplay-dl crashes.

`USER:~USER$ svtplay-dl -A -S -P hds --exclude=syntolkat -o /url/url/url/mr-robot http://www.svtplay.se/mr-robot` 
`INFO: Episode 1 of 4` 
`ERROR: svtplay-dl crashed` 
`ERROR: Run again and add --verbose as an argument, to get more information` 
`ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues`
`ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue`
`USER:~ USER$ svtplay-dl -A -S -P hds --exclude=syntolkat --verbose -o /url/url/url/mr-robot http://www.svtplay.se/mr-robot`
`DEBUG [1475690612.78] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request:` `HTTP getting 'http://www.svtplay.se/mr-robot'`
`INFO [1475690613.3] /usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_all_episodes:` `Episode 1 of 4`
`DEBUG [1475690613.3] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request:` `HTTP getting u'http://www.svtplay.se/video/10196847/mr-robot/mr-robot-sasong-2-avsnitt-9'`
`DEBUG [1475690613.38] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request:` `HTTP getting u'http://www.svt.se/videoplayer-api/video/1375327-009A'`
`DEBUG [1475690613.43] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request:` `HTTP getting u'http://svtplay20m-f.akamaihd.net/i/se/open/20160908/1375327-009A/PG-1375327-009A-MRROBOT2-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1375327-009A.m3u8'`
`DEBUG [1475690613.85] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1375327-009A.m3u8'`
`DEBUG [1475690613.96] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed2.cdn.svt.se/vod/_definst_/amlst:20160908/1375327-009A/PG-1375327-009A-MRROBOT2-02/playlist.m3u8'`
`DEBUG [1475690613.99] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay20b-f.akamaihd.net/d/se/open/delivery/20160908/1375327-009A/dash-live/PG-1375327-009A-MRROBOT2-02-becc0b97-6e5f-336d-9f2f-7faea6f9d414-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1375327-009A.mpd'`
`ERROR [1475690614.42] /usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.5`
`Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 176, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 204, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 125, in get
    streams = dashparse(self.options, self.http.request("get", i["url"]), i["url"])
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 42, in dashparse
    audiourl = urljoin(baseurl, i.find("{urn:mpeg:dash:schema:mpd:2011}BaseURL").text)
AttributeError: 'NoneType' object has no attribute 'text'
`
`USER:~ USER$ pip uninstall svtplay-dl`
`Uninstalling svtplay-dl-1.5:`

Reinstalling ended up with #466  error again.

Any other files than services/svtplay.py that a fix should be applied to?

**Comment by spaam** [comment]
1.6 have fixes for this
