### ISSUE TITLE
Live?

### ISSUE THREAD

**Issue by durian** [spaam/svtplay-dl#47]
Is there a way to get this working with the live "broadcasts" from svt? ( I mean http://www.svtplay.se/kanaler/svt1). I tried with and w/o the --live option, but to no avail....

(It's probably silly because most of it will be downloadable later, but I still wonder :-) )

-peter

**Comment by noSumo** [comment]
Any updates on this feature? e.g.. Live "svt/kanaler"
I get error "ERROR: This is a live HLS stream, and they are not supported."
//s

**Comment by insurw** [comment]
Is this feature dead/not possible anymore? I was looking forward to do some live rips. Specially Kalle Anka on julafton.

**Comment by MR-2** [comment]
@insurw #chrippa/livestreamer/issues/1258

**Comment by spaam** [comment]
i had something working-ish. but there was some issues when outputting the stream to stdout instead of a file.   maybe i should remove that option. 

but with  svt/kanaler is it will never end. need to have som kind of option to stop after X something.

**Comment by durian** [comment]
To a file with an option to specify the number of minutes maybe? Would suit me....

**Comment by dalgr** [comment]
@spaam Hello,

I have created a hack that supports svt live stream('kanaler') 
Link: https://github.com/dalgr/svtplay-dl

It is enabled when using '-c' or '--capture_time' capture_time define capture time in minutes of a live stream (only for svt-play)

Manuel testing with(worked for all tests below):
`
python svtplay-dl -c 1 https://www.svtplay.se/kanaler/svt1 --force
python svtplay-dl -c 60 https://www.svtplay.se/kanaler/svt1 --force
python svtplay-dl -c 1 https://www.svtplay.se/kanaler/svt2 --force
python svtplay-dl -c 1 https://www.svtplay.se/kanaler/svt24 –force
`

This hack is meant as a way to add support for svt live stream'kanaler', this is no final solution, I will gladly receive feedback on parts to improve.

**Comment by insurw** [comment]
@dalgr Not sure if it's possible but being able to set start time would be nice. Maybe a online capping feature that sets svtplay-dl into idle mode and activates at a specific time and date or when the stream contains a specific title/word.

**Comment by dalgr** [comment]
@insurw For now you can create the same behavior with the 'at'(used to schedule one task) command in windows(https://technet.microsoft.com/en-us/library/bb490866.aspx) and linux(https://tecadmin.net/one-time-task-scheduling-using-at-commad-in-linux/)

**Comment by spaam** [comment]
svtplay got live support using HLS in 1.9.7..  yay? :)
