### ISSUE TITLE
URPlay - downloading with -A

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#470]
When i was trying to download 'Grym kemi' i used this url and as you can see it found 20 programs to download but i can't even find 20 programs on the page. Some of them was even radio and i do see one radio at the bottom of the page.

```
python svtplay-dl -S -A http://urplay.se/program/193584-grym-kemi-njutning
INFO: Episode 1 of 20
```

**Comment by spaam** [comment]
this is because of the rss thing in urplay.py

**Comment by spaam** [comment]
cant find a good way to fix this without getting other videos as well.
