### ISSUE TITLE
Make it easier to download episodes with -A

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#480]
Many sites have changed their sites and when i use -A it will download all episodes. I know -A stands for all but it worked much better before when i could download all episodes or only all from season 2 depending on the URL i used. Now i can't do that anymore, not even on SVTPlay will it work.
So if you could find out a great way to add this into svtplay-dl it would be great :)

**Comment by spaam** [comment]
#550 fixed this issue. please try it out.

**Comment by Sopor-** [comment]
@spaam i can't find anything about `--include-clips` when i run `--help` and how do i use it with season?
Dplay.se do have seasons too but when i press on the season the URL won't change so how do i download only one season from dplay or this will only work on svtplay?
