### ISSUE TITLE
tv3play.lt now redirects to play.tv3.lt

### ISSUE THREAD

**Issue by tomasvilda** [spaam/svtplay-dl#482]
tv3play.lt now redirects to play.tv3.lt, please add this domain to supported list.

**Comment by spaam** [comment]
thanks for the bug report. i have commited a fix for this in master, next version will have a fix for this. :)

**Comment by spaam** [comment]
i will release that version tomorrow or saturday.

**Comment by priiduonu** [comment]
and tv3play.ee redirects to tv3play.tv3.ee

**Comment by spaam** [comment]
@priiduonu  next version will have support for it
