### ISSUE TITLE
python-svtplay-dl 1.7 and svtplay-dl 1.7 dependancy issue.

### ISSUE THREAD

**Issue by danielholm** [spaam/svtplay-dl#484]
Trying to install svtplay-dl from APT repo (https://apt.svtplay-dl.se/) in Ubuntu 16.04, but there is a dependancy issue. 

svtplay-dl depends on python-svtplay-dl but they can't both be installed due to the file "/usr/bin/svtplay-dl" being in both of them.

**Comment by spaam** [comment]
this was fixed when i relased 1.8
