### ISSUE TITLE
Get all all episodes (-A) not working _svtplay.se

### ISSUE THREAD

**Issue by noSumo** [spaam/svtplay-dl#485]
Can't get -A to work..

```
/usr/local/bin/svtplay-dl -A -g http://www.svtplay.se/labyrint
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 176, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_all_episodes
    episodes = stream.find_all_episodes(options)
  File "/usr/local/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 238, in find_all_episodes
    items = dataj["videoTitlePage"]["realatedVideoTabs"]
KeyError: 'realatedVideoTabs'
```

Installed version, 1.7

**Comment by MR-2** [comment]
Works fine for me with current master version.

**Comment by qnorsten** [comment]
I think commit #17c1ff4 is a fix for this error. So try current master instead of the released 1.7 version.

**Comment by noSumo** [comment]
Thank you @qnorsten & @MR-2 will give current master a try. Just need to figure out how install it correctly... ;)

**Comment by noSumo** [comment]
Help needed, please...  How can I install a "Master" version over current, 1.7 using "pip install upgrade" or pip install?
Clean "pip install" from zip doesn't work either. 
`pip install svtplay-dl --no-index --find-link file:/Users/noSumo/Downloads/svtplay-dl-master.zip`

**Comment by qnorsten** [comment]
Seems svtplay updated their api or something again. 
__reduxStore needs to be changed to __svtplay in the find_all_episodes function in services/svtplay.py

**Comment by spaam** [comment]
master have a fix for this. 1.8 the next version will have a fix for it.
