### ISSUE TITLE
Correct version for Ubuntu? 

### ISSUE THREAD

**Issue by gusseleet** [spaam/svtplay-dl#487]
When I try to update svtplay-dl via apt-get I get:

`svtplay-dl is already the newest version (0.30.2016.02.08-1).`

Is this really the newest version? Seems like some functions/errors is different then on my Windows version Mac version (1.1)

**Comment by Sopor-** [comment]
I download master so i always have the latest version/changes. Try that instead @gusseleet

**Comment by spaam** [comment]
in the official ubuntu repo have an old version.. best way is to use  pip or https://apt.svtplay-dl.se/

master can be broken.
