### ISSUE TITLE
Sista chansen - Couldn't retrieve episode list.

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#488]
`svtplay-dl -g -A http://www.svtplay.se/sista-chansen --verbose
DEBUG [1477516036.09] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/sista-chansen'
ERROR [1477516036.91] /usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py/find_all_episodes: Couldn't retrieve episode list`

**Comment by Sopor-** [comment]
SVT have updated their API again.

**Comment by spaam** [comment]
master have a fix for this. 1.8 the next version will have a fix for it.
