### ISSUE TITLE
Failed to download from SVT: AttributeError

### ISSUE THREAD

**Issue by ecsfang** [spaam/svtplay-dl#490]
The following link failed on both Windows and Linux. Updated and build from the latest source didn't help.

**$ svtplay-dl --verbose http://www.svtplay.se/video/10848033/gudstjanst-fran-lunds-domkyrka-med-pave-franciskus/gudstjanst-fran-lunds-domkyrka-med-pave-franciskus-31-okt-14-30**

DEBUG [1477947828.13] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/10848033/gudstjanst-fran-lunds-domkyrka-med-pave-franciskus/gudstjanst-fran-lunds-domkyrka-med-pave-franciskus-31-okt-14-30'
DEBUG [1477947828.43] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1374632-002A'
DEBUG [1477947828.68] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'https://svt07-b.akamaized.net/u/svt07.mpd?start=1477920600&end=1477928700&pevi=1374632-002A'
ERROR [1477947828.91] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.7-6-g7c7542e
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 178, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 225, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 127, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 61, in dashparse
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 71, in parsesegments
AttributeError: 'NoneType' object has no attribute 'attrib'

**$ svtplay-dl --version**
1.7-6-g7c7542e

**Comment by spaam** [comment]
oh interesting.  thanks for the bug report. :)

**Comment by spaam** [comment]
there is a fix for this in master. i will do some more testing tomorrow and release a new version with the fix.

**Comment by ecsfang** [comment]
Thanks for the quick response! :)

But, strangly enough, it works today! Yesterday it failed on two different machines (same version on win+linux), but today it works on the same machines without any update on my side. And reading your comment, I suspect that you also saw the problem yesterday.
Could it have been something on the SVT site? The link pointed to a (then) just released show ... ?

**Comment by spaam** [comment]
i guess the issue you (and i) had yesterday was because of they had this live event and the just copy the segments with the pope and made it available on the website.   today they made some changes and made it as a normal video (vod).

why it crashed was because the .mpd playlist looked a bit different from the ones i have seen before.  

thanks for the bugreport :)

**Comment by ecsfang** [comment]
Yes, that might explain it :)

No problem, happy to help!
