### ISSUE TITLE
Issue with SVTPlay-dl on www.svtplay.se - 

### ISSUE THREAD

**Issue by IVOx64** [spaam/svtplay-dl#492]
I think svtplay.se have change something in there services www.svtplay.se

You can´t download full episodes any longer with version 1.7 of svtplay-dl, only single episodes!

**svtplay-dl.exe -q 100 -Q 1000 -A http://www.svtplay.se/video/10829221/plus/plus-avsnitt-5-3?start=auto**

ERROR: Couldn't retrieve episode list

 =========================================================
 SourceURL
 =========================================================
http://svtplay1h-f.akamaihd.net/d/world/open/delivery/20161027/1372503-005A/dash-live/PG-1372503-005A-PLUSHOST2016-03-5717cb2a-8960-4bcb-9cbb-d405f071225f-1a894f3d-44cc-336d-47c1-49a19efd9e49-live.mpd?alt=http://switcher.cdn.svt.se/1372503-005A.mpd
 =========================================================
 
 =========================================================
 SVTPlay-DL Version
 =========================================================
1.7

**Comment by MR-2** [comment]
Check out #[485](https://github.com/spaam/svtplay-dl/issues/485)

**Comment by spaam** [comment]
this is fixed in latest version
