### ISSUE TITLE
ERROR: Can't access premium content

### ISSUE THREAD

**Issue by Johanledin** [spaam/svtplay-dl#496]
Hej!

Försöker ladda ned Bonde söker fru:
svtplay-dl http://www.tv4play.se/program/bonde-s%C3%B6ker-fru?video_id=3133812

Felmeddelande:
ERROR: Can't access premium content

Finns det någon fix för detta?

**Comment by Sopor-** [comment]
Det är bara att ta fram plånboken @Johanledin och betala TV4 om du vill se premium innehåll.

**Comment by qnorsten** [comment]
Du måste skaffa ett premiumkonto och sen använda -u <användarnamn> och -p <lösenord> för att ladda ned programmet. Finns tyvärr inget annat sätt just nu

**Comment by Johanledin** [comment]
Okej tack! då vet jag :-)
