### ISSUE TITLE
Got cmore to work?

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#502]
I tried rip down Gåsmamman s02e01 from cmore, 
http://www.cmore.se/serie/72596-gasmamman/sasong-2/episod-1/3581973-gasmamman
but got message that site dont supported. So I pulled up a ticket :)

Could it be fixed?

**Comment by MR-2** [comment]
Cmore have DRM-protection on all their streams so I would close this issue and re-open it if that changes. Note. The subtitles are still available without encryption

**Comment by Sopor-** [comment]
I have tried to download the subtitles but i only get this message:
ERROR: That site is not supported. Make a ticket or send a message

**Comment by MR-2** [comment]
svtplay-dl don't have any support for cmore whatsoever. My earlier post is just pointing out that the subtitles are available and that there is nothing hindering anyone from downloading them. With that said, svtplay-dl doesn't have support for downloading subtitles from cmore. One way to find the subtitles is thru the the developers tool in your web browser.

**Comment by spaam** [comment]
#567 we have some support for this now in master and it will be part of 1.9.5
