### ISSUE TITLE
Fail to get subtitle from URplay.se

### ISSUE THREAD

**Issue by pythonuser3856** [spaam/svtplay-dl#504]
Hi,
Extracting subtitles from URplay.se has ceased to work.

When tracing svtplay-dl execution it seems as if URplay.se has changed subtitle format to ".vtt" which seems to not be recognized by svtplay-dl. When looking at the code I see support for ".tt" but not for ".vtt".
As far as I can tell my comment applies to all links at URplay.se where the video has subtitles.
One example link is:
http://urplay.se/program/197034-cityliv-pa-taken-buenos-aires

**Comment by Sopor-** [comment]
Viafree have also change format to vtt.
Btw, when using -g -S to get the url to the subtitle it seems to be cut off like this
`//undertexter.ur.se/197000-197999/197034-18.vtt`

**Comment by pythonuser3856** [comment]
Yes, the "http:" is for some reason gone missing. That's easy to fix,
though.
As a temporary fix I changed the "tt" identification to select the
"wrst" execution.
It produces an .srt file with a slightly incorrect content which I fix
manually using Subtitle Edit. I can live with that for now, I get my
subtitles.

**Comment by spaam** [comment]
master have a fix for this.  it will be in the next version.

**Comment by pythonuser3856** [comment]
Great !
/L-B
