### ISSUE TITLE
TV4 Play problem

### ISSUE THREAD

**Issue by khazod** [spaam/svtplay-dl#515]
Using v1.8 trying to download video from tv4 play. Video will download but not the asked video, you'll get a video from tv4 crew that says that the version of player isn't supported any longer and needs to be updated.

**Comment by Sopor-** [comment]
Should already be fixed #498 and it is working for me running 1.8-9-gde055b8

**Comment by khazod** [comment]
I believe I only have to fix that, since I'm just a beginner I'll try to solve it.
Using Mac and homebrew says I'm on latest version (1.8)

URL http://www.tv4play.se/program/familjen-annorlunda?video_id=2259088

**Comment by Sopor-** [comment]
That was funny... It was the same episode i did my own test on :) It should be fixed in version 1.8.

**Comment by khazod** [comment]
Haha ^^

I'll give it another try tomorrow! Thanks

**Comment by khazod** [comment]
Force removed all earlier versions thru brew, installed again, works satis! Thanks
