### ISSUE TITLE
Is it possible to download only subtitles?

### ISSUE THREAD

**Issue by MrYakobo** [spaam/svtplay-dl#519]
This is what the help command says:

```
  -S, --subtitle        download subtitle from the site if available
  -M, --merge-subtitle  merge subtitle with video/audio file with
                        corresponding ISO639-3 language code. use with -S for
                        external also.
  --force-subtitle      download only subtitle if its used with -S
  --require-subtitle    download only if a subtitle is available
  --all-subtitles       Download all available subtitles for the video
  --raw-subtitles       also download the subtitles in their native format
```

Which switches do I need to download **only** the subtitle? (effectively seperating the subtitle from the video) My goal is to translate a prorgram by extracting the subtitles, mowing it through Google Translate and finally merge with video again.

Oh and by the way, this program rocks ass!! My family and I are lovin' it ❤️🥇

**Comment by Sopor-** [comment]
You will use -S and --force-subtitle
```
svtplay-dl -S --force-subtitle http://www.svtplay.se/video/10696487/veckans-brott/veckans-brott-sasong-13-avsnitt-1
INFO: Outfile: veckans-brott.s13e01.avsnitt.1-81f7cdb-svtplay.srt
```

**Comment by MrYakobo** [comment]
Thank you. It seems like there are different types of subtitles, optional subtitles and "merged" subtitles. [These turkish series](http://www.svtplay.se/forvaxlingen), for example, has the subtitles rendered onto the mp4 itself sadly... so RIP my translation.

**Comment by MR-2** [comment]
@MrYakobo a bit OT but have you considered OCR?

**Comment by MrYakobo** [comment]
@MR-2 Actually no! I have absolutely zero experimence with OCR though, but I guess I could try it. The (non-translated) series are available on Youtube, so it's pretty open in that sense. Though, it seems like SVT are the only guys that have translated the series into a language that translates to English... Google Translate aren't all that great on Turkish lol. 💃
But seriously, if I OCR would work, one could easily transpile that text through Google Translate and get English translation... thank you for the tip :)

**Comment by MR-2** [comment]
@MrYakobo I would argue that most automated translation programs are still pretty poor. There's a reason why there still are people who is actively work as translators, this profession would have been automated by now otherwise. OCR and automated translation would only help you a bit on the way, you would still have to do some work yourself if you would like a good end result.
