### ISSUE TITLE
Just get aac stereo sound?

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#522]
Hi there, I download from svtplay or tv4play, but I never get their 5.1 sound-streams. Is there a way I can get them within svtplay-dl ?

**Comment by spaam** [comment]
do they have 5.1 sound?  i didnt know that

**Comment by yabbah** [comment]
If I watch them using svtplay on plex I get 5.1 sound. But maybe that is emulated? Now you make me feel like a idiot, haha :P

**Comment by spaam** [comment]
Do you have a video that is 5.1 on plex and is also available on svtplay? i can always check do see if i can see if there is any streams for it :)
no need to feel like a idiot :)

**Comment by yabbah** [comment]
Yes I have 'Innan vi dör' from yesterday in Plex with 5.1 sound. But its a *cough* downloaded release from a torrentsite, maybe ripped from TV then. I ripped it from svtplay with svtplay-dl and I only got AAC Stereo.

**Comment by spaam** [comment]
I guess the other video source you used came from the TV with 5.1 sound. i cant find it on the webpage =/

**Comment by yabbah** [comment]
Okey, thanks for checking it out tho. :)

**Comment by dentarg** [comment]
Sounds like there's not immediate plans from SVT to add 5.1 sound to SVT Play, see 
https://kontakt.svt.se/guide/horbarhet-och-bakgrundsljud

> Allt ljud på SVT och på SVT Play sänds i stereo. Men vi gör även allt fler produktioner med multikanalsljud, vanligast så kallat 5.1-ljud. För att kunna lyssna på multikanalsljud behövs en hemmabioanläggning samt att du tar emot programmen via våra HD-sändningar.

**Comment by dentarg** [comment]
Same for TV4 Play: https://www.tv4play.se/support#humany-tv4play=/584/vad-har-tv4-foer-ljudkvalite/

> Vad har TV4 för ljudkvalité?
> Vi har 2.1-ljud på alla våra plattformar.
