### ISSUE TITLE
Dont download srt

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#523]
Hi, dont know if this is a bug in svtplay-dl or at viafree. But I try to download subtitles for season 13 of Geordie Shore at viafree. Its text on each episode on their site, but when I download I just got for ep01.

I tried with this
svtplay-dl -A -S --force-subtitle --all-subtitles http://www.viafree.se/program/reality/geordie-shore/sasong-13/

It then download srt for all seasons, but this issue just accour on season13ep02 and above. Can you digg into it and see if you see any issue? :)

Regards and thanks for a wonderful application.
//Niklas

**Comment by spaam** [comment]
1.8 have the issue . master have a fix for this. i will release a new version on saturday :)

**Comment by yabbah** [comment]
Ah wonderful, thanks :)

**Comment by yabbah** [comment]
I tried with 1.9 now: svtplay-dl -S --force-subtitle http://www.viafree.se/program/reality/geordie-shore/sasong-13/avsnitt-2

Dont download the srt, just seems working but nothing happens.

**Comment by yabbah** [comment]
Sorry, It worked, just took 5 minutes on some episodes. Not your fault I think :)

**Comment by spaam** [comment]
haha good it worked great on my osx computer. .was going to try it on windows :)
