### ISSUE TITLE
KeyError: 'titlePagePath'

### ISSUE THREAD

**Issue by iwconfig** [spaam/svtplay-dl#528]
I get the following error:
`File "/usr/local/lib/python3.6/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'`

I guess they have changed their json.

**Comment by hrefsnes** [comment]
Getting the exact same error, using svtplay-dl 1.9. It worked just a few days ago, so they must have just changed it.

**Comment by iwconfig** [comment]
It seems to have been changed to programTitle, but when I edit this in `svtplay.py` nothing happens. The `output` variable is correct. Character encoding problem?

**Comment by spaam** [comment]
@iwconfig "nothing happens" .. sounds like we cant find any videos :)

**Comment by iwconfig** [comment]
@spaam the url is working.
`iwconfig:~/workspace $ svtplay-dl http://www.svtplay.se/video/10698871/korrespondenterna/korrespondenterna-sasong-14-avsnitt-1 --verbose
DEBUG [1485369813.5] /usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/10698871/korrespondenterna/korrespondenterna-sasong-14-avsnitt-1'`

That is all i get.

**Comment by spaam** [comment]
yeah . i guess they changed the name "videoReferences" also.  in that part of svtplay.py we search for the video :)

**Comment by iwconfig** [comment]
oh, right :) but it seems "VideoReferences" isn't changed.. btw shouldn't i get an KeyError if they've changed that key also? I can't see anything changed with its subkeys either

**Comment by spaam** [comment]
no. on line 54 we have  `if "videoReferences" in janson["video"]`   it check if we have the key videoReferences inside janson["video"].   if it cant find it. it will not go inside of that condition :)

**Comment by hrefsnes** [comment]
Seems this is what they changed the json to

{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "http://jsonschema.net",
	"required":false,
	"properties":{
		"context": {
			"type":"object",
			"id": "http://jsonschema.net/context",
			"required":false,
			"properties":{
				"popoutUrl": {
					"type":"string",
					"id": "http://jsonschema.net/context/popoutUrl",
					"required":false
				},
				"posterImage": {
					"type":"string",
					"id": "http://jsonschema.net/context/posterImage",
					"required":false
				},
				"programTitle": {
					"type":"string",
					"id": "http://jsonschema.net/context/programTitle",
					"required":false
				},
				"programVersionId": {
					"type":"string",
					"id": "http://jsonschema.net/context/programVersionId",
					"required":false
				},
				"thumbnailImage": {
					"type":"string",
					"id": "http://jsonschema.net/context/thumbnailImage",
					"required":false
				},
				"title": {
					"type":"string",
					"id": "http://jsonschema.net/context/title",
					"required":false
				}
			}
		},
		"statistics": {
			"type":"object",
			"id": "http://jsonschema.net/statistics",
			"required":false,
			"properties":{
				"broadcastDate": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/broadcastDate",
					"required":false
				},
				"broadcastTime": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/broadcastTime",
					"required":false
				},
				"category": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/category",
					"required":false
				},
				"client": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/client",
					"required":false
				},
				"context": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/context",
					"required":false
				},
				"folderStructure": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/folderStructure",
					"required":false
				},
				"mmsCategory": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/mmsCategory",
					"required":false
				},
				"mmsClientNr": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/mmsClientNr",
					"required":false
				},
				"programId": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/programId",
					"required":false
				},
				"statisticsUrl": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/statisticsUrl",
					"required":false
				},
				"title": {
					"type":"string",
					"id": "http://jsonschema.net/statistics/title",
					"required":false
				}
			}
		},
		"videoId": {
			"type":"number",
			"id": "http://jsonschema.net/videoId",
			"required":false
		},
		"video": {
			"type":"object",
			"id": "http://jsonschema.net/video",
			"required":false,
			"properties":{
				"availableOnMobile": {
					"type":"boolean",
					"id": "http://jsonschema.net/video/availableOnMobile",
					"required":false
				},
				"live": {
					"type":"boolean",
					"id": "http://jsonschema.net/video/live",
					"required":false
				},
				"materialLength": {
					"type":"number",
					"id": "http://jsonschema.net/video/materialLength",
					"required":false
				},
				"position": {
					"type":"number",
					"id": "http://jsonschema.net/video/position",
					"required":false
				},
				"subtitleReferences": {
					"type":"array",
					"id": "http://jsonschema.net/video/subtitleReferences",
					"required":false,
					"items":
						{
							"type":"object",
							"id": "http://jsonschema.net/video/subtitleReferences/0",
							"required":false,
							"properties":{
								"url": {
									"type":"string",
									"id": "http://jsonschema.net/video/subtitleReferences/0/url",
									"required":false
								}
							}
						}
					

				},
				"videoReferences": {
					"type":"array",
					"id": "http://jsonschema.net/video/videoReferences",
					"required":false,
					"items":
						{
							"type":"object",
							"id": "http://jsonschema.net/video/videoReferences/0",
							"required":false,
							"properties":{
								"bitrate": {
									"type":"number",
									"id": "http://jsonschema.net/video/videoReferences/0/bitrate",
									"required":false
								},
								"playerType": {
									"type":"string",
									"id": "http://jsonschema.net/video/videoReferences/0/playerType",
									"required":false
								},
								"url": {
									"type":"string",
									"id": "http://jsonschema.net/video/videoReferences/0/url",
									"required":false
								}
							}
						}
					

				}
			}
		}
	}
}

**Comment by iwconfig** [comment]
@hrefsnes try indenting the json/code (each newline), its easier to read :)

@spaam ah yes, of course.. :) but is it looking for "videoReferences" in the React JSON or the generated JSON from `http://svtplay.se/video/blahblah?output=json`? I thought it was the latter which is where "videoReferences" are, so i guess they've removed "videoReferences" from the React JSON

**Comment by Sopor-** [comment]
They have at least changed the videoTitlePage from `realatedVideosTabs` to `relatedVideosTabs`

**Comment by spaam** [comment]
@iwconfig im thinking about taking the programVersionId key value from the video and get the video from the page http://api.svt.se/videoplayer-api/video/programVersionId-value just like what the page is doing now :)

@Sopor- ahh good catch. time to check everything with svtplay what we support now :)

**Comment by HakanSor** [comment]
Works good in version 1.7 and earlier, but not in version 1.8 and 1.9
Tested with url http://www.svtplay.se/video/12051382/vanligen-lars-lerin/vanligen-lars-lerin-sasong-2-avsnitt-3

**Comment by Zcalman** [comment]
Tried to download with version 1.7 on windows aswell and it worked. Just for info.
