### ISSUE TITLE
Program suddenly starts crashing

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#536]
Hi, i installed svtplay-dl on my OS X El Capitain in December. It has worked smoothly up until yesterday. 

When I try to download anything from svtplay.se I get the following text:

ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

The strange thing is that dowloading from SVT:s other site oppetarkiv.se still works without any problems.

**Comment by iwconfig** [comment]
Yes, check out #528. This has been resolved in the the latest version.

**Comment by ijbh** [comment]
Ok thanks. I'm a novice when it comes to all of this lol. Do I understand it correctly that I have to install an older version of the app, 1.7 or older? And could you please explain how I do that on mac? All I know is the following command in terminal:

brew install svtplay-dl

What do I type in if I wanna install a specific older version?

I'm sorry if these are stupid questions lol.

**Comment by spaam** [comment]
I have made a pull request at brew so they will get the new version.  Hope fully it will get fixed today :)

-- 
Johan Andersson

**Comment by ijbh** [comment]
Ok thank you! :)

**Comment by ijbh** [comment]
Is it possible you could post a notification so we know when we can install the latest version through brew? :)

**Comment by spaam** [comment]
sure. where do you want that notification? i can tweet about when i get a notification when they have merged it :)

**Comment by ijbh** [comment]
Sure that's great. What is your twitter?

**Comment by spaam** [comment]
https://twitter.com/j0hanandersson :)

**Comment by ijbh** [comment]
Thank you! Your service is great :)

**Comment by ijbh** [comment]
Can I ask another dumb question lol?

When I type "brew install svtplay-dl" I get the following message:

> Error: You must `brew link rtmpdump` before svtplay-dl can be installed

I Think it's strange because I never installed rtmpdump to begin with. Anyway, I typed "brew link rtmpdump" and got the following message:

> Error: Could not symlink lib/librtmp.dylib
> Target /usr/local/lib/librtmp.dylib
> already exists. You may want to remove it:
> rm '/usr/local/lib/librtmp.dylib'
> 
> To force the link and overwrite all conflicting files:
> brew link --overwrite rtmpdump
> 
> To list all files that would be deleted:
> brew link --overwrite --dry-run rtmpdump

What is the best way going forward without screwing everything up? :D

**Comment by iwconfig** [comment]
I don't use osx but I think you can safely run it since its a dependency which means it's already installed from an earlier installation of svtplay-dl via brew and it's an older version already installed. Either that or svtplay-dl was installed from elsewhere (source code maybe?). Go ahead

**Comment by imist** [comment]
To update something that's already have been installed with brew earlier, you run brew update rather than brew install. So try "brew update svtplay-dl".

**Comment by ijbh** [comment]
Aah....it all makes sense now. Thank you!
