### ISSUE TITLE
KeyError when attempting to --list-quality

### ISSUE THREAD

**Issue by winterflags** [spaam/svtplay-dl#537]
> svtplay-dl --list-quality --verbose http://www.svtplay.se/video/12051082/aktuellt/aktuellt-22-jan-21-00
> DEBUG [1485534598.37] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12051082/aktuellt/aktuellt-22-jan-21-00'
> ERROR [1485534598.8] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
> Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
>     get_media(urls[0], options)
>   File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
>     get_one_media(stream, options)
>   File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
>     for i in streams:
>   File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
>     self.options.output = self.outputfilename(janson, self.options.output)
>   File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
>     name = data["video"]["titlePagePath"]
> KeyError: 'titlePagePath'

**Comment by spaam** [comment]
this is fixed in 1.9.1. i have made an pulll request to brew to update that verstion.  thank you for the bug report <3

**Comment by winterflags** [comment]
Thanks for the awesomely quick reply!
