### ISSUE TITLE
Options().output missing filename extension

### ISSUE THREAD

**Issue by iwconfig** [spaam/svtplay-dl#540]
I need to set the absolute path to svtplay-dl but unlike the standalone script, when `Options().output` is set I only get `/tmp/blah/complex file name` instead of `/tmp/blah/complex file name.ext`. When standalone, the correct extension is appended. When module, it is not.

Also btw, `self.flexibleq` in `Options()` needs the default value of `False` instead of `None`.

**Comment by spaam** [comment]
do you have a test case or something for the first thing?  
```
import svtplay_dl
print(svtplay_dl.__version__)
options = svtplay_dl.Options()
options.output = "/tmp/kalle.anka/hahaha"
geturl = "http://www.svtplay.se/klipp/12141178/polisen-satsar-pa-att-oftare-gora-kontroller-dar-man-vet-att-rattfyllerister-finns"
svtplay_dl.setup_log(options.silent, options.verbose)
svtplay_dl.get_media(geturl, options)
```

will output
```wasted:svtplay-dl-test johan$ python grej.py
1.9.1
INFO: Selected to download dash, bitrate: 3029
INFO: Outfile: /tmp/kalle.anka/hahaha.m4a
[9/9][===============================================================================================================================================================================================================================] ETA: 0:00:00
INFO: Outfile: /tmp/kalle.anka/hahaha.mp4
[9/9][===============================================================================================================================================================================================================================] ETA: 0:00:00
INFO: Merge audio and video into /tmp/kalle.anka/hahaha.mp4
INFO: Merging done, removing old files.```

i have commited a fix for flexibleq.. thansk for reporting that :)

**Comment by iwconfig** [comment]
yes i do, but hmm.. how strange! i can swear it did not work this morning but now it does... and i have not made any changes (at least what i can remember haha #trött). oh well, lets close this. thanks :)

**Comment by iwconfig** [comment]
I think I know what caused this. I suspect i had set a path name something like `/tmp/SVT nyheter 17.15` where `.15` is treated as an extension which i blindly didn't think of at the time. This is not problem when downloading via HDS/HLS since its a single file but when using DASH it fails after the audio file.

    iwconfig:/tmp/test $ svtplay-dl -S -q 260 -o "/tmp/test/SVT Nyheter 17.asd" http://www.svtplay.se/video/12517544/svt-nyheter-pa-latt-svenska/nyheter-pa-latt-svenska-22-feb-17-15
    INFO: Outfile: /tmp/test/SVT Nyheter 17.srt
    INFO: Selected to download dash, bitrate: 260
    INFO: Outfile: /tmp/test/SVT Nyheter 17.asd
    [48/48][======================================================================================] ETA: 0:00:00
    INFO: Outfile: /tmp/test/SVT Nyheter 17.asd
    ERROR: File (/tmp/test/SVT Nyheter 17.asd) already exists. Use --force to overwrite
    INFO: Merge audio and video into /tmp/test/SVT Nyheter 17.asd
    ERROR: Something went wrong: /tmp/test/SVT Nyheter 17.m4a: No such file or directory

    iwconfig:/tmp/test $ ls
    SVT Nyheter 17.asd  SVT Nyheter 17.srt

This of course means `SVT Nyheter 17.asd` only contains audio. This is also the case if path name extension is set to `.mp4`

With this figured out, i don't think this is intended? Why not search the path name for an extension and if there is one that matches either .ts, .mp4 and i guess .m4a (for audio from SR?), else append the correct one regardless of e.g. the .asd extension in this case.
