### ISSUE TITLE
Downloads are "crap files"

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#545]
I've had a problem several times downloading from svtplay where the downloaded movies files are crappy versions of the original video. These contain a grey image and have no sound (you can't see anything in it). Sometimes it will just be small movies (maybe 10 mb) and sometimes they are the same size as the original would be. 

It has never been a permanent problem though. It seems like you can always download the correct version 24 hours after the original upload. Does anyone know if SVT puts up different versions at different times? It is still a problem though because I need to get the movies as soon as they have been broadcast.

Interested in knowing if anyone else has had the same problem!

**Comment by spaam** [comment]
intressting. does it happen to dash? ts? hds? all of them ?

**Comment by ijbh** [comment]
Dash? Hds?

I use terminal on mac OS to download. I only have svtplay-dl and ffmpeg downloaded. I download all sorts of programs from SVT and its mp4-files in 99 percent of cases. 

The file I'm trying to download right now is an mp4-file. Im attaching a screenshot. It is one of those that appears to be the normal video except the image is blurred (the audio works fine).

[IMG]http://i63.tinypic.com/2usvhwl.png[/IMG]

**Comment by spaam** [comment]
can you share the url to the video?

**Comment by ijbh** [comment]
http://www.svtplay.se/video/12132702/gomorron-sverige/gomorron-sverige-31-jan-06-25?tab=senast

**Comment by spaam** [comment]
nice. it looks like the init file might be wrong here. init file have the info about how the video should look like.

**Comment by spaam** [comment]
it download the wrong init file that is why it looks bad :)

**Comment by spaam** [comment]
i will release a new version with some fixes tomorrow evening or thursday

**Comment by ijbh** [comment]
Awesome. Thanks!

**Comment by ijbh** [comment]
Could you give me a heads up in this thread once it's possible to upgrade to the new version in brew? So I don't have to keep downloading that big file several times? :)

**Comment by spaam** [comment]
@ijbh sure :)

**Comment by ijbh** [comment]
So, just like I said, I was now able (24 hours later) to download the correct video. Both image and sound work perfectly. And I have not updated the app.

Strange huh?

**Comment by spaam** [comment]
@ijbh you can find the updated version in brew now :)
