### ISSUE TITLE
Feature request: Add command to include clips when using -A 

### ISSUE THREAD

**Issue by qnorsten** [spaam/svtplay-dl#549]
I think it would be a good idea to add an command to include clips when using -A, might be named --include-clips or something similar. 
Would be useful for at least svtplay and viafree, that adds some bonus clips not found in the original show. 
For svtplay it can probably share most of the code with a solution for #514. 
In that case for svtplay 
*using -A and --include-clips would download every episode as well as all the clips
*using -A on the ?tabs=klipp url would download just all the clips

**Comment by spaam** [comment]
thats sounds like a thing to do.  the tabs thing can also fix #480 if you only want downloading one season with some modifications.

**Comment by qnorsten** [comment]
Yep:) Viafree should be easy to implement. I am not sure about how much work is needed for the tabs though. Is there any other site that uses clips in a similar way, that should also be included?

**Comment by qnorsten** [comment]
Would also be great if it could be used with an episode on viafree to only download the associated clips also 
such as using --include-clips on https://www.viafree.se/program/reality/ung-och-bortskamd/sasong-1/avsnitt-8 and only grab the clips associated to that episodes by checking the relatedEpisodeId.
Maybe utilise that in the generation of the autonaming process so one can see which episode the clip belongs to.

**Comment by spaam** [comment]
do people want to do that?

**Comment by qnorsten** [comment]
Well I would want do that in some cases, but that is just me. I can not speak for anyone else. 
But it is not as important as the other stuff. The most important part for me is to do not have to download each clip manually.

**Comment by qnorsten** [comment]
I wrote up a little something for viafree that works for me to include and name the clips for the whole show. 
It is available in https://github.com/qnorsten/svtplay-dl in case anyone is interested. 

It does not include the functionality to just grab the clips for just one episode as mentioned in https://github.com/spaam/svtplay-dl/issues/549#issuecomment-276650479 as it might be overkill to try and implement something like that. 

For svtplay and tab support I will wait and see if spaam writes up anything, as I am not sure what the best way to accomplish that is.
