### ISSUE TITLE
Cant download from tv4play from today.

### ISSUE THREAD

**Issue by yabbah** [spaam/svtplay-dl#552]
Since today tv4 seems to changed their way to offer tv4play.se. And now I cant download (tried Farmen e21). I tried use the -u and -p to provide my account info, but dont work either. I use 1.9.1

**Comment by spaam** [comment]
did you get any error message or something? :)

**Comment by spaam** [comment]
it works for me with 1.9.1

**Comment by yabbah** [comment]
Sorry, it was that damn 'little snitch' bugging. I tried download from remote (ssh), so I didn't noticed the popup. :(
