### ISSUE TITLE
SVT and "melodifestivalen" creates gibberish video but OK audio

### ISSUE THREAD

**Issue by AliensInc** [spaam/svtplay-dl#556]
It all seems OK when downloading it and the A/V merge is OK but the final MP4 is corrupt.
![svtplay-dl-mello-fuckup](https://cloud.githubusercontent.com/assets/25713237/22857944/a94cab98-f0b0-11e6-8fa4-660066bbb11e.png)
This is what the video looks like, also looked the same on the previous episode but seems OK with stuff like "vetenskapens värld". Audio is OK though.
Using v1.9.1 on Windows and trying to set up a Linux machine to see what if that works....

**Comment by spaam** [comment]
this is fixed in a previous ticket. i will release a new version later today with the fix. thanks for the ticket <3

**Comment by spaam** [comment]
1.9.2 have a fix for this :)
