### ISSUE TITLE
Some error in video 45 mins into "mello"

### ISSUE THREAD

**Issue by AliensInc** [spaam/svtplay-dl#562]
Hi again.
Once again there seem to be a problem in the video handling, something svt did or such I don't know.
45mins 11sec in it hangs and all after that ain't working properly. Did the rip twice and got the exact same problem.
Using v1.9.2

//AI

**Comment by spaam** [comment]
what mello video did you try with? :)

**Comment by AliensInc** [comment]
The one today, ep 3

**Comment by spaam** [comment]
i dont see this "some error". can you be a bit more verbose? you can write it in swedish if you prefer that.

**Comment by AliensInc** [comment]
Spelaren "fryser" och inget efter den tiden går att se.
Det går att "spola" in efter 45:12 men det visas bara en stillbild, 
inget ljud och ibland så "avslutas" spelningen helt,
dvs som om man skulle ha tryckt på 'stop'.

Kör med VLC 2.2.4

**Comment by AliensInc** [comment]
Tried it now and I got this:

svtplay-dl.exe http://www.svtplay.se/video/12366498/melodifestivalen/melodifestivalen-2017-deltavling-3-18-feb-20-00-1?start=auto --verbose
DEBUG [1487607676.1298609] site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12366498/melodifestivalen/melodifestivalen-2017-deltavling-3-18-feb-20-00-1?start=auto'
ERROR [1487607676.538728] site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.2
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 461, in main
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 192, in get_media
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 239, in get_one_media
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\service\svtplay.py", line 43, in get
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\service\svtplay.py", line 237, in outputfilename
KeyError: 'accessServices'
Failed to execute script svtplay-dl

**Comment by spaam** [comment]
@AliensInc we have a ticket for that #566 :)

**Comment by dentarg** [comment]
Hard to reproduce as the video is no longer available, so I will close.
