### ISSUE TITLE
Crash trying to download latest agenda show on Windows 10 - KeyError 'accessServices'

### ISSUE THREAD

**Issue by Zoomer1988** [spaam/svtplay-dl#566]
Hello. Faced this issue while trying to download latest agenda. Maybe something has changed on the SVT's side? Downloaded and remuxed many times before.

D:\svtplay>svtplay-dl http://www.svtplay.se/video/12366630/agenda/agenda-sasong-13-19-feb-21-15?start=auto --verbose
DEBUG [1487591882.8241553] site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12366630/agenda/agenda-sasong-13-19-feb-21-15?start=auto'
ERROR [1487591882.870278] site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.2
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 461, in main
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 192, in get_media
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\__init__.py", line 239, in get_one_media
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\service\svtplay.py", line 43, in get
  File "site-packages\svtplay_dl-1.9.2-py3.5.egg\svtplay_dl\service\svtplay.py", line 237, in outputfilename
KeyError: 'accessServices'
Failed to execute script svtplay-dl

**Comment by iwconfig** [comment]
I get the same error. I guess its a change in their json. My output is a little more verbose for some reason:

    #...........
      File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.2-py2.7.egg/svtplay_dl/service/svtplay.py", line 47, in get
        self.options.output = self.outputfilename(janson["video"], self.options.output)
      File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.9.2-py2.7.egg/svtplay_dl/service/svtplay.py", line 240, in outputfilename
        if data["accessServices"]["audioDescription"]:
    KeyError: 'accessServices'

**Comment by spaam** [comment]
yup they did that and changed the key from "accessServices" to "accessService"

**Comment by Zoomer1988** [comment]
Yeah, I've got the same error output under Ubuntu. I've also noticed that some older agenda and other random videos still downloaded fine. Probably it's only this one.

**Comment by iwconfig** [comment]
@Zoomer1988 I think your your agena url has an optional audio description version also (syntolkad) so other videos without audio description works fine

**Comment by Zoomer1988** [comment]
Oh, that explains why other videos work then.

**Comment by spaam** [comment]
do people like to download syntolkad and teckentolkat videos?

**Comment by AliensInc** [comment]
Is it possible to write the keys into a XML or such so anyone can change them?
In this case the small change is just a letter and that can easily be found when checking the web page source.

**Comment by spaam** [comment]
im working on a fix for this right now.  :)  should be fixed later today :)

**Comment by iwconfig** [comment]
@spaam why not? I mean there has to be at least someone, at least for someone. does svtplay often make changes to this feature?
i second that @AliensInc, i thought of something similar, like `--json >janson.json` tag and `-i janson.json`

**Comment by spaam** [comment]
@iwconfig they have made some changes the last couple of months compared to before.
yeah true i have an idea for this syntolkat thing.

**Comment by AliensInc** [comment]
For my _original_ error in #562.

I downloaded the source on my CentOS machine and remarked the 2 'IF' lines with the invalid key,
compiled it, ran it and got the mp4 and m4a, moved them to win10 and used ffmeg to join them. and now it works.
Will be waiting for the update though 👍
