### ISSUE TITLE
tv4 premium moving to cmore.se

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#567]

**Comment by agent666** [comment]
Tror du de blir möjligt att ladda ned premium i fortsättningen?

**Comment by spaam** [comment]
det hoppas jag. just nu har inte tv4 premium innehållet drm. så det är najs :)

**Comment by tooobe** [comment]
Betyder det att det ska gå att ladda ner tv4 program från cmore? För det funkar inte för mig 🙁
Har premium...

**Comment by qnorsten** [comment]
TV4 premium innehållet på cmore har inte drm så det borde vara möjligt att ladda ned, men funktionaliteten för att spara ned detta är inte tilllagt i svtplay-dl än. Även om jag tror spaam jobbar på det.

**Comment by agent666** [comment]
Spaam hur går det?

**Comment by spaam** [comment]
@agent666 sakta. men ska fixa det ikväll. har inga andra planer så blir att koda koden ikväll.

**Comment by agent666** [comment]
De blir ingen fix för detta?
