### ISSUE TITLE
Merge svtplay-dl into youtube-dl?

### ISSUE THREAD

**Issue by fnadde42** [spaam/svtplay-dl#577]
I really like `svtplay-dl` and the vast support of sites that comes with it but I immediately ask myself why this is a separate tool from for example `youtube-dl`. Are there some problems that prohibits these projects to be merged as one? From a user perspective it would be a hell of a lot easier to just use one tool for every site.

**Comment by spaam** [comment]
In the beginnig i wrote svtplay-dl just to learn python and wanted to download some videos. after that people started to use it and wanted more stuff. sure the name is bit meh.  other then the -dl its pretty separate projects and how things work.

svtplay-dl have some support that youtube-dl dont have. like the -A feature  for example.  sure it can be added you youtube-dl too if they want. maybe there are some other things too.

i dont really see a reason to merge it. if people like to use some other script over the other one, its fine :)

**Comment by iwconfig** [comment]
You could just write a wrapper script for that.
If this site; then use svtplay-dl
if that site; then use youtube-dl

**Comment by fnadde42** [comment]
@spaam Thanks for the answer. This is not a huge issue and now I got a bit of a background on why things are the way they are. Do continue with this awesome tool! Also, thanks @iwconfig for the suggested solution.
