### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#580]
Hi, I am using the app on Mac. When I try to download this link the app crashes:

www.svtplay.se/klipp/12680908/morgonsvepet-5-mars-det-viktigaste-om-melodifestivalen-2017

Thanks for the help!

**Comment by spaam** [comment]
@ijbh what version are you using ? did you install it via brew? if so try `brew update` and `brew upgrade`

**Comment by ijbh** [comment]
Yes, now it works. Thank you!
