### ISSUE TITLE
Sista Chansen - xml.etree.ElementTree.ParseError

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#584]
Sista chansen seems to have changed today and it isn't working.

svtplay-dl -A --verbose http://svtplay.se/sista-chansen
DEBUG [1489571772.0] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay.se/sista-chansen'
DEBUG [1489571772.67] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svtplay.se/sista-chansen/rss.xml'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 463, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 192, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 208, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 210, in find_all_episodes
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by spaam** [comment]
i guess we should remove the rss.xml section in the find_all_episodes part.

**Comment by MR-2** [comment]
Seems weird that atom and xml isn't working for sista-chansen but sure.

**Comment by spaam** [comment]
but do it work for other things at svtplay?

**Comment by MR-2** [comment]
Yeah works for regular program titles.

**Comment by spaam** [comment]
it does? do you have a program title where it is downloading the rss.xml ?

**Comment by MR-2** [comment]
svtplay-dl http://www.svtplay.se/innan-vi-dor --verbose
DEBUG [1489573547.74] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/innan-vi-dor'
ERROR [1489573549.43] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: This mode is not supported anymore. need the url with the video
svtplay-dl http://www.svtplay.se/innan-vi-dor --verbose -A
DEBUG [1489573561.58] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/innan-vi-dor'
DEBUG [1489573562.49] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svtplay.se/innan-vi-dor/rss.xml'
INFO [1489573562.59] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 9
DEBUG [1489573562.59] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11933746/innan-vi-dor/innan-vi-dor-sasong-1-avsnitt-1'
DEBUG [1489573563.21] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1371612-001A'
DEBUG [1489573563.41] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay11g-f.akamaihd.net/d/se/open/delivery/20170210/1371612-001A/dash-live/PG-1371612-001A-INNANVIDOR-03-64d1b452-989e-4545-8778-27180edcbdb2-6f0049ca-b461-336d-8b49-f16bdd1fb5fd-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1371612-001A.mpd'
....

**Comment by spaam** [comment]
nice thank you @MR-2  :D

**Comment by MR-2** [comment]
Might be a bug or a "new feature" on their part I guess but for now maybe adding an exclude for the Titles (sista-chansen|live|populara|senaste) would be nice? :)

**Comment by spaam** [comment]
yes that sounds like a good thing to do :)

**Comment by MR-2** [comment]
Suggestion:
`re.search(r'<link rel="alternate" type="application/rss\+xml" [^>]*href="(^(?!sista\-chansen$)[^"]+)"',`
Don't know if we actual need to adress the other Titles, do we?
(sista-chansen|**live**|**populara**|**senaste**)

**Comment by qnorsten** [comment]
I feel a better and more future secure way might be to perform some sort of check on the linked rss.xml to see if it  returns a valid rss feed or not.  As of now http://svtplay.se/sista-chansen actually contains a link to http://svtplay.se/sista-chansen/rss.xml (which it did not before) but the rss.xml only contains Title sista-chansen not found.  A basic check for a valid rss feed will remove the need for a specific excludes and be more future proof.

**Comment by qnorsten** [comment]
Commit https://github.com/spaam/svtplay-dl/commit/9fe6b951cc4a68b514d04648f4244172d9faf8d7 should fix this issue. Everyone is free to help improve the valid rss-feed check. But this seems like a better and more future proof solution than to exclude certain urls.
