### ISSUE TITLE
via free dk says wont download

### ISSUE THREAD

**Issue by Jespor** [spaam/svtplay-dl#586]
It says
> ERROR: That site is not supported. Make a ticket or send a message

when i try to use it

**Comment by spaam** [comment]
what version do you use? feels like you are using an old version.  i added support for viafree.dk in 1.3 . i released that in 2016-09-03

**Comment by Jespor** [comment]
ahh, you might be right.
`svtplay-dl --version` tells me :

> 0.30.2016.02.08-debian1

installed with the `sudo apt install svtplay-dl` on ubuntu

**Comment by qnorsten** [comment]
Yea that is a very old version. Follow the installation step in the readme to get the newest version

**Comment by From2750** [comment]
i have the new version, but its says the same here.

**Comment by qnorsten** [comment]
I just tried it (running almost latest master, the last commits are not included, but they should not affect viaplay.dk 

svtplay-dl -S https://www.viafree.dk/programmer/serier/numb3rs/saeson-5/episode-16 --http-header="X-FORWARDED-FOR=**DANISH_IP**"  --force
INFO: Outfile: numb3rs.s05e16-818311-viafree.srt
ERROR: File (numb3rs.s05e16-818311-viafree.srt) already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 3597
INFO: Outfile: numb3rs.s05e16-818311-viafree.ts
[241/241][================================================================================] ETA: 0:00:00

**Comment by Jespor** [comment]
My original problem was that i downloaded the old version with `apt install svtplay-dl` on ubuntu, and reps aren't updated. IF you got pip for python, you can do `pip install svtplay-dl` as stated in the readme file.

**Comment by selepo** [comment]
Should this be closed then ?
@spaam : Seems to be some issues that relate specifically to old versions from repos on Ubuntu. When issuing the next release, is it possible to update the Ubuntu repo as well ?

**Comment by dentarg** [comment]
Yes it should :)

It's better with a new issue about syncing releases and apt repo @selepo
