### ISSUE TITLE
No module named svtplay-dl

### ISSUE THREAD

**Issue by tasveri** [spaam/svtplay-dl#587]
Hi, I'm getting an error when trying to run svtplay:

Traceback (most recent call last):
  File "svtplay-dl", line 4, in <module>
    import svtplay_dl
ModuleNotFoundError: No module named 'svtplay_dl

Anyone got a tip on how to solve it?

**Comment by spaam** [comment]
how did you install it?

**Comment by tasveri** [comment]
I installed python, unzipped svtplay-dl..zip and then ran setup.py. Maybe that's not correct?

**Comment by spaam** [comment]
yeah. the module is named svtplay_dl   not svtplay-dl :)

**Comment by spaam** [comment]
but how did you start it ? :)

**Comment by tasveri** [comment]
I started it from the svtplay-dl folder with python svtplay-dl ...[link]..

Ah..and I copied the svtplay-dl file from the bin-folder to the main folder.

**Comment by selepo** [comment]
@tasveri : Has this been resolved, or can you still not start the program ?

**Comment by dentarg** [comment]
We can re-open if it's still a problem.
