### ISSUE TITLE
dr1.dk/tv

### ISSUE THREAD

**Issue by From2750** [spaam/svtplay-dl#594]
i try to download from dr1.dk/tv 
https://www.dr.dk/tv/se/what-on-earth/-/what-on-earth-2-6#
ERROR: Something wrong with that url
ERROR: Error code: 404

**Comment by iwconfig** [comment]
Hint: pass `--verbose` to `svtplay-dl` together with the url and copy/paste the output. Also indent each line with 4 spaces, that way we get a nice looking and more readable block format :)

**Comment by qnorsten** [comment]
I could not replicate this as the link you listed was geoblocked. 
but https://www.dr.dk/tv/se/moderne-mirakler/-/moderne-mirakler-2-6 worked great for me using latest version.

**Comment by From2750** [comment]
sorry for late answer, 
but i try with --verbose and thats works fine,

i had the latest version.  :)

thank you all, 
on thing more, when i use --remux, can i make it to mkv instead of mp4?

**Comment by qnorsten** [comment]
That is strange cause --verbose should not affect if it works or not, it should just change the amount of output from the program. Guess it must have been some temporary error on DR´s part. 

Right now I do not think mkv output is possible.

**Comment by From2750** [comment]
Yes maybe there have been some weird things going on, but just good that its works now :)

**Comment by qnorsten** [comment]
I am closing this now as it seem to have been some temporary error on dr1.dk/tv´s part. 
You are free to create a separate issue for the mkv support if you like to request that.
