### ISSUE TITLE
Trouble upgrading in Ubuntu 16.04

### ISSUE THREAD

**Issue by pulsatorius** [spaam/svtplay-dl#598]
When I tried to upgrade my Ubuntu 16.04 system. I got this error:
Fel:2 http://apt.svtplay-dl.se svtplay-dl InRelease                                  
  Följande signaturer är ogiltiga: KEYEXPIRED 1490722658  KEYEXPIRED 1490722658  KEYEXPIRED 1490722658  KEYEXPIRED 1490722658
Tried:
$ curl -s https://svtplay-dl.se/release-key.txt | sudo apt-key add -
OK
$ sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   4096R/4422971A 2016-03-28
uid                  svtplay-dl releases <svtplay-dl@i19.se>
sub   4096R/81CF3F17 2016-03-28
$ sudo apt update 
Fel:1 http://apt.svtplay-dl.se svtplay-dl InRelease                                                 
  Följande signaturer är ogiltiga: KEYEXPIRED 1490722658  KEYEXPIRED 1490722658  KEYEXPIRED 1490722658  KEYEXPIRED 1490722658

What to do?

**Comment by spaam** [comment]
oh shit. my bad..  if you do it again. it should be fixed. thanks for the bug report  <3

**Comment by pulsatorius** [comment]
Working! :)
