### ISSUE TITLE
TV4Play crash @ Det Okända

### ISSUE THREAD

**Issue by Usudanix** [spaam/svtplay-dl#600]
\>svtplay-dl https://www.tv4play.se/program/det-ok%C3%A4nda?video_id=3879672 --subtitle --stream-priority=hds --force --quality=1496 -Q 200 -u xxxx@xxxxx.xxx -p xxxxxxxx --verbose

DEBUG [1491565652.5602376] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/det-ok%C3%A4nda?video_id=3879672'
DEBUG [1491565653.228297] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/session/new?https='
DEBUG [1491565653.3842385] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://account.services.tv4play.se/session/authenticate'
ERROR [1491565653.3892448] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3

Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 33, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\tv4play.py", line 236, in _login
AttributeError: 'NoneType' object has no attribute 'json'
Failed to execute script svtplay-dl

Thank you for your Superb work!!

**Comment by pike2k** [comment]
yep, happen here also!

**Comment by Sopor-** [comment]
Works perfect here
```
INFO: Selected to download hls, bitrate: 4496
INFO: Outfile: det.okanda.s22e13.del.13-3879672-tv4play.ts
[028/294][===.....................................] ETA: 0:02:02
```
but i can see you are using your account information. Have you tried without that -u and -p?

**Comment by Usudanix** [comment]
Hmm... That's strange.
It now works without account information. But I've always used account information before, since the site wanted you to login before you could watch.

Anyway... Shouldn't it work with account information as well, since I can watch it still while being logged in?

**Comment by qnorsten** [comment]
I think they changed something on the login page/ login process. It is proably an easy fix, but as all premium content is moving to Cmore it might not be needed anymore (only premium content requires login to download, even though the site requires login to list any videos)

**Comment by spaam** [comment]
master have a fix for this. will be in the next verison later today
