### ISSUE TITLE
NRK No longer workning

### ISSUE THREAD

**Issue by kurtlager** [spaam/svtplay-dl#604]
I can't download any programs from NRK (https://tv.nrk.no) I just get the error message:

ERROR: Can't find video id.

**Comment by waltherbans** [comment]
Same here. NRK must have changed something, since the error show up on videos that I managed to download earlier, too.

**Comment by MR-2** [comment]
Looks like they changed their name of their api from "....v8.psapi..." to ..."psapi-ne..."

**Comment by kurtlager** [comment]
Chaining "....v8.psapi..." to ..."psapi-ne..." is NO solution

**Comment by spaam** [comment]
okey :) i will take a look at it today

**Comment by MR-2** [comment]
@kurtlager there are a few things more that would need to be fixed other then that.

**Comment by snix47** [comment]
Yeppz, NRK downloading does not work with 1.9.3 - "Can't find video id"
