### ISSUE TITLE
TV4Play Issue - Cant find vid id for autonaming

### ISSUE THREAD

**Issue by stdlogin** [spaam/svtplay-dl#607]
Hi, 
I can´t download movies from tv4play.se anymore with the lastest svtplay-dl for windows

**have tried to download this movie, but I get this messages**
https://www.tv4play.se/program/sn%C3%A5lvatten-j%C3%A4kelskap?video_id=900814
 
**Messages:**
Cant find vid id for autonaming

**DEBUG:**
DEBUG [1492450619.4407203] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/snalvatten-jakelskap?video_id=900814'
DEBUG [1492450620.0257504] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/900814/play'
DEBUG [1492450620.3834157] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=snalvatten-jakelskap&per_page=99999'
DEBUG [1492450620.4823878] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=clips&is_live=false&platform=web&node_nids=snalvatten-jakelskap&per_page=1000&page=1'
ERROR [1492450620.5048394] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Cant find vid id for autonaming

**Comment by Sopor-** [comment]
It works here
```
svtplay-dl -S -P hls https://www.tv4play.se/program/sn%C3%A5lvatten-j%C3%A4k
elskap?video_id=900814
INFO: Outfile: snalvatten.jakelskap-900814-tv4play.srt
INFO: Selected to download hls, bitrate: 2496
INFO: Outfile: snalvatten.jakelskap-900814-tv4play.ts
[035/739][===...................................................................] ETA: 0:01:24
```

**Comment by qnorsten** [comment]
Works for me too with latest master. @stdlogin can you try again and see if it was some temporary issue or something?

**Comment by stdlogin** [comment]
It works for me too now if I use svtplay-dl
Exe with powershell.exe instead of cmd.exe

I think it is a bug issue in the lastest Windows 10 insider build, it has worked with cmd.exe before

**Comment by spaam** [comment]
i have released a new version. it will have this fix. thanks for the bug report.
