### ISSUE TITLE
TV4Play.se - Swedish characters show up as diamond and a question mark inside it in the subtitle

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#609]
After using @qnorsten fix https://github.com/spaam/svtplay-dl/commit/9fe6b951cc4a68b514d04648f4244172d9faf8d7 i now get the Swedish characters show up as diamond and a question mark inside it in the subtitle. I run it on Ubuntu with python 2.7.6.
```
1
00:00:00,080 --> 00:00:05,240
Ska vi l�gga ett bud? Vill du?

2
00:00:05,400 --> 00:00:08,320
�Jag kommer ju till sommaren.
�Jag vet.

3
00:00:14,000 --> 00:00:19,400
Wilma Persson drunknade inte i �lven,
kropp flyttades dit efter hennes d�d.
```
If i use 1.9.3 it look like this
```
1
00:00:00,080 --> 00:00:05,240
Ska vi lägga ett bud? Vill du?

2
00:00:05,400 --> 00:00:08,320
-Jag kommer ju till sommaren.
-Jag vet.

3
00:00:14,000 --> 00:00:19,400
Wilma Persson drunknade inte i älven,
kropp flyttades dit efter hennes död.
```
I run it on Ubuntu with python 2.7.6 and before i pulled @qnorsten  commit it worked perfect.
This is last weeks download:
```
1
00:00:41,240 --> 00:00:45,080
Här är det! Wilma!

2
00:00:45,240 --> 00:00:48,120
Wilma, här är det. Kom.

3
00:00:49,440 --> 00:00:52,800
Kolla.

4
00:00:52,960 --> 00:00:56,000
Enligt koordinaterna
ska det vara exakt här.
```
It seems to work on Viafree
```
1
0:00:17,360 --> 0:00:21,080
Det är väldigt svårt att beskriva
hur panik känns.

2
0:00:21,160 --> 0:00:23,680
Jag vill bara gråta.

3
0:00:23,760 --> 0:00:29,520
Verkligt mod handlar om att
utsätta sig för det man fruktar mest.
```

**Comment by qnorsten** [comment]
Like I said in the other issue, I have no idea why you are having this issue. Nothing in https://github.com/spaam/svtplay-dl/commit/9fe6b951cc4a68b514d04648f4244172d9faf8d7 should affect subtitle encoding and it works fine on Windows 10 with both python 2.7 and 3.5  for me. 

https://github.com/spaam/svtplay-dl/commit/a9e1e92ba219ac878d8b04973f5da211185ad049 , https://github.com/spaam/svtplay-dl/commit/a310ceb2a136395dabcf00361737a0469835b35d , and https://github.com/spaam/svtplay-dl/commit/f963b5f7555780e722edce3a3fd2b47be0bfb088 that was also added since the 1.9.3 release affects subtitles but only in smi format (TV4 play) and I can not see how they can screw up the encoding. Hopefully @spaam has some idea what might cause the problem.

**Comment by Sopor-** [comment]
Yeah, i have no idea. I let the experts take over :)
You can try these two:
$`svtplay-dl -S --force-subtitle https://www.tv4play.se/program/biggest-loser?video_id=3888596`
or
$`svtplay-dl -S --force-subtitle https://www.tv4play.se/program/macgyver-1986?video_id=3811514`

**Comment by MR-2** [comment]
Sounds like a BOM problem. 
@Sopor- Do you experience this while looking at the subtitles in an editor or when being played in a media player?

**Comment by Sopor-** [comment]
@MR-2 Both!
If i open it in a editor the file is UNIX UTF-8. If i open the file in hex the `å, ä, ö and -` will be `ï¿½`

**Comment by MR-2** [comment]
@Sopor- With or without BOM? Have you compared the subtitles that doesn't produce this with those that produce this issue?

**Comment by qnorsten** [comment]
I would also recommend using the --raw-subtitles parameter to grab the raw subtitles file also, and compare them to see if they differ in some way.

**Comment by Sopor-** [comment]
@MR-2 no BOM

@qnorsten DOS UTF-8 if i download raw subtitle and it look like this and no BOM in that file either:
```
  <BODY>
    <SYNC Start=160>
      <P Class=SVCC>En vecka har passerat pĺ slottet<br>och det blev en händelserik start.
    <SYNC Start=6760>
      <P Class=SVCC>&nbsp;
    <SYNC Start=6920>
      <P Class=SVCC>Ingemar klarade inte av pressen<br>och bröt tävlingen.
    <SYNC Start=10720>
      <P Class=SVCC>&nbsp;
    <SYNC Start=10880>
      <P Class=SVCC>Det är kaos i hjärnan.<br>Jag vill bara försvinna.
    <SYNC Start=14840>
      <P Class=SVCC>&nbsp;
    <SYNC Start=15000>
      <P Class=SVCC>Starka känslor kom upp till ytan.<br>Jag klarar inte av att förlora.
```
Som chars seems to work but not all all of them...

**Comment by spaam** [comment]
is there something wrong with the biggest loser subtitle? it works great here on macos with py2 and 3.

**Comment by MR-2** [comment]
@Sopor- Have you checked the first three hex values of the files to verify that they don't contain BOM or how have you verified this?

**Comment by Sopor-** [comment]
@spaam i get the same on all TV4 subtitles. I have downloaded older subtitles and i get the same issue after i did the pull from master.

**Comment by Sopor-** [comment]
@MR-2 Yes, i have opening the file in hex and there is no BOM. A BOM should have looked like this: `ï»¿` (EF BB BF)

**Comment by spaam** [comment]
this feels really strange. i cant see why @qnorsten broke it..   what version of requests do you have installed?  `pip list | grep request`. i tried on a ubuntu 15.10 system and it worked great.

**Comment by MR-2** [comment]
@Sopor- Have you changed any language settings on your systems recently perhaps or in any of your apps?

**Comment by spaam** [comment]
it might be a broken unicode. like double encoded or something like that.

**Comment by qnorsten** [comment]
@Sopor-  have you tried reverting to the 1.9.3 and confirmed that that works correctly now too?

**Comment by Sopor-** [comment]
@qnorsten I will try that now!

**Comment by Sopor-** [comment]
@qnorsten It wasn't your commit. If i go back to 1.9.3 it works again so it must have been some of the other commits before yours.
```
1
00:00:00,160 --> 00:00:06,760
En vecka har passerat på slottet
och det blev en händelserik start.

2
00:00:06,920 --> 00:00:10,720
Ingemar klarade inte av pressen
och bröt tävlingen.

3
00:00:10,880 --> 00:00:14,840
Det är kaos i hjärnan.
Jag vill bara försvinna. 
```

**Comment by qnorsten** [comment]
Can you try and checkout all the commits after 1.9.3 one at a time and see which one that breaks it? Cause it is probably one of my 3 smi subtitle related ones (even though I do not see how).

**Comment by Sopor-** [comment]
@qnorsten of course it was the last one https://github.com/spaam/svtplay-dl/commit/a9e1e92ba219ac878d8b04973f5da211185ad049 :(

**Comment by Sopor-** [comment]
@qnorsten Do you find the reason in the above commit why it fails?

**Comment by qnorsten** [comment]
I have no idea actually. But maybe @spaam can think of some reason why decode_html_entities might cause this? 
It is just strange that it works fine for him with ubuntu.

**Comment by spaam** [comment]
@Sopor-  it works for newer versions of python2. im starting to think its your old python2 that is the issue here.  i cant reproduce it on a newer version of python2.

**Comment by spaam** [comment]
does it work with python3 or do you still get the same issue?

**Comment by Sopor-** [comment]
@spaam I have tested it on another computer that run Python 2.7.6 and it seems to work there. The only difference is the Ubuntu version.
Ubuntu 14.04.5 LTS - Working
Ubuntu 14.04.1 LTS - Not working after commit https://github.com/spaam/svtplay-dl/commit/a9e1e92ba219ac878d8b04973f5da211185ad049

**Comment by spaam** [comment]
what does `dpkg -l | grep python2.7` say?  same thing on both systems?

**Comment by Sopor-** [comment]
Exact the same thing
```
$ dpkg -l | grep python2.7
ii  libpython2.7:amd64                     2.7.6-8ubuntu0.3                      amd64        Shared Python runtime library (version 2.7)
ii  libpython2.7-dev:amd64                 2.7.6-8ubuntu0.3                      amd64        Header files and a static library for Python (v2.7)
ii  libpython2.7-minimal:amd64             2.7.6-8ubuntu0.3                      amd64        Minimal subset of the Python language (version 2.7)
ii  libpython2.7-stdlib:amd64              2.7.6-8ubuntu0.3                      amd64        Interactive high-level object-oriented language (standard library, version 2.7)
ii  python2.7                              2.7.6-8ubuntu0.3                      amd64        Interactive high-level object-oriented language (version 2.7)
ii  python2.7-dev                          2.7.6-8ubuntu0.3                      amd64        Header files and a static library for Python (v2.7)
ii  python2.7-minimal                      2.7.6-8ubuntu0.3                      amd64        Minimal subset of the Python language (version 2.7)
```

**Comment by spaam** [comment]
sorry i dont see any reason to fix this "issue". this is outside of svtplay-dl.  because it is working on every other machine and not your 14.04.1 system. its working on your 14.04.5 system and not 14.04.1 one.  upgrade the 14.04.1 one to 14.04.5 or something that is even newer. 14.04 getting very old now. 

if you still get the same issue with 14.04.1 system after upgrading to 14.04.5. you need to see what is the difference between those to systems. like same python-requests version. you can see that in `dpkg -l` and/or `pip list` depending how you installed it.

**Comment by Sopor-** [comment]
@spaam @qnorsten I found it. I updated requests and now it is working :)

**Comment by spaam** [comment]
awesome 👍
