### ISSUE TITLE
Crash "KeyError ProgramTitle" on oppetarkiv.se

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#610]
svtplay-dl -A https://www.oppetarkiv.se/etikett/titel/Sexton/
    1.9.3_1 ... python2.7 ... oppetarkiv.py line 155: KeyError ProgramTitle

**Comment by qnorsten** [comment]
Dupe of https://github.com/spaam/svtplay-dl/issues/596
So closing this:) Thanks for the report though:)
