### ISSUE TITLE
TV4 play "Can't find the video api"

### ISSUE THREAD

**Issue by frepe360** [spaam/svtplay-dl#611]
Tried to do this:

> svtplay-dl -v https://www.tv4play.se/program/gws-mord?video_id=3887993
> DEBUG [1492680022.62] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.tv4play.se/program/gws-mord?video_id=3887993'
> DEBUG [1492680022.84] /usr/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://premium.tv4play.se/api/web/asset/3887993/play'
> ERROR [1492680022.88] /usr/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: Can't find the video api

**Comment by qnorsten** [comment]
Strange works here. Which version are you using?

**Comment by frepe360** [comment]
svtplay-dl --version
0.30.2016.02.08-debian1

**Comment by qnorsten** [comment]
That explains why that api adress looked odd. The current version is 1.9.3 so the version you are using is extremly old. Try installing it from source or using https://apt.svtplay-dl.se/ as the original ubuntu or debian repository do not include newer versions of svtplay-dl.

**Comment by frepe360** [comment]
That worked a lot better, thank you.

I followed the installation instructions on the front page: https://github.com/spaam/svtplay-dl

It says to install from the ubuntu/debian repo. Perhaps adding the info about the apt.svtplay-dl.se repo can avoid more issues like this one.

**Comment by qnorsten** [comment]
I understand, perhaps @spaam  should update the instructions:)
