### ISSUE TITLE
Add support for http://video.disney.se

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#613]
I only get a file with this text when trying to download. I believe it has worked before but i'm not sure...
`svtplay-dl http://video.disney.se/spela/avsnitt-66-54ce458ca47ad08830bf120e`
```
<!DOCTYPE html>
<html lang="sv">
  <head>
    <title>Viktigt meddelande</title>
    <link rel="stylesheet" type="text/css" href="//a.dilcdn.com/a/waystation/emea-exit-6bf6901a226c.css">
    <link rel="canonical" href="http://kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1492085574~exp=1492107174~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4*~hmac=248b7083cd389adce16e78667b7e91347230b84ecc6fc82ea2a07763b4758dc7">
  </head>
  <body>
    <div class="container">
      <div id="message">
        <div class="header">Är du säker på att du vill lämna Disney?</div>
        <div class="body">Den webbplats som du försöker nå kontrolleras inte av Disney och andra användarvillkor samt en annan integritetspolicy gäller. Genom att gå vidare accepterar och inser du att Disney inte har något ansvar för den webbplats som du vill besöka.</div>
      </div>
      <div id="options">
        <a id="cancel" class="button">Tillbaka</a>
        <a id="continue" class="button primary" href="http://kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1492085574~exp=1492107174~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4*~hmac=248b7083cd389adce16e78667b7e91347230b84ecc6fc82ea2a07763b4758dc7">Fortsätt</a>
      </div>
    </div>
    <script type="text/javascript" src="//a.dilcdn.com/a/waystation/exit-25cc6c030a58.js"></script>
  </body>
</html>
```

**Comment by qnorsten** [comment]
It still works for some urls such as http://video.disney.se/spela/gravity-falls/dipper-forklarar-det-oforklarliga-avsnitt-5-501744a291685fb39b523143

But for some videos they seem to have added a redirection page and changed some other things (maybe some DRM protection or something?)
The redirection page is easy to parse and get the correct url

> http://kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1492085574~exp=1492107174~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_f97g7e5d/v/2/flavorId/1_ve7xgf45/fileName/Avsnitt_66_(SD_Large_-_WEB_MBL_(H264_1500)).mp4/forceproxy/true/name/a.mp4*~hmac=248b7083cd389adce16e78667b7e91347230b84ecc6fc82ea2a07763b4758dc7

This url returns a 403 Forbidden response. So I am not sure on how to fix this. Hopefully spaam or someone else have an idea.
