### ISSUE TITLE
"Download all" downloads only subtitles, no videos

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#614]
Using the latest version from Github, only subtitles are downloaded when all videos and subtitles are supposed to be downloaded. Command line used:

    svtplay-dl -A -S https://www.svtplay.se/bron

**Comment by qnorsten** [comment]
Can you please run svtplay-dl -A -S https://www.svtplay.se/bron --verbose and show the input here?
Cause I get both video and subtitles when I run svtplay-dl -A -S https://www.svtplay.se/bron

**Comment by forthrin** [comment]
It seems this issue was probably caused by a failing proxy and can be deleted. (Posted request for proxy support/workaround in another issue.)
