### ISSUE TITLE
svtplay crash

### ISSUE THREAD

**Issue by Maackan88** [spaam/svtplay-dl#620]
svtplay-dl.exe https://www.svtplay.se/video/13012992/motorsport-rallycross-vm/motor-vm-rallycross-2-apr-14-00 --verbose
DEBUG [1493802798.8192112] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting '
https://www.svtplay.se/video/13012992/motorsport-rallycross-vm/motor-vm-rallycross-2-apr-14-00'
ERROR [1493802799.093245] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\svtplay.py", line 41, in get
KeyError: 'videoTitlePage'
Failed to execute script svtplay-dl

**Comment by qnorsten** [comment]
Svtplay seem to have changed videoTitlePage to videoPage should be a quick fix.

**Comment by Maackan88** [comment]
Nice, thanks for the info! 👍

**Comment by qnorsten** [comment]
Should be fixed now. Let me know if they changed something else also. I tried some urls with success, but you never know.

**Comment by Maackan88** [comment]
I get the same error-messages as before. Am I doing something wrong?
Do I have to do something special now after your change?

**Comment by qnorsten** [comment]
Which OS are you running? Windows?
It is only in latest master until spaam releases a new version. To use it you need to follow the instructions under install from source in the readme.

**Comment by Maackan88** [comment]
Yes, I'm using Windows. Ok, thanks for your help :)
