### ISSUE TITLE
Problem with latest Windows download

### ISSUE THREAD

**Issue by vasaen** [spaam/svtplay-dl#624]
Hi
Seems that the fix that is mention in case 620 not is in the Windows download

Regards and Thanks in advance
/Anders

**Comment by qnorsten** [comment]
Spaam has not release a new release version in a while and therefore not updated the windows file. 
Try the one I posted here https://github.com/spaam/svtplay-dl/issues/621#issuecomment-299390341

**Comment by vasaen** [comment]
Tackar

Såg INTE din länk http://s000.tinyupload.com/?file_id=86513641326422364191
den fungerade helt ok

Än en gång tack för ett snabbt svar 
MVH
/Anders

**Comment by spaam** [comment]
i have released a new version. it will have this fix. thanks for the bug report.  :)
