### ISSUE TITLE
PyInstaller and svtplay-dl on Windows...

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#625]
Everything works fine when i create svtplay-dl on Windows but when i run the `svtplay-dl.exe` i get this message
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: No module named 'svtplay_dl'
svtplay-dl returned -1
```
I have updated everything but it still won't run :(

**Comment by qnorsten** [comment]
Have you ran setup.py install before running pyinstaller?

**Comment by Sopor-** [comment]
@qnorsten Now i manage to get a svtplay-dl.exe to run and the file size is now `12 106 719 bytes`.
Shouldn't there be any error messages if i do it wrong? Even if the `README.rst` explains it there should be a more detailed instruction instead of only `2. Follow the steps listed under From source`.
Anyway, thanks for the tip 👍

**Comment by qnorsten** [comment]
Glad it is working for you:)
Feel free to write some more detailed instructions and do a pull request if you like:)

**Comment by Sopor-** [comment]
@qnorsten but do i really need to use PyInstaller? If i [download](https://github.com/spaam/svtplay-dl/archive/master.zip) or clone, i can run it from the `bin` folder if i run it like this `python svtplay-dl`.
I do need to have [Python](https://www.python.org/ftp/python/3.6.1/python-3.6.1.exe) installed of course and requests and PyCrypto.
What i mean is, if you manage to install Python, requests and PyCrypto then PyInstaller is totally useless because it will work without it and you don't need to create any svtplay-dl.exe.

**Comment by spaam** [comment]
If you want to create an .exe you need to run `setup.py install`    the one in bin is just a small script that calls some functions from the module.

**Comment by Sopor-** [comment]
There seems to be something wrong with PyInstaller, Python 3.5 and Windows 10. I can't get it to work and after some searching i found this https://github.com/pyinstaller/pyinstaller/issues/1566
I believe you have other programs installed that makes it work for you, Visual Studio and other kind of programs? I can't get it to work in a fresh installed Windows 10.
@qnorsten what do you have installed to create exe files with PyInstaller? It will create a svtplay-dl.exe but when i try to run it i get `You need to install python-requests to use this script` even if i have it installed and then i get a lot of missing files `api-ms-win-crt*.dll` when running PyInstaller same as the issue i have linked to in this comment.
I'm asking because i'm trying to create a better guide on how to pull from master and create an executable svtplay-dl.
