### ISSUE TITLE
No module named 'svtplay_dl'

### ISSUE THREAD

**Issue by linderlake** [spaam/svtplay-dl#627]
Hi,

I installed this on a Raspberry pi running Raspbian 8.0 (jessie) through the metod of adding the svtplay-dl repo and then apt-get install it. However I get the following printout whenever I try to run it:

```
linderlake@rbpi:~/svtplaydl $ sudo svtplay-dl https://www.svtplay.se/video/13357656/kobra/kobra-sasong-19-andra-sidan-henrik-berggren?start=auto&tab=senaste
[1] 2659
linderlake@rbpi:~/svtplaydl $ Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 4, in <module>
    import svtplay_dl
ImportError: No module named 'svtplay_dl'
```

Any ideas?

**Comment by spaam** [comment]
thanks i will look into it

**Comment by spaam** [comment]
i found the issue :)

**Comment by spaam** [comment]
thanks for the bug report. i have fixed the issue now. just apt-get update and upgrade and you will have it :)

**Comment by linderlake** [comment]
I just upgraded and verified that it's now working again! :+1: 
Thanks for the super fast response and fix.
