### ISSUE TITLE
New version filled with virus?

### ISSUE THREAD

**Issue by psonnosp** [spaam/svtplay-dl#630]
So tried to download the new Windows version but my virus program wouldn't let me and Virustotal get hits on 12/60. So what's up with that?

**Comment by spaam** [comment]
its a false positive :(
im using [pyinstaller](http://www.pyinstaller.org/) to create the .exe execute from the python script. had some issues before when it was packed with [upx](https://upx.github.io/). when i stopped doing that with false positives . it became better. i guess its back again.

**Comment by spaam** [comment]
https://github.com/pyinstaller/pyinstaller/issues/603 some relevant info

**Comment by selepo** [comment]
Should this issue be closed then ?

**Comment by dentarg** [comment]
Yes, sounds like this problem come and goes for all software that can create installers.

https://github.com/pyinstaller/pyinstaller/issues/603#issuecomment-59615590

> The only correct way to deal with antivirus is to report them that they are wrong. If we are working around them, we simply start a cat-and-mouse game that never ends.
