### ISSUE TITLE
TV4Play - can't download subtitle even if the site show it

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#631]
When i downloaded this episode https://www.tv4play.se/program/gws-mord?video_id=3887993 of GW:s Mord del 1 i don't get any subtitle even if i get it on there site. If i force download the subtitle i get this message `WARNING: Can't download subtitle file`. Episode 2 and 3 i get subtitle
`Outfile: gws.mord.s01e02.del.2-3903955-tv4play.srt`

![picpick-2017 05 11-00 07 57](https://cloud.githubusercontent.com/assets/5789283/25923495/16a9b970-35de-11e7-97a8-6125579614e1.png)

**Comment by qnorsten** [comment]
Interesting looking at the api the link to the [smi subtitle]https://asset-subtitles.tv4play.se/2017-04-19/8pid200019550!3887993,T3HSMIL!.smi) only gives me a Access Denied message when I try to view it. While the [webvtt link](http://iosv.tv4play.se/subs/2017-04-28/vid_3887993/vid_3887993.webvtt) seem to work fine. So it seem to be some sort of error on tv4s side. 
If it is not fixed it might be worth trying to fetch the vtt subtitle also as a backup.

**Comment by MR-2** [comment]
@Sopor- in my experience the .smi subtitles have been causing these access denied messages on and off for quite a while. I'm thinking that tv4 has changed something in their publishing process which is causing these issues.

**Comment by qnorsten** [comment]
@MR-2  Do you know if every title also have the webvtt subtitle? In that case it might be a good idea to switch over to that as default instead of smi.

**Comment by MR-2** [comment]
@qnorsten Both .smi and .vtt should be present for all videos. Might be an idea to implement the ability  for the user which subtitle format they want to fetch or that svtplay-dl tries to download first best available.

**Comment by spaam** [comment]
if both are there and .vtt always works. maybe its time to use .vtt instead. if .vtt dont work use .smi ?

**Comment by MR-2** [comment]
@spaam changing to .vtt might be wise, vtt is also present on the cmore plattform while i think sami isn't available there at all. So vtt seems to be strongest candidate. But yeah would be nice to have a function if vtt fails try sami.
