### ISSUE TITLE
TV4Play

### ISSUE THREAD

**Issue by hjoel** [spaam/svtplay-dl#633]
Is  svtpla-dl  supposed to work with TV4Play? I believe I have read somewhere that it is, but I can't get it to work.

Attempt:  svtplay-dl -v https://www.tv4play.se/program/lets-dance
(I have also tried with an assortment of different parameters, but get exactly the same result.)

URL:  https://www.tv4play.se/program/lets-dance

Message:  
DEBUG [1494666453.3375742] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/lets-dance'
ERROR [1494666453.8688264] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Can't find video id for https://www.tv4play.se/program/lets-dance

/Håkan

**Comment by spaam** [comment]
@hjoel , it looks like you are using 1.8. can try using 1.9.4 and see if you still see the issue? :)

**Comment by spaam** [comment]
try klicking on the actual video.  for example https://www.tv4play.se/program/lets-dance?video_id=3876463 for the lastest video.  the script cant grab the video on the program page..

**Comment by hjoel** [comment]
Thank you!

After I submitted my issue, I discovered that I wasn't using the latest version of  svtplay-dl. I will remedy that.

But your second tip was what really did the trick! I hadn't realized that the URLs were different in different "locations".

Thanks a million!
/Håkan
