### ISSUE TITLE
TV4Play.se - Can't find the video api

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#634]
Hi, I get an error when I try to download this clip from this url at www.tv4play.se today (2017/05/13), see more info about it down below:
https://www.tv4play.se/program/talang?video_id=3876383

**SVTPlayDL Version:**

- [ ] 1.9.4 for Windows

**Debug code:**

DEBUG [1494707312.9012644] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/talang?video_id=3911194'
DEBUG [1494707313.5069876] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3911194/play'
ERROR [1494707313.55996] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Can't find the video api

**Comment by spaam** [comment]
does this happen for all tv4play videos?
i cant reproduce this.

**Comment by myowncloudservice** [comment]
Not all videos on www.tv4play.se are affected by this problem!

**This video work:**
https://www.tv4play.se/program/talang?video_id=3876383

**This video not working:**
https://www.tv4play.se/program/talang?video_id=3911194 (I think this, link is a live adress, a misstake by me)

**Comment by spaam** [comment]
hmm yeah. i wonder how we should detect that kind of a thing..

**Comment by myowncloudservice** [comment]
I think I was a bit too quick to copy the link to the video I wanted to download from www.tv4play.se this evening. The video probably had a video_id that was for a live stream, and after the live stream was over, it got another video_id that is now available and works correctly with version **1.9.4 of SVTPlay-DL**

**SVTPlay-DL does not support live streaming yet?**

**Comment by myowncloudservice** [comment]
done
