### ISSUE TITLE
TV4Play.se - Cant find vid id for autonaming

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#635]
Hi, I get an error when I try to download this clip from this url at www.tv4play.se today (2017/05/15), see more info about it down below:
https://www.tv4play.se/program/bagges-hemlB6sa-hundar?video_id=3868657

**SVTPlayDL Version:**
- [ ] 1.9.4 for Windows

**Debug code:**
DEBUG [1494878906.4220908] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.tv4play.se/program/bagges-hemlB6sa-hundar?video_id=3868657'
DEBUG [1494878906.8519516] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://prima.tv4play.se/api/web/asset/3868657/play'
DEBUG [1494878906.9707944] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=episode&is_live=false&platform=web&node_nids=bagges-hemlB6sa-hundar&per_page=99999'
DEBUG [1494878907.0141778] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://webapi.tv4play.se/play/video_assets?type=clips&is_live=false&platform=web&node_nids=bagges-hemlB6sa-hundar&per_page=1000&page=1'
ERROR [1494878907.031825] site-packages\svtplay_dl-1.9.4-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Cant find vid id for autonaming

**Comment by spaam** [comment]
How do you get the url? it loks a bit broken
for me when o copy the url. i get `https://www.tv4play.se/program/bagges-heml%C3%B6sa-hundar?video_id=3868657`  notice the `%C3%B6`     you have `B6` only.

**Comment by myowncloudservice** [comment]
Hmm, I don´t now, I try to copy the URL again from www.tv4play.se and now It´works correctly with this url
https://www.tv4play.se/program/bagges-heml%C3%B6sa-hundar?video_id=3868657

I don´t now what have happen when I copy the URL, the first time?

** Tanks for your help!**

**Comment by spaam** [comment]
strange. it should keep those `%C3%B6` chars when you copy the url :)
