### ISSUE TITLE
Wanted: version specific dependency

### ISSUE THREAD

**Issue by gunnarhj** [spaam/svtplay-dl#637]
The `svtplay-dl` package in `apt.svtplay-dl.se` depends on `python-svtplay-dl` without specifying the version, which [may lead to confusion](https://ubuntu-se.org/phpBB3/viewtopic.php?p=490199#p490199).

This line in `debian/control`:

`Depends: python, python:any (>= 2.6~), python-svtplay-dl`

should be changed to:

`Depends: python, python:any (>= 2.6~), python-svtplay-dl (= ${binary:Version})`

**Comment by spaam** [comment]
ahh  oke. i have released a new revision of the packet with that fix. thank you <3

**Comment by gunnarhj** [comment]
Thanks. :)
