### ISSUE TITLE
Subtitles in URPlay

### ISSUE THREAD

**Issue by hjoel** [spaam/svtplay-dl#639]
I'm sorry to trouble you guys, but I'm struggling vainly to download TVprograms from URPlay that include functioning subtitles.
When I try eg.     
svtplay-dl http://urplay.se/program/199700-lange-leve-akta-mat#
I get a downloaded file 
lange.leve.akta.mat-ur.play.ts
which I can play and watch and hear - but no subtitles.
I've tried different combinations of parameters (like -S -M-), but nothing works for me.
Parameter -S downloads a file    lange.leve.akta.mat-ur.play.srt
but subtitles don't merge into the video-file.

Downloads from SVTPlay generate *.mp4-files that include sound and subtitles and everything.

Rather confused
/Håkan

**Comment by hjoel** [comment]
PS      

When trying 
D:\##dl>svtplay-dl -S -M http://urplay.se/program/199700-lange-leve-akta-mat#

I get this result:
INFO: Outfile: lange.leve.akta.mat-ur.play.srt
INFO: Selected to download hls, bitrate: 3462
INFO: Outfile: lange.leve.akta.mat-ur.play.ts
[326/326][========================================] ETA: 0:00:00
INFO: Muxing lange.leve.akta.mat-ur.play.ts and merging its subtitle into lange.leve.akta.mat-ur.play.mp4
INFO: Determining the language of the subtitle.
INFO: Language code: swe
ERROR: Something went wrong: lange.leve.akta.mat-ur.play.srt: Invalid data found when processing input

/Håkan

**Comment by spaam** [comment]
i think i found the issue. normally they send the subtitle in HH:MM:SS.mmm  but urplay send it as MM:SS.mmm and skip the Hour field.
