### ISSUE TITLE
SVT öppet akriv 

### ISSUE THREAD

**Issue by noob403** [spaam/svtplay-dl#640]
Keeps crashing on me

svtplay-dl -S -t -q 986 --remux -A https://www.oppetarkiv.se/video/1150858/tre-karlekar-sasong-1-avsnitt-1-av-8?ac=tre

**Comment by spaam** [comment]
@noob403 what version are you using? it works great with 1.9.4

**Comment by noob403** [comment]
Fortfarande samma historia:
Version enligt Terminal är 1.1 har försökt uppdatera och fortfarande 1.1. Ja jag kör den från en mac.

macbook-pro:~ PD$ svtplay-dl -S -t -q 985 --remux https://www.oppetarkiv.se/video/1150858/tre-karlekar-sasong-1-avsnitt-1-av-8?ac=tre
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

**Comment by spaam** [comment]
hur installerade/uppdaterade du svtplay-dl? kör du via brew? om du kör via brew. testa `brew update`  sedan `brew upgrade`

**Comment by noob403** [comment]
Vad gjorde jag för fel?!

PD$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
xmount
Error: Could not link:
/usr/local/etc/bash_completion.d/brew

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/zsh/site-functions/_brew

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/man/man1/brew.1

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/doc/homebrew

Please delete these paths and run `brew update`.

**Comment by spaam** [comment]
verkar vara något med brew. testa ta bort dom dära sökvägarna den klagar på o kör om `brew update`

**Comment by noob403** [comment]
Den har stått så där i 10min ...

pds-macbook-pro:~ PD$ brew update
Already up-to-date.
pds-macbook-pro:~ PD$ brew upgrade
==> Upgrading 1 outdated package, with result:
yasm 1.3.0_1
==> Upgrading yasm 
==> Installing dependencies for yasm: cython
==> Installing yasm dependency: cython
==> Using the sandbox
==> Downloading https://pypi.python.org/packages/b7/67/7e2a817f9e9c773ee3995c1e1
######################################################################## 100,0%
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel

**Comment by noob403** [comment]
fick detta efter 5min

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/PD/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/PD/Library/Python/2.7/lib/python/site-packages/homebrew.pth

Jag hänger inte med vad det är jag saknar

**Comment by spaam** [comment]
jag har ingen aning tyvärr. känns som något är lite trasigt med din homebrew. plus dina paste verkar vara avklippta så svårt o se vad de skulle vara.

**Comment by noob403** [comment]
det är lugnt

**Comment by noob403** [comment]
Jag löste det , körde brew doctor och den visade att makedepend , rtmdump och svtplay-dl var unlinked.
Så jag körde brew link makedepend  etc och nu fungerar det
