### ISSUE TITLE
Installation trouble on Mac

### ISSUE THREAD

**Issue by EmmW** [spaam/svtplay-dl#642]
I have had svtplay-dl installed before (v. 1.9.3), but co-inciding with an svtplay.se update about a month ago it seased working (produced an immediate error after every download command). I then found out that there was an svtplay-dl update available (v. 1.9.4), but after having tried to update in various ways, I still cannot get svtplay-dl to work.

I have run "brew install svtplay-dl", which updates ffmpeg and youtube-dl just fine, but then says "Warning: svtplay-dl 1.9.4 already installed". When I check version with "svtplay-dl --version" it still says 1.9.3 (which obviously still doesn't work with svtplay-dl). I have now removed all found instances of "svtplay-dl" from my hard drive, and tried both "brew install svtplay-dl" and "git clone git://github.com/spaam/svtplay-dl", but to no avail.

How do I properly remove all instances of svtplay-dl, wherever they may be (since I seem to still have version 1.9.3 lying around somewhere), and which commando shall I run to make a proper new installation of version 1.9.4? Help appreciated!

**Comment by spaam** [comment]
do you have `pip`installed?   if so. do you see `svtplay-dl` in `pip list`? if so. try `pip uninstall svtplay-dl`. after that you should be able to reinstall svtplay-dl via brew

**Comment by EmmW** [comment]
Thanks! I ran "pip list" and did find svtplay-dl (1.9.3) in the list, so I ran "pip uninstall svtplay-dl", which was successful (1.9.3 removed). After that I ran "brew install svtplay-dl", but then received "Warning: svtplay-dl 1.9.4 already installed". However, when I check the version number with "svtplay-dl --version", I receive the following: "svtplay-dl: Command not found" ???

**Comment by spaam** [comment]
try: `brew unlink svtplay-dl && brew link svtplay-dl && hash -r`.  after that. do you have svtplay-dl?

**Comment by EmmW** [comment]
I tried that, with the following two results:
   Unlinking /usr/local/Cellar/svtplay-dl/1.9.4... 0 symlinks removed
   Linking /usr/local/Cellar/svtplay-dl/1.9.4... 1 symlinks created
Then I wrote "svtplay-dl --version" to check, but still received:
   svtplay-dl: Command not found
When I then tried "brew install svtplay-dl", I received the following (as usual):
   Warning: svtplay-dl 1.9.4 is already installed
I have no idea whatsoever what could be wrong with this installation, but would really appreciate your help to sort it out! :-)
/Mark

**Comment by spaam** [comment]
when you type /usr/local/bin/svtplay-dl  does that work?

**Comment by EmmW** [comment]
Yes -- finally! That did it! I have no idea what that command just did, but now svtplay-dl works on svtplay.se again -- many thanks for your patience and support with this! :-)
/Mark

**Comment by imist** [comment]
/usr/local/bin/svtplay-dl  is the absolute path to where svtplay-dl is supposed to be installed if you use brew correctly.

You seem to have a collision with another version of svtplay-dl somewhere.

What do you get if you type:

which svtplay-dl

at the command prompt?

This should tell you where the incorrect and interfering version is located.

Michael

**Comment by EmmW** [comment]
When I wrote "which svtplay-dl" I got "/usr/local/bin/svtplay-dl" back, which is what I wrote before and also solved the problem. Perhaps it was a only path problem all along (svtplay-dl looking for its folder somewhere else, where it no longer resided)? Thanks

**Comment by dentarg** [comment]
This looks resolved.
