### ISSUE TITLE
svtplay.se JSONDecodeError

### ISSUE THREAD

**Issue by cknoos** [spaam/svtplay-dl#648]
Been hitting this on anything I try to download:

(Below output is from: svtplay-dl -A https://www.svtplay.se/kom-ketchup-sa-gar-vi/ --verbose)

```
DEBUG [1498052162.8733118] /usr/local/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/kom-ketchup-sa-gar-vi/'
DEBUG [1498052163.834121] /usr/local/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/kom-ketchup-sa-gar-vi/rss.xml'
INFO [1498052163.9871473] /usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 15
INFO [1498052163.987317] /usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_all_episodes: Url: https://www.svtplay.se/video/138695/kom-ketchup-sa-gar-vi/kom-ketchup-sa-gar-vi-sasong-1-avsnitt-1
DEBUG [1498052163.9874523] /usr/local/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/138695/kom-ketchup-sa-gar-vi/kom-ketchup-sa-gar-vi-sasong-1-avsnitt-1'
DEBUG [1498052164.8840272] /usr/local/lib/python3.5/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1138000-001A'
ERROR [1498052165.5496392] /usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.4
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 223, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/__init__.py", line 244, in get_one_media
    for i in streams:
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/service/svtplay.py", line 74, in get
    janson = res.json()
  File "/usr/local/lib/python3.5/site-packages/requests/models.py", line 894, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by selepo** [comment]
There are no episodes avavilable for the url stated above. 
Does this happen for any other urls ?

**Comment by Sopor-** [comment]
It seems that all the rss feed has stopped working on SVTPlay and if i'm not wrong, svtplay-dl use that to download?

**Comment by selepo** [comment]
@Sopor- At least some programs seems to have [rss](https://www.svtplay.se/allsang-pa-skansen/rss.xml) available. Can you give an example of an URL that does not work ?

**Comment by Sopor-** [comment]
@selepo I use `https://www.svtplay.se/senaste/rss.xml` and `https://www.svtplay.se/sista-chansen/rss.xml` to run in Kodi, but maybe it was only those feeds that stopped working? I haven't tried any other links.
When i saw this issue and it was -A included i guessed it could be related when my rss feed didn't worked either. I did some random testing but i couldn't find any other program that was missing the feed so i don't think this is related.

**Comment by selepo** [comment]
Ok, so question is if we can close this, or if there are any url that has the stated issue.

**Comment by spaam** [comment]
the issue here is that we try to read something that is not json with json. 
see this line 
```
  File "/usr/local/lib/python3.5/site-packages/svtplay_dl/service/svtplay.py", line 74, in get
    janson = res.json()
``` 
in the output. we should handle that.  this is not something with rss.xml or similar

**Comment by Sopor-** [comment]
I found one without rss feed `https://www.svtplay.se/video/998829/en-pilgrims-dod/rss.xml`

**Comment by selepo** [comment]
I am now getting this error repeatedly also. Has SVT changed something the last couple of days ?

**Comment by spaam** [comment]
can you reproduce this every time on same video?  can you show me the output from -v ?

**Comment by selepo** [comment]
Ja, dock använder jag x-header. (befinner mig utomlands)
https://www.svtplay.se/video/15367469/top-of-the-lake/top-of-the-lake-china-girl-sasong-2-the-loved-one

DEBUG [1507052348.5941002] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.svtplay.se/video/15367469/top-of-the-lake/top-of-the-lake-china-girl-sasong-2-the-loved-one'
DEBUG [1507052351.096899] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1379045-002A'
ERROR [1507052351.377678] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\svtplay.py", line 74, in get
  File "site-packages\requests\models.py", line 826, in json
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Failed to execute script svtplay-dl

**Comment by spaam** [comment]
jag kan inte reproducera det.. kan du ge mig outputen från: curl -v -H "X-Forwarded-For: 8.8.8.8 http://api.svt.se/videoplayer-api/video/1379045-002A  . byt ut 8.8.8.8 med det ip du använder med svtplay-dl

**Comment by selepo** [comment]
* TCP_NODELAY set
* Connected to api.svt.se (46.246.93.157) port 80 (#0)
> GET /videoplayer-api/video/1379045-002A HTTP/1.1
> Host: api.svt.se
> User-Agent: curl/7.55.1
> Accept: */*
> X-Forwarded-For: 192.71.3.91
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Moved Temporarily
< Server: squid/3.1.23
< Mime-Version: 1.0
< Date: Tue, 03 Oct 2017 18:40:14 GMT
< Content-Type: text/html
< Content-Length: 0
< Location: http://error.unlocator.com
< X-Squid-Error: 403 Access Denied
< X-Cache: MISS from my.test.com
< X-Cache-Lookup: NONE from my.test.com:3128
< Via: 1.0 my.test.com (squid/3.1.23)
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
<
* Connection #0 to host api.svt.se left intact

**Comment by spaam** [comment]
are you using https://unlocator.com/? :)

**Comment by selepo** [comment]
Yes, is that the issue?

**Comment by spaam** [comment]
verkar va något fel med det. `X-Squid-Error: 403 Access Denied`  och den redirectar till http://error.unlocator.com. så det är inte något fel på själva svtplay-dl.   men visst borde inte crasha när vi inte får json tillbaka.
