### ISSUE TITLE
Dplay - ERROR: Cant find any playable files when using -A

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#650]
When i try to download from `http://www.dplay.se/gisslantagningen` with -A i get this message:
```
$ svtplay-dl -A -S -P hls http://www.dplay.se/gisslantagningen/
ERROR: Cant find any playable files
```
The page have 7 premium episodes and 1 without but for some reason it can't find episode 1 when using
`-A`. If i download only episode 1 it do work but i should be able to use -A and those files that it can't download should be skipped. Now it download nothing :(

**Comment by spaam** [comment]
i see the issue. we check only the first episode in the list which is the lastest episode.
