### ISSUE TITLE
Some episode on tv4play.se doesn’t work, tells me to download the new tv4play app

### ISSUE THREAD

**Issue by sigun004** [spaam/svtplay-dl#662]
Some episode on tv4play.se doesn’t work, tells me to download the new tv4play app
I tried to use svtplay-dl to download some videos from tv4play.se and I got a short video that tells me to download the new tv4play app.

Some example that doesn’t work at tv4play.se
https://www.tv4play.se/program/halvv%C3%A4gs-till-himlen?video_id=2449047
https://www.tv4play.se/program/halvv%C3%A4gs-till-himlen?video_id=2975140
https://www.tv4play.se/program/halvv%C3%A4gs-till-himlen?video_id=3355655
https://www.tv4play.se/program/familjen-annorlunda?video_id=2265025
https://www.tv4play.se/program/familjen-annorlunda?video_id=2311177
https://www.tv4play.se/program/familjen-annorlunda?video_id=2580797

Some example that work at tv4play.se
https://www.tv4play.se/program/sm%C3%A5staden?video_id=3928117
https://www.tv4play.se/program/farang?video_id=3921819

I tried svtplay.se dplay.se viafree.se and that works fine.

What could I do to solve the problem?
I use Ubuntu.

**Comment by spaam** [comment]
i tried "https://www.tv4play.se/program/halvv%C3%A4gs-till-himlen?video_id=2449047" andit works fine.
https://www.tv4play.se/program/familjen-annorlunda?video_id=2311177 it will download 200+ parts for the file
what version of svtplay-dl do you have?

**Comment by sigun004** [comment]
Thanks, 
I had updated the version of svtplay-dl and reinstalled svtplay-dl and that didn’t help. Then I asked. When I checked the version it was unknown. I reinstalled the client and then installed svtplay-dl and prerequisite and that worked. :)
