### ISSUE TITLE
Downloading from Aftonbladet only works on Aftonbladet TV

### ISSUE THREAD

**Issue by Amitari** [spaam/svtplay-dl#664]
Downloading from Aftonbladet only works on the tv.-subdomain, not when it's part of an article like the following: [https://www.aftonbladet.se/nojesbladet/a/8292d/gws-harda-ord-mot-svt-kommer-fa-stora-problem-med-fler-an-mig](url)

**Comment by spaam** [comment]
this will be in the next 1.9.5 release that will be out this weekend.

**Comment by spaam** [comment]
thanks for the bug report <3
