### ISSUE TITLE
Add npo.nl

### ISSUE THREAD

**Issue by MKaterbarg** [spaam/svtplay-dl#666]
Npo.nl is the dutch equivelant of svtplay.se. Youtube-dl does support them, but only for the latest videos.

NPO also has paid accounts, NPO Start Plus, allowing more videos and better quality. Support for that is highly requested. Login for developers is available if they contact me

**Comment by durian** [comment]
What about uitzendinggemist.nl? That's also public Dutch TV, and would also be nice to have.

**Comment by MKaterbarg** [comment]
That comes to the same page. I think adding support for the premium content where you need to login for, is most interesting however.
I'm currently working on getting to it with cURL. There's a few steps to be taken, so far I've gotten as far as getting the .MPD file, which they seem to be using for content

**Comment by durian** [comment]
Indeed it does, missed it when I checked yesterday.

**Comment by MKaterbarg** [comment]
Further along. Using PHP and curl I've been able to download all the .dash files required, both video and audio. Just need to figure out how to join them. catting all audio dash files results in each fragment being played twice.

Any python devver who wants to work with me on getting this into this program, let me know!
