### ISSUE TITLE
TV4 Can't find video id

### ISSUE THREAD

**Issue by diskpart** [spaam/svtplay-dl#674]
svtplay-dl https://www.tv4play.se/program/idol/3933169
ERROR: Can't find video id for https://www.tv4play.se/program/idol/3933169

Same problem with non premium content like the news.

Using the 1.9.4 windows exe

**Comment by spaam** [comment]
this will be in 1.9.5 release later today

**Comment by wahboh** [comment]
Hi spaam, and thanks for your dedicated work!

When will version 1.9.5 be released for Windows? I do believe a majority of the users use the self-contained Windows distribution, but it is very hard to create yourself from GitHub. Can you assist?
BR
