### ISSUE TITLE
svtplay-dl does not work with tv4play.se anymore

### ISSUE THREAD

**Issue by Kvilimas** [spaam/svtplay-dl#675]
Just throwing out "Can't  find video id for <url>"

**Comment by spaam** [comment]
this was fixed in #674 .. i will release a new version later today with the fix  :)

**Comment by yabbah** [comment]
This new version isn't released yet?

**Comment by MaistroX** [comment]
Will it be released today?

**Comment by diskpart** [comment]
What's the ETA on 1.9.5?

Btw thanks for all your work. Love this program!

**Comment by anders55j** [comment]
Possible workaround until release, if your url looks like https://www.tv4play.se/program/parlamentet/3934756
use https://www.tv4play.se/program/parlamentet?video_id=3934756 instead.

**Comment by spaam** [comment]
1.9.5 is out right now :) 
1.9.6 with some new fixes for tv.aftonbladet, svtplay and dash will be out tonight :) 

thanks for the bug report <3
