### ISSUE TITLE
Could support for urskola.se be added?

### ISSUE THREAD

**Issue by crapmaster** [spaam/svtplay-dl#677]
Lots of interesting programs there!

**Comment by spaam** [comment]
we already have support for it. it doesnt work or do you get any error message with 1.9.4?

**Comment by crapmaster** [comment]
Aha, it seems to be --all-episodes switch not working.

$ svtplay-dl --remux --subtitle  --all-episodes -o ~/Downloads/Justitia/ http://urskola.se/Produkter/186953-Justitia-Hatbrott
ERROR: Can't find any videos
$ svtplay-dl --remux --subtitle -o ~/Downloads/Justitia/ http://urskola.se/Produkter/186953-Justitia-Hatbrott
INFO: Outfile: /home/petjan/Downloads/Justitia/justitia.hatbrott-ur.skola.srt
INFO: Selected to download hls, bitrate: 2945
....
