### ISSUE TITLE
mv: replace ‘./svtplay-dl’, overriding mode 0755 (rwxr-xr-x)?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#680]
I use `master` so i run `git pull` and then `make` and finally `sudo make install` and it has worked until a few versions ago. Now i get `mv: replace ‘./svtplay-dl’, overriding mode 0755 (rwxr-xr-x)?` when i run `make`. I do the exact same thing as i always have. I even did a new `clone` but that didn't helped.
Do you know why this happens and can you do something about it?

**Comment by spaam** [comment]
this is fixed by #694
