### ISSUE TITLE
Login to cmore

### ISSUE THREAD

**Issue by selepo** [spaam/svtplay-dl#681]
There are two types of login to cmore. One that require username / password and  one that require username/password + country_code=se/operator=xxxx, where xxx can be for example boxer, bredbandbolaget, etc. 

There only seems to be support for the first one, in addition if login fails there is crash:

`svtplay-dl -u 1 -p 2 -v https://www.cmore.se/serie/3446-game-of-thrones/sasong-7/episod-7/3929616-game-of-thrones-the-dragon-and-the-wolf
DEBUG [1505743953.2612238] site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.cmore.se/serie/3446-game-of-thrones/sasong-7/episod-7/3929616-game-of-thrones-the-dragon-and-the-wolf'
DEBUG [1505743953.739353] site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.cmore.se/login'
DEBUG [1505743953.7642095] site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://account.cmore.se/session?client=web'
ERROR [1505743954.0096095] site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.5
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\__init__.py", line 469, in main
  File "site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\service\cmore.py", line 21, in get
  File "site-packages\svtplay_dl-1.9.5-py3.5.egg\svtplay_dl\service\cmore.py", line 110, in _login
KeyError: 'data'
Failed to execute script svtplay-dl`

We should at least make sure a failed login doesn't create crash. 
I think is fairly simple to support also ofter login with operator, but then where should that info go in the command line ?

**Comment by spaam** [comment]
good catch. lets see how we can deal with that

**Comment by spaam** [comment]
i guess we should add a new argument for cmore-operator.
i have something like that planned for 2.0. like --cmore-username --cmore-password. then we can store that in a config file with other things.

**Comment by selepo** [comment]
I think that makes sense !

**Comment by selepo** [comment]
This should be closed, was fixed by spaam in version 1.9.6.
