### ISSUE TITLE
1.9.5 for brew

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#682]
Hi! Is it possible to upload 1.9.5. for brew? That would be awesome :D

**Comment by spaam** [comment]
yeah. brew will have a pull request for 1.9.6 in a few hours.
1.9.5 had a bug that we had to fix :)

**Comment by ijbh** [comment]
Yeay, thanks!

**Comment by mannesson** [comment]
Still 1.9.4 on brew :(

**Comment by spaam** [comment]
sorry for the delay for 1.9.6.. was some issues with the brew formula. but that is fixed now. thanks for the bug report <3
