### ISSUE TITLE
Crashes when trying to download URL containing Ø

### ISSUE THREAD

**Issue by sjuktstarkgrogg** [spaam/svtplay-dl#683]
I was trying to download a video from NRK which has an URL containing Ø and therefore svtplay-dl crashes.

**Comment by qnorsten** [comment]
can you please post the error you are receiving when running the command with the --verbose parameter?

It might be an issue with your shell/commandpromt.

**Comment by dentarg** [comment]
Can't find any videos on https://tv.nrk.no/ with an URL that contain Ø, but I faked one:

```
$ svtplay-dl --verbose https://tv.nrk.no/serie/oeystein-og-meg/FUHA16000801/fooØfoo
DEBUG [1506209201.1] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://tv.nrk.no/serie/oeystein-og-meg/FUHA16000801/foo\xc3\x98foo'
DEBUG [1506209201.41] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://psapi-we.nrk.no//mediaelement/FUHA16000801'
...
```

Works for me with svtplay-dl 1.9.6.

> It might be an issue with your shell/commandpromt.

I think so too, something like https://github.com/spaam/svtplay-dl/issues/430 maybe?

**Comment by dentarg** [comment]
I will close as we lack info to continue debug this issue. We can re-open if we get more info on how to reproduce the crash.
