### ISSUE TITLE
Replace pyinstaller with something better

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#692]
[pynsist](http://pynsist.readthedocs.io/en/latest/index.html)
- pros: py3 support
- cons: not a single file
- other: it will create a installer for the script

[cx_Freeze](https://anthony-tuininga.github.io/cx_Freeze/)
- pros: py3 support
- cons: not single file .exe
- other: bunch of files in the directory

[py2exe](http://www.py2exe.org/)
- pros: single file .exe
- cons: no py3 support ( really a deal breaker )

**Comment by granbom** [comment]
Maybe have a look at nuikta to? http://nuitka.net/pages/overview.html Not that I'm affiliated with it or anything just googled a bit the other day when I saw the virus issue.

**Comment by spaam** [comment]
@granbom yes that sounds like an awesome idea :)

**Comment by granbom** [comment]
Are you implying that I should look into Nukita? =)
Sorry, but I can't make those decisions for you.

**Comment by spaam** [comment]
I will look into it :)

-- 
Johan Andersson

**Comment by dalgr** [comment]
@spaam 
I would suggest py2exe as it supports python 3:
https://pypi.python.org/pypi/py2exe/

**Comment by spaam** [comment]
Nukita creates two files svtplay-dl.exe and python36.dll . if i use that. we need to zip  both files and ship it. 
@dalgr its not working with py36

**Comment by spaam** [comment]
using nuitka now to create the file
