### ISSUE TITLE
--all-last=n doesn't always do the right thing

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#696]
I use `--all-last=1` on viafree to download only the latest episode but now suddenly it will download episode 01 instead of episode 04. Some channels don't list the episodes from newest to oldest but viafree do that but now suddenly svtplay-dl have changed the download order and download oldest first. Or is it viafree that have changed something?
```
svtplay-dl -A -S -P hls --all-last=1 https://www.viafree.se/program/livsstil/skonhetsfallan-sverige
INFO: Episode 1 of 1
INFO: Url: https://www.viafree.se/program/livsstil/skonhetsfallan-sverige/sasong-3/avsnitt-1
INFO: Selected to download hls, bitrate: 2465
INFO: Outfile: skonhetsfallan-sverige.s03e01-870310-viafree.ts
[021/260][=====.................................................................] ETA: 0:01:20
```
(episode 01 don't have any subtitles for some unknown reason)

It should be downloading:
INFO: Outfile: skonhetsfallan-sverige.s03e04-876731-viafree.ts

**Comment by Sopor-** [comment]
It seems that even dplay have changed download order, so this must have something to do with svtplay-dl.

**Comment by Sopor-** [comment]
I downloaded https://www.viafree.se/program/livsstil/skonhetsfallan-sverige with the older 1.9.4 and it seems to download episode 01. So it seems to be viafree that have changed it.

**Comment by Sopor-** [comment]
Is it possible to fix? `--all-last` should download from newest to oldest or else this is not very usable. Some channels it works on and some not. Maybe add a new switch so the user can choose the download order?

**Comment by dentarg** [comment]
Yes, seems that the should specify the order the site is using

**Comment by dentarg** [comment]
Could maybe be solved without a new switch, by sorting on something. (Haven't looked at the code)
