### ISSUE TITLE
ERROR: svtplay-dl crashed

### ISSUE THREAD

**Issue by KGBGit** [spaam/svtplay-dl#702]
Tried to download 
svtplay-dl -S https://www.svtplay.se/video/15344189/falsk-identitet/falsk-identitet-sasong-3-avsnitt-3?start=auto
svtplay-dl --version
1.9.3
Altough it is 1.9.6, newly downloaded and installed.

And this one,
ERROR: Can't find video id for https://www.tv4play.se/program/farang/3922024

**Comment by spaam** [comment]
it works great with 1.9.6 for both those urls. why it show up as 1.9.3 and not 1.9.6 , i have no idea why.
