### ISSUE TITLE
ERROR: svtplay-dl crashed

### ISSUE THREAD

**Issue by KGBGit** [spaam/svtplay-dl#703]
Still won't work
svtplay-dl -S https://www.svtplay.se/video/15344189/falsk-identitet/falsk-identitet-sasong-3-avsnitt-3?start=auto
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

What can I have done wrong.
It has been working for at least one year and suddenly today...no!

**Comment by spaam** [comment]
what version do you get when you use: svtplay-dl --version? 
older then 1.9.6? if so how did you install it? 
does it happen all the time? if so. please add `-v` as a argument
it works fine here.

**Comment by KGBGit** [comment]
I get 1.9.3 but when I use this
brew upgrade svtplay-dl
Error: svtplay-dl 1.9.6 already installed

**Comment by KGBGit** [comment]
svtplay-dl -S -v https://www.svtplay.se/video/15344189/falsk-identitet/falsk-identitet-sasong-3-avsnitt-3?start=auto
DEBUG [1507219408.52] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svtplay.se/video/15344189/falsk-identitet/falsk-identitet-sasong-3-avsnitt-3?start=auto'
DEBUG [1507219412.67] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1379081-003A'
DEBUG [1507219413.0] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9e-f.akamaihd.net/z/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1507219413.9] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1379081-003A.m3u8'
DEBUG [1507219414.82] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_0_av.m3u8?null=0'
DEBUG [1507219415.08] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_1_av.m3u8?null=0'
DEBUG [1507219415.74] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_2_av.m3u8?null=0'
DEBUG [1507219416.66] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_3_av.m3u8?null=0'
DEBUG [1507219416.97] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_4_av.m3u8?null=0'
DEBUG [1507219417.89] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_5_av.m3u8?null=0'
DEBUG [1507219418.17] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9h-f.akamaihd.net/i/se/open/20170928/1379081-003A/PG-1379081-003A-BUREAUDESLEGEN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/index_6_av.m3u8?null=0'
DEBUG [1507219418.81] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1379081-003A.m3u8'
DEBUG [1507219420.41] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/playlist.m3u8'
DEBUG [1507219420.42] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b988000_slsv.m3u8'
DEBUG [1507219420.43] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b240000_slsv.m3u8'
DEBUG [1507219420.44] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b348000_slsv.m3u8'
DEBUG [1507219420.45] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b456000_slsv.m3u8'
DEBUG [1507219420.46] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b636000_slsv.m3u8'
DEBUG [1507219420.48] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b1680000_slsv.m3u8'
DEBUG [1507219420.49] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/chunklist_b2796000_slsv.m3u8'
DEBUG [1507219420.5] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay9f-f.akamaihd.net/d/se/open/delivery/20170928/1379081-003A/dash-live/PG-1379081-003A-BUREAUDESLEGEN-01-3c4c7f42-e111-4aab-aab8-56e5a7d302fd-44fd1bb0-6bc5-336d-da60-ad40d92f3713-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1379081-003A.mpd'
DEBUG [1507219421.64] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1379081-003A.mpd'
DEBUG [1507219421.66] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed5.cdn.svt.se/vod/_definst_/amlst:20170928/1379081-003A/c651029a-ef3f-41d2-9e92-248f3a455e4b/PG-1379081-003A-BUREAUDESLEGEN-01/manifest.mpd'
ERROR [1507219421.67] /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.3', 'svtplay-dl')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 464, in main
    get_media(urls[0], options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/__init__.py", line 242, in get_one_media
    for i in streams:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/service/svtplay.py", line 125, in get
    streams = dashparse(self.options, self.http.request("get", alt.request.url), alt.request.url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/fetcher/dash.py", line 61, in dashparse
    videofiles = parsesegments(video, url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/svtplay_dl/fetcher/dash.py", line 121, in parsesegments
    for n in time:
TypeError: 'bool' object is not iterable

**Comment by KGBGit** [comment]
brew uninstall --force --ignore-dependencies svtplay-dl
Uninstalling svtplay-dl... (1,058 files, 12.2MB)

svtplay-dl --version
1.9.3
??????

**Comment by spaam** [comment]
it looks like you installed svtplay-dl via setup.py .   try this: `sudo rm -rf /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/svtplay_dl-1.9.3-py2.7.egg/`  it will remove it.

**Comment by KGBGit** [comment]
Tried both above...and when I reinstalled 1.9.6 and wrote "svtplay-dl" this came up.
What have I done wrong?

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/svtplay-dl", line 4, in <module>
    __import__('pkg_resources').run_script('svtplay-dl==1.9.3', 'svtplay-dl')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'svtplay-dl==1.9.3' distribution was not found and is required by the application

**Comment by KGBGit** [comment]
Uninstalled Pyton and removed all Pyton files, now everything is working again.

Thanks a lot.

**Comment by dentarg** [comment]
Doesn't look like an svtplay-dl issue, and also it's resolved. Closing.
