### ISSUE TITLE
Failure to parse video id from URLs instead of GET 

### ISSUE THREAD

**Issue by lazyoldbear** [spaam/svtplay-dl#712]
As of 1.9.6, we noticed that svtplay fails with URLs like "https://www.tv4play.se/program/parlamentet/3934756", but works with "https://www.tv4play.se/program/parlamentet?video_id=3934756".
Could be related to #707.

**Comment by dalgr** [comment]
I have tested, and both link work fine with the recent master. I have tested with both python 2 and 3, under Linux Debian 9.

**Comment by lazyoldbear** [comment]
Probably, due to 9284c4d76c31e781ca9cc4996ce54e046294a8ef. 
Good to know, this means next version will probably fix that.

**Comment by dalgr** [comment]
9284c4d won't affect that problem

**Comment by lazyoldbear** [comment]
That was an error on our side: we just checked that we've been using master for some random moment. I apologise for the mistake.

**Comment by spaam** [comment]
ah okey . good thing you found the issue  :D thanks for the bug report <3
