### ISSUE TITLE
Download bar on Windows 10, Cygwin

### ISSUE THREAD

**Issue by dalgr** [spaam/svtplay-dl#713]
Currently my download bar on windows look like:
```
INFO: Selected to download dash, bitrate: 3185
INFO: Outfile: helikopterranet.s01e05.avsnitt.5.rattegangen-7f68ecd-svtplay.m4a
139
79
139
79
...
```
It writes out 139 and 79 over and over. 
I am running Windows 10 with `Python 2.7.11`(win, not cygwin). I also have cygwin x64 installed which I uses to run svtplay-dl. Used svtplay-dl is built from the latest master (with cygwin).

**Comment by spaam** [comment]
cygwin interesting. that was some years ago i heard anything about that :)

hmm is it always 79 and 139?

**Comment by spaam** [comment]
https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/utils/terminal.py#L8  is ze code.. it should work with cygwin.

**Comment by spaam** [comment]
is your terminal 139x79?

**Comment by dalgr** [comment]
I have it working when I change('_get_terminal_size_tput'in 'utils.output') to:
```
cols = int(subprocess.check_output(shlex.split('tput cols')))
rows = int(subprocess.check_output(shlex.split('tput lines')))
```
from
```
cols = int(subprocess.check_call(shlex.split('tput cols')))
rows = int(subprocess.check_call(shlex.split('tput lines')))
```

Got a pull request with this change

**Comment by dalgr** [comment]
yes, my terminal was 139x79

**Comment by spaam** [comment]
i dont think it will break something. :)

**Comment by dalgr** [comment]
It seem like `subprocess.check_call` gets called direct in cygwin instead of background.

**Comment by spaam** [comment]
it worked in cmd under windows. i dont have cygwin.
