### ISSUE TITLE
Add support for telia play +

### ISSUE THREAD

**Issue by dalgr** [spaam/svtplay-dl#721]
Support for: https://playplus.telia.se/

Telia play + uses `Microsoft silverlight` and `IIS Smooth Streaming`, as far as i know.

**Comment by MR-2** [comment]
@dalgr it's encrypted.

**Comment by dalgr** [comment]
Relevant info: https://github.com/rg3/youtube-dl/issues/8118

**Comment by dalgr** [comment]
@MR-2 Ok so(http://www.iis.net/learn/media/transform-manager/encrypting-on-demand-smooth-streams), that is a bit harder

**Comment by dalgr** [comment]
unlikely to happen
