### ISSUE TITLE
TV4 Play issue

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#722]
I'm using Terminal on Mac. When I try downloading from TV4 it says:

>  "ERROR: Cant find vid id for autonaming".

**Comment by spaam** [comment]
what version are you using?

**Comment by ijbh** [comment]
Hi! I'm using 1.9.6. That's the latest one right? At least the latest one uploaded to brew?

**Comment by spaam** [comment]
yep. what video are you trying to download?

**Comment by ijbh** [comment]
Any video really. This one for example: https://www.tv4play.se/program/nyheterna/3940428

**Comment by ijbh** [comment]
Actually, for this video the error message is

> ERROR: Can't find video id for https://www.tv4play.se/program/nyheterna/3940428

If that makes a differene...

**Comment by granbom** [comment]
Any video found on tv4play site works for me. Maybe tv4 removed this one? Are you able to find it on their site, and if so, how?

**Comment by ijbh** [comment]
Yeah, just click the link and you'll see it works.

**Comment by granbom** [comment]
Guess it is some kind of livestream on that ID, not a single program. Hence TV4 haven't published it with any information in their API.
The different clips that they are streaming there most likely will be found with different IDs on their site.

**Comment by ijbh** [comment]
Huh, that's weird. So for the same clip it apparently makes a difference whether you right-click on the clip's tumbnail preview to get the link OR if you first click the link and then cut the address from the url-bar. You either get:

https://www.tv4play.se/program/link/3940360  OR
https://www.tv4play.se/program/nyhetsmorgon/3940360

One works in Terminal and the other doesn't. Well, now that I know a work-around it's all fine. Good for people to know maybe if it's the same case for all shows on TV4 Play.

**Comment by spaam** [comment]
this is two different issues. "ERROR: Cant find vid id for autonaming" is one issue.  we search for the video in their api to get a proper name for it. 
"ERROR: Can't find video id for ..."  that is  used for getting the info where to download the videos.

**Comment by spaam** [comment]
the issue why "https://www.tv4play.se/program/link/3940360" is not working but "https://www.tv4play.se/program/nyhetsmorgon/3940360" works  is the word "link" and "nyhetsmorgon".  we look for the showname between the id and program. there is no show called "link". that is why it failed for autonaming thing.  you can do a workaround and type your own name instad using `-o super_cool_video_from_tv4play.ext`
