### ISSUE TITLE
Kommer inte åt C-More, "ERROR: Wrong username or password"

### ISSUE THREAD

**Issue by DuaneDibbley** [spaam/svtplay-dl#729]
När jag tittar i webläsaren, loggar jag in med mitt TV4Play-konto. TV4Play finns inte i listan över operatörer, så jag har provat att ange cmore och min internetoperatör, men båda ger samma felmeddelande. Om jag inte anger operatör alls, blir det istället "ERROR: DRM protected. Can't do anything"

Jag har kollat noga så att användarnamn och lösenord är korrekt.

**Comment by spaam** [comment]
vad är det för video du försöker kolla på?  det kan vara så att videon du kollar på har DRM och vi kan inte dekryptera det.

**Comment by DuaneDibbley** [comment]
Jag har själv, genom slutledning, kommit fram till att det rör sig om DRM. Kort sagt, eftersom jag fick olika fel beroende på om jag angav operatör (med --cmore-operator) eller inte, tolkar jag det som att jag inte ska ange operatör när jag loggar in med mitt TV4Play-konto, och att inloggningen faktiskt fungerade då, men videon inte kunde dekrypteras. Det var senaste säsongen av Gåsmamman jag försökte ladda ned.

Men har C-More överhuvudtaget något DRM-fritt material? Annars är det väl ganska meningslöst att stödja C-More?
