### ISSUE TITLE
Some videos not working on NRK TV

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#732]
I'm trying to download https://tv.nrk.no/serie/backstage/MSUI14001216/sesong-1/episode-12 from NRK, but it doesn't seem to work. Using Windows binary of version 1.9.6.

I'm using:
svtplay-dl -S --raw-subtitles --remux --verbose https://tv.nrk.no/serie/backstage/MSUI14001216/sesong-1/episode-12

Output:
> DEBUG [1509686998.6648536] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://tv.nrk.no/serie/backstage/MSUI14001216/sesong-1/episode-12'
> DEBUG [1509687000.109535] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://psapi-we.nrk.no//mediaelement/MSUI14001216'
> DEBUG [1509687000.577094] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://nordond13b-f.akamaihd.net/i/no/open/09/0974e501c1124e99f57a7be7184481b0dbdb77f2/cfe28b39-94d4-42c3-90ac-9084c7cb8d45_,141,316,563,1266,2250,.mp4.csmil/master.m3u8'
> ERROR [1509687001.001647] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
> Traceback (most recent call last):
>   File "svtplay-dl", line 7, in <module>
>   File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
>   File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
>   File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
>   File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\nrk.py", line 55, in get
> AttributeError: 'NoneType' object has no attribute 'keys'
> Failed to execute script svtplay-dl
> 

Why is that? As far as I can tell, all other episodes of the same show is working fine.

**Comment by spaam** [comment]
this is fixed in master and will be in 1.9.7
