### ISSUE TITLE
Dplay - How to download only one season?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#739]
How do i download only one specific season from dplay? Dplay.se do have seasons tabs, but when i press on the season tab the URL won't change so how do i download only one season from dplay?

**Comment by Sopor-** [comment]
I'm using `--exclude=s01,s02,s03,s04,s05,s06,s07,s08` and it is working but when a program have several seasons it is not sustainable. Ullared have 78 episodes and when using --exclude it will skip about 70 episodes (season 01-08) and it takes too long time.
I then tried to use one of the episode from season 09 and -A but it will again download all 70+ episodes. So is it possible to only download a specific episode or download in descending order?
Exclude (and include if you add it) only work when you don't have many episodes to skip. I hope you can use the "Säsong X" to download one season only. You can see [here](https://www.dplay.se/videos/ullared/ullared-901) it will only show episodes from season 09.

**Comment by spaam** [comment]
i dont see any good way to do it right now.
maybe somehow this will get fixed sometime in the future somehow.
i dont see this right now as a top priority right now.

**Comment by spaam** [comment]
if those "Säsong X" was links it would be easier. but they are not.

**Comment by Sopor-** [comment]
@spaam If you use the first episode it could use that to download only that season or that isn't possible?
`https://www.dplay.se/videos/tunnelbanan/tunnelbanan-801`
If i use the exclude it will now have to exclude 84 episodes if i use -A :(

**Comment by Sopor-** [comment]
It is possible to list all episodes from a specific season by opening one of the episodes in that season, https://www.dplay.se/videos/sofias-anglar/sofias-anglar-1101 will only list season 11. Could this be used with -A the same way i can download a specific season from svtplay https://www.svtplay.se/scott-och-bailey?tab=sasong5 ?
