### ISSUE TITLE
Can't find video id with C More

### ISSUE THREAD

**Issue by fredrikjohnsson** [spaam/svtplay-dl#750]
I can't get videos from C More, I get the error "Can't find video id". 

I'm using 1.9.6 on a Mac and I'm using the following commands:
svtplay-dl -v -u <USERNAME> -p <PASSWORD> https://www.cmore.se/film/3920998-hundraettaringen-som-smet-fran-notan-och-forsvann

It returns:
DEBUG [1513531589.11] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.cmore.se/film/3920998-hundraettaringen-som-smet-fran-notan-och-forsvann'
DEBUG [1513531589.2] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.cmore.se/login'
DEBUG [1513531589.22] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://account.cmore.se/session?client=web'
DEBUG [1513531589.39] /usr/local/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.cmore.se/film/3920998-hundraettaringen-som-smet-fran-notan-och-forsvann'
ERROR [1513531589.41] /usr/local/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: Can't find video id

**Comment by spaam** [comment]
1.9.7 will have a fix for this. it will be released this weekend. thanks for the bug report :)
