### ISSUE TITLE
Different download URLs if i use tab or tab and section

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#760]
Different download URLs if i use tab or tab and section:
```
svtplay-dl -A -S -P hls https://www.svtplay.se/bron?tab=sasong3
INFO: Episode 1 of 20
INFO: Url: http://www.svtplay.se/video/3813639/bron/bron-sasong-3-avsnitt-1

svtplay-dl -A -S -P hls https://www.svtplay.se/bron?tab=sasong1#section-sasong1
INFO: Episode 1 of 10
INFO: Url: http://www.svtplay.se/video/8169480/bron/bron-sasong-1-avsnitt-1

```
You can see the difference between using tab and tab and section. When i only use tab i get 20 episodes. This because when i only use tab it will also download `syntolkat`. I don't know if this could be fixed?

**Comment by spaam** [comment]
they have `syntolkat` in season 3 and not in season 1. i cant add support for `syntolkat` for season 1.. i dont see this as a bug.
