### ISSUE TITLE
sudo apt install svtplay-dl gives dependency error

### ISSUE THREAD

**Issue by e8quarl** [spaam/svtplay-dl#767]
I get the following error when doing 'sudo apt install svtplay-dl'
 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
>  svtplay-dl : Depends: python-svtplay-dl (= 1.9.7-1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Trying 'sudo apt install python-svtplay-dl' gives 'python-svtplay-dl : Depends: python-pysocks but it is not installable'. Finally, trying 'sudo apt install python-pysocks' I get the following

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Package python-pysocks is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   python-socks
> 
> E: Package 'python-pysocks' has no installation candidate

Googling this I find someone has the same problem, but for python-streamlink:

[https://github.com/streamlink/streamlink/issues/1341](url)

**Comment by spaam** [comment]
@e8quarl  it should be fixed now with 1.9.7-3. thanks for the bugreport <3

**Comment by theinmostdens** [comment]
Ubuntu 14

svtplay-dl --version
1.9.6

sudo apt-get install svtplay-dl
The following packages have unmet dependencies:
 svtplay-dl : Depends: python-svtplay-dl (= 1.9.7-3) but 1.9.6 is to be installed
E: Unable to correct problems, you have held broken packages.

sudo apt-get install python-svtplay-dl
The following extra packages will be installed:
  python-svtplay-dl
Recommended packages:
  ffmpeg
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.

How to install 1.9.7?

**Comment by spaam** [comment]
@theinmostdens that is fixed now . apt-get update and upgrade / install it should be fixed
