### ISSUE TITLE
New problem dowloading from svtplay

### ISSUE THREAD

**Issue by ijbh** [spaam/svtplay-dl#775]
Hi, I'm using Terminal and Brew on Mac to download the following link:

> https://www.svtplay.se/video/16716845/guldbaggen/guldbaggen-2018-roda-mattan-for-gala-galan-och-eftersnack

First, I got this error message:

> ERROR: svtplay-dl crashed
> ERROR: Run again and add --verbose as an argument, to get more information
> ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
> ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

I first upgraded svtplay-dl. When trying to dowload again I got a new error message after just pasting the link into Terminal, I didn't even have to press ENTER!

> INFO: Outfile: guldbaggen.gala.med.eftersnack-e296f59-svtplay.mp4
> Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 497, in main
>     get_media(urls[0], options)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 209, in get_media
>     get_one_media(stream, copy.copy(options))
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 330, in get_one_media
>     stream.download()
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 157, in download
>     self._download2(self.files)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 172, in _download2
>     eta = ETA(len(files))
> TypeError: object of type 'None

After a few seconds the following error message would follow unprompted:

> Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 499, in main
>     get_multiple_media(urls, options)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 182, in get_multiple_media
>     get_media(url, copy.copy(options))
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 195, in get_media
>     url, stream = generic.get(sites)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/service/__init__.py", line 115, in get
>     data = self.http.request("get", self.url).text
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 68, in request
>     res = Session.request(self, method, url, verify=self.verify, proxies=self.proxy, *args, **kwargs)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='info', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108cbfcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
> Js-MacBook-Pro:~ jhenriksson$ INFO: Outfile: guldbaggen.gala.med.eftersnack-e296f59-svtplay.mp4
> -bash: INFO:: command not found
> Js-MacBook-Pro:~ jhenriksson$ Traceback (most recent call last):
> -bash: syntax error near unexpected token `most'
> Js-MacBook-Pro:~ jhenriksson$   File "/usr/local/bin/svtplay-dl", line 7, in <module>
> -bash: syntax error near unexpected token `newline'
> Js-MacBook-Pro:~ jhenriksson$     svtplay_dl.main()
> >   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 497, in main
> -bash: syntax error near unexpected token `File'
> Js-MacBook-Pro:~ jhenriksson$     get_media(urls[0], options)
> -bash: syntax error near unexpected token `urls[0],'
> Js-MacBook-Pro:~ jhenriksson$   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 209, in get_media
> /usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py,: cannot open `/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py,' (No such file or directory)
> line:                                                                                           cannot open `line' (No such file or directory)
> 209,:                                                                                           cannot open `209,' (No such file or directory)
> in:                                                                                             cannot open `in' (No such file or directory)
> get_media:                                                                                      cannot open `get_media' (No such file or directory)
> Js-MacBook-Pro:~ jhenriksson$     get_one_media(stream, copy.copy(options))
> -bash: syntax error near unexpected token `stream,'
> Js-MacBook-Pro:~ jhenriksson$   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 330, in get_one_media
> /usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py,: cannot open `/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py,' (No such file or directory)
> line:                                                                                           cannot open `line' (No such file or directory)
> 330,:                                                                                           cannot open `330,' (No such file or directory)
> in:                                                                                             cannot open `in' (No such file or directory)
> get_one_media:                                                                                  cannot open `get_one_media' (No such file or directory)
> Js-MacBook-Pro:~ jhenriksson$     stream.download()
> >   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 157, in download
> -bash: syntax error near unexpected token `File'
> Js-MacBook-Pro:~ jhenriksson$     self._download2(self.files)
> -bash: syntax error near unexpected token `self.files'
> Js-MacBook-Pro:~ jhenriksson$   File "/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 172, in _download2
> /usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py,: cannot open `/usr/local/Cellar/svtplay-dl/1.9.7/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py,' (No such file or directory)
> line:                                                                                               cannot open `line' (No such file or directory)
> 172,:                                                                                               cannot open `172,' (No such file or directory)
> in:                                                                                                 cannot open `in' (No such file or directory)
> _download2:                                                                                         cannot open `_download2' (No such file or directory)
> Js-MacBook-Pro:~ jhenriksson$     eta = ETA(len(files))
> -bash: syntax error near unexpected token `('
> Js-MacBook-Pro:~ jhenriksson$ TypeError: object of type 'NoneType' has no len()

I've only had time to try a few other videos from svtplay and they seem to be working. So maybe it is just this show?

Thanks in advance!

**Comment by drhexgit** [comment]
Not only this show. When running on Linux Mint using version 1.9.7:

>svtplay-dl https://www.svtplay.se/video/16832738/melodifestivalen-2018/melodifestivalen-2018-deltavling-1-deltavling-1
INFO: Selected to download dash, bitrate: 2892
INFO: Outfile: melodifestivalen.2018.avsnitt.1.deltavling.1-c747ccb-svtplay.mp4
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 497, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 209, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 330, in get_one_media
    stream.download()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/fetcher/dash.py", line 157, in download
    self._download2(self.files)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/fetcher/dash.py", line 172, in _download2
    eta = ETA(len(files))
TypeError: object of type 'NoneType' has no len()

**Comment by spaam** [comment]
hmmm  i guess there are some more bugs in the dash playlist parser

**Comment by myowncloudservice** [comment]
It works ok for me
https://www.svtplay.se/video/16832738/melodifestivalen-2018/melodifestivalen-2018-deltavling-1-deltavling-1?start=auto

**Comment by myowncloudservice** [comment]
----------------------------------------------------------------------
INFO: Selected to download hls, bitrate: 1084
INFO: Outfile: melodifestivalen.2018.avsnitt.1.deltavling.1-c747ccb-svtplay.ts
[1679/1679][=======================================================================================================================================================================================] ETA: 0:00:00
INFO: Muxing melodifestivalen.2018.avsnitt.1.deltavling.1-c747ccb-svtplay.ts into melodifestivalen.2018.avsnitt.1.deltavling.1-c747ccb-svtplay.mp4
INFO: Muxing done, removing the old file.
PS C:\Users\myown\Desktop\svtplay-dl_v1>

**Comment by drhexgit** [comment]
The same file worked fine with "-P hls" added to the command line.
