### ISSUE TITLE
Dplay.{dk, no, se} not working anymore

### ISSUE THREAD

**Issue by CiASpook** [spaam/svtplay-dl#777]
v1.9.7 does not work with dplay.no

Example: https://www.dplay.no/videoer/4-stjerners-middag/sesong-10-episode-14

Output:
svtplay-dl.exe https://www.dplay.no/videoer/4-stjerners-middag/sesong-10-episode-14 --remux -S
ERROR: No videos found.
ERROR: Can't find video id

I have tried several others aswell. Same result. It used to work before. Think they change dplay the last couple of days.

**Comment by myowncloudservice** [comment]
They has changed the platform for dplay.se and the movement to the new platform was finished at 30/1

The player has been changed from Adobe Flash to HTML5 

# More information on this site
https://www.dplay.se/artiklar/dplay-ar-relanserat

**Comment by myowncloudservice** [comment]
Hi, 
maybe this script may help to fix the problem that you can not download movies from www.dplay.com etc later with svtplay-dl after they have replaced the platform.then 30/1

There is a script called youtube-dl located at https://github.com/rg3/youtube-dl and with this script you can download movies from www.dplay.se

I tried to download a movie on 3/2 and it worked the great.

**# COMMAND:**   
	.\youtube-dl.exe -F https://www.dplay.se/videos/vagens-hjaltar/vagens-hjaltar-309

**# OUTPUT FILEFORMAT:**
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading webpage
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading token
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading JSON metadata
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading JSON metadata
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading m3u8 information
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading MPD manifest
[info] Available formats for 39807:
format code              extension  resolution note
hls-159992mp4a.40.2-und  mp4        audio only [und]
hls-64000mp4a.40.2-und   mp4        audio only [und]
hls-64                   mp4        audio only   64k , mp4a.40.2
hls-234                  mp4        320x180     234k , avc1.42C015, 25.0fps, video only
hls-464                  mp4        480x270     464k , avc1.42C01F, 25.0fps, video only
hls-862                  mp4        640x360     862k , avc1.4D401E, 25.0fps, video only
hls-1750                 mp4        960x540    1750k , avc1.4D401F, 25.0fps, video only
hls-3338                 mp4        1280x720   3338k , avc1.64001F, 25.0fps, video only
hls-6530                 mp4        1920x1080  6530k , avc1.640029, 25.0fps, video only (best)


**# COMMAND:**   
	.\youtube-dl.exe -f hls-862 https://www.dplay.se/videos/vagens-hjaltar/vagens-hjaltar-309

**# OUTPUT DOWNLOAD:**
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading webpage
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading token
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading JSON metadata
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading JSON metadata
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading MPD manifest
[DPlay] vagens-hjaltar/vagens-hjaltar-309: Downloading m3u8 information
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 252
[download] Destination: Ett lastbilsdäck har exploderat-39807.mp4
[download] 100% of 252.48MiB in 01:30

**Comment by MR-2** [comment]
https://www.dplay.se/videos/ullared/ullared-902
https://disco-api.dplay.se/content/videos/ullared/ullared-902
--> "id" : "**38641**"
https://disco-api.dplay.se/playback/videoPlaybackInfo/38641

**Comment by Sopor-** [comment]
@spaam So it is not possible to download `ts` files anymore?
Now when all hls files are remuxed is it possible to add a noremux switch or there is no use of it? I download my files to a slow USB2 device so remux will take at least 30 minutes. That is why i ask.

**Comment by spaam** [comment]
@Sopor- the issue here is that the we call the files .m4a and .mp4 ( which is wrong and we should fix that..) but its .ts files. audio and video is in separate files now in the new dplay page, so we need to merge them into .ts.
