### ISSUE TITLE
Dplay.se - ERROR: No videos found.

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#784]
When i try to download i get ERROR: No videos found. Here is an example but i get the same result on other programs too.
```
svtplay-dl -P hls https://www.dplay.se/videos/sofias-anglar/sofias-anglar-1001
ERROR: No videos found.
ERROR: Can't find video id
```

**Comment by spaam** [comment]
we have a ticket #777  for this already. closing this.

**Comment by Sopor-** [comment]
That was for .no, this was .se :)

**Comment by spaam** [comment]
yes, but they are more or less the same :)
