### ISSUE TITLE
#777 Workaround until svtplay-dl is updated (use youtube-dl)

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#788]
**Related information** 
https://github.com/spaam/svtplay-dl/issues/777

You can use **youtube-dl** until the issue with www.dplay.se is fixed in **svtplay-dl**
Maybe someone good **python** developer can fix the issue with www.dplay.se in **svtplay-dl** by looking in the source code for **youtube-dl** who is also developed in **python**

**Website for youtube-dl**
https://rg3.github.io/youtube-dl/

**youtube-dl on github (source code)**
https://github.com/rg3/youtube-dl/

---

I try to download from www.dplay.se with **youtube-dl** and it works fine!

**Show Quailty Format** = `-F`
`.\youtube-dl.exe -F https://www.dplay.se/videos/sofias-anglar/sofias-anglar-100`

**Output Quailty Format**
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading webpage
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading token
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading JSON metadata
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading JSON metadata
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading m3u8 information
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading MPD manifest
[info] Available formats for 40158:
format code              extension  resolution note
hls-159992mp4a.40.2-und  mp4        audio only [und]
hls-64000mp4a.40.2-und   mp4        audio only [und]
hls-64                   mp4        audio only   64k , mp4a.40.2
hls-234                  mp4        320x180     234k , avc1.42C015, 25.0fps, video only
hls-463                  mp4        480x270     463k , avc1.42C01F, 25.0fps, video only
hls-859                  mp4        640x360     859k , avc1.4D401E, 25.0fps, video only
hls-1743                 mp4        960x540    1743k , avc1.4D401F, 25.0fps, video only
hls-3328                 mp4        1280x720   3328k , avc1.64001F, 25.0fps, video only
hls-6508                 mp4        1920x1080  6508k , avc1.640029, 25.0fps, video only (best)

**Download movie with 1280x720 resolution and with audio  64k , mp4a.40.2** = `-f`
`.\youtube-dl.exe -f hls-3328+hls-64 https://www.dplay.se/videos/sofias-anglar/sofias-anglar-100`

**Output Downloading**
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading webpage
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading token
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading JSON metadata
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading JSON metadata
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading m3u8 information
[DPlay] sofias-anglar/sofias-anglar-1001: Downloading MPD manifest
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 251
[download] Destination: Dödsbudet kom som en chock-40158.fhls-3328.mp4
[download]   1.8% of ~1002.95MiB at  5.26MiB/s ETA 04:08

**Comment by spaam** [comment]
this is not helping fixing the issue.

**Comment by Sopor-** [comment]
No subtitles with youtube-dl and i wondering if @spaam will fix it...but i cross my fingers that he do :)
