### ISSUE TITLE
HLS/TS stream contains garbage

### ISSUE THREAD

**Issue by drhexgit** [spaam/svtplay-dl#794]
Using version 1.9.7 from Linux mint, there are problems with this URL:  https://www.svtplay.se/video/16908882/melodifestivalen-2018/melodifestivalen-2018-deltavling-2-deltavling-2
Downloading with DASH crashes the program (see issue #775 ) and with HLS a file of reasonable size is downloaded, but cannot be played with e.g. mplayer or vlc  (last week's episode played fine).
It is possible to stream the same file to the chromium browser though.

**Comment by dalgr** [comment]
Try downloading HLS with option `--remux`

**Comment by drhexgit** [comment]
Thank you. Confirming that  **-P hls --remux**  made it work.  Strange that one would need different setting for the next episode of the same series!

**Comment by ijbh** [comment]
How do I fix this if I'm using svtplay-dl on Mac using Terminal? Is there a new update coming to Brew soon? :)
