### ISSUE TITLE
Windows Defender keeps deleting svtplay-dl.exe v1.9.7...

### ISSUE THREAD

**Issue by gorillakilla** [spaam/svtplay-dl#798]
In the last few days, I've repeatedly restored svtplay-dl.exe after Windows Defender deletes it and refuses to let me make an exception or anything like it. The virus it detect varies by the day.

Today, it was: Trojan:Win32/Tiggre!plock
Yesterday, it was: Trojan:Win32/Bitrep.A

So... even if these are false positives, I don't know what to do since it keeps deleting the EXE over and over.

**Comment by spaam** [comment]
When did you update your windows defender virus definition?  this is happening because we use a thing called pyinstaller to create the .exe file.

**Comment by spaam** [comment]
another user had the same issue and that person create a special folder where he put the .exe file and tell the antivirus to exclude it.  https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus

**Comment by gorillakilla** [comment]
I've never updated the program. I assume it does that all on its own.

**Comment by Sopor-** [comment]
There are still 14 out of 67 that detect 1.9.7 as a [virus](https://www.virustotal.com/#/file/97ced6e4614f9ccbe838001d002270a5e55944384d16edba8cc4afb7289efc4a/detection) and Microsoft seems to not be one of them...

**Comment by Sopor-** [comment]
@gorillakilla do you mean Defender in Windows 8.1/10? Defender in Windows 7 is not an antivirus program and i don't even know if MS is updating it...

**Comment by gorillakilla** [comment]
I have Windows 10. It says "Windows Defender".

**Comment by Sopor-** [comment]
Latest Defender update should be from today and it won't detect any virus in my `svtplay-dl.exe`. Search and open Defender and see if you have the latest threat definition version [1.261.1097.0](https://www.microsoft.com/en-us/wdsi/definitions).

**Comment by gorillakilla** [comment]
It says it's up to date, Sopor-.
