### ISSUE TITLE
viafree -A

### ISSUE THREAD

**Issue by agent666** [spaam/svtplay-dl#805]
-A is not working on viafree for me from updated master

**Comment by spaam** [comment]
this is fixed in master now

**Comment by yabbah** [comment]
Not work for me with version 2.1. Seems that it dont find any video, even if the videos is under the same path it seems?

`svtplay-dl -v -A https://www.viafree.se/program/humor/blasningen/sasong-1

DEBUG [1551203313.0111675] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1551203313.015438] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: viaplay
DEBUG [1551203313.0169137] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.viafree.se/program/humor/blasningen/sasong-1'
DEBUG [1551203313.0198069] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se
DEBUG [1551203313.4593718] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/humor/blasningen/sasong-1 HTTP/1.1" 200 None
`
