### ISSUE TITLE
Issue with DPlay.se

### ISSUE THREAD

**Issue by ecsjjgg** [spaam/svtplay-dl#806]
Hi, I can't download the series 'Wahlgrens Värld'...

The output is as follows:

D:\TV>svtplay-dl https://www.dplay.se/videos/wahlgrens-varld/wahlgrens-varld-301
ERROR: No videos found.
ERROR: Can't find video id

Please help me!

This program works perfectly for downloading from tv4play.se and svtplay.se, but not (anymore) on dplay.se!

**Comment by agent666** [comment]
Same as #777

**Comment by spaam** [comment]
What @agent666 said. Thanks for the bug report  :)
