### ISSUE TITLE
WARNING: --all-episodes not implemented for this service

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#81]
I was trying to download all episode from a program on TV3 but i got this message: "WARNING: --all-episodes not implemented for this service". What play sites can i use this feature on and download all episode? Do you have a list of working sites or is it only on SVTPlay i can use it?

**Comment by Sopor-** [comment]
All programs on Kanal 5 have a "Hela avsnitt" button. It must be possible to get all episodes from this kind of link: http://www.kanal5play.se/program/957932846/sasong/1

**Comment by spaam** [comment]
@Sopor- should be possible.

**Comment by Sopor-** [comment]
I hope you will find a way to solve it. Now i have to manually check each program for new episodes instead of doing it with a script :smile:
It's not that hard, really. It's only a little annoying because all the other Swedish channels can handle the -A except for Kanal 5.

**Comment by Sopor-** [comment]
You manage to fix this, great! :smile: 
I will test it soon!

**Comment by spaam** [comment]
this should had happen last year.. :(
