### ISSUE TITLE
Dplay.se - how to download only one season?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#817]
I have now tested the new master `1.9.7-41-g6d3c57a` and when using -A it will download every episode and that is not wrong, but how to download only one season? Do i really need to use the `--exclude=` to exclude from season 01 to season 09 when i only want to download season 10?
Could you add `--include=` switch so it is possible to download only selected seasons or maybe you have a better idea?
I have used the `--all-last=2` before but the sort order on Dplay seems to be from lowest to highest :(

**Comment by Sopor-** [comment]
Btw, `--exclude=` doesn't seems to have any affect :(

**Comment by spaam** [comment]
Yep i forgot to fix that. :)

-- 
Johan Andersson

**Comment by Sopor-** [comment]
I noticed that if i open one of the episodes it will only show episodes from that season. Open this [url](https://www.dplay.se/videos/ullared/ullared-904) and you will see

**Comment by spaam** [comment]
im closing this. i saw that we already have one ticket from you about this issue #739 :D
