### ISSUE TITLE
dplay.no not working anymore.

### ISSUE THREAD

**Issue by jaarsa** [spaam/svtplay-dl#823]
In december 2017 svtplay-dl was working with the dplay.no site, but not anymore.

I get "ERROR: Can't find video id" on all the shows, including the free ones.
I must admit, that I can't find anything saying that dplay.no is supported by svtplay-dl. (only dplay.se)
Is this something that can be easily fixed?

Thx for a great program btw...... so far. :)

**Comment by spaam** [comment]
what version are you using?

**Comment by spaam** [comment]
i just released 1.9.8 and check if that version is working

**Comment by jaarsa** [comment]
Latest version for windows. :)

**Comment by jaarsa** [comment]
Downloaded today.

**Comment by jaarsa** [comment]
1.9.7 is the only one available on the website.

**Comment by jaarsa** [comment]
With 1.9.8 i get the following error:
ERROR: No videos found.
ERROR: Cant find any videos on this url

**Comment by spaam** [comment]
what url are you using ?

**Comment by jaarsa** [comment]
svtplay-dl -S https://www.dplay.no/videoer/neste-sommer/sesong-5-episode-1

**Comment by spaam** [comment]
bah. i found the issue.  it say `videos` in the api for..  but for the path is `videoer` for .dk and .no but for .se it say `videos` almost the same for the english word..  i was hoping they used the english word for the api

**Comment by spaam** [comment]
1.9.9 have a fix for this. :)

**Comment by jaarsa** [comment]
Thx alot, this is just fantastic.
