### ISSUE TITLE
Problem with Dplay

### ISSUE THREAD

**Issue by Whifi** [spaam/svtplay-dl#825]
When i try to download from dplay.se with 1.9.9 i get this message

svtplay-dl -S -o c:\svtdl\Inspelat\ https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-3

<RequestsCookieJar[]>
INFO: Merge audio and video into c:\svtdl\Inspelat\sommaren-med-slakten.s01e03.avsnitt.3-2279-dplay.mp4
ERROR: Something went wrong: Conversion failed!

**Comment by larsamannen** [comment]
Something with the AAC bitstream:
`INFO: Merge audio and video into sommaren-med-slakten.s02e01.avsnitt.1-41711-dplay.mp4
ERROR: Something went wrong: ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.29)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --enable-videotoolbox --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mpegts, from 'sommaren-med-slakten.s02e01.avsnitt.1-41711-dplay.mp4':
  Duration: 00:22:10.04, start: 0.080000, bitrate: 6549 kb/s
  Program 1 
    Stream #0:0[0x21]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
Input #1, mpegts, from 'sommaren-med-slakten.s02e01.avsnitt.1-41711-dplay.m4a':
  Duration: 00:22:09.94, start: 0.000000, bitrate: 171 kb/s
  Program 1 
    Stream #1:0[0x22]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 159 kb/s
[mp4 @ 0x7fa42802e600] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x7fa42802e600] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'sommaren-med-slakten.s02e01.avsnitt.1-41711-dplay.mp4.temp':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 159 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x7fa42802e600] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
frame=    4 fps=0.0 q=-1.0 Lsize=     385kB time=00:00:00.04 bitrate=78809.1kbits/s    
video:384kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.116842%
Conversion failed!
`

**Comment by spaam** [comment]
interesting  🤔

**Comment by spaam** [comment]
i guess we need to change some order to fix this.
