### ISSUE TITLE
D-Play - Can't find video id

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#828]
dplay.se does not show the actual video id anymore just like this for every episode ex: " https://www.dplay.se/program/wahlgrens-varld" and that is when watching S03E01 as an example!

Ex: 
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.dplay.se/program/wahlgrens-varld
ERROR: No videos found.
ERROR: Can't find video id

What can be done to locate the actual video id string?

Regards

**Comment by spaam** [comment]
you need click on the link for the episode and copy link..  so you get a link that looks like this `https://www.dplay.se/videos/wahlgrens-varld/wahlgrens-varld-302`

**Comment by MaistroX** [comment]
THX! :)

**Comment by spaam** [comment]
closing this ticket  :)
