### ISSUE TITLE
On viafree we download the wrong video. 

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#829]
could be only this one, but I dought it.
Are you the one - Sverige
Säsong 1Avsnitt 1
Ex: https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-1
"
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-1
INFO: Selected to download hls, bitrate: 2789
INFO: Outfile: I:\svtplay-dl\are-you-the-one-studion.s01e01-922151-viafree.ts
[66/66][======================================================================================================================================================================================================================================================================================================================================================] ETA: 0:00:00
INFO: Muxing I:\svtplay-dl\are-you-the-one-studion.s01e01-922151-viafree.ts into I:\svtplay-dl\are-you-the-one-studion.s01e01-922151-viafree.mp4
INFO: Muxing done, removing the old file.
"

It plays S01E01 but dont DL it, something else come down "are-you-the-one-studion.s01e01-922151-viafree" some studio thing with a runtime of 10:55 , NOT S01E01 as it should be, any suggestions on this?

Sry, for being enoing! :)

**Comment by spaam** [comment]
sounds like a real bug. we downloaded the "studion" video instead of the real one :D

**Comment by MaistroX** [comment]
OR is it really a bug, maby a genius move from viafree.se to actually get rid of downloaders, as it plays the correct episode!? 😱
