### ISSUE TITLE
https://www.viafree.se again, whats going on there?

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#834]
Tryed svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-3
and get: 
"
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-3
ERROR: No videos found.
ERROR: Can't find video file for: https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-3
"

And that´s the only link that I can get, please help!

**Comment by myowncloudservice** [comment]
I think they have switched to the same platform as dplay.se

I try download from viafree.se with **youtube-dl**(and It worked ok

**Comment by MaistroX** [comment]
Yes, youtube-dl works, but it cant DL subtitles from ex:  https://www.viafree.se ! :(

I hope svtplay-dl can be fixed so it works with https://www.viafree.se again.

**Comment by myowncloudservice** [comment]
https://www.viafree.se/program/reality/unga-mammor/sasong-3/avsnitt-8

In the link above, I found this **video_id**

#Video_Id
**916809**

# Download Info about this link
http://playapi.mtgx.tv/v3/videos/916809

# Streaming info about this link
http://playapi.mtgx.tv/v3/videos/stream/916809

**Comment by MaistroX** [comment]
Maby, but in this case it's regarding https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-3
And HOW to get the #Video_Id on that?

**Comment by myowncloudservice** [comment]
http://playapi.mtgx.tv/v3/videos/922489

http://playapi.mtgx.tv/v3/videos/stream/922489

**Comment by myowncloudservice** [comment]
Hi, I found a worktrue until a new version of **svtplay-dl** will be released

If you get the **Video_ID** from **youtube-dl**
`youtube-dl.exe --get-id https://www.viafree.se/program/reality/are-you-the-on e-sverige/sasong-1/avsnitt-3`

Copy the **Video_ID** and Insert It **%Video_ID%** after URL: https://www.viafree.se/program/reality/are-you-the-on e-sverige/sasong-1/%Video_ID%

like this, and It will work OK to download with svtplay-dl v.1.9.9:
https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/922489

**Comment by MaistroX** [comment]
Strange, all I get is ->
C:\youtube-dl>youtube-dl.exe --get-id https://www.viafree.se/program/reality/are-you-the-on e-sverige/sasong-1/avsnitt-3
WARNING: [Viafree] are-you-the-on: Failed to parse JSON Expecting ',' delimiter: line 1 column 19364 (char 19363)
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

How to I get what you get

**Comment by MaistroX** [comment]
NOW it worked, THX! :)

"
C:\youtube-dl>youtube-dl.exe --get-id https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avsnitt-3
WARNING: [Viafree] avsnitt-3: Failed to parse JSON Expecting ',' delimiter: line 1 column 19492 (char 19491)
922489
"

**Comment by myowncloudservice** [comment]
Your URL Is´t correct

**Correct URL**
https://www.viafree.se/program/reality/are-you-the-**one**-sverige/sasong-1/avsnitt-3

**Wrong, Your URL**
https://www.viafree.se/program/reality/are-you-the-*on e*-sverige/sasong-1/avsnitt-3

**Comment by myowncloudservice** [comment]
Until the bug/issue is fixed in **svtplay-dl v.1.9.9** you can use this workaround

** This workaround is only for viafree.se site

**Comment by myowncloudservice** [comment]
Hi,

I try download from viafree.se now with svtplay-dl and It worked again without using the workaround

PS C:\Users\myown\Desktop\svtplay-dl_v1> .\svtplay-dl.exe -q 100 -Q 1000 -P hls https://www.viafree.se/program/reality/are-you-the-one-sverige/sasong-1/avs
nitt-3 --force
INFO: Selected to download hls, bitrate: 899
INFO: Outfile: are-you-the-one-studion.s01e03-922798-viafree.ts
[013/178][========...........................................................................................................] ETA: 0:00:58

very strange??

**Comment by myowncloudservice** [comment]
This issue can now be closed by #spaam
