### ISSUE TITLE
Wrong/old version via APT?

### ISSUE THREAD

**Issue by 24hourbullshit** [spaam/svtplay-dl#838]
Running Ubuntu 16.04.4, installed svtplay-dl via the repo yesterday, but I only get version 1.6, is the repo not updated or is it something else?

**Comment by spaam** [comment]
what version apt repo? if its ubuntus own. you will get a old verison . use this https://apt.svtplay-dl.se/ if you want a more up to date version.

**Comment by 24hourbullshit** [comment]
Ohh sorry, forgot to say, but yes I've added https://apt.svtplay-dl.se/ but still version just says 1.6

**Comment by spaam** [comment]
did you do an `apt-get update`  and `apt-get upgrade` or `apt-get install svtplay-dl` ?

**Comment by 24hourbullshit** [comment]
First update then install!

Tried to upgrade also, but it can't find any newer version.
