### ISSUE TITLE
Feature request:     Change output filename by parameters

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#844]
Hi, 

I wish it was possible to change the name of a file automatically by setting parameters when downloading file.

**Parameters**
Series = $Series
Title = $Title
Season = $Season
Episode = $Episode
Space1(.) = $Space1
Space1(_) = $Space2
Space3(-) = $Space3

**Example:**
svtplay-dl.exe -o $Series $Space1 $Title .mp4

by info from **JSON**

**Comment by spaam** [comment]
we talked a little bit about this on IRC and we have some ideas to add it to a config file #328 for 2.0

**Comment by myowncloudservice** [comment]
OK, great!
