### ISSUE TITLE
Viafree, No videos found problem

### ISSUE THREAD

**Issue by xpkt1** [spaam/svtplay-dl#845]
I'm getting this with version 1.9.9.  
ERROR: No videos found.
ERROR: Can't find video file for: https://www.viafree.se/program/drama/advokaten
/sasong-1/avsnitt-2

**Comment by myowncloudservice** [comment]
I think it is the same issue as #834 and this item `https://www.viafree.se/program/drama/advokaten/sasong-1/avsnitt-2` is marked in the HTML source **Can't play this because the video is geoblocked.**

I think viafree.se has accidentally put geo-blocking on this series.

**Comment by xpkt1** [comment]
It´s not just that series, it´s everything on viafree. I can play it on viafree but I can´t download it.

**Comment by Sebbe** [comment]
Same happen on .no

https://www.viafree.no/programmer/underholdning/camp-kulinaris/sesong-1/episode-5

**Comment by spaam** [comment]
i have a fix for this and will commit it and release a new version later today :D

**Comment by Sopor-** [comment]
With -A i get this:
```
$ svtplay-dl -A https://www.viafree.se/program/drama/advokaten --verbose
DEBUG [1520348865.29] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_media: version: 1.9.9-9-g8b3a5da
DEBUG [1520348865.3] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.viafree.se/program/drama/advokaten'
```

**Comment by Sopor-** [comment]
Is this fixed @spaam ? I'm still getting the same error and i'm running 1.9.10.

**Comment by xpkt1** [comment]
I´m getting: 
ERROR: You need to install pycrypto to download encrypted HLS streams. Don´t really know what to do.
