### ISSUE TITLE
Nickelodeon Doesn't Work

### ISSUE THREAD

**Issue by Anonyyyyyyym** [spaam/svtplay-dl#852]
You can't download from Nickelodeon anymore, why?

**Comment by spaam** [comment]
What version are using? URL? 

-- 
Johan Andersson

**Comment by Anonyyyyyyym** [comment]
What do you mean with URL.

Using the latest version of SVTDL

**Comment by Anonyyyyyyym** [comment]
http://www.nickelodeon.se/fanboy-chum-chum/videor/magiskt-mote-en-nasvis-ide/

**Comment by dalgr** [comment]
Works with 1.9.11

**Comment by evildemons** [comment]
@spaam 
Does not work, is it something you can fix when you have time?

http://www.nickelodeon.se/icarly/**videor**/jag-kanske-byter-skola/
http://www.nickelodeon.se/svampbob-fyrkant/videor/fe1026f9-47aa-48d6-902e-4556829436ae/

If the link contains "video" then you know that there is no clip.

 ```--all-episodes```
