### ISSUE TITLE
"ERROR: You need to install pycrypto to download encrypted HLS streams"?

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#855]
Can´t find ANY guide that works for Windows 10, step by step! :/

Anyone able to help?

Or maby iplement it direct in svtplay-dl? :)

**Comment by spaam** [comment]
What version are you using? Did it work with previous version?

-- 
Johan Andersson

**Comment by MaistroX** [comment]
Using latest svtplay-dl Latest (currently 1.9.10)

**Comment by spaam** [comment]
Does it work 1.9.9?

-- 
Johan Andersson

**Comment by MaistroX** [comment]
Never needed pycrypto Before , and now all of a sudden it requires it, but I can´t seem to get it to work. :/

**Comment by MaistroX** [comment]
Don´t know what version I had Before, Think maby D-Play changed something, don´t know.

**Comment by xpkt1** [comment]
I got it too on win 7. Never got it before. It´s also on viafree.se

**Comment by spaam** [comment]
Can you share a url where you see this issue? 

-- 
Johan Andersson

**Comment by MaistroX** [comment]
Ex: 
svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.dplay.se/videos/wahlgrens-varld/wahlgrens-varld-304

same thing IF I use Login and Password

**Comment by MaistroX** [comment]
Ex output: 
"
C:\svtplay-dl>svtplay-dl.exe -o I:\svtplay-dl -S -M --remux -f https://www.dplay.se/videos/wahlgrens-varld/wahlgrens-varld-304
INFO: Outfile: I:\svtplay-dl\wahlgrens-varld.s03e04.sex.and.the.city-inspirerad.resa-41988-dplay.srt
ERROR: File (I:\svtplay-dl\wahlgrens-varld.s03e04.sex.and.the.city-inspirerad.resa-41988-dplay.srt) already exists. Use --force-subtitle to overwrite
INFO: Selected to download hls, bitrate: 6544
ERROR: You need to install pycrypto to download encrypted HLS streams
"

**Comment by xpkt1** [comment]
The same on viafree. 
svtplay-dl.exe https://www.viafree.se/program/reality/kockakademin/sasong-1/avsnitt-6
INFO: Selected to download hls, bitrate: 2512
ERROR: You need to install pycrypto to download encrypted HLS streams

**Comment by spaam** [comment]
i see the error. it only happens on windows. becuase of this line https://github.com/spaam/svtplay-dl/commit/8b3a5dacbe36d9afdc9cffa89d332e28675193e6#diff-d270417624a29285ade534bbf701a599R129 .. . pycrypto wants winrandom installed. pycrypto dont depend on  that module in their install script.

**Comment by MaistroX** [comment]
Ok, how to fix it? 😀

**Comment by dalgr** [comment]
@MaistroX 
Update to version 1.9.11
