### ISSUE TITLE
Forgetting to clean up

### ISSUE THREAD

**Issue by pulsatorius** [spaam/svtplay-dl#856]
$ svtplay-dl https://www.svtplay.se/video/17233754/the-sinner/the-sinner-sasong-1-avsnitt-1
INFO: Selected to download dash, bitrate: 3284
INFO: Outfile: the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.m4a
[445/445][========================================] ETA: 0:00:00
INFO: Outfile: the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.mp4
[446/446][========================================] ETA: 0:00:00
INFO: Merge audio and video into the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.mp4
$ ls -hl
totalt 1,8G
-rw-rw-r-- 1 patrick patrick  31M mar  9 18:16 the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.m4a
-rw-rw-r-- 1 patrick patrick 861M mar  9 18:25 the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.mp4
-rw-rw-r-- 1 patrick patrick 891M mar  9 18:25 the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.mp4.temp
$ svtplay-dl --version
1.9.10
$

The relevant file is the.sinner.s01e01.avsnitt.1-aa99c5a-svtplay.mp4.temp.

**Comment by olof** [comment]
Yes, I noticed this as well. I think this is simply a typo, where the error case got inverted. Opening a pull request correcting this now.
