### ISSUE TITLE
svt play rename file issue

### ISSUE THREAD

**Issue by manderss99** [spaam/svtplay-dl#860]
svtplay-dl -silent-semi -A --all-last=1 https://www.svtplay.se/video/17253110/svenska-nyheter

svtplay-dl say it complete successfully however there are three files created: *.mp4, *.mp4.temp and *.m4a.

the *.mp4 file contains no audio.
if I delete *.mp4 and *.m4a and manually renames *.mp4.temp to *.mp4, the file plays correctly.

using latest svtplay-dl from homebrew on mac

**Comment by MR-2** [comment]
#856

**Comment by manderss99** [comment]
fixed in git repository, tested successfully.
closing.
