### ISSUE TITLE
I can't load the site svtplay-dl.se!

### ISSUE THREAD

**Issue by ecsjjgg** [spaam/svtplay-dl#870]
I can't load the website, I have tried both chrome and firefox, but nothing works for me!

**Comment by spaam** [comment]
Hmm something got screwed up from yesterday when i made some changes. hopefully it will get fixed in some hours or next morning.

**Comment by myowncloudservice** [comment]
Ok, greate info!

**Comment by myowncloudservice** [comment]
'https://svtplay-dl.se/sites/'works again, and this issue can now be closed by #spaam or #escjigg

**Comment by ecsjjgg** [comment]
It works again, so I'm closing this issue
