### ISSUE TITLE
When Downloading from Cmore, I suddenly get Error:Geoblocked

### ISSUE THREAD

**Issue by ecsjjgg** [spaam/svtplay-dl#881]
I am trying to download the serie Sjölyckan E03, I am using the command-line: 

svtplay-dl --cmore-operator Telia -u xxx@xxx.se -p xxxxxxxxx-S https://www.cmore.se/serie/106076-sjolyckan/sasong-1/episod-3/3954761-sjolyckan

This results in 
ERROR: No videos found.
ERROR: This video is geoblocked

It used to work last week, then I could download E01 and E02

BTW, I am using Google DNS (8.8.8.8), but I reverted this to Telias DNS when I got this error, but it didn't help, even after a ipconfig /flushdns!

So, this must be something else, or the fact that Cmore has changed something on their side, because now I can't even Download E01 anymore!!!

Also I get a SSL error when I try to access https://svtplay-dl.se

Error 526 Ray ID: 40b1ced8f85a75fa • 2018-04-13 23:45:43 UTC
Invalid SSL certificate

Edit: Webpage works now!

...And I am using the latest version, v19.11

**Comment by ecsjjgg** [comment]
I just wonder if this is due to DRM or if it is something else....

**Comment by frepe360** [comment]
I am getting this as well. Did you ever solve this?

**Comment by ecsjjgg** [comment]
No, I didn't solve it... It used to work for E01 and E02, but it doesn't work anymore :-(

**Comment by granbom** [comment]
Since TV4 owns Cmore, and TV4 doesn't work either, maybe it's related? They both did tweaks etc in their APIs?

**Comment by ecsjjgg** [comment]
Yes I have solved this problem, by using m3u8x.exe... Then I can download everything on tv4play.se (and the tv4 section on cmore.se)

**Comment by frepe360** [comment]
What is "m3u8x.exe"? Where did you find it? How did you use it?

**Comment by ecsjjgg** [comment]
https://sourceforge.net/projects/m3u8x/

Just google it for tutorials
