### ISSUE TITLE
viafree.se - ERROR: No videos found

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#888]
It seems that all viafree videos now show the same error message:
ERROR: No videos found.
ERROR: Can't find video file for:

svtplay-dl 1.9.11-5-g8b25a60

**Comment by ecsjjgg** [comment]
I get the same error, when trying for example SVTPlay-dl  -S  --all-subtitles https://www.viafree.se/program/reality/parneviks/sasong-4/avsnitt-7

**Comment by wahlterh** [comment]
I get the same error on viafree..... (svtplay-dl 1.9.11)
