### ISSUE TITLE
ImportError: No module named 'yaml'

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#898]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ImportError: No module named 'yaml'
```
svtplay-dl latest master

**Comment by spaam** [comment]
this is not a issue.  we added two new deps pycryptodome and pyyaml. pycrypto is not needed anymore.

**Comment by Sopor-** [comment]
So how do i fix this ?

**Comment by Sopor-** [comment]
After installing yaml i now get `ImportError: No module named 'requests'`

**Comment by spaam** [comment]
it depends on your dist.  in debian/ubuntu its named `python3-pycryptodome` and `python3-yaml` .if not `pip3 install pyyaml pycryptodome`

**Comment by spaam** [comment]
what did you do?  that error is complaining about `setuptools` , `apt-get install -y python3-setuptools`

**Comment by Sopor-** [comment]
Yes, when i run your `pip3 install pyyaml pycryptodome` i got that message about setuptools.

**Comment by Sopor-** [comment]
```
$ svtplay-dl --version
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 10, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 7, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py", line 10, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py", line 4, in <module>
ImportError: No module named 'requests'
```

**Comment by Sopor-** [comment]
And now something is messed up with pip3. I saw something about it that version 10.x was not working as it should.

**Comment by spaam** [comment]
did you run the `apt-get install -y python3-setuptools`  and maybe add `python3-pip`  to the apt-get command.

**Comment by Sopor-** [comment]
I uninstalled pip and pip3 and installed it again and now it seems to run something
````
$ sudo pip install pyyaml pycryptodome
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (3.12)
Collecting pycryptodome
  Using cached https://files.pythonhosted.org/packages/f9/72/63fc67bf43286a0fe6a377adc68cec30dcb02b862b10d667788bde112741/pycryptodome-3.6.1.tar.gz
Building wheels for collected packages: pycryptodome
  Running setup.py bdist_wheel for pycryptodome ... done
  Stored in directory: /root/.cache/pip/wheels/19/1f/54/66439c5fbf6dbf9a8b5ab56244981a63a3488c31c33829aa84
Successfully built pycryptodome
Installing collected packages: pycryptodome
Successfully installed pycryptodome-3.6.1
```
`python3-setuptools is already the newest version (33.1.1-1)`

**Comment by Sopor-** [comment]
Why is svtplay-dl complaining about: `ImportError: No module named 'requests'` ?

**Comment by spaam** [comment]
do you have requests installed?

**Comment by spaam** [comment]
what does `python3 -c "import requests"` say?

**Comment by Sopor-** [comment]
But requests must have been there before, or not? It is the same computer.

Now it is working. It was the requests:
svtplay-dl 1.9.11-95-g72af4ff

**Comment by Sopor-** [comment]
Thanks @spaam for your help ...

**Comment by spaam** [comment]
did you fix it ? :)   the only different is that we are using python3 now by default .

**Comment by Sopor-** [comment]
pip is now pip3 so when i run pip3 i get this `No such file or directory` and when i run pip i get this: `pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)`

Yes, it is working!

**Comment by crapmaster** [comment]
I have tried all above suggestions but cannot get the setup to work. Running on Linux Mint, i.e. Ubuntu-based.

Any ideas on how to resolve this?

`$ sudo -H python setup.py  install

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import svtplay_dl
  File "/home/petjan/Projects/github/svtplay-dl/lib/svtplay_dl/__init__.py", line 10, in <module>
    from svtplay_dl.utils.getmedia import get_media, get_multiple_media
  File "/home/petjan/Projects/github/svtplay-dl/lib/svtplay_dl/utils/getmedia.py", line 7, in <module>
    from svtplay_dl.service import service_handler, Generic
  File "/home/petjan/Projects/github/svtplay-dl/lib/svtplay_dl/service/__init__.py", line 7, in <module>
    from urllib.parse import urlparse
`

**Comment by spaam** [comment]
@crapmaster it seems like you are using python2..   try using `python3` instead of `python` when you want to install it :)

**Comment by spaam** [comment]
next version going to be `2.0` and it will be python3 only :)

**Comment by crapmaster** [comment]
@spaam Great. Well of course! python3 (plus installing some missing dependencies) solved the problem.

2.0 gonna be great! :-)
Any estimate on when it's comming?
