### ISSUE TITLE
TV4Play - new name?

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#901]
new name: `biggest.loser.s08e13.-.starkare.tillsammans.del.13-3964438-tv4play.ts`
old name: `biggest.loser.s08e12-starkare.tillsammans.del.12-3961881-tv4play.mp4`

Some extra dots have been added after episode number.
Should it really be ts?

**Comment by Sopor-** [comment]
It seems that i now can play the ts extension in Kodi. You don't remux it to mp4 anymore?

**Comment by spaam** [comment]
@Sopor-, i have fixed the `.-.` thing. but its not commited.  the file extention was a bit wrong before.  as i have written before. we had a `mp4` file extention when it was a `ts` file

**Comment by spaam** [comment]
oh im wrong its commited and pushed 7a8b4af606dc2bce5737e2b0d19c4f6d50ad2c15

**Comment by Sopor-** [comment]
Should i open a new issue about it?

**Comment by spaam** [comment]
there is _no_ issue with svtplay-dl now. before by mistake we named the .ts file as .mp4. your media player is bad and thought that the file was .mp4 and not .ts. a proper player like mpv or vlc can play the file without any issue. we can have the file named `nötter` and they will play the .ts file without any issue.
