### ISSUE TITLE
DPlay - only download audio (latest master)

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#902]
It will now only download the audio from DPlay
`jakten-pa-storsaljaren.s04e04.finurliga.uppfinningar.for.vardagsproblem-42681-dplay.audio.ts`

**Comment by Sopor-** [comment]
```
$ svtplay-dl -S https://www.dplay.se/videos/jakten-pa-storsaljaren/ullared-jakten-pa-storsaljaren-403
Selected to download hls, bitrate: 6532
INFO: Selected to download hls, bitrate: 6532
INFO: Outfile: jakten-pa-storsaljaren.s04e03.pandivider.spel.och.en.sport-bh.med.forvaring-42679-dplay.audio.ts
[253/253][==============================================================================================================] ETA: 0:00:00
INFO: Outfile: jakten-pa-storsaljaren.s04e03.pandivider.spel.och.en.sport-bh.med.forvaring-42679-dplay.ts
WARNING: File (jakten-pa-storsaljaren.s04e03.pandivider.spel.och.en.sport-bh.med.forvaring-42679-dplay.ts) already exists. Use --force to overwrite
```

**Comment by myowncloudservice** [comment]
The link works fine for me!

....
https://www.dplay.se/videos/jakten-pa-storsaljaren/ullared-jakten-pa-storsaljaren-403
....

**Comment by Sopor-** [comment]
@myowncloudservice Do you run svtplay-dl 1.9.11-112-g08210da (latest master)?

**Comment by MR-2** [comment]
@Sopor- are you running python3? Had same similar issue on one client, went in to the svtplay-dl folder an ran the script with:
`python3 svtplay-dl --verbose https://www.dplay.se/videos/jakten-pa-storsaljaren/ullared-jakten-pa-storsaljaren-403`
And then it worked.

**Comment by myowncloudservice** [comment]
@Sopor

I run the latest version of svtplay-dl för Windows 
Release date: 2018-03-12

**Comment by Sopor-** [comment]
@MR-2 Latest master requires python 3
