### ISSUE TITLE
Viafree - ts files won't play in Kodi (latest master)

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#903]
Now we are back to the same issue #871 that ts files won't play and you need to remux them to mp4.

**Comment by spaam** [comment]
did you try using --remux?

**Comment by Sopor-** [comment]
No i didn't because it wasn't necessary before ...

**Comment by spaam** [comment]
sure. but its a workaround until i fixed the issue :)

**Comment by Sopor-** [comment]
--remux is working :)
