### ISSUE TITLE
No videos found for svtplay when video has specified time left

### ISSUE THREAD

**Issue by lhenriksson** [spaam/svtplay-dl#905]
If a video on svtplay has specified time left before removal it can't be downloaded, only returns  "ERROR: No videos found."

svtplay-dl version 1.9.11

**Comment by spaam** [comment]
do you have an example of a video that have this issue?

**Comment by spaam** [comment]
i cant reproduce this issue. for me i can download the video without any issue. 
```
➜  /tmp svtplay-dl --version
1.9.11
➜  /tmp svtplay-dl https://www.svtplay.se/video/17234250/bast-i-test/bast-i-test-sasong-2-avsnitt-1
INFO: Selected to download dash, bitrate: 3372
INFO: Outfile: bast.i.test.s02e01.claes.malmberg.gastar-8a299ea-svtplay.m4a
[031/587][==.................................................] ETA: 0:00:22^C
➜  /tmp
```

are you using any special flags for something?  🤔

**Comment by lhenriksson** [comment]
Nope, using the same as you. Also tried with `-A -S` and with those flags it downloads subtitles but not the video
```
> svtplay-dl https://www.svtplay.se/video/17234250/bast-i-test/bast-i-test-sasong-2-avsnitt-1
ERROR: No videos found.
```
Python version is 2.7.12
OS Ubuntu 16.04.4 LTS

**Comment by lhenriksson** [comment]
Think i found the problem, using from my server that is in Netherlands, and the program is only watchable in Sweden.
Stupid that i forgot to check that first.

**Comment by spaam** [comment]
ahh. okey i guess we should fix that issue.
you can get around the geoip blocking thing using `svtplay-dl --http-header "X-FORWARDED-FOR=127.0.0.1" url`  replace `127.0.0.1` with an swedish ip :)
