### ISSUE TITLE
Add some more files to gitignore

### ISSUE THREAD

**Issue by spaam** [spaam/svtplay-dl#907]
https://github.com/github/gitignore/blob/master/Global/Windows.gitignore
https://github.com/github/gitignore/blob/master/Global/macOS.gitignore
https://github.com/github/gitignore/blob/master/Python.gitignore
https://github.com/github/gitignore/blob/master/Global/Vim.gitignore
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

these links have some good ones we should add.

**Comment by PierreMesure** [comment]
Hey, you added `/lib` in the .gitignore!
