### ISSUE TITLE
TV4play no sub

### ISSUE THREAD

**Issue by pammis01** [spaam/svtplay-dl#909]
Using -S will not give any subs.

**Comment by agent666** [comment]
And some videos give svtplay-dl crashed

**Comment by Sopor-** [comment]
TV4 now use WebVTT.

**Comment by Pibben** [comment]
Any plans to implement support for TV4 subs again? Are there technical difficulties?

**Comment by spaam** [comment]
@Sopor-  yes and its split into several .m3u8 files too.. :D 
@Pibben  i have something that works-ish . but need to change how we parse subtitles from m3u8 playlists.  hopefully i can fix it tonight :)

**Comment by spaam** [comment]
master have a fix for this. hopefully i will release 2.0 tomorrow or friday.
