### ISSUE TITLE
Viafree doesn't work anymore

### ISSUE THREAD

**Issue by dhofverberg** [spaam/svtplay-dl#921]
It seems like Viafree doesn't work anymore, or at least not the videos I've tried with. Using svtplay-dl version 1.9.11.

Example URL: https://www.viafree.se/program/humor/life-in-pieces/sasong-2/avsnitt-22

Example command line: svtplay-dl -S --raw-subtitles --remux https://www.viafree.se/program/humor/life-in-pieces/sasong-2/avsnitt-22

Output:
ERROR: No videos found.
ERROR: Can't find video file for: https://www.viafree.se/program/humor/life-in-pieces/sasong-2/avsnitt-22

**Comment by stdlogin** [comment]
This issue has been for at least two months now, and It will not be fixed until a new release of svtplay-dl.exe will be compiled.

Use youtube-dl.exe now instead of svtplay-dl.exe, if you don't want to wait!

**Comment by qnorsten** [comment]
You can also use the latest master:) That works fine:) Until Spaam releases version 2.0

**Comment by stdlogin** [comment]
Okay, greate news

**Comment by myowncloudservice** [comment]
@qnorsten 

How did I install the latest master?

On Ubuntu or WIndows?

**Comment by spaam** [comment]
master have a fix for this. hopefully i will release 2.0 tomorrow evening or friday.  :)

**Comment by OldSchool297** [comment]
Does it work? This show up for me. 

Microsoft Windows [Version 6.0.6002]
Copyright (c) 2006 Microsoft Corporation. Med ensamrätt.



C:\>E:\youtube-dl -c -o C:\Ned\24.ts https://www.viafree.se/program/reality/geor
die-shore/sasong-17/avsnitt-3
[Viafree] avsnitt-3: Downloading webpage
WARNING: [Viafree] avsnitt-3: Failed to parse JSON Expecting ',' delimiter: line
 1 column 327 (char 326)
ERROR: Unable to extract video id; please report this issue on https://yt-dl.org
/bug . Make sure you are using the latest version; type  youtube-dl -U  to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete o
utput.
