### ISSUE TITLE
Question:  How to install from the master on ubuntu?

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#922]
Hi,

I wounder how I can install from the master release on ubuntu?

I am very new on ubuntu, and I can´t all the commands on ubuntu.

I have installed svtplay-dl on ubuntu, but this is not the master release.

I hope someone can help me with this!

/Regards
myowncloudservice

**Comment by qnorsten** [comment]
Follow the instruction from https://github.com/spaam/svtplay-dl#from-source
Let me know if you need any more help.

**Comment by myowncloudservice** [comment]
@qnorsten 

I have follow the steps from https://github.com/spaam/svtplay-dl#from-source
but I cant install svtplay-dl.

I have installed python 3.7 on Windows
but I cant run **git clone https://github.com/spaam/svtplay-dl** and not **sudo python3 setup.py install**

**Comment by qnorsten** [comment]
First install git
With sudo apt-get install git
Then cd into the svtplay-dl directory and run python3 setup.py install

**Comment by myowncloudservice** [comment]
@qnorsten 

i got this error when i try to run **python3 setup.py install**

raceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pip' is not defined

**Comment by qnorsten** [comment]
@myowncloudservice  than you need to install pip first 
https://pip.pypa.io/en/stable/installing/ 

just do 
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```

**Comment by stdlogin** [comment]
@qnorsten 

I have installed **pip** but I can't run **python3 setup.py install** only **python setup.py install**
but svtplay-dl doesn't work for me anyway.

I think I wait until a new version of svtplay-dl.exe will be released, nothing is working correctly for me.

My Python3 is installed in this directory:
`C:\Users\myown\AppData\Local\Programs\Python\Python37-32\`
