### ISSUE TITLE
tv.nrk.no broken

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#926]
tv.nrk.no has been redesigned, and downloading programmes and episodes doesn't work anymore.

**Comment by waltherbans** [comment]
Actually, you *can* download films and episodes, but no "newer" episodes (of series) in the new design of the website.
For instance, I've tried downloading "Greyzone" using both the old adress: https://tv.nrk.no/serie/greyzone/sesong/1/episode/1 and the new one: https://tv.nrk.no/serie/greyzone/KOIF22008917/sesong-1/episode-1
The result is the same for both:
`ERROR: No videos found. Can't find video id.`

**Comment by Hertizch** [comment]
I am hoping this will be fixed!

**Comment by psonnosp** [comment]
Any news on this?
Will it be fixed or is NRK abandoned?

**Comment by fiskhandlarn** [comment]
+1

Still seems broken:
```bash
$ svtplay-dl -S https://tv.nrk.no/serie/tine/1985/FTRO00008484
ERROR: No videos found. Can't find video id.
```

**Comment by fiskhandlarn** [comment]
I used this in the meantime: https://github.com/marhoy/nrk-download

**Comment by forthrin** [comment]
Writing my own script was easier (and more fun!) than having to deal with other programmers. Anyone still having a problem with the site can open a new issue -- or write their own extractor :)
