### ISSUE TITLE
Downloading v1.9.11 - Windows says Virus Detected !

### ISSUE THREAD

**Issue by Usudanix** [spaam/svtplay-dl#928]
Tried to download latest svt-dl.exe an Windows says Virus Detected.
ANyone else had this?

Windows Security Center Report:

Trojan:Win32/Spursint.F!cl
Alert level: Severe
Status: Quarantined
Date: 2018-07-12
Recommended action: Remove threat now.
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
Affected items:
file: C:\SVTplay-dl\svtplay-dl.exe
webfile: C:\SVTplay-dl\svtplay-dl.exe|https://svtplay-dl.se/download/latest/svtplay-dl.exe|pid:10172,ProcessStart:131759009567792803

**Comment by spaam** [comment]
yes. quite a few #884 #803  #690 . hopefully it will get fixed when i release 2.0 later today or tomorrow. :)
