### ISSUE TITLE
make it possible to enter more then one url at the same time

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#929]
It would be nice if svtplay-dl did support several download links at the same run. I don't know if it has a name but it would be possible to write:
```
svtplay-dl -S -P hls url1 url2 url3 url4
```

**Comment by spaam** [comment]
this feature was added in #512 and 1.9.11 have this feature :)

**Comment by Sopor-** [comment]
Wow, that was nice :)
