### ISSUE TITLE
Question: OUTPUT folder ({title}, {season_number})

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#940]
is there any way you can get the information about the **title** or **season number** of the video you want to download, then use this information to create an OUTPUT where the video will be stored.

`Example:
C:\users\admin\desktop\{title}\filename of video item.mp4`

`C:\users\admin\desktop\{title}\{season_number}\filename of video item.mp4`

Can you do something in the svtplay-dl.yaml to something like that?

**Comment by qnorsten** [comment]
That is very similar to what I ended up suggesting in this issue https://github.com/spaam/svtplay-dl/issues/915

**Comment by myowncloudservice** [comment]
@qnorsten

Ok
