### ISSUE TITLE
tried to install svtplay-dl from source, failed!

### ISSUE THREAD

**Issue by KGBGit** [spaam/svtplay-dl#942]
Here is what happened, can anyone give a hint to why i don't works?

KGBMacPro:~ ketil$ git clone https://github.com/spaam/svtplay-dl.git
Cloning into 'svtplay-dl'...
remote: Counting objects: 11940, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 11940 (delta 0), reused 4 (delta 0), pack-reused 11934
Receiving objects: 100% (11940/11940), 2.66 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (7400/7400), done.
KGBMacPro:~ ketil$ cd svtplay-dl
KGBMacPro:svtplay-dl ketil$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C lib
for py in svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py; do \
		install -d ".build/${py%/*}"; \
		install $py .build/$py; \
	done
# Add git version info to __version__, seen in --version
sed -i -e 's/^__version__ = \(.*\)$/__version__ = "2.0-1-g8297d66"/' \
		.build/svtplay_dl/__init__.py
find .build/ -exec touch -m -t 198001010000 {} \;
(cd .build && zip -X --quiet svtplay-dl svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py)
(cd .build && zip -X --quiet --junk-paths svtplay-dl svtplay_dl/__main__.py)
echo '#!/usr/bin/env python3' > svtplay-dl
cat .build/svtplay-dl.zip >> svtplay-dl
rm -rf .build
chmod a+x svtplay-dl
mv -f lib/svtplay-dl .
KGBMacPro:svtplay-dl ketil$ sudo make install
Password:
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C lib
for py in svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py; do \
		install -d ".build/${py%/*}"; \
		install $py .build/$py; \
	done
# Add git version info to __version__, seen in --version
sed -i -e 's/^__version__ = \(.*\)$/__version__ = "2.0-1-g8297d66"/' \
		.build/svtplay_dl/__init__.py
find .build/ -exec touch -m -t 198001010000 {} \;
(cd .build && zip -X --quiet svtplay-dl svtplay_dl/*.py svtplay_dl/fetcher/*.py svtplay_dl/postprocess/*.py svtplay_dl/service/*.py svtplay_dl/subtitle/*.py svtplay_dl/utils/*.py)
(cd .build && zip -X --quiet --junk-paths svtplay-dl svtplay_dl/__main__.py)
echo '#!/usr/bin/env python3' > svtplay-dl
cat .build/svtplay-dl.zip >> svtplay-dl
rm -rf .build
chmod a+x svtplay-dl
mv -f lib/svtplay-dl .
install -d /usr/local/bin
install -m 755 svtplay-dl /usr/local/bin
KGBMacPro:svtplay-dl ketil$ cd ~
KGBMacPro:~ ketil$ svtplay-dl --version
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 11, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 7, in <module>
ImportError: No module named 'yaml'
KGBMacPro:~ ketil$

**Comment by MR-2** [comment]
In the error message you're Prompted with it clearly states "ImportError: No module named 'yaml'"
Please read the very detailed Installation Guide and the Requirements stated [Link](
https://github.com/spaam/svtplay-dl#from-source)

**Comment by KGBGit** [comment]
Thank you very much.

Why is ”brew install svtplay-dl” installing svtplay-dl 1.9.11??

Mvh Ketil

**Comment by MR-2** [comment]
Because brew doesn't have the latest version from this repo. Brew is just a package manager and various packages from brew doesn't have to be update date, it's that simple. Brew will sooner or later get the latest version but it has to pass different tests etc.

**Comment by KGBGit** [comment]
Thanks again.
That was a lot to leran, like that.

Mvh Ketil

**Comment by MR-2** [comment]
@KGBGit I would suggest that you close this issue.

**Comment by spaam** [comment]
thanks for answer @MR-2 <3 
closing this :)
