### ISSUE TITLE
How do i disable the config file?

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#957]
If i want to run `svtplay-dl` clean without any options. How do i disable the config file without renaming the file?

**Comment by spaam** [comment]
you cant.

**Comment by Sopor-** [comment]
So even if i for example use -A like this `svtplay-dl -A <URL>` it will not ignore the config file?
When using switches on the command line it should automatically ignore the config file.

**Comment by spaam** [comment]
command line switches override the config. that is what every other command works.

**Comment by Sopor-** [comment]
It seems that if the config file have -S and i use other command line switches it will still use the -S from the config file. IMO that is wrong. If i use any command line switches it should ignore the config file and only use those i use on the command line. I believe that was the intention if i got everything right?

**Comment by spaam** [comment]
yes you are right but the issue is that i dont know if someone use subtitle or not using the command line. sure we can just override everything and make the config file useless

**Comment by Sopor-** [comment]
It would be great if it was possible to ignore the config file instead of renaming the file when i don't want to use it. It will be very complex for the users if only some of the command line switches override and others not. Like i suggested above `--no-config` :)

**Comment by granbom** [comment]
Maybe look into how "presets" could work that I wrote about in #328. Then one preset or a default preset could be to clear anything from config file if used. Like `--preset no-config`.

**Comment by dentarg** [comment]
@Sopor- I don't think it makes sense to not use the config file at all, when you use _any_ command line switch. That's just not how programs usually works.

I haven't tried out `svtplay-dl` with the config file, but couldn't a workaround be to point to an empty file with `--config`?

**Comment by dentarg** [comment]
Oh, with empty config file we crash... a bug IMHO :)

**Comment by Sopor** [comment]
> Maybe look into how "presets" could work that I wrote about in #328. Then one preset or a default preset could be to clear anything from config file if used. Like `--preset no-config`.

It seems that `--config whatever` will work too. If it can't find the file it will ignore the original config file.
