### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by arrbie** [spaam/svtplay-dl#959]
On MacOS 10.13.6, I get the following:

brew install svtplay-dl
==> Installing dependencies for svtplay-dl: openssl, rtmpdump
==> Installing svtplay-dl dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2a.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/openssl/openssl/commit/6281abc796234.diff
######################################################################## 100.0%
Error: SHA256 mismatch

**Comment by dentarg** [comment]
Not sure what happened here, but this doesn't look like a problem with svtplay-dl

Seems like something that can happen with Homebrew: https://github.com/Homebrew/homebrew-core/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22checksum+mismatch%22
