### ISSUE TITLE
Issues for some TV4 videos (HTTP 401 or 404 errors)

### ISSUE THREAD

**Issue by olof** [spaam/svtplay-dl#96]
This was reported in #62:

    $ ./svtplay-dl http://www.tv4.se/snn-news/avsnitt/avsnitt-4-169107
    ERROR: Something wrong with that url
    ERROR: Error code: 404

This is still the case for some videos, either giving 404 or 401:

    $ ./svtplay-dl http://www.tv4play.se/program/cph-kastrup?video_id=2180683
    ERROR: Something wrong with that url
    ERROR: Error code: 401

This works though:
* http://www.tv4play.se/program/humorgalan?video_id=2604398

This can be related to #56.

**Comment by spaam** [comment]
closing this. over a year old
