### ISSUE TITLE
Issue: can't download from Viafree.se

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#960]
Hi,

svtplay-dl v2.0 for Windows will crash everytime I will try to download this links from **viafree.se**

Series:  **ultimate-factories**

**Links**
`
https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972947

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972827

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972551

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972889

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972893

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972892

https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972890
`

**Debug**

`
Version: 2.0
DEBUG [1536173327.1536584] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.0
DEBUG [1536173327.159128] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: viaplay
DEBUG [1536173327.1596305] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972890'
DEBUG [1536173327.1681316] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.viafree.se:443
DEBUG [1536173329.0551388] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.viafree.se:443 "GET /program/dokumentar/ultimate-factories/sasong-1/972890 HTTP/1.1" 200 None
DEBUG [1536173329.3367019] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://playapi.mtgx.tv/v3/videos/972890'
DEBUG [1536173329.3396993] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP conn...
`

**Comment by spaam** [comment]
this is fixed in master.

**Comment by myowncloudservice** [comment]
@Sopor-  The build doesn´t work, It doesn´t work for any other sites either.

**Link**
`.\svtplay-dl.exe --verbose https://www.viafree.se/program/dokumentar/ultimate-factories/sasong-1/972947
`

**Debug/Traceback**
```
Traceback (most recent call last):
  File "C:\Users\Abbe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\Abbe\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 4, in <module>
ModuleNotFoundError: No module named 'svtplay_dl'
```

**Comment by spaam** [comment]
@myowncloudservice on every commit we build a new snapshot. you can try using https://ci.appveyor.com/api/buildjobs/dk9j9hs9pd3nke6m/artifacts/svtplay-dl.zip

**Comment by Sopor-** [comment]
@myowncloudservice I followed the build instructions but it seems that i have forgot something :(
