### ISSUE TITLE
Feature: Download multiple Urls from batch-file

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#967]
# Feature functions

Download multiple `**Urls**` from batch-file
like youtube-dl 

**Options**
`--batch-file`
**CommandLine**
`svtplay-dl.exe -q 100 -Q 1000 --batch-file C:\Users\YourUserName\svtplay-dl\batch-file.txt`

**Example** `batch-file.txt`

**Index, Url**
`[0], https://www.dplay.se/videos/det-som-goms-i-sno/det-som-goms-i-sno-1
[1], https://www.dplay.se/videos/det-som-goms-i-sno/det-som-goms-i-sno-2
[2], https://www.dplay.se/videos/det-som-goms-i-sno/det-som-goms-i-sno-4`

**Comment by spaam** [comment]
why? what is wrong using multiple arguments? 🤔

**Comment by myowncloudservice** [comment]
@spaam 
Hi, can you download multiple URLs in svtplay-dl with arguments?

**Comment by spaam** [comment]
@myowncloudservice yeah. that feature was added a long time ago with the PR #512. try `svtplay-dl url url url url url url`.   i have never seen a use case with batch file so that is why i asked :)

**Comment by myowncloudservice** [comment]
@Sopor- It is exactly what I mean!

@Spaam
I can use svtplay-dl.exe URLs URLs URLs to if It works, I didn't know that you can use this arguements in svtplay-dl to download multiple URLs. Thanks a lot for the tips.



Thanks!
