### ISSUE TITLE
"svtplay-dl crashed" when trying to download Farmen VIP on TV4 Play.

### ISSUE THREAD

**Issue by Ola-Ponny** [spaam/svtplay-dl#972]
svtplay-dl.exe https://www.tv4play.se/program/farmen-vip/3960663
ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

svtplay-dl.exe https://www.tv4play.se/program/farmen-vip/3960663 --verbose
version: 2.0
DEBUG [1537382327.005266] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.0
DEBUG [1537382327.0067935] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1537382327.0067935] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/farmen-vip/3960663'
DEBUG [1537382327.0082984] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1537382327.515874] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/farmen-vip/3960663 HTTP/1.1" 200 11326
DEBUG [1537382327.5183835] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback-api.b17g.net/media/3960663?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
DEBUG [1537382327.5199134] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
DEBUG [1537382327.8326259] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/3960663?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 401 125
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 63, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 56, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 105, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 76, in get
KeyError: 'playbackItem'

svtplay-dl.exe --version
svtplay-dl 2.0

:-(

(Those paths don't exist on my computer, BTW, but I assume it's the developer's...)

**Comment by granbom** [comment]
This URL works for me, but I can see a HTTP 401 (Forbidden) in your log, which could indicate that your IP number is non Swedish.

**Comment by Ola-Ponny** [comment]
Ah. It works after I specified a proxy located in Sweden.

**Comment by Sopor-** [comment]
But svtplay-dl shouldn't crashed because of this...

**Comment by granbom** [comment]
Tekniskt sätt krashade det nog inte, men i errorhanteringen när det inte fungerade står det "crashed". Det är ju i detta fallet tv4 som busar och säger "forbidden" och svtplay-dl säger gick inte.

**Comment by myowncloudservice** [comment]
It works correctly for me to download the Url
`https://www.tv4play.se/program/farmen-vip/3960663`

I have svtplay-dl version: 2.0-6-ga7aa860 for Windows

**Comment by spaam** [comment]
try using `--http-header "X-FORWARDED-FOR=127.0.0.1"`  change 127.0.0.1 to a swedish ip. it works at some places.
