### ISSUE TITLE
TV4 svtplay-dl 2.0

### ISSUE THREAD

**Issue by stefner** [spaam/svtplay-dl#979]
Since 2.0, it seems download from tv4 comes with a default "--remux".
That's fine, but in the resulting mp4 audio/video is out of sync (increasing over play time).

I've tried several videos, and the all have the same problem. Below  is a small example.

PS. Why the duplicated log texts? 
```
C:\python\Lib\site-packages>python svtplay_dl --subtitle --force https://www.tv4play.se/program/idol/11150365
INFO: Selected to download hls, bitrate: 3412
INFO: Outfile: idol.s14e01.idol-revanschen.del.1-11150365-tv4play.audio.ts
[141/141][===================================================================================================================================================================================================] ETA: 0:00:00
INFO: Outfile: idol.s14e01.idol-revanschen.del.1-11150365-tv4play.ts
[141/141][===================================================================================================================================================================================================] ETA: 0:00:00
Merge audio and video into idol.s14e01.idol-revanschen.del.1-11150365-tv4play.ts
INFO: Merge audio and video into idol.s14e01.idol-revanschen.del.1-11150365-tv4play.ts
Merging done, removing old files.
INFO: Merging done, removing old files.
Muxing idol.s14e01.idol-revanschen.del.1-11150365-tv4play.ts into idol.s14e01.idol-revanschen.del.1-11150365-tv4play.mp4
INFO: Muxing idol.s14e01.idol-revanschen.del.1-11150365-tv4play.ts into idol.s14e01.idol-revanschen.del.1-11150365-tv4play.mp4
Muxing done, removing the old file.
INFO: Muxing done, removing the old file.```

**Comment by Sopor-** [comment]
What version of ffmpeg do you have?

**Comment by stefner** [comment]
```
C:\python\Lib\site-packages>ffmpeg
ffmpeg version N-71066-ga2dd2d7 Copyright (c) 2000-2015 the FFmpeg
developers
  built with gcc 4.9.2 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads
--enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r
--enable-gnutls --enable-iconv --enable-libass --enable-libbluray
--enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme
--enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame
--enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg
--enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr
--enable-libspeex --enable-libtheora --enable-libtwolame
--enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
--enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp
--enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid
--enable-lzma --enable-decklink --enable-zlib
  libavutil      54. 20.101 / 54. 20.101
  libavcodec     56. 29.100 / 56. 29.100
  libavformat    56. 26.101 / 56. 26.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 13.101 /  5. 13.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options]
outfile}
```


Den sön 30 sep. 2018 kl 20:28 skrev Sopor <notifications@github.com>:

**Comment by Sopor-** [comment]
I have no idea what `ffmpeg version N-71066-ga2dd2d7` is but the year seems to be old, 2015. To get rid of the out of sync issue you need to run at least version 4.0.

**Comment by stefner** [comment]
Updated ffmpeg, and issuee solved! 
Audio/Video in sync. 

Thanks,
/S

C:\python\Lib\site-packages>ffmpeg -v
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
