### ISSUE TITLE
Question:  https://ci.appveyor.com/api/buildjobs/

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#983]
Hi, 
I wounder if `dk9j9hs9pd3nke6m` is a encrypted hash for **2018-09-05** or is It a api created by appveyor?

I wounder if I can replace `dk9j9hs9pd3nke6m` with something to download the latest build of svtplay-dl.zip from https://ci.appveyor.com/api/buildjobs/**<replace with something?>**/artifacts/svtplay-dl.zip

I got this link from @spaam in the beginning of September and now I am looking for a new version/release if a new one has been build?

**Comment by spaam** [comment]
if you check latest commit at https://github.com/spaam/svtplay-dl/commits/master  you can see this green checkmark . click on that, then on appveyor link.    right now it will go to https://ci.appveyor.com/project/spaam/svtplay-dl/build/1.0.223 page. after that you can click on the aritfact link on the right side.   on that page you can see the svtplay-dl.zip file :) 

i have some plans to upload those to the website. so if you go to like https://svtplay-dl.se/snapshots/  you can find latest builds.

**Comment by myowncloudservice** [comment]
@spaam

Okay, thanks for your help!

**Comment by MaistroX** [comment]
"i have some plans to upload those to the website. so if you go to like https://svtplay-dl.se/snapshots/ you can find latest builds."
Please announce when this will be avalible! :)

**Comment by Sopor-** [comment]
I didn't manage to compile any working version in Windows :(
