### ISSUE TITLE
Tv4play.se - NewConnectionError

### ISSUE THREAD

**Issue by myowncloudservice** [spaam/svtplay-dl#985]
Hi,
I get this error when I try to download the first episodes of **Cirkus Bagge** from tv4play.se

**Link**
`https://www.tv4play.se/program/cirkus-bagge/3971809`

WARNING: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0363BF50>: Failed to establish a new connection: [WinError 10060] Anslutningsförsöket misslyckades eftersom den anslutna datorn inte svarade inom en viss tid eller på grund av att den etablerade anslutningen till värddatorn inte längre fungerar',)': /vod/82a72/vncpep3owom(3971809_ISMUSP).ism/vncpep3owom(3971809_ISMUSP)-textstream_swe=3000-35.webvtt
WARNING: Retrying (Retry(total=4, connect=4, read=5, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x036019B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)': /vod/82a72/vncpep3owom(3971809_ISMUSP).ism/vncpep3owom(3971809_ISMUSP)-textstream_swe=3000-58.webvtt

**Debug**
.DEBUG [1539367530.1796381] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://lbs-usp-hls-vod.cmore.se:443 "GET /vod/82a72/vncpep3owom(3971809_ISMUSP).ism/vncpep3owom(3971809_ISMUSP)-textstream_swe=3000-427.webvtt HTTP/1.1" 302 0
DEBUG [1539367530.1866274] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): cmoreseusphlsvod70.akamaized.net:443
DEBUG [1539367530.286624] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://cmoreseusphlsvod70.akamaized.net:443 "GET /vod/82a72/vncpep3owom(3971809_ISMUSP).ism/vncpep3owom(3971809_ISMUSP)-textstream_swe=3000-427.webvtt HTTP/1.1" 200 145
DEBUG [1539367530.2896175] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/82a72/vncpep3owom(3971809_ISMUSP).ism/vncpep3owom(3971809_ISMUSP)-textstream_swe=3000-428.webvtt'
DEBUG [1539367530.30679] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_reques...

**Comment by Sopor-** [comment]
It is working here :)
```
$ svtplay-dl https://www.tv4play.se/program/cirkus-bagge/3971809
INFO: Outfile: cirkus.bagge.s01e01.cirkus.bagge.del.1-3971809-tv4play.srt
INFO: Selected to download hls, bitrate: 4857
INFO: Outfile: cirkus.bagge.s01e01.cirkus.bagge.del.1-3971809-tv4play.audio.ts
[166/663][===========================...................................................................................] ETA: 0:01:13
```

svtplay-dl 2.0+45.g7ac0b5f

**Comment by myowncloudservice** [comment]
Hmm, Okay I have the latest version of svtplay-dl 2.0-36-g1499a00 from https://ci.appveyor.com/project/spaam/svtplay-dl/build/artifacts I get from @spaam for 5 days ago.

**Comment by spaam** [comment]
feels like the site went down and back up again. i cant reproduce the error 🤔

**Comment by myowncloudservice** [comment]
@spaam 

Okay I will try download the episodes again!
