### ISSUE TITLE
Support for eurosportplayer

### ISSUE THREAD

**Issue by raffam** [spaam/svtplay-dl#989]
Is there a way to support the [eursportplayer](eurosportplayer.com) website?

**Comment by granbom** [comment]
At least before eurosportplayer worked, like during the Olympics in Feb. Has that changed? An account for eurosportplayer is needed though.

**Comment by raffam** [comment]
I can provide the account. The list of supported sites does not include eurosportplayer

**Comment by raffam** [comment]
> D:\Downloads\svtplay-dl>svtplay-dl.exe https://it.eurosportplayer.com/en/event/ax-armani-exchange-milano-cska-moscow-euro-league/a78b0afc-90a2-46de-b83c-a05cd97f2ad8
> ERROR: That site is not supported. Make a ticket or send a message

Although there is an eurosport.py in the scripts

**Comment by raffam** [comment]
I have made some experiments and can confirm that the Eurosport player back-end no longer works. The server return a 406 error on these lines in `eurosport.py`:

```
data = {"grant_type": "urn:mlbam:params:oauth:grant_type:token", "latitude": "0",
                "longitude": "0", "platform": "browser", "token": res.json()["code"]}
        header = {"authorization": "Bearer {}".format(clientapikey)}
        res = self.http.post("https://global-api.svcs.eurosportplayer.com/token", headers=header, data=data)
```

**Comment by raffam** [comment]
I have managed to have cracked it down. My preliminary work is [here](https://github.com/raffam/eurosportplayer-dl).

My main problem now is how to obtain the link to the master m3u8 from the link of the video. Currently you have to use the Chrome DevTools to obtain the link of the master playlist file. For the rest we should be covered

**Comment by spaam** [comment]
@raffam  have you tried adding `it.eurosportplayer.com` to this list https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/eurosport.py#L13 ?

**Comment by raffam** [comment]
Well yes, if you see my comment 2 way up, I have managed to modify the source in order to re-add the Eurosport backend but it didn't work. I assume, maybe, it was disabled because it was old? Anyway I preferred to make my own in order to learn too :)

**Comment by spaam** [comment]
oh. it seems like i forgot to import the file in https://github.com/spaam/svtplay-dl/blob/master/lib/svtplay_dl/service/services.py after i made some changes :(

**Comment by spaam** [comment]
I commited a fix that it will support some more subdomains. it might work now.

**Comment by raffam** [comment]
Hi @spaam ,
thank you for your commit. Here is the error message. 

> raffaele@raffaele-GL753VD:/media/raffaele/DATA/data/programmi/svtplay-dl$ svtplay-dl -u USERNAME -p PASSWORD https://it.eurosportplayer.com/en/event/lietuvos-rytas-unics-kazan/c58b1f18-8852-458a-a642-2da01a165f2a --verbose
> DEBUG [1542137424.9510877] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/getmedia.py/get_media: version: 2.1+9.ga65a322
> DEBUG [1542137424.9516828] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/service/__init__.py/__init__: service: eurosport
> DEBUG [1542137424.9517913] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://it.eurosportplayer.com/en/event/lietuvos-rytas-unics-kazan/c58b1f18-8852-458a-a642-2da01a165f2a'
> DEBUG [1542137424.9536507] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): it.eurosportplayer.com:443
> DEBUG [1542137425.325098] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://it.eurosportplayer.com:443 "GET /en/event/lietuvos-rytas-unics-kazan/c58b1f18-8852-458a-a642-2da01a165f2a HTTP/1.1" 200 59017
> DEBUG [1542137425.4072893] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://global-api.svcs.eurosportplayer.com/token'
> DEBUG [1542137425.4106977] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): global-api.svcs.eurosportplayer.com:443
> DEBUG [1542137425.8771644] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://global-api.svcs.eurosportplayer.com:443 "POST /token HTTP/1.1" 200 None
> DEBUG [1542137425.8816676] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://eu-west-1-api.svcs.eurosportplayer.com/v2/user/identity'
> DEBUG [1542137425.8829796] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): eu-west-1-api.svcs.eurosportplayer.com:443
> DEBUG [1542137426.239034] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://eu-west-1-api.svcs.eurosportplayer.com:443 "POST /v2/user/identity HTTP/1.1" 200 None
> DEBUG [1542137426.2526507] /usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://global-api.svcs.eurosportplayer.com/token'
> DEBUG [1542137426.3596723] /home/raffaele/.local/lib/python3.6/site-packages/urllib3/connectionpool.py/_make_request: https://global-api.svcs.eurosportplayer.com:443 "POST /token HTTP/1.1" 406 76
> Traceback (most recent call last):
>   File "/usr/local/bin/svtplay-dl", line 4, in <module>
>     __import__('pkg_resources').run_script('svtplay-dl==2.1+9.ga65a322', 'svtplay-dl')
>   File "/home/raffaele/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/raffaele/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
>     exec(code, namespace, namespace)
>   File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
>     svtplay_dl.main()
>   File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/__init__.py", line 64, in main
>     get_media(urls[0], config, __version__)
>   File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/getmedia.py", line 58, in get_media
>     get_one_media(stream)
>   File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
>     for i in streams:
>   File "/usr/local/lib/python3.6/dist-packages/svtplay_dl-2.1+9.ga65a322-py3.6.egg/svtplay_dl/service/eurosport.py", line 44, in get
>     refresh = res.json()["refresh_token"]
>   File "/home/raffaele/.local/lib/python3.6/site-packages/requests/models.py", line 896, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
>     obj, end = self.raw_decode(s)
>   File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
>     return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>

**Comment by spaam** [comment]
latest master have a fix for this :)
